{
  "abstract": [
    {
      "text": "An object that specifies what subscriber account information your app retrieves.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VSAccountMetadataRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VSAccountMetadataRequest"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VSAccountMetadataRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "VSAccountMetadataRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "VSAccountMetadataRequest",
              "type": "codeVoice"
            },
            {
              "text": " object to indicate the specific information your app will obtain about a subscriber from their subscription provider. Also, use this object to provide information to the subscription provider that it needs to perform the request, such as a verification token, the authentication schemes your app supports, or your app’s identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager/enqueue(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Submits a request for subscriber account information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSAccountMetadataRequest",
          "text": "VSAccountMetadataRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSAccountMetadata",
          "text": "VSAccountMetadata"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSAccountManagerResult",
          "text": "VSAccountManagerResult"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager/enqueue(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueAccountMetadataRequest:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueue(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmanager/enqueue(_:completionhandler:)"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManagerResult": {
      "abstract": [
        {
          "text": "An object that represents a request made for subscriber account information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountManagerResult"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManagerResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountManagerResult"
        }
      ],
      "role": "symbol",
      "title": "VSAccountManagerResult",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmanagerresult"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadata": {
      "abstract": [
        {
          "text": "A collection of information for a subscriber’s account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountMetadata"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountMetadata"
        }
      ],
      "role": "symbol",
      "title": "VSAccountMetadata",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadata"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest": {
      "abstract": [
        {
          "text": "An object that specifies what subscriber account information your app retrieves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountMetadataRequest"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountMetadataRequest"
        }
      ],
      "role": "symbol",
      "title": "VSAccountMetadataRequest",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/accountProviderAuthenticationToken": {
      "abstract": [
        {
          "text": "An authentication session token that your app sends to the account provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountProviderAuthenticationToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/accountProviderAuthenticationToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accountProviderAuthenticationToken"
        }
      ],
      "role": "symbol",
      "title": "accountProviderAuthenticationToken",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/accountproviderauthenticationtoken"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders": {
      "abstract": [
        {
          "text": "An array of application-specific providers to add to the list of account providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationAccountProviders"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSAccountApplicationProvider",
          "text": "VSAccountApplicationProvider"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationAccountProviders"
        }
      ],
      "role": "symbol",
      "title": "applicationAccountProviders",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/applicationaccountproviders"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/attributeNames": {
      "abstract": [
        {
          "text": "The SAML attributes that your app sends to the account provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/attributeNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributeNames"
        }
      ],
      "role": "symbol",
      "title": "attributeNames",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/attributenames"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/channelIdentifier": {
      "abstract": [
        {
          "text": "The channel identifier for the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/channelIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelIdentifier"
        }
      ],
      "role": "symbol",
      "title": "channelIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/channelidentifier"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers": {
      "abstract": [
        {
          "text": "The providers your app lists prominently during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featuredAccountProviderIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featuredAccountProviderIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "featuredAccountProviderIdentifiers",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/featuredaccountprovideridentifiers"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app ignores cached credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceAuthentication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "forceAuthentication"
        }
      ],
      "role": "symbol",
      "title": "forceAuthentication",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/forceauthentication"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAccountProviderIdentifier": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app requests the identifier of the account provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includeAccountProviderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAccountProviderIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includeAccountProviderIdentifier"
        }
      ],
      "role": "symbol",
      "title": "includeAccountProviderIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/includeaccountprovideridentifier"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAuthenticationExpirationDate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app requests the expiration date of the user’s current authentication session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includeAuthenticationExpirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAuthenticationExpirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includeAuthenticationExpirationDate"
        }
      ],
      "role": "symbol",
      "title": "includeAuthenticationExpirationDate",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/includeauthenticationexpirationdate"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can prompt the user to authenticate to complete the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInterruptionAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interruptionAllowed"
        }
      ],
      "role": "symbol",
      "title": "isInterruptionAllowed",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/isinterruptionallowed"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle": {
      "abstract": [
        {
          "text": "A short, user-presentable name for the video that the user wants to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedVideoTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedVideoTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedVideoTitle",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/localizedvideotitle"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAccountProviderIdentifiers": {
      "abstract": [
        {
          "text": "A list of identifiers for TV providers that your app supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedAccountProviderIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAccountProviderIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedAccountProviderIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "supportedAccountProviderIdentifiers",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/supportedaccountprovideridentifiers"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAuthenticationSchemes": {
      "abstract": [
        {
          "text": "A collection of authentication schemes your app supports for this request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedAuthenticationSchemes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VSAccountProviderAuthenticationScheme",
          "text": "VSAccountProviderAuthenticationScheme"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAuthenticationSchemes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedAuthenticationSchemes"
        }
      ],
      "role": "symbol",
      "title": "supportedAuthenticationSchemes",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/supportedauthenticationschemes"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/verificationToken": {
      "abstract": [
        {
          "text": "A token that your app sends to an account provider to identify itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verificationToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/verificationToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verificationToken"
        }
      ],
      "role": "symbol",
      "title": "verificationToken",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountmetadatarequest/verificationtoken"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderAuthenticationScheme": {
      "abstract": [
        {
          "text": "Authentication schemes for account provider requests and responses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountProviderAuthenticationScheme"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderAuthenticationScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountProviderAuthenticationScheme"
        }
      ],
      "role": "symbol",
      "title": "VSAccountProviderAuthenticationScheme",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountproviderauthenticationscheme"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderResponse": {
      "abstract": [
        {
          "text": "An object that contains the response from the account provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSAccountProviderResponse"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSAccountProviderResponse"
        }
      ],
      "role": "symbol",
      "title": "VSAccountProviderResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsaccountproviderresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enqueuing-Requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager/enqueue(_:completionHandler:)",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadata",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManagerResult",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderAuthenticationScheme"
      ],
      "title": "Enqueuing Requests"
    }
  ],
  "topicSections": [
    {
      "anchor": "Requesting-TV-Provider-Info",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAccountProviderIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAuthenticationExpirationDate"
      ],
      "title": "Requesting TV Provider Info"
    },
    {
      "anchor": "Requesting-App-Level-Authentication",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/attributeNames",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/channelIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAccountProviderIdentifiers",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAuthenticationSchemes",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/verificationToken"
      ],
      "title": "Requesting App-Level Authentication"
    },
    {
      "anchor": "Specifying-Additional-Options",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders"
      ],
      "title": "Specifying Additional Options"
    },
    {
      "anchor": "Supporting-Authentication-Share",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/accountProviderAuthenticationToken"
      ],
      "title": "Supporting Authentication Share"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VSAccountMetadataRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Requesting-TV-Provider-Info",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAccountProviderIdentifier",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/includeAuthenticationExpirationDate"
              ],
              "title": "Requesting TV Provider Info"
            },
            {
              "anchor": "Requesting-App-Level-Authentication",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/attributeNames",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/channelIdentifier",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAccountProviderIdentifiers",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/supportedAuthenticationSchemes",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/verificationToken"
              ],
              "title": "Requesting App-Level Authentication"
            },
            {
              "anchor": "Specifying-Additional-Options",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/isInterruptionAllowed",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/featuredAccountProviderIdentifiers",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/forceAuthentication",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/localizedVideoTitle",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/applicationAccountProviders"
              ],
              "title": "Specifying Additional Options"
            },
            {
              "anchor": "Supporting-Authentication-Share",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadataRequest/accountProviderAuthenticationToken"
              ],
              "title": "Supporting Authentication Share"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enqueuing-Requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManager/enqueue(_:completionHandler:)",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountMetadata",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountManagerResult",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderResponse",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSAccountProviderAuthenticationScheme"
              ],
              "title": "Enqueuing Requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VSAccountMetadataRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1isInterruptionAllowed/title",
          "value": "interruptionAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1isInterruptionAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interruptionAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1includeAuthenticationExpirationDate/title",
          "value": "includeAuthenticationExpirationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1includeAuthenticationExpirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includeAuthenticationExpirationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManager~1enqueue(_:completionHandler:)/title",
          "value": "enqueueAccountMetadataRequest:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManager~1enqueue(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueAccountMetadataRequest:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1supportedAccountProviderIdentifiers/title",
          "value": "supportedAccountProviderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1supportedAccountProviderIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedAccountProviderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1forceAuthentication/title",
          "value": "forceAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1forceAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "forceAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountProviderAuthenticationScheme/title",
          "value": "VSAccountProviderAuthenticationScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountProviderAuthenticationScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountProviderAuthenticationScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountProviderAuthenticationScheme/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountProviderAuthenticationScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManagerResult/title",
          "value": "VSAccountManagerResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManagerResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountManagerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountManagerResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountManagerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1applicationAccountProviders/title",
          "value": "applicationAccountProviders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1applicationAccountProviders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationAccountProviders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1supportedAuthenticationSchemes/title",
          "value": "supportedAuthenticationSchemes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1supportedAuthenticationSchemes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedAuthenticationSchemes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1includeAccountProviderIdentifier/title",
          "value": "includeAccountProviderIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1includeAccountProviderIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includeAccountProviderIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountProviderResponse/title",
          "value": "VSAccountProviderResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountProviderResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountProviderResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountProviderResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountProviderResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1localizedVideoTitle/title",
          "value": "localizedVideoTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1localizedVideoTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedVideoTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1channelIdentifier/title",
          "value": "channelIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1channelIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1featuredAccountProviderIdentifiers/title",
          "value": "featuredAccountProviderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1featuredAccountProviderIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featuredAccountProviderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1verificationToken/title",
          "value": "verificationToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1verificationToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verificationToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1attributeNames/title",
          "value": "attributeNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1attributeNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributeNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadata/title",
          "value": "VSAccountMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1accountProviderAuthenticationToken/title",
          "value": "accountProviderAuthenticationToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest~1accountProviderAuthenticationToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accountProviderAuthenticationToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest/title",
          "value": "VSAccountMetadataRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSAccountMetadataRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSAccountMetadataRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vsaccountmetadatarequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videosubscriberaccount/vsaccountmetadatarequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
