{
  "abstract": [
    {
      "text": "Error information in the framework error domain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11VSErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VSError"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VSError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VSError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VSError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/customnserror/2946828-errorcode": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorCode"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/customnserror/2946828-errorcode",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorCode",
      "type": "topic",
      "url": "/documentation/foundation/customnserror/2946828-errorcode"
    },
    "doc://com.apple.documentation/documentation/foundation/customnserror/3017373-erroruserinfo": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorUserInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/customnserror/3017373-erroruserinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorUserInfo",
      "type": "topic",
      "url": "/documentation/foundation/customnserror/3017373-erroruserinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError": {
      "abstract": [
        {
          "text": "Error information in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "role": "symbol",
      "title": "VSError",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code": {
      "abstract": [
        {
          "text": "Error codes in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/accessNotGranted": {
      "abstract": [
        {
          "text": "The user hasn’t granted access to their subscription information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessNotGranted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/accessNotGranted",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessNotGranted",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/accessnotgranted"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/errordomain"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/invalidVerificationToken": {
      "abstract": [
        {
          "text": "The user’s subscription provider rejected the verification token that the app sent with the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVerificationToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/invalidVerificationToken",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVerificationToken",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/invalidverificationtoken"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/providerRejected": {
      "abstract": [
        {
          "text": "The user’s subscription provider didn’t allow the request to proceed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerRejected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/providerRejected",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerRejected",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/providerrejected"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/rejected": {
      "abstract": [
        {
          "text": "The system rejected the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rejected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/rejected",
      "kind": "symbol",
      "role": "symbol",
      "title": "rejected",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/rejected"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/serviceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "The request failed due to a timeout or unreachable host, but a subsequent attempt might succeed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceTemporarilyUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/serviceTemporarilyUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "serviceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/servicetemporarilyunavailable"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupported": {
      "abstract": [
        {
          "text": "The provider doesn’t support the feature the user requested in the device’s current region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupported",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/unsupported"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupportedProvider": {
      "abstract": [
        {
          "text": "The system doesn’t support the user’s subscription provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupportedProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedProvider",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/unsupportedprovider"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/userCancelled": {
      "abstract": [
        {
          "text": "The user canceled the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/userCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCancelled",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/usercancelled"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain": {
      "abstract": [
        {
          "text": "The domain for all errors in the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "VSErrorDomain",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrordomain"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse": {
      "abstract": [
        {
          "text": "The account provider’s error-response object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyAccountProviderResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyAccountProviderResponse"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeyAccountProviderResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeyaccountproviderresponse"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse": {
      "abstract": [
        {
          "text": "The subscription provider’s SAML error response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponse"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeySAMLResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeysamlresponse"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus": {
      "abstract": [
        {
          "text": "The subscription provider’s SAML error-response status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponseStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeySAMLResponseStatus",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeysamlresponsestatus"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the unsupported subscription provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeyUnsupportedProviderIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeyunsupportedprovideridentifier"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Information",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/customnserror/2946828-errorcode",
        "doc://com.apple.documentation/documentation/foundation/customnserror/3017373-erroruserinfo"
      ],
      "title": "Error Information"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/accessNotGranted",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/invalidVerificationToken",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/providerRejected",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/rejected",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/serviceTemporarilyUnavailable",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupported",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupportedProvider",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/userCancelled",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/title",
          "value": "VSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorDomain/title",
          "value": "VSErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponseStatus/title",
          "value": "VSErrorInfoKeySAMLResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeySAMLResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyUnsupportedProviderIdentifier/title",
          "value": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyUnsupportedProviderIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponse/title",
          "value": "VSErrorInfoKeySAMLResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeySAMLResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyAccountProviderResponse/title",
          "value": "VSErrorInfoKeyAccountProviderResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyAccountProviderResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeyAccountProviderResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vserror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
