{
  "abstract": [
    {
      "text": "An object that represents a user’s account.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:22VideoSubscriberAccount06VSUserC0V",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VSUserAccount"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VSUserAccount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VSUserAccount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VSUserAccount"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are two sources for a ",
              "type": "text"
            },
            {
              "code": "VSUserAccount",
              "type": "codeVoice"
            },
            {
              "text": " instance:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You create an instance when a person registers a new account or signs into an existing account in your app, and you call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/update(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with the instance.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You fetch user accounts by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/userAccounts(options:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", which can return user accounts created on the current device, or user accounts registered on all the devices signed into the user’s iCloud account.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct": {
      "abstract": [
        {
          "text": "An object that represents a user’s account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccount"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccount",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/AccountType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that represent whether a user has access to paid content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccountType"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/AccountType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccountType"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccount.AccountType",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/accounttype-swift.enum"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/OriginatingDeviceCategory": {
      "abstract": [
        {
          "text": "Constants that represent whether the device from which the user originally registered is mobile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OriginatingDeviceCategory"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/OriginatingDeviceCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OriginatingDeviceCategory"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccount.OriginatingDeviceCategory",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/originatingdevicecategory"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/accountProviderIdentifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a provider known to Apple that provides the user account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountProviderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/accountProviderIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "accountProviderIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/accountprovideridentifier"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/accountType-swift.property": {
      "abstract": [
        {
          "text": "A constant that represents whether a user has access to paid content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
          "text": "VSUserAccount"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V0C4TypeO",
          "text": "AccountType"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/accountType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "accountType",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/accounttype-swift.property"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/appleSubscription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleSubscription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount19VSAppleSubscriptionV",
          "text": "VSAppleSubscription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/appleSubscription",
      "kind": "symbol",
      "role": "symbol",
      "title": "appleSubscription",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/applesubscription"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/authenticationData": {
      "abstract": [
        {
          "text": "A string that represents an authentication token for the user account to authenticate with a provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/authenticationData",
      "kind": "symbol",
      "role": "symbol",
      "title": "authenticationData",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/authenticationdata"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/billingIdentifier": {
      "abstract": [
        {
          "text": "A string that Identifies the billing group associated with the user account’s subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/billingIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "billingIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/billingidentifier"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/deviceCategory": {
      "abstract": [
        {
          "text": "A constant that indicates whether the device from which the user registered is mobile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
          "text": "VSUserAccount"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V25OriginatingDeviceCategoryO",
          "text": "OriginatingDeviceCategory"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/deviceCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceCategory",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/devicecategory"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/identifier": {
      "abstract": [
        {
          "text": "A string you provide that uniquely identifies the account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/identifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/identifier"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/init(accountType:updateURL:)": {
      "abstract": [
        {
          "text": "Creates a user account object with a URL for account update requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "accountType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
          "text": "VSUserAccount"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V0C4TypeO",
          "text": "AccountType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updateURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/init(accountType:updateURL:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(accountType:updateURL:)",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/init(accounttype:updateurl:)"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/isFromCurrentDevice": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user originated their account on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFromCurrentDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/isFromCurrentDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "isFromCurrentDevice",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/isfromcurrentdevice"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/isSignedOut": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user has signed out of their account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSignedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/isSignedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSignedOut",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/issignedout"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/requiresSystemTrust": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the update URL must have a system-trusted certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresSystemTrust"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/requiresSystemTrust",
      "kind": "symbol",
      "role": "symbol",
      "title": "requiresSystemTrust",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/requiressystemtrust"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/subscriptionBillingCycleEndDate": {
      "abstract": [
        {
          "text": "A date that indicates when the billing cycle ends for a paid account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionBillingCycleEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/subscriptionBillingCycleEndDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscriptionBillingCycleEndDate",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/subscriptionbillingcycleenddate"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/tierIdentifiers": {
      "abstract": [
        {
          "text": "An array of strings that identify a subset of content from your catalog that the subscriber can play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tierIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/tierIdentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "tierIdentifiers",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/tieridentifiers"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/updateURL": {
      "abstract": [
        {
          "text": "A URL that points to the application’s JavaScript endpoint for update requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/updateURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateURL",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccount-swift.struct/updateurl"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager": {
      "abstract": [
        {
          "text": "The object that coordinates your app’s user account actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSUserAccountManager"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSUserAccountManager"
        }
      ],
      "role": "symbol",
      "title": "VSUserAccountManager",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/update(_:)": {
      "abstract": [
        {
          "text": "Registers a new user account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
          "text": "VSUserAccount"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/update(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "update(_:)",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager/update(_:)"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/userAccounts(options:)": {
      "abstract": [
        {
          "text": "Returns a list of registered user accounts for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userAccounts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VSUserAccountManager",
          "text": "VSUserAccountManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSUserAccountQueryOptions",
          "text": "QueryOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22VideoSubscriberAccount06VSUserC0V",
          "text": "VSUserAccount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager/userAccounts(options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "userAccounts(options:)",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vsuseraccountmanager/useraccounts(options:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-account-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccountManager"
      ],
      "title": "User account management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-user-accounts",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/init(accountType:updateURL:)",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/AccountType-swift.enum"
      ],
      "title": "Creating user accounts"
    },
    {
      "anchor": "User-account-information",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/accountProviderIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/accountType-swift.property",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/authenticationData",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/billingIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/deviceCategory",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/OriginatingDeviceCategory",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/identifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/isFromCurrentDevice",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/isSignedOut",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/requiresSystemTrust",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/subscriptionBillingCycleEndDate",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/tierIdentifiers",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/updateURL"
      ],
      "title": "User account information"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSUserAccount-swift.struct/appleSubscription"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/title",
          "value": "VSUserAccountManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSUserAccountManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSUserAccountManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vsuseraccount-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
