{
  "abstract": [
    {
      "text": "The user activities with the watch that can impact the temperature measurement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:@E@SRWristTemperatureCondition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Condition"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Condition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SRWristTemperature.Condition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Condition"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature": {
      "abstract": [
        {
          "text": "The temperature of the user’s wrist while the user sleeps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "role": "symbol",
      "title": "SRWristTemperature",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct": {
      "abstract": [
        {
          "text": "The user activities with the watch that can impact the temperature measurement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "role": "symbol",
      "title": "SRWristTemperature.Condition",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion": {
      "abstract": [
        {
          "text": "The watch being in motion impacts the accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inMotion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionInMotion"
        }
      ],
      "role": "symbol",
      "title": "inMotion",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/inmotion"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates and returns a new structure with the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist": {
      "abstract": [
        {
          "text": "The watch being off the wrist impacts the accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offWrist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionOffWrist"
        }
      ],
      "role": "symbol",
      "title": "offWrist",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/offwrist"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger": {
      "abstract": [
        {
          "text": "The watch being on the charger impacts the accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onCharger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionOnCharger"
        }
      ],
      "role": "symbol",
      "title": "onCharger",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.struct/oncharger"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/condition-swift.property": {
      "abstract": [
        {
          "text": "The condition of the measurement that impacts its accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRWristTemperature",
          "text": "SRWristTemperature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRWristTemperatureCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/condition-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "condition"
        }
      ],
      "role": "symbol",
      "title": "condition",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperature/condition-swift.property"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureCondition/SRWristTemperatureConditionNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SRWristTemperatureConditionNone"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureCondition/SRWristTemperatureConditionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRWristTemperatureConditionNone",
      "type": "topic",
      "url": "/documentation/sensorkit/srwristtemperaturecondition/srwristtemperatureconditionnone"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-the-accuracy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/condition-swift.property"
      ],
      "title": "Determining the accuracy"
    }
  ],
  "topicSections": [
    {
      "anchor": "Conditions",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion"
      ],
      "title": "Conditions"
    },
    {
      "anchor": "Creating-conditions",
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/init(rawValue:)"
      ],
      "title": "Creating conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRWristTemperatureCondition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Conditions",
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/offWrist",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/onCharger",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/Condition-swift.struct/inMotion"
              ],
              "title": "Conditions"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperatureCondition/SRWristTemperatureConditionNone"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-the-accuracy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/condition-swift.property"
              ],
              "title": "Determining the accuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRWristTemperatureCondition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct/title",
          "value": "SRWristTemperatureCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1onCharger/title",
          "value": "SRWristTemperatureConditionOnCharger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1onCharger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionOnCharger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1offWrist/title",
          "value": "SRWristTemperatureConditionOffWrist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1offWrist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionOffWrist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/title",
          "value": "SRWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1condition-swift.property/title",
          "value": "condition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1condition-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "condition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1inMotion/title",
          "value": "SRWristTemperatureConditionInMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1Condition-swift.struct~1inMotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRWristTemperatureConditionInMotion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srwristtemperature/condition-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srwristtemperature/condition-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
