{"metadata":{"symbolKind":"property","platforms":[{"introducedAt":"17.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"17.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"17.0","name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false}],"roleHeading":"Instance Property","externalID":"c:objc(cs)SRWristTemperature(py)value","navigatorTitle":[{"kind":"identifier","text":"value"}],"role":"symbol","title":"value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation11MeasurementV","kind":"typeIdentifier","text":"Measurement"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSUnitTemperature","kind":"typeIdentifier","text":"UnitTemperature"},{"kind":"text","text":">"}],"modules":[{"name":"SensorKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/value","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/sensorkit/srwristtemperature/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/sensorkit/srwristtemperature/value"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature"]]},"seeAlsoSections":[{"anchor":"Getting-temperature-information","identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/timestamp","doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/errorEstimate"],"title":"Getting temperature information","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation11MeasurementV","kind":"typeIdentifier","text":"Measurement","identifier":"doc://com.externally.resolved.symbol/s:10Foundation11MeasurementV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSUnitTemperature","kind":"typeIdentifier","text":"UnitTemperature","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSUnitTemperature"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"The temperature sensor value in celsius."}],"references":{"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature","title":"SRWristTemperature","abstract":[{"text":"The temperature of the user’s wrist while the user sleeps.","type":"text"}],"url":"/documentation/sensorkit/srwristtemperature","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRWristTemperature","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SRWristTemperature","kind":"identifier"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/errorEstimate":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/errorEstimate","title":"errorEstimate","abstract":[{"text":"An estimate of the amount of error in the temperature measurement.","type":"text"}],"url":"/documentation/sensorkit/srwristtemperature/errorestimate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorEstimate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation11MeasurementV","text":"Measurement","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUnitTemperature","text":"UnitTemperature","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"errorEstimate","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSUnitTemperature":{"url":"/documentation/foundation/unittemperature","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"UnitTemperature"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSUnitTemperature","title":"UnitTemperature","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A unit of measure for temperature.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies"},"doc://com.apple.sensorkit/documentation/SensorKit":{"type":"topic","title":"SensorKit","abstract":[{"type":"text","text":"Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch."}],"url":"/documentation/sensorkit","role":"collection","identifier":"doc://com.apple.sensorkit/documentation/SensorKit","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/value":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/value","title":"value","abstract":[{"text":"The temperature sensor value in celsius.","type":"text"}],"url":"/documentation/sensorkit/srwristtemperature/value","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation11MeasurementV","text":"Measurement","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUnitTemperature","text":"UnitTemperature","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"value","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:10Foundation11MeasurementV":{"type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation11MeasurementV","fragments":[{"text":"struct ","kind":"text"},{"text":"Measurement","kind":"identifier"}],"title":"Measurement","abstract":[{"type":"text","text":"A numeric quantity labeled with a unit of measure, with support for unit conversion and unit-aware calculations. "}],"role":"symbol","url":"/documentation/foundation/measurement"},"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/timestamp":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/timestamp","title":"timestamp","abstract":[{"text":"The date and time when the device records the temperature.","type":"text"}],"url":"/documentation/sensorkit/srwristtemperature/timestamp","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"timestamp","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"17.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"17.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"17.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"value","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/timestamp","doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature/errorEstimate"],"title":"Getting temperature information","generated":true,"anchor":"Getting-temperature-information"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSMeasurement<NSUnitTemperature *>","preciseIdentifier":"c:Q$objc(cs)NSMeasurement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"value"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/title","value":"SRWristTemperature"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/fragments","value":[{"text":"SRWristTemperature","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/navigatorTitle","value":[{"text":"SRWristTemperature","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1errorEstimate/title","value":"errorEstimate","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1errorEstimate/fragments","value":[{"text":"errorEstimate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSUnitTemperature/title","value":"NSUnitTemperature","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1value/title","value":"value","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1value/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1timestamp/title","value":"timestamp","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature~1timestamp/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}