{
  "abstract": [
    {
      "text": "A constant that represents the left button on a remote.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIRemoteButton@XCUIRemoteButtonLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "left"
      }
    ],
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIRemoteButtonLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.3",
        "name": "Xcode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "XCUIRemoteButton.left"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "left"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton": {
      "abstract": [
        {
          "text": "A button on a physical remote control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIRemoteButton"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButton"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down": {
      "abstract": [
        {
          "text": "A constant that represents the down button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonDown"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.down",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/down"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors": {
      "abstract": [
        {
          "text": "A constant that represents the color functions button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fourColors"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonFourColors"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.fourColors",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/fourcolors"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide": {
      "abstract": [
        {
          "text": "A constant that represents the guide button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guide"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonGuide"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.guide",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/guide"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home": {
      "abstract": [
        {
          "text": "A constant that represents the home button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonHome"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.home",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/home"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left": {
      "abstract": [
        {
          "text": "A constant that represents the left button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonLeft"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.left",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/left"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu": {
      "abstract": [
        {
          "text": "A constant that represents the menu button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonMenu"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.menu",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/menu"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree": {
      "abstract": [
        {
          "text": "A constant that represents the channel-tuning button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTwoThree"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonOneTwoThree"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.oneTwoThree",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/onetwothree"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown": {
      "abstract": [
        {
          "text": "A constant that represents the page down button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageDown"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonPageDown"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.pageDown",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/pagedown"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp": {
      "abstract": [
        {
          "text": "A constant that represents the page up button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageUp"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonPageUp"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.pageUp",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/pageup"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause": {
      "abstract": [
        {
          "text": "A constant that represents the play-and-pause button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playPause"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonPlayPause"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.playPause",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/playpause"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right": {
      "abstract": [
        {
          "text": "A constant that represents the right button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonRight"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.right",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/right"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select": {
      "abstract": [
        {
          "text": "A constant that represents the select button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "select"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonSelect"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.select",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/select"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider": {
      "abstract": [
        {
          "text": "A constant that represents the TV provider button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvProvider"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonTVProvider"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.tvProvider",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/tvprovider"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up": {
      "abstract": [
        {
          "text": "A constant that represents the up button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonUp"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.up",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/up"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Remote-buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider"
      ],
      "title": "Remote buttons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.3",
              "name": "Xcode",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIRemoteButtonLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Remote-buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider"
              ],
              "title": "Remote buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCUIRemoteButtonLeft"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1right/title",
          "value": "XCUIRemoteButtonRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageDown/title",
          "value": "XCUIRemoteButtonPageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonPageDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1home/title",
          "value": "XCUIRemoteButtonHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton/title",
          "value": "XCUIRemoteButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1oneTwoThree/title",
          "value": "XCUIRemoteButtonOneTwoThree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1oneTwoThree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonOneTwoThree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1menu/title",
          "value": "XCUIRemoteButtonMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1fourColors/title",
          "value": "XCUIRemoteButtonFourColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1fourColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonFourColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1select/title",
          "value": "XCUIRemoteButtonSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1select/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1left/title",
          "value": "XCUIRemoteButtonLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1guide/title",
          "value": "XCUIRemoteButtonGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1guide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1up/title",
          "value": "XCUIRemoteButtonUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1playPause/title",
          "value": "XCUIRemoteButtonPlayPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1playPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonPlayPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageUp/title",
          "value": "XCUIRemoteButtonPageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonPageUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1down/title",
          "value": "XCUIRemoteButtonDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1tvProvider/title",
          "value": "XCUIRemoteButtonTVProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1tvProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonTVProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation/xcuiremotebutton/left"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcuiautomation/xcuiremotebutton/left"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
