{
  "abstract": [
    {
      "text": "Properties of an event that indicates a change to a process’s working directory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chdir"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UA@es_events_t@FI@chdir",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "chdir"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_event_chdir_t",
        "text": "es_event_chdir_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "chdir"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "chdir"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "chdir"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_chdir_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_event_chdir_t",
              "text": "es_event_chdir_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_chdir_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates a change to a process’s working directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_chdir_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_chdir_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_chdir_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_chdir_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_chdir_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t": {
      "abstract": [
        {
          "text": "A C union of event-specific types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "role": "symbol",
      "title": "es_events_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chdir": {
      "abstract": [
        {
          "text": "Properties of an event that indicates a change to a process’s working directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chdir"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_chdir_t",
          "text": "es_event_chdir_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chdir",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chdir"
        }
      ],
      "role": "symbol",
      "title": "chdir",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/chdir"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chroot": {
      "abstract": [
        {
          "text": "Properties of an event that indicates a change to a process’s root directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chroot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_chroot_t",
          "text": "es_event_chroot_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chroot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chroot"
        }
      ],
      "role": "symbol",
      "title": "chroot",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/chroot"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exec": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the execution of a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_exec_t",
          "text": "es_event_exec_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exec"
        }
      ],
      "role": "symbol",
      "title": "exec",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/exec"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exit": {
      "abstract": [
        {
          "text": "Properties of an event that indicates a process exiting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_exit_t",
          "text": "es_event_exit_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exit"
        }
      ],
      "role": "symbol",
      "title": "exit",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/exit"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fork": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the forking of a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_fork_t",
          "text": "es_event_fork_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fork"
        }
      ],
      "role": "symbol",
      "title": "fork",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/fork"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/proc_check": {
      "abstract": [
        {
          "text": "Properties of an event that indicate the retrieval of process information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proc_check"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_proc_check_t",
          "text": "es_event_proc_check_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/proc_check",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "proc_check"
        }
      ],
      "role": "symbol",
      "title": "proc_check",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/proc_check"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/signal": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the sending of a signal to a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_signal_t",
          "text": "es_event_signal_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/signal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signal"
        }
      ],
      "role": "symbol",
      "title": "signal",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/signal"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Process-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chroot",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exec",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fork",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/proc_check",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/signal",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exit"
      ],
      "title": "Process Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "chdir"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chdir"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Process-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/chroot",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exec",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fork",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/proc_check",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/signal",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exit"
              ],
              "title": "Process Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_chdir_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@es_event_chdir_t",
                    "text": "es_event_chdir_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "chdir"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1exec/title",
          "value": "exec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1exec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1chdir/title",
          "value": "chdir"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1chdir/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chdir"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1exit/title",
          "value": "exit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1exit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1proc_check/title",
          "value": "proc_check"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1proc_check/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "proc_check"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1signal/title",
          "value": "signal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1signal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1chroot/title",
          "value": "chroot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1chroot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chroot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_chdir_t/title",
          "value": "es_event_chdir_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_chdir_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_chdir_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_chdir_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_chdir_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/title",
          "value": "es_events_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1fork/title",
          "value": "fork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1fork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fork"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_events_t/chdir"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_events_t/chdir"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
