{
  "abstract": [
    {
      "text": "Properties of an event that indicates the cloning of a file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/copyfile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UA@es_events_t@FI@copyfile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "copyfile"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_event_copyfile_t",
        "text": "es_event_copyfile_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "copyfile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "copyfile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "copyfile"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_event_copyfile_t",
              "text": "es_event_copyfile_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the copying of a file by use of a system call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_copyfile_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_copyfile_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_copyfile_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_copyfile_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t": {
      "abstract": [
        {
          "text": "A C union of event-specific types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "role": "symbol",
      "title": "es_events_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/access": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the checking of a file’s access permission.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "access"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_access_t",
          "text": "es_event_access_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/access",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "access"
        }
      ],
      "role": "symbol",
      "title": "access",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/access"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/clone": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the cloning of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_clone_t",
          "text": "es_event_clone_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/clone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clone"
        }
      ],
      "role": "symbol",
      "title": "clone",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/clone"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/close": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the closing of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "close"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_close_t",
          "text": "es_event_close_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/close",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "role": "symbol",
      "title": "close",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/close"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/copyfile": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the cloning of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_copyfile_t",
          "text": "es_event_copyfile_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/copyfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyfile"
        }
      ],
      "role": "symbol",
      "title": "copyfile",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/copyfile"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/create": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the creation of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "create"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_create_t",
          "text": "es_event_create_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/create",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "create"
        }
      ],
      "role": "symbol",
      "title": "create",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/create"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/dup": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the duplication of a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_dup_t",
          "text": "es_event_dup_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/dup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dup"
        }
      ],
      "role": "symbol",
      "title": "dup",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/dup"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exchangedata": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the exchange of data between two files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exchangedata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_exchangedata_t",
          "text": "es_event_exchangedata_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exchangedata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exchangedata"
        }
      ],
      "role": "symbol",
      "title": "exchangedata",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/exchangedata"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fcntl": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the manipulation of a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fcntl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_fcntl_t",
          "text": "es_event_fcntl_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fcntl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fcntl"
        }
      ],
      "role": "symbol",
      "title": "fcntl",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/fcntl"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/lookup": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the lookup of a file’s path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_lookup_t",
          "text": "es_event_lookup_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/lookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookup"
        }
      ],
      "role": "symbol",
      "title": "lookup",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/lookup"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/open": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the opening of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_open_t",
          "text": "es_event_open_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/open",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "open"
        }
      ],
      "role": "symbol",
      "title": "open",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/open"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/rename": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the renaming of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_rename_t",
          "text": "es_event_rename_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/rename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rename"
        }
      ],
      "role": "symbol",
      "title": "rename",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/rename"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/searchfs": {
      "abstract": [
        {
          "text": "Properties of an event that indicates a search operation on a volume or mounted file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchfs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_searchfs_t",
          "text": "es_event_searchfs_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/searchfs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchfs"
        }
      ],
      "role": "symbol",
      "title": "searchfs",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/searchfs"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/truncate": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the truncation of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "truncate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_truncate_t",
          "text": "es_event_truncate_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/truncate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "truncate"
        }
      ],
      "role": "symbol",
      "title": "truncate",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/truncate"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/write": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the writing of data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_write_t",
          "text": "es_event_write_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/write",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "write"
        }
      ],
      "role": "symbol",
      "title": "write",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/write"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-System-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/access",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/clone",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/close",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/create",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/dup",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exchangedata",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fcntl",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/open",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/rename",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/write",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/truncate",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/lookup",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/searchfs"
      ],
      "title": "File-System Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "copyfile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "copyfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-System-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/access",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/clone",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/close",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/create",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/dup",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/exchangedata",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fcntl",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/open",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/rename",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/write",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/truncate",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/lookup",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/searchfs"
              ],
              "title": "File-System Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_copyfile_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@es_event_copyfile_t",
                    "text": "es_event_copyfile_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "copyfile"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1close/title",
          "value": "close"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1close/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "close"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1truncate/title",
          "value": "truncate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1truncate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "truncate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1fcntl/title",
          "value": "fcntl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1fcntl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fcntl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1rename/title",
          "value": "rename"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1rename/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rename"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1access/title",
          "value": "access"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1access/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1dup/title",
          "value": "dup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1dup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1create/title",
          "value": "create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1create/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1searchfs/title",
          "value": "searchfs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1searchfs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchfs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1clone/title",
          "value": "clone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1clone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1write/title",
          "value": "write"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1write/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "write"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/title",
          "value": "es_events_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t/title",
          "value": "es_event_copyfile_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_copyfile_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_copyfile_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1open/title",
          "value": "open"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1open/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "open"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1exchangedata/title",
          "value": "exchangedata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1exchangedata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exchangedata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1lookup/title",
          "value": "lookup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1lookup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1copyfile/title",
          "value": "copyfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1copyfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "copyfile"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_events_t/copyfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_events_t/copyfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
