{
  "abstract": [
    {
      "text": "Properties of an event that indicates the deletion of an extended attribute from a file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/deleteextattr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UA@es_events_t@FI@deleteextattr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deleteextattr"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_event_deleteextattr_t",
        "text": "es_event_deleteextattr_t"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "deleteextattr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "deleteextattr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deleteextattr"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_deleteextattr_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_event_deleteextattr_t",
              "text": "es_event_deleteextattr_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_deleteextattr_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the deletion of an extended attribute from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_deleteextattr_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_deleteextattr_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_deleteextattr_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_deleteextattr_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_deleteextattr_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t": {
      "abstract": [
        {
          "text": "A C union of event-specific types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_events_t"
        }
      ],
      "role": "symbol",
      "title": "es_events_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/deleteextattr": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the deletion of an extended attribute from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteextattr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_deleteextattr_t",
          "text": "es_event_deleteextattr_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/deleteextattr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteextattr"
        }
      ],
      "role": "symbol",
      "title": "deleteextattr",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/deleteextattr"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fsgetpath": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the retrieval of a file-system path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fsgetpath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_fsgetpath_t",
          "text": "es_event_fsgetpath_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fsgetpath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fsgetpath"
        }
      ],
      "role": "symbol",
      "title": "fsgetpath",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/fsgetpath"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getattrlist": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the retrieval of attributes from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getattrlist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_getattrlist_t",
          "text": "es_event_getattrlist_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getattrlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getattrlist"
        }
      ],
      "role": "symbol",
      "title": "getattrlist",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/getattrlist"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getextattr": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the retrieval of an extended attribute from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getextattr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_getextattr_t",
          "text": "es_event_getextattr_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getextattr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getextattr"
        }
      ],
      "role": "symbol",
      "title": "getextattr",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/getextattr"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/listextattr": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the retrieval of multiple extended attributes from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listextattr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_listextattr_t",
          "text": "es_event_listextattr_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/listextattr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listextattr"
        }
      ],
      "role": "symbol",
      "title": "listextattr",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/listextattr"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/readdir": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the reading of a file-system directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readdir"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_readdir_t",
          "text": "es_event_readdir_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/readdir",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readdir"
        }
      ],
      "role": "symbol",
      "title": "readdir",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/readdir"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setacl": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the setting of a file’s access control list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setacl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setacl_t",
          "text": "es_event_setacl_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setacl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setacl"
        }
      ],
      "role": "symbol",
      "title": "setacl",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setacl"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setattrlist": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the setting of an attribute of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setattrlist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setattrlist_t",
          "text": "es_event_setattrlist_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setattrlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setattrlist"
        }
      ],
      "role": "symbol",
      "title": "setattrlist",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setattrlist"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setextattr": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the setting of an extended attribute of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setextattr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setextattr_t",
          "text": "es_event_setextattr_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setextattr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setextattr"
        }
      ],
      "role": "symbol",
      "title": "setextattr",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setextattr"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setflags": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the setting of a file’s flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setflags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setflags_t",
          "text": "es_event_setflags_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setflags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setflags"
        }
      ],
      "role": "symbol",
      "title": "setflags",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setflags"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setmode": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the setting of a file’s mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setmode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setmode_t",
          "text": "es_event_setmode_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setmode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setmode"
        }
      ],
      "role": "symbol",
      "title": "setmode",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setmode"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setowner": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the setting of a file’s owner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setowner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_setowner_t",
          "text": "es_event_setowner_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setowner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setowner"
        }
      ],
      "role": "symbol",
      "title": "setowner",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/setowner"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/stat": {
      "abstract": [
        {
          "text": "Properties of an event that indicates the retrieval of a file’s status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_stat_t",
          "text": "es_event_stat_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/stat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stat"
        }
      ],
      "role": "symbol",
      "title": "stat",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/stat"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/utimes": {
      "abstract": [
        {
          "text": "Properties of an event that indicates a change to a file’s access time or modification time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utimes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_event_utimes_t",
          "text": "es_event_utimes_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/utimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "utimes"
        }
      ],
      "role": "symbol",
      "title": "utimes",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_events_t/utimes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-Metadata-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fsgetpath",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getattrlist",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getextattr",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/listextattr",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/readdir",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setacl",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setattrlist",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setextattr",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setflags",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setmode",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setowner",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/stat",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/utimes"
      ],
      "title": "File Metadata Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "deleteextattr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteextattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-Metadata-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/fsgetpath",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getattrlist",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/getextattr",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/listextattr",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/readdir",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setacl",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setattrlist",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setextattr",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setflags",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setmode",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/setowner",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/stat",
                "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_events_t/utimes"
              ],
              "title": "File Metadata Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_deleteextattr_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@es_event_deleteextattr_t",
                    "text": "es_event_deleteextattr_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "deleteextattr"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_deleteextattr_t/title",
          "value": "es_event_deleteextattr_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_deleteextattr_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_deleteextattr_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_deleteextattr_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_deleteextattr_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/title",
          "value": "es_events_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_events_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1deleteextattr/title",
          "value": "deleteextattr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1deleteextattr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deleteextattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1getextattr/title",
          "value": "getextattr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1getextattr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getextattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setowner/title",
          "value": "setowner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setowner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setowner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setattrlist/title",
          "value": "setattrlist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setattrlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setattrlist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1readdir/title",
          "value": "readdir"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1readdir/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readdir"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1utimes/title",
          "value": "utimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1utimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "utimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1stat/title",
          "value": "stat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1stat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setflags/title",
          "value": "setflags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setflags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setflags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setextattr/title",
          "value": "setextattr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setextattr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setextattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1fsgetpath/title",
          "value": "fsgetpath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1fsgetpath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fsgetpath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1listextattr/title",
          "value": "listextattr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1listextattr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "listextattr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setmode/title",
          "value": "setmode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setmode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setmode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setacl/title",
          "value": "setacl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1setacl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "setacl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1getattrlist/title",
          "value": "getattrlist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_events_t~1getattrlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getattrlist"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_events_t/deleteextattr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/endpointsecurity/es_events_t/deleteextattr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
