{
  "abstract": [
    {
      "text": "Daily situations for a relevance provider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "c:@E@INDailyRoutineSituation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Situation"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Situation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INDailyRoutineRelevanceProvider.Situation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Situation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider": {
      "abstract": [
        {
          "text": "The provider class that specifies a relevant daily routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDailyRoutineRelevanceProvider"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineRelevanceProvider"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum": {
      "abstract": [
        {
          "text": "Daily situations for a relevance provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Situation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Situation"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/activeWorkout": {
      "abstract": [
        {
          "text": "A situation that occurs during an active workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeWorkout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/activeWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationActiveWorkout"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.activeWorkout",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/activeworkout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/commute": {
      "abstract": [
        {
          "text": "A situation that occurs during a daily commute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commute"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/commute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationCommute"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.commute",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/commute"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/evening": {
      "abstract": [
        {
          "text": "A situation that occurs in the evening.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evening"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/evening",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationEvening"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.evening",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/evening"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/gym": {
      "abstract": [
        {
          "text": "A situation that occurs at the gym.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gym"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/gym",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationGym"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.gym",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/gym"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/headphonesConnected": {
      "abstract": [
        {
          "text": "A situation that occurs with connected headphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headphonesConnected"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/headphonesConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationHeadphonesConnected"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.headphonesConnected",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/headphonesconnected"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/home": {
      "abstract": [
        {
          "text": "A situation that occurs at the user’s home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationHome"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.home",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/home"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/morning": {
      "abstract": [
        {
          "text": "A situation that occurs during the morning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "morning"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/morning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationMorning"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.morning",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/morning"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/physicalActivityIncomplete": {
      "abstract": [
        {
          "text": "A situation occurs that causes a physical activity to become incomplete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalActivityIncomplete"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/physicalActivityIncomplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationPhysicalActivityIncomplete"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.physicalActivityIncomplete",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/physicalactivityincomplete"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/school": {
      "abstract": [
        {
          "text": "A situation that occurs at the user’s school.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "school"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/school",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationSchool"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.school",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/school"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/work": {
      "abstract": [
        {
          "text": "A situation that occurs at the user’s place of work.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "work"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/work",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDailyRoutineSituationWork"
        }
      ],
      "role": "symbol",
      "title": "INDailyRoutineRelevanceProvider.Situation.work",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum/work"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/situation-swift.property": {
      "abstract": [
        {
          "text": "The relevant daily routine situation for the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "situation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDailyRoutineRelevanceProvider",
          "text": "INDailyRoutineRelevanceProvider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDailyRoutineSituation",
          "text": "Situation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/situation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "situation"
        }
      ],
      "role": "symbol",
      "title": "situation",
      "type": "topic",
      "url": "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Situation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/situation-swift.property"
      ],
      "title": "Getting the Situation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Situations",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/morning",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/evening",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/home",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/work",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/school",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/gym",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/commute",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/headphonesConnected",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/activeWorkout",
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/physicalActivityIncomplete"
      ],
      "title": "Situations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INDailyRoutineSituation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Situations",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/morning",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/evening",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/home",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/work",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/school",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/gym",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/commute",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/headphonesConnected",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/activeWorkout",
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/Situation-swift.enum/physicalActivityIncomplete"
              ],
              "title": "Situations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Situation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INDailyRoutineRelevanceProvider/situation-swift.property"
              ],
              "title": "Getting the Situation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INDailyRoutineSituation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1gym/title",
          "value": "INDailyRoutineSituationGym"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1gym/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationGym"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1evening/title",
          "value": "INDailyRoutineSituationEvening"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1evening/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationEvening"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1physicalActivityIncomplete/title",
          "value": "INDailyRoutineSituationPhysicalActivityIncomplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1physicalActivityIncomplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationPhysicalActivityIncomplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1activeWorkout/title",
          "value": "INDailyRoutineSituationActiveWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1activeWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationActiveWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum/title",
          "value": "INDailyRoutineSituation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider/title",
          "value": "INDailyRoutineRelevanceProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineRelevanceProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1work/title",
          "value": "INDailyRoutineSituationWork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1work/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationWork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1home/title",
          "value": "INDailyRoutineSituationHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1school/title",
          "value": "INDailyRoutineSituationSchool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1school/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationSchool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1morning/title",
          "value": "INDailyRoutineSituationMorning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1morning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationMorning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1commute/title",
          "value": "INDailyRoutineSituationCommute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1commute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationCommute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1situation-swift.property/title",
          "value": "situation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1situation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "situation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1headphonesConnected/title",
          "value": "INDailyRoutineSituationHeadphonesConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDailyRoutineRelevanceProvider~1Situation-swift.enum~1headphonesConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDailyRoutineSituationHeadphonesConnected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/indailyroutinerelevanceprovider/situation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
