{
  "abstract": [
    {
      "text": "Returns a new numeric factor options structure with the specified properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So26SparseNumericFactorOptionsa7control13scalingMethod0F014pivotTolerance04zeroI0ABSo0A9Control_ta_So0A9Scaling_taSvSgS2dtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "control"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparseControl_t",
        "text": "SparseControl_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "scalingMethod"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparseScaling_t",
        "text": "SparseScaling_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "scaling"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "pivotTolerance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "zeroTolerance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "control"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparseControl_t",
              "text": "SparseControl_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "scalingMethod"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparseScaling_t",
              "text": "SparseScaling_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "scaling"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "pivotTolerance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "zeroTolerance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The flags that control the computation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "control"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The scaling method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "scalingMethod"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array that scales the matrix before factorization.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "scaling"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The pivot tolerance that threshold partial pivoting uses.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pivotTolerance"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The zero tolerance that some pivoting modes use.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "zeroTolerance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Only the symmetric factorization algorithms use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " parameters. ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorizationQR",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ignores the pivot and zero tolerance values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t": {
      "abstract": [
        {
          "text": "Options that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "role": "symbol",
      "title": "SparseControl_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecontrol_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorizationQR": {
      "abstract": [
        {
          "text": "A constant that represents QR factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactorizationQR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseFactorization_t",
          "text": "SparseFactorization_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorizationQR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactorizationQR"
        }
      ],
      "role": "symbol",
      "title": "SparseFactorizationQR",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactorizationqr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions": {
      "abstract": [
        {
          "text": "A structure that contains options that affect the numerical stage of a sparse factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseNumericFactorOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseNumericFactorOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseNumericFactorOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init()": {
      "abstract": [
        {
          "text": "Returns a new numeric factor options structure with default properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)": {
      "abstract": [
        {
          "text": "Returns a new numeric factor options structure with the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "control"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseControl_t",
          "text": "SparseControl_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scalingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "pivotTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "zeroTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/init(control:scalingmethod:scaling:pivottolerance:zerotolerance:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance": {
      "abstract": [
        {
          "text": "The pivot tolerance that threshold partial pivoting uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pivotTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pivotTolerance"
        }
      ],
      "role": "symbol",
      "title": "pivotTolerance",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/pivottolerance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance": {
      "abstract": [
        {
          "text": "The zero tolerance that some pivoting modes use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zeroTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zeroTolerance"
        }
      ],
      "role": "symbol",
      "title": "zeroTolerance",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/zerotolerance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t": {
      "abstract": [
        {
          "text": "Options that define which scaling algorithm to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScaling_t"
        }
      ],
      "role": "symbol",
      "title": "SparseScaling_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescaling_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Numeric-Factor-Options-Stucture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init()"
      ],
      "title": "Creating a Numeric Factor Options Stucture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/title",
          "value": "SparseNumericFactorOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/title",
          "value": "SparseControl_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorizationQR/title",
          "value": "SparseFactorizationQR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorizationQR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactorizationQR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/title",
          "value": "SparseScaling_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScaling_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScaling_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1zeroTolerance/title",
          "value": "zeroTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1zeroTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zeroTolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1pivotTolerance/title",
          "value": "pivotTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1pivotTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pivotTolerance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsenumericfactoroptions/init(control:scalingmethod:scaling:pivottolerance:zerotolerance:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
