{
  "abstract": [
    {
      "text": "An array that scales the matrix before factorization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SparseNumericFactorOptions@FI@scaling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scaling"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "scaling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "scaling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scaling"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This array can either be ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or a pointer to an array of real values with a length greater than or equal to the size of the matrix that you’re factoring. The type of the array values is the element type of the matrix (but real, even if the matrix is complex).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and this pointer is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the system doesn’t apply scaling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and this pointer isn’t ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the system uses the user-provided array to scale the matrix before factorization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " isn’t ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the factor function computes its own scaling.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If this pointer isn’t ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the computed scaling returns in the array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t": {
      "abstract": [
        {
          "text": "Options that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "role": "symbol",
      "title": "SparseControl_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecontrol_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions": {
      "abstract": [
        {
          "text": "A structure that contains options that affect the numerical stage of a sparse factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseNumericFactorOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseNumericFactorOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseNumericFactorOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control": {
      "abstract": [
        {
          "text": "The flags that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "control"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseControl_t",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "control"
        }
      ],
      "role": "symbol",
      "title": "control",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/control"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance": {
      "abstract": [
        {
          "text": "The pivot tolerance that threshold partial pivoting uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pivotTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pivotTolerance"
        }
      ],
      "role": "symbol",
      "title": "pivotTolerance",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/pivottolerance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling": {
      "abstract": [
        {
          "text": "An array that scales the matrix before factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaling"
        }
      ],
      "role": "symbol",
      "title": "scaling",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/scaling"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod": {
      "abstract": [
        {
          "text": "The scaling method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scalingMethod"
        }
      ],
      "role": "symbol",
      "title": "scalingMethod",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/scalingmethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance": {
      "abstract": [
        {
          "text": "The zero tolerance that some pivoting modes use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zeroTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zeroTolerance"
        }
      ],
      "role": "symbol",
      "title": "zeroTolerance",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/zerotolerance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser": {
      "abstract": [
        {
          "text": "User scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScalingUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScalingUser"
        }
      ],
      "role": "symbol",
      "title": "SparseScalingUser",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescalinguser"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t": {
      "abstract": [
        {
          "text": "Options that define which scaling algorithm to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScaling_t"
        }
      ],
      "role": "symbol",
      "title": "SparseScaling_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescaling_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "scaling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "scaling"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingUser/title",
          "value": "SparseScalingUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScalingUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1pivotTolerance/title",
          "value": "pivotTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1pivotTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pivotTolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/title",
          "value": "SparseControl_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1control/title",
          "value": "control"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1control/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scalingMethod/title",
          "value": "scalingMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scalingMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scalingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/title",
          "value": "SparseScaling_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScaling_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScaling_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/title",
          "value": "SparseNumericFactorOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scaling/title",
          "value": "scaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1zeroTolerance/title",
          "value": "zeroTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1zeroTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zeroTolerance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsenumericfactoroptions/scaling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparsenumericfactoroptions/scaling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
