{
  "abstract": [
    {
      "text": "A symbolic description of the stylistic aspects of a font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSFontDescriptorSymbolicTraits",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SymbolicTraits"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SymbolicTraits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSFontDescriptor.SymbolicTraits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SymbolicTraits"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAssetRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFontAssetRequest",
      "type": "topic",
      "url": "/documentation/appkit/nsfontassetrequest"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor": {
      "abstract": [
        {
          "text": "A dictionary of attributes that describe a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct": {
      "abstract": [
        {
          "text": "A symbolic description of the stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.SymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/UIOptimized": {
      "abstract": [
        {
          "text": "The font synthesizes appropriate attributes for user interface rendering, such as in control titles, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIOptimized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/UIOptimized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitUIOptimized"
        }
      ],
      "role": "symbol",
      "title": "UIOptimized",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/uioptimized"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/bold": {
      "abstract": [
        {
          "text": "The font’s style is boldface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/bold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitBold"
        }
      ],
      "role": "symbol",
      "title": "bold",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/bold"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classClarendonSerifs": {
      "abstract": [
        {
          "text": "The font’s characters include variations of old style and transitional serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classClarendonSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classClarendonSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassClarendonSerifs"
        }
      ],
      "role": "symbol",
      "title": "classClarendonSerifs",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classclarendonserifs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classFreeformSerifs": {
      "abstract": [
        {
          "text": "The font’s characters include serifs, and don’t generally fit within other serif design classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classFreeformSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classFreeformSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassFreeformSerifs"
        }
      ],
      "role": "symbol",
      "title": "classFreeformSerifs",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classfreeformserifs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classMask": {
      "abstract": [
        {
          "text": "The font family class mask that you use to access font descriptor values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassMask"
        }
      ],
      "role": "symbol",
      "title": "classMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classModernSerifs": {
      "abstract": [
        {
          "text": "The font’s characters include serifs, and reflect the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classModernSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classModernSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassModernSerifs"
        }
      ],
      "role": "symbol",
      "title": "classModernSerifs",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classmodernserifs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOldStyleSerifs": {
      "abstract": [
        {
          "text": "The font’s characters include serifs, and reflect the Latin printing style of the 15th to 17th centuries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOldStyleSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOldStyleSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassOldStyleSerifs"
        }
      ],
      "role": "symbol",
      "title": "classOldStyleSerifs",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classoldstyleserifs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOrnamentals": {
      "abstract": [
        {
          "text": "The font’s characters use highly decorated or stylized character shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOrnamentals"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOrnamentals",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassOrnamentals"
        }
      ],
      "role": "symbol",
      "title": "classOrnamentals",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classornamentals"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSansSerif": {
      "abstract": [
        {
          "text": "The font’s characters don’t have serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSansSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSansSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassSansSerif"
        }
      ],
      "role": "symbol",
      "title": "classSansSerif",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classsansserif"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classScripts": {
      "abstract": [
        {
          "text": "The font’s characters simulate handwriting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classScripts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classScripts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassScripts"
        }
      ],
      "role": "symbol",
      "title": "classScripts",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classscripts"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSlabSerifs": {
      "abstract": [
        {
          "text": "The font’s characters use square transitions, without brackets, between strokes and serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSlabSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSlabSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassSlabSerifs"
        }
      ],
      "role": "symbol",
      "title": "classSlabSerifs",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classslabserifs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSymbolic": {
      "abstract": [
        {
          "text": "The font’s characters consist mainly of symbols rather than letters and numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSymbolic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSymbolic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassSymbolic"
        }
      ],
      "role": "symbol",
      "title": "classSymbolic",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classsymbolic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classTransitionalSerifs": {
      "abstract": [
        {
          "text": "The font’s characters include serifs, and reflect the Latin printing style of the 18th to 19th centuries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classTransitionalSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classTransitionalSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassTransitionalSerifs"
        }
      ],
      "role": "symbol",
      "title": "classTransitionalSerifs",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/classtransitionalserifs"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/condensed": {
      "abstract": [
        {
          "text": "The font’s characters have a condensed width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condensed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/condensed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitCondensed"
        }
      ],
      "role": "symbol",
      "title": "condensed",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/condensed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/expanded": {
      "abstract": [
        {
          "text": "The font’s characters have an expanded width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/expanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitExpanded"
        }
      ],
      "role": "symbol",
      "title": "expanded",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/expanded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/italic": {
      "abstract": [
        {
          "text": "The font’s style is italic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/italic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitItalic"
        }
      ],
      "role": "symbol",
      "title": "italic",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/italic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/looseLeading": {
      "abstract": [
        {
          "text": "The font uses a leading value that’s greater than the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "looseLeading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/looseLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitLooseLeading"
        }
      ],
      "role": "symbol",
      "title": "looseLeading",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/looseleading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/monoSpace": {
      "abstract": [
        {
          "text": "The font’s characters all have the same width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/monoSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitMonoSpace"
        }
      ],
      "role": "symbol",
      "title": "monoSpace",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/monospace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/tightLeading": {
      "abstract": [
        {
          "text": "The font uses a leading value that’s less than the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tightLeading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/tightLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitTightLeading"
        }
      ],
      "role": "symbol",
      "title": "tightLeading",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/tightleading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/vertical": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontDescriptorSymbolicTraits",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/vertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitVertical"
        }
      ],
      "role": "symbol",
      "title": "vertical",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct/vertical"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptorSymbolicTraits/NSFontDescriptorClassUnknown": {
      "abstract": [
        {
          "text": "The font has no design classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorClassUnknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptorSymbolicTraits/NSFontDescriptorClassUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontDescriptorClassUnknown",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptorsymbolictraits/nsfontdescriptorclassunknown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptorSymbolicTraits/NSFontDescriptorTraitEmphasized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptorTraitEmphasized"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptorSymbolicTraits/NSFontDescriptorTraitEmphasized",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontDescriptorTraitEmphasized",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptorsymbolictraits/nsfontdescriptortraitemphasized"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass": {
      "abstract": [
        {
          "text": "Constants that classify certain stylistic qualities of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontFamilyClass"
        }
      ],
      "role": "symbol",
      "title": "NSFontFamilyClass",
      "type": "topic",
      "url": "/documentation/appkit/nsfontfamilyclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits": {
      "abstract": [
        {
          "text": "A symbolic description of stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "NSFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/appkit/nsfontsymbolictraits"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask": {
      "abstract": [
        {
          "text": "Constants for isolating specific traits of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontTraitMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct": {
      "abstract": [
        {
          "text": "Constants that describe the stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFontDescriptor.SymbolicTraits",
      "type": "topic",
      "url": "/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Font-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
        "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
      ],
      "title": "Font Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Symbolic-Traits",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/italic",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/bold",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/expanded",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/condensed",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/monoSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/vertical",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/UIOptimized",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/tightLeading",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/looseLeading",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOldStyleSerifs",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classTransitionalSerifs",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classModernSerifs",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classClarendonSerifs",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSlabSerifs",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classFreeformSerifs",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSansSerif",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOrnamentals",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classScripts",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSymbolic"
      ],
      "title": "Symbolic Traits"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Symbolic-Traits",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/italic",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/bold",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/expanded",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/condensed",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/monoSpace",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/vertical",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/UIOptimized",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/tightLeading",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/looseLeading",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptorSymbolicTraits/NSFontDescriptorClassUnknown",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOldStyleSerifs",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classTransitionalSerifs",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classModernSerifs",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classClarendonSerifs",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSlabSerifs",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classFreeformSerifs",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSansSerif",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classOrnamentals",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classScripts",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/SymbolicTraits-swift.struct/classSymbolic"
              ],
              "title": "Symbolic Traits"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptorSymbolicTraits/NSFontDescriptorTraitEmphasized"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Font-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontFamilyClass",
                "doc://com.apple.appkit/documentation/AppKit/NSFontAssetRequest",
                "doc://com.apple.appkit/documentation/AppKit/NSFontSymbolicTraits"
              ],
              "title": "Font Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontDescriptorSymbolicTraits"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1bold/title",
          "value": "NSFontDescriptorTraitBold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1bold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitBold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classFreeformSerifs/title",
          "value": "NSFontDescriptorClassFreeformSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classFreeformSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassFreeformSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classModernSerifs/title",
          "value": "NSFontDescriptorClassModernSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classModernSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassModernSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/title",
          "value": "NSFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/title",
          "value": "NSFontFamilyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontFamilyClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontFamilyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classOldStyleSerifs/title",
          "value": "NSFontDescriptorClassOldStyleSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classOldStyleSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassOldStyleSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1looseLeading/title",
          "value": "NSFontDescriptorTraitLooseLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1looseLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitLooseLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1UIOptimized/title",
          "value": "NSFontDescriptorTraitUIOptimized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1UIOptimized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitUIOptimized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIFontDescriptor~1SymbolicTraits-swift.struct/title",
          "value": "UIFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIFontDescriptor~1SymbolicTraits-swift.struct/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFontDescriptorSymbolicTraits"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1vertical/title",
          "value": "NSFontDescriptorTraitVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1vertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1tightLeading/title",
          "value": "NSFontDescriptorTraitTightLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1tightLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitTightLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1condensed/title",
          "value": "NSFontDescriptorTraitCondensed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1condensed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitCondensed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/title",
          "value": "NSFontTraitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/title",
          "value": "NSFontAssetRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontAssetRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAssetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classSansSerif/title",
          "value": "NSFontDescriptorClassSansSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classSansSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassSansSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1monoSpace/title",
          "value": "NSFontDescriptorTraitMonoSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1monoSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitMonoSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classTransitionalSerifs/title",
          "value": "NSFontDescriptorClassTransitionalSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classTransitionalSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassTransitionalSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1italic/title",
          "value": "NSFontDescriptorTraitItalic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1italic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitItalic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classClarendonSerifs/title",
          "value": "NSFontDescriptorClassClarendonSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classClarendonSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassClarendonSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/title",
          "value": "NSFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classSymbolic/title",
          "value": "NSFontDescriptorClassSymbolic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classSymbolic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassSymbolic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classScripts/title",
          "value": "NSFontDescriptorClassScripts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classScripts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassScripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classSlabSerifs/title",
          "value": "NSFontDescriptorClassSlabSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classSlabSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassSlabSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classOrnamentals/title",
          "value": "NSFontDescriptorClassOrnamentals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classOrnamentals/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassOrnamentals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classMask/title",
          "value": "NSFontDescriptorClassMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1classMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorClassMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1expanded/title",
          "value": "NSFontDescriptorTraitExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1SymbolicTraits-swift.struct~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitExpanded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor/symbolictraits-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
