{
  "abstract": [
    {
      "text": "An array of time intervals that indicate where to insert media items into another, single media item.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVMediaItem(py)interstitials",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "interstitials"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)TVMediaItem",
        "text": "TVMediaItem"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)TVTimeRange",
        "text": "TimeRange"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "interstitials"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "interstitials"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "interstitials"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVMediaItem",
              "text": "TVMediaItem"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVTimeRange",
              "text": "TimeRange"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "Interstitials",
              "type": "codeVoice"
            },
            {
              "text": " property defines points within a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object where you can insert another media item; for example, a short ad. Each time range in the array contains two properties: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange/startTime",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange/duration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The ",
              "type": "text"
            },
            {
              "code": "startTime",
              "type": "codeVoice"
            },
            {
              "text": " is the length of time from the beginning of a media item, in seconds. The ",
              "type": "text"
            },
            {
              "code": "duration",
              "type": "codeVoice"
            },
            {
              "text": " is the length of the interstitial, in seconds. Both properties are required. A common use for these objects is to define when and where ads are to be played during a stream.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem": {
      "abstract": [
        {
          "text": "A single audio or video item associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup": {
      "abstract": [
        {
          "text": "A container for groups of highlights for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HighlightGroup"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HighlightGroup"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.HighlightGroup",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroup"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange": {
      "abstract": [
        {
          "text": "An object that defines a time range in a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TimeRange"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TimeRange"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.TimeRange",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/timerange"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange/duration": {
      "abstract": [
        {
          "text": "The duration of a time range in a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/timerange/duration"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange/startTime": {
      "abstract": [
        {
          "text": "The time in a media item that determines when a time range begins.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange/startTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTime"
        }
      ],
      "role": "symbol",
      "title": "startTime",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/timerange/starttime"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups": {
      "abstract": [
        {
          "text": "An array containing groups of individual highlights in a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVHighlightGroup",
          "text": "HighlightGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightGroups"
        }
      ],
      "role": "symbol",
      "title": "highlightGroups",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroups"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials": {
      "abstract": [
        {
          "text": "An array of time intervals that indicate where to insert media items into another, single media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interstitials"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTimeRange",
          "text": "TimeRange"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/interstitials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interstitials"
        }
      ],
      "role": "symbol",
      "title": "interstitials",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/interstitials"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime": {
      "abstract": [
        {
          "text": "The number of seconds from the beginning of a media item to the point where that media item begins playing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeTime"
        }
      ],
      "role": "symbol",
      "title": "resumeTime",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/resumetime"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-Timing-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime"
      ],
      "title": "Setting Timing Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "interstitials"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interstitials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-Timing-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/highlightGroups",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/TimeRange",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/resumeTime"
              ],
              "title": "Setting Timing Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<TVTimeRange *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "interstitials"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1resumeTime/title",
          "value": "resumeTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1resumeTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resumeTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1highlightGroups/title",
          "value": "highlightGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1highlightGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1interstitials/title",
          "value": "interstitials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1interstitials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interstitials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/title",
          "value": "TVMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange~1startTime/title",
          "value": "startTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange~1startTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange/title",
          "value": "TVTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/title",
          "value": "TVHighlightGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlightGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlightGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1TimeRange~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvmediaitem/interstitials"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvmediaitem/interstitials"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
