{
  "abstract": [
    {
      "text": "Allows the system to choose the horizontal alignment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SWAttributionViewHorizontalAlignment@SWAttributionViewHorizontalAlignmentDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SWAttributionViewHorizontalAlignmentDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SWAttributionView.HorizontalAlignment.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView": {
      "abstract": [
        {
          "text": "A view that displays the sender who shares a highlight and provides related actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum": {
      "abstract": [
        {
          "text": "The horizontal alignment of attribution view’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HorizontalAlignment"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HorizontalAlignment"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.HorizontalAlignment",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/center": {
      "abstract": [
        {
          "text": "Aligns horizontally with the center of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewHorizontalAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.HorizontalAlignment.center",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum/center"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/default": {
      "abstract": [
        {
          "text": "Allows the system to choose the horizontal alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewHorizontalAlignmentDefault"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.HorizontalAlignment.default",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum/default"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/leading": {
      "abstract": [
        {
          "text": "Aligns horizontally with the leading edge of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewHorizontalAlignmentLeading"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.HorizontalAlignment.leading",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum/leading"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/trailing": {
      "abstract": [
        {
          "text": "Aligns horizontally with the trailing edge of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewHorizontalAlignmentTrailing"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.HorizontalAlignment.trailing",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum/trailing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Horizontal-alignments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/leading",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/center",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/trailing"
      ],
      "title": "Horizontal alignments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SWAttributionViewHorizontalAlignmentDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignmentDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Horizontal-alignments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/leading",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/center",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/HorizontalAlignment-swift.enum/trailing"
              ],
              "title": "Horizontal alignments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SWAttributionViewHorizontalAlignmentDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1leading/title",
          "value": "SWAttributionViewHorizontalAlignmentLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignmentLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1center/title",
          "value": "SWAttributionViewHorizontalAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum/title",
          "value": "SWAttributionViewHorizontalAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/title",
          "value": "SWAttributionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1trailing/title",
          "value": "SWAttributionViewHorizontalAlignmentTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignmentTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1default/title",
          "value": "SWAttributionViewHorizontalAlignmentDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1HorizontalAlignment-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewHorizontalAlignmentDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyou/swattributionview/horizontalalignment-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
