{
  "abstract": [
    {
      "text": "The left margin between the receiver and its superview is flexible.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinXMargin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CAAutoresizingMask@kCALayerMinXMargin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "layerMinXMargin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CAAutoresizingMask",
        "text": "CAAutoresizingMask"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCALayerMinXMargin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "layerMinXMargin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "layerMinXMargin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CAAutoresizingMask",
              "text": "CAAutoresizingMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask": {
      "abstract": [
        {
          "text": "These constants are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAutoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "CAAutoresizingMask",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/init(rawvalue:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/kCALayerNotSizable": {
      "abstract": [
        {
          "text": "The receiver cannot be resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCALayerNotSizable"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/kCALayerNotSizable",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCALayerNotSizable",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/kcalayernotsizable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerHeightSizable": {
      "abstract": [
        {
          "text": "The receiver’s height is flexible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerHeightSizable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerHeightSizable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerHeightSizable"
        }
      ],
      "role": "symbol",
      "title": "layerHeightSizable",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/layerheightsizable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxXMargin": {
      "abstract": [
        {
          "text": "The right margin between the receiver and its superview is flexible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMaxXMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxXMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMaxXMargin"
        }
      ],
      "role": "symbol",
      "title": "layerMaxXMargin",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/layermaxxmargin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxYMargin": {
      "abstract": [
        {
          "text": "The top margin between the receiver and its superview is flexible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMaxYMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxYMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMaxYMargin"
        }
      ],
      "role": "symbol",
      "title": "layerMaxYMargin",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/layermaxymargin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinXMargin": {
      "abstract": [
        {
          "text": "The left margin between the receiver and its superview is flexible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMinXMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinXMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMinXMargin"
        }
      ],
      "role": "symbol",
      "title": "layerMinXMargin",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/layerminxmargin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinYMargin": {
      "abstract": [
        {
          "text": "The bottom margin between the receiver and its superview is flexible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMinYMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinYMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMinYMargin"
        }
      ],
      "role": "symbol",
      "title": "layerMinYMargin",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/layerminymargin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerWidthSizable": {
      "abstract": [
        {
          "text": "The receiver’s width is flexible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerWidthSizable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerWidthSizable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerWidthSizable"
        }
      ],
      "role": "symbol",
      "title": "layerWidthSizable",
      "type": "topic",
      "url": "/documentation/quartzcore/caautoresizingmask/layerwidthsizable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask": {
      "abstract": [
        {
          "text": "A bitmask defining how the layer is resized when the bounds of its superlayer changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoresizingMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CAAutoresizingMask",
          "text": "CAAutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "autoresizingMask",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/autoresizingmask"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/init(rawValue:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerWidthSizable",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxXMargin",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinYMargin",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerHeightSizable",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxYMargin"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCALayerMinXMargin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMinXMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/kCALayerNotSizable",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerWidthSizable",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxXMargin",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMinYMargin",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerHeightSizable",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAutoresizingMask/layerMaxYMargin"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCALayerMinXMargin"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1autoresizingMask/title",
          "value": "autoresizingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1autoresizingMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoresizingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMinYMargin/title",
          "value": "kCALayerMinYMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMinYMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMinYMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask/title",
          "value": "CAAutoresizingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAutoresizingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAutoresizingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerWidthSizable/title",
          "value": "kCALayerWidthSizable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerWidthSizable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerWidthSizable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerHeightSizable/title",
          "value": "kCALayerHeightSizable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerHeightSizable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerHeightSizable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMaxXMargin/title",
          "value": "kCALayerMaxXMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMaxXMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMaxXMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMaxYMargin/title",
          "value": "kCALayerMaxYMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMaxYMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMaxYMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMinXMargin/title",
          "value": "kCALayerMinXMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAutoresizingMask~1layerMinXMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMinXMargin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/caautoresizingmask/layerminxmargin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/caautoresizingmask/layerminxmargin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
