{
  "abstract": [
    {
      "text": "If this method is implemented and returns ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", NSToolbar will disable ",
      "type": "text"
    },
    {
      "code": "theItem",
      "type": "codeVoice"
    },
    {
      "text": "; returning ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " causes ",
      "type": "text"
    },
    {
      "code": "theItem",
      "type": "codeVoice"
    },
    {
      "text": " to be enabled.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation/validateToolbarItem(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSToolbarItemValidation(im)validateToolbarItem:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "validateToolbarItem"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSToolbarItem",
        "text": "NSToolbarItem"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "validateToolbarItem:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "validateToolbarItem(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "validateToolbarItem"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "item"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbarItem",
              "text": "NSToolbarItem"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "NSToolbar only calls this method for image items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1524282-validatetoolbaritem",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " is called very frequently, so it must be efficient.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If the receiver is the ",
              "type": "text"
            },
            {
              "code": "target",
              "type": "codeVoice"
            },
            {
              "text": " for the actions of multiple toolbar items, it’s necessary to determine which toolbar item ",
              "type": "text"
            },
            {
              "code": "theItem",
              "type": "codeVoice"
            },
            {
              "text": " refers to by testing the ",
              "type": "text"
            },
            {
              "code": "itemIdentifier",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "-(BOOL)validateToolbarItem:(NSToolbarItem *)toolbarItem",
            "{",
            "    BOOL enable = NO;",
            "    if ([[toolbarItem itemIdentifier] isEqual:SaveDocToolbarItemIdentifier]) {",
            "        // We will return YES (enable the save item)",
            "        // only when the document is dirty and needs saving",
            "        enable = [self isDocumentEdited];",
            "    } else if ([[toolbarItem itemIdentifier] isEqual:NSToolbarPrintItemIdentifier]) {",
            "        // always enable print for this window",
            "        enable = YES;",
            "    }",
            "    return enable;",
            "}"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/validateVisibleItems()": {
      "abstract": [
        {
          "text": "Validates the toolbar’s visible items during a window update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateVisibleItems"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/validateVisibleItems()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateVisibleItems"
        }
      ],
      "role": "symbol",
      "title": "validateVisibleItems()",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/validatevisibleitems()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem": {
      "abstract": [
        {
          "text": "A single item that appears in a window’s toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSToolbarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/action": {
      "abstract": [
        {
          "text": "The action method to call when someone clicks on the toolbar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "action"
        }
      ],
      "role": "symbol",
      "title": "action",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem/action"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target": {
      "abstract": [
        {
          "text": "The object that defines the action method the toolbar item calls when clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": AnyObject?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem/target"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()": {
      "abstract": [
        {
          "text": "Validates the toolbar item’s menu and its ability to perfrom its action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validate"
        }
      ],
      "role": "symbol",
      "title": "validate()",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem/validate()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation": {
      "abstract": [
        {
          "text": "Validation of a toolbar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItemValidation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbarItemValidation"
        }
      ],
      "role": "symbol",
      "title": "NSToolbarItemValidation",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritemvalidation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation/validateToolbarItem(_:)": {
      "abstract": [
        {
          "text": "If this method is implemented and returns ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/false",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", NSToolbar will disable ",
          "type": "text"
        },
        {
          "code": "theItem",
          "type": "codeVoice"
        },
        {
          "text": "; returning ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " causes ",
          "type": "text"
        },
        {
          "code": "theItem",
          "type": "codeVoice"
        },
        {
          "text": " to be enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateToolbarItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSToolbarItem",
          "text": "NSToolbarItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation/validateToolbarItem(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateToolbarItem:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "validateToolbarItem(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritemvalidation/validatetoolbaritem(_:)"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1524282-validatetoolbaritem": {
      "abstract": [
        {
          "text": "If this method is implemented and returns , NSToolbar will disable `theItem`; returning  causes `theItem` to be enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1524282-validatetoolbaritem",
      "kind": "symbol",
      "role": "symbol",
      "title": "validateToolbarItem:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1524282-validatetoolbaritem"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Toolbars.html#//apple_ref/doc/uid/10000109i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Toolbars.html#//apple_ref/doc/uid/10000109i",
      "title": "Toolbar Programming Topics for Cocoa",
      "titleInlineContent": [
        {
          "text": "Toolbar Programming Topics for Cocoa",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Toolbars.html#//apple_ref/doc/uid/10000109i"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar/validateVisibleItems()",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/action",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target",
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Toolbars.html#//apple_ref/doc/uid/10000109i",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "validateToolbarItem:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateToolbarItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemValidation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar/validateVisibleItems()",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/action",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target",
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Toolbars.html#//apple_ref/doc/uid/10000109i",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/validate()"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "validateToolbarItem:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSToolbarItem",
                    "text": "NSToolbarItem"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "item"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemValidation/title",
          "value": "NSToolbarItemValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemValidation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemValidation~1validateToolbarItem(_:)/title",
          "value": "validateToolbarItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemValidation~1validateToolbarItem(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateToolbarItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1action/title",
          "value": "action"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "action"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1validate()/title",
          "value": "validate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1validate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1target/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1target/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1validateVisibleItems()/title",
          "value": "validateVisibleItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1validateVisibleItems()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateVisibleItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/title",
          "value": "NSToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstoolbaritemvalidation/validatetoolbaritem(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstoolbaritemvalidation/validatetoolbaritem(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
