{
  "abstract": [
    {
      "text": "Responds when a drag exits the bounds of the spring-loading destination.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingExited(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSSpringLoadingDestination(im)springLoadingExited:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "springLoadingExited"
      },
      {
        "kind": "text",
        "text": "(any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
        "text": "NSDraggingInfo"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "springLoadingExited:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "springLoadingExited(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "springLoadingExited"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "draggingInfo"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
              "text": "NSDraggingInfo"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object of type ",
                  "type": "text"
                },
                {
                  "code": "NSDraggingInfo",
                  "type": "codeVoice"
                },
                {
                  "text": ", which provides information about the drag event, including the dragged data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "draggingInfo"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called when a drag exits the bounds of a spring-loaded destination.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This is a good place to clean up any initialization work that may have been performed during ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingEntered(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo": {
      "abstract": [
        {
          "text": "A set of methods that supply information about a dragging session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingInfo"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsdragginginfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged object can implement to support spring-loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSpringLoadingDestination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpringLoadingDestination"
        }
      ],
      "role": "symbol",
      "title": "NSSpringLoadingDestination",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/draggingEnded(_:)": {
      "abstract": [
        {
          "text": "Responds to the end of a drag operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draggingEnded"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/draggingEnded(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "draggingEnded:"
        }
      ],
      "role": "symbol",
      "title": "draggingEnded(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination/draggingended(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingActivated(_:draggingInfo:)": {
      "abstract": [
        {
          "text": "Responds to the activation or deactivation of spring-loading on a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springLoadingActivated"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "draggingInfo"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingActivated(_:draggingInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoadingActivated:draggingInfo:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "springLoadingActivated(_:draggingInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination/springloadingactivated(_:dragginginfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingEntered(_:)": {
      "abstract": [
        {
          "text": "Returns whether to enable or disable spring-loading when a drag enters the bounds of the spring-loading destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springLoadingEntered"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSpringLoadingOptions",
          "text": "NSSpringLoadingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingEntered(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoadingEntered:"
        }
      ],
      "role": "symbol",
      "title": "springLoadingEntered(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination/springloadingentered(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingExited(_:)": {
      "abstract": [
        {
          "text": "Responds when a drag exits the bounds of the spring-loading destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springLoadingExited"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingExited(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoadingExited:"
        }
      ],
      "role": "symbol",
      "title": "springLoadingExited(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination/springloadingexited(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingHighlightChanged(_:)": {
      "abstract": [
        {
          "text": "Updates the destination’s user interface to display a new highlighting style during a spring-loading operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springLoadingHighlightChanged"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingHighlightChanged(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoadingHighlightChanged:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "springLoadingHighlightChanged(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination/springloadinghighlightchanged(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingUpdated(_:)": {
      "abstract": [
        {
          "text": "Returns whether to enable or disable spring-loading as a drag moves within the bounds of the spring-loading destination or ",
          "type": "text"
        },
        {
          "code": "draggingInfo",
          "type": "codeVoice"
        },
        {
          "text": " changes during the drag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springLoadingUpdated"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSDraggingInfo",
          "text": "NSDraggingInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSpringLoadingOptions",
          "text": "NSSpringLoadingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingUpdated(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoadingUpdated:"
        }
      ],
      "role": "symbol",
      "title": "springLoadingUpdated(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingdestination/springloadingupdated(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingOptions": {
      "abstract": [
        {
          "text": "These constants denote the type of spring-loading behavior configured for the destination object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSpringLoadingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpringLoadingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSSpringLoadingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsspringloadingoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Respond-to-Spring-loading-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingActivated(_:draggingInfo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingHighlightChanged(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingEntered(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingUpdated(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/draggingEnded(_:)"
      ],
      "title": "Respond to Spring-loading Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "springLoadingExited:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "springLoadingExited:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Respond-to-Spring-loading-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingActivated(_:draggingInfo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingHighlightChanged(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingEntered(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/springLoadingUpdated(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSpringLoadingDestination/draggingEnded(_:)"
              ],
              "title": "Respond to Spring-loading Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "springLoadingExited:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)NSDraggingInfo",
                    "text": "id<NSDraggingInfo>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "draggingInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object of type ",
                        "type": "text"
                      },
                      {
                        "code": "NSDraggingInfo",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", which provides information about the drag event, including the dragged data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "draggingInfo"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingOptions/title",
          "value": "NSSpringLoadingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/title",
          "value": "NSDraggingInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingEntered(_:)/title",
          "value": "springLoadingEntered:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingEntered(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "springLoadingEntered:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingExited(_:)/title",
          "value": "springLoadingExited:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingExited(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "springLoadingExited:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination/title",
          "value": "NSSpringLoadingDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpringLoadingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingHighlightChanged(_:)/title",
          "value": "springLoadingHighlightChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingHighlightChanged(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "springLoadingHighlightChanged:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingActivated(_:draggingInfo:)/title",
          "value": "springLoadingActivated:draggingInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingActivated(_:draggingInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "springLoadingActivated:draggingInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingUpdated(_:)/title",
          "value": "springLoadingUpdated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1springLoadingUpdated(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "springLoadingUpdated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1draggingEnded(_:)/title",
          "value": "draggingEnded:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpringLoadingDestination~1draggingEnded(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "draggingEnded:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsspringloadingdestination/springloadingexited(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsspringloadingdestination/springloadingexited(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
