{
  "abstract": [
    {
      "text": "A remote-control event for playing audio or video.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIEventSubtype@UIEventSubtypeRemoteControlPlay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remoteControlPlay"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIEventSubtypeRemoteControlPlay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIEvent.EventSubtype.remoteControlPlay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remoteControlPlay"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This is a subtype of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType/remoteControl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " general event type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent": {
      "abstract": [
        {
          "text": "An object that describes a single user interaction with your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEvent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEvent"
        }
      ],
      "role": "symbol",
      "title": "UIEvent",
      "type": "topic",
      "url": "/documentation/uikit/uievent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype": {
      "abstract": [
        {
          "text": "Constants that specify the subtype of the event in relation to its general type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake": {
      "abstract": [
        {
          "text": "The event is related to a person shaking the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionShake"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeMotionShake"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.motionShake",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/motionshake"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none": {
      "abstract": [
        {
          "text": "The event has no subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeNone"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.none",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward": {
      "abstract": [
        {
          "text": "A remote-control event to start seeking backward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlBeginSeekingBackward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlBeginSeekingBackward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlBeginSeekingBackward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolbeginseekingbackward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward": {
      "abstract": [
        {
          "text": "A remote-control event to start seeking forward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlBeginSeekingForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlBeginSeekingForward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlBeginSeekingForward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolbeginseekingforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward": {
      "abstract": [
        {
          "text": "A remote-control event to end seeking backward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlEndSeekingBackward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlEndSeekingBackward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlEndSeekingBackward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolendseekingbackward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward": {
      "abstract": [
        {
          "text": "A remote-control event to end seeking forward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlEndSeekingForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlEndSeekingForward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlEndSeekingForward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolendseekingforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack": {
      "abstract": [
        {
          "text": "A remote-control event for skipping to the next audio or video track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlNextTrack"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlNextTrack"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlNextTrack",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolnexttrack"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause": {
      "abstract": [
        {
          "text": "A remote-control event for pausing audio or video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlPause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlPause"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlPause",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolpause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay": {
      "abstract": [
        {
          "text": "A remote-control event for playing audio or video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlPlay"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlPlay"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlPlay",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolplay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack": {
      "abstract": [
        {
          "text": "A remote-control event for skipping to the previous audio or video track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlPreviousTrack"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlPreviousTrack"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlPreviousTrack",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolprevioustrack"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop": {
      "abstract": [
        {
          "text": "A remote-control event for stopping audio or video from playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlStop"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlStop"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlStop",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolstop"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause": {
      "abstract": [
        {
          "text": "A remote-control event for toggling audio or video between play and pause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlTogglePlayPause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlTogglePlayPause"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlTogglePlayPause",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontroltoggleplaypause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType/remoteControl": {
      "abstract": [
        {
          "text": "The event is a remote-control event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType/remoteControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventTypeRemoteControl"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventType.remoteControl",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventtype/remotecontrol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIEventSubtypeRemoteControlPlay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIEventSubtypeRemoteControlPlay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType~1remoteControl/title",
          "value": "UIEventTypeRemoteControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType~1remoteControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventTypeRemoteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingForward/title",
          "value": "UIEventSubtypeRemoteControlBeginSeekingForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlBeginSeekingForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/title",
          "value": "UIEventSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPlay/title",
          "value": "UIEventSubtypeRemoteControlPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingBackward/title",
          "value": "UIEventSubtypeRemoteControlEndSeekingBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingBackward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlEndSeekingBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPreviousTrack/title",
          "value": "UIEventSubtypeRemoteControlPreviousTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPreviousTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPreviousTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPause/title",
          "value": "UIEventSubtypeRemoteControlPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingForward/title",
          "value": "UIEventSubtypeRemoteControlEndSeekingForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlEndSeekingForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlTogglePlayPause/title",
          "value": "UIEventSubtypeRemoteControlTogglePlayPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlTogglePlayPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlTogglePlayPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1motionShake/title",
          "value": "UIEventSubtypeMotionShake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1motionShake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeMotionShake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingBackward/title",
          "value": "UIEventSubtypeRemoteControlBeginSeekingBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingBackward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlBeginSeekingBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1none/title",
          "value": "UIEventSubtypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/title",
          "value": "UIEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlNextTrack/title",
          "value": "UIEventSubtypeRemoteControlNextTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlNextTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlNextTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlStop/title",
          "value": "UIEventSubtypeRemoteControlStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlStop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uievent/eventsubtype/remotecontrolplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uievent/eventsubtype/remotecontrolplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
