{
  "abstract": [
    {
      "text": "A synchronization point for tasks executing in a concurrent dispatch queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-barrier"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch Barrier"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a barrier to synchronize the execution of one or more tasks in your dispatch queue. When you add a barrier to a concurrent dispatch queue, the queue delays the execution of the barrier block (and any tasks submitted after the barrier) until all previously submitted tasks finish executing. After the previous tasks finish executing, the queue executes the barrier block by itself. Once the barrier block finishes, the queue resumes its normal execution behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore": {
      "abstract": [
        {
          "text": "An object that controls access to a resource across multiple execution contexts through use of a traditional counting semaphore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSemaphore"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSemaphore"
        }
      ],
      "role": "symbol",
      "title": "DispatchSemaphore",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore": {
      "abstract": [
        {
          "text": "An object that controls access to a resource across multiple execution contexts through use of a traditional counting semaphore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Semaphore",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-semaphore"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async": {
      "abstract": [
        {
          "text": "Submits a barrier block for asynchronous execution and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait": {
      "abstract": [
        {
          "text": "Submits a work item for synchronous execution and marks the work as a barrier for subsequent concurrent tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async_and_wait"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async_and_wait",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async_and_wait"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait_f": {
      "abstract": [
        {
          "text": "Submits a function-based work item for synchronous execution and marks the work as a barrier for subsequent concurrent tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async_and_wait_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async_and_wait_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async_and_wait_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_f": {
      "abstract": [
        {
          "text": "Submits a barrier function for asynchronous execution and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync": {
      "abstract": [
        {
          "text": "Submits a barrier block object for execution and waits until that block completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_sync"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_sync",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_sync"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync_f": {
      "abstract": [
        {
          "text": "Submits a barrier function for execution and waits until that function completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_sync_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_sync_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_sync_f"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Task-Synchronization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore"
      ],
      "title": "Task Synchronization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Barrier-Asynchronously",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_f"
              ],
              "title": "Creating a Barrier Asynchronously"
            },
            {
              "anchor": "Creating-a-Barrier-Synchronously",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait_f"
              ],
              "title": "Creating a Barrier Synchronously"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Task-Synchronization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore"
              ],
              "title": "Task Synchronization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-barrier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-barrier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
