{
  "abstract": [
    {
      "text": "Events involving a change to a file system object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@dispatch_source_vnode_flags_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_source_vnode_flags_t"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_source_vnode_flags_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "dispatch_source_vnode_flags_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:l",
              "text": "unsigned long"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_source_vnode_flags_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_ATTRIB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_ATTRIB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_ATTRIB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_ATTRIB"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_ATTRIB",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_attrib"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_DELETE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_DELETE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_DELETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_DELETE"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_DELETE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_delete"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_EXTEND": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_EXTEND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_EXTEND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_EXTEND"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_EXTEND",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_extend"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_FUNLOCK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_FUNLOCK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_FUNLOCK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_FUNLOCK"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_FUNLOCK",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_funlock"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_LINK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_LINK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_LINK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_LINK"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_LINK",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_link"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_RENAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_RENAME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_RENAME",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_RENAME"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_RENAME",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_rename"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_REVOKE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_REVOKE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_REVOKE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_REVOKE"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_REVOKE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_revoke"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_WRITE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_WRITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_WRITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_VNODE_WRITE"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_VNODE_WRITE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_vnode_write"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data": {
      "abstract": [
        {
          "text": "Returns pending data for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle": {
      "abstract": [
        {
          "text": "Returns the underlying system handle associated with the specified dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_handle"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_handle",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_handle"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask": {
      "abstract": [
        {
          "text": "Returns the mask of events monitored by the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_mask"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_mask",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_mask"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t": {
      "abstract": [
        {
          "text": "Mach receive-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_source_mach_recv_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_recv_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t": {
      "abstract": [
        {
          "text": "Mach send-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_send_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_mach_send_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_send_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t": {
      "abstract": [
        {
          "text": "Memory pressure events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_memorypressure_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_memorypressure_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_memorypressure_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data": {
      "abstract": [
        {
          "text": "Merges data into a dispatch source and submits its event handler block to its target queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_merge_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_merge_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_merge_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t": {
      "abstract": [
        {
          "text": "Events related to a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_proc_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_proc_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_proc_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t": {
      "abstract": [
        {
          "text": "Events involving a change to a file system object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_vnode_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_vnode_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_vnode_flags_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Dispatch-Source-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t"
      ],
      "title": "Getting Dispatch Source Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "File-System-Event-Flags",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_LINK",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_WRITE",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_ATTRIB",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_DELETE",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_EXTEND",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_RENAME",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_REVOKE",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_VNODE_FUNLOCK"
      ],
      "title": "File System Event Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_REVOKE/title",
          "value": "DISPATCH_VNODE_REVOKE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_REVOKE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_REVOKE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/title",
          "value": "dispatch_source_mach_recv_flags_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_FUNLOCK/title",
          "value": "DISPATCH_VNODE_FUNLOCK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_FUNLOCK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_FUNLOCK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_DELETE/title",
          "value": "DISPATCH_VNODE_DELETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_DELETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_DELETE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_ATTRIB/title",
          "value": "DISPATCH_VNODE_ATTRIB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_ATTRIB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_ATTRIB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_WRITE/title",
          "value": "DISPATCH_VNODE_WRITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_WRITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_WRITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_RENAME/title",
          "value": "DISPATCH_VNODE_RENAME"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_RENAME/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_RENAME"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_LINK/title",
          "value": "DISPATCH_VNODE_LINK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_LINK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_LINK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_EXTEND/title",
          "value": "DISPATCH_VNODE_EXTEND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_VNODE_EXTEND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_VNODE_EXTEND"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_source_vnode_flags_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
