{
  "abstract": [
    {
      "text": "A number of seconds, millisconds, microseconds, or nanoseconds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8Dispatch0A12TimeIntervalO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DispatchTimeInterval"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DispatchTimeInterval"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "DispatchTimeInterval"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DispatchTimeInterval"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " values to specify the interval at which a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceTimer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " fires or I/O handlers are invoked for a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " channel, as well as to increment and decrement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants": {
      "abstract": [
        {
          "text": "Constants for wall time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Wall Time Constants",
      "type": "topic",
      "url": "/documentation/dispatch/2963138-wall-time-constants"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW": {
      "abstract": [
        {
          "text": "The current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_WALLTIME_NOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_WALLTIME_NOW"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_WALLTIME_NOW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_walltime_now"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceTimer": {
      "abstract": [
        {
          "text": "A dispatch source that submits the event handler block based on a timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceTimer"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceTimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceTimer"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceTimer",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcetimer"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime": {
      "abstract": [
        {
          "text": "A point in time relative to the default clock, with nanosecond precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTime"
        }
      ],
      "role": "symbol",
      "title": "DispatchTime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtime"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds, millisconds, microseconds, or nanoseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeInterval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/microseconds(_:)": {
      "abstract": [
        {
          "text": "A number of microseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/microseconds(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeInterval.microseconds(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval/microseconds(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/milliseconds(_:)": {
      "abstract": [
        {
          "text": "A number of milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "milliseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/milliseconds(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeInterval.milliseconds(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval/milliseconds(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/nanoseconds(_:)": {
      "abstract": [
        {
          "text": "A number of nanoseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nanoseconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/nanoseconds(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeInterval.nanoseconds(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval/nanoseconds(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/never": {
      "abstract": [
        {
          "text": "No interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "never"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/never",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeInterval.never",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval/never"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/seconds(_:)": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/seconds(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeInterval.seconds(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval/seconds(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult": {
      "abstract": [
        {
          "text": "A result value indicating whether a dispatch operation finished before a specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeoutResult"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeoutResult",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeoutresult"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime": {
      "abstract": [
        {
          "text": "An absolute point in time according to the wall clock, with microsecond precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWallTime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWallTime"
        }
      ],
      "role": "symbol",
      "title": "DispatchWallTime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchwalltime"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t": {
      "abstract": [
        {
          "text": "An abstract representation of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_time_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-Constructs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW",
        "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants"
      ],
      "title": "Time Constructs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/seconds(_:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/milliseconds(_:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/microseconds(_:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/nanoseconds(_:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval/never"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/title",
          "value": "dispatch_time_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_WALLTIME_NOW/title",
          "value": "DISPATCH_WALLTIME_NOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_WALLTIME_NOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_WALLTIME_NOW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchtimeinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
