{
  "abstract": [
    {
      "text": "A file descriptor used for I/O operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@dispatch_fd_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_fd_t"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_fd_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "dispatch_fd_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_fd_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_io"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_io",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_io"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t": {
      "abstract": [
        {
          "text": "A file descriptor used for I/O operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_fd_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_fd_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_fd_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create": {
      "abstract": [
        {
          "text": "Creates a dispatch I/O channel and associates it with the specified file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io": {
      "abstract": [
        {
          "text": "Creates a new dispatch I/O channel from an existing channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create_with_io"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create_with_io",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create_with_io"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path": {
      "abstract": [
        {
          "text": "Creates a dispatch I/O channel with the associated path name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create_with_path"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create_with_path",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create_with_path"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t": {
      "abstract": [
        {
          "text": "A dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_io_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t": {
      "abstract": [
        {
          "text": "The type of a dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_type_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_type_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_type_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Dispatch-IO-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t"
      ],
      "title": "Creating a Dispatch I/O Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/title",
          "value": "dispatch_io_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_fd_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
