{
  "abstract": [
    {
      "text": "Returns attributes suitable for creating a dispatch queue with the desired quality-of-service information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_qos_class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_queue_attr_make_with_qos_class",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_attr_make_with_qos_class"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_attr_make_with_qos_class"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_queue_attr_make_with_qos_class"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_attr_t",
              "text": "dispatch_queue_attr_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_attr_make_with_qos_class"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_attr_t",
              "text": "dispatch_queue_attr_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attr"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_qos_class_t",
              "text": "dispatch_qos_class_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "qos_class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "relative_priority"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A queue attribute value to be combined with the quality-of-service class. Specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " if you want submitted tasks to be scheduled serially or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " if tasks may be scheduled concurrently. If you specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", this function creates a serial queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attr"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The quality of service you want to give to tasks executed using this queue. Quality-of-service helps determine the priority given to tasks executed by the queue. Specify one of the values ",
                  "type": "text"
                },
                {
                  "code": "QOS_CLASS_USER_INTERACTIVE",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "QOS_CLASS_USER_INITIATED",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "QOS_CLASS_UTILITY",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "QOS_CLASS_BACKGROUND",
                  "type": "codeVoice"
                },
                {
                  "text": ". Queues that handle user-interactive or user-initiated tasks have a higher priority than tasks meant to run in the background.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "qos_class"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A negative offset from the maximum supported scheduler priority for the given quality-of-service class. This value must be less than ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " and greater than or equal to ",
                  "type": "text"
                },
                {
                  "code": "QOS_MIN_RELATIVE_PRIORITY",
                  "type": "codeVoice"
                },
                {
                  "text": ", or else this function returns ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "relative_priority"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An attribute value that may be passed to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_create",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function when creating a dispatch queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this function prior to calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_create",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function when you want to create a dispatch queue with a specific quality-of-service level. This function combines the queue type attributes with the quality-of-service information you specify and returns a value that you can pass to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_create",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. The quality-of-service value you specify using this function takes precedence over the priority level inherited from the dispatch queue’s target queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The global queue priorities map to the following quality-of-service classes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_HIGH",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " maps to the ",
                      "type": "text"
                    },
                    {
                      "code": "QOS_CLASS_USER_INITIATED",
                      "type": "codeVoice"
                    },
                    {
                      "text": " class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_DEFAULT",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " maps to the ",
                      "type": "text"
                    },
                    {
                      "code": "QOS_CLASS_DEFAULT",
                      "type": "codeVoice"
                    },
                    {
                      "text": " class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_LOW",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " maps to the ",
                      "type": "text"
                    },
                    {
                      "code": "QOS_CLASS_UTILITY",
                      "type": "codeVoice"
                    },
                    {
                      "text": " class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_BACKGROUND",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " maps to the ",
                      "type": "text"
                    },
                    {
                      "code": "QOS_CLASS_BACKGROUND",
                      "type": "codeVoice"
                    },
                    {
                      "text": " class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT": {
      "abstract": [
        {
          "text": "A dispatch queue that executes blocks concurrently.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_CONCURRENT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_QUEUE_CONCURRENT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_concurrent"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_BACKGROUND": {
      "abstract": [
        {
          "text": "Tasks run at the background priority, which is equivalent to the background quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_BACKGROUND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_BACKGROUND",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_background"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_DEFAULT": {
      "abstract": [
        {
          "text": "Tasks run at the default priority, which is equivalent to the default quality-of-service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_DEFAULT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_default"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_HIGH": {
      "abstract": [
        {
          "text": "Tasks run at the highest priority, which is equivalent to the user-initiated quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_HIGH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_HIGH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_HIGH"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_HIGH",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_high"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_LOW": {
      "abstract": [
        {
          "text": "Tasks run at a low priority, which is equivalent to the utility quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_LOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_LOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_LOW"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_LOW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_low"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL": {
      "abstract": [
        {
          "text": "A dispatch queue that executes blocks serially in FIFO order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_SERIAL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_QUEUE_SERIAL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_serial"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t": {
      "abstract": [
        {
          "text": "Constants indicating the frequency with which a dispatch queue creates autorelease pools for its tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_autorelease_frequency_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_autorelease_frequency_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_autorelease_frequency_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t": {
      "abstract": [
        {
          "text": "Quality-of-service classes that specify the priorities for executing tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_qos_class_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_qos_class_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_qos_class_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_initially_inactive": {
      "abstract": [
        {
          "text": "Returns an attribute that configures a dispatch queue as initially inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_make_initially_inactive"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_initially_inactive",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_attr_make_initially_inactive",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_make_initially_inactive"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_autorelease_frequency": {
      "abstract": [
        {
          "text": "Returns an attribute that specifies how the dispatch queue manages autorelease pools for the blocks it executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_make_with_autorelease_frequency"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_autorelease_frequency",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_attr_make_with_autorelease_frequency",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_make_with_autorelease_frequency"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_qos_class": {
      "abstract": [
        {
          "text": "Returns attributes suitable for creating a dispatch queue with the desired quality-of-service information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_make_with_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_attr_make_with_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_make_with_qos_class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t": {
      "abstract": [
        {
          "text": "Attributes describing the behaviors of a dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_attr_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_create": {
      "abstract": [
        {
          "text": "Creates a new dispatch queue to which you can submit blocks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class": {
      "abstract": [
        {
          "text": "Returns the quality-of-service class for the specified queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_get_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_get_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_get_qos_class"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Queue-Execution-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_initially_inactive",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_autorelease_frequency",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t"
      ],
      "title": "Configuring Queue Execution Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_attr_t/title",
          "value": "dispatch_queue_attr_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_attr_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_attr_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_attr_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_attr_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_LOW/title",
          "value": "DISPATCH_QUEUE_PRIORITY_LOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_LOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_LOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_HIGH/title",
          "value": "DISPATCH_QUEUE_PRIORITY_HIGH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_HIGH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_HIGH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_DEFAULT/title",
          "value": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_BACKGROUND/title",
          "value": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_BACKGROUND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_queue_attr_make_with_qos_class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
