{
  "abstract": [
    {
      "text": "Closes the specified channel to new read and write operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_io_close",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_io_close"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_io_close"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_io_close"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_io_close"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_io_t",
              "text": "dispatch_io_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "channel"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_io_close_flags_t",
              "text": "dispatch_io_close_flags_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The channel to close.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "channel"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options to use when closing the channel. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After calling this function, you should not schedule any more read or write operations on the channel. Doing so causes an error to be sent to your handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STOP",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " option is specified in the ",
              "type": "text"
            },
            {
              "code": "flags",
              "type": "codeVoice"
            },
            {
              "text": " parameter, the system attempts to interrupt any outstanding read and write operations on the I/O channel. Even if you specify this flag, the corresponding handlers may be invoked with partial results. In addition, the final invocation of the handler is passed the ",
              "type": "text"
            },
            {
              "code": "ECANCELED",
              "type": "codeVoice"
            },
            {
              "text": " error code to indicate that the operation was interrupted. If you do not specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STOP",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " flag, read and write operations on the channel run to completion as normal.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STOP": {
      "abstract": [
        {
          "text": "Stop any in-progress read and write operations when closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_IO_STOP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STOP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_IO_STOP"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_IO_STOP",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_stop"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close": {
      "abstract": [
        {
          "text": "Closes the specified channel to new read and write operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_close"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_close",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_close"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t": {
      "abstract": [
        {
          "text": "Additional flags to use when closing an I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_close_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_close_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_close_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t": {
      "abstract": [
        {
          "text": "A dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_io_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Closing-the-File",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t"
      ],
      "title": "Closing the File"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_IO_STOP/title",
          "value": "DISPATCH_IO_STOP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_IO_STOP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_IO_STOP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/title",
          "value": "dispatch_io_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_io_close"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
