{
  "abstract": [
    {
      "text": "The current time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@DISPATCH_WALLTIME_NOW@DISPATCH_WALLTIME_NOW",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DISPATCH_WALLTIME_NOW"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Su",
        "text": "UInt"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DISPATCH_WALLTIME_NOW"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DISPATCH_WALLTIME_NOW"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DISPATCH_WALLTIME_NOW"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Su",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Su",
              "text": "UInt"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants": {
      "abstract": [
        {
          "text": "Constants for wall time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Wall Time Constants",
      "type": "topic",
      "url": "/documentation/dispatch/2963138-wall-time-constants"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW": {
      "abstract": [
        {
          "text": "The current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_WALLTIME_NOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_WALLTIME_NOW"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_WALLTIME_NOW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_walltime_now"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime": {
      "abstract": [
        {
          "text": "A point in time relative to the default clock, with nanosecond precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTime"
        }
      ],
      "role": "symbol",
      "title": "DispatchTime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtime"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds, millisconds, microseconds, or nanoseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeInterval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult": {
      "abstract": [
        {
          "text": "A result value indicating whether a dispatch operation finished before a specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeoutResult"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeoutResult",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeoutresult"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime": {
      "abstract": [
        {
          "text": "An absolute point in time according to the wall clock, with microsecond precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWallTime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWallTime"
        }
      ],
      "role": "symbol",
      "title": "DispatchWallTime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchwalltime"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time": {
      "abstract": [
        {
          "text": "Creates a ",
          "type": "text"
        },
        {
          "code": "dispatch_time_t",
          "type": "codeVoice"
        },
        {
          "text": " relative to the default clock or modifies an existing ",
          "type": "text"
        },
        {
          "code": "dispatch_time_t",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_time"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_time",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t": {
      "abstract": [
        {
          "text": "An abstract representation of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_time_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_walltime": {
      "abstract": [
        {
          "text": "Creates a ",
          "type": "text"
        },
        {
          "code": "dispatch_time_t",
          "type": "codeVoice"
        },
        {
          "text": " using an absolute time according to the wall clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_walltime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_walltime",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_walltime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_walltime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Su": {
      "abstract": [
        {
          "text": "An unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Su",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt",
      "type": "topic",
      "url": "/documentation/Swift/UInt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-Constructs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
        "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants"
      ],
      "title": "Time Constructs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DISPATCH_WALLTIME_NOW"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_WALLTIME_NOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dispatch/documentation/Dispatch"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Time-Constructs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_walltime",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
                "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants"
              ],
              "title": "Time Constructs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "DISPATCH_WALLTIME_NOW"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/title",
          "value": "dispatch_time_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_WALLTIME_NOW/title",
          "value": "DISPATCH_WALLTIME_NOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_WALLTIME_NOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_WALLTIME_NOW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_walltime_now"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch_walltime_now"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
