{
  "abstract": [
    {
      "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch Source"
  },
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "role": "symbol",
      "title": "DispatchData",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator": {
      "abstract": [
        {
          "text": "A byte-by-byte iterator over the contents of a dispatch data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "role": "symbol",
      "title": "DispatchDataIterator",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdataiterator"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "role": "symbol",
      "title": "DispatchSource",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsource"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol": {
      "abstract": [
        {
          "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch I/O",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-i-o"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_cancel": {
      "abstract": [
        {
          "text": "Asynchronously cancels the dispatch source, preventing any further invocation of its event handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_cancel"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_cancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_cancel",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_cancel"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_create": {
      "abstract": [
        {
          "text": "Creates a new dispatch source to monitor low-level system events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data": {
      "abstract": [
        {
          "text": "Returns pending data for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle": {
      "abstract": [
        {
          "text": "Returns the underlying system handle associated with the specified dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_handle"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_handle",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_handle"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask": {
      "abstract": [
        {
          "text": "Returns the mask of events monitored by the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_mask"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_mask",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_mask"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t": {
      "abstract": [
        {
          "text": "Mach receive-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_source_mach_recv_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_recv_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t": {
      "abstract": [
        {
          "text": "Mach send-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_send_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_mach_send_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_send_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t": {
      "abstract": [
        {
          "text": "Memory pressure events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_memorypressure_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_memorypressure_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_memorypressure_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data": {
      "abstract": [
        {
          "text": "Merges data into a dispatch source and submits its event handler block to its target queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_merge_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_merge_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_merge_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t": {
      "abstract": [
        {
          "text": "Events related to a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_proc_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_proc_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_proc_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_cancel_handler": {
      "abstract": [
        {
          "text": "Sets the cancellation handler block for the given dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_cancel_handler"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_cancel_handler",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_cancel_handler",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_cancel_handler"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_cancel_handler_f": {
      "abstract": [
        {
          "text": "Sets the cancellation handler function for the given dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_cancel_handler_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_cancel_handler_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_cancel_handler_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_cancel_handler_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_event_handler": {
      "abstract": [
        {
          "text": "Sets the event handler block for the given dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_event_handler"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_event_handler",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_event_handler",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_event_handler"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_event_handler_f": {
      "abstract": [
        {
          "text": "Sets the event handler function for the given dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_event_handler_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_event_handler_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_event_handler_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_event_handler_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_registration_handler": {
      "abstract": [
        {
          "text": "Sets the registration handler block for the given dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_registration_handler"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_registration_handler",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_registration_handler",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_registration_handler"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_registration_handler_f": {
      "abstract": [
        {
          "text": "Sets the registration handler function for the given dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_registration_handler_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_registration_handler_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_registration_handler_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_registration_handler_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_timer": {
      "abstract": [
        {
          "text": "Sets a start time, interval, and leeway value for a timer source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_set_timer"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_timer",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_set_timer",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_set_timer"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_source_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_source_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_source_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_testcancel": {
      "abstract": [
        {
          "text": "Tests whether the given dispatch source has been canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_testcancel"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_testcancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_testcancel",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_testcancel"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_timer_flags_t": {
      "abstract": [
        {
          "text": "Flags to use when configuring a timer dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_timer_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_timer_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_timer_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_timer_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_type_t": {
      "abstract": [
        {
          "text": "An identifier for the type of system object being monitored by a dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_type_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_type_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_type_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t": {
      "abstract": [
        {
          "text": "Events involving a change to a file system object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_vnode_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_vnode_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_vnode_flags_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-Event-Monitoring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
      ],
      "title": "System Event Monitoring"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-Source",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t"
      ],
      "title": "Creating a Dispatch Source"
    },
    {
      "anchor": "Getting-Dispatch-Source-Attributes",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t"
      ],
      "title": "Getting Dispatch Source Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Dispatch-Source",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_create",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_type_t"
              ],
              "title": "Creating a Dispatch Source"
            },
            {
              "anchor": "Managing-Event-Handlers",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_registration_handler_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_registration_handler",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_event_handler_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_event_handler",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_cancel_handler_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_cancel_handler"
              ],
              "title": "Managing Event Handlers"
            },
            {
              "anchor": "Getting-Dispatch-Source-Attributes",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t"
              ],
              "title": "Getting Dispatch Source Attributes"
            },
            {
              "anchor": "Managing-Timer-Parameters",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_set_timer",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_timer_flags_t"
              ],
              "title": "Managing Timer Parameters"
            },
            {
              "anchor": "Canceling-a-Dispatch-Source",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_cancel",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_testcancel"
              ],
              "title": "Canceling a Dispatch Source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-Event-Monitoring",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
              ],
              "title": "System Event Monitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_t/title",
          "value": "dispatch_source_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/title",
          "value": "dispatch_source_mach_recv_flags_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-source"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-source"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
