{
  "abstract": [
    {
      "text": "A group of tasks that you monitor as a single unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)OS_dispatch_group",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DispatchGroup"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DispatchGroup"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DispatchGroup"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DispatchGroup"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Groups allow you to aggregate a set of tasks and synchronize behaviors on the group. You attach multiple work items to a group and schedule them for asynchronous execution on the same queue or different queues. When all work items finish executing, the group executes its completion handler. You can also wait synchronously for all tasks in the group to finish executing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup": {
      "abstract": [
        {
          "text": "A group of tasks that you monitor as a single unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchGroup"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchGroup"
        }
      ],
      "role": "symbol",
      "title": "DispatchGroup",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()": {
      "abstract": [
        {
          "text": "Explicitly indicates that a block has entered the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enter"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_enter"
        }
      ],
      "role": "symbol",
      "title": "enter()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/enter()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()": {
      "abstract": [
        {
          "text": "Creates a new group to which you can assign block objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_create"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/init()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()": {
      "abstract": [
        {
          "text": "Explicitly indicates that a block in the group finished executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leave"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_leave"
        }
      ],
      "role": "symbol",
      "title": "leave()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/leave()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/notify(qos:flags:queue:execute:)": {
      "abstract": [
        {
          "text": "Schedules the submission of a block with the specified attributes to a queue when all tasks in the current group have finished executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notify"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
          "text": "DispatchWorkItemFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/notify(qos:flags:queue:execute:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "notify(qos:flags:queue:execute:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/notify(qos:flags:queue:execute:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/notify(queue:work:)": {
      "abstract": [
        {
          "text": "Schedules the submission of a block to a queue when all tasks in the current group have finished executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notify"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "work"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WorkItemC",
          "text": "DispatchWorkItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/notify(queue:work:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "notify(queue:work:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/notify(queue:work:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait()": {
      "abstract": [
        {
          "text": "Waits synchronously for the previously submitted work to finish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait()",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/wait()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait(timeout:)": {
      "abstract": [
        {
          "text": "Waits synchronously for the previously submitted work to complete, and returns if the work is not completed before the specified timeout period has elapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4TimeV",
          "text": "DispatchTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13TimeoutResultO",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait(timeout:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait(timeout:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/wait(timeout:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait(wallTimeout:)": {
      "abstract": [
        {
          "text": "Waits synchronously for the previously submitted work to complete, and returns if the work is not completed before the specified timeout period has elapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "wallTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WallTimeV",
          "text": "DispatchWallTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13TimeoutResultO",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait(wallTimeout:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait(wallTimeout:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/wait(walltimeout:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject": {
      "abstract": [
        {
          "text": "The base class for most dispatch types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchObject"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchObject"
        }
      ],
      "role": "symbol",
      "title": "DispatchObject",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchobject"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem": {
      "abstract": [
        {
          "text": "The work you want to perform, encapsulated in a way that lets you attach a completion handle or execution dependencies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWorkItem"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWorkItem"
        }
      ],
      "role": "symbol",
      "title": "DispatchWorkItem",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchworkitem"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group": {
      "abstract": [
        {
          "text": "A group of tasks that you monitor as a single unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Group",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-group"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item": {
      "abstract": [
        {
          "text": "The work you want to perform, encapsulated in a way that lets you attach a completion handle or execution dependencies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Work Item",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-work-item"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/workloop": {
      "abstract": [
        {
          "text": "A dispatch object that prioritizes the execution of tasks based on their quality-of-service (QoS) level.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/workloop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workloop",
      "type": "topic",
      "url": "/documentation/dispatch/workloop"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queues-and-Tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group",
        "doc://com.apple.dispatch/documentation/Dispatch/workloop"
      ],
      "title": "Queues and Tasks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-Group",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()"
      ],
      "title": "Creating a Dispatch Group"
    },
    {
      "anchor": "Adding-a-Completion-Handler",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/notify(qos:flags:queue:execute:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/notify(queue:work:)"
      ],
      "title": "Adding a Completion Handler"
    },
    {
      "anchor": "Waiting-for-Tasks-to-Finish-Executing",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait(timeout:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/wait(wallTimeout:)"
      ],
      "title": "Waiting for Tasks to Finish Executing"
    },
    {
      "anchor": "Updating-the-Group-Manually",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()"
      ],
      "title": "Updating the Group Manually"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1enter()/title",
          "value": "dispatch_group_enter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1enter()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_enter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1init()/title",
          "value": "dispatch_group_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1init()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1leave()/title",
          "value": "dispatch_group_leave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1leave()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_leave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchgroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
