{
  "abstract": [
    {
      "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch Data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The memory buffer managed by this object may be a single contiguous block of memory, or it may consist of multiple discontiguous blocks. For the discontiguous case, the dispatch data object makes it appear as if the memory is contiguous.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_DEFAULT": {
      "abstract": [
        {
          "text": "The default data destructor for dispatch objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DESTRUCTOR_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DESTRUCTOR_DEFAULT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_destructor_default"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_FREE": {
      "abstract": [
        {
          "text": "The destructor for dispatch data objects whose memory buffer was created using the malloc family of allocation routines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DESTRUCTOR_FREE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_FREE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DESTRUCTOR_FREE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_destructor_free"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "role": "symbol",
      "title": "DispatchData",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator": {
      "abstract": [
        {
          "text": "A byte-by-byte iterator over the contents of a dispatch data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "role": "symbol",
      "title": "DispatchDataIterator",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdataiterator"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "role": "symbol",
      "title": "DispatchSource",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsource"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol": {
      "abstract": [
        {
          "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_data": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_data",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch I/O",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-i-o"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Source",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-source"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_applier_t": {
      "abstract": [
        {
          "text": "A block to invoke for every contiguous memory region in a data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_applier_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_applier_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_applier_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_applier_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_apply": {
      "abstract": [
        {
          "text": "Traverses the memory of a dispatch data object and executes custom code on each region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_apply"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_apply",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_apply",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_apply"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_copy_region": {
      "abstract": [
        {
          "text": "Returns a data object containing a portion of the data in another data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_copy_region"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_copy_region",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_copy_region",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_copy_region"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create": {
      "abstract": [
        {
          "text": "Creates a new dispatch data object with the specified memory buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_concat": {
      "abstract": [
        {
          "text": "Returns a new dispatch data object consisting of the concatenated data from two other data objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create_concat"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_concat",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create_concat",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create_concat"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_map": {
      "abstract": [
        {
          "text": "Returns a new dispatch data object containing a contiguous representation of the specified object’s memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create_map"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_map",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create_map",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create_map"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_subrange": {
      "abstract": [
        {
          "text": "Returns a new dispatch data object whose contents consist of a portion of another object’s memory region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create_subrange"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_subrange",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create_subrange",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create_subrange"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_empty": {
      "abstract": [
        {
          "text": "A dispatch data object representing a zero-length memory region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_empty"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_empty",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_empty",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_empty"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_get_size": {
      "abstract": [
        {
          "text": "Returns the logical size of the memory managed by a dispatch data object",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_get_size"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_get_size",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_get_size",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_get_size"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t": {
      "abstract": [
        {
          "text": "An immutable object representing a contiguous or sparse region of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_data_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_data_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_data_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-Event-Monitoring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
      ],
      "title": "System Event Monitoring"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-Data-Object",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t"
      ],
      "title": "Creating a Dispatch Data Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Dispatch-Data-Object",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_map",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_concat",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_subrange",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_copy_region",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_empty",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
                "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_data",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_DEFAULT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_FREE"
              ],
              "title": "Creating a Dispatch Data Object"
            },
            {
              "anchor": "Getting-the-Number-of-Elements",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_get_size"
              ],
              "title": "Getting the Number of Elements"
            },
            {
              "anchor": "Applying-Changes-to-the-Data",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_apply",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_applier_t"
              ],
              "title": "Applying Changes to the Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-Event-Monitoring",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
              ],
              "title": "System Event Monitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_data_t/title",
          "value": "dispatch_data_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_data_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_data_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_data_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
