{
  "abstract": [
    {
      "text": "An object that controls access to a resource across multiple execution contexts through use of a traditional counting semaphore.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)OS_dispatch_semaphore",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DispatchSemaphore"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DispatchSemaphore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DispatchSemaphore"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DispatchSemaphore"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A dispatch semaphore is an efficient implementation of a traditional counting semaphore. Dispatch semaphores call down to the kernel only when the calling thread needs to be blocked. If the calling semaphore does not need to block, no kernel call is made.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You increment a semaphore count by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/signal()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, and decrement a semaphore count by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or one of its variants that specifies a timeout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject": {
      "abstract": [
        {
          "text": "The base class for most dispatch types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchObject"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchObject"
        }
      ],
      "role": "symbol",
      "title": "DispatchObject",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchobject"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore": {
      "abstract": [
        {
          "text": "An object that controls access to a resource across multiple execution contexts through use of a traditional counting semaphore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSemaphore"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSemaphore"
        }
      ],
      "role": "symbol",
      "title": "DispatchSemaphore",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/init(value:)": {
      "abstract": [
        {
          "text": "Creates new counting semaphore with an initial value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/init(value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_semaphore_create"
        }
      ],
      "role": "symbol",
      "title": "init(value:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore/init(value:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/signal()": {
      "abstract": [
        {
          "text": "Signals (increments) a semaphore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/signal()",
      "kind": "symbol",
      "role": "symbol",
      "title": "signal()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore/signal()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait()": {
      "abstract": [
        {
          "text": "Waits for, or decrements, a semaphore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait()",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore/wait()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait(timeout:)": {
      "abstract": [
        {
          "text": "Waits for, or decrements, a semaphore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4TimeV",
          "text": "DispatchTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13TimeoutResultO",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait(timeout:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait(timeout:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore/wait(timeout:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait(wallTimeout:)": {
      "abstract": [
        {
          "text": "Waits for, or decrements, a semaphore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "wallTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WallTimeV",
          "text": "DispatchWallTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13TimeoutResultO",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait(wallTimeout:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait(wallTimeout:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsemaphore/wait(walltimeout:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-barrier": {
      "abstract": [
        {
          "text": "A synchronization point for tasks executing in a concurrent dispatch queue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-barrier",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Barrier",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-barrier"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore": {
      "abstract": [
        {
          "text": "An object that controls access to a resource across multiple execution contexts through use of a traditional counting semaphore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Semaphore",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-semaphore"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Task-Synchronization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-semaphore",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-barrier"
      ],
      "title": "Task Synchronization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Semaphore",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/init(value:)"
      ],
      "title": "Creating a Semaphore"
    },
    {
      "anchor": "Signaling-the-Semaphore",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/signal()"
      ],
      "title": "Signaling the Semaphore"
    },
    {
      "anchor": "Blocking-on-the-Semaphore",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait(timeout:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSemaphore/wait(wallTimeout:)"
      ],
      "title": "Blocking on the Semaphore"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSemaphore~1init(value:)/title",
          "value": "dispatch_semaphore_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSemaphore~1init(value:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_semaphore_create"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchsemaphore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
