{
  "abstract": [
    {
      "text": "Enqueues a block for execution at the specified time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_after",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_after"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_after"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_after"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_after"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_time_t",
              "text": "dispatch_time_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "when"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_block_t",
              "text": "dispatch_block_t"
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The temporal milestone ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_walltime",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " returns.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "when"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The queue on which to submit the block. The system retains the queue until the block runs to completion. This parameter cannot be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to submit.  This function performs a ",
                  "type": "text"
                },
                {
                  "code": "Block_copy",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "Block_release",
                  "type": "codeVoice"
                },
                {
                  "text": " on behalf of the caller. This parameter cannot be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "block"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function waits until the specified time and then asynchronously adds ",
              "type": "text"
            },
            {
              "code": "block",
              "type": "codeVoice"
            },
            {
              "text": " to the specified ",
              "type": "text"
            },
            {
              "code": "queue",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Passing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TIME_NOW",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as the ",
              "type": "text"
            },
            {
              "code": "when",
              "type": "codeVoice"
            },
            {
              "text": " parameter is supported, but is not as optimal as calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead. Passing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TIME_FOREVER",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is undefined.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TIME_FOREVER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_TIME_FOREVER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TIME_FOREVER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_TIME_FOREVER"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_TIME_FOREVER",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time_forever"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TIME_NOW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_TIME_NOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TIME_NOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_TIME_NOW"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_TIME_NOW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time_now"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after": {
      "abstract": [
        {
          "text": "Enqueues a block for execution at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_after"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_after",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_after"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after_f": {
      "abstract": [
        {
          "text": "Enqueues an app-defined function for execution at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_after_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_after_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_after_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async": {
      "abstract": [
        {
          "text": "Submits a block for asynchronous execution on a dispatch queue and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_async"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_async",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_async"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_f": {
      "abstract": [
        {
          "text": "Submits an app-defined function for asynchronous execution on a dispatch queue and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_async_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_async_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_async_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t": {
      "abstract": [
        {
          "text": "The prototype of blocks submitted to dispatch queues, which take no arguments and have no return value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_block_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_block_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_block_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_function_t": {
      "abstract": [
        {
          "text": "The prototype of functions submitted to dispatch queues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_function_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_function_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_function_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_function_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time": {
      "abstract": [
        {
          "text": "Creates a ",
          "type": "text"
        },
        {
          "code": "dispatch_time_t",
          "type": "codeVoice"
        },
        {
          "text": " relative to the default clock or modifies an existing ",
          "type": "text"
        },
        {
          "code": "dispatch_time_t",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_time"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_time",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t": {
      "abstract": [
        {
          "text": "An abstract representation of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_time_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_walltime": {
      "abstract": [
        {
          "text": "Creates a ",
          "type": "text"
        },
        {
          "code": "dispatch_time_t",
          "type": "codeVoice"
        },
        {
          "text": " using an absolute time according to the wall clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_walltime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_walltime",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_walltime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_walltime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Executing-Tasks-Asynchronously",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_f",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after_f",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_function_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t"
      ],
      "title": "Executing Tasks Asynchronously"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_TIME_FOREVER/title",
          "value": "DISPATCH_TIME_FOREVER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_TIME_FOREVER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_TIME_FOREVER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/title",
          "value": "dispatch_time_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/title",
          "value": "dispatch_queue_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_TIME_NOW/title",
          "value": "DISPATCH_TIME_NOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_TIME_NOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_TIME_NOW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_after"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
