{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch Functions"
  },
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Constants",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-constants"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Data Types",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-data-types"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_allow_send_signals(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_allow_send_signals"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_allow_send_signals(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_allow_send_signals"
        }
      ],
      "role": "symbol",
      "title": "dispatch_allow_send_signals(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_allow_send_signals(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_os_workgroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_set_os_workgroup"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_os_workgroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_workloop_set_os_workgroup",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_set_os_workgroup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-constants",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_allow_send_signals(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_allow_send_signals(_:)",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_os_workgroup"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-constants",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_allow_send_signals(_:)/title",
          "value": "dispatch_allow_send_signals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_allow_send_signals(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_allow_send_signals"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
