{
  "abstract": [
    {
      "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch I/O"
  },
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "role": "symbol",
      "title": "DispatchData",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator": {
      "abstract": [
        {
          "text": "A byte-by-byte iterator over the contents of a dispatch data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "role": "symbol",
      "title": "DispatchDataIterator",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdataiterator"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/barrier(execute:)": {
      "abstract": [
        {
          "text": "Schedules a barrier operation on the specified channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barrier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/barrier(execute:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_barrier"
        }
      ],
      "role": "symbol",
      "title": "barrier(execute:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/barrier(execute:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor": {
      "abstract": [
        {
          "text": "Returns the file descriptor associated with the specified channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_get_descriptor"
        }
      ],
      "role": "symbol",
      "title": "fileDescriptor",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/filedescriptor"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)": {
      "abstract": [
        {
          "text": "Sets the maximum number of bytes to process before enqueueing a handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "highWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_high_water"
        }
      ],
      "role": "symbol",
      "title": "setLimit(highWater:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setlimit(highwater:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)": {
      "abstract": [
        {
          "text": "Sets the minimum number of bytes to process before enqueueing a handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lowWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_low_water"
        }
      ],
      "role": "symbol",
      "title": "setLimit(lowWater:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setlimit(lowwater:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "role": "symbol",
      "title": "DispatchSource",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsource"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol": {
      "abstract": [
        {
          "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_io"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_io",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_io"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Source",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-source"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t": {
      "abstract": [
        {
          "text": "A file descriptor used for I/O operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_fd_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_fd_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_fd_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close": {
      "abstract": [
        {
          "text": "Closes the specified channel to new read and write operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_close"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_close",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_close"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t": {
      "abstract": [
        {
          "text": "Additional flags to use when closing an I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_close_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_close_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_close_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create": {
      "abstract": [
        {
          "text": "Creates a dispatch I/O channel and associates it with the specified file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io": {
      "abstract": [
        {
          "text": "Creates a new dispatch I/O channel from an existing channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create_with_io"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create_with_io",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create_with_io"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path": {
      "abstract": [
        {
          "text": "Creates a dispatch I/O channel with the associated path name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create_with_path"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create_with_path",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create_with_path"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_handler_t": {
      "abstract": [
        {
          "text": "A handler block used to process operations on a dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_handler_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_handler_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_handler_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_handler_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_interval_flags_t": {
      "abstract": [
        {
          "text": "The desired delivery behavior for interval events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_interval_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_interval_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_interval_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_interval_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_read": {
      "abstract": [
        {
          "text": "Schedules an asynchronous read operation on the specified channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_read"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_read",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_read",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_read"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_set_interval": {
      "abstract": [
        {
          "text": "Sets the interval (in nanoseconds) at which to invoke the I/O handlers for the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_interval"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_set_interval",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_set_interval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_set_interval"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t": {
      "abstract": [
        {
          "text": "A dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_io_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t": {
      "abstract": [
        {
          "text": "The type of a dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_type_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_type_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_type_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_write": {
      "abstract": [
        {
          "text": "Schedules an asynchronous write operation for the specified channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_write"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_write",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_write",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_write"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_read": {
      "abstract": [
        {
          "text": "Schedules an asynchronous read operation using the specified file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_read"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_read",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_read",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_read"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_write": {
      "abstract": [
        {
          "text": "Schedules an asynchronous write operation using the specified file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_write"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_write",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_write",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_write"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-Event-Monitoring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
      ],
      "title": "System Event Monitoring"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-IO-Object",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t"
      ],
      "title": "Creating a Dispatch I/O Object"
    },
    {
      "anchor": "Managing-the-File-Descriptor",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)"
      ],
      "title": "Managing the File Descriptor"
    },
    {
      "anchor": "Synchronizing-File-Operations",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/barrier(execute:)"
      ],
      "title": "Synchronizing File Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Dispatch-IO-Object",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t",
                "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t"
              ],
              "title": "Creating a Dispatch I/O Object"
            },
            {
              "anchor": "Reading-from-the-File",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_read",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_read",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_handler_t"
              ],
              "title": "Reading from the File"
            },
            {
              "anchor": "Writing-to-the-File",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_write",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_write"
              ],
              "title": "Writing to the File"
            },
            {
              "anchor": "Closing-the-File",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close_flags_t"
              ],
              "title": "Closing the File"
            },
            {
              "anchor": "Managing-the-File-Descriptor",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_set_interval",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_interval_flags_t",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)"
              ],
              "title": "Managing the File Descriptor"
            },
            {
              "anchor": "Synchronizing-File-Operations",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/barrier(execute:)"
              ],
              "title": "Synchronizing File Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-Event-Monitoring",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
              ],
              "title": "System Event Monitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1barrier(execute:)/title",
          "value": "dispatch_io_barrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1barrier(execute:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_barrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/title",
          "value": "dispatch_io_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(lowWater:)/title",
          "value": "dispatch_io_set_low_water"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(lowWater:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_set_low_water"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(highWater:)/title",
          "value": "dispatch_io_set_high_water"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(highWater:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_set_high_water"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1fileDescriptor/title",
          "value": "dispatch_io_get_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1fileDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_get_descriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-i-o"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-i-o"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
