{
  "abstract": [
    {
      "text": "Events related to a process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@dispatch_source_proc_flags_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_source_proc_flags_t"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_source_proc_flags_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "dispatch_source_proc_flags_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:l",
              "text": "unsigned long"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_source_proc_flags_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_EXEC": {
      "abstract": [
        {
          "text": "The process became another executable image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_EXEC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_EXEC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_EXEC"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_PROC_EXEC",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_proc_exec"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_EXIT": {
      "abstract": [
        {
          "text": "The process has exited (perhaps cleanly, perhaps not).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_EXIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_EXIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_EXIT"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_PROC_EXIT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_proc_exit"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_FORK": {
      "abstract": [
        {
          "text": "The process created one or more child processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_FORK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_FORK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_FORK"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_PROC_FORK",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_proc_fork"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_SIGNAL": {
      "abstract": [
        {
          "text": "The process received a UNIX signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_SIGNAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_SIGNAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_PROC_SIGNAL"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_PROC_SIGNAL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_proc_signal"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data": {
      "abstract": [
        {
          "text": "Returns pending data for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle": {
      "abstract": [
        {
          "text": "Returns the underlying system handle associated with the specified dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_handle"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_handle",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_handle"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask": {
      "abstract": [
        {
          "text": "Returns the mask of events monitored by the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_mask"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_mask",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_mask"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t": {
      "abstract": [
        {
          "text": "Mach receive-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_source_mach_recv_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_recv_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t": {
      "abstract": [
        {
          "text": "Mach send-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_send_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_mach_send_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_send_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t": {
      "abstract": [
        {
          "text": "Memory pressure events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_memorypressure_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_memorypressure_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_memorypressure_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data": {
      "abstract": [
        {
          "text": "Merges data into a dispatch source and submits its event handler block to its target queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_merge_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_merge_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_merge_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t": {
      "abstract": [
        {
          "text": "Events related to a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_proc_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_proc_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_proc_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t": {
      "abstract": [
        {
          "text": "Events involving a change to a file system object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_vnode_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_vnode_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_vnode_flags_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Dispatch-Source-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t"
      ],
      "title": "Getting Dispatch Source Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Process-Event-Flags",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_EXEC",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_EXIT",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_FORK",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PROC_SIGNAL"
      ],
      "title": "Process Event Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_EXEC/title",
          "value": "DISPATCH_PROC_EXEC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_EXEC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_PROC_EXEC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_EXIT/title",
          "value": "DISPATCH_PROC_EXIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_EXIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_PROC_EXIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_FORK/title",
          "value": "DISPATCH_PROC_FORK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_FORK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_PROC_FORK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_SIGNAL/title",
          "value": "DISPATCH_PROC_SIGNAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_PROC_SIGNAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_PROC_SIGNAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/title",
          "value": "dispatch_source_mach_recv_flags_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_source_proc_flags_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
