{
  "abstract": [
    {
      "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8Dispatch0A4DataV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DispatchData"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DispatchData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "DispatchData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DispatchData"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The memory buffer managed by this object may be a single contiguous block of memory, or it may consist of multiple discontiguous blocks. For the discontiguous case, the dispatch data object makes it appear as if the memory is contiguous.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "role": "symbol",
      "title": "DispatchData",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/Deallocator": {
      "abstract": [
        {
          "text": "Memory deallocators for dispatch data objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Deallocator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/Deallocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Deallocator"
        }
      ],
      "role": "symbol",
      "title": "DispatchData.Deallocator",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/deallocator"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/Region": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Region"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/Region",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Region"
        }
      ],
      "role": "symbol",
      "title": "DispatchData.Region",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/region"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-1m94x": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SW",
          "text": "UnsafeRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-1m94x",
      "kind": "symbol",
      "role": "symbol",
      "title": "append(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/append(_:)-1m94x"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-3bvdr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-3bvdr",
      "kind": "symbol",
      "role": "symbol",
      "title": "append(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/append(_:)-3bvdr"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-9sgkq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "SourceType"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "SourceType"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-9sgkq",
      "kind": "symbol",
      "role": "symbol",
      "title": "append(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/append(_:)-9sgkq"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:count:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:count:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "append(_:count:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/append(_:count:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-3j0qx": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sw",
          "text": "UnsafeMutableRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-3j0qx",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyBytes(to:count:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/copybytes(to:count:)-3j0qx"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-4ffyj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-4ffyj",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyBytes(to:count:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/copybytes(to:count:)-4ffyj"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-60yai": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sw",
          "text": "UnsafeMutableRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV5Indexa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-60yai",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyBytes(to:from:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/copybytes(to:from:)-60yai"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-6ztcb": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV5Indexa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-6ztcb",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyBytes(to:from:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/copybytes(to:from:)-6ztcb"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-7zz4y": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyBytes"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "DestinationType"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sr",
          "text": "UnsafeMutableBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "DestinationType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV5Indexa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-7zz4y",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyBytes(to:from:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/copybytes(to:from:)-7zz4y"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/empty": {
      "abstract": [
        {
          "text": "A dispatch data object representing a zero-length memory region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "empty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/empty",
      "kind": "symbol",
      "role": "symbol",
      "title": "empty",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/empty"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateBytes"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "enumerateBytes(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/enumeratebytes(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(block:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "block"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(block:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "enumerateBytes(block:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/enumeratebytes(block:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytes:)-9lrd": {
      "abstract": [
        {
          "text": "Creates a new dispatch data object from the specified memory buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SW",
          "text": "UnsafeRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytes:)-9lrd",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytes:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/init(bytes:)-9lrd"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytes:)-mkbp": {
      "abstract": [
        {
          "text": "Initialize a data object with copied memory content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytes:)-mkbp",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytes:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/init(bytes:)-mkbp"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytesNoCopy:deallocator:)-7h08w": {
      "abstract": [
        {
          "text": "Initialize a data object without copying the bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV11DeallocatorO",
          "text": "Deallocator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytesNoCopy:deallocator:)-7h08w",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytesNoCopy:deallocator:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/init(bytesnocopy:deallocator:)-7h08w"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytesNoCopy:deallocator:)-vfoe": {
      "abstract": [
        {
          "text": "Creates a new dispatch data object using the specified memory buffer and deallocator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytesNoCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SW",
          "text": "UnsafeRawBufferPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV11DeallocatorO",
          "text": "Deallocator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytesNoCopy:deallocator:)-vfoe",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytesNoCopy:deallocator:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/init(bytesnocopy:deallocator:)-vfoe"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/makeIterator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeIterator"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV8Iteratora",
          "text": "Iterator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/makeIterator()",
      "kind": "symbol",
      "role": "symbol",
      "title": "makeIterator()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/makeiterator()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/region(location:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "region"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": ", offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/region(location:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "region(location:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/region(location:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subdata(in:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subdata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV5Indexa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subdata(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subdata(in:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/subdata(in:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subscript(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV5Indexa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subscript(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/subscript(_:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/withUnsafeBytes(body:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeBytes"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "ContentType"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "ContentType"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/withUnsafeBytes(body:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeBytes(body:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata/withunsafebytes(body:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator": {
      "abstract": [
        {
          "text": "A byte-by-byte iterator over the contents of a dispatch data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "role": "symbol",
      "title": "DispatchDataIterator",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdataiterator"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "role": "symbol",
      "title": "DispatchSource",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsource"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol": {
      "abstract": [
        {
          "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch I/O",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-i-o"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Source",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-source"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation12DataProtocolP": {
      "abstract": [
        {
          "text": "A protocol that provides consistent data access to the bytes underlying contiguous and noncontiguous data buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "DataProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12DataProtocolP",
      "kind": "symbol",
      "role": "symbol",
      "title": "DataProtocol",
      "type": "topic",
      "url": "/documentation/foundation/dataprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SK": {
      "abstract": [
        {
          "text": "A collection that supports backward as well as forward traversal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl",
          "text": "Collection"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SK",
      "kind": "symbol",
      "role": "symbol",
      "title": "BidirectionalCollection",
      "type": "topic",
      "url": "/documentation/Swift/BidirectionalCollection"
    },
    "doc://com.externally.resolved.symbol/s:ST": {
      "abstract": [
        {
          "text": "A type that provides sequential, iterated access to its elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sequence"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ST",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sequence",
      "type": "topic",
      "url": "/documentation/Swift/Sequence"
    },
    "doc://com.externally.resolved.symbol/s:Sk": {
      "abstract": [
        {
          "text": "A collection that supports efficient random-access index traversal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RandomAccessCollection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7IndicesQa",
          "text": "Indices"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk",
          "text": "RandomAccessCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sk",
          "text": "RandomAccessCollection"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sk",
      "kind": "symbol",
      "role": "symbol",
      "title": "RandomAccessCollection",
      "type": "topic",
      "url": "/documentation/Swift/RandomAccessCollection"
    },
    "doc://com.externally.resolved.symbol/s:Sl": {
      "abstract": [
        {
          "text": "A sequence whose elements can be traversed multiple times, nondestructively, and accessed by an indexed subscript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Collection"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST",
          "text": "Sequence"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sl",
      "kind": "symbol",
      "role": "symbol",
      "title": "Collection",
      "type": "topic",
      "url": "/documentation/Swift/Collection"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SK",
        "doc://com.externally.resolved.symbol/s:Sl",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:10Foundation12DataProtocolP",
        "doc://com.externally.resolved.symbol/s:Sk",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:ST"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-Event-Monitoring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
      ],
      "title": "System Event Monitoring"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-Data-Structure",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytes:)-9lrd",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytesNoCopy:deallocator:)-vfoe",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/withUnsafeBytes(body:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/Deallocator",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/empty"
      ],
      "title": "Creating a Dispatch Data Structure"
    },
    {
      "anchor": "Appending-Data-to-the-Buffer",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-3bvdr",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-9sgkq",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-1m94x"
      ],
      "title": "Appending Data to the Buffer"
    },
    {
      "anchor": "Copying-Bytes",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-3j0qx",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-7zz4y",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-60yai"
      ],
      "title": "Copying Bytes"
    },
    {
      "anchor": "Accessing-Buffer-Data",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subscript(_:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/region(location:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/Region"
      ],
      "title": "Accessing Buffer Data"
    },
    {
      "anchor": "Iterating-Over-the-Buffer-Contents",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/makeIterator()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(_:)"
      ],
      "title": "Iterating Over the Buffer Contents"
    },
    {
      "anchor": "Retrieving-Buffer-Subsequences",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subdata(in:)"
      ],
      "title": "Retrieving Buffer Subsequences"
    },
    {
      "anchor": "Combining-Sequence-Elements",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-3bvdr",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-9sgkq",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:)-1m94x",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:count:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-4ffyj",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-3j0qx",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-7zz4y",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-6ztcb",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-60yai",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(_:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/makeIterator()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/region(location:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/subdata(in:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/withUnsafeBytes(body:)"
      ],
      "title": "Combining Sequence Elements"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytes:)-mkbp",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/init(bytesNoCopy:deallocator:)-7h08w",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/append(_:count:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:count:)-4ffyj",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/copyBytes(to:from:)-6ztcb"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData/enumerateBytes(block:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
