{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PURE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@DISPATCH_PURE",
    "fragments": [
      {
        "kind": "identifier",
        "text": "DISPATCH_PURE"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DISPATCH_PURE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "DISPATCH_PURE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DISPATCH_PURE"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALIAS_V2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ALIAS_V2"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALIAS_V2",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ALIAS_V2",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_alias_v2"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALWAYS_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ALWAYS_INLINE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALWAYS_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ALWAYS_INLINE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_always_inline"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_API_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_API_VERSION"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_API_VERSION",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_api_version"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_APPLY_AUTO_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_APPLY_AUTO_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_APPLY_AUTO_AVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_apply_auto_available"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_QUEUE_ARG_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_APPLY_QUEUE_ARG_NULLABILITY"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_QUEUE_ARG_NULLABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_APPLY_QUEUE_ARG_NULLABILITY",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_apply_queue_arg_nullability"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_ABI_SINGLE_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_ABI_SINGLE_BEGIN",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_abi_single_begin"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_ABI_SINGLE_END"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_ABI_SINGLE_END",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_abi_single_end"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_NONNULL_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_NONNULL_BEGIN",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_nonnull_begin"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_NONNULL_END"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_NONNULL_END",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_nonnull_end"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COLD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_COLD"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COLD",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_COLD",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_cold"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COMPILER_CAN_ASSUME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_COMPILER_CAN_ASSUME"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COMPILER_CAN_ASSUME",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_COMPILER_CAN_ASSUME",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_compiler_can_assume"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_CONST"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_CONST",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_const"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COUNTED_BY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_COUNTED_BY"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COUNTED_BY",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_COUNTED_BY",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_counted_by"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DECL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DECL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_decl"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DECL_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DECL_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_decl_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_PURE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PURE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_PURE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_pure"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALIAS_V2",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALWAYS_INLINE",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_QUEUE_ARG_NULLABILITY",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_BEGIN",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_END",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_BEGIN",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_END",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COLD",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COMPILER_CAN_ASSUME",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_CONST",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COUNTED_BY",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL_SWIFT"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_API_VERSION/title",
          "value": "DISPATCH_API_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_API_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_API_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_APPLY_AUTO_AVAILABLE/title",
          "value": "DISPATCH_APPLY_AUTO_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_APPLY_AUTO_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_APPLY_AUTO_AVAILABLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_pure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
