{
  "abstract": [
    {
      "text": "Returns a new dispatch data object consisting of the concatenated data from two other data objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_concat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_data_create_concat",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_data_create_concat"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_data_create_concat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_data_create_concat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_data_t",
              "text": "dispatch_data_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_data_create_concat"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_data_t",
              "text": "dispatch_data_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "data1"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_data_t",
              "text": "dispatch_data_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "data2"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The first data object to include. The memory from this object is placed at the beginning of the new data object’s memory region.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "data1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The second data object to include. The memory from this object is added to the end of the memory from ",
                  "type": "text"
                },
                {
                  "code": "data1",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "data2"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new dispatch data object containing the concatenated memory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After calling this function, it is safe to release either of the objects in ",
              "type": "text"
            },
            {
              "code": "data1",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "data2",
              "type": "codeVoice"
            },
            {
              "text": ". However, be aware that the memory from those objects may not be deallocated if the newly created dispatch data object references it, as opposed to copies it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_DEFAULT": {
      "abstract": [
        {
          "text": "The default data destructor for dispatch objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DESTRUCTOR_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DESTRUCTOR_DEFAULT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_destructor_default"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_FREE": {
      "abstract": [
        {
          "text": "The destructor for dispatch data objects whose memory buffer was created using the malloc family of allocation routines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DESTRUCTOR_FREE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_FREE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DESTRUCTOR_FREE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_destructor_free"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_data": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_data",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_copy_region": {
      "abstract": [
        {
          "text": "Returns a data object containing a portion of the data in another data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_copy_region"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_copy_region",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_copy_region",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_copy_region"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create": {
      "abstract": [
        {
          "text": "Creates a new dispatch data object with the specified memory buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_concat": {
      "abstract": [
        {
          "text": "Returns a new dispatch data object consisting of the concatenated data from two other data objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create_concat"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_concat",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create_concat",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create_concat"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_map": {
      "abstract": [
        {
          "text": "Returns a new dispatch data object containing a contiguous representation of the specified object’s memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create_map"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_map",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create_map",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create_map"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_subrange": {
      "abstract": [
        {
          "text": "Returns a new dispatch data object whose contents consist of a portion of another object’s memory region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_create_subrange"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_subrange",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_create_subrange",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_create_subrange"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_empty": {
      "abstract": [
        {
          "text": "A dispatch data object representing a zero-length memory region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_data_empty"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_empty",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_data_empty",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_empty"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t": {
      "abstract": [
        {
          "text": "An immutable object representing a contiguous or sparse region of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_data_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_data_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_data_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Dispatch-Data-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_map",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_create_subrange",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_copy_region",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_empty",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_data_t",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_data",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_DEFAULT",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_FREE"
      ],
      "title": "Creating a Dispatch Data Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_data_t/title",
          "value": "dispatch_data_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_data_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_data_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_data_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_data_create_concat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
