{
  "abstract": [
    {
      "text": "Creates a dispatch I/O channel with the associated path name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_io_create_with_path",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_io_create_with_path"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_io_create_with_path"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_io_create_with_path"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_io_t",
              "text": "dispatch_io_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_io_create_with_path"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_io_type_t",
              "text": "dispatch_io_type_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "path"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "oflag"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@mode_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@mode_t",
              "text": "mode_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^"
            },
            {
              "kind": "internalParam",
              "text": "cleanup_handler"
            },
            {
              "kind": "text",
              "text": ")("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": "));"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of channel to create. For a list of possible options, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The file system path to open and use for the channel I/O. This path is opened using the open system call.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "path"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The flags to pass to the open function when opening the path.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "oflag"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The mode to pass to the open function when creating a file at the specified path. If you are not creating a file, specify ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The dispatch queue to associate with the channel. This queue is used to execute the channel’s clean up handler. The channel retains this queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to enqueue when the system relinquishes control of the channel’s file descriptor. This channel takes a single parameter that indicates the reason why control was relinquished. If the ",
                  "type": "text"
                },
                {
                  "code": "error",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter contains a non zero value, control was relinquished because there was an error creating the channel; otherwise, this value should be ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cleanup_handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The dispatch I/O channel or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if an error occurred. The returned object is retained before it is returned; it is your responsibility to close the channel and then release this object when you are done using it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function associates the specified path with the channel but does not open a file descriptor for that path until you perform the first I/O operation. While it is open, the channel owns the file descriptor. The channel closes the file descriptor and calls its cleanup handler when one of the following occurs:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You close the channel by calling the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " function.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An unrecoverable error occurs on the file descriptor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "All references to the channel are released.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_io"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_io",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_io"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t": {
      "abstract": [
        {
          "text": "A file descriptor used for I/O operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_fd_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_fd_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_fd_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close": {
      "abstract": [
        {
          "text": "Closes the specified channel to new read and write operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_close"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_close",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_close",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_close"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create": {
      "abstract": [
        {
          "text": "Creates a dispatch I/O channel and associates it with the specified file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io": {
      "abstract": [
        {
          "text": "Creates a new dispatch I/O channel from an existing channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create_with_io"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create_with_io",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create_with_io"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path": {
      "abstract": [
        {
          "text": "Creates a dispatch I/O channel with the associated path name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_create_with_path"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_path",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_create_with_path",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_create_with_path"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t": {
      "abstract": [
        {
          "text": "A dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_io_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t": {
      "abstract": [
        {
          "text": "The type of a dispatch I/O channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_type_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_type_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_type_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@mode_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@mode_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode_t",
      "type": "topic",
      "url": "/documentation/kernel/mode_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Dispatch-IO-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_create_with_io",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_fd_t",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_io",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_type_t"
      ],
      "title": "Creating a Dispatch I/O Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/title",
          "value": "dispatch_queue_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/title",
          "value": "dispatch_io_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_io_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_io_create_with_path"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
