{
  "abstract": [
    {
      "text": "Configures how the workloop manages the autorelease pools for the blocks it executes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_autorelease_frequency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_workloop_set_autorelease_frequency",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_workloop_set_autorelease_frequency"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_workloop_set_autorelease_frequency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_workloop_set_autorelease_frequency"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_workloop_set_autorelease_frequency"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_workloop_t",
              "text": "dispatch_workloop_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "workloop"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@dispatch_autorelease_frequency_t",
              "text": "dispatch_autorelease_frequency_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "frequency"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The workloop object you want to modify.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "workloop"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The autorelease behavior attribute to apply to the dispatch queue. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frequency"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t": {
      "abstract": [
        {
          "text": "Constants indicating the frequency with which a dispatch queue creates autorelease pools for its tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_autorelease_frequency_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_autorelease_frequency_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_autorelease_frequency_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class": {
      "abstract": [
        {
          "text": "Returns the quality-of-service class for the specified queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_get_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_get_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_get_qos_class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor": {
      "abstract": [
        {
          "text": "Specifies the minimum quality-of-service level for a dispatch queue, source, or workloop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_set_qos_class_floor"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_set_qos_class_floor",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_set_qos_class_floor"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_autorelease_frequency": {
      "abstract": [
        {
          "text": "Configures how the workloop manages the autorelease pools for the blocks it executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_set_autorelease_frequency"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_autorelease_frequency",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_workloop_set_autorelease_frequency",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_set_autorelease_frequency"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t": {
      "abstract": [
        {
          "text": "A dispatch queue that prioritizes the execution of tasks based on their quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_workloop_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_workloop_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Workloop-Behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class"
      ],
      "title": "Configuring the Workloop Behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_workloop_t/title",
          "value": "dispatch_workloop_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_workloop_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_workloop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_workloop_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_workloop_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_workloop_set_autorelease_frequency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
