{
  "abstract": [
    {
      "text": "Returns the underlying system handle associated with the specified dispatch source.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_source_get_handle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_source_get_handle"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_source_get_handle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_source_get_handle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uintptr_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uintptr_t",
              "text": "uintptr_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_source_get_handle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_source_t",
              "text": "dispatch_source_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "source"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This parameter cannot be NULL.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "source"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 3,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The return value should be interpreted according to the type of the dispatch source, and can be one of the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_MACH_SEND",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ":  mach port (",
                      "type": "text"
                    },
                    {
                      "code": "mach_port_t",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_MACH_RECV",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ":  mach port (",
                      "type": "text"
                    },
                    {
                      "code": "mach_port_t",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_PROC",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": process identifier (",
                      "type": "text"
                    },
                    {
                      "code": "pid_t",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_READ",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": file descriptor (",
                      "type": "text"
                    },
                    {
                      "code": "int",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_SIGNAL",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": signal number (",
                      "type": "text"
                    },
                    {
                      "code": "int",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_VNODE",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": file descriptor (",
                      "type": "text"
                    },
                    {
                      "code": "int",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "Dispatch Source Memory Pressure Event Flags",
                      "type": "codeVoice"
                    },
                    {
                      "text": ": file descriptor (",
                      "type": "text"
                    },
                    {
                      "code": "int",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The handle returned is a reference to the underlying system object being monitored by the dispatch source.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_MACH_RECV": {
      "abstract": [
        {
          "text": "A type of dispatch source for monitoring a mach receive port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_MACH_RECV"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_MACH_RECV",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_MACH_RECV",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_mach_recv"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_MACH_SEND": {
      "abstract": [
        {
          "text": "A type of dispatch source for monitoring a mach send port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_MACH_SEND"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_MACH_SEND",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_MACH_SEND",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_mach_send"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_PROC": {
      "abstract": [
        {
          "text": "A type of dispatch source for monitoring a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_PROC"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_PROC",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_PROC",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_proc"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_READ": {
      "abstract": [
        {
          "text": "A type of dispatch source for monitoring read operations on a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_READ"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_READ",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_READ",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_read"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_SIGNAL": {
      "abstract": [
        {
          "text": "A type of dispatch source for monitoring signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_SIGNAL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_SIGNAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_SIGNAL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_signal"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_VNODE": {
      "abstract": [
        {
          "text": "A type of dispatch source for monitoring changes to a file system object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_VNODE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_VNODE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_VNODE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_vnode"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data": {
      "abstract": [
        {
          "text": "Returns pending data for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle": {
      "abstract": [
        {
          "text": "Returns the underlying system handle associated with the specified dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_handle"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_handle",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_handle",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_handle"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask": {
      "abstract": [
        {
          "text": "Returns the mask of events monitored by the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_get_mask"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_get_mask",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_get_mask"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t": {
      "abstract": [
        {
          "text": "Mach receive-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_recv_flags_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_source_mach_recv_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_recv_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t": {
      "abstract": [
        {
          "text": "Mach send-right flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_mach_send_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_mach_send_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_mach_send_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t": {
      "abstract": [
        {
          "text": "Memory pressure events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_memorypressure_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_memorypressure_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_memorypressure_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data": {
      "abstract": [
        {
          "text": "Merges data into a dispatch source and submits its event handler block to its target queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_merge_data"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_merge_data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_merge_data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t": {
      "abstract": [
        {
          "text": "Events related to a process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_proc_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_proc_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_proc_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_source_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_source_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_source_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t": {
      "abstract": [
        {
          "text": "Events involving a change to a file system object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_source_vnode_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_source_vnode_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_vnode_flags_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uintptr_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uintptr_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uintptr_t",
      "type": "topic",
      "url": "/documentation/kernel/uintptr_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Dispatch-Source-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_data",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_get_mask",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_merge_data",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_proc_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_vnode_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_recv_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_mach_send_flags_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_source_memorypressure_flags_t"
      ],
      "title": "Getting Dispatch Source Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_t/title",
          "value": "dispatch_source_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/title",
          "value": "dispatch_source_mach_recv_flags_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_source_mach_recv_flags_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_source_mach_recv_flags_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_source_get_handle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
