{
  "abstract": [
    {
      "text": "The execution priority for tasks in a global concurrent queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_priority_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@dispatch_queue_priority_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_priority_t"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_priority_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "dispatch_queue_priority_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:L",
              "text": "long"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_priority_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS 10.10 and later, use quality-of-service (QoS) classes to specify the priority of tasks instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_BACKGROUND": {
      "abstract": [
        {
          "text": "Tasks run at the background priority, which is equivalent to the background quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_BACKGROUND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_BACKGROUND",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_background"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_DEFAULT": {
      "abstract": [
        {
          "text": "Tasks run at the default priority, which is equivalent to the default quality-of-service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_DEFAULT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_default"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_HIGH": {
      "abstract": [
        {
          "text": "Tasks run at the highest priority, which is equivalent to the user-initiated quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_HIGH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_HIGH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_HIGH"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_HIGH",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_high"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_LOW": {
      "abstract": [
        {
          "text": "Tasks run at a low priority, which is equivalent to the utility quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_LOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_LOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_PRIORITY_LOW"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_QUEUE_PRIORITY_LOW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_low"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t": {
      "abstract": [
        {
          "text": "Quality-of-service classes that specify the priorities for executing tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_qos_class_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_qos_class_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_qos_class_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_priority_t": {
      "abstract": [
        {
          "text": "The execution priority for tasks in a global concurrent queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_priority_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_priority_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_priority_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_priority_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor": {
      "abstract": [
        {
          "text": "Specifies the minimum quality-of-service level for a dispatch queue, source, or workloop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_set_qos_class_floor"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_set_qos_class_floor",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_set_qos_class_floor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Thread-Scheduling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor"
      ],
      "title": "Thread Scheduling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Priorities",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_HIGH",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_DEFAULT",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_LOW",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_PRIORITY_BACKGROUND"
      ],
      "title": "Priorities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_HIGH/title",
          "value": "DISPATCH_QUEUE_PRIORITY_HIGH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_HIGH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_HIGH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_DEFAULT/title",
          "value": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_DEFAULT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_BACKGROUND/title",
          "value": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_BACKGROUND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_BACKGROUND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_LOW/title",
          "value": "DISPATCH_QUEUE_PRIORITY_LOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_QUEUE_PRIORITY_LOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_QUEUE_PRIORITY_LOW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_queue_priority_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
