{
  "abstract": [
    {
      "text": "Returns an attribute that configures a dispatch queue as initially inactive.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_initially_inactive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_queue_attr_make_initially_inactive",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_attr_make_initially_inactive"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_attr_make_initially_inactive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_queue_attr_make_initially_inactive"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_attr_t",
              "text": "dispatch_queue_attr_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_attr_make_initially_inactive"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_attr_t",
              "text": "dispatch_queue_attr_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attr"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Other queue attributes that you want to combine with the initially inactive attribute.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attr"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An updated set of queue attributes that includes the initially inactive attribute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you configure a dispatch queue with this attribute, the queue does not execute tasks until you call its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/activate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/activate()": {
      "abstract": [
        {
          "text": "Activates the dispatch object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/activate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_activate"
        }
      ],
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchobject/activate()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t": {
      "abstract": [
        {
          "text": "Constants indicating the frequency with which a dispatch queue creates autorelease pools for its tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_autorelease_frequency_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_autorelease_frequency_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_autorelease_frequency_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t": {
      "abstract": [
        {
          "text": "Quality-of-service classes that specify the priorities for executing tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_qos_class_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_qos_class_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_qos_class_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_initially_inactive": {
      "abstract": [
        {
          "text": "Returns an attribute that configures a dispatch queue as initially inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_make_initially_inactive"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_initially_inactive",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_attr_make_initially_inactive",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_make_initially_inactive"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_autorelease_frequency": {
      "abstract": [
        {
          "text": "Returns an attribute that specifies how the dispatch queue manages autorelease pools for the blocks it executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_make_with_autorelease_frequency"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_autorelease_frequency",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_attr_make_with_autorelease_frequency",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_make_with_autorelease_frequency"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_qos_class": {
      "abstract": [
        {
          "text": "Returns attributes suitable for creating a dispatch queue with the desired quality-of-service information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_make_with_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_attr_make_with_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_make_with_qos_class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t": {
      "abstract": [
        {
          "text": "Attributes describing the behaviors of a dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_attr_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_attr_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_attr_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class": {
      "abstract": [
        {
          "text": "Returns the quality-of-service class for the specified queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_get_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_get_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_get_qos_class"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Queue-Execution-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_qos_class",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_qos_class_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_attr_make_with_autorelease_frequency",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_autorelease_frequency_t"
      ],
      "title": "Configuring Queue Execution Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_attr_t/title",
          "value": "dispatch_queue_attr_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_attr_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_attr_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_attr_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_attr_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1activate()/title",
          "value": "dispatch_activate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1activate()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_activate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_queue_attr_make_initially_inactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
