{
  "abstract": [
    {
      "text": "A dispatch queue that executes tasks serially in first-in, first-out (FIFO) order.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_serial_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@dispatch_queue_serial_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dispatch_queue_serial_t"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_queue_serial_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "dispatch_queue_serial_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OS_dispatch_queue_serial",
              "text": "DispatchSerialQueue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchConcurrentQueue": {
      "abstract": [
        {
          "text": "A custom dispatch queue that schedules tasks for concurrent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchConcurrentQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchConcurrentQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchConcurrentQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchConcurrentQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchconcurrentqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum": {
      "abstract": [
        {
          "text": "Quality-of-service classes that specify the priorities for executing tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QoSClass"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QoSClass"
        }
      ],
      "role": "symbol",
      "title": "DispatchQoS.QoSClass",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqos/qosclass-swift.enum"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/Attributes": {
      "abstract": [
        {
          "text": "Attributes that define the behavior of a dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/Attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue.Attributes",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/attributes"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/AutoreleaseFrequency": {
      "abstract": [
        {
          "text": "Constants indicating the frequency with which a dispatch queue autoreleases objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoreleaseFrequency"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/AutoreleaseFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoreleaseFrequency"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue.AutoreleaseFrequency",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/autoreleasefrequency"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/global(qos:)": {
      "abstract": [
        {
          "text": "Returns the global system queue with the specified quality-of-service class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "global"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV0B6SClassO",
          "text": "QoSClass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/global(qos:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "global(qos:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/global(qos:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/init(label:qos:attributes:autoreleaseFrequency:target:)": {
      "abstract": [
        {
          "text": "Creates a new dispatch queue to which you can submit blocks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17OS_dispatch_queueC8DispatchE10AttributesV",
          "text": "Attributes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "autoreleaseFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17OS_dispatch_queueC8DispatchE20AutoreleaseFrequencyO",
          "text": "AutoreleaseFrequency"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/init(label:qos:attributes:autoreleaseFrequency:target:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(label:qos:attributes:autoreleaseFrequency:target:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/init(label:qos:attributes:autoreleasefrequency:target:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/main": {
      "abstract": [
        {
          "text": "The dispatch queue associated with the main thread of the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/main",
      "kind": "symbol",
      "role": "symbol",
      "title": "main",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/main"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue": {
      "abstract": [
        {
          "text": "A custom dispatch queue that schedules tasks for serial execution on an arbitrary thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSerialQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSerialQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchSerialQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchserialqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_global-swift.class": {
      "abstract": [
        {
          "text": "A system-provided dispatch queue that schedules tasks for concurrent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_global"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_global-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_global"
        }
      ],
      "role": "symbol",
      "title": "OS_dispatch_queue_global",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_queue_global-swift.class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_main-swift.class": {
      "abstract": [
        {
          "text": "A system-provided dispatch queue that schedules tasks for serial execution on the app’s main thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_main"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_main-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_queue_main"
        }
      ],
      "role": "symbol",
      "title": "OS_dispatch_queue_main",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_queue_main-swift.class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t": {
      "abstract": [
        {
          "text": "A dispatch queue that executes tasks concurrently and in any order, respecting any barriers that may be in place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_concurrent_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_concurrent_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_concurrent_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_concurrent_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t": {
      "abstract": [
        {
          "text": "A dispatch queue that executes tasks concurrently using threads from the global thread pool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_global_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_global_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_global_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_global_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t": {
      "abstract": [
        {
          "text": "A dispatch queue that is bound to the app’s main thread and executes tasks serially on that thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_main_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_main_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_main_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_main_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_serial_t": {
      "abstract": [
        {
          "text": "A dispatch queue that executes tasks serially in first-in, first-out (FIFO) order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_serial_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_serial_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_serial_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_serial_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_serial_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Dispatch-Queue",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/main",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/global(qos:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/init(label:qos:attributes:autoreleaseFrequency:target:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQoS/QoSClass-swift.enum",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/Attributes",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/AutoreleaseFrequency",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_main-swift.class",
        "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_queue_global-swift.class",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSerialQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchConcurrentQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t"
      ],
      "title": "Creating a Dispatch Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dispatch_queue_serial_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dispatch/documentation/Dispatch"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Dispatch-Queue",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_main_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_global_t",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_concurrent_t"
              ],
              "title": "Creating a Dispatch Queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue_serial",
                    "text": "NSObject<OS_dispatch_queue_serial>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "dispatch_queue_serial_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_serial_t/title",
          "value": "dispatch_queue_serial_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_serial_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_serial_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_serial_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_main_t/title",
          "value": "dispatch_queue_main_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_main_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_main_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_main_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_main_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_concurrent_t/title",
          "value": "dispatch_queue_concurrent_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_concurrent_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_concurrent_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_concurrent_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_concurrent_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_global_t/title",
          "value": "dispatch_queue_global_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_global_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_global_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_global_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_global_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_queue_serial_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch_queue_serial_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
