{
  "abstract": [
    {
      "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)OS_dispatch_source",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DispatchSourceProtocol"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DispatchSourceProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "DispatchSourceProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DispatchSourceProtocol"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You do not adopt this protocol in your objects. Instead, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource/makeSignalSource(signal:queue:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create an object that adopts this protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchData": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchData"
        }
      ],
      "role": "symbol",
      "title": "DispatchData",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdata"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator": {
      "abstract": [
        {
          "text": "A byte-by-byte iterator over the contents of a dispatch data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchDataIterator"
        }
      ],
      "role": "symbol",
      "title": "DispatchDataIterator",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchdataiterator"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSource"
        }
      ],
      "role": "symbol",
      "title": "DispatchSource",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsource"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource/makeSignalSource(signal:queue:)": {
      "abstract": [
        {
          "text": "Creates a new dispatch source object that monitors the arrival of a UNIX signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeSignalSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "signal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": "?) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)OS_dispatch_source_signal",
          "text": "DispatchSourceSignal"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource/makeSignalSource(signal:queue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "makeSignalSource(signal:queue:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsource/makesignalsource(signal:queue:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceFileSystemObject": {
      "abstract": [
        {
          "text": "A dispatch source that monitors events associated with a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceFileSystemObject"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceFileSystemObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceFileSystemObject"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceFileSystemObject",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcefilesystemobject"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMachReceive": {
      "abstract": [
        {
          "text": "A dispatch source that monitors a Mach port for pending messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceMachReceive"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMachReceive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceMachReceive"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceMachReceive",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcemachreceive"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMachSend": {
      "abstract": [
        {
          "text": "A dispatch source that monitors a Mach port for dead name notifications, indicating that a send right no longer has a corresponding receive right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceMachSend"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMachSend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceMachSend"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceMachSend",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcemachsend"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMemoryPressure": {
      "abstract": [
        {
          "text": "A dispatch source that monitors the system for changes in the memory pressure condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceMemoryPressure"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMemoryPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceMemoryPressure"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceMemoryPressure",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcememorypressure"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProcess": {
      "abstract": [
        {
          "text": "A dispatch source that monitors an external process for events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProcess"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProcess"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProcess",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprocess"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol": {
      "abstract": [
        {
          "text": "Defines a common set of properties and methods that are shared with all dispatch source types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/DispatchSourceHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceHandler"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/DispatchSourceHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceHandler"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceProtocol.DispatchSourceHandler",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/dispatchsourcehandler"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/activate()": {
      "abstract": [
        {
          "text": "Activates the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/activate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/activate()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()": {
      "abstract": [
        {
          "text": "Asynchronously cancels the dispatch source, preventing any further invocation of its event handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/cancel()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/data": {
      "abstract": [
        {
          "text": "Returns pending data for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/data",
      "kind": "symbol",
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/handle": {
      "abstract": [
        {
          "text": "Returns the underlying system handle associated with the specified dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/handle",
      "kind": "symbol",
      "role": "symbol",
      "title": "handle",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/handle"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/isCancelled": {
      "abstract": [
        {
          "text": "Returns a Boolean indicating whether the given dispatch source has been canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/isCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isCancelled",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/iscancelled"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/mask": {
      "abstract": [
        {
          "text": "Returns the mask of events monitored by the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/mask",
      "kind": "symbol",
      "role": "symbol",
      "title": "mask",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/mask"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/resume()": {
      "abstract": [
        {
          "text": "Resumes the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resume"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/resume()",
      "kind": "symbol",
      "role": "symbol",
      "title": "resume()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/resume()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(handler:)": {
      "abstract": [
        {
          "text": "Sets the cancellation handler block for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancelHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WorkItemC",
          "text": "DispatchWorkItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCancelHandler(handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/setcancelhandler(handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(qos:flags:handler:)": {
      "abstract": [
        {
          "text": "Sets the cancellation handler block for the dispatch source with the specified quality-of-service class and work item options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancelHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
          "text": "DispatchWorkItemFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18OS_dispatch_sourceP8DispatchE0D13SourceHandlera",
          "text": "DispatchSourceHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(qos:flags:handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setCancelHandler(qos:flags:handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/setcancelhandler(qos:flags:handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setEventHandler(handler:)": {
      "abstract": [
        {
          "text": "Sets the event handler work item for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEventHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WorkItemC",
          "text": "DispatchWorkItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setEventHandler(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setEventHandler(handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/seteventhandler(handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setEventHandler(qos:flags:handler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEventHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
          "text": "DispatchWorkItemFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18OS_dispatch_sourceP8DispatchE0D13SourceHandlera",
          "text": "DispatchSourceHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setEventHandler(qos:flags:handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setEventHandler(qos:flags:handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/seteventhandler(qos:flags:handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setRegistrationHandler(handler:)": {
      "abstract": [
        {
          "text": "Sets the registration handler work item for the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRegistrationHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A8WorkItemC",
          "text": "DispatchWorkItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setRegistrationHandler(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setRegistrationHandler(handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/setregistrationhandler(handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setRegistrationHandler(qos:flags:handler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRegistrationHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "qos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A3QoSV",
          "text": "DispatchQoS"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A13WorkItemFlagsV",
          "text": "DispatchWorkItemFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So18OS_dispatch_sourceP8DispatchE0D13SourceHandlera",
          "text": "DispatchSourceHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setRegistrationHandler(qos:flags:handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setRegistrationHandler(qos:flags:handler:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/setregistrationhandler(qos:flags:handler:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/suspend()": {
      "abstract": [
        {
          "text": "Suspends the dispatch source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspend"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/suspend()",
      "kind": "symbol",
      "role": "symbol",
      "title": "suspend()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceprotocol/suspend()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceRead": {
      "abstract": [
        {
          "text": "A dispatch source object for reading data from a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceRead"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceRead"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceRead",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceread"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceSignal": {
      "abstract": [
        {
          "text": "A dispatch source that monitors the current process for UNIX signals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceSignal"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceSignal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceSignal"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceSignal",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcesignal"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceTimer": {
      "abstract": [
        {
          "text": "A dispatch source that submits the event handler block based on a timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceTimer"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceTimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceTimer"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceTimer",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcetimer"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataAdd": {
      "abstract": [
        {
          "text": "A dispatch source that coalesces data you provide using an AND operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceUserDataAdd"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataAdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceUserDataAdd"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceUserDataAdd",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceuserdataadd"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataOr": {
      "abstract": [
        {
          "text": "A dispatch source that coalesces data you provide using an OR operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceUserDataOr"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataOr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceUserDataOr"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceUserDataOr",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceuserdataor"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataReplace": {
      "abstract": [
        {
          "text": "A dispatch source that replaces any pending data with the new value you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceUserDataReplace"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataReplace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceUserDataReplace"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceUserDataReplace",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourceuserdatareplace"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceWrite": {
      "abstract": [
        {
          "text": "A dispatch source object for writing data to a file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchSourceWrite"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchSourceWrite"
        }
      ],
      "role": "symbol",
      "title": "DispatchSourceWrite",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchsourcewrite"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_object": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_object"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_object",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_object",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_object"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data": {
      "abstract": [
        {
          "text": "An object that manages a memory-based data buffer and exposes it as a contiguous block of memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Data",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-data"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch I/O",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-i-o"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source": {
      "abstract": [
        {
          "text": "An object that coordinates the processing of specific low-level system events, such as file-system events, timers, and UNIX signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Source",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-source"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceFileSystemObject",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMachReceive",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMachSend",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceMemoryPressure",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProcess",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceRead",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceSignal",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceTimer",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataAdd",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataOr",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceUserDataReplace",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceWrite"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-Event-Monitoring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSource",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchData",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchDataIterator",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data"
      ],
      "title": "System Event Monitoring"
    }
  ],
  "topicSections": [
    {
      "anchor": "Activating-Suspending-and-Resuming-a-Source",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/activate()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/suspend()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/resume()"
      ],
      "title": "Activating, Suspending, and Resuming a Source"
    },
    {
      "anchor": "Canceling-a-Dispatch-Source",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/cancel()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/isCancelled",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(handler:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setCancelHandler(qos:flags:handler:)"
      ],
      "title": "Canceling a Dispatch Source"
    },
    {
      "anchor": "Installing-Event-Handlers",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setEventHandler(handler:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setEventHandler(qos:flags:handler:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setRegistrationHandler(handler:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/setRegistrationHandler(qos:flags:handler:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/DispatchSourceHandler"
      ],
      "title": "Installing Event Handlers"
    },
    {
      "anchor": "Getting-the-Dispatch-Source-Attributes",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/handle",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/data",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchSourceProtocol/mask"
      ],
      "title": "Getting the Dispatch Source Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dispatch/documentation/Dispatch"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_object"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-Event-Monitoring",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-source",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-i-o",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data"
              ],
              "title": "System Event Monitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OS_dispatch_source"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_object",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)OS_dispatch_object",
                    "text": "OS_dispatch_object"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/title",
          "value": "OS_dispatch_source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchSourceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_dispatch_source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchsourceprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatchsourceprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
