{
  "abstract": [
    {
      "text": "A group of tasks that you monitor as a single unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch Group"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Groups allow you to aggregate a set of tasks and synchronize behaviors on the group. You attach multiple blocks to a group and schedule them for asynchronous execution on the same queue or different queues. When all blocks finish executing, the group executes its completion handler. You can also wait synchronously for all blocks in the group to finish executing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup": {
      "abstract": [
        {
          "text": "A group of tasks that you monitor as a single unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchGroup"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchGroup"
        }
      ],
      "role": "symbol",
      "title": "DispatchGroup",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()": {
      "abstract": [
        {
          "text": "Explicitly indicates that a block has entered the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enter"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_enter"
        }
      ],
      "role": "symbol",
      "title": "enter()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/enter()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()": {
      "abstract": [
        {
          "text": "Creates a new group to which you can assign block objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_create"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/init()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()": {
      "abstract": [
        {
          "text": "Explicitly indicates that a block in the group finished executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leave"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_leave"
        }
      ],
      "role": "symbol",
      "title": "leave()",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup/leave()"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem": {
      "abstract": [
        {
          "text": "The work you want to perform, encapsulated in a way that lets you attach a completion handle or execution dependencies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWorkItem"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWorkItem"
        }
      ],
      "role": "symbol",
      "title": "DispatchWorkItem",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchworkitem"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_group": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_group"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_group",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_group",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_group"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item": {
      "abstract": [
        {
          "text": "The work you want to perform, encapsulated in a way that lets you attach a completion handle or execution dependencies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Work Item",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-work-item"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_global_queue": {
      "abstract": [
        {
          "text": "Returns a system-defined global concurrent queue with the specified quality-of-service class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_get_global_queue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_global_queue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_get_global_queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_get_global_queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_main_queue": {
      "abstract": [
        {
          "text": "Returns the serial dispatch queue associated with the application’s main thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_get_main_queue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_main_queue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_get_main_queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_get_main_queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_async": {
      "abstract": [
        {
          "text": "Schedules a block asynchronously for execution and simultaneously associates it with the specified dispatch group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_group_async"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_async",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_async"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_async_f": {
      "abstract": [
        {
          "text": "Submits an application-defined function to a dispatch queue and associates it with the specified dispatch group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_group_async_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_async_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_async_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_async_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify": {
      "abstract": [
        {
          "text": "Schedules a block object to be submitted to a queue when a group of previously submitted block objects have completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_group_notify"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_notify",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_notify"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify_f": {
      "abstract": [
        {
          "text": "Schedules an application-defined function to be submitted to a queue when a group of previously submitted block objects have completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_group_notify_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_notify_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_notify_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_t": {
      "abstract": [
        {
          "text": "A group of block objects submitted to a queue for asynchronous invocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_group_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_group_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_group_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_wait": {
      "abstract": [
        {
          "text": "Waits synchronously for the previously submitted block objects to finish; returns if the blocks do not complete before the specified timeout period has elapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_group_wait"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_wait",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_wait",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_wait"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/workloop": {
      "abstract": [
        {
          "text": "A dispatch object that prioritizes the execution of tasks based on their quality-of-service (QoS) level.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/workloop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workloop",
      "type": "topic",
      "url": "/documentation/dispatch/workloop"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queues-and-Tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
        "doc://com.apple.dispatch/documentation/Dispatch/workloop"
      ],
      "title": "Queues and Tasks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-Group",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_t"
      ],
      "title": "Creating a Dispatch Group"
    },
    {
      "anchor": "Updating-the-Group-Manually",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()"
      ],
      "title": "Updating the Group Manually"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Dispatch-Group",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/init()",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_t",
                "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_group"
              ],
              "title": "Creating a Dispatch Group"
            },
            {
              "anchor": "Adding-Work-to-the-Group",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_async",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_async_f"
              ],
              "title": "Adding Work to the Group"
            },
            {
              "anchor": "Adding-a-Completion-Handler",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify_f"
              ],
              "title": "Adding a Completion Handler"
            },
            {
              "anchor": "Waiting-for-Tasks-to-Finish-Executing",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_wait"
              ],
              "title": "Waiting for Tasks to Finish Executing"
            },
            {
              "anchor": "Updating-the-Group-Manually",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/enter()",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup/leave()"
              ],
              "title": "Updating the Group Manually"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Queues-and-Tasks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_main_queue",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_global_queue",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
                "doc://com.apple.dispatch/documentation/Dispatch/workloop"
              ],
              "title": "Queues and Tasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1enter()/title",
          "value": "dispatch_group_enter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1enter()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_enter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1init()/title",
          "value": "dispatch_group_create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1init()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_group_t/title",
          "value": "dispatch_group_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_group_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_group_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1leave()/title",
          "value": "dispatch_group_leave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchGroup~1leave()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_group_leave"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-group"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-group"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
