{
  "abstract": [
    {
      "text": "Schedules a notification block to be submitted to a queue when the execution of a specified dispatch block has completed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_notify"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_block_notify",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_block_notify"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_block_notify"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_block_notify"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_block_notify"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_block_t",
              "text": "dispatch_block_t"
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_block_t",
              "text": "dispatch_block_t"
            },
            {
              "kind": "internalParam",
              "text": "notification_block"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The dispatch block to observe.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The result of passing ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " or a block object not returned by the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_create",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_create_with_qos_class",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function is undefined.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "block"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The queue to which the supplied notification block is submitted when the observed block completes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The notification block to submit when the observed block object completes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "notification_block"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function submits the notification block immediately if execution of the observed block object has already completed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It is not possible to be notified of multiple executions of the same block object with this interface. Instead, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function for that purpose.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A single dispatch block may either be observed one or more times and executed once, or it may be executed any number of times. The behavior of any other combination is undefined. Submission to a dispatch queue counts as an execution, even if cancellation using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_cancel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function means the block’s code never runs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If multiple notification blocks are scheduled for a single block object, there is no defined order in which the notification blocks are submitted to their associated queues.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_cancel": {
      "abstract": [
        {
          "text": "Cancels the specified dispatch block asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_block_cancel"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_cancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_block_cancel",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_block_cancel"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_create": {
      "abstract": [
        {
          "text": "Creates a new dispatch block on the heap using an existing block and the given flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_block_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_block_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_block_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_create_with_qos_class": {
      "abstract": [
        {
          "text": "Creates a new dispatch block from an existing block and the given flags, and assigns it the specified quality-of-service class and relative priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_block_create_with_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_create_with_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_block_create_with_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_block_create_with_qos_class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_notify": {
      "abstract": [
        {
          "text": "Schedules a notification block to be submitted to a queue when the execution of a specified dispatch block has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_block_notify"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_notify",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_block_notify",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_block_notify"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t": {
      "abstract": [
        {
          "text": "The prototype of blocks submitted to dispatch queues, which take no arguments and have no return value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_block_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_block_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_block_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_block_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify": {
      "abstract": [
        {
          "text": "Schedules a block object to be submitted to a queue when a group of previously submitted block objects have completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_group_notify"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_group_notify",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_group_notify",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_group_notify"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/title",
          "value": "dispatch_queue_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_block_notify"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
