{
  "abstract": [
    {
      "text": "The desired delivery behavior for interval events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_interval_flags_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@dispatch_io_interval_flags_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_io_interval_flags_t"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_io_interval_flags_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "dispatch_io_interval_flags_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:l",
              "text": "unsigned long"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_io_interval_flags_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STRICT_INTERVAL": {
      "abstract": [
        {
          "text": "Enqueue handlers for a channel at strict intervals regardless of how much data has been read or written.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_IO_STRICT_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STRICT_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_IO_STRICT_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_IO_STRICT_INTERVAL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_strict_interval"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor": {
      "abstract": [
        {
          "text": "Returns the file descriptor associated with the specified channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_get_descriptor"
        }
      ],
      "role": "symbol",
      "title": "fileDescriptor",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/filedescriptor"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)": {
      "abstract": [
        {
          "text": "Sets the maximum number of bytes to process before enqueueing a handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "highWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_high_water"
        }
      ],
      "role": "symbol",
      "title": "setLimit(highWater:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setlimit(highwater:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)": {
      "abstract": [
        {
          "text": "Sets the minimum number of bytes to process before enqueueing a handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lowWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_low_water"
        }
      ],
      "role": "symbol",
      "title": "setLimit(lowWater:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setlimit(lowwater:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_interval_flags_t": {
      "abstract": [
        {
          "text": "The desired delivery behavior for interval events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_interval_flags_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_interval_flags_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_interval_flags_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_interval_flags_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_set_interval": {
      "abstract": [
        {
          "text": "Sets the interval (in nanoseconds) at which to invoke the I/O handlers for the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_interval"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_set_interval",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_io_set_interval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_io_set_interval"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-File-Descriptor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_io_set_interval",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)"
      ],
      "title": "Managing the File Descriptor"
    }
  ],
  "topicSections": [
    {
      "anchor": "Channel-Configuration-Options",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_IO_STRICT_INTERVAL"
      ],
      "title": "Channel Configuration Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(lowWater:)/title",
          "value": "dispatch_io_set_low_water"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(lowWater:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_set_low_water"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(highWater:)/title",
          "value": "dispatch_io_set_high_water"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(highWater:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_set_high_water"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_IO_STRICT_INTERVAL/title",
          "value": "DISPATCH_IO_STRICT_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_IO_STRICT_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_IO_STRICT_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1fileDescriptor/title",
          "value": "dispatch_io_get_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1fileDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_get_descriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_io_interval_flags_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
