{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_dequeue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@dispatch_introspection_hook_queue_item_dequeue",
    "fragments": [
      {
        "kind": "identifier",
        "text": "dispatch_introspection_hook_queue_item_dequeue"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dispatch_introspection_hook_queue_item_dequeue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "dispatch_introspection_hook_queue_item_dequeue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dispatch_introspection_hook_queue_item_dequeue"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_object_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_object_t",
              "text": "dispatch_object_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "item"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_callout_begin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_callout_begin"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_callout_begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_callout_begin",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_callout_begin"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_callout_end": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_callout_end"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_callout_end",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_callout_end",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_callout_end"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_create": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_destroy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_destroy"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_destroy",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_destroy",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_destroy"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_complete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_item_complete"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_complete",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_item_complete",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_item_complete"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_dequeue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_item_dequeue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_dequeue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_item_dequeue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_item_dequeue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_enqueue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_introspection_hook_queue_item_enqueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_enqueue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_introspection_hook_queue_item_enqueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_introspection_hook_queue_item_enqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_object_t": {
      "abstract": [
        {
          "text": "A dispatch object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_object_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_object_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_object_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_object_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Introspecting-a-Dispatch-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_create",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_destroy",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_enqueue",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_callout_begin",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_callout_end",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_introspection_hook_queue_item_complete"
      ],
      "title": "Introspecting a Dispatch Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_object_t/title",
          "value": "dispatch_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/title",
          "value": "dispatch_queue_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch_introspection_hook_queue_item_dequeue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
