{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dispatch Constants"
  },
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALIAS_V2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ALIAS_V2"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALIAS_V2",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ALIAS_V2",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_alias_v2"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALWAYS_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ALWAYS_INLINE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALWAYS_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ALWAYS_INLINE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_always_inline"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_API_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_API_VERSION"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_API_VERSION",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_api_version"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_APPLY_AUTO_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_APPLY_AUTO_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_APPLY_AUTO_AVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_apply_auto_available"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_QUEUE_ARG_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_APPLY_QUEUE_ARG_NULLABILITY"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_QUEUE_ARG_NULLABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_APPLY_QUEUE_ARG_NULLABILITY",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_apply_queue_arg_nullability"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_ABI_SINGLE_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_ABI_SINGLE_BEGIN",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_abi_single_begin"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_ABI_SINGLE_END"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_ABI_SINGLE_END",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_abi_single_end"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_NONNULL_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_NONNULL_BEGIN",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_nonnull_begin"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ASSUME_NONNULL_END"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ASSUME_NONNULL_END",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assume_nonnull_end"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COLD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_COLD"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COLD",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_COLD",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_cold"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COMPILER_CAN_ASSUME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_COMPILER_CAN_ASSUME"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COMPILER_CAN_ASSUME",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_COMPILER_CAN_ASSUME",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_compiler_can_assume"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_CONST"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_CONST",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_const"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COUNTED_BY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_COUNTED_BY"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COUNTED_BY",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_COUNTED_BY",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_counted_by"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DECL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DECL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_decl"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DECL_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DECL_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_decl_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_MUNMAP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DESTRUCTOR_MUNMAP"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_MUNMAP",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DESTRUCTOR_MUNMAP",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_destructor_munmap"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_TYPE_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DATA_DESTRUCTOR_TYPE_DECL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_TYPE_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DATA_DESTRUCTOR_TYPE_DECL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_data_destructor_type_decl"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DECL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DECL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_decl"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_FACTORY_CLASS_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DECL_FACTORY_CLASS_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_FACTORY_CLASS_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DECL_FACTORY_CLASS_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_decl_factory_class_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SERIAL_EXECUTOR_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DECL_SERIAL_EXECUTOR_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SERIAL_EXECUTOR_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DECL_SERIAL_EXECUTOR_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_decl_serial_executor_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SUBCLASS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DECL_SUBCLASS"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SUBCLASS",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DECL_SUBCLASS",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_decl_subclass"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SUBCLASS_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DECL_SUBCLASS_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SUBCLASS_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DECL_SUBCLASS_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_decl_subclass_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_DECL_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_DECL_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_decl_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ENUM"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ENUM",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_enum"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ENUM_API_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ENUM_API_AVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_enum_api_available"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ENUM_API_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ENUM_API_DEPRECATED",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_enum_api_deprecated"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_DEPRECATED_WITH_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ENUM_API_DEPRECATED_WITH_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_DEPRECATED_WITH_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_ENUM_API_DEPRECATED_WITH_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_enum_api_deprecated_with_replacement"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_EXPECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_EXPECT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_EXPECT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_EXPECT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_expect"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_EXPORT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_export"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_FALLTHROUGH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_FALLTHROUGH"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_FALLTHROUGH",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_FALLTHROUGH",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_fallthrough"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_FREEBSD_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_FREEBSD_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_FREEBSD_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_FREEBSD_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_freebsd_unavailable"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_GLOBAL_OBJECT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_GLOBAL_OBJECT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_GLOBAL_OBJECT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_GLOBAL_OBJECT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_global_object"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_INLINE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_INLINE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_inline"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_LINUX_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_LINUX_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_LINUX_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_LINUX_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_linux_unavailable"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_MALLOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_MALLOC"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_MALLOC",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_MALLOC",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_malloc"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOESCAPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NOESCAPE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOESCAPE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NOESCAPE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_noescape"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL1"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL1",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL1",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull1"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL2"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL2",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL2",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull2"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL3"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL3",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL3",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull3"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL4"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL4",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL4",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull4"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL5"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL5",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL5",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull5"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL6"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL6",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL6",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull6"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL7"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL7",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL7",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull7"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL_ALL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NONNULL_ALL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL_ALL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NONNULL_ALL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nonnull_all"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NORETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NORETURN"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NORETURN",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NORETURN",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_noreturn"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOTHROW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NOTHROW"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOTHROW",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NOTHROW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_nothrow"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOT_TAIL_CALLED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_NOT_TAIL_CALLED"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOT_TAIL_CALLED",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_NOT_TAIL_CALLED",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_not_tail_called"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ONCE_INLINE_FASTPATH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_ONCE_INLINE_FASTPATH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ONCE_INLINE_FASTPATH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_ONCE_INLINE_FASTPATH"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_ONCE_INLINE_FASTPATH",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_once_inline_fastpath"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_OPTIONS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_OPTIONS"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_OPTIONS",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_OPTIONS",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_options"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_OSX_SUPPORTS_AT_LEAST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_OSX_SUPPORTS_AT_LEAST"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_OSX_SUPPORTS_AT_LEAST",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_OSX_SUPPORTS_AT_LEAST",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_osx_supports_at_least"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_PURE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PURE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_PURE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_pure"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT_INACTIVE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_CONCURRENT_INACTIVE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT_INACTIVE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_QUEUE_CONCURRENT_INACTIVE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_concurrent_inactive"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_concurrent_with_autorelease_pool"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL_INACTIVE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_SERIAL_INACTIVE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL_INACTIVE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_QUEUE_SERIAL_INACTIVE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_serial_inactive"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_serial_with_autorelease_pool"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_REFINED_FOR_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_REFINED_FOR_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_REFINED_FOR_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_REFINED_FOR_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_refined_for_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_RETURNS_RETAINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_RETURNS_RETAINED"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_RETURNS_RETAINED",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_RETURNS_RETAINED",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_returns_retained"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_RETURNS_RETAINED_BLOCK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_RETURNS_RETAINED_BLOCK"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_RETURNS_RETAINED_BLOCK",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_RETURNS_RETAINED_BLOCK",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_returns_retained_block"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SENTINEL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SENTINEL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SENTINEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SENTINEL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_sentinel"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SIZED_BY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SIZED_BY"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SIZED_BY",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SIZED_BY",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_sized_by"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_DECL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_DECL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_decl"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_DECL_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_DECL_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_DECL_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_DECL_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_decl_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DATA_REPLACE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_DATA_REPLACE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DATA_REPLACE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_DATA_REPLACE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_data_replace"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DECL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_DECL"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DECL",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_DECL",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_decl"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DECL_SWIFT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SOURCE_TYPE_DECL_SWIFT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DECL_SWIFT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SOURCE_TYPE_DECL_SWIFT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_source_type_decl_swift"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_OVERLAY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_SWIFT3_OVERLAY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_OVERLAY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SWIFT3_OVERLAY"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_SWIFT3_OVERLAY",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_swift3_overlay"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SWIFT3_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SWIFT3_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_swift3_unavailable"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT_NAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SWIFT_NAME"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SWIFT_NAME",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_swift_name"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_SWIFT_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_SWIFT_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_swift_unavailable"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TARGET_QUEUE_DEFAULT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_TARGET_QUEUE_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TARGET_QUEUE_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_TARGET_QUEUE_DEFAULT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_target_queue_default"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TRANSPARENT_UNION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_TRANSPARENT_UNION"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TRANSPARENT_UNION",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_TRANSPARENT_UNION",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_transparent_union"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_unavailable"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNAVAILABLE_MSG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_UNAVAILABLE_MSG"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNAVAILABLE_MSG",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_UNAVAILABLE_MSG",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_unavailable_msg"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNSAFE_INDEXABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_UNSAFE_INDEXABLE"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNSAFE_INDEXABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_UNSAFE_INDEXABLE",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_unsafe_indexable"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WARN_RESULT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DISPATCH_WARN_RESULT"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WARN_RESULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "DISPATCH_WARN_RESULT",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_warn_result"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/MSEC_PER_SEC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSEC_PER_SEC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/MSEC_PER_SEC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSEC_PER_SEC"
        }
      ],
      "role": "symbol",
      "title": "MSEC_PER_SEC",
      "type": "topic",
      "url": "/documentation/dispatch/msec_per_sec"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Data Types",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-data-types"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Functions",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-functions"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_barrier_debug": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_assert_queue_barrier_debug"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_barrier_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_assert_queue_barrier_debug",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assert_queue_barrier_debug"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_debug": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_assert_queue_debug"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_assert_queue_debug",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assert_queue_debug"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_not_debug": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_assert_queue_not_debug"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_not_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_assert_queue_not_debug",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_assert_queue_not_debug"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_cancel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_cancel"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_cancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_cancel",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_cancel"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_compiler_barrier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_compiler_barrier"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_compiler_barrier",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_compiler_barrier",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_compiler_barrier"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_notify": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_notify"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_notify",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_notify",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_notify"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_once-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_once"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_once-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_once",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_once-c.macro"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_once_f-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_once_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_once_f-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_once_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_once_f-c.macro"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_testcancel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_testcancel"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_testcancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_testcancel",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_testcancel"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_wait": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_wait"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_wait",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_wait",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_wait"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ONCE_INLINE_FASTPATH",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_OVERLAY",
        "doc://com.apple.dispatch/documentation/Dispatch/MSEC_PER_SEC"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ONCE_INLINE_FASTPATH",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_OVERLAY",
                "doc://com.apple.dispatch/documentation/Dispatch/MSEC_PER_SEC"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALIAS_V2",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ALWAYS_INLINE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_API_VERSION",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_AUTO_AVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_APPLY_QUEUE_ARG_NULLABILITY",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_BEGIN",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_ABI_SINGLE_END",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_BEGIN",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ASSUME_NONNULL_END",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COLD",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COMPILER_CAN_ASSUME",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_CONST",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_COUNTED_BY",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DECL_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_MUNMAP",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DATA_DESTRUCTOR_TYPE_DECL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_FACTORY_CLASS_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SERIAL_EXECUTOR_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SUBCLASS",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SUBCLASS_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_DECL_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_AVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_DEPRECATED",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ENUM_API_DEPRECATED_WITH_REPLACEMENT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_EXPECT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_EXPORT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_FALLTHROUGH",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_FREEBSD_UNAVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_GLOBAL_OBJECT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_INLINE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_LINUX_UNAVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_MALLOC",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOESCAPE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL1",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL2",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL3",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL4",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL5",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL6",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL7",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NONNULL_ALL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NORETURN",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOTHROW",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_NOT_TAIL_CALLED",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_ONCE_INLINE_FASTPATH",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_OPTIONS",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_OSX_SUPPORTS_AT_LEAST",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_PURE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT_INACTIVE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL_INACTIVE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_REFINED_FOR_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_RETURNS_RETAINED",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_RETURNS_RETAINED_BLOCK",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SENTINEL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SIZED_BY",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_DECL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_DECL_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DATA_REPLACE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DECL",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SOURCE_TYPE_DECL_SWIFT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_OVERLAY",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT3_UNAVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT_NAME",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_SWIFT_UNAVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TARGET_QUEUE_DEFAULT",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_TRANSPARENT_UNION",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNAVAILABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNAVAILABLE_MSG",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_UNSAFE_INDEXABLE",
                "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WARN_RESULT",
                "doc://com.apple.dispatch/documentation/Dispatch/MSEC_PER_SEC",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_barrier_debug",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_debug",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_assert_queue_not_debug",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_cancel",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_compiler_barrier",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_notify",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_once-c.macro",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_once_f-c.macro",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_testcancel",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_wait"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-data-types",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_ONCE_INLINE_FASTPATH/title",
          "value": "DISPATCH_ONCE_INLINE_FASTPATH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_ONCE_INLINE_FASTPATH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_ONCE_INLINE_FASTPATH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_SWIFT3_OVERLAY/title",
          "value": "DISPATCH_SWIFT3_OVERLAY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_SWIFT3_OVERLAY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_SWIFT3_OVERLAY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_APPLY_AUTO_AVAILABLE/title",
          "value": "DISPATCH_APPLY_AUTO_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_APPLY_AUTO_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_APPLY_AUTO_AVAILABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_API_VERSION/title",
          "value": "DISPATCH_API_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_API_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_API_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1MSEC_PER_SEC/title",
          "value": "MSEC_PER_SEC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1MSEC_PER_SEC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSEC_PER_SEC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatch-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/dispatch-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
