{
  "abstract": [
    {
      "text": "A result value indicating whether a dispatch operation finished before a specified time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8Dispatch0A13TimeoutResultO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DispatchTimeoutResult"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DispatchTimeoutResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "DispatchTimeoutResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@frozen"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DispatchTimeoutResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants": {
      "abstract": [
        {
          "text": "Constants for wall time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Wall Time Constants",
      "type": "topic",
      "url": "/documentation/dispatch/2963138-wall-time-constants"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW": {
      "abstract": [
        {
          "text": "The current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DISPATCH_WALLTIME_NOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DISPATCH_WALLTIME_NOW"
        }
      ],
      "role": "symbol",
      "title": "DISPATCH_WALLTIME_NOW",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_walltime_now"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime": {
      "abstract": [
        {
          "text": "A point in time relative to the default clock, with nanosecond precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTime"
        }
      ],
      "role": "symbol",
      "title": "DispatchTime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtime"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds, millisconds, microseconds, or nanoseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeInterval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult": {
      "abstract": [
        {
          "text": "A result value indicating whether a dispatch operation finished before a specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeoutResult"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeoutResult"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeoutResult",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeoutresult"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult/success": {
      "abstract": [
        {
          "text": "Indicates that a dispatch operation successfully finished before the specified time elapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult/success",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeoutResult.success",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeoutresult/success"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult/timedOut": {
      "abstract": [
        {
          "text": "Indicates that a dispatch operation failed to finish before the specified time elapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult/timedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "DispatchTimeoutResult.timedOut",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeoutresult/timedout"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime": {
      "abstract": [
        {
          "text": "An absolute point in time according to the wall clock, with microsecond precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWallTime"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWallTime"
        }
      ],
      "role": "symbol",
      "title": "DispatchWallTime",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchwalltime"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t": {
      "abstract": [
        {
          "text": "An abstract representation of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_time_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_time_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_time_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-Constructs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTime",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchWallTime",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_time_t",
        "doc://com.apple.dispatch/documentation/Dispatch/DISPATCH_WALLTIME_NOW",
        "doc://com.apple.dispatch/documentation/Dispatch/2963138-wall-time-constants"
      ],
      "title": "Time Constructs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult/success",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeoutResult/timedOut"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/title",
          "value": "dispatch_time_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_time_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_time_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_WALLTIME_NOW/title",
          "value": "DISPATCH_WALLTIME_NOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DISPATCH_WALLTIME_NOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DISPATCH_WALLTIME_NOW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchtimeoutresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
