{
  "abstract": [
    {
      "text": "A dispatch object that prioritizes the execution of tasks based on their quality-of-service (QoS) level.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/workloop"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Workloop"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A workloop is a priority-ordered dispatch queue that uses QoS levels to determine the execution order of tasks. Before it starts executing each new task, the queue evaluates the QoS levels of currently enqueued tasks and selects the one with the highest priority. Tasks with the QoS level ",
              "type": "text"
            },
            {
              "code": "QOS_CLASS_USER_INTERACTIVE",
              "type": "codeVoice"
            },
            {
              "text": " have the highest priority, followed by tasks with the ",
              "type": "text"
            },
            {
              "code": "QOS_CLASS_USER_INITIATED",
              "type": "codeVoice"
            },
            {
              "text": " priority, and so on.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A workloop is a type of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, and you use the same functions to enqueue new tasks. For example, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to enqueue a task asynchronously.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup": {
      "abstract": [
        {
          "text": "A group of tasks that you monitor as a single unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchGroup"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchGroup"
        }
      ],
      "role": "symbol",
      "title": "DispatchGroup",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchgroup"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/setTarget(queue:)": {
      "abstract": [
        {
          "text": "Specifies the dispatch queue on which to perform work associated with the current object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTarget"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/setTarget(queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_set_target_queue"
        }
      ],
      "role": "symbol",
      "title": "setTarget(queue:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchobject/settarget(queue:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchQueue"
        }
      ],
      "role": "symbol",
      "title": "DispatchQueue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/asyncAndWait(execute:)-1udeu": {
      "abstract": [
        {
          "text": "Submits a work item for execution and returns only after it finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asyncAndWait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/asyncAndWait(execute:)-1udeu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_async_and_wait"
        }
      ],
      "role": "symbol",
      "title": "asyncAndWait(execute:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/asyncandwait(execute:)-1udeu"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/sync(execute:)-3segw": {
      "abstract": [
        {
          "text": "Submits a block object for execution and returns after that block finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/sync(execute:)-3segw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_sync"
        }
      ],
      "role": "symbol",
      "title": "sync(execute:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchqueue/sync(execute:)-3segw"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem": {
      "abstract": [
        {
          "text": "The work you want to perform, encapsulated in a way that lets you attach a completion handle or execution dependencies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchWorkItem"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchWorkItem"
        }
      ],
      "role": "symbol",
      "title": "DispatchWorkItem",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchworkitem"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_workloop": {
      "abstract": [
        {
          "text": "A dispatch queue that prioritizes the execution of tasks based on their quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_dispatch_workloop"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_workloop",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_dispatch_workloop",
      "type": "topic",
      "url": "/documentation/dispatch/os_dispatch_workloop"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group": {
      "abstract": [
        {
          "text": "A group of tasks that you monitor as a single unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Group",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-group"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue": {
      "abstract": [
        {
          "text": "An object that manages the execution of tasks serially or concurrently on your app’s main thread or on a background thread.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item": {
      "abstract": [
        {
          "text": "The work you want to perform, encapsulated in a way that lets you attach a completion handle or execution dependencies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dispatch Work Item",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch-work-item"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after": {
      "abstract": [
        {
          "text": "Enqueues a block for execution at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_after"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_after",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_after"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after_f": {
      "abstract": [
        {
          "text": "Enqueues an app-defined function for execution at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_after_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_after_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_after_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async": {
      "abstract": [
        {
          "text": "Submits a block for asynchronous execution on a dispatch queue and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_async"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_async",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_async"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_and_wait_f": {
      "abstract": [
        {
          "text": "Submits a function-based work item for execution and returns only after it finishes executing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_async_and_wait_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_and_wait_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_async_and_wait_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_async_and_wait_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_f": {
      "abstract": [
        {
          "text": "Submits an app-defined function for asynchronous execution on a dispatch queue and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_async_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_async_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_async_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async": {
      "abstract": [
        {
          "text": "Submits a barrier block for asynchronous execution and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait": {
      "abstract": [
        {
          "text": "Submits a work item for synchronous execution and marks the work as a barrier for subsequent concurrent tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async_and_wait"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async_and_wait",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async_and_wait"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait_f": {
      "abstract": [
        {
          "text": "Submits a function-based work item for synchronous execution and marks the work as a barrier for subsequent concurrent tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async_and_wait_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async_and_wait_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async_and_wait_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_f": {
      "abstract": [
        {
          "text": "Submits a barrier function for asynchronous execution and returns immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_async_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_async_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_async_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync": {
      "abstract": [
        {
          "text": "Submits a barrier block object for execution and waits until that block completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_sync"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_sync",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_sync"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync_f": {
      "abstract": [
        {
          "text": "Submits a barrier function for execution and waits until that function completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_barrier_sync_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_barrier_sync_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_barrier_sync_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_global_queue": {
      "abstract": [
        {
          "text": "Returns a system-defined global concurrent queue with the specified quality-of-service class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_get_global_queue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_global_queue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_get_global_queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_get_global_queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_main_queue": {
      "abstract": [
        {
          "text": "Returns the serial dispatch queue associated with the application’s main thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_get_main_queue"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_main_queue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_get_main_queue",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_get_main_queue"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_label": {
      "abstract": [
        {
          "text": "Returns the label you assigned to the dispatch queue at creation time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_get_label"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_label",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_get_label",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_get_label"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class": {
      "abstract": [
        {
          "text": "Returns the quality-of-service class for the specified queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_get_qos_class"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_get_qos_class",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_get_qos_class"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_queue_t"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor": {
      "abstract": [
        {
          "text": "Specifies the minimum quality-of-service level for a dispatch queue, source, or workloop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_set_qos_class_floor"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_set_qos_class_floor",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_set_qos_class_floor"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_sync_f": {
      "abstract": [
        {
          "text": "Submits an app-defined function for synchronous execution on a dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_sync_f"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_sync_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_sync_f",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_sync_f"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_create": {
      "abstract": [
        {
          "text": "Creates a new workloop with the specified label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_create"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_workloop_create",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_create"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_create_inactive": {
      "abstract": [
        {
          "text": "Creates a new inactive workloop with the specified label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_create_inactive"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_create_inactive",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_workloop_create_inactive",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_create_inactive"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_autorelease_frequency": {
      "abstract": [
        {
          "text": "Configures how the workloop manages the autorelease pools for the blocks it executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_set_autorelease_frequency"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_autorelease_frequency",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_workloop_set_autorelease_frequency",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_set_autorelease_frequency"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t": {
      "abstract": [
        {
          "text": "A dispatch queue that prioritizes the execution of tasks based on their quality-of-service level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_workloop_t"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_workloop_t"
        }
      ],
      "role": "symbol",
      "title": "dispatch_workloop_t",
      "type": "topic",
      "url": "/documentation/dispatch/dispatch_workloop_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Queues-and-Tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchWorkItem",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchGroup",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group"
      ],
      "title": "Queues and Tasks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Dispatch-Workloop",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t"
      ],
      "title": "Creating a Dispatch Workloop"
    },
    {
      "anchor": "Executing-Tasks-Synchronously",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/sync(execute:)-3segw",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/asyncAndWait(execute:)-1udeu"
      ],
      "title": "Executing Tasks Synchronously"
    },
    {
      "anchor": "Managing-Queue-Attributes",
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/setTarget(queue:)"
      ],
      "title": "Managing Queue Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Dispatch-Workloop",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_create",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_create_inactive",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_t",
                "doc://com.apple.dispatch/documentation/Dispatch/OS_dispatch_workloop"
              ],
              "title": "Creating a Dispatch Workloop"
            },
            {
              "anchor": "Configuring-the-Workloop-Behavior",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_workloop_set_autorelease_frequency",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_set_qos_class_floor",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_qos_class"
              ],
              "title": "Configuring the Workloop Behavior"
            },
            {
              "anchor": "Executing-Tasks-Asynchronously",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_after_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_f"
              ],
              "title": "Executing Tasks Asynchronously"
            },
            {
              "anchor": "Executing-Tasks-Synchronously",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/sync(execute:)-3segw",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_sync_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_sync_f",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchQueue/asyncAndWait(execute:)-1udeu",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_async_and_wait_f",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_barrier_async_and_wait_f"
              ],
              "title": "Executing Tasks Synchronously"
            },
            {
              "anchor": "Managing-Queue-Attributes",
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_queue_get_label",
                "doc://com.apple.dispatch/documentation/Dispatch/DispatchObject/setTarget(queue:)"
              ],
              "title": "Managing Queue Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Queues-and-Tasks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_main_queue",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch_get_global_queue",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-queue",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-work-item",
                "doc://com.apple.dispatch/documentation/Dispatch/dispatch-group"
              ],
              "title": "Queues and Tasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchQueue~1asyncAndWait(execute:)-1udeu/title",
          "value": "dispatch_async_and_wait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchQueue~1asyncAndWait(execute:)-1udeu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_async_and_wait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/title",
          "value": "dispatch_queue_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_queue_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_workloop_t/title",
          "value": "dispatch_workloop_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_workloop_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_workloop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1dispatch_workloop_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_workloop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1setTarget(queue:)/title",
          "value": "dispatch_set_target_queue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchObject~1setTarget(queue:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_set_target_queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchQueue~1sync(execute:)-3segw/title",
          "value": "dispatch_sync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchQueue~1sync(execute:)-3segw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_sync"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/workloop"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dispatch/workloop"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
