{
  "abstract": [
    {
      "text": "The domain’s version when the source location deleted the item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/domainVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSFileProviderTestingDeletion(py)domainVersion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "domainVersion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFileProviderDomainVersion",
        "text": "NSFileProviderDomainVersion"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "domainVersion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "domainVersion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "domainVersion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFileProviderDomainVersion",
              "text": "NSFileProviderDomainVersion"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainVersion": {
      "abstract": [
        {
          "text": "An opaque object that identifies a specific version of a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderDomainVersion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderDomainVersion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderDomainVersion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileproviderdomainversion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion": {
      "abstract": [
        {
          "text": "An operation that syncs the deletion of the source item to the target location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingDeletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingDeletion"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingDeletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/domainVersion": {
      "abstract": [
        {
          "text": "The domain’s version when the source location deleted the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domainVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFileProviderDomainVersion",
          "text": "NSFileProviderDomainVersion"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/domainVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domainVersion"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "domainVersion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion/domainversion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/sourceItemIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier for the source item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/sourceItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceItemIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sourceItemIdentifier",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion/sourceitemidentifier"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemBaseVersion": {
      "abstract": [
        {
          "text": "The version of the deleted item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetItemBaseVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFileProviderItemVersion",
          "text": "NSFileProviderItemVersion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemBaseVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetItemBaseVersion"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "targetItemBaseVersion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion/targetitembaseversion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier for the target item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetItemIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "targetItemIdentifier",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion/targetitemidentifier"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetSide": {
      "abstract": [
        {
          "text": "The target location for the delete operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetSide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderTestingOperationSide",
          "text": "NSFileProviderTestingOperationSide"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetSide"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "targetSide",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingdeletion/targetside"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Operations-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/sourceItemIdentifier",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetSide",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemIdentifier",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemBaseVersion"
      ],
      "title": "Accessing the Operation’s Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "domainVersion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "domainVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Operations-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/sourceItemIdentifier",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetSide",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemIdentifier",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingDeletion/targetItemBaseVersion"
              ],
              "title": "Accessing the Operation’s Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderDomainVersion",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSFileProviderDomainVersion",
                    "text": "NSFileProviderDomainVersion"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "domainVersion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1targetSide/title",
          "value": "targetSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1targetSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1targetItemBaseVersion/title",
          "value": "targetItemBaseVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1targetItemBaseVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetItemBaseVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDomainVersion/title",
          "value": "NSFileProviderDomainVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDomainVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderDomainVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderDomainVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderDomainVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/title",
          "value": "NSFileProviderTestingDeletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1domainVersion/title",
          "value": "domainVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1domainVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "domainVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1targetItemIdentifier/title",
          "value": "targetItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1targetItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1sourceItemIdentifier/title",
          "value": "sourceItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingDeletion~1sourceItemIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceItemIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingdeletion/domainversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingdeletion/domainversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
