{
  "abstract": [
    {
      "text": "A transfer size that represents 1 or more gigabytes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKOperationGroupTransferSize@CKOperationGroupTransferSizeGigabytes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gigabytes"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKOperationGroupTransferSizeGigabytes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CKOperationGroup.TransferSize.gigabytes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gigabytes"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup": {
      "abstract": [
        {
          "text": "An explicit association between two or more operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKOperationGroup"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroup"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize": {
      "abstract": [
        {
          "text": "Constants that represent possible data transfer sizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransferSize"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TransferSize"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents 1 or more gigabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gigabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeGigabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.gigabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/gigabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents hundreds of gigabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hundredsOfGigabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeHundredsOfGigabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.hundredsOfGigabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/hundredsofgigabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents hundreds of megabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hundredsOfMegabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeHundredsOfMegabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.hundredsOfMegabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/hundredsofmegabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes": {
      "abstract": [
        {
          "text": "A transfer size that represents 1 or more kilobytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kilobytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeKilobytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.kilobytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/kilobytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents 1 or more megabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "megabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeMegabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.megabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/megabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents tens of gigabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensOfGigabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeTensOfGigabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.tensOfGigabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/tensofgigabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents tens of megabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensOfMegabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeTensOfMegabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.tensOfMegabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/tensofmegabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown": {
      "abstract": [
        {
          "text": "An unknown transfer size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeUnknown"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.unknown",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transfer-Sizes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown"
      ],
      "title": "Transfer Sizes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKOperationGroupTransferSizeGigabytes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transfer-Sizes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown"
              ],
              "title": "Transfer Sizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKOperationGroupTransferSizeGigabytes"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize/title",
          "value": "CKOperationGroupTransferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfMegabytes/title",
          "value": "CKOperationGroupTransferSizeHundredsOfMegabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfMegabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeHundredsOfMegabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1megabytes/title",
          "value": "CKOperationGroupTransferSizeMegabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1megabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeMegabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfGigabytes/title",
          "value": "CKOperationGroupTransferSizeTensOfGigabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfGigabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeTensOfGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfGigabytes/title",
          "value": "CKOperationGroupTransferSizeHundredsOfGigabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfGigabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeHundredsOfGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1gigabytes/title",
          "value": "CKOperationGroupTransferSizeGigabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1gigabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1kilobytes/title",
          "value": "CKOperationGroupTransferSizeKilobytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1kilobytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeKilobytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfMegabytes/title",
          "value": "CKOperationGroupTransferSizeTensOfMegabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfMegabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeTensOfMegabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/title",
          "value": "CKOperationGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1unknown/title",
          "value": "CKOperationGroupTransferSizeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckoperationgroup/transfersize/gigabytes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckoperationgroup/transfersize/gigabytes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
