{
  "abstract": [
    {
      "text": "An array of filename extensions or UTIs that represent the allowed file types for the panel.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use -allowedContentTypes instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSSavePanel(py)allowedFileTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allowedFileTypes"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "allowedFileTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.3",
        "message": "Use -allowedContentTypes instead",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "allowedFileTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allowedFileTypes"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to specify the file types for the user to select from. A file type can be a common filename extension, or a UTI. The default value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", which indicates that any file type can be used. If you specify an empty array for this parameter, the Save panel raises an exception.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the user doesn’t select a type, the panel uses the first item in the ",
              "type": "text"
            },
            {
              "code": "allowedFileTypes",
              "type": "codeVoice"
            },
            {
              "text": " array. If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowsOtherFileTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the user enters a filename extension that doesn’t match one of the types in the array, AppKit prompts the user to confirm the choice.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ": In versions of macOS earlier than v10.6, this property is ignored. For applications that link against v10.6 and higher, this property determines which files the open panel enables. Don’t use the deprecated methods to show the open panel (that is, the methods that take a ",
              "type": "text"
            },
            {
              "code": "types:",
              "type": "codeVoice"
            },
            {
              "text": " parameter) because they will overwrite this value. The allowed file types can be changed while the panel is running (for example, from an accessory view). This is also known as the “enabled file types.” A ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " value indicates that all files should be enabled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel": {
      "abstract": [
        {
          "text": "A panel that prompts the user to select a file to open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "NSOpenPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsopenpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel": {
      "abstract": [
        {
          "text": "A panel that prompts the user for information about where to save a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSavePanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSavePanel"
        }
      ],
      "role": "symbol",
      "title": "NSSavePanel",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes": {
      "abstract": [
        {
          "text": "An array of filename extensions or UTIs that represent the allowed file types for the panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedFileTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedFileTypes"
        }
      ],
      "role": "symbol",
      "title": "allowedFileTypes",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/allowedfiletypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowsOtherFileTypes": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the panel allows the user to save files with a filename extension that’s not in the list of allowed types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsOtherFileTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowsOtherFileTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsOtherFileTypes"
        }
      ],
      "role": "symbol",
      "title": "allowsOtherFileTypes",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/allowsotherfiletypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:": {
      "abstract": [
        {
          "text": "Presents a Save panel as a sheet with a specified path and, optionally, a specified file in that path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/beginsheetfordirectory:file:modalforwindow:modaldelegate:didendselector:contextinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directory": {
      "abstract": [
        {
          "text": "Returns the absolute pathname of the directory currently shown in the panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "directory"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "directory"
        }
      ],
      "role": "symbol",
      "title": "directory",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/directory"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/filename": {
      "abstract": [
        {
          "text": "Returns the absolute pathname of the file currently shown in the panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "filename"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/filename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filename"
        }
      ],
      "role": "symbol",
      "title": "filename",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/filename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/requiredFileType": {
      "abstract": [
        {
          "text": "Returns the required file type (if any).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "requiredFileType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/requiredFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiredFileType"
        }
      ],
      "role": "symbol",
      "title": "requiredFileType",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/requiredfiletype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/runModalForDirectory:file:": {
      "abstract": [
        {
          "text": "Initializes the panel to the directory and file specified, if any, then displays it and begins its modal event loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "runModalForDirectory:file:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/runModalForDirectory:file:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForDirectory:file:"
        }
      ],
      "role": "symbol",
      "title": "runModalForDirectory:file:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/runmodalfordirectory:file:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/selectText:": {
      "abstract": [
        {
          "text": "This method has been deprecated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectText:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/selectText:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectText:"
        }
      ],
      "role": "symbol",
      "title": "selectText:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/selecttext:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setDirectory:": {
      "abstract": [
        {
          "text": "Sets the current pathname in the panel’s browser.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setDirectory:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setDirectory:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDirectory:"
        }
      ],
      "role": "symbol",
      "title": "setDirectory:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/setdirectory:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setRequiredFileType:": {
      "abstract": [
        {
          "text": "Specifies the file type (as an extension) or a UTI.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setRequiredFileType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setRequiredFileType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRequiredFileType:"
        }
      ],
      "role": "symbol",
      "title": "setRequiredFileType:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/setrequiredfiletype:"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1538970-panel": {
      "abstract": [
        {
          "text": "Gives the delegate the opportunity to validate selected items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1538970-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:isValidFilename:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1538970-panel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539030-panel": {
      "abstract": [
        {
          "text": "Gives the delegate the opportunity to filter items that it doesn’t want the user to choose.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539030-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:shouldShowFilename:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539030-panel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539080-panel": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has changed the selected directory in the `NSSavePanel` object specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539080-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:directoryDidChange:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539080-panel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539083-panel": {
      "abstract": [
        {
          "text": "Controls the ordering of files presented by the `NSSavePanel` object specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539083-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:compareFilename:with:caseSensitive:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539083-panel"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "allowedFileTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/requiredFileType",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setRequiredFileType:",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setDirectory:",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/runModalForDirectory:file:",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1539083-panel",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1538970-panel",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1539030-panel",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1539080-panel",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directory",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/filename",
                "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/selectText:"
              ],
              "title": "Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowedFileTypes"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use -allowedContentTypes instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1allowsOtherFileTypes/title",
          "value": "allowsOtherFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1allowsOtherFileTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsOtherFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1allowedFileTypes/title",
          "value": "allowedFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1allowedFileTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/title",
          "value": "NSSavePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/title",
          "value": "NSOpenPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenPanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssavepanel/allowedfiletypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssavepanel/allowedfiletypes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
