{"variants":[{"paths":["/documentation/appkit/nssavepanel/directoryurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssavepanel/directoryurl"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSavePanel"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSavePanel/title","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/prompt","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/message","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldLabel","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldStringValue","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/accessoryView","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/showsTagField","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/tagNames"],"anchor":"Configuring-the-Panels-Appearance","title":"Configuring the Panel’s Appearance","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directoryURL"},"abstract":[{"type":"text","text":"The current directory shown in the panel."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directoryURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"platforms":[{"introducedAt":"10.6","unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"role":"symbol","symbolKind":"property","externalID":"c:objc(cs)NSSavePanel(py)directoryURL","navigatorTitle":[{"text":"directoryURL","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"AppKit"}],"title":"directoryURL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directoryURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"URL"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","abstract":[{"text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.","type":"text"}],"type":"topic","title":"URL","url":"/documentation/foundation/url"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSavePanel"}],"type":"topic","kind":"symbol","abstract":[{"text":"A panel that prompts the user for information about where to save a file.","type":"text"}],"url":"/documentation/appkit/nssavepanel","navigatorTitle":[{"kind":"identifier","text":"NSSavePanel"}],"title":"NSSavePanel","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/tagNames":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagNames"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}],"url":"/documentation/appkit/nssavepanel/tagnames","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/tagNames","navigatorTitle":[{"text":"tagNames","kind":"identifier"}],"title":"tagNames","abstract":[{"type":"text","text":"The tag names that you want to include on a saved file."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/prompt":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/prompt","title":"prompt","url":"/documentation/appkit/nssavepanel/prompt","abstract":[{"type":"text","text":"The text to display in the default button."}],"navigatorTitle":[{"text":"prompt","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prompt"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/message":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/message","title":"message","url":"/documentation/appkit/nssavepanel/message","abstract":[{"type":"text","text":"The message text displayed in the panel."}],"navigatorTitle":[{"kind":"identifier","text":"message"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/showsTagField":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/showsTagField","title":"showsTagField","url":"/documentation/appkit/nssavepanel/showstagfield","abstract":[{"type":"text","text":"A Boolean value that indicates whether the panel displays the Tags field."}],"navigatorTitle":[{"kind":"identifier","text":"showsTagField"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsTagField"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directoryURL":{"abstract":[{"type":"text","text":"The current directory shown in the panel."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directoryURL","role":"symbol","url":"/documentation/appkit/nssavepanel/directoryurl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"directoryURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"directoryURL","kind":"identifier"}],"title":"directoryURL"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldLabel":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nameFieldLabel"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameFieldLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"url":"/documentation/appkit/nssavepanel/namefieldlabel","type":"topic","kind":"symbol","title":"nameFieldLabel","abstract":[{"type":"text","text":"The label text displayed in front of the filename text field."}]},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/accessoryView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/accessoryView","title":"accessoryView","url":"/documentation/appkit/nssavepanel/accessoryview","abstract":[{"type":"text","text":"The custom accessory view for the current app."}],"navigatorTitle":[{"text":"accessoryView","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessoryView"},{"kind":"text","text":": "},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSURL":{"role":"symbol","url":"/documentation/foundation/nsurl","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","title":"NSURL","abstract":[{"text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSURL"}]},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/title":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"/documentation/appkit/nssavepanel/title","abstract":[{"type":"text","text":"The title of the panel."}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/title","title":"title"},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldStringValue":{"abstract":[{"type":"text","text":"The user-editable filename currently shown in the name field."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldStringValue","role":"symbol","url":"/documentation/appkit/nssavepanel/namefieldstringvalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameFieldStringValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nameFieldStringValue"}],"title":"nameFieldStringValue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.6","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"directoryURL"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"directoryURL"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSavePanel"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Configuring the Panel’s Appearance","anchor":"Configuring-the-Panels-Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSavePanel/title","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/prompt","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/message","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldLabel","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/nameFieldStringValue","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/accessoryView","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/showsTagField","doc://com.apple.appkit/documentation/AppKit/NSSavePanel/tagNames"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"directoryURL","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"value":"NSSavePanel","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSSavePanel"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSSavePanel"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/navigatorTitle","op":"replace"},{"value":"tagNames","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1tagNames/title","op":"replace"},{"value":[{"kind":"identifier","text":"tagNames"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1tagNames/fragments","op":"replace"},{"value":"prompt","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1prompt/title","op":"replace"},{"value":[{"kind":"identifier","text":"prompt"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1prompt/fragments","op":"replace"},{"value":"message","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1message/title","op":"replace"},{"value":[{"kind":"identifier","text":"message"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1message/fragments","op":"replace"},{"value":"showsTagField","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1showsTagField/title","op":"replace"},{"value":[{"text":"showsTagField","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1showsTagField/fragments","op":"replace"},{"value":"directoryURL","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1directoryURL/title","op":"replace"},{"value":[{"text":"directoryURL","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1directoryURL/fragments","op":"replace"},{"value":"nameFieldLabel","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1nameFieldLabel/title","op":"replace"},{"value":[{"text":"nameFieldLabel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1nameFieldLabel/fragments","op":"replace"},{"value":"accessoryView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1accessoryView/title","op":"replace"},{"value":[{"text":"accessoryView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1accessoryView/fragments","op":"replace"},{"value":[{"type":"text","text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. "}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract","op":"replace"},{"value":"title","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1title/title","op":"replace"},{"value":[{"text":"title","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1title/fragments","op":"replace"},{"value":"nameFieldStringValue","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1nameFieldStringValue/title","op":"replace"},{"value":[{"kind":"identifier","text":"nameFieldStringValue"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1nameFieldStringValue/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}