{
  "abstract": [
    {
      "text": "Specifies the file type (as an extension) or a UTI.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setRequiredFileType:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSavePanel(im)setRequiredFileType:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setRequiredFileType:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setRequiredFileType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setRequiredFileType:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setRequiredFileType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "String to set as the extension to be appended to any selected files that don’t already have that extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "type",
              "type": "codeVoice"
            },
            {
              "text": " is an extension, it should not include the period that begins the extension. Pass ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " to indicate any type. File type strings encoding HFS file types are not valid values for this attribute. You need to invoke this method each time the Save panel is used for another file type within the application.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method is equivalent to using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with an array containing only ",
              "type": "text"
            },
            {
              "code": "type",
              "type": "codeVoice"
            },
            {
              "text": " (unless ",
              "type": "text"
            },
            {
              "code": "type",
              "type": "codeVoice"
            },
            {
              "text": " is nil, and then it’s equivalent to setting the property to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel": {
      "abstract": [
        {
          "text": "A panel that prompts the user for information about where to save a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSavePanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSavePanel"
        }
      ],
      "role": "symbol",
      "title": "NSSavePanel",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes": {
      "abstract": [
        {
          "text": "An array of filename extensions or UTIs that represent the allowed file types for the panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedFileTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedFileTypes"
        }
      ],
      "role": "symbol",
      "title": "allowedFileTypes",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/allowedfiletypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:": {
      "abstract": [
        {
          "text": "Presents a Save panel as a sheet with a specified path and, optionally, a specified file in that path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/beginsheetfordirectory:file:modalforwindow:modaldelegate:didendselector:contextinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directory": {
      "abstract": [
        {
          "text": "Returns the absolute pathname of the directory currently shown in the panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "directory"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "directory"
        }
      ],
      "role": "symbol",
      "title": "directory",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/directory"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/filename": {
      "abstract": [
        {
          "text": "Returns the absolute pathname of the file currently shown in the panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "filename"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/filename",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filename"
        }
      ],
      "role": "symbol",
      "title": "filename",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/filename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/requiredFileType": {
      "abstract": [
        {
          "text": "Returns the required file type (if any).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "requiredFileType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/requiredFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiredFileType"
        }
      ],
      "role": "symbol",
      "title": "requiredFileType",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/requiredfiletype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/runModalForDirectory:file:": {
      "abstract": [
        {
          "text": "Initializes the panel to the directory and file specified, if any, then displays it and begins its modal event loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "runModalForDirectory:file:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/runModalForDirectory:file:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForDirectory:file:"
        }
      ],
      "role": "symbol",
      "title": "runModalForDirectory:file:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/runmodalfordirectory:file:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/selectText:": {
      "abstract": [
        {
          "text": "This method has been deprecated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectText:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/selectText:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectText:"
        }
      ],
      "role": "symbol",
      "title": "selectText:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/selecttext:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setDirectory:": {
      "abstract": [
        {
          "text": "Sets the current pathname in the panel’s browser.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setDirectory:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setDirectory:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDirectory:"
        }
      ],
      "role": "symbol",
      "title": "setDirectory:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/setdirectory:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setRequiredFileType:": {
      "abstract": [
        {
          "text": "Specifies the file type (as an extension) or a UTI.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setRequiredFileType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setRequiredFileType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRequiredFileType:"
        }
      ],
      "role": "symbol",
      "title": "setRequiredFileType:",
      "type": "topic",
      "url": "/documentation/appkit/nssavepanel/setrequiredfiletype:"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1538970-panel": {
      "abstract": [
        {
          "text": "Gives the delegate the opportunity to validate selected items.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1538970-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:isValidFilename:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1538970-panel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539030-panel": {
      "abstract": [
        {
          "text": "Gives the delegate the opportunity to filter items that it doesn’t want the user to choose.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539030-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:shouldShowFilename:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539030-panel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539080-panel": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has changed the selected directory in the `NSSavePanel` object specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539080-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:directoryDidChange:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539080-panel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1539083-panel": {
      "abstract": [
        {
          "text": "Controls the ordering of files presented by the `NSSavePanel` object specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1539083-panel",
      "kind": "symbol",
      "role": "symbol",
      "title": "panel:compareFilename:with:caseSensitive:",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1539083-panel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/allowedFileTypes",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/requiredFileType",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/setDirectory:",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo:",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/runModalForDirectory:file:",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1539083-panel",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1538970-panel",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1539030-panel",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1539080-panel",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/directory",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/filename",
        "doc://com.apple.appkit/documentation/AppKit/NSSavePanel/selectText:"
      ],
      "title": "Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1allowedFileTypes/title",
          "value": "allowedFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1allowedFileTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/title",
          "value": "NSSavePanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSavePanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSavePanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssavepanel/setrequiredfiletype:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
