{
  "abstract": [
    {
      "text": "Advertises peripheral manager data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBPeripheralManager(im)startAdvertising:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startAdvertising"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?)"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startAdvertising:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startAdvertising(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startAdvertising"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "advertisementData"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional dictionary containing the data you want to advertise. The peripheral manager only supports two keys: ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "advertisementData"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you start advertising peripheral data, the peripheral manager calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManagerDidStartAdvertising(_:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of its delegate object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Core Bluetooth advertises data on a “best effort” basis, due to limited space and because there may be multiple apps advertising simultaneously. While in the foreground, your app can use up to 28 bytes of space in the initial advertisement data for any combination of the supported advertising data keys. If no this space remains, there’s an additional 10 bytes of space in the scan response, usable only for the local name (represented by the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key). Note that these sizes don’t include the 2 bytes of header information required for each new data type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Any service UUIDs contained in the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key that don’t fit in the allotted space go to a special “overflow” area. These services are discoverable only by an iOS device explicitly scanning for them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "While your app is in the background, the local name isn’t advertised and all service UUIDs are in the overflow area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For details about the format of advertising and response data, see the Bluetooth 4.0 specification, Volume 3, Part C, Section 11.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey": {
      "abstract": [
        {
          "text": "The local name of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataLocalNameKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatalocalnamekey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of UUIDs found in the overflow area of the advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataOverflowServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataoverflowserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager": {
      "abstract": [
        {
          "text": "An object that manages and advertises peripheral services exposed by this app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBPeripheralManager"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBPeripheralManager"
        }
      ],
      "role": "symbol",
      "title": "CBPeripheralManager",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the peripheral is advertising data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAdvertising"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isAdvertising"
        }
      ],
      "role": "symbol",
      "title": "isAdvertising",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager/isadvertising"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)": {
      "abstract": [
        {
          "text": "Advertises peripheral manager data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAdvertising"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAdvertising:"
        }
      ],
      "role": "symbol",
      "title": "startAdvertising(_:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager/startadvertising(_:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()": {
      "abstract": [
        {
          "text": "Stops advertising peripheral manager data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAdvertising"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopAdvertising"
        }
      ],
      "role": "symbol",
      "title": "stopAdvertising()",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager/stopadvertising()"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManagerDidStartAdvertising(_:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate the peripheral manager started advertising the local peripheral device’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peripheralManagerDidStartAdvertising"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBPeripheralManager",
          "text": "CBPeripheralManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManagerDelegate/peripheralManagerDidStartAdvertising(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peripheralManagerDidStartAdvertising:error:"
        }
      ],
      "role": "symbol",
      "title": "peripheralManagerDidStartAdvertising(_:error:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanagerdelegate/peripheralmanagerdidstartadvertising(_:error:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/advertising-data": {
      "abstract": [],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/advertising-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Advertising Data",
      "type": "topic",
      "url": "/documentation/corebluetooth/advertising-data"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Advertising",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/advertising-data",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising"
      ],
      "title": "Managing Advertising"
    }
  ],
  "topicSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startAdvertising:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAdvertising:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Advertising",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/advertising-data",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising"
              ],
              "title": "Managing Advertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startAdvertising:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,id>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "advertisementData"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An optional dictionary containing the data you want to advertise. The peripheral manager only supports two keys: ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "advertisementData"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/title",
          "value": "CBAdvertisementDataLocalNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataLocalNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManagerDidStartAdvertising(_:error:)/title",
          "value": "peripheralManagerDidStartAdvertising:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManagerDelegate~1peripheralManagerDidStartAdvertising(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peripheralManagerDidStartAdvertising:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/title",
          "value": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1isAdvertising/title",
          "value": "isAdvertising"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1isAdvertising/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isAdvertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1stopAdvertising()/title",
          "value": "stopAdvertising"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1stopAdvertising()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopAdvertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1startAdvertising(_:)/title",
          "value": "startAdvertising:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1startAdvertising(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAdvertising:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/title",
          "value": "CBPeripheralManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBPeripheralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBPeripheralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/title",
          "value": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbperipheralmanager/startadvertising(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbperipheralmanager/startadvertising(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
