{
  "abstract": [
    {
      "text": "The unique identifier of the context object.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context/identifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIWritingToolsCoordinatorContext(py)identifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "identifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4UUIDV",
        "text": "UUID"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "identifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "identifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4UUIDV",
              "text": "UUID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object initializes the value of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this property at creation time. Use this value to identify the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "context object within your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator": {
      "abstract": [
        {
          "text": "An object that manages interactions between Writing Tools and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your custom text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWritingToolsCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWritingToolsCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UIWritingToolsCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context": {
      "abstract": [
        {
          "text": "A data object that you use to share your custom view’s text with Writing Tools.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "role": "symbol",
      "title": "UIWritingToolsCoordinator.Context",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinator/context"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context/identifier": {
      "abstract": [
        {
          "text": "The unique identifier of the context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinator/context/identifier"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV": {
      "abstract": [
        {
          "text": "A universally unique value to identify types, interfaces, and other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4UUIDV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UUID",
      "type": "topic",
      "url": "/documentation/foundation/uuid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUUID",
                    "text": "NSUUID"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "identifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator/title",
          "value": "UIWritingToolsCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context/title",
          "value": "UIWritingToolsCoordinatorContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwritingtoolscoordinator/context/identifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwritingtoolscoordinator/context/identifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
