{
  "abstract": [
    {
      "text": "Creates a context object with the specified attributed string and range",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "information.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context/init(attributedString:range:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIWritingToolsCoordinatorContext(im)initWithAttributedString:range:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "attributedString"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAttributedString",
        "text": "NSAttributedString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "range"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "NSRange"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithAttributedString:range:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(attributedString:range:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "attributedString"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAttributedString",
              "text": "NSAttributedString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string that contains some or all of the content",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "from your view’s text storage. This initializer makes a copy of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "string you provide, so you can discard the original when you’re done.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attributedString"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The portion of ",
                  "type": "text"
                },
                {
                  "code": "attributedString",
                  "type": "codeVoice"
                },
                {
                  "text": " you want Writing Tools to",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "evaluate. If you want Writing Tools to evaluate the entire string you",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "provided, specify a range with a location of ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": " and a length equal to",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "your string’s length. If you want Writing Tools to evaluate only part",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "of the string, provide the appropriate range in this parameter. Writing",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Tools suggests changes only to the range of text you specify, but it",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "can consider text outside that range during the evaluation process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When Writing Tools asks for your view’s current selection, it’s best to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "create a string that includes text before and after that selection. During",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the evaluation process, Writing Tools can use the additional text you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "provided to improve the results it delivers. If you do provide additional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "text, set the ",
              "type": "text"
            },
            {
              "code": "range",
              "type": "codeVoice"
            },
            {
              "text": " parameter to the portion of ",
              "type": "text"
            },
            {
              "code": "attributedString",
              "type": "codeVoice"
            },
            {
              "text": " with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the current selection. Don’t use the ",
              "type": "text"
            },
            {
              "code": "range",
              "type": "codeVoice"
            },
            {
              "text": " parameter to specify the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "location of the text in your view’s text storage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator": {
      "abstract": [
        {
          "text": "An object that manages interactions between Writing Tools and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your custom text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWritingToolsCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWritingToolsCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UIWritingToolsCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context": {
      "abstract": [
        {
          "text": "A data object that you use to share your custom view’s text with Writing Tools.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "role": "symbol",
      "title": "UIWritingToolsCoordinator.Context",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinator/context"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context/init(attributedString:range:)": {
      "abstract": [
        {
          "text": "Creates a context object with the specified attributed string and range",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context/init(attributedString:range:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedString:range:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedString:range:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinator/context/init(attributedstring:range:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithAttributedString:range:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedString:range:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinator/Context"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithAttributedString:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSAttributedString",
                    "text": "NSAttributedString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attributedString"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "range:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@_NSRange",
                    "text": "NSRange"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "range"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that contains some or all of the content",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "from your view’s text storage. This initializer makes a copy of the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "string you provide, so you can discard the original when you’re done.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attributedString"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The portion of ",
                        "type": "text"
                      },
                      {
                        "code": "attributedString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " you want Writing Tools to",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "evaluate. If you want Writing Tools to evaluate the entire string you",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "provided, specify a range with a location of ",
                        "type": "text"
                      },
                      {
                        "code": "0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and a length equal to",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "your string’s length. If you want Writing Tools to evaluate only part",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "of the string, provide the appropriate range in this parameter. Writing",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "Tools suggests changes only to the range of text you specify, but it",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "can consider text outside that range during the evaluation process.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "range"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator/title",
          "value": "UIWritingToolsCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context/title",
          "value": "UIWritingToolsCoordinatorContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context~1init(attributedString:range:)/title",
          "value": "initWithAttributedString:range:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinator~1Context~1init(attributedString:range:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedString:range:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwritingtoolscoordinator/context/init(attributedstring:range:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwritingtoolscoordinator/context/init(attributedstring:range:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
