{
  "abstract": [
    {
      "text": "The aspects of a photo picker’s default appearance that your app can disable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHPickerConfiguration(py)disabledCapabilities",
    "fragments": [
      {
        "kind": "identifier",
        "text": "disabledCapabilities"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "disabledCapabilities"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "disabledCapabilities"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHPickerCapabilities",
              "text": "PHPickerCapabilities"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "disabledCapabilities"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities": {
      "abstract": [
        {
          "text": "Options that customize the look and behavior of the photos picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "role": "symbol",
      "title": "PHPickerCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickercapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities": {
      "abstract": [
        {
          "text": "The aspects of a photo picker’s default appearance that your app can disable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "disabledCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/disabledCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "disabledCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/disabledcapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s perimeter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode": {
      "abstract": [
        {
          "text": "A layout type for the photos in the picker’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-c.class/mode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum": {
      "abstract": [
        {
          "text": "Layout options that determine how the picker orders photos visually.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickermode-c.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration": {
      "abstract": [
        {
          "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHPickerUpdateConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPickerUpdateConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerupdateconfiguration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-picker-appearance-and-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/mode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-c.enum",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-c.class/edgesWithoutContentMargins",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerUpdateConfiguration"
      ],
      "title": "Customizing picker appearance and behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/title",
          "value": "PHPickerCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerconfiguration-c.class/disabledcapabilities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
