{
  "abstract": [
    {
      "text": "Creates a location coordinate object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22CLLocationCoordinate2DVABycfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D": {
      "abstract": [
        {
          "text": "The latitude and longitude associated with a location, specified using the WGS 84 reference frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2D",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init()": {
      "abstract": [
        {
          "text": "Creates a location coordinate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d/init()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init(latitude:longitude:)": {
      "abstract": [
        {
          "text": "Creates a location coordination object with the specified latitude and longitude values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "latitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "longitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init(latitude:longitude:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(latitude:longitude:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d/init(latitude:longitude:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)": {
      "abstract": [
        {
          "text": "Formats a latitude and longitude value into a coordinate data structure format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2DMake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2DMake"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2DMake(_:_:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2dmake(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-location-coordinate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init(latitude:longitude:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)"
      ],
      "title": "Creating a location coordinate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2DMake(_:_:)/title",
          "value": "CLLocationCoordinate2DMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2DMake(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2DMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/title",
          "value": "CLLocationCoordinate2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationcoordinate2d/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
