{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addClip"},{"kind":"text","text":"()"}],"platforms":["macOS"]}]},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This method uses the current winding rule to determine the clipping shape of the receiver. This method does not affect the receiver’s path.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)"],"generated":true,"title":"Specifying a Clipping Path","anchor":"Specifying-a-Clipping-Path"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/addclip()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/addclip()"]}],"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()","interfaceLanguage":"swift"},"metadata":{"platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"roleHeading":"Instance Method","title":"addClip()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"addClip"}],"modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addClip"},{"kind":"text","text":"()"}],"externalID":"c:objc(cs)NSBezierPath(im)addClip","role":"symbol"},"abstract":[{"type":"text","text":"Intersects the area enclosed by the path with the clipping path of the current graphics context and makes the resulting shape the current clipping path."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()","navigatorTitle":[{"kind":"identifier","text":"addClip"}],"title":"addClip()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addClip"},{"kind":"text","text":"()"}],"abstract":[{"text":"Intersects the area enclosed by the path with the clipping path of the current graphics context and makes the resulting shape the current clipping path.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/addclip()"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clip"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsbezierpath/clip(_:)","navigatorTitle":[{"kind":"identifier","text":"clipRect:"}],"title":"clip(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)","type":"topic","abstract":[{"text":"Intersects the specified rectangle with the clipping path of the current graphics context and makes the resulting shape the current clipping path.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()":{"kind":"symbol","url":"/documentation/appkit/nsbezierpath/setclip()","abstract":[{"type":"text","text":"Replaces the clipping path of the current graphics context with the area inside the path."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClip"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()","type":"topic","title":"setClip()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setClip"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"addClip"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"addClip","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)"],"anchor":"Specifying-a-Clipping-Path","title":"Specifying a Clipping Path"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"addClip"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1addClip()/title","value":"addClip","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1addClip()/fragments","value":[{"text":"- ","kind":"text"},{"text":"addClip","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1clip(_:)/title","value":"clipRect:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1clip(_:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clipRect:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1setClip()/title","value":"setClip","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1setClip()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClip"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"kind":"identifier","text":"NSBezierPath"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}