{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/append(withcgglyphs:count:in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/append(withcgglyphs:count:in:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)"},"abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCGGlyphs"},{"kind":"text","text":" "},{"kind":"internalParam","text":"glyphs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@CGGlyph","preciseIdentifier":"c:@T@CGGlyph","text":"CGGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont"},{"text":")","kind":"text"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithCGGlyphs:count:inFont:"}],"title":"append(withCGGlyphs:count:in:)","platforms":[{"unavailable":false,"introducedAt":"10.13","name":"macOS","deprecated":false,"beta":false}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCGGlyphs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@CGGlyph","kind":"typeIdentifier","text":"CGGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier","text":"NSFont"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)NSBezierPath(im)appendBezierPathWithCGGlyphs:count:inFont:","modules":[{"name":"AppKit"}]},"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Appending-Common-Shapes-to-a-Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)"],"title":"Appending Common Shapes to a Path"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Appends a rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendrect(_:)","title":"appendRect(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithRect:"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCGGlyphs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"appendBezierPathWithCGGlyphs:count:inFont:","kind":"identifier"}],"url":"/documentation/appkit/nsbezierpath/append(withcgglyphs:count:in:)","title":"append(withCGGlyphs:count:in:)","abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSFont":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSFont"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSFont"}],"url":"/documentation/appkit/nsfont","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","title":"NSFont","abstract":[{"text":"The representation of a font in an app.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"text":"(","kind":"text"},{"text":"withCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"startAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endAngle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clockwise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","abstract":[{"type":"text","text":"Appends an arc of a circle to the path."}],"url":"/documentation/appkit/nsbezierpath/appendarc(withcenter:radius:startangle:endangle:clockwise:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)":{"navigatorTitle":[{"text":"appendBezierPathWithOvalInRect:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendOval"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"appendOval(in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","url":"/documentation/appkit/nsbezierpath/appendoval(in:)","type":"topic","abstract":[{"type":"text","text":"Appends an oval path to the path, inscribing the oval in the specified rectangle."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SP":{"url":"/documentation/Swift/UnsafePointer","kind":"symbol","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"title":"UnsafePointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafePointer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Pointee","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)":{"navigatorTitle":[{"text":"appendBezierPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath","text":"NSBezierPath"},{"kind":"text","text":")"}],"title":"append(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","url":"/documentation/appkit/nsbezierpath/append(_:)","type":"topic","abstract":[{"type":"text","text":"Appends the contents of the specified path object to the path."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRoundedRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"xRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"yRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Appends a rounded rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendroundedrect(_:xradius:yradius:)","title":"appendRoundedRect(_:xRadius:yRadius:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"appendBezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"startAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:"}],"url":"/documentation/appkit/nsbezierpath/appendarc(withcenter:radius:startangle:endangle:)","title":"appendArc(withCenter:radius:startAngle:endAngle:)","abstract":[{"text":"Appends an arc of a circle to the path.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)":{"navigatorTitle":[{"text":"appendBezierPathWithGlyph:inFont:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendGlyph"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"deprecated":true,"title":"appendGlyph(_:in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","url":"/documentation/appkit/nsbezierpath/appendglyph(_:in:)","type":"topic","abstract":[{"text":"Appends an outline of the specified glyph to the path.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)":{"url":"/documentation/appkit/nsbezierpath/appendglyphs(_:count:in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","navigatorTitle":[{"text":"appendBezierPathWithGlyphs:count:inFont:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendGlyphs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}],"title":"appendGlyphs(_:count:in:)","type":"topic","deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)":{"url":"/documentation/appkit/nsbezierpath/appendarc(from:to:radius:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendArc","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","type":"topic","kind":"symbol","title":"appendArc(from:to:radius:)","abstract":[{"text":"Appends an arc to the path.","type":"text"}],"navigatorTitle":[{"text":"appendBezierPathWithArcFromPoint:toPoint:radius:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"text":"withCGGlyph","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGGlyph","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGGlyph"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithCGGlyph:inFont:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","title":"append(withCGGlyph:in:)","url":"/documentation/appkit/nsbezierpath/append(withcgglyph:in:)","role":"symbol","abstract":[{"type":"text","text":"Appends an outline of the specified glyph to the path."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.externally.resolved.symbol/c:@T@CGGlyph":{"identifier":"doc://com.externally.resolved.symbol/c:@T@CGGlyph","title":"CGGlyph","fragments":[{"text":"typealias ","kind":"text"},{"text":"CGGlyph","kind":"identifier"}],"abstract":[{"type":"text","text":"An index into the internal glyph table of a font."}],"role":"symbol","url":"/documentation/coregraphics/cgglyph","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)":{"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithPoints:count:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendPoints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSPointArray","preciseIdentifier":"c:@T@NSPointArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"appendPoints(_:count:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","url":"/documentation/appkit/nsbezierpath/appendpoints(_:count:)","type":"topic","abstract":[{"type":"text","text":"Appends a series of line segments to the path."}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithPackedGlyphs:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendPackedGlyphs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">)"}],"title":"appendPackedGlyphs(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)","deprecated":true,"abstract":[{"text":"Appends an array of packed glyphs to the path.","type":"text"}],"url":"/documentation/appkit/nsbezierpath/appendpackedglyphs(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.13","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"appendBezierPathWithCGGlyphs:count:inFont:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithCGGlyphs:count:inFont:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Appending Common Shapes to a Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)"],"anchor":"Appending-Common-Shapes-to-a-Path","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"appendBezierPathWithCGGlyphs:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph","identifier":"doc://com.externally.resolved.symbol/c:@T@CGGlyph"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"glyphs"},{"kind":"text","text":" "},{"kind":"identifier","text":"count:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"count"},{"kind":"text","text":" "},{"kind":"identifier","text":"inFont:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier","text":"NSFont"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"font"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/title","value":"appendBezierPathWithRect:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithRect:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyphs:count:in:)/title","value":"appendBezierPathWithCGGlyphs:count:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyphs:count:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithCGGlyphs:count:inFont:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title","value":"NSFont","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments","value":[{"text":"NSFont","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle","value":[{"kind":"identifier","text":"NSFont"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:clockwise:)/title","value":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:clockwise:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendOval(in:)/title","value":"appendBezierPathWithOvalInRect:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendOval(in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithOvalInRect:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(_:)/title","value":"appendBezierPath:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPath:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRoundedRect(_:xRadius:yRadius:)/title","value":"appendBezierPathWithRoundedRect:xRadius:yRadius:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRoundedRect(_:xRadius:yRadius:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:)/title","value":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyph(_:in:)/title","value":"appendBezierPathWithGlyph:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyph(_:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithGlyph:inFont:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyphs(_:count:in:)/title","value":"appendBezierPathWithGlyphs:count:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyphs(_:count:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithGlyphs:count:inFont:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(from:to:radius:)/title","value":"appendBezierPathWithArcFromPoint:toPoint:radius:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(from:to:radius:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithArcFromPoint:toPoint:radius:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyph:in:)/title","value":"appendBezierPathWithCGGlyph:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyph:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithCGGlyph:inFont:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPoints(_:count:)/title","value":"appendBezierPathWithPoints:count:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPoints(_:count:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithPoints:count:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPackedGlyphs(_:)/title","value":"appendBezierPathWithPackedGlyphs:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPackedGlyphs(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithPackedGlyphs:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}