{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendArc","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"point1","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"point2","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"point1","content":[{"inlineContent":[{"text":"The middle point of the angle.","type":"text"}],"type":"paragraph"}]},{"name":"point2","content":[{"inlineContent":[{"text":"The end point of the angle.","type":"text"}],"type":"paragraph"}]},{"name":"radius","content":[{"inlineContent":[{"text":"The radius of the circle inscribed in the angle.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The created arc is defined by a circle inscribed inside the angle specified by three points: the current point, the "},{"type":"codeVoice","code":"fromPoint"},{"type":"text","text":" parameter, and the  "},{"type":"codeVoice","code":"toPoint"},{"type":"text","text":" parameter (in that order). The arc itself lies on the perimeter of the circle, whose radius is specified by the "},{"type":"codeVoice","code":"radius"},{"type":"text","text":" parameter. The arc is drawn between the two points of the circle that are tangent to the two legs of the angle."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The arc usually does not contain the points in the "},{"code":"fromPoint","type":"codeVoice"},{"type":"text","text":" and "},{"code":"toPoint","type":"codeVoice"},{"type":"text","text":" parameters. If the starting point of the arc does not coincide with the current point, a line is drawn between the two points. The starting point of the arc lies on the line defined by the current point and the "},{"code":"fromPoint","type":"codeVoice"},{"type":"text","text":" parameter."}]},{"type":"paragraph","inlineContent":[{"text":"You must set the path’s current point (using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)"},{"text":" method or through the creation of a preceding line or curve segment) before you invoke this method. If the path is empty, this method raises an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1412113-genericexception"},{"text":" exception.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Depending on the length of the arc, this method may add multiple connected curve segments to the path."}]}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/appendarc(from:to:radius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/appendarc(from:to:radius:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"appendBezierPathWithArcFromPoint:toPoint:radius:","kind":"identifier"}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"role":"symbol","title":"appendArc(from:to:radius:)","externalID":"c:objc(cs)NSBezierPath(im)appendBezierPathWithArcFromPoint:toPoint:radius:"},"sections":[],"abstract":[{"type":"text","text":"Appends an arc to the path."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)"],"generated":true,"title":"Appending Common Shapes to a Path","anchor":"Appending-Common-Shapes-to-a-Path"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)":{"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithPoints:count:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendPoints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSPointArray","preciseIdentifier":"c:@T@NSPointArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"appendPoints(_:count:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","url":"/documentation/appkit/nsbezierpath/appendpoints(_:count:)","type":"topic","abstract":[{"type":"text","text":"Appends a series of line segments to the path."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"text":"withCGGlyph","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGGlyph","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGGlyph"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithCGGlyph:inFont:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","title":"append(withCGGlyph:in:)","url":"/documentation/appkit/nsbezierpath/append(withcgglyph:in:)","role":"symbol","abstract":[{"type":"text","text":"Appends an outline of the specified glyph to the path."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"text":"(","kind":"text"},{"text":"withCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"startAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endAngle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clockwise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","abstract":[{"type":"text","text":"Appends an arc of a circle to the path."}],"url":"/documentation/appkit/nsbezierpath/appendarc(withcenter:radius:startangle:endangle:clockwise:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"startAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:"}],"url":"/documentation/appkit/nsbezierpath/appendarc(withcenter:radius:startangle:endangle:)","title":"appendArc(withCenter:radius:startAngle:endAngle:)","abstract":[{"text":"Appends an arc of a circle to the path.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCGGlyphs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"appendBezierPathWithCGGlyphs:count:inFont:","kind":"identifier"}],"url":"/documentation/appkit/nsbezierpath/append(withcgglyphs:count:in:)","title":"append(withCGGlyphs:count:in:)","abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)":{"navigatorTitle":[{"text":"appendBezierPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath","text":"NSBezierPath"},{"kind":"text","text":")"}],"title":"append(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","url":"/documentation/appkit/nsbezierpath/append(_:)","type":"topic","abstract":[{"type":"text","text":"Appends the contents of the specified path object to the path."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)":{"url":"/documentation/appkit/nsbezierpath/appendglyphs(_:count:in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","navigatorTitle":[{"text":"appendBezierPathWithGlyphs:count:inFont:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendGlyphs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}],"title":"appendGlyphs(_:count:in:)","type":"topic","deprecated":true},"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1412113-genericexception":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1412113-genericexception","url":"/documentation/foundation/nsexceptionname/1412113-genericexception","fragments":[{"kind":"text","text":"static let "},{"kind":"identifier","text":"genericException"},{"kind":"text","text":": NSExceptionName"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A generic name for an exception."}],"title":"genericException"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","abstract":[{"text":"The basic type for all floating-point values.","type":"text"}],"type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)":{"title":"move(to:)","url":"/documentation/appkit/nsbezierpath/move(to:)","navigatorTitle":[{"text":"moveToPoint:","kind":"identifier"}],"abstract":[{"text":"Moves the path’s current point to the specified location.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"move","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)":{"url":"/documentation/appkit/nsbezierpath/appendarc(from:to:radius:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendArc","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","type":"topic","kind":"symbol","title":"appendArc(from:to:radius:)","abstract":[{"text":"Appends an arc to the path.","type":"text"}],"navigatorTitle":[{"text":"appendBezierPathWithArcFromPoint:toPoint:radius:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)":{"navigatorTitle":[{"text":"appendBezierPathWithGlyph:inFont:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendGlyph"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"deprecated":true,"title":"appendGlyph(_:in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","url":"/documentation/appkit/nsbezierpath/appendglyph(_:in:)","type":"topic","abstract":[{"text":"Appends an outline of the specified glyph to the path.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"CGFloat","kind":"identifier"}],"abstract":[{"text":"The basic type for floating-point scalar values in Core Graphics and related frameworks.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)":{"navigatorTitle":[{"text":"appendBezierPathWithOvalInRect:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendOval"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"appendOval(in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","url":"/documentation/appkit/nsbezierpath/appendoval(in:)","type":"topic","abstract":[{"type":"text","text":"Appends an oval path to the path, inscribing the oval in the specified rectangle."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRoundedRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"xRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"yRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Appends a rounded rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendroundedrect(_:xradius:yradius:)","title":"appendRoundedRect(_:xRadius:yRadius:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"appendBezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Appends a rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendrect(_:)","title":"appendRect(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithRect:"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithPackedGlyphs:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendPackedGlyphs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">)"}],"title":"appendPackedGlyphs(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)","deprecated":true,"abstract":[{"text":"Appends an array of packed glyphs to the path.","type":"text"}],"url":"/documentation/appkit/nsbezierpath/appendpackedglyphs(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"appendBezierPathWithArcFromPoint:toPoint:radius:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithArcFromPoint:toPoint:radius:"}],"op":"replace"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Appending Common Shapes to a Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)"],"anchor":"Appending-Common-Shapes-to-a-Path"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"appendBezierPathWithArcFromPoint:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"point1"},{"kind":"text","text":" "},{"kind":"identifier","text":"toPoint:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"point2"},{"text":" ","kind":"text"},{"text":"radius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"radius","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The middle point of the angle."}]}],"name":"point1"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The end point of the angle."}]}],"name":"point2"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The radius of the circle inscribed in the angle.","type":"text"}]}],"name":"radius"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPoints(_:count:)/title","value":"appendBezierPathWithPoints:count:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPoints(_:count:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithPoints:count:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyph:in:)/title","value":"appendBezierPathWithCGGlyph:inFont:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyph:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithCGGlyph:inFont:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:clockwise:)/title","value":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:clockwise:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:)/title","value":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyphs:count:in:)/title","value":"appendBezierPathWithCGGlyphs:count:inFont:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyphs:count:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithCGGlyphs:count:inFont:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(_:)/title","value":"appendBezierPath:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPath:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyphs(_:count:in:)/title","value":"appendBezierPathWithGlyphs:count:inFont:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyphs(_:count:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithGlyphs:count:inFont:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11412113-genericexception/title","value":"NSGenericException"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"kind":"identifier","text":"NSBezierPath"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/title","value":"moveToPoint:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToPoint:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(from:to:radius:)/title","value":"appendBezierPathWithArcFromPoint:toPoint:radius:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(from:to:radius:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithArcFromPoint:toPoint:radius:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyph(_:in:)/title","value":"appendBezierPathWithGlyph:inFont:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyph(_:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithGlyph:inFont:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendOval(in:)/title","value":"appendBezierPathWithOvalInRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendOval(in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithOvalInRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRoundedRect(_:xRadius:yRadius:)/title","value":"appendBezierPathWithRoundedRect:xRadius:yRadius:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRoundedRect(_:xRadius:yRadius:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/title","value":"appendBezierPathWithRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithRect:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPackedGlyphs(_:)/title","value":"appendBezierPathWithPackedGlyphs:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPackedGlyphs(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithPackedGlyphs:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}