{"abstract":[{"type":"text","text":"Appends the outlines of the specified glyphs to the path."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appendGlyphs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"glyphs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","identifier":"doc://com.externally.resolved.symbol/s:Sp","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGlyph"},{"text":">, ","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"font","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"glyphs","content":[{"type":"paragraph","inlineContent":[{"text":"A C-style array of ","type":"text"},{"code":"NSGlyph","type":"codeVoice"},{"text":" data types to add to the path.","type":"text"}]}]},{"name":"count","content":[{"type":"paragraph","inlineContent":[{"text":"The number of glyphs in the ","type":"text"},{"type":"codeVoice","code":"glyphs"},{"text":" parameter.","type":"text"}]}]},{"name":"font","content":[{"type":"paragraph","inlineContent":[{"text":"The font in which the glyphs are encoded.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If the glyphs are not encoded in the font specified by the ","type":"text"},{"code":"fontObj","type":"codeVoice"},{"text":" parameter—that is, the font does not have an entry for one of the specified glyphs—then no path is appended to the receiver.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You must set the path’s current point (using the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)"},{"text":" method or through the creation of a preceding line or curve segment) before you invoke this method. If the path is empty, this method raises an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1412113-genericexception"},{"text":" exception.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nsbezierpath/appendglyphs(_:count:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbezierpath/appendglyphs(_:count:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","title":"appendGlyphs(_:count:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendGlyphs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"AppKit"}],"extendedModule":"AppKit","navigatorTitle":[{"text":"appendBezierPathWithGlyphs:count:inFont:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","platforms":[{"beta":false,"deprecatedAt":"10.14","message":"Use -appendBezierPathWithCGGlyphs:count:inFont: instead","introducedAt":"10.0","name":"macOS","deprecated":false,"unavailable":false}],"externalID":"c:objc(cs)NSBezierPath(im)appendBezierPathWithGlyphs:count:inFont:"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","type":"reference"},{"text":" instead.","type":"text"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)"],"anchor":"Related-Documentation"},{"title":"Appending Common Shapes to a Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)"],"generated":true,"anchor":"Appending-Common-Shapes-to-a-Path"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSGlyph":{"kind":"symbol","url":"/documentation/appkit/nsglyph","title":"NSGlyph","navigatorTitle":[{"text":"NSGlyph","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSGlyph","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The type used to specify glyphs."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGlyph","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"text":"withCGGlyph","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGGlyph","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGGlyph"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithCGGlyph:inFont:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","title":"append(withCGGlyph:in:)","url":"/documentation/appkit/nsbezierpath/append(withcgglyph:in:)","role":"symbol","abstract":[{"type":"text","text":"Appends an outline of the specified glyph to the path."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)":{"navigatorTitle":[{"text":"appendBezierPathWithOvalInRect:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendOval"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"appendOval(in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","url":"/documentation/appkit/nsbezierpath/appendoval(in:)","type":"topic","abstract":[{"type":"text","text":"Appends an oval path to the path, inscribing the oval in the specified rectangle."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)":{"url":"/documentation/appkit/nsbezierpath/appendglyphs(_:count:in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyphs(_:count:in:)","navigatorTitle":[{"text":"appendBezierPathWithGlyphs:count:inFont:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendGlyphs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}],"title":"appendGlyphs(_:count:in:)","type":"topic","deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Appends a rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendrect(_:)","title":"appendRect(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithRect:"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)":{"navigatorTitle":[{"text":"appendBezierPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath","text":"NSBezierPath"},{"kind":"text","text":")"}],"title":"append(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","url":"/documentation/appkit/nsbezierpath/append(_:)","type":"topic","abstract":[{"type":"text","text":"Appends the contents of the specified path object to the path."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)":{"title":"move(to:)","url":"/documentation/appkit/nsbezierpath/move(to:)","navigatorTitle":[{"text":"moveToPoint:","kind":"identifier"}],"abstract":[{"text":"Moves the path’s current point to the specified location.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"move","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSFont":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSFont"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSFont"}],"url":"/documentation/appkit/nsfont","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","title":"NSFont","abstract":[{"text":"The representation of a font in an app.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithPackedGlyphs:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendPackedGlyphs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">)"}],"title":"appendPackedGlyphs(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)","deprecated":true,"abstract":[{"text":"Appends an array of packed glyphs to the path.","type":"text"}],"url":"/documentation/appkit/nsbezierpath/appendpackedglyphs(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)":{"url":"/documentation/appkit/nsbezierpath/appendarc(from:to:radius:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendArc","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","type":"topic","kind":"symbol","title":"appendArc(from:to:radius:)","abstract":[{"text":"Appends an arc to the path.","type":"text"}],"navigatorTitle":[{"text":"appendBezierPathWithArcFromPoint:toPoint:radius:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)":{"kind":"symbol","url":"/documentation/appkit/nsbezierpath/drawpackedglyphs(_:at:)","role":"symbol","navigatorTitle":[{"text":"drawPackedGlyphs:atPoint:","kind":"identifier"}],"abstract":[{"text":"Draws a set of packed glyphs at the specified point in the current coordinate system.","type":"text"}],"title":"drawPackedGlyphs(_:at:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawPackedGlyphs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)":{"navigatorTitle":[{"text":"appendBezierPathWithGlyph:inFont:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendGlyph"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSFont","preciseIdentifier":"c:objc(cs)NSFont"},{"text":")","kind":"text"}],"deprecated":true,"title":"appendGlyph(_:in:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","url":"/documentation/appkit/nsbezierpath/appendglyph(_:in:)","type":"topic","abstract":[{"text":"Appends an outline of the specified glyph to the path.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1412113-genericexception":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1412113-genericexception","url":"/documentation/foundation/nsexceptionname/1412113-genericexception","fragments":[{"kind":"text","text":"static let "},{"kind":"identifier","text":"genericException"},{"kind":"text","text":": NSExceptionName"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A generic name for an exception."}],"title":"genericException"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRoundedRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"xRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"yRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Appends a rounded rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendroundedrect(_:xradius:yradius:)","title":"appendRoundedRect(_:xRadius:yRadius:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"appendBezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"text":"(","kind":"text"},{"text":"withCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"startAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endAngle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clockwise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","abstract":[{"type":"text","text":"Appends an arc of a circle to the path."}],"url":"/documentation/appkit/nsbezierpath/appendarc(withcenter:radius:startangle:endangle:clockwise:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)":{"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithPoints:count:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendPoints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSPointArray","preciseIdentifier":"c:@T@NSPointArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"appendPoints(_:count:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","url":"/documentation/appkit/nsbezierpath/appendpoints(_:count:)","type":"topic","abstract":[{"type":"text","text":"Appends a series of line segments to the path."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendArc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"startAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:"}],"url":"/documentation/appkit/nsbezierpath/appendarc(withcenter:radius:startangle:endangle:)","title":"appendArc(withCenter:radius:startAngle:endAngle:)","abstract":[{"text":"Appends an arc of a circle to the path.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.externally.resolved.symbol/s:Sp":{"title":"UnsafeMutablePointer","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sp","role":"symbol","url":"/documentation/Swift/UnsafeMutablePointer","kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"Pointee"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"kind":"text","text":" "},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}],"abstract":[{"text":"A pointer for accessing and manipulating data of a specific type.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCGGlyphs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGGlyph","preciseIdentifier":"c:@T@CGGlyph"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSFont","text":"NSFont","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"appendBezierPathWithCGGlyphs:count:inFont:","kind":"identifier"}],"url":"/documentation/appkit/nsbezierpath/append(withcgglyphs:count:in:)","title":"append(withCGGlyphs:count:in:)","abstract":[{"text":"Appends the outlines of the specified glyphs to the path.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.0","unavailable":false,"beta":false,"name":"macOS","deprecatedAt":"10.14","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"appendBezierPathWithGlyphs:count:inFont:"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithGlyphs:count:inFont:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"path":"/hierarchy"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)"]},{"title":"Appending Common Shapes to a Path","anchor":"Appending-Common-Shapes-to-a-Path","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPoints(_:count:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendOval(in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(from:to:radius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendArc(withCenter:radius:startAngle:endAngle:clockwise:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRoundedRect(_:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyph:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendGlyph(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendPackedGlyphs(_:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"appendBezierPathWithGlyphs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSGlyph","preciseIdentifier":"c:@T@NSGlyph","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSGlyph"},{"text":" *) ","kind":"text"},{"text":"glyphs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"count:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"count","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inFont:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSFont","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSFont"},{"text":" *) ","kind":"text"},{"text":"font","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A C-style array of "},{"type":"codeVoice","code":"NSGlyph"},{"type":"text","text":" data types to add to the path."}]}],"name":"glyphs"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of glyphs in the "},{"code":"glyphs","type":"codeVoice"},{"type":"text","text":" parameter."}]}],"name":"count"},{"content":[{"inlineContent":[{"text":"The font in which the glyphs are encoded.","type":"text"}],"type":"paragraph"}],"name":"font"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/append(withCGGlyphs:count:in:)"},{"text":" instead.","type":"text"}]}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/title","value":"NSGlyph","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/fragments","value":[{"kind":"identifier","text":"NSGlyph"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGlyph/navigatorTitle","value":[{"text":"NSGlyph","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyph:in:)/title","value":"appendBezierPathWithCGGlyph:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyph:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithCGGlyph:inFont:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendOval(in:)/title","value":"appendBezierPathWithOvalInRect:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendOval(in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithOvalInRect:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyphs(_:count:in:)/title","value":"appendBezierPathWithGlyphs:count:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyphs(_:count:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithGlyphs:count:inFont:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/title","value":"appendBezierPathWithRect:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithRect:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(_:)/title","value":"appendBezierPath:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPath:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/title","value":"moveToPoint:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToPoint:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title","value":"NSFont","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments","value":[{"text":"NSFont","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle","value":[{"text":"NSFont","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPackedGlyphs(_:)/title","value":"appendBezierPathWithPackedGlyphs:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPackedGlyphs(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithPackedGlyphs:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(from:to:radius:)/title","value":"appendBezierPathWithArcFromPoint:toPoint:radius:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(from:to:radius:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithArcFromPoint:toPoint:radius:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1drawPackedGlyphs(_:at:)/title","value":"drawPackedGlyphs:atPoint:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1drawPackedGlyphs(_:at:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"drawPackedGlyphs:atPoint:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyph(_:in:)/title","value":"appendBezierPathWithGlyph:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendGlyph(_:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithGlyph:inFont:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11412113-genericexception/title","value":"NSGenericException","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRoundedRect(_:xRadius:yRadius:)/title","value":"appendBezierPathWithRoundedRect:xRadius:yRadius:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRoundedRect(_:xRadius:yRadius:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:clockwise:)/title","value":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:clockwise:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPoints(_:count:)/title","value":"appendBezierPathWithPoints:count:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendPoints(_:count:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithPoints:count:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:)/title","value":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendArc(withCenter:radius:startAngle:endAngle:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"kind":"identifier","text":"NSBezierPath"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyphs:count:in:)/title","value":"appendBezierPathWithCGGlyphs:count:inFont:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1append(withCGGlyphs:count:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithCGGlyphs:count:inFont:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}