{"variants":[{"paths":["/documentation/appkit/nsbezierpath/bezierpath"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290"],"anchor":"Related-Documentation"},{"title":"Creating a Bézier Path","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(rect:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed"],"anchor":"Creating-a-Bézier-Path"}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath"},{"text":" *) ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new empty path object.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bezierPath"}],"symbolKind":"method","title":"bezierPath","role":"symbol","externalID":"c:objc(cs)NSBezierPath(cm)bezierPath","platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"modules":[{"name":"AppKit"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"bezierPath"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Creates and returns a new Bézier path object."}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath","interfaceLanguage":"occ"},"references":{"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290":{"url":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290","title":"Cocoa Drawing Guide","titleInlineContent":[{"type":"text","text":"Cocoa Drawing Guide"}],"type":"link","identifier":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath":{"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bezierPath"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath","abstract":[{"type":"text","text":"Creates and returns a new Bézier path object."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPath"}],"url":"/documentation/appkit/nsbezierpath/bezierpath","title":"bezierPath"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reversed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed","abstract":[{"type":"text","text":"A path containing the reversed contents of the current path object."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathByReversingPath"}],"url":"/documentation/appkit/nsbezierpath/reversed","title":"reversed"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flattened"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathByFlatteningPath"}],"abstract":[{"text":"A flattened version of the path object.","type":"text"}],"title":"flattened","kind":"symbol","role":"symbol","url":"/documentation/appkit/nsbezierpath/flattened","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPath","preciseIdentifier":"c:@T@CGPathRef"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithCGPath:"}],"url":"/documentation/appkit/nsbezierpath/init(cgpath:)","title":"init(cgPath:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roundedRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"xRadius"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"yRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)","abstract":[{"type":"text","text":"Creates and returns a new Bézier path object initialized with a rounded rectangular path."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithRoundedRect:xRadius:yRadius:"}],"url":"/documentation/appkit/nsbezierpath/init(roundedrect:xradius:yradius:)","title":"init(roundedRect:xRadius:yRadius:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ovalIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)","abstract":[{"text":"Creates and returns a new Bézier path object initialized with an oval path inscribed in the specified rectangle.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithOvalInRect:"}],"url":"/documentation/appkit/nsbezierpath/init(ovalin:)","title":"init(ovalIn:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(rect:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(rect:)","abstract":[{"type":"text","text":"Creates and returns a new Bézier path object initialized with a rectangular path."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithRect:"}],"url":"/documentation/appkit/nsbezierpath/init(rect:)","title":"init(rect:)"}},"variantOverrides":[{"patch":[{"value":"bezierPathByReversingPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1reversed/title"},{"value":[{"text":"bezierPathByReversingPath","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1reversed/fragments"},{"value":"NSBezierPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title"},{"value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments"},{"value":[{"kind":"identifier","text":"NSBezierPath"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle"},{"value":"bezierPathByFlatteningPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1flattened/title"},{"value":[{"kind":"identifier","text":"bezierPathByFlatteningPath"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1flattened/fragments"},{"value":"bezierPathWithCGPath:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(cgPath:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"bezierPathWithCGPath:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(cgPath:)/fragments"},{"value":"bezierPathWithRoundedRect:xRadius:yRadius:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(roundedRect:xRadius:yRadius:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bezierPathWithRoundedRect:xRadius:yRadius:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(roundedRect:xRadius:yRadius:)/fragments"},{"value":"bezierPathWithOvalInRect:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(ovalIn:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"bezierPathWithOvalInRect:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(ovalIn:)/fragments"},{"value":"bezierPathWithRect:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(rect:)/title"},{"value":[{"kind":"text","text":"+ "},{"text":"bezierPathWithRect:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(rect:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}