{"seeAlsoSections":[{"anchor":"Constructing-a-Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint1:controlPoint2:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/close()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeMove(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeLine(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint1:controlPoint2:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint:)"],"generated":true,"title":"Constructing a Path"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"curve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"endPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"controlPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"curve(to:controlPoint:)","platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"curve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"controlPoint"},{"kind":"text","text":": "},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"curveToPoint:controlPoint:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSBezierPath(im)curveToPoint:controlPoint:","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/curve(to:controlpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/curve(to:controlpoint:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint:)"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)":{"kind":"symbol","title":"line(to:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"line"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsbezierpath/line(to:)","navigatorTitle":[{"text":"lineToPoint:","kind":"identifier"}],"abstract":[{"type":"text","text":"Appends a straight line to the path."}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeLine(to:)":{"title":"relativeLine(to:)","url":"/documentation/appkit/nsbezierpath/relativeline(to:)","navigatorTitle":[{"text":"relativeLineToPoint:","kind":"identifier"}],"abstract":[{"text":"Appends a straight line segment to the path starting at the current point and moving towards the specified point, relative to the current location.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"relativeLine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeLine(to:)","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/close()":{"kind":"symbol","title":"close()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/close()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"close","kind":"identifier"},{"text":"()","kind":"text"}],"url":"/documentation/appkit/nsbezierpath/close()","navigatorTitle":[{"text":"closePath","kind":"identifier"}],"abstract":[{"type":"text","text":"Closes the most recently added subpath."}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)":{"title":"move(to:)","url":"/documentation/appkit/nsbezierpath/move(to:)","navigatorTitle":[{"text":"moveToPoint:","kind":"identifier"}],"abstract":[{"text":"Moves the path’s current point to the specified location.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"move","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeMove(to:)":{"title":"relativeMove(to:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"relativeMoveToPoint:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relativeMove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeMove(to:)","url":"/documentation/appkit/nsbezierpath/relativemove(to:)","abstract":[{"type":"text","text":"Moves the path’s current point to a new point whose location is the specified distance from the current point."}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint:)":{"title":"curve(to:controlPoint:)","url":"/documentation/appkit/nsbezierpath/curve(to:controlpoint:)","navigatorTitle":[{"text":"curveToPoint:controlPoint:","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"curve"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controlPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint:)","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint1:controlPoint2:)":{"title":"relativeCurve(to:controlPoint1:controlPoint2:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"relativeCurveToPoint:controlPoint1:controlPoint2:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relativeCurve","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controlPoint1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controlPoint2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint1:controlPoint2:)","url":"/documentation/appkit/nsbezierpath/relativecurve(to:controlpoint1:controlpoint2:)","abstract":[{"text":"Adds a Bezier cubic curve to the path from the current point to a new location, which is specified as a relative distance from the current point.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint1:controlPoint2:)":{"title":"curve(to:controlPoint1:controlPoint2:)","url":"/documentation/appkit/nsbezierpath/curve(to:controlpoint1:controlpoint2:)","navigatorTitle":[{"text":"curveToPoint:controlPoint1:controlPoint2:","kind":"identifier"}],"abstract":[{"text":"Adds a Bezier cubic curve to the path.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"curve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controlPoint1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controlPoint2","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint1:controlPoint2:)","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint:)":{"kind":"symbol","title":"relativeCurve(to:controlPoint:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relativeCurve","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controlPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsbezierpath/relativecurve(to:controlpoint:)","navigatorTitle":[{"text":"relativeCurveToPoint:controlPoint:","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"14.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"curveToPoint:controlPoint:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"curveToPoint:controlPoint:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Constructing-a-Path","generated":true,"title":"Constructing a Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/curve(to:controlPoint1:controlPoint2:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/close()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeMove(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeLine(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint1:controlPoint2:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/relativeCurve(to:controlPoint:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"curveToPoint:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"endPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlPoint:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"controlPoint"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1line(to:)/title","value":"lineToPoint:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1line(to:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lineToPoint:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeLine(to:)/title","value":"relativeLineToPoint:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"relativeLineToPoint:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeLine(to:)/fragments"},{"value":"closePath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1close()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"closePath","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1close()/fragments"},{"value":"moveToPoint:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToPoint:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/fragments"},{"value":"relativeMoveToPoint:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeMove(to:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"relativeMoveToPoint:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeMove(to:)/fragments"},{"value":"curveToPoint:controlPoint:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1curve(to:controlPoint:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"curveToPoint:controlPoint:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1curve(to:controlPoint:)/fragments"},{"value":"relativeCurveToPoint:controlPoint1:controlPoint2:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeCurve(to:controlPoint1:controlPoint2:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"relativeCurveToPoint:controlPoint1:controlPoint2:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeCurve(to:controlPoint1:controlPoint2:)/fragments"},{"value":"curveToPoint:controlPoint1:controlPoint2:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1curve(to:controlPoint1:controlPoint2:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"curveToPoint:controlPoint1:controlPoint2:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1curve(to:controlPoint1:controlPoint2:)/fragments"},{"value":"relativeCurveToPoint:controlPoint:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeCurve(to:controlPoint:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"relativeCurveToPoint:controlPoint:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1relativeCurve(to:controlPoint:)/fragments"},{"value":"NSBezierPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title"},{"value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments"},{"value":[{"kind":"identifier","text":"NSBezierPath"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}