{
  "abstract": [
    {
      "text": "Returns the default line join style for all paths.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineJoinStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSBezierPath(cpy)defaultLineJoinStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "defaultLineJoinStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSBezierPath",
        "text": "NSBezierPath"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSLineJoinStyle",
        "text": "LineJoinStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "defaultLineJoinStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "defaultLineJoinStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "defaultLineJoinStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSBezierPath",
              "text": "NSBezierPath"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineJoinStyle",
              "text": "LineJoinStyle"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default line join style or ",
              "type": "text"
            },
            {
              "code": "NSMiterLineJoinStyle",
              "type": "codeVoice"
            },
            {
              "text": " if no other value has been set. For a list of values, see Constants.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of the joins between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultFlatness": {
      "abstract": [
        {
          "text": "The default flatness value for all paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultFlatness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultFlatness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultFlatness"
        }
      ],
      "role": "symbol",
      "title": "defaultFlatness",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/defaultflatness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineCapStyle": {
      "abstract": [
        {
          "text": "Returns the default line cap style for all paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultLineCapStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBezierPath",
          "text": "NSBezierPath"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineCapStyle",
          "text": "LineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineCapStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultLineCapStyle"
        }
      ],
      "role": "symbol",
      "title": "defaultLineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/defaultlinecapstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineJoinStyle": {
      "abstract": [
        {
          "text": "Returns the default line join style for all paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultLineJoinStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBezierPath",
          "text": "NSBezierPath"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineJoinStyle",
          "text": "LineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineJoinStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultLineJoinStyle"
        }
      ],
      "role": "symbol",
      "title": "defaultLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/defaultlinejoinstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineWidth": {
      "abstract": [
        {
          "text": "Returns the default line width for the all paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultLineWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultLineWidth"
        }
      ],
      "role": "symbol",
      "title": "defaultLineWidth",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/defaultlinewidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultMiterLimit": {
      "abstract": [
        {
          "text": "Returns the default miter limit for all paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMiterLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultMiterLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMiterLimit"
        }
      ],
      "role": "symbol",
      "title": "defaultMiterLimit",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/defaultmiterlimit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultWindingRule": {
      "abstract": [
        {
          "text": "Returns the default winding rule used to fill all paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultWindingRule"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBezierPath",
          "text": "NSBezierPath"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindingRule",
          "text": "WindingRule"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultWindingRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultWindingRule"
        }
      ],
      "role": "symbol",
      "title": "defaultWindingRule",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/defaultwindingrule"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/lineJoinStyle-swift.property": {
      "abstract": [
        {
          "text": "The line join style for the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineJoinStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBezierPath",
          "text": "NSBezierPath"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineJoinStyle",
          "text": "LineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/lineJoinStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineJoinStyle"
        }
      ],
      "role": "symbol",
      "title": "lineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/lineJoinStyle-swift.property"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Configuring-Default-Path-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultWindingRule",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineCapStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultMiterLimit",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultFlatness"
      ],
      "title": "Configuring Default Path Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "defaultLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/lineJoinStyle-swift.property"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Configuring-Default-Path-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultWindingRule",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineCapStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultLineWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultMiterLimit",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/defaultFlatness"
              ],
              "title": "Configuring Default Path Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSLineJoinStyle",
                    "text": "NSLineJoinStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "defaultLineJoinStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/title",
          "value": "NSLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultLineCapStyle/title",
          "value": "defaultLineCapStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultLineCapStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultMiterLimit/title",
          "value": "defaultMiterLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultMiterLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMiterLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1lineJoinStyle-swift.property/title",
          "value": "lineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1lineJoinStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultLineWidth/title",
          "value": "defaultLineWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultLineWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultLineWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultLineJoinStyle/title",
          "value": "defaultLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultLineJoinStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultWindingRule/title",
          "value": "defaultWindingRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultWindingRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultWindingRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultFlatness/title",
          "value": "defaultFlatness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1defaultFlatness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultFlatness"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/defaultlinejoinstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/defaultlinejoinstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
