{
  "abstract": [
    {
      "text": "Constants that specify basic path element commands.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSBezierPathElement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ElementType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ElementType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSBezierPath.ElementType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ElementType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These commands are enough to define all of the possible path shapes. Each command has one or more points that contain information needed to position the path element. Most path elements use the current drawing point as the starting point for drawing. For more details, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Paths/Paths.html#//apple_ref/doc/uid/TP40003290-CH206",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType": {
      "abstract": [
        {
          "text": "Constants that specify basic path element commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath": {
      "abstract": [
        {
          "text": "Marks the end of the current subpath at the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closePath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementClosePath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.closePath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/closepath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubicCurveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementCubicCurveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.cubicCurveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/cubiccurveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo": {
      "abstract": [
        {
          "text": "Creates a curved line segment from the current point to the specified endpoint using two control points to define the curve.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBezierPath",
          "text": "NSBezierPath"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezierPathElement",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementCurveTo"
        }
      ],
      "role": "symbol",
      "title": "curveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/curveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo": {
      "abstract": [
        {
          "text": "Creates a straight line from the current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementLineTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.lineTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/lineto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo": {
      "abstract": [
        {
          "text": "Moves the path object’s current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementMoveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.moveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/moveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quadraticCurveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementQuadraticCurveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.quadraticCurveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/quadraticcurveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of endpoints for an open path when it is stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of the joins between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the winding rule a Bézier path uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindingRule"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WindingRule"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.WindingRule",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/windingrule-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClosePathBezierPathElement": {
      "abstract": [
        {
          "text": "Marks the end of the current subpath at the specified point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSClosePathBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClosePathBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSClosePathBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nsclosepathbezierpathelement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCurveToBezierPathElement": {
      "abstract": [
        {
          "text": "Creates a curved line segment from the current point to the specified endpoint using two control points to define the curve.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCurveToBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCurveToBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCurveToBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nscurvetobezierpathelement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineToBezierPathElement": {
      "abstract": [
        {
          "text": "Creates a straight line from the current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLineToBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineToBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLineToBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nslinetobezierpathelement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMoveToBezierPathElement": {
      "abstract": [
        {
          "text": "Moves the path object’s current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMoveToBezierPathElement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMoveToBezierPathElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMoveToBezierPathElement",
      "type": "topic",
      "url": "/documentation/appkit/nsmovetobezierpathelement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Paths/Paths.html#//apple_ref/doc/uid/TP40003290-CH206": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Paths/Paths.html#//apple_ref/doc/uid/TP40003290-CH206",
      "title": "Paths",
      "titleInlineContent": [
        {
          "text": "Paths",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Paths/Paths.html#//apple_ref/doc/uid/TP40003290-CH206"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBezierPathElement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMoveToBezierPathElement",
                "doc://com.apple.appkit/documentation/AppKit/NSLineToBezierPathElement",
                "doc://com.apple.appkit/documentation/AppKit/NSCurveToBezierPathElement",
                "doc://com.apple.appkit/documentation/AppKit/NSClosePathBezierPathElement"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSBezierPathElement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1curveTo/title",
          "value": "NSBezierPathElementCurveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1curveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementCurveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1quadraticCurveTo/title",
          "value": "NSBezierPathElementQuadraticCurveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1quadraticCurveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementQuadraticCurveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/title",
          "value": "NSLineCapStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/title",
          "value": "NSWindingRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1lineTo/title",
          "value": "NSBezierPathElementLineTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1lineTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementLineTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1moveTo/title",
          "value": "NSBezierPathElementMoveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1moveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementMoveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1cubicCurveTo/title",
          "value": "NSBezierPathElementCubicCurveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1cubicCurveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementCubicCurveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/title",
          "value": "NSBezierPathElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/title",
          "value": "NSLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1closePath/title",
          "value": "NSBezierPathElementClosePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1closePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementClosePath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/elementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/elementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
