{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"abstract":[{"text":"Paints the region enclosed by the path.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/fill()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/fill()"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"},{"text":"()","kind":"text"}],"title":"fill()","navigatorTitle":[{"text":"fill","kind":"identifier"}],"role":"symbol","modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method","externalID":"c:objc(cs)NSBezierPath(im)fill"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSColor/set()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/windingRule-swift.property"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)"],"anchor":"Drawing-a-Path","generated":true,"title":"Drawing a Path"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method fills the path using the current fill color and the receiver’s current winding rule. If the path contains any open subpaths, this method implicitly closes them before painting the fill region.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The painted region includes the pixels right up to, but not including, the path line itself. For paths with large line widths, this can result in overlap between the fill region and the stroked path (which is itself centered on the path line)."}]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()":{"abstract":[{"type":"text","text":"Draws a line along the path using the current stroke color and drawing attributes."}],"navigatorTitle":[{"text":"stroke","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()","url":"/documentation/appkit/nsbezierpath/stroke()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stroke","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"stroke()"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fillRect:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsbezierpath/fill(_:)","abstract":[{"text":"Fills the specified rectangular path with the current fill color.","type":"text"}],"title":"fill(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()","abstract":[{"text":"Paints the region enclosed by the path.","type":"text"}],"navigatorTitle":[{"text":"fill","kind":"identifier"}],"url":"/documentation/appkit/nsbezierpath/fill()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"fill()"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/windingRule-swift.property":{"abstract":[{"type":"text","text":"The winding rule used to fill the path."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/windingRule-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"windingRule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WindingRule","preciseIdentifier":"c:@E@NSWindingRule"}],"title":"windingRule","url":"/documentation/appkit/nsbezierpath/windingrule-swift.property","navigatorTitle":[{"kind":"identifier","text":"windingRule"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)":{"kind":"symbol","url":"/documentation/appkit/nsbezierpath/drawpackedglyphs(_:at:)","role":"symbol","navigatorTitle":[{"text":"drawPackedGlyphs:atPoint:","kind":"identifier"}],"abstract":[{"text":"Draws a set of packed glyphs at the specified point in the current coordinate system.","type":"text"}],"title":"drawPackedGlyphs(_:at:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawPackedGlyphs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSColor/set()":{"abstract":[{"text":"Sets the color of subsequent drawing to the color that the color object represents.","type":"text"}],"type":"topic","title":"set()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColor/set()","role":"symbol","url":"/documentation/appkit/nscolor/set()","navigatorTitle":[{"text":"set","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)":{"abstract":[{"text":"Strokes a line between two points using the current stroke color and the default drawing attributes.","type":"text"}],"url":"/documentation/appkit/nsbezierpath/strokeline(from:to:)","kind":"symbol","role":"symbol","title":"strokeLine(from:to:)","navigatorTitle":[{"text":"strokeLineFromPoint:toPoint:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strokeLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)":{"abstract":[{"type":"text","text":"Strokes the path of the specified rectangle using the current stroke color and the default drawing attributes."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stroke"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"},{"kind":"text","text":")"}],"title":"stroke(_:)","url":"/documentation/appkit/nsbezierpath/stroke(_:)","navigatorTitle":[{"kind":"identifier","text":"strokeRect:"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"fill","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fill"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSColor/set()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/windingRule-swift.property"],"anchor":"Related-Documentation","title":"Related Documentation"},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)"],"anchor":"Drawing-a-Path","title":"Drawing a Path"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fill","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke()/title","op":"replace","value":"stroke"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stroke","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill(_:)/title","op":"replace","value":"fillRect:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill(_:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fillRect:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill()/title","op":"replace","value":"fill"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fill"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1windingRule-swift.property/title","op":"replace","value":"windingRule"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1windingRule-swift.property/fragments","op":"replace","value":[{"kind":"identifier","text":"windingRule"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","op":"replace","value":"NSBezierPath"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","op":"replace","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSBezierPath"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1drawPackedGlyphs(_:at:)/title","op":"replace","value":"drawPackedGlyphs:atPoint:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1drawPackedGlyphs(_:at:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"drawPackedGlyphs:atPoint:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1set()/title","op":"replace","value":"set"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1set()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"set"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1strokeLine(from:to:)/title","op":"replace","value":"strokeLineFromPoint:toPoint:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1strokeLine(from:to:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"strokeLineFromPoint:toPoint:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke(_:)/title","op":"replace","value":"strokeRect:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke(_:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"strokeRect:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}