{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(rect:)","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)"],"anchor":"Related-Documentation"},{"title":"Creating a Bézier Path","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed"],"generated":true,"anchor":"Creating-a-Bézier-Path"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"kind":"text","text":")"}],"platforms":["macOS"]}]},{"parameters":[{"name":"rect","content":[{"type":"paragraph","inlineContent":[{"text":"The rectangle describing the path to create.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new path object with the rectangular path.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The path is constructed by starting at the origin of "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":" and adding line segments in a counterclockwise direction."}]}]}],"abstract":[{"text":"Creates and returns a new Bézier path object initialized with a rectangular path.","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"bezierPathWithRect:"}],"platforms":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}],"externalID":"c:objc(cs)NSBezierPath(cm)bezierPathWithRect:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"modules":[{"name":"AppKit"}],"title":"init(rect:)"},"variants":[{"paths":["/documentation/appkit/nsbezierpath/init(rect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbezierpath/init(rect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ovalIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)","abstract":[{"text":"Creates and returns a new Bézier path object initialized with an oval path inscribed in the specified rectangle.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithOvalInRect:"}],"url":"/documentation/appkit/nsbezierpath/init(ovalin:)","title":"init(ovalIn:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath":{"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bezierPath"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath","abstract":[{"type":"text","text":"Creates and returns a new Bézier path object."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPath"}],"url":"/documentation/appkit/nsbezierpath/bezierpath","title":"bezierPath"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)":{"abstract":[{"type":"text","text":"Strokes the path of the specified rectangle using the current stroke color and the default drawing attributes."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stroke"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"},{"kind":"text","text":")"}],"title":"stroke(_:)","url":"/documentation/appkit/nsbezierpath/stroke(_:)","navigatorTitle":[{"kind":"identifier","text":"strokeRect:"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roundedRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"xRadius"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"yRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)","abstract":[{"type":"text","text":"Creates and returns a new Bézier path object initialized with a rounded rectangular path."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithRoundedRect:xRadius:yRadius:"}],"url":"/documentation/appkit/nsbezierpath/init(roundedrect:xradius:yradius:)","title":"init(roundedRect:xRadius:yRadius:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Appends a rectangular path to the path."}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/appendrect(_:)","title":"appendRect(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendBezierPathWithRect:"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flattened"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathByFlatteningPath"}],"abstract":[{"text":"A flattened version of the path object.","type":"text"}],"title":"flattened","kind":"symbol","role":"symbol","url":"/documentation/appkit/nsbezierpath/flattened","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fillRect:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsbezierpath/fill(_:)","abstract":[{"text":"Fills the specified rectangular path with the current fill color.","type":"text"}],"title":"fill(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPath","preciseIdentifier":"c:@T@CGPathRef"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithCGPath:"}],"url":"/documentation/appkit/nsbezierpath/init(cgpath:)","title":"init(cgPath:)"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reversed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed","abstract":[{"type":"text","text":"A path containing the reversed contents of the current path object."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathByReversingPath"}],"url":"/documentation/appkit/nsbezierpath/reversed","title":"reversed"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(rect:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(rect:)","abstract":[{"type":"text","text":"Creates and returns a new Bézier path object initialized with a rectangular path."}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathWithRect:"}],"url":"/documentation/appkit/nsbezierpath/init(rect:)","title":"init(rect:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"bezierPathWithRect:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bezierPathWithRect:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/appendRect(_:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/bezierPath","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(ovalIn:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(roundedRect:xRadius:yRadius:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/init(cgPath:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/flattened","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/reversed"],"generated":true,"title":"Creating a Bézier Path","anchor":"Creating-a-Bézier-Path"}],"op":"replace"},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","kind":"typeIdentifier","text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"bezierPathWithRect:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The rectangle describing the path to create.","type":"text"}]}],"name":"rect"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"A new path object with the rectangular path."}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(ovalIn:)/title","value":"bezierPathWithOvalInRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(ovalIn:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bezierPathWithOvalInRect:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke(_:)/title","value":"strokeRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke(_:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"strokeRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(roundedRect:xRadius:yRadius:)/title","value":"bezierPathWithRoundedRect:xRadius:yRadius:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(roundedRect:xRadius:yRadius:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"bezierPathWithRoundedRect:xRadius:yRadius:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/title","value":"appendBezierPathWithRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1appendRect(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendBezierPathWithRect:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1flattened/title","value":"bezierPathByFlatteningPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1flattened/fragments","value":[{"kind":"identifier","text":"bezierPathByFlatteningPath"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill(_:)/title","value":"fillRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill(_:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fillRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(cgPath:)/title","value":"bezierPathWithCGPath:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(cgPath:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"bezierPathWithCGPath:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1reversed/title","value":"bezierPathByReversingPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1reversed/fragments","value":[{"kind":"identifier","text":"bezierPathByReversingPath"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(rect:)/title","value":"bezierPathWithRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1init(rect:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"bezierPathWithRect:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}