{
  "abstract": [
    {
      "text": "Constants that specify the shape of the joins between connected segments of a stroked path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSLineJoinStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LineJoinStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LineJoinStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSBezierPath.LineJoinStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LineJoinStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBevelLineJoinStyle": {
      "abstract": [
        {
          "text": "Specifies a bevel line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBevelLineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBevelLineJoinStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBevelLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbevellinejoinstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType": {
      "abstract": [
        {
          "text": "Constants that specify basic path element commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of endpoints for an open path when it is stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of the joins between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineJoinStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/bevel": {
      "abstract": [
        {
          "text": "Specifies a bevel line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bevel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/bevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineJoinStyleBevel"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle.bevel",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum/bevel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter": {
      "abstract": [
        {
          "text": "Specifies a miter line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineJoinStyleMiter"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle.miter",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum/miter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/round": {
      "abstract": [
        {
          "text": "Specifies a round line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "round"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/round",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineJoinStyleRound"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineJoinStyle.round",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum/round"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the winding rule a Bézier path uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindingRule"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WindingRule"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.WindingRule",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/windingrule-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMiterLineJoinStyle": {
      "abstract": [
        {
          "text": "Specifies a miter line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMiterLineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMiterLineJoinStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMiterLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsmiterlinejoinstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundLineJoinStyle": {
      "abstract": [
        {
          "text": "Specifies a round line shape of the joints between connected segments of a stroked path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundLineJoinStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundLineJoinStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundLineJoinStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundlinejoinstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/round",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/bevel"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/miter",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/round",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum/bevel"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMiterLineJoinStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSRoundLineJoinStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSBevelLineJoinStyle"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSLineJoinStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/title",
          "value": "NSLineCapStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/title",
          "value": "NSLineJoinStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/title",
          "value": "NSWindingRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindingRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1round/title",
          "value": "NSLineJoinStyleRound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1round/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyleRound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1bevel/title",
          "value": "NSLineJoinStyleBevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1bevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyleBevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/title",
          "value": "NSBezierPathElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1miter/title",
          "value": "NSLineJoinStyleMiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum~1miter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineJoinStyleMiter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
