{"topicSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/init(rawValue:)"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"seeAlsoSections":[{"generated":true,"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum"]}],"metadata":{"navigatorTitle":[{"text":"LineCapStyle","kind":"identifier"}],"role":"symbol","extendedModule":"AppKit","symbolKind":"enum","title":"NSBezierPath.LineCapStyle","platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"modules":[{"name":"AppKit"}],"roleHeading":"Enumeration","externalID":"c:@E@NSLineCapStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineCapStyle","kind":"identifier"}]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineCapStyle"}],"platforms":["macOS"],"languages":["swift"]}]}],"abstract":[{"text":"Constants that specify the shape of endpoints for an open path when it is stroked.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"sections":[],"variants":[{"paths":["/documentation/appkit/nsbezierpath/linecapstyle-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbezierpath/linecapstyle-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum":{"role":"symbol","url":"/documentation/appkit/nsbezierpath/linejoinstyle-swift.enum","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum","title":"NSBezierPath.LineJoinStyle","abstract":[{"text":"Constants that specify the shape of the joins between connected segments of a stroked path.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"LineJoinStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineJoinStyle","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round","type":"topic","url":"/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/round","title":"NSBezierPath.LineCapStyle.round","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSLineCapStyleRound"}],"abstract":[{"type":"text","text":"Specifies a round line cap style for endpoints for an open path when stroked."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"round"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum":{"url":"/documentation/appkit/nsbezierpath/windingrule-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WindingRule"}],"title":"NSBezierPath.WindingRule","kind":"symbol","abstract":[{"text":"Constants that specify the winding rule a Bézier path uses.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WindingRule"}]},"doc://com.apple.appkit/documentation/AppKit/NSSquareLineCapStyle":{"fragments":[{"kind":"identifier","text":"NSSquareLineCapStyle"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSquareLineCapStyle","abstract":[{"text":"Specifies a square line cap style for endpoints for an open path when stroked.","type":"text"}],"type":"topic","title":"NSSquareLineCapStyle","kind":"symbol","deprecated":true,"url":"/documentation/appkit/nssquarelinecapstyle","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSButtLineCapStyle":{"abstract":[{"type":"text","text":"Specifies a butt line cap style for endpoints for an open path when stroked."}],"url":"/documentation/appkit/nsbuttlinecapstyle","kind":"symbol","role":"symbol","title":"NSButtLineCapStyle","identifier":"doc://com.apple.appkit/documentation/AppKit/NSButtLineCapStyle","deprecated":true,"type":"topic","fragments":[{"kind":"identifier","text":"NSButtLineCapStyle"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"type":"text","text":"Describes an unsigned integer."}],"url":"/documentation/objectivec/nsuinteger","kind":"symbol","role":"symbol","title":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType","url":"/documentation/appkit/nsbezierpath/elementtype","abstract":[{"text":"Constants that specify basic path element commands.","type":"text"}],"kind":"symbol","title":"NSBezierPath.ElementType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElementType","kind":"identifier"}],"navigatorTitle":[{"text":"ElementType","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSRoundLineCapStyle":{"role":"symbol","type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Specifies a round line cap style for endpoints for an open path when stroked."}],"url":"/documentation/appkit/nsroundlinecapstyle","kind":"symbol","fragments":[{"text":"NSRoundLineCapStyle","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRoundLineCapStyle","title":"NSRoundLineCapStyle"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum":{"url":"/documentation/appkit/nsbezierpath/linecapstyle-swift.enum","title":"NSBezierPath.LineCapStyle","kind":"symbol","abstract":[{"text":"Constants that specify the shape of endpoints for an open path when it is stroked.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LineCapStyle","kind":"identifier"}],"navigatorTitle":[{"text":"LineCapStyle","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"square","kind":"identifier"}],"url":"/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/square","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square","role":"symbol","title":"NSBezierPath.LineCapStyle.square","kind":"symbol","abstract":[{"type":"text","text":"Specifies a square line cap style for endpoints for an open path when stroked."}],"navigatorTitle":[{"text":"NSLineCapStyleSquare","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/init(rawvalue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/init(rawValue:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt":{"type":"topic","navigatorTitle":[{"text":"NSLineCapStyleButt","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"butt","kind":"identifier"}],"title":"NSBezierPath.LineCapStyle.butt","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt","url":"/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/butt","abstract":[{"text":"Specifies a butt line cap style for endpoints for an open path when stroked.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration","path":"/metadata/roleHeading","op":"replace"},{"value":"NSLineCapStyle","path":"/metadata/title","op":"replace"},{"value":"enum","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"NSLineCapStyle","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"NSLineCapStyle","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/butt","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/round","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square"]},{"title":"Deprecated Constants","anchor":"Deprecated-Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSButtLineCapStyle","doc://com.apple.appkit/documentation/AppKit/NSRoundLineCapStyle","doc://com.apple.appkit/documentation/AppKit/NSSquareLineCapStyle"]}],"op":"replace"},{"path":"/relationshipsSections","value":null,"op":"replace"},{"path":"/seeAlsoSections","value":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineJoinStyle-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/WindingRule-swift.enum"],"title":"Constants"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLineCapStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/title","value":"NSLineJoinStyle","op":"replace"},{"op":"replace","value":[{"text":"NSLineJoinStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSLineJoinStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineJoinStyle-swift.enum/navigatorTitle"},{"op":"replace","value":"NSLineCapStyleRound","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1round/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSLineCapStyleRound"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1round/fragments"},{"op":"replace","value":"NSWindingRule","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindingRule"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/fragments"},{"value":[{"kind":"identifier","text":"NSWindingRule"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1WindingRule-swift.enum/navigatorTitle"},{"value":"NSBezierPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"kind":"identifier","text":"NSBezierPath"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/title","value":"NSBezierPathElement"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/fragments","value":[{"text":"NSBezierPathElement","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/navigatorTitle","value":[{"text":"NSBezierPathElement","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/title","value":"NSLineCapStyle"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/fragments","value":[{"text":"NSLineCapStyle","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"NSLineCapStyle"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1square/title","value":"NSLineCapStyleSquare"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1square/fragments","value":[{"text":"NSLineCapStyleSquare","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1butt/title","value":"NSLineCapStyleButt"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1butt/fragments","value":[{"text":"NSLineCapStyleButt","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}