{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllPoints","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"abstract":[{"type":"text","text":"Removes all path elements from the path, effectively clearing the path."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/removeallpoints()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/removeallpoints()"]}],"metadata":{"externalID":"c:objc(cs)NSBezierPath(im)removeAllPoints","navigatorTitle":[{"text":"removeAllPoints","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"removeAllPoints()","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"symbolKind":"method","modules":[{"name":"AppKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllPoints","kind":"identifier"},{"text":"()","kind":"text"}]},"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Accessing-Elements-of-a-Path","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/cgPath","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/elementCount","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:associatedPoints:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setAssociatedPoints(_:at:)"],"title":"Accessing Elements of a Path"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/removeAllPoints()"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/cgPath":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/cgPath","abstract":[],"title":"cgPath","type":"topic","url":"/documentation/appkit/nsbezierpath/cgpath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPath"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGPathRef","kind":"typeIdentifier","text":"CGPath"}],"navigatorTitle":[{"kind":"identifier","text":"CGPath"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/removeAllPoints()":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/removeAllPoints()","abstract":[{"text":"Removes all path elements from the path, effectively clearing the path.","type":"text"}],"title":"removeAllPoints()","type":"topic","url":"/documentation/appkit/nsbezierpath/removeallpoints()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllPoints"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"removeAllPoints"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setAssociatedPoints(_:at:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setAssociatedPoints(_:at:)","abstract":[{"text":"Changes the points associated with the specified path element.","type":"text"}],"title":"setAssociatedPoints(_:at:)","type":"topic","url":"/documentation/appkit/nsbezierpath/setassociatedpoints(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAssociatedPoints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSPointArray","preciseIdentifier":"c:@T@NSPointArray"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setAssociatedPoints:atIndex:"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:associatedPoints:)":{"url":"/documentation/appkit/nsbezierpath/element(at:associatedpoints:)","abstract":[{"text":"Gets the element type and (and optionally) the associated points for the path element at the specified index.","type":"text"}],"navigatorTitle":[{"text":"elementAtIndex:associatedPoints:","kind":"identifier"}],"type":"topic","title":"element(at:associatedPoints:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:associatedPoints:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"element","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"associatedPoints","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPointArray","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPointArray"},{"text":"?) -> ","kind":"text"},{"text":"NSBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath"},{"text":".","kind":"text"},{"text":"ElementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSBezierPathElement"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:)","abstract":[{"text":"Returns the type of path element at the specified index.","type":"text"}],"title":"element(at:)","type":"topic","url":"/documentation/appkit/nsbezierpath/element(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"element"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> ","kind":"text"},{"text":"NSBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath"},{"text":".","kind":"text"},{"text":"ElementType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSBezierPathElement"}],"navigatorTitle":[{"text":"elementAtIndex:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/elementCount":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/elementCount","abstract":[{"text":"The total number of path elements in the path.","type":"text"}],"title":"elementCount","type":"topic","url":"/documentation/appkit/nsbezierpath/elementcount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elementCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"elementCount"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"removeAllPoints","path":"/metadata/title"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllPoints"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"op":"replace"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/cgPath","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/elementCount","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/element(at:associatedPoints:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setAssociatedPoints(_:at:)"],"title":"Accessing Elements of a Path","generated":true,"anchor":"Accessing-Elements-of-a-Path"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeAllPoints"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"CGPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1cgPath/title"},{"value":[{"kind":"identifier","text":"CGPath"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1cgPath/fragments"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1removeAllPoints()/title","op":"replace","value":"removeAllPoints"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1removeAllPoints()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeAllPoints","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","op":"replace","value":"NSBezierPath"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","op":"replace","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","op":"replace","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1setAssociatedPoints(_:at:)/title","op":"replace","value":"setAssociatedPoints:atIndex:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1setAssociatedPoints(_:at:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAssociatedPoints:atIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1element(at:associatedPoints:)/title","op":"replace","value":"elementAtIndex:associatedPoints:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1element(at:associatedPoints:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"elementAtIndex:associatedPoints:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1element(at:)/title","value":"elementAtIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1element(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"elementAtIndex:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1elementCount/title","value":"elementCount","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1elementCount/fragments","value":[{"kind":"identifier","text":"elementCount"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}