{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)"],"generated":true,"title":"Specifying a Clipping Path","anchor":"Specifying-a-Clipping-Path"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Replaces the clipping path of the current graphics context with the area inside the path.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/setclip()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/setclip()"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClip"},{"kind":"text","text":"()"}],"externalID":"c:objc(cs)NSBezierPath(im)setClip","platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol","title":"setClip()","navigatorTitle":[{"kind":"identifier","text":"setClip"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClip"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"You should avoid using this method as a way of adjusting the clipping path, as it may expand the clipping path beyond the bounds set by the enclosing view. If you do use this method, be sure to save the graphics state prior to modifying the clipping path and restore the graphics state when you are done.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This method uses the current winding rule to determine the clipping shape of the receiver. This method does not affect the receiver’s path.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()":{"kind":"symbol","url":"/documentation/appkit/nsbezierpath/setclip()","abstract":[{"type":"text","text":"Replaces the clipping path of the current graphics context with the area inside the path."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClip"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/setClip()","type":"topic","title":"setClip()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setClip"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method":{"role":"symbol","abstract":[{"type":"text","text":"Removes the context’s graphics state from the top of the graphics state stack and makes the next graphics state the current graphics state."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method","navigatorTitle":[{"text":"restoreGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/restoregraphicsstate()-swift.method","title":"restoreGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()","navigatorTitle":[{"kind":"identifier","text":"addClip"}],"title":"addClip()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addClip"},{"kind":"text","text":"()"}],"abstract":[{"text":"Intersects the area enclosed by the path with the clipping path of the current graphics context and makes the resulting shape the current clipping path.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsbezierpath/addclip()"},"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method":{"role":"symbol","abstract":[{"text":"Saves the current graphics state and creates a new graphics state on the top of the stack.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","navigatorTitle":[{"text":"saveGraphicsState","kind":"identifier"}],"url":"/documentation/appkit/nsgraphicscontext/savegraphicsstate()-swift.method","title":"saveGraphicsState()","kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clip"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsbezierpath/clip(_:)","navigatorTitle":[{"kind":"identifier","text":"clipRect:"}],"title":"clip(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)","type":"topic","abstract":[{"text":"Intersects the specified rectangle with the clipping path of the current graphics context and makes the resulting shape the current clipping path.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"setClip","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClip"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/saveGraphicsState()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSGraphicsContext/restoreGraphicsState()-swift.method"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/addClip()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/clip(_:)"],"generated":true,"title":"Specifying a Clipping Path","anchor":"Specifying-a-Clipping-Path"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setClip","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1setClip()/title","value":"setClip","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1setClip()/fragments","value":[{"text":"- ","kind":"text"},{"text":"setClip","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"text":"NSBezierPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/title","value":"restoreGraphicsState","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1restoreGraphicsState()-swift.method/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restoreGraphicsState"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1addClip()/title","value":"addClip","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1addClip()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addClip"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/title","value":"saveGraphicsState","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGraphicsContext~1saveGraphicsState()-swift.method/fragments","value":[{"text":"- ","kind":"text"},{"text":"saveGraphicsState","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1clip(_:)/title","value":"clipRect:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1clip(_:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clipRect:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}