{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strokeLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"point1","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"point2","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"point1","content":[{"inlineContent":[{"type":"text","text":"The starting point of the line."}],"type":"paragraph"}]},{"name":"point2","content":[{"inlineContent":[{"type":"text","text":"The ending point of the line."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"This method strokes the specified path immediately.","type":"text"}]}],"kind":"content"}],"metadata":{"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeLine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint","text":"NSPoint"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"strokeLineFromPoint:toPoint:"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"modules":[{"name":"AppKit"}],"title":"strokeLine(from:to:)","externalID":"c:objc(cs)NSBezierPath(cm)strokeLineFromPoint:toPoint:"},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)"],"title":"Drawing a Path","anchor":"Drawing-a-Path","generated":true}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Strokes a line between two points using the current stroke color and the default drawing attributes."}],"variants":[{"paths":["/documentation/appkit/nsbezierpath/strokeline(from:to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsbezierpath/strokeline(from:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()":{"abstract":[{"type":"text","text":"Draws a line along the path using the current stroke color and drawing attributes."}],"navigatorTitle":[{"text":"stroke","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()","url":"/documentation/appkit/nsbezierpath/stroke()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stroke","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"stroke()"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.externally.resolved.symbol/c:@T@NSPoint":{"abstract":[{"text":"A point in a Cartesian coordinate system.","type":"text"}],"url":"/documentation/foundation/nspoint","kind":"symbol","role":"symbol","title":"NSPoint","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSPoint","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()","abstract":[{"text":"Paints the region enclosed by the path.","type":"text"}],"navigatorTitle":[{"text":"fill","kind":"identifier"}],"url":"/documentation/appkit/nsbezierpath/fill()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"fill()"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)":{"kind":"symbol","url":"/documentation/appkit/nsbezierpath/drawpackedglyphs(_:at:)","role":"symbol","navigatorTitle":[{"text":"drawPackedGlyphs:atPoint:","kind":"identifier"}],"abstract":[{"text":"Draws a set of packed glyphs at the specified point in the current coordinate system.","type":"text"}],"title":"drawPackedGlyphs(_:at:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawPackedGlyphs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fillRect:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsbezierpath/fill(_:)","abstract":[{"text":"Fills the specified rectangular path with the current fill color.","type":"text"}],"title":"fill(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)":{"abstract":[{"text":"Strokes a line between two points using the current stroke color and the default drawing attributes.","type":"text"}],"url":"/documentation/appkit/nsbezierpath/strokeline(from:to:)","kind":"symbol","role":"symbol","title":"strokeLine(from:to:)","navigatorTitle":[{"text":"strokeLineFromPoint:toPoint:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/strokeLine(from:to:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strokeLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)":{"kind":"symbol","title":"line(to:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"line"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsbezierpath/line(to:)","navigatorTitle":[{"text":"lineToPoint:","kind":"identifier"}],"abstract":[{"type":"text","text":"Appends a straight line to the path."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)":{"abstract":[{"type":"text","text":"Strokes the path of the specified rectangle using the current stroke color and the default drawing attributes."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stroke"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"},{"kind":"text","text":")"}],"title":"stroke(_:)","url":"/documentation/appkit/nsbezierpath/stroke(_:)","navigatorTitle":[{"kind":"identifier","text":"strokeRect:"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)":{"title":"move(to:)","url":"/documentation/appkit/nsbezierpath/move(to:)","navigatorTitle":[{"text":"moveToPoint:","kind":"identifier"}],"abstract":[{"text":"Moves the path’s current point to the specified location.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"move","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Method"},{"op":"replace","path":"/metadata/title","value":"strokeLineFromPoint:toPoint:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"strokeLineFromPoint:toPoint:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/move(to:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/line(to:)"],"anchor":"Related-Documentation","title":"Related Documentation"},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill()","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/fill(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/stroke(_:)","doc://com.apple.appkit/documentation/AppKit/NSBezierPath/drawPackedGlyphs(_:at:)"],"anchor":"Drawing-a-Path","title":"Drawing a Path"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"strokeLineFromPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"text":") ","kind":"text"},{"text":"point1","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSPoint"},{"text":") ","kind":"text"},{"text":"point2","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The starting point of the line."}],"type":"paragraph"}],"name":"point1"},{"content":[{"inlineContent":[{"text":"The ending point of the line.","type":"text"}],"type":"paragraph"}],"name":"point2"}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke()/title","value":"stroke"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke()/fragments","value":[{"text":"- ","kind":"text"},{"text":"stroke","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"kind":"identifier","text":"NSBezierPath"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"kind":"identifier","text":"NSBezierPath"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill()/title","value":"fill"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fill"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1drawPackedGlyphs(_:at:)/title","value":"drawPackedGlyphs:atPoint:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1drawPackedGlyphs(_:at:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"drawPackedGlyphs:atPoint:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill(_:)/title","value":"fillRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1fill(_:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fillRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1strokeLine(from:to:)/title","value":"strokeLineFromPoint:toPoint:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1strokeLine(from:to:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"strokeLineFromPoint:toPoint:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1line(to:)/title","value":"lineToPoint:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1line(to:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"lineToPoint:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke(_:)/title","value":"strokeRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1stroke(_:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"strokeRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/title","value":"moveToPoint:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1move(to:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToPoint:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}