{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsbezierpath/transform(using:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsbezierpath/transform(using:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"transform","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AffineTransform","identifier":"doc://com.externally.resolved.symbol/s:10Foundation15AffineTransformV","preciseIdentifier":"s:10Foundation15AffineTransformV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The transform to apply to the path.","type":"text"}],"type":"paragraph"}],"name":"transform"}],"kind":"parameters"},{"content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This method applies the transform to the path’s points immediately. The following code translates a line from 0,0 to 100,100 to a line from 10,10 to 110,110."}],"type":"paragraph"},{"code":["NSBezierPath *bezierPath = [NSBezierPath bezierPath];","NSAffineTransform *transform = [NSAffineTransform transform];"," ","[bezierPath moveToPoint: NSMakePoint(0.0, 0.0)];","[bezierPath lineToPoint: NSMakePoint(100.0, 100.0)];"," ","[transform translateXBy: 10.0 yBy: 10.0];","[bezierPath transformUsingAffineTransform: transform];"],"syntax":"objc","type":"codeListing"}],"kind":"content"}],"sections":[],"metadata":{"title":"transform(using:)","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSBezierPath(im)transformUsingAffineTransform:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation15AffineTransformV","text":"AffineTransform"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"transformUsingAffineTransform:","kind":"identifier"}],"platforms":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/transform(using:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Transforms all points in the path using the specified transform."}],"references":{"doc://com.externally.resolved.symbol/s:10Foundation15AffineTransformV":{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation15AffineTransformV","url":"/documentation/foundation/affinetransform","fragments":[{"text":"struct ","kind":"text"},{"text":"AffineTransform","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AffineTransform","role":"symbol","abstract":[{"text":"A graphics coordinate transformation.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath":{"abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"navigatorTitle":[{"text":"NSBezierPath","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath","url":"/documentation/appkit/nsbezierpath","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSBezierPath","kind":"identifier"}],"role":"symbol","title":"NSBezierPath"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/transform(using:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AffineTransform","preciseIdentifier":"s:10Foundation15AffineTransformV"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsbezierpath/transform(using:)","title":"transform(using:)","navigatorTitle":[{"text":"transformUsingAffineTransform:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSBezierPath/transform(using:)","abstract":[{"text":"Transforms all points in the path using the specified transform.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"transformUsingAffineTransform:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transformUsingAffineTransform:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSBezierPath"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transformUsingAffineTransform:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSAffineTransform","preciseIdentifier":"c:objc(cs)NSAffineTransform","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transform","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The transform to apply to the path.","type":"text"}]}],"name":"transform"}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title","value":"NSBezierPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle","value":[{"text":"NSBezierPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1transform(using:)/title","value":"transformUsingAffineTransform:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1transform(using:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformUsingAffineTransform:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}