{
  "abstract": [
    {
      "text": "The system decides whether playback continues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/automatic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVPlayerAudiovisualBackgroundPlaybackPolicy@AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "automatic"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVPlayerAudiovisualBackgroundPlaybackPolicy.automatic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automatic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy": {
      "abstract": [
        {
          "text": "Policies that describe playback behavior when an app transitions to the background while playing video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerAudiovisualBackgroundPlaybackPolicy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerAudiovisualBackgroundPlaybackPolicy"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerAudiovisualBackgroundPlaybackPolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeraudiovisualbackgroundplaybackpolicy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/automatic": {
      "abstract": [
        {
          "text": "The system decides whether playback continues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerAudiovisualBackgroundPlaybackPolicy.automatic",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeraudiovisualbackgroundplaybackpolicy/automatic"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/continuesIfPossible": {
      "abstract": [
        {
          "text": "The app continues playback, if possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuesIfPossible"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/continuesIfPossible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyContinuesIfPossible"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerAudiovisualBackgroundPlaybackPolicy.continuesIfPossible",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeraudiovisualbackgroundplaybackpolicy/continuesifpossible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/pauses": {
      "abstract": [
        {
          "text": "The app pauses playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauses"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/pauses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyPauses"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerAudiovisualBackgroundPlaybackPolicy.pauses",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeraudiovisualbackgroundplaybackpolicy/pauses"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/continuesIfPossible",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/pauses"
      ],
      "title": "Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/continuesIfPossible",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerAudiovisualBackgroundPlaybackPolicy/pauses"
              ],
              "title": "Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy/title",
          "value": "AVPlayerAudiovisualBackgroundPlaybackPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerAudiovisualBackgroundPlaybackPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerAudiovisualBackgroundPlaybackPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy~1automatic/title",
          "value": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy~1continuesIfPossible/title",
          "value": "AVPlayerAudiovisualBackgroundPlaybackPolicyContinuesIfPossible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy~1continuesIfPossible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyContinuesIfPossible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy~1pauses/title",
          "value": "AVPlayerAudiovisualBackgroundPlaybackPolicyPauses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerAudiovisualBackgroundPlaybackPolicy~1pauses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerAudiovisualBackgroundPlaybackPolicyPauses"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplayeraudiovisualbackgroundplaybackpolicy/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avplayeraudiovisualbackgroundplaybackpolicy/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
