{
  "abstract": [
    {
      "text": "An object that adds sound layers for environmental effects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHASESpatialMixerDefinition(py)spatialPipeline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "spatialPipeline"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
        "text": "PHASESpatialPipeline"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "spatialPipeline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "spatialPipeline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "spatialPipeline"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
              "text": "PHASESpatialPipeline"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework sets the value to the ",
              "type": "text"
            },
            {
              "code": "spatialPipeline",
              "type": "codeVoice"
            },
            {
              "text": " initializer argument. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition": {
      "abstract": [
        {
          "text": "An audio-layering object that produces environmental effects and plays sound with a 3D position and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialMixerDefinition"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialMixerDefinition"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialMixerDefinition",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)": {
      "abstract": [
        {
          "text": "Creates a mixer with the designated spatial pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "spatialPipeline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
          "text": "PHASESpatialPipeline"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/init(spatialPipeline:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSpatialPipeline:"
        }
      ],
      "role": "symbol",
      "title": "init(spatialPipeline:)",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/init(spatialpipeline:)"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline": {
      "abstract": [
        {
          "text": "An object that adds sound layers for environmental effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialPipeline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
          "text": "PHASESpatialPipeline"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition/spatialPipeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spatialPipeline"
        }
      ],
      "role": "symbol",
      "title": "spatialPipeline",
      "type": "topic",
      "url": "/documentation/phase/phasespatialmixerdefinition/spatialpipeline"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline": {
      "abstract": [
        {
          "text": "An object that specifies the volume of optional environmental effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASESpatialPipeline"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASESpatialPipeline"
        }
      ],
      "role": "symbol",
      "title": "PHASESpatialPipeline",
      "type": "topic",
      "url": "/documentation/phase/phasespatialpipeline"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "spatialPipeline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASESpatialMixerDefinition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.phase/documentation/PHASE/PHASESpatialPipeline",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHASESpatialPipeline",
                    "text": "PHASESpatialPipeline"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "spatialPipeline"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1spatialPipeline/title",
          "value": "spatialPipeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1spatialPipeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/title",
          "value": "PHASESpatialPipeline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialPipeline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialPipeline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1init(spatialPipeline:)/title",
          "value": "initWithSpatialPipeline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition~1init(spatialPipeline:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSpatialPipeline:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/title",
          "value": "PHASESpatialMixerDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASESpatialMixerDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASESpatialMixerDefinition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasespatialmixerdefinition/spatialpipeline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasespatialmixerdefinition/spatialpipeline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
