{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboButton/style-swift.property","doc://com.apple.appkit/documentation/AppKit/NSComboButton/title","doc://com.apple.appkit/documentation/AppKit/NSComboButton/image","doc://com.apple.appkit/documentation/AppKit/NSComboButton/imageScaling"],"title":"Configuring the Button Appearance","anchor":"Configuring-the-Button-Appearance","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscombobutton/style-swift.enum"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscombobutton/style-swift.enum"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum"},"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/split","doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/unified"],"title":"Getting the Combo Button Styles","anchor":"Getting-the-Combo-Button-Styles"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true}],"sections":[],"abstract":[{"text":"Constants that indicate how a combo button presents its menu.","type":"text"}],"metadata":{"title":"NSComboButton.Style","modules":[{"name":"AppKit"}],"symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"Style","kind":"identifier"}],"platforms":[{"beta":false,"name":"macOS","unavailable":false,"introducedAt":"13.0","deprecated":false}],"externalID":"c:@E@NSComboButtonStyle","extendedModule":"AppKit","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSComboButton"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/init(rawValue:)":{"role":"symbol","kind":"symbol","url":"/documentation/appkit/nscombobutton/style-swift.enum/init(rawvalue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"title":"init(rawValue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/init(rawValue:)"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/imageScaling":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/imageScaling","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageScaling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSImageScaling","preciseIdentifier":"c:@E@NSImageScaling","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageScaling","kind":"identifier"}],"kind":"symbol","title":"imageScaling","abstract":[{"text":"The scaling behavior to apply to the button’s image.","type":"text"}],"url":"/documentation/appkit/nscombobutton/imagescaling","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/title":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/title","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"kind":"symbol","title":"title","abstract":[{"type":"text","text":"The localized string that the button displays."}],"url":"/documentation/appkit/nscombobutton/title","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/split":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/split","kind":"symbol","url":"/documentation/appkit/nscombobutton/style-swift.enum/split","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"split","kind":"identifier"}],"title":"NSComboButton.Style.split","navigatorTitle":[{"text":"NSComboButtonStyleSplit","kind":"identifier"}],"abstract":[{"text":"A style that separates the button’s title and image from the menu indicator people use to activate the button.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/image":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/image","type":"topic","url":"/documentation/appkit/nscombobutton/image","kind":"symbol","title":"image","abstract":[{"type":"text","text":"The image that the button displays."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSImage","preciseIdentifier":"c:objc(cs)NSImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"image","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/unified":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/unified","url":"/documentation/appkit/nscombobutton/style-swift.enum/unified","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSComboButtonStyleUnified"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unified"}],"kind":"symbol","title":"NSComboButton.Style.unified","type":"topic","abstract":[{"text":"A style that unifies the button’s title and image with the menu indicator.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/style-swift.property":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/style-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSComboButton","preciseIdentifier":"c:objc(cs)NSComboButton","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSComboButtonStyle","text":"Style","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"style","kind":"identifier"}],"kind":"symbol","title":"style","abstract":[{"text":"The appearance setting that determines how the button presents its menu .","type":"text"}],"url":"/documentation/appkit/nscombobutton/style-swift.property","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSComboButton","kind":"identifier"}],"title":"NSComboButton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton","abstract":[{"text":"A button with a pull-down menu and a default action.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nscombobutton","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSComboButton","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"kind":"symbol","title":"NSComboButton.Style","abstract":[{"type":"text","text":"Constants that indicate how a combo button presents its menu."}],"url":"/documentation/appkit/nscombobutton/style-swift.enum","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration"},{"path":"/metadata/title","op":"replace","value":"NSComboButtonStyle"},{"path":"/metadata/symbolKind","op":"replace","value":"enum"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"NSComboButtonStyle","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"text":"NSComboButtonStyle","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"path":"/topicSections","op":"replace","value":[{"title":"Getting the Combo Button Styles","anchor":"Getting-the-Combo-Button-Styles","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/split","doc://com.apple.appkit/documentation/AppKit/NSComboButton/Style-swift.enum/unified"]}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Configuring-the-Button-Appearance","generated":true,"title":"Configuring the Button Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSComboButton/style-swift.property","doc://com.apple.appkit/documentation/AppKit/NSComboButton/title","doc://com.apple.appkit/documentation/AppKit/NSComboButton/image","doc://com.apple.appkit/documentation/AppKit/NSComboButton/imageScaling"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSComboButtonStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1imageScaling/title","value":"imageScaling"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1imageScaling/fragments","value":[{"kind":"identifier","text":"imageScaling"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1title/title","value":"title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1title/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1split/title","value":"NSComboButtonStyleSplit"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1split/fragments","value":[{"kind":"identifier","text":"NSComboButtonStyleSplit"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1image/title","value":"image"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1image/fragments","value":[{"text":"image","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1unified/title","value":"NSComboButtonStyleUnified"},{"op":"replace","value":[{"text":"NSComboButtonStyleUnified","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum~1unified/fragments"},{"op":"replace","value":"style","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1style-swift.property/title"},{"op":"replace","value":[{"kind":"identifier","text":"style"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1style-swift.property/fragments"},{"op":"replace","value":"NSComboButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSComboButton"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton/fragments"},{"op":"replace","value":[{"text":"NSComboButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton/navigatorTitle"},{"op":"replace","value":"NSComboButtonStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSComboButtonStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum/fragments"},{"op":"replace","value":[{"text":"NSComboButtonStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton~1Style-swift.enum/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}