{
  "abstract": [
    {
      "text": "A query that matches tab group elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/tabGroups"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCUIElementTypeQueryProvider(py)tabGroups",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tabGroups"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
        "text": "XCUIElementQuery"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tabGroups"
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "tabGroups"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tabGroups"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
              "text": "XCUIElementQuery"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery": {
      "abstract": [
        {
          "text": "An object that defines the search criteria a test uses to identify UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementQuery"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementQuery",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementquery"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider": {
      "abstract": [
        {
          "text": "A type that provides ready-made queries for locating descendant UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementTypeQueryProvider"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementTypeQueryProvider",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/activityIndicators": {
      "abstract": [
        {
          "text": "A query that matches activity indicator view elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityIndicators"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/activityIndicators",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityIndicators"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "activityIndicators",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/activityindicators"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/alerts": {
      "abstract": [
        {
          "text": "A query that matches alert view elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alerts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/alerts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alerts"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "alerts",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/alerts"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/browsers": {
      "abstract": [
        {
          "text": "A query that matches browser elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "browsers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/browsers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "browsers"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "browsers",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/browsers"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/buttons": {
      "abstract": [
        {
          "text": "A query that matches button control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/buttons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttons"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "buttons",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/buttons"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells": {
      "abstract": [
        {
          "text": "A query that matches cell elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cells"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cells"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cells",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/cells"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/checkBoxes": {
      "abstract": [
        {
          "text": "A query that matches checkbox control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/checkBoxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "checkBoxes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "checkBoxes",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/checkboxes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/collectionViews": {
      "abstract": [
        {
          "text": "A query that matches collection view elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionViews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/collectionViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionViews"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "collectionViews",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/collectionviews"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/colorWells": {
      "abstract": [
        {
          "text": "A query that matches color well elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorWells"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/colorWells",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWells"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorWells",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/colorwells"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/comboBoxes": {
      "abstract": [
        {
          "text": "A query that matches combo box control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comboBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/comboBoxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comboBoxes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "comboBoxes",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/comboboxes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/datePickers": {
      "abstract": [
        {
          "text": "A query that matches date picker control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datePickers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/datePickers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "datePickers"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "datePickers",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/datepickers"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/decrementArrows": {
      "abstract": [
        {
          "text": "A query that matches decrement arrow control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementArrows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/decrementArrows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decrementArrows"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "decrementArrows",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/decrementarrows"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dialogs": {
      "abstract": [
        {
          "text": "A query that matches dialog view elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialogs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dialogs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dialogs"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "dialogs",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/dialogs"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosedChildRows": {
      "abstract": [
        {
          "text": "A query that matches disclosed child row elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disclosedChildRows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosedChildRows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disclosedChildRows"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "disclosedChildRows",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/disclosedchildrows"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosureTriangles": {
      "abstract": [
        {
          "text": "A query that matches disclosure triangle control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disclosureTriangles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosureTriangles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disclosureTriangles"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "disclosureTriangles",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/disclosuretriangles"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dockItems": {
      "abstract": [
        {
          "text": "A query that matches dock item control elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dockItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dockItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dockItems"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "dockItems",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/dockitems"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/tabGroups": {
      "abstract": [
        {
          "text": "A query that matches tab group elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
          "text": "XCUIElementQuery"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/tabGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabGroups"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "tabGroups",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementtypequeryprovider/tabgroups"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Querying-Descendant-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/activityIndicators",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/alerts",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/browsers",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/buttons",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/checkBoxes",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/collectionViews",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/colorWells",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/comboBoxes",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/datePickers",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/decrementArrows",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dialogs",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosureTriangles",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosedChildRows",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dockItems"
      ],
      "title": "Querying Descendant Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tabGroups"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Querying-Descendant-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/activityIndicators",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/alerts",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/browsers",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/buttons",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/cells",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/checkBoxes",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/collectionViews",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/colorWells",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/comboBoxes",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/datePickers",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/decrementArrows",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dialogs",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosureTriangles",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/disclosedChildRows",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementTypeQueryProvider/dockItems"
              ],
              "title": "Querying Descendant Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementQuery",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCUIElementQuery",
                    "text": "XCUIElementQuery"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "tabGroups"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1alerts/title",
          "value": "alerts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1alerts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alerts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1cells/title",
          "value": "cells"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1cells/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementQuery/title",
          "value": "XCUIElementQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1dialogs/title",
          "value": "dialogs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1dialogs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dialogs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1disclosedChildRows/title",
          "value": "disclosedChildRows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1disclosedChildRows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disclosedChildRows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1browsers/title",
          "value": "browsers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1browsers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "browsers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1tabGroups/title",
          "value": "tabGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1tabGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1buttons/title",
          "value": "buttons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1buttons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1datePickers/title",
          "value": "datePickers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1datePickers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "datePickers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1dockItems/title",
          "value": "dockItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1dockItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dockItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1colorWells/title",
          "value": "colorWells"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1colorWells/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorWells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1comboBoxes/title",
          "value": "comboBoxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1comboBoxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "comboBoxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1activityIndicators/title",
          "value": "activityIndicators"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1activityIndicators/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityIndicators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/title",
          "value": "XCUIElementTypeQueryProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementTypeQueryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1checkBoxes/title",
          "value": "checkBoxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1checkBoxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "checkBoxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1collectionViews/title",
          "value": "collectionViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1collectionViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collectionViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1decrementArrows/title",
          "value": "decrementArrows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1decrementArrows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decrementArrows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1disclosureTriangles/title",
          "value": "disclosureTriangles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementTypeQueryProvider~1disclosureTriangles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disclosureTriangles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuielementtypequeryprovider/tabgroups"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuielementtypequeryprovider/tabgroups"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
