{
  "abstract": [
    {
      "text": "Information about the media format and presentation options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/mediaOptions-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVTopShelfCarouselItem(py)mediaOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mediaOptions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
        "text": "TVTopShelfCarouselItem"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
        "text": "MediaOptions"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mediaOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mediaOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mediaOptions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
              "text": "TVTopShelfCarouselItem"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
              "text": "MediaOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify all of the options that apply to the underlying content. The system adds standard icons for the options you support. For example, if you specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolution4K",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " option, the system adds an icon to the detail view indicating that playback in 4K resolution is possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem": {
      "abstract": [
        {
          "text": "An item containing images, video, and other information that you want to display using a carousel-based interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItem"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItem"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfCarouselItem",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants indicating the item’s audio and video capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MediaOptions"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfCarouselItem.MediaOptions",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolution4K": {
      "abstract": [
        {
          "text": "Ultra-high-definition 4K video resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoResolution4K"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct/videoResolution4K",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfCarouselItemVideoResolution4K"
        }
      ],
      "role": "symbol",
      "title": "videoResolution4K",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.struct/videoresolution4k"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/mediaOptions-swift.property": {
      "abstract": [
        {
          "text": "Information about the media format and presentation options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVTopShelfCarouselItem",
          "text": "TVTopShelfCarouselItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
          "text": "MediaOptions"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/mediaOptions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaOptions"
        }
      ],
      "role": "symbol",
      "title": "mediaOptions",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.property"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-Media-Badges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct"
      ],
      "title": "Adding Media Badges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mediaOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices",
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-Media-Badges",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct"
              ],
              "title": "Adding Media Badges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfCarouselItem/MediaOptions-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@TVTopShelfCarouselItemMediaOptions",
                    "text": "TVTopShelfCarouselItemMediaOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mediaOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem/title",
          "value": "TVTopShelfCarouselItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct/title",
          "value": "TVTopShelfCarouselItemMediaOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemMediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemMediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1mediaOptions-swift.property/title",
          "value": "mediaOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1mediaOptions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoResolution4K/title",
          "value": "TVTopShelfCarouselItemVideoResolution4K"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfCarouselItem~1MediaOptions-swift.struct~1videoResolution4K/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfCarouselItemVideoResolution4K"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvtopshelfcarouselitem/mediaoptions-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
