{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/points"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICScannerMeasurementUnit@ICScannerMeasurementUnitPoints",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "points"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICScannerMeasurementUnitPoints"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICScannerMeasurementUnit.points"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "points"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit": {
      "abstract": [
        {
          "text": "The unit of measurement used by the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnit"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/centimeters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centimeters"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/centimeters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnitCentimeters"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit.centimeters",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit/centimeters"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/inches": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inches"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/inches",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnitInches"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit.inches",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit/inches"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/picas": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "picas"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/picas",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnitPicas"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit.picas",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit/picas"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/pixels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixels"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/pixels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnitPixels"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit.pixels",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit/pixels"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/points": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "points"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnitPoints"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit.points",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit/points"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/twips": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twips"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/twips",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerMeasurementUnitTwips"
        }
      ],
      "role": "symbol",
      "title": "ICScannerMeasurementUnit.twips",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannermeasurementunit/twips"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/centimeters",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/inches",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/picas",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/pixels",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/twips"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICScannerMeasurementUnitPoints"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/centimeters",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/inches",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/picas",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/pixels",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerMeasurementUnit/twips"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICScannerMeasurementUnitPoints"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1pixels/title",
          "value": "ICScannerMeasurementUnitPixels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1pixels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitPixels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1points/title",
          "value": "ICScannerMeasurementUnitPoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1centimeters/title",
          "value": "ICScannerMeasurementUnitCentimeters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1centimeters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitCentimeters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1twips/title",
          "value": "ICScannerMeasurementUnitTwips"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1twips/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitTwips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit/title",
          "value": "ICScannerMeasurementUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1inches/title",
          "value": "ICScannerMeasurementUnitInches"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1inches/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitInches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1picas/title",
          "value": "ICScannerMeasurementUnitPicas"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerMeasurementUnit~1picas/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerMeasurementUnitPicas"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannermeasurementunit/points"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannermeasurementunit/points"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
