{
  "abstract": [
    {
      "text": "The grayscale color-space model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSColorSpaceModel@NSColorSpaceModelGray",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gray"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSColorSpaceModelGray"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSColorSpace.Model.gray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gray"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace": {
      "abstract": [
        {
          "text": "An object that represents a custom color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model": {
      "abstract": [
        {
          "text": "Constants that describe the abstract model on which color space objects are based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk": {
      "abstract": [
        {
          "text": "The CMYK (cyan-magenta-yellow-black) color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmyk"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelCMYK"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.cmyk",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/cmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN": {
      "abstract": [
        {
          "text": "The DeviceN color-space model from Adobe Systems, Inc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceN"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelDeviceN"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.deviceN",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/devicen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray": {
      "abstract": [
        {
          "text": "The grayscale color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelGray"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed": {
      "abstract": [
        {
          "text": "An indexed color space, which identifies discrete colors in a color list by index number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelIndexed"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.indexed",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/indexed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab": {
      "abstract": [
        {
          "text": "The L*a*b* device-independent color-space model, which represents colors relative to a reference white point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelLAB"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.lab",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/lab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned": {
      "abstract": [
        {
          "text": "A pattern color space, which is a repeated image that creates a tiled pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patterned"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelPatterned"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.patterned",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/patterned"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb": {
      "abstract": [
        {
          "text": "The RGB (red-green-blue) color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgb"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelRGB"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.rgb",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/rgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown": {
      "abstract": [
        {
          "text": "An unknown color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-Spaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned"
      ],
      "title": "Color Spaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSColorSpaceModelGray"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-Spaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned"
              ],
              "title": "Color Spaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSColorSpaceModelGray"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1unknown/title",
          "value": "NSColorSpaceModelUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1rgb/title",
          "value": "NSColorSpaceModelRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1rgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1patterned/title",
          "value": "NSColorSpaceModelPatterned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1patterned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelPatterned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1indexed/title",
          "value": "NSColorSpaceModelIndexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelIndexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1lab/title",
          "value": "NSColorSpaceModelLAB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1lab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelLAB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1gray/title",
          "value": "NSColorSpaceModelGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/title",
          "value": "NSColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1cmyk/title",
          "value": "NSColorSpaceModelCMYK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1cmyk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelCMYK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1deviceN/title",
          "value": "NSColorSpaceModelDeviceN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1deviceN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelDeviceN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/title",
          "value": "NSColorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorspace/model/gray"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorspace/model/gray"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
