{
  "abstract": [
    {
      "text": "An option to animate the replacement of text in your view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/interactive"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWritingToolsCoordinatorTextReplacementReason@NSWritingToolsCoordinatorTextReplacementReasonInteractive",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "interactive"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSWritingToolsCoordinator.TextReplacementReason.interactive"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "interactive"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When Writing Tools requests an interactive change in your delegate’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "NSWritingToolsCoordinator/writingToolsCoordinator(_:replaceRange:inContext:proposedText:reason:animationParameters:completion:)",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method, it passes a valid set of animation parameters to that method.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Update your view’s text storage and use the provided ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "type to create any view-specific animations you need to support the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "animated replacement of the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator": {
      "abstract": [
        {
          "text": "An object that manages interactions between Writing Tools and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your custom text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters": {
      "abstract": [
        {
          "text": "An object you use to configure additional tasks or animations to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "run alongside the Writing Tools animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationParameters"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationParameters"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.AnimationParameters",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/animationparameters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason": {
      "abstract": [
        {
          "text": "Options that indicate whether Writing Tools is animating changes to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your view’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextReplacementReason"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextReplacementReason"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextReplacementReason",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textreplacementreason"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/interactive": {
      "abstract": [
        {
          "text": "An option to animate the replacement of text in your view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactive"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/interactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextReplacementReason.interactive",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textreplacementreason/interactive"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/noninteractive": {
      "abstract": [
        {
          "text": "An option to replace the text in your view without animating the change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noninteractive"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/noninteractive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextReplacementReasonNoninteractive"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextReplacementReason.noninteractive",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textreplacementreason/noninteractive"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/noninteractive"
      ],
      "title": "Getting the reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-reasons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextReplacementReason/noninteractive"
              ],
              "title": "Getting the reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason~1noninteractive/title",
          "value": "NSWritingToolsCoordinatorTextReplacementReasonNoninteractive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason~1noninteractive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextReplacementReasonNoninteractive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1AnimationParameters/title",
          "value": "NSWritingToolsCoordinatorAnimationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1AnimationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorAnimationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1AnimationParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorAnimationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/title",
          "value": "NSWritingToolsCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason/title",
          "value": "NSWritingToolsCoordinatorTextReplacementReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextReplacementReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextReplacementReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason~1interactive/title",
          "value": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextReplacementReason~1interactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextReplacementReasonInteractive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswritingtoolscoordinator/textreplacementreason/interactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswritingtoolscoordinator/textreplacementreason/interactive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
