{
  "abstract": [
    {
      "text": "A sample that doesn’t have an assigned classification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/notSet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKElectrocardiogramClassification@HKElectrocardiogramClassificationNotSet",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notSet"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKElectrocardiogramClassificationNotSet"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKElectrocardiogram.Classification.notSet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notSet"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram": {
      "abstract": [
        {
          "text": "A sample for electrocardiogram data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKElectrocardiogram"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogram"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum": {
      "abstract": [
        {
          "text": "Classifications returned by Apple Watch’s ECG algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/atrialFibrillation": {
      "abstract": [
        {
          "text": "The sample exhibits signs of atrial fibrillation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atrialFibrillation"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/atrialFibrillation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationAtrialFibrillation"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.atrialFibrillation",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/atrialfibrillation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveHighHeartRate": {
      "abstract": [
        {
          "text": "An unclassifiable sample caused by a rapid heart rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inconclusiveHighHeartRate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveHighHeartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationInconclusiveHighHeartRate"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.inconclusiveHighHeartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/inconclusivehighheartrate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveLowHeartRate": {
      "abstract": [
        {
          "text": "An unclassifiable sample caused by a heart rate below 50 bpm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inconclusiveLowHeartRate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveLowHeartRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationInconclusiveLowHeartRate"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.inconclusiveLowHeartRate",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/inconclusivelowheartrate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveOther": {
      "abstract": [
        {
          "text": "An unclassifiable sample caused by an unknown issue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inconclusiveOther"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveOther",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationInconclusiveOther"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.inconclusiveOther",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/inconclusiveother"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusivePoorReading": {
      "abstract": [
        {
          "text": "An unclassifiable sample caused by an unclear signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inconclusivePoorReading"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusivePoorReading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationInconclusivePoorReading"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.inconclusivePoorReading",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/inconclusivepoorreading"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/notSet": {
      "abstract": [
        {
          "text": "A sample that doesn’t have an assigned classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSet"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/notSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationNotSet"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.notSet",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/notset"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/sinusRhythm": {
      "abstract": [
        {
          "text": "The sample exhibits no signs of atrial fibrillation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sinusRhythm"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/sinusRhythm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationSinusRhythm"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.sinusRhythm",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/sinusrhythm"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/unrecognized": {
      "abstract": [
        {
          "text": "A sample classification that this version of HealthKit doesn’t recognize.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecognized"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/unrecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKElectrocardiogramClassificationUnrecognized"
        }
      ],
      "role": "symbol",
      "title": "HKElectrocardiogram.Classification.unrecognized",
      "type": "topic",
      "url": "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/unrecognized"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/sinusRhythm",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/atrialFibrillation",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveHighHeartRate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveLowHeartRate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusivePoorReading",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveOther",
        "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/unrecognized"
      ],
      "title": "Classifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKElectrocardiogramClassificationNotSet"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/sinusRhythm",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/atrialFibrillation",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveHighHeartRate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveLowHeartRate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusivePoorReading",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/inconclusiveOther",
                "doc://com.apple.healthkit/documentation/HealthKit/HKElectrocardiogram/Classification-swift.enum/unrecognized"
              ],
              "title": "Classifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKElectrocardiogramClassificationNotSet"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1unrecognized/title",
          "value": "HKElectrocardiogramClassificationUnrecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1unrecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationUnrecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusiveOther/title",
          "value": "HKElectrocardiogramClassificationInconclusiveOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusiveOther/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationInconclusiveOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusiveLowHeartRate/title",
          "value": "HKElectrocardiogramClassificationInconclusiveLowHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusiveLowHeartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationInconclusiveLowHeartRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram/title",
          "value": "HKElectrocardiogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum/title",
          "value": "HKElectrocardiogramClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1sinusRhythm/title",
          "value": "HKElectrocardiogramClassificationSinusRhythm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1sinusRhythm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationSinusRhythm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusivePoorReading/title",
          "value": "HKElectrocardiogramClassificationInconclusivePoorReading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusivePoorReading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationInconclusivePoorReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1notSet/title",
          "value": "HKElectrocardiogramClassificationNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1notSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1atrialFibrillation/title",
          "value": "HKElectrocardiogramClassificationAtrialFibrillation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1atrialFibrillation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationAtrialFibrillation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusiveHighHeartRate/title",
          "value": "HKElectrocardiogramClassificationInconclusiveHighHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKElectrocardiogram~1Classification-swift.enum~1inconclusiveHighHeartRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKElectrocardiogramClassificationInconclusiveHighHeartRate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/notset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkelectrocardiogram/classification-swift.enum/notset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
