{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"UIKit","role":"symbol","roleHeading":"Instance Method","externalID":"s:5UIKit37UIIndirectScribbleInteractionDelegatePAAE08indirectcD0_25didFinishWritingInElementySo13UIInteraction_p_0K10IdentifierQztF","symbolKind":"method","title":"indirectScribbleInteraction(_:didFinishWritingInElement:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indirectScribbleInteraction","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"UIInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIInteraction"},{"text":", ","kind":"text"},{"text":"didFinishWritingInElement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ElementIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:5UIKit37UIIndirectScribbleInteractionDelegateP17ElementIdentifierQa"},{"text":")","kind":"text"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}]},"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/indirectScribbleInteraction(_:didFinishWritingInElement:)-9q7os","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiindirectscribbleinteractiondelegate-hdh/indirectscribbleinteraction(_:didfinishwritinginelement:)-9q7os"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indirectScribbleInteraction"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"UIInteraction","preciseIdentifier":"c:objc(pl)UIInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWritingInElement","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"elementIdentifier","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ElementIdentifier","preciseIdentifier":"s:5UIKit37UIIndirectScribbleInteractionDelegateP17ElementIdentifierQa","identifier":"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/ElementIdentifier","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/indirectScribbleInteraction(_:didFinishWritingInElement:)-9q7os":{"title":"indirectScribbleInteraction(_:didFinishWritingInElement:)","url":"/documentation/uikit/uiindirectscribbleinteractiondelegate-hdh/indirectscribbleinteraction(_:didfinishwritinginelement:)-9q7os","abstract":[],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/indirectScribbleInteraction(_:didFinishWritingInElement:)-9q7os","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"indirectScribbleInteraction","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"UIInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIInteraction"},{"text":", ","kind":"text"},{"text":"didFinishWritingInElement","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ElementIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:5UIKit37UIIndirectScribbleInteractionDelegateP17ElementIdentifierQa"},{"text":")","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIInteraction":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIInteraction"}],"role":"symbol","title":"UIInteraction","url":"/documentation/uikit/uiinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction","navigatorTitle":[{"kind":"identifier","text":"UIInteraction"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The protocol that an interaction implements to access the view that owns it."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh","kind":"symbol","url":"/documentation/uikit/uiindirectscribbleinteractiondelegate-hdh","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIIndirectScribbleInteractionDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIIndirectScribbleInteractionDelegate"}],"abstract":[{"text":"Methods that customize behavior on views that aren’t formally text input views.","type":"text"}],"title":"UIIndirectScribbleInteractionDelegate"},"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/ElementIdentifier":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/ElementIdentifier","kind":"symbol","url":"/documentation/uikit/uiindirectscribbleinteractiondelegate-hdh/elementidentifier","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ElementIdentifier","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SH","kind":"typeIdentifier","text":"Hashable"},{"kind":"text","text":" = "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"required":true,"type":"topic","abstract":[{"text":"A unique identifier for a control that isn’t a text field in a Scribble interaction.","type":"text"}],"title":"ElementIdentifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title","value":"UIInteraction"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments","value":[{"text":"UIInteraction","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle","value":[{"kind":"identifier","text":"UIInteraction"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}