{
  "abstract": [
    {
      "text": "Add additional accessibility information to the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Assignables/documentation/Assignables",
        "doc://com.apple.Assignables/documentation/Assignables/AssignedWorkDocumentView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Assignables/documentation/Assignables/AssignedWorkDocumentView/accessibilityCustomContent(_:_:importance:)-7mspt"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SwiftUI",
    "externalID": "s:7SwiftUI4ViewPAAE26accessibilityCustomContent__10importanceAA08ModifiedF0VyxAA31AccessibilityAttachmentModifierVGAA0ieF3KeyV_AA015LocalizedStringL0VSo08AXCustomF10ImportanceVtF::SYNTHESIZED::s:11Assignables24AssignedWorkDocumentViewV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityCustomContent"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
        "text": "AccessibilityCustomContentKey"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
        "text": "LocalizedStringKey"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "importance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AXCustomContent",
        "text": "AXCustomContent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AXCustomContentImportance",
        "text": "Importance"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
        "text": "ModifiedContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
        "text": "AccessibilityAttachmentModifier"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "Assignables",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityCustomContent(_:_:importance:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityCustomContent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI29AccessibilityCustomContentKeyV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
              "text": "AccessibilityCustomContentKey"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "valueKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI18LocalizedStringKeyV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
              "text": "LocalizedStringKey"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "importance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AXCustomContent",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AXCustomContentImportance",
              "text": "Importance"
            },
            {
              "kind": "text",
              "text": " = .default) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
              "text": "ModifiedContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
              "text": "AccessibilityAttachmentModifier"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Key used to specify the identifier and label of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "of the additional accessibility information entry.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Text value for the additional accessibility",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "information. For example: “landscape.” A value of ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " will remove",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "any entry of additional information added earlier for any ",
                  "type": "text"
                },
                {
                  "code": "key",
                  "type": "codeVoice"
                },
                {
                  "text": " with",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the same identifier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "valueKey"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Importance of the accessibility information.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "High-importance information gets read out immediately, while",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "default-importance information must be explicitly asked for by the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "importance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to add information you want accessibility users to be",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "able to access about this element, beyond the basics of label, value,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and hint. For example, ",
              "type": "text"
            },
            {
              "code": "accessibilityCustomContent",
              "type": "codeVoice"
            },
            {
              "text": " can be used to add",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information about the orientation of a photograph, or the number of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "people found in the picture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Repeated calls of ",
                  "type": "text"
                },
                {
                  "code": "accessibilityCustomContent",
                  "type": "codeVoice"
                },
                {
                  "text": " with ",
                  "type": "text"
                },
                {
                  "code": "key",
                  "type": "codeVoice"
                },
                {
                  "text": "s",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "having different identifiers will create new entries of",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "additional information.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Calling ",
                  "type": "text"
                },
                {
                  "code": "accessibilityAdditionalContent",
                  "type": "codeVoice"
                },
                {
                  "text": " repeatedly with ",
                  "type": "text"
                },
                {
                  "code": "key",
                  "type": "codeVoice"
                },
                {
                  "text": "s",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "having matching identifiers will replace the previous entry.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Assignables/documentation/Assignables": {
      "abstract": [
        {
          "text": "A framework that contain wrappers to a PDF to allow creation",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "of an assessment and student work on that assessment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Assignables/documentation/Assignables",
      "kind": "symbol",
      "role": "collection",
      "title": "Assignables",
      "type": "topic",
      "url": "/documentation/assignables"
    },
    "doc://com.apple.Assignables/documentation/Assignables/AssignedWorkDocumentView": {
      "abstract": [
        {
          "text": "SwiftUI View to display an ",
          "type": "text"
        },
        {
          "code": "AssignedWorkDocument",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssignedWorkDocumentView"
        }
      ],
      "identifier": "doc://com.apple.Assignables/documentation/Assignables/AssignedWorkDocumentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssignedWorkDocumentView"
        }
      ],
      "role": "symbol",
      "title": "AssignedWorkDocumentView",
      "type": "topic",
      "url": "/documentation/assignables/assignedworkdocumentview"
    },
    "doc://com.apple.Assignables/documentation/Assignables/AssignedWorkDocumentView/accessibilityCustomContent(_:_:importance:)-7mspt": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI29AccessibilityCustomContentKeyV",
          "text": "AccessibilityCustomContentKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.Assignables/documentation/Assignables/AssignedWorkDocumentView/accessibilityCustomContent(_:_:importance:)-7mspt",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/assignables/assignedworkdocumentview/accessibilitycustomcontent(_:_:importance:)-7mspt"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance": {
      "abstract": [
        {
          "text": "Objects that control the timing of content output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Importance"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent.Importance",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent/Importance-swift.enum"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent": {
      "abstract": [
        {
          "text": "Objects that define custom content and the timing of its output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContent"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV": {
      "abstract": [
        {
          "text": "A value with a modifier applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Modifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV",
      "kind": "symbol",
      "role": "symbol",
      "title": "ModifiedContent",
      "type": "topic",
      "url": "/documentation/SwiftUI/ModifiedContent"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI18LocalizedStringKeyV": {
      "abstract": [
        {
          "text": "The key used to look up an entry in a strings file or strings dictionary file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalizedStringKey"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI18LocalizedStringKeyV",
      "kind": "symbol",
      "role": "symbol",
      "title": "LocalizedStringKey",
      "type": "topic",
      "url": "/documentation/SwiftUI/LocalizedStringKey"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI29AccessibilityCustomContentKeyV": {
      "abstract": [
        {
          "text": "Key used to specify the identifier and label associated with an entry of additional accessibility information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityCustomContentKey"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI29AccessibilityCustomContentKeyV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AccessibilityCustomContentKey",
      "type": "topic",
      "url": "/documentation/SwiftUI/AccessibilityCustomContentKey"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV": {
      "abstract": [
        {
          "text": "A view modifier that adds accessibility properties to the view",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityAttachmentModifier"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AccessibilityAttachmentModifier",
      "type": "topic",
      "url": "/documentation/SwiftUI/AccessibilityAttachmentModifier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/title",
          "value": "AXCustomContentImportance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContentImportance"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AXCustomContent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assignables/assignedworkdocumentview/accessibilitycustomcontent(_:_:importance:)-7mspt"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
