{
  "abstract": [
    {
      "text": "Creates a query object with provided parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery/init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ODQuery(im)initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "node"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ODNode",
        "text": "ODNode"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "forRecordTypes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "attribute"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "matchType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ODMatchType",
        "text": "ODMatchType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "queryValues"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "returnAttributes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "maximumResults"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "node"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inNode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ODNode",
              "text": "ODNode"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "forRecordTypes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inRecordTypeOrList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "attribute"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inAttribute"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "matchType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inMatchType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ODMatchType",
              "text": "ODMatchType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "queryValues"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inQueryValueOrList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "returnAttributes"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inReturnAttributeOrList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "maximumResults"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inMaximumResults"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The node to query.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inNode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type or types of record to query. Can be an ",
                  "type": "text"
                },
                {
                  "code": "NSString",
                  "type": "codeVoice"
                },
                {
                  "text": " object for a single type or an ",
                  "type": "text"
                },
                {
                  "code": "NSArray",
                  "type": "codeVoice"
                },
                {
                  "text": " object containing ",
                  "type": "text"
                },
                {
                  "code": "NSString",
                  "type": "codeVoice"
                },
                {
                  "text": " objects for multiple types.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inRecordTypeOrList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the attribute to query.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inAttribute"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of query.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inMatchType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value or values to query in the attribute. Can be an ",
                  "type": "text"
                },
                {
                  "code": "NSString",
                  "type": "codeVoice"
                },
                {
                  "text": " object or an ",
                  "type": "text"
                },
                {
                  "code": "NSData",
                  "type": "codeVoice"
                },
                {
                  "text": " object for a single value, or an ",
                  "type": "text"
                },
                {
                  "code": "NSArray",
                  "type": "codeVoice"
                },
                {
                  "text": " containing ",
                  "type": "text"
                },
                {
                  "code": "NSString",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "NSData",
                  "type": "codeVoice"
                },
                {
                  "text": " objects for multiple values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inQueryValueOrList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The attribute or attributes to be returned from the query. Can be an ",
                  "type": "text"
                },
                {
                  "code": "NSString",
                  "type": "codeVoice"
                },
                {
                  "text": " object for a single attribute or an ",
                  "type": "text"
                },
                {
                  "code": "NSArray",
                  "type": "codeVoice"
                },
                {
                  "text": " object containing ",
                  "type": "text"
                },
                {
                  "code": "NSString",
                  "type": "codeVoice"
                },
                {
                  "text": " objects for multiple attributes. Passing ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " is equivalent to passing ",
                  "type": "text"
                },
                {
                  "code": "kODAttributeTypeStandardOnly",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inReturnAttributeOrList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The maximum number of values to return.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inMaximumResults"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The initialized query.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In Swift, this API is imported as an initializer and is marked with the ",
                  "type": "text"
                },
                {
                  "code": "throws",
                  "type": "codeVoice"
                },
                {
                  "text": " keyword to indicate that it throws an error in cases of failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "You call this method in a ",
                  "type": "text"
                },
                {
                  "code": "try",
                  "type": "codeVoice"
                },
                {
                  "text": " expression and handle any errors in the ",
                  "type": "text"
                },
                {
                  "code": "catch",
                  "type": "codeVoice"
                },
                {
                  "text": " clauses of a ",
                  "type": "text"
                },
                {
                  "code": "do",
                  "type": "codeVoice"
                },
                {
                  "text": " statement, as described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "About Imported Cocoa Error Parameters",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Handling Errors in Swift",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeType": {
      "abstract": [
        {
          "text": "An Open Directory attribute type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODAttributeType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODAttributeType"
        }
      ],
      "role": "symbol",
      "title": "ODAttributeType",
      "type": "topic",
      "url": "/documentation/opendirectory/odattributetype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType": {
      "abstract": [
        {
          "text": "An Open Directory match type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODMatchType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODMatchType"
        }
      ],
      "role": "symbol",
      "title": "ODMatchType",
      "type": "topic",
      "url": "/documentation/opendirectory/odmatchtype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODNode",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNode"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNode"
        }
      ],
      "role": "symbol",
      "title": "ODNode",
      "type": "topic",
      "url": "/documentation/opendirectory/odnode"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODQuery",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQuery"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQuery"
        }
      ],
      "role": "symbol",
      "title": "ODQuery",
      "type": "topic",
      "url": "/documentation/opendirectory/odquery"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery/init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)": {
      "abstract": [
        {
          "text": "Creates a query object with provided parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "node"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ODNode",
          "text": "ODNode"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forRecordTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "attribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "matchType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ODMatchType",
          "text": "ODMatchType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "queryValues"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "returnAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "maximumResults"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery/init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
        }
      ],
      "role": "symbol",
      "title": "init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)",
      "type": "topic",
      "url": "/documentation/opendirectory/odquery/init(node:forrecordtypes:attribute:matchtype:queryvalues:returnattributes:maximumresults:)"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery/queryWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:": {
      "abstract": [
        {
          "text": "Returns an autoreleased query object created with provided parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "queryWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery/queryWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
        }
      ],
      "role": "symbol",
      "title": "queryWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:",
      "type": "topic",
      "url": "/documentation/opendirectory/odquery/querywithnode:forrecordtypes:attribute:matchtype:queryvalues:returnattributes:maximumresults:error:"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "https://docs.swift.org/swift-book/": {
      "identifier": "https://docs.swift.org/swift-book/",
      "title": "The Swift Programming Language",
      "titleInlineContent": [
        {
          "text": "The Swift Programming Language",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/"
    },
    "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html": {
      "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
      "title": "Error Handling",
      "titleInlineContent": [
        {
          "text": "Error Handling",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-and-Initializing-a-Query",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery/queryWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
              ],
              "title": "Creating and Initializing a Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithNode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ODNode",
                    "text": "ODNode"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inNode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forRecordTypes:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inRecordTypeOrList"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "attribute:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ODAttributeType",
                    "text": "ODAttributeType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inAttribute"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "matchType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ODMatchType",
                    "text": "ODMatchType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inMatchType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "queryValues:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inQueryValueOrList"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "returnAttributes:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inReturnAttributeOrList"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "maximumResults:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inMaximumResults"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The node to query.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inNode"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type or types of record to query. Can be an ",
                        "type": "text"
                      },
                      {
                        "code": "NSString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object for a single type or an ",
                        "type": "text"
                      },
                      {
                        "code": "NSArray",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object containing ",
                        "type": "text"
                      },
                      {
                        "code": "NSString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " objects for multiple types.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inRecordTypeOrList"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the attribute to query.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inAttribute"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of query.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inMatchType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The value or values to query in the attribute. Can be an ",
                        "type": "text"
                      },
                      {
                        "code": "NSString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object or an ",
                        "type": "text"
                      },
                      {
                        "code": "NSData",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object for a single value, or an ",
                        "type": "text"
                      },
                      {
                        "code": "NSArray",
                        "type": "codeVoice"
                      },
                      {
                        "text": " containing ",
                        "type": "text"
                      },
                      {
                        "code": "NSString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "NSData",
                        "type": "codeVoice"
                      },
                      {
                        "text": " objects for multiple values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inQueryValueOrList"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The attribute or attributes to be returned from the query. Can be an ",
                        "type": "text"
                      },
                      {
                        "code": "NSString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object for a single attribute or an ",
                        "type": "text"
                      },
                      {
                        "code": "NSArray",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object containing ",
                        "type": "text"
                      },
                      {
                        "code": "NSString",
                        "type": "codeVoice"
                      },
                      {
                        "text": " objects for multiple attributes. Passing ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is equivalent to passing ",
                        "type": "text"
                      },
                      {
                        "code": "kODAttributeTypeStandardOnly",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inReturnAttributeOrList"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The maximum number of values to return.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inMaximumResults"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error reference for error details. Can be ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outError"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The initialized query.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/title",
          "value": "ODNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeType/title",
          "value": "ODAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/title",
          "value": "ODQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMatchType/title",
          "value": "ODMatchType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMatchType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMatchType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery~1init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)/title",
          "value": "initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery~1init(node:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithNode:forRecordTypes:attribute:matchType:queryValues:returnAttributes:maximumResults:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/odquery/init(node:forrecordtypes:attribute:matchtype:queryvalues:returnattributes:maximumresults:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/odquery/init(node:forrecordtypes:attribute:matchtype:queryvalues:returnattributes:maximumresults:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
