{
  "abstract": [
    {
      "text": "A thick style divider displays between subviews.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitView",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thick"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSSplitViewDividerStyle@NSSplitViewDividerStyleThick",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "thick"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSplitViewDividerStyleThick"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSSplitView.DividerStyle.thick"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "thick"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This style is the default divider style.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitView": {
      "abstract": [
        {
          "text": "A view that arranges two or more views in a linear stack running horizontally or vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSplitView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitView"
        }
      ],
      "role": "symbol",
      "title": "NSSplitView",
      "type": "topic",
      "url": "/documentation/appkit/nssplitview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the style of the split view’s dividers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DividerStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DividerStyle"
        }
      ],
      "role": "symbol",
      "title": "NSSplitView.DividerStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssplitview/dividerstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/paneSplitter": {
      "abstract": [
        {
          "text": "A thick style divider with a 3D appearance displays between subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paneSplitter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/paneSplitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewDividerStylePaneSplitter"
        }
      ],
      "role": "symbol",
      "title": "NSSplitView.DividerStyle.paneSplitter",
      "type": "topic",
      "url": "/documentation/appkit/nssplitview/dividerstyle-swift.enum/panesplitter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thick": {
      "abstract": [
        {
          "text": "A thick style divider displays between subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thick"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewDividerStyleThick"
        }
      ],
      "role": "symbol",
      "title": "NSSplitView.DividerStyle.thick",
      "type": "topic",
      "url": "/documentation/appkit/nssplitview/dividerstyle-swift.enum/thick"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thin": {
      "abstract": [
        {
          "text": "A thin style divider displays between subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thin"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSplitViewDividerStyleThin"
        }
      ],
      "role": "symbol",
      "title": "NSSplitView.DividerStyle.thin",
      "type": "topic",
      "url": "/documentation/appkit/nssplitview/dividerstyle-swift.enum/thin"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thin",
        "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/paneSplitter"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSplitViewDividerStyleThick"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewDividerStyleThick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/thin",
                "doc://com.apple.appkit/documentation/AppKit/NSSplitView/DividerStyle-swift.enum/paneSplitter"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSSplitViewDividerStyleThick"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum/title",
          "value": "NSSplitViewDividerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewDividerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewDividerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum~1thick/title",
          "value": "NSSplitViewDividerStyleThick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum~1thick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewDividerStyleThick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum~1thin/title",
          "value": "NSSplitViewDividerStyleThin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum~1thin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewDividerStyleThin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView/title",
          "value": "NSSplitView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum~1paneSplitter/title",
          "value": "NSSplitViewDividerStylePaneSplitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSplitView~1DividerStyle-swift.enum~1paneSplitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSplitViewDividerStylePaneSplitter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssplitview/dividerstyle-swift.enum/thick"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssplitview/dividerstyle-swift.enum/thick"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
