{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketDevices"},{"kind":"text","text":": ["},{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice","kind":"typeIdentifier","text":"VZSocketDevice","preciseIdentifier":"c:objc(cs)VZSocketDevice"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"If you included a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration"},{"text":" object in the configuration of your VM, this property contains a corresponding ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice"},{"text":" object. Use that object to configure the ports your VM makes available to the guest operating system.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If you didn’t include a socket device in your configuration, this property contains an empty array."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"The array of socket devices that the VM configures for use ports in the guest VM."}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"socketDevices","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZSocketDevice","text":"VZSocketDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"Virtualization"}],"role":"symbol","externalID":"c:objc(cs)VZVirtualMachine(py)socketDevices","platforms":[{"introducedAt":"11.0","unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"symbolKind":"property","navigatorTitle":[{"text":"socketDevices","kind":"identifier"}],"title":"socketDevices"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/virtualization/vzvirtualmachine/socketdevices"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/virtualization/vzvirtualmachine/socketdevices"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/socketDevices"},"seeAlsoSections":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/consoleDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/memoryBalloonDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/networkDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/directorySharingDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/usbControllers"],"generated":true,"anchor":"Configuring-VM-attributes-at-runtime","title":"Configuring VM attributes at runtime"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VZVirtioSocketDevice"}],"role":"symbol","type":"topic","url":"/documentation/virtualization/vzvirtiosocketdevice","navigatorTitle":[{"kind":"identifier","text":"VZVirtioSocketDevice"}],"title":"VZVirtioSocketDevice","kind":"symbol","abstract":[{"text":"A device that manages port-based connections between the guest system and the host computer.","type":"text"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDevice"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZVirtualMachine"}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine","abstract":[{"type":"text","text":"An object that manages the overall state and configuration of your VM."}],"role":"symbol","title":"VZVirtualMachine","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VZVirtualMachine"}],"url":"/documentation/virtualization/vzvirtualmachine"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/usbControllers":{"type":"topic","title":"usbControllers","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/usbControllers","role":"symbol","abstract":[{"type":"text","text":"The list of runtime USB controller objects."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usbControllers"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)VZUSBController","kind":"typeIdentifier","text":"VZUSBController"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"usbControllers"}],"url":"/documentation/virtualization/vzvirtualmachine/usbcontrollers","kind":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/networkDevices":{"url":"/documentation/virtualization/vzvirtualmachine/networkdevices","kind":"symbol","role":"symbol","title":"networkDevices","navigatorTitle":[{"kind":"identifier","text":"networkDevices"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkDevices","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZNetworkDevice","text":"VZNetworkDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"The list of configured network devices on the VM."}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/networkDevices"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/consoleDevices":{"type":"topic","title":"consoleDevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/consoleDevices","role":"symbol","abstract":[{"type":"text","text":"The list of configured console devices on the VM."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consoleDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"VZConsoleDevice","preciseIdentifier":"c:objc(cs)VZConsoleDevice"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"consoleDevices"}],"url":"/documentation/virtualization/vzvirtualmachine/consoledevices","kind":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/memoryBalloonDevices":{"title":"memoryBalloonDevices","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"memoryBalloonDevices"}],"kind":"symbol","abstract":[{"type":"text","text":"The array of devices that you use to adjust the amount of memory available to the guest system."}],"type":"topic","url":"/documentation/virtualization/vzvirtualmachine/memoryballoondevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/memoryBalloonDevices","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryBalloonDevices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)VZMemoryBalloonDevice","kind":"typeIdentifier","text":"VZMemoryBalloonDevice"},{"kind":"text","text":"]"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"VZVirtioSocketDeviceConfiguration","kind":"identifier"}],"abstract":[{"text":"A configuration object that requests the creation of a socket device to communicate with the guest system.","type":"text"}],"role":"symbol","title":"VZVirtioSocketDeviceConfiguration","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSocketDeviceConfiguration","url":"/documentation/virtualization/vzvirtiosocketdeviceconfiguration"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/socketDevices":{"type":"topic","title":"socketDevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/socketDevices","role":"symbol","abstract":[{"type":"text","text":"The array of socket devices that the VM configures for use ports in the guest VM."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socketDevices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)VZSocketDevice","kind":"typeIdentifier","text":"VZSocketDevice"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"socketDevices"}],"url":"/documentation/virtualization/vzvirtualmachine/socketdevices","kind":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice":{"navigatorTitle":[{"kind":"identifier","text":"VZSocketDevice"}],"type":"topic","title":"VZSocketDevice","abstract":[{"type":"text","text":"The common behavior of socket devices."}],"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZSocketDevice","kind":"symbol","role":"symbol","url":"/documentation/virtualization/vzsocketdevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VZSocketDevice"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/directorySharingDevices":{"type":"topic","title":"directorySharingDevices","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/directorySharingDevices","role":"symbol","abstract":[{"text":"The list of configured directory-sharing devices on the VM.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directorySharingDevices","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)VZDirectorySharingDevice","text":"VZDirectorySharingDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"directorySharingDevices","kind":"identifier"}],"url":"/documentation/virtualization/vzvirtualmachine/directorysharingdevices","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"introducedAt":"11.0","unavailable":false,"deprecated":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"socketDevices","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"socketDevices"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Configuring VM attributes at runtime","generated":true,"anchor":"Configuring-VM-attributes-at-runtime","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/consoleDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/memoryBalloonDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/networkDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/directorySharingDevices","doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/usbControllers"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<VZSocketDevice *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"socketDevices"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/title","value":"VZVirtioSocketDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/fragments","value":[{"text":"VZVirtioSocketDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDevice/navigatorTitle","value":[{"kind":"identifier","text":"VZVirtioSocketDevice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/title","value":"VZVirtualMachine","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/fragments","value":[{"text":"VZVirtualMachine","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/navigatorTitle","value":[{"text":"VZVirtualMachine","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1usbControllers/title","value":"usbControllers","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1usbControllers/fragments","value":[{"text":"usbControllers","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1networkDevices/title","value":"networkDevices","op":"replace"},{"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1networkDevices/fragments","value":[{"kind":"identifier","text":"networkDevices"}],"op":"replace"},{"value":"consoleDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1consoleDevices/title","op":"replace"},{"value":[{"kind":"identifier","text":"consoleDevices"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1consoleDevices/fragments","op":"replace"},{"value":"memoryBalloonDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1memoryBalloonDevices/title","op":"replace"},{"value":[{"text":"memoryBalloonDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1memoryBalloonDevices/fragments","op":"replace"},{"value":"VZVirtioSocketDeviceConfiguration","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtioSocketDeviceConfiguration"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZVirtioSocketDeviceConfiguration"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSocketDeviceConfiguration/navigatorTitle"},{"op":"replace","value":"socketDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1socketDevices/title"},{"op":"replace","value":[{"kind":"identifier","text":"socketDevices"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1socketDevices/fragments"},{"op":"replace","value":"VZSocketDevice","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDevice/title"},{"op":"replace","value":[{"text":"VZSocketDevice","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDevice/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"VZSocketDevice"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZSocketDevice/navigatorTitle"},{"op":"replace","value":"directorySharingDevices","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1directorySharingDevices/title"},{"op":"replace","value":[{"text":"directorySharingDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1directorySharingDevices/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}