{
  "abstract": [
    {
      "text": "The execution states of the VM.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Virtualization",
    "externalID": "c:@E@VZVirtualMachineState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "State"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "State"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VZVirtualMachine.State"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "State"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine": {
      "abstract": [
        {
          "text": "An object that manages the overall state and configuration of your VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachine"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum": {
      "abstract": [
        {
          "text": "The execution states of the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error": {
      "abstract": [
        {
          "text": "The VM encountered an unrecoverable error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateError"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.error",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/error"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused": {
      "abstract": [
        {
          "text": "The framework has paused a started VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStatePaused"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.paused",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/paused"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing": {
      "abstract": [
        {
          "text": "The VM is pausing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pausing"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStatePausing"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.pausing",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/pausing"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring": {
      "abstract": [
        {
          "text": "The VM is restoring from a saved state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoring"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateRestoring"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.restoring",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/restoring"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming": {
      "abstract": [
        {
          "text": "The VM is resuming from a paused state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resuming"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateResuming"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.resuming",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/resuming"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running": {
      "abstract": [
        {
          "text": "The VM is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "running"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateRunning"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.running",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/running"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving": {
      "abstract": [
        {
          "text": "The VM is saving its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saving"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateSaving"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.saving",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/saving"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting": {
      "abstract": [
        {
          "text": "The VM is configuring the hardware preparing to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "starting"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateStarting"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.starting",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/starting"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped": {
      "abstract": [
        {
          "text": "The VM isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateStopped"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.stopped",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopped"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping": {
      "abstract": [
        {
          "text": "The VM is stopping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopping"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtualMachineStateStopping"
        }
      ],
      "role": "symbol",
      "title": "VZVirtualMachine.State.stopping",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.enum/stopping"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canPause": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can pause the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPause"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPause"
        }
      ],
      "role": "symbol",
      "title": "canPause",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canpause"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canRequestStop": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can ask the guest operating system to stop running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canRequestStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canRequestStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canRequestStop"
        }
      ],
      "role": "symbol",
      "title": "canRequestStop",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canrequeststop"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canResume": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can resume the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canResume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canResume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canResume"
        }
      ],
      "role": "symbol",
      "title": "canResume",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canresume"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can start the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStart"
        }
      ],
      "role": "symbol",
      "title": "canStart",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canstart"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStop": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can stop the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStop"
        }
      ],
      "role": "symbol",
      "title": "canStop",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canstop"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/graphicsDevices": {
      "abstract": [
        {
          "text": "The list of configured graphics devices on the virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicsDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZGraphicsDevice",
          "text": "VZGraphicsDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/graphicsDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "graphicsDevices"
        }
      ],
      "role": "symbol",
      "title": "graphicsDevices",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/graphicsdevices"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/state-swift.property": {
      "abstract": [
        {
          "text": "The current execution state of the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZVirtualMachine",
          "text": "VZVirtualMachine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VZVirtualMachineState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/state-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-state-of-the-VM",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/state-swift.property",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/graphicsDevices",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canPause",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canResume",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStop",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canRequestStop"
      ],
      "title": "Getting the state of the VM"
    }
  ],
  "topicSections": [
    {
      "anchor": "States",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving"
      ],
      "title": "States"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZVirtualMachineState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "States",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopped",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/running",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/paused",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/error",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/starting",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/pausing",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/stopping",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/resuming",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/restoring",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/State-swift.enum/saving"
              ],
              "title": "States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-state-of-the-VM",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/state-swift.property",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/graphicsDevices",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canPause",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canResume",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStop",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canRequestStop"
              ],
              "title": "Getting the state of the VM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VZVirtualMachineState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStart/title",
          "value": "canStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/title",
          "value": "VZVirtualMachine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1resuming/title",
          "value": "VZVirtualMachineStateResuming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1resuming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateResuming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1restoring/title",
          "value": "VZVirtualMachineStateRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1restoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1running/title",
          "value": "VZVirtualMachineStateRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1running/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canRequestStop/title",
          "value": "canRequestStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canRequestStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canRequestStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1pausing/title",
          "value": "VZVirtualMachineStatePausing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1pausing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStatePausing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1graphicsDevices/title",
          "value": "graphicsDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1graphicsDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "graphicsDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1error/title",
          "value": "VZVirtualMachineStateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1saving/title",
          "value": "VZVirtualMachineStateSaving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1saving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateSaving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canResume/title",
          "value": "canResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canResume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canPause/title",
          "value": "canPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1starting/title",
          "value": "VZVirtualMachineStateStarting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1starting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateStarting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStop/title",
          "value": "canStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1paused/title",
          "value": "VZVirtualMachineStatePaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1paused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStatePaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/title",
          "value": "VZVirtualMachineState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopped/title",
          "value": "VZVirtualMachineStateStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopping/title",
          "value": "VZVirtualMachineStateStopping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1State-swift.enum~1stopping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtualMachineStateStopping"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtualmachine/state-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtualmachine/state-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
