{
  "abstract": [
    {
      "text": "Sets the badge image and label for the given ID.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Finder-Sync/documentation/FinderSync",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FIFinderSyncController(im)setBadgeImage:label:forBadgeIdentifier:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setBadgeImage"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSImage",
        "text": "NSImage"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "label"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "forBadgeIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Finder Sync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setBadgeImage:label:forBadgeIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setBadgeImage(_:label:forBadgeIdentifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setBadgeImage"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "image"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSImage",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "label"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "forBadgeIdentifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "badgeID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSImage",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "object. The system may or may not draw this image on top of the item’s",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "icon; when it does, the system determines the overlay position. Don’t",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "add any padding to the image to adjust this positioning. The image draws",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "at up to 320 x 320 points.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "image"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A label describing the sync state represented by this badge.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Each label should be a short localized string, such as “Waiting.”",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "label"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A unique ID, identifying this badge.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "badgeID"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to configure your badges. Finder may display the image, the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "label or both. Your Finder Sync extension typically sets up a fixed number",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of badges during its ",
              "type": "text"
            },
            {
              "code": "init",
              "type": "codeVoice"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Finder-Sync/documentation/FinderSync": {
      "abstract": [
        {
          "text": "Modify the Finder’s user interface to express file synchronization and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync",
      "kind": "symbol",
      "role": "collection",
      "title": "Finder Sync",
      "type": "topic",
      "url": "/documentation/findersync"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController": {
      "abstract": [
        {
          "text": "A controller that acts as a bridge between your Finder Sync extension and the Finder itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FIFinderSyncController"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FIFinderSyncController"
        }
      ],
      "role": "symbol",
      "title": "FIFinderSyncController",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()": {
      "abstract": [
        {
          "text": "Returns the shared Finder Sync controller object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultController"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/default()"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs": {
      "abstract": [
        {
          "text": "The directories managed by this extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "directoryURLs"
        }
      ],
      "role": "symbol",
      "title": "directoryURLs",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/directoryurls"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()": {
      "abstract": [
        {
          "text": "Returns an array of selected items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedItemURLs"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedItemURLs"
        }
      ],
      "role": "symbol",
      "title": "selectedItemURLs()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/selecteditemurls()"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)": {
      "abstract": [
        {
          "text": "Sets the badge for a file or directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBadgeIdentifier:forURL:"
        }
      ],
      "role": "symbol",
      "title": "setBadgeIdentifier(_:for:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/setbadgeidentifier(_:for:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)": {
      "abstract": [
        {
          "text": "Sets the badge image and label for the given ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBadgeImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forBadgeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeImage(_:label:forBadgeIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBadgeImage:label:forBadgeIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "setBadgeImage(_:label:forBadgeIdentifier:)",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/setbadgeimage(_:label:forbadgeidentifier:)"
    },
    "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()": {
      "abstract": [
        {
          "text": "Returns the URL of the Finder’s current target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetedURL"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetedURL"
        }
      ],
      "role": "symbol",
      "title": "targetedURL()",
      "type": "topic",
      "url": "/documentation/findersync/fifindersynccontroller/targetedurl()"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/AppKit/NSImage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/AppKit/NSImage"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Finder-Sync-Controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
        "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()"
      ],
      "title": "Managing the Finder Sync Controller"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setBadgeImage:label:forBadgeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBadgeImage:label:forBadgeIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Finder-Sync/documentation/FinderSync",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Finder-Sync-Controller",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/default()",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/directoryURLs",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/selectedItemURLs()",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/setBadgeIdentifier(_:for:)",
                "doc://com.apple.Finder-Sync/documentation/FinderSync/FIFinderSyncController/targetedURL()"
              ],
              "title": "Managing the Finder Sync Controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setBadgeImage:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSImage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSImage",
                    "text": "NSImage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "image"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "label:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "label"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forBadgeIdentifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "badgeID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AppKit/NSImage",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "object. The system may or may not draw this image on top of the item’s",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "icon; when it does, the system determines the overlay position. Don’t",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "add any padding to the image to adjust this positioning. The image draws",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "at up to 320 x 320 points.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "image"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A label describing the sync state represented by this badge.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "Each label should be a short localized string, such as “Waiting.”",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "label"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A unique ID, identifying this badge.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "badgeID"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/title",
          "value": "FIFinderSyncController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FIFinderSyncController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1selectedItemURLs()/title",
          "value": "selectedItemURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1selectedItemURLs()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectedItemURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1default()/title",
          "value": "defaultController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1directoryURLs/title",
          "value": "directoryURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1directoryURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "directoryURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1targetedURL()/title",
          "value": "targetedURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1targetedURL()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetedURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeIdentifier(_:for:)/title",
          "value": "setBadgeIdentifier:forURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeIdentifier(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBadgeIdentifier:forURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeImage(_:label:forBadgeIdentifier:)/title",
          "value": "setBadgeImage:label:forBadgeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Finder-Sync~1documentation~1FinderSync~1FIFinderSyncController~1setBadgeImage(_:label:forBadgeIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBadgeImage:label:forBadgeIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/findersync/fifindersynccontroller/setbadgeimage(_:label:forbadgeidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/findersync/fifindersynccontroller/setbadgeimage(_:label:forbadgeidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
