{
  "abstract": [
    {
      "text": "The animation that Writing Tools performs when waiting to receive",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "results from the large language model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWritingToolsCoordinatorTextAnimation@NSWritingToolsCoordinatorTextAnimationAnticipate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "anticipate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWritingToolsCoordinatorTextAnimationAnticipate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSWritingToolsCoordinator.TextAnimation.anticipate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "anticipate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This type of animation applies a visual effect to the text that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Writing Tools is evaluating. When preparing for this animation, hide",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the text that Writing Tools is about to evaluate. In the same space",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "where that text appears, Writing Tools displays a preview image that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you provide and animates changes to that image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator": {
      "abstract": [
        {
          "text": "An object that manages interactions between Writing Tools and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your custom text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation": {
      "abstract": [
        {
          "text": "The types of animations that Writing Tools performs during an",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "interactive update of your view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextAnimation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextAnimation"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextAnimation",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textanimation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipate": {
      "abstract": [
        {
          "text": "The animation that Writing Tools performs when waiting to receive",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "results from the large language model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anticipate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextAnimationAnticipate"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextAnimation.anticipate",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textanimation/anticipate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipateInactive": {
      "abstract": [
        {
          "text": "The animation effect that Writing Tools performs when the view is waiting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "for results, but the system isn’t actively evaluating the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anticipateInactive"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipateInactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextAnimationAnticipateInactive"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextAnimation.anticipateInactive",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textanimation/anticipateinactive"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/insert": {
      "abstract": [
        {
          "text": "The animation that Writing Tools performs when inserting text into your view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/insert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextAnimationInsert"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextAnimation.insert",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textanimation/insert"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/remove": {
      "abstract": [
        {
          "text": "The animation that Writing Tools performs when removing text from your view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/remove",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextAnimationRemove"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextAnimation.remove",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textanimation/remove"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/translate": {
      "abstract": [
        {
          "text": "The animation effect that Writing Tools performs on text situated after",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/translate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinatorTextAnimationTranslate"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.TextAnimation.translate",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/textanimation/translate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-animation-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/insert",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/remove",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipateInactive",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/translate"
      ],
      "title": "Getting the animation types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWritingToolsCoordinatorTextAnimationAnticipate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimationAnticipate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-animation-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/insert",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/remove",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/anticipateInactive",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/TextAnimation/translate"
              ],
              "title": "Getting the animation types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWritingToolsCoordinatorTextAnimationAnticipate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1insert/title",
          "value": "NSWritingToolsCoordinatorTextAnimationInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1insert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimationInsert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1translate/title",
          "value": "NSWritingToolsCoordinatorTextAnimationTranslate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1translate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimationTranslate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1remove/title",
          "value": "NSWritingToolsCoordinatorTextAnimationRemove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1remove/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimationRemove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/title",
          "value": "NSWritingToolsCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1anticipate/title",
          "value": "NSWritingToolsCoordinatorTextAnimationAnticipate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1anticipate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimationAnticipate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1anticipateInactive/title",
          "value": "NSWritingToolsCoordinatorTextAnimationAnticipateInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation~1anticipateInactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimationAnticipateInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation/title",
          "value": "NSWritingToolsCoordinatorTextAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1TextAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorTextAnimation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswritingtoolscoordinator/textanimation/anticipate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswritingtoolscoordinator/textanimation/anticipate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
