{
  "abstract": [
    {
      "text": "An alignment that positions lines at the top of the block progression direction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/before"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVCaptionRegionDisplayAlignment@AVCaptionRegionDisplayAlignmentBefore",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "before"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptionRegionDisplayAlignmentBefore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVCaptionRegion.DisplayAlignment.before"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "before"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Aligns lines to the top for English captions, for example.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion": {
      "abstract": [
        {
          "text": "An object that represents the region in which the system presents a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionRegion"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the alignment of lines in a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayAlignment"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayAlignment"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.DisplayAlignment",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/after": {
      "abstract": [
        {
          "text": "An alignment that positions lines at the bottom of the block progression direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "after"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/after",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionRegionDisplayAlignmentAfter"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.DisplayAlignment.after",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum/after"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/before": {
      "abstract": [
        {
          "text": "An alignment that positions lines at the top of the block progression direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "before"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/before",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionRegionDisplayAlignmentBefore"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.DisplayAlignment.before",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum/before"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/center": {
      "abstract": [
        {
          "text": "An alignment that positions lines in the middle of the block progression direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionRegionDisplayAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.DisplayAlignment.center",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum/center"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Display-Alignments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/center",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/after"
      ],
      "title": "Display Alignments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptionRegionDisplayAlignmentBefore"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignmentBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Display-Alignments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/center",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum/after"
              ],
              "title": "Display Alignments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVCaptionRegionDisplayAlignmentBefore"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum~1center/title",
          "value": "AVCaptionRegionDisplayAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum~1before/title",
          "value": "AVCaptionRegionDisplayAlignmentBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum~1before/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignmentBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum/title",
          "value": "AVCaptionRegionDisplayAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum~1after/title",
          "value": "AVCaptionRegionDisplayAlignmentAfter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum~1after/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignmentAfter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion/title",
          "value": "AVCaptionRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum/before"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum/before"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
