{
  "abstract": [
    {
      "text": "Constants that specify options for configuring the contents of the main Print panel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSPrintPanelOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Options"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSPrintPanel.Options"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Options"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel": {
      "abstract": [
        {
          "text": "The Print panel that queries the user for information about a print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify job style hints for activating the simplified Print panel interface and setting the options to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JobStyleHint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JobStyleHint"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.JobStyleHint",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/jobstylehint-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify options for configuring the contents of the main Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.Options",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies": {
      "abstract": [
        {
          "text": "The Print panel includes a field for manipulating the number of copies being printed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsCopies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsCopies"
        }
      ],
      "role": "symbol",
      "title": "showsCopies",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showscopies"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation": {
      "abstract": [
        {
          "text": "The Print panel includes a control for manipulating the page orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsOrientation"
        }
      ],
      "role": "symbol",
      "title": "showsOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showsorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange": {
      "abstract": [
        {
          "text": "The Print panel includes a set of fields for manipulating the range of pages being printed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPageRange"
        }
      ],
      "role": "symbol",
      "title": "showsPageRange",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspagerange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory": {
      "abstract": [
        {
          "text": "The Print panel includes a separate accessory view for manipulating the paper size, orientation, and scaling attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPageSetupAccessory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPageSetupAccessory"
        }
      ],
      "role": "symbol",
      "title": "showsPageSetupAccessory",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspagesetupaccessory"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize": {
      "abstract": [
        {
          "text": "The Print panel includes a control for manipulating the paper size of the printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPaperSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPaperSize"
        }
      ],
      "role": "symbol",
      "title": "showsPaperSize",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspapersize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview": {
      "abstract": [
        {
          "text": "The Print panel displays a built-in preview of the document contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPreview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPreview"
        }
      ],
      "role": "symbol",
      "title": "showsPreview",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showspreview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection": {
      "abstract": [
        {
          "text": "The Print panel includes an additional selection option for paper range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPrintSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsPrintSelection"
        }
      ],
      "role": "symbol",
      "title": "showsPrintSelection",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showsprintselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling": {
      "abstract": [
        {
          "text": "The Print panel includes a control for scaling the printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsScaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelShowsScaling"
        }
      ],
      "role": "symbol",
      "title": "showsScaling",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct/showsscaling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()": {
      "abstract": [
        {
          "text": "Returns the title of the Print panel’s default button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultButtonTitle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultButtonTitle"
        }
      ],
      "role": "symbol",
      "title": "defaultButtonTitle()",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/defaultbuttontitle()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor": {
      "abstract": [
        {
          "text": "The HTML help anchor associated with the Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "helpAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSHelpManager",
          "text": "NSHelpManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSHelpAnchorName",
          "text": "AnchorName"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "helpAnchor"
        }
      ],
      "role": "symbol",
      "title": "helpAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/helpanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property": {
      "abstract": [
        {
          "text": "The type of settings that the print panel displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobStyleHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintPanelJobStyleHint",
          "text": "JobStyleHint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jobStyleHint"
        }
      ],
      "role": "symbol",
      "title": "jobStyleHint",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/jobstylehint-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property": {
      "abstract": [
        {
          "text": "The current configuration options for the Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the Print panel’s default button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDefaultButtonTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDefaultButtonTitle:"
        }
      ],
      "role": "symbol",
      "title": "setDefaultButtonTitle(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/setdefaultbuttontitle(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-Panel",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor"
      ],
      "title": "Customizing the Panel"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrintPanelOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsCopies",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageRange",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPaperSize",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsOrientation",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsScaling",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPrintSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPageSetupAccessory",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct/showsPreview"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-Panel",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor"
              ],
              "title": "Customizing the Panel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrintPanelOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageSetupAccessory/title",
          "value": "NSPrintPanelShowsPageSetupAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageSetupAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPageSetupAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsCopies/title",
          "value": "NSPrintPanelShowsCopies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsCopies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsCopies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/title",
          "value": "NSPrintPanelOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsScaling/title",
          "value": "NSPrintPanelShowsScaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsScaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsScaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1options-swift.property/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1options-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsOrientation/title",
          "value": "NSPrintPanelShowsOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPaperSize/title",
          "value": "NSPrintPanelShowsPaperSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPaperSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPaperSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1jobStyleHint-swift.property/title",
          "value": "jobStyleHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1jobStyleHint-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jobStyleHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPrintSelection/title",
          "value": "NSPrintPanelShowsPrintSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPrintSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPrintSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1defaultButtonTitle()/title",
          "value": "defaultButtonTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1defaultButtonTitle()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "defaultButtonTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1helpAnchor/title",
          "value": "helpAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1helpAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "helpAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageRange/title",
          "value": "NSPrintPanelShowsPageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1JobStyleHint-swift.struct/title",
          "value": "NSPrintPanelJobStyleHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1JobStyleHint-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelJobStyleHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1JobStyleHint-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelJobStyleHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/title",
          "value": "NSPrintPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1setDefaultButtonTitle(_:)/title",
          "value": "setDefaultButtonTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1setDefaultButtonTitle(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDefaultButtonTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPreview/title",
          "value": "NSPrintPanelShowsPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct~1showsPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelShowsPreview"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintpanel/options-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintpanel/options-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
