{
  "abstract": [
    {
      "text": "The plane anchor represents a real-world floor, ground plane, or similar large horizontal surface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/floor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO5flooryA2EmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "floor"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARPlaneAnchor.Classification.floor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "floor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor": {
      "abstract": [
        {
          "text": "An anchor for a 2D planar surface that ARKit detects in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARPlaneAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARPlaneAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum": {
      "abstract": [
        {
          "text": "Possible characterizations of real-world surfaces represented by plane anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/ceiling": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world ceiling or similar overhead horizontal surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ceiling"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/ceiling",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.ceiling",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/ceiling"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/door": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world door or similar vertical surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "door"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/door",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.door",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/door"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/floor": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world floor, ground plane, or similar large horizontal surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/floor",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.floor",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/floor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/seat": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world chair, stool, bench or similar flat surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seat"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/seat",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.seat",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/seat"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/table": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world table, desk, bar, or similar flat surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/table",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.table",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/table"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/wall": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world wall or similar large vertical surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wall"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/wall",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.wall",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/wall"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/window": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world window or similar vertical surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/window",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.window",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/window"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Plane-Classifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/wall",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/ceiling",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/table",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/seat",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/door",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/window"
      ],
      "title": "Plane Classifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/title",
          "value": "ARPlaneAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arplaneanchor/classification-swift.enum/floor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
