{
  "abstract": [
    {
      "text": "A constant that identifies the PDF417 symbology.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/pdf417"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataObjectTypePDF417Code",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pdf417"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVMetadataObject",
        "text": "AVMetadataObject"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataObjectType",
        "text": "ObjectType"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataObjectTypePDF417Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "pdf417"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pdf417"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMetadataObject",
              "text": "AVMetadataObject"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataObjectType",
              "text": "ObjectType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject": {
      "abstract": [
        {
          "text": "The abstract superclass for objects provided by a metadata capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType": {
      "abstract": [
        {
          "text": "Constants that identify metadata object types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ObjectType"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataObject.ObjectType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/aztec": {
      "abstract": [
        {
          "text": "A constant that identifies the Aztec symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aztec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/aztec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObjectTypeAztecCode"
        }
      ],
      "role": "symbol",
      "title": "aztec",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype/aztec"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/dataMatrix": {
      "abstract": [
        {
          "text": "A constant that identifies the DataMatrix symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/dataMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObjectTypeDataMatrixCode"
        }
      ],
      "role": "symbol",
      "title": "dataMatrix",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype/datamatrix"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microPDF417": {
      "abstract": [
        {
          "text": "A constant that identifies the Micro PDF417 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microPDF417"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microPDF417",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObjectTypeMicroPDF417Code"
        }
      ],
      "role": "symbol",
      "title": "microPDF417",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype/micropdf417"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microQR": {
      "abstract": [
        {
          "text": "A constant that identifies the Micro QR symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microQR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microQR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObjectTypeMicroQRCode"
        }
      ],
      "role": "symbol",
      "title": "microQR",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype/microqr"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/pdf417": {
      "abstract": [
        {
          "text": "A constant that identifies the PDF417 symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pdf417"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/pdf417",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObjectTypePDF417Code"
        }
      ],
      "role": "symbol",
      "title": "pdf417",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype/pdf417"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/qr": {
      "abstract": [
        {
          "text": "A constant that identifies the QR symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "qr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/qr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObjectTypeQRCode"
        }
      ],
      "role": "symbol",
      "title": "qr",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype/qr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "2D-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/aztec",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/dataMatrix",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microPDF417",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microQR",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/qr"
      ],
      "title": "2D Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataObjectTypePDF417Code"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypePDF417Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "2D-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/aztec",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/dataMatrix",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microPDF417",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/microQR",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType/qr"
              ],
              "title": "2D Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataObjectType",
                    "text": "AVMetadataObjectType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataObjectTypePDF417Code"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType/title",
          "value": "AVMetadataObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1microPDF417/title",
          "value": "AVMetadataObjectTypeMicroPDF417Code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1microPDF417/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypeMicroPDF417Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1pdf417/title",
          "value": "AVMetadataObjectTypePDF417Code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1pdf417/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypePDF417Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1aztec/title",
          "value": "AVMetadataObjectTypeAztecCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1aztec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypeAztecCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1qr/title",
          "value": "AVMetadataObjectTypeQRCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1qr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypeQRCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1dataMatrix/title",
          "value": "AVMetadataObjectTypeDataMatrixCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1dataMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypeDataMatrixCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1microQR/title",
          "value": "AVMetadataObjectTypeMicroQRCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType~1microQR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectTypeMicroQRCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/title",
          "value": "AVMetadataObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataobject/objecttype/pdf417"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataobject/objecttype/pdf417"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
