{
  "abstract": [
    {
      "text": "A general characterization of what kind of real-world surface the plane anchor represents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "s:So13ARPlaneAnchorC5ARKitE14classificationAbCE14ClassificationOvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "classification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARPlaneAnchor",
        "text": "ARPlaneAnchor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
        "text": "Classification"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "classification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "classification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARPlaneAnchor",
              "text": "ARPlaneAnchor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
              "text": "Classification"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On supported devices, ARKit automatically attempts to characterize each detected plane, describing it as a real-world surface such as as a wall, floor, or table. You can then use this information to enhance the realism of your AR experience; for example, by placing certain virtual content only on floors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Plane classification can take longer than plane detection, and ARKit reports classifications only for planes where it has a high confidence in the result. If ARKit currently has no classification result for a plane, this property’s value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/none(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", with an associated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/Status",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value indicating why.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Plane classification is available only on iPhone XS, iPhone XS Max, and iPhone XR. Before using classification results, check the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class property to make sure you’re on a supported device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor": {
      "abstract": [
        {
          "text": "An anchor for a 2D planar surface that ARKit detects in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARPlaneAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARPlaneAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum": {
      "abstract": [
        {
          "text": "Possible characterizations of real-world surfaces represented by plane anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/Status": {
      "abstract": [
        {
          "text": "Reasons ARKit is unable to classify a plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/Status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.Status",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/status"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/none(_:)": {
      "abstract": [
        {
          "text": "No classification is available for the plane anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARPlaneAnchor",
          "text": "ARPlaneAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
          "text": "Classification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO6StatusO",
          "text": "Status"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/none(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.none(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/none(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8": {
      "abstract": [
        {
          "text": "A general characterization of what kind of real-world surface the plane anchor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARPlaneAnchor",
          "text": "ARPlaneAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
          "text": "Classification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8",
      "kind": "symbol",
      "role": "symbol",
      "title": "classification",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-2r4x8"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether plane classification is available on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isClassificationSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classificationSupported"
        }
      ],
      "role": "symbol",
      "title": "isClassificationSupported",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/isclassificationsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classifying-a-Plane",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum"
      ],
      "title": "Classifying a Plane"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/title",
          "value": "ARPlaneAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor~1isClassificationSupported/title",
          "value": "classificationSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor~1isClassificationSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "classificationSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arplaneanchor/classification-2r4x8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
