{
  "abstract": [
    {
      "text": "Possible characterizations of real-world surfaces represented by plane anchors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Classification"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Classification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ARPlaneAnchor.Classification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Classification"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You get values of this type from a plane anchor’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, identifying both the likely type of real-world surface for a detected plane anchor and the state of ARKit’s plane classification process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor": {
      "abstract": [
        {
          "text": "An anchor for a 2D planar surface that ARKit detects in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARPlaneAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARPlaneAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum": {
      "abstract": [
        {
          "text": "Possible characterizations of real-world surfaces represented by plane anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Classification"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/Status": {
      "abstract": [
        {
          "text": "Reasons ARKit is unable to classify a plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/Status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.Status",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/status"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/ceiling": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world ceiling or similar overhead horizontal surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ceiling"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/ceiling",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.ceiling",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/ceiling"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/door": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world door or similar vertical surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "door"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/door",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.door",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/door"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/floor": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world floor, ground plane, or similar large horizontal surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/floor",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.floor",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/floor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/none(_:)": {
      "abstract": [
        {
          "text": "No classification is available for the plane anchor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARPlaneAnchor",
          "text": "ARPlaneAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
          "text": "Classification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO6StatusO",
          "text": "Status"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/none(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.none(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/none(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/seat": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world chair, stool, bench or similar flat surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seat"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/seat",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.seat",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/seat"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/table": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world table, desk, bar, or similar flat surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/table",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.table",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/table"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/wall": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world wall or similar large vertical surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wall"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/wall",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.wall",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/wall"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/window": {
      "abstract": [
        {
          "text": "The plane anchor represents a real-world window or similar vertical surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/window",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARPlaneAnchor.Classification.window",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-swift.enum/window"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8": {
      "abstract": [
        {
          "text": "A general characterization of what kind of real-world surface the plane anchor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARPlaneAnchor",
          "text": "ARPlaneAnchor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So13ARPlaneAnchorC5ARKitE14ClassificationO",
          "text": "Classification"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8",
      "kind": "symbol",
      "role": "symbol",
      "title": "classification",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/classification-2r4x8"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether plane classification is available on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isClassificationSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "classificationSupported"
        }
      ],
      "role": "symbol",
      "title": "isClassificationSupported",
      "type": "topic",
      "url": "/documentation/arkit/arplaneanchor/isclassificationsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classifying-a-Plane",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/isClassificationSupported",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/classification-2r4x8"
      ],
      "title": "Classifying a Plane"
    }
  ],
  "topicSections": [
    {
      "anchor": "Plane-Classifications",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/wall",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/floor",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/ceiling",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/table",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/seat",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/door",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/window"
      ],
      "title": "Plane Classifications"
    },
    {
      "anchor": "Missing-Classification-Status",
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/none(_:)",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneAnchor/Classification-swift.enum/Status"
      ],
      "title": "Missing Classification Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor~1isClassificationSupported/title",
          "value": "classificationSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor~1isClassificationSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "classificationSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/title",
          "value": "ARPlaneAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arplaneanchor/classification-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
