{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType/init(rawValue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So44VTHDRPerFrameMetadataGenerationHDRFormatTypea8rawValueABSo11CFStringRefa_tcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rawValue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType": {
      "abstract": [
        {
          "text": "The HDR format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        }
      ],
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationHDRFormatType",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationhdrformattype"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationhdrformattype/init(rawvalue:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/title",
          "value": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vthdrperframemetadatagenerationhdrformattype/init(rawvalue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
