{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@E@HKStateOfMindAssociation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Association"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Association"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HKStateOfMind.Association"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Association"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramConductionType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramConductionType"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramConductionType",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramconductiontype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTestSide"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKAudiogramSensitivityTestSide"
        }
      ],
      "role": "symbol",
      "title": "HKAudiogramSensitivityTestSide",
      "type": "topic",
      "url": "/documentation/healthkit/hkaudiogramsensitivitytestside"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex": {
      "abstract": [
        {
          "text": "Constants indicating the user’s sex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBiologicalSex"
        }
      ],
      "role": "symbol",
      "title": "HKBiologicalSex",
      "type": "topic",
      "url": "/documentation/healthkit/hkbiologicalsex"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType": {
      "abstract": [
        {
          "text": "Constants indicating the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueVaginalBleeding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueVaginalBleeding"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueVaginalBleeding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluevaginalbleeding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType": {
      "abstract": [
        {
          "text": "Categories representing the user’s skin type based on the Fitzpatrick scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKFitzpatrickSkinType"
        }
      ],
      "role": "symbol",
      "title": "HKFitzpatrickSkinType",
      "type": "topic",
      "url": "/documentation/healthkit/hkfitzpatrickskintype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "role": "symbol",
      "title": "HKGAD7Assessment.Answer",
      "type": "topic",
      "url": "/documentation/healthkit/hkgad7assessment/answer"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "role": "symbol",
      "title": "HKGAD7Assessment.Risk",
      "type": "topic",
      "url": "/documentation/healthkit/hkgad7assessment/risk-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Answer"
        }
      ],
      "role": "symbol",
      "title": "HKPHQ9Assessment.Answer",
      "type": "topic",
      "url": "/documentation/healthkit/hkphq9assessment/answer"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Risk"
        }
      ],
      "role": "symbol",
      "title": "HKPHQ9Assessment.Risk",
      "type": "topic",
      "url": "/documentation/healthkit/hkphq9assessment/risk-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Association"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Association"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/community": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "community"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/community",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationCommunity"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.community",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/community"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/currentEvents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentEvents"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/currentEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationCurrentEvents"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.currentEvents",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/currentevents"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/dating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dating"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/dating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationDating"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.dating",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/dating"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/education": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "education"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/education",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationEducation"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.education",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/education"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/family": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "family"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/family",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationFamily"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.family",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/family"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/fitness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fitness"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/fitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationFitness"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.fitness",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/fitness"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/friends": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friends"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/friends",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationFriends"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.friends",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/friends"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/health": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "health"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/health",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationHealth"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.health",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/health"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/hobbies": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hobbies"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/hobbies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationHobbies"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.hobbies",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/hobbies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/identity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identity"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/identity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationIdentity"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.identity",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/identity"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/money": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "money"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/money",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationMoney"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.money",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/money"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/partner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partner"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/partner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationPartner"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.partner",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/partner"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/selfCare": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selfCare"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/selfCare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationSelfCare"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.selfCare",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/selfcare"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/spirituality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spirituality"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/spirituality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationSpirituality"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.spirituality",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/spirituality"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/tasks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tasks"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/tasks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationTasks"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.tasks",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/tasks"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/travel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "travel"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/travel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationTravel"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.travel",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/travel"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/weather": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weather"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/weather",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationWeather"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.weather",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/weather"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/work": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "work"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/work",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKStateOfMindAssociationWork"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Association.work",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/association/work"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Kind",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/kind-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Label"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Label"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.Label",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/label"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ValenceClassification"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ValenceClassification"
        }
      ],
      "role": "symbol",
      "title": "HKStateOfMind.ValenceClassification",
      "type": "topic",
      "url": "/documentation/healthkit/hkstateofmind/valenceclassification-swift.enum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse": {
      "abstract": [
        {
          "text": "Constants indicating the user’s wheelchair use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWheelchairUse"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWheelchairUse"
        }
      ],
      "role": "symbol",
      "title": "HKWheelchairUse",
      "type": "topic",
      "url": "/documentation/healthkit/hkwheelchairuse"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQueryOptions"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQueryOptions"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutEffortRelationshipQueryOptions",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkouteffortrelationshipqueryoptions"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer",
        "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/community",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/currentEvents",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/dating",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/education",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/family",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/fitness",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/friends",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/health",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/hobbies",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/identity",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/money",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/partner",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/selfCare",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/spirituality",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/tasks",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/travel",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/weather",
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/work"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKStateOfMindAssociation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/community",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/currentEvents",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/dating",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/education",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/family",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/fitness",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/friends",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/health",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/hobbies",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/identity",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/money",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/partner",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/selfCare",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/spirituality",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/tasks",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/travel",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/weather",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Association/work"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramConductionType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKAudiogramSensitivityTestSide",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueVaginalBleeding",
                "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Answer",
                "doc://com.apple.healthkit/documentation/HealthKit/HKGAD7Assessment/Risk-swift.enum",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Answer",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPHQ9Assessment/Risk-swift.enum",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Kind-swift.enum",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/Label",
                "doc://com.apple.healthkit/documentation/HealthKit/HKStateOfMind/ValenceClassification-swift.enum",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutEffortRelationshipQueryOptions",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBiologicalSex",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKFitzpatrickSkinType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKWheelchairUse"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKStateOfMindAssociation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQueryOptions/title",
          "value": "HKWorkoutEffortRelationshipQueryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQueryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQueryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQueryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQueryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1weather/title",
          "value": "HKStateOfMindAssociationWeather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1weather/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationWeather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1hobbies/title",
          "value": "HKStateOfMindAssociationHobbies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1hobbies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationHobbies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Label/title",
          "value": "HKStateOfMindLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Label/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1family/title",
          "value": "HKStateOfMindAssociationFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1family/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1education/title",
          "value": "HKStateOfMindAssociationEducation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1education/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationEducation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Kind-swift.enum/title",
          "value": "HKStateOfMindKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Kind-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Kind-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1money/title",
          "value": "HKStateOfMindAssociationMoney"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1money/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationMoney"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1spirituality/title",
          "value": "HKStateOfMindAssociationSpirituality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1spirituality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationSpirituality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Answer/title",
          "value": "HKPHQ9AssessmentAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Answer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Answer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1work/title",
          "value": "HKStateOfMindAssociationWork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1work/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationWork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1currentEvents/title",
          "value": "HKStateOfMindAssociationCurrentEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1currentEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationCurrentEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Answer/title",
          "value": "HKGAD7AssessmentAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Answer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Answer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1travel/title",
          "value": "HKStateOfMindAssociationTravel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1travel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationTravel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1selfCare/title",
          "value": "HKStateOfMindAssociationSelfCare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1selfCare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationSelfCare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1fitness/title",
          "value": "HKStateOfMindAssociationFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1fitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Risk-swift.enum/title",
          "value": "HKPHQ9AssessmentRisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Risk-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPHQ9Assessment~1Risk-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPHQ9AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1community/title",
          "value": "HKStateOfMindAssociationCommunity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1community/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationCommunity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/title",
          "value": "HKBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramConductionType/title",
          "value": "HKAudiogramConductionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramConductionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramConductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramConductionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramConductionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUse/title",
          "value": "HKWheelchairUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWheelchairUse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWheelchairUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1identity/title",
          "value": "HKStateOfMindAssociationIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1identity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/title",
          "value": "HKFitzpatrickSkinType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKFitzpatrickSkinType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKFitzpatrickSkinType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Risk-swift.enum/title",
          "value": "HKGAD7AssessmentRisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Risk-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKGAD7Assessment~1Risk-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKGAD7AssessmentRisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/title",
          "value": "HKCategoryValueVaginalBleeding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueVaginalBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueVaginalBleeding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueVaginalBleeding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1ValenceClassification-swift.enum/title",
          "value": "HKStateOfMindValenceClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1ValenceClassification-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindValenceClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1ValenceClassification-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindValenceClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTestSide/title",
          "value": "HKAudiogramSensitivityTestSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTestSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTestSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKAudiogramSensitivityTestSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKAudiogramSensitivityTestSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1partner/title",
          "value": "HKStateOfMindAssociationPartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1partner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationPartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association/title",
          "value": "HKStateOfMindAssociation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1friends/title",
          "value": "HKStateOfMindAssociationFriends"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1friends/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationFriends"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1health/title",
          "value": "HKStateOfMindAssociationHealth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1health/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationHealth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/title",
          "value": "HKStateOfMind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1tasks/title",
          "value": "HKStateOfMindAssociationTasks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1tasks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationTasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/title",
          "value": "HKBiologicalSex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBiologicalSex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1dating/title",
          "value": "HKStateOfMindAssociationDating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKStateOfMind~1Association~1dating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKStateOfMindAssociationDating"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkstateofmind/association"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkstateofmind/association"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
