{
  "abstract": [
    {
      "text": "A value that indicates the visibility of the title.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITitlebar(py)titleVisibility",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "titleVisibility"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UITitlebarTitleVisibility",
        "text": "UITitlebarTitleVisibility"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "titleVisibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "titleVisibility"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "titleVisibility"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UITitlebarTitleVisibility",
              "text": "UITitlebarTitleVisibility"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Setting the title visibility to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " hides only the title displayed in the title bar, not the title bar itself. To remove the title bar from the window, set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property defaults to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar": {
      "abstract": [
        {
          "text": "An object that you use to configure the title bar of a window in a Mac app built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebar"
        }
      ],
      "role": "symbol",
      "title": "UITitlebar",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL": {
      "abstract": [
        {
          "text": "A URL of the file or resource represented in the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "representedURL"
        }
      ],
      "role": "symbol",
      "title": "representedURL",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/representedurl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle": {
      "abstract": [
        {
          "text": "The type of separator that the app displays between the title bar and content of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "separatorStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITitlebarSeparatorStyle",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "separatorStyle"
        }
      ],
      "role": "symbol",
      "title": "separatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/separatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility": {
      "abstract": [
        {
          "text": "A value that indicates the visibility of the title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleVisibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITitlebarTitleVisibility",
          "text": "UITitlebarTitleVisibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleVisibility"
        }
      ],
      "role": "symbol",
      "title": "titleVisibility",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/titlevisibility"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbar": {
      "abstract": [
        {
          "text": "The toolbar displayed beneath or integrated with the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSToolbar",
          "text": "NSToolbar"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbar"
        }
      ],
      "role": "symbol",
      "title": "toolbar",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/toolbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle": {
      "abstract": [
        {
          "text": "Styles that determine the type of separator displayed between the title bar and content of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility": {
      "abstract": [
        {
          "text": "States that determine visibility of the title in the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibility"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarTitleVisibility",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden": {
      "abstract": [
        {
          "text": "A state indicating that the title isn’t visible in the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibilityHidden"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarTitleVisibility.hidden",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility/hidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible": {
      "abstract": [
        {
          "text": "A state indicating that the title is visible in the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibilityVisible"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarTitleVisibility.visible",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility/visible"
    },
    "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Display content that fills the entire height of a window by removing the title bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Removing the title bar in your Mac app built with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-title-bar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL"
      ],
      "title": "Configuring the title bar"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "titleVisibility"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-title-bar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL"
              ],
              "title": "Configuring the title bar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UITitlebarTitleVisibility",
                    "text": "UITitlebarTitleVisibility"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "titleVisibility"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1toolbar/title",
          "value": "toolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1toolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar/title",
          "value": "UITitlebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility/title",
          "value": "UITitlebarTitleVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1hidden/title",
          "value": "UITitlebarTitleVisibilityHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1hidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibilityHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1visible/title",
          "value": "UITitlebarTitleVisibilityVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1visible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibilityVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1representedURL/title",
          "value": "representedURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1representedURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "representedURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1titleVisibility/title",
          "value": "titleVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1titleVisibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1separatorStyle/title",
          "value": "separatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1separatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "separatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/title",
          "value": "UITitlebarSeparatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uititlebar/titlevisibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uititlebar/titlevisibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
