{
  "abstract": [
    {
      "text": "The toolbar displayed beneath or integrated with the title bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbar"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITitlebar(py)toolbar",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "toolbar"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSToolbar",
        "text": "NSToolbar"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "toolbar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "toolbar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "toolbar"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSToolbar",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbar",
              "text": "NSToolbar"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar": {
      "abstract": [
        {
          "text": "An object that you use to configure the title bar of a window in a Mac app built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebar"
        }
      ],
      "role": "symbol",
      "title": "UITitlebar",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/autoHidesToolbarInFullScreen": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the toolbar automatically hides in full-screen windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHidesToolbarInFullScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/autoHidesToolbarInFullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoHidesToolbarInFullScreen"
        }
      ],
      "role": "symbol",
      "title": "autoHidesToolbarInFullScreen",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/autohidestoolbarinfullscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbar": {
      "abstract": [
        {
          "text": "The toolbar displayed beneath or integrated with the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSToolbar",
          "text": "NSToolbar"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbar"
        }
      ],
      "role": "symbol",
      "title": "toolbar",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/toolbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbarStyle": {
      "abstract": [
        {
          "text": "The style of the toolbar determining its appearance and location related to the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITitlebarToolbarStyle",
          "text": "UITitlebarToolbarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarStyle"
        }
      ],
      "role": "symbol",
      "title": "toolbarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/toolbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle": {
      "abstract": [
        {
          "text": "Styles that determine the toolbar’s appearance and location related to the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarToolbarStyle"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarToolbarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartoolbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Display content that fills the entire height of a window by removing the title bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Removing the title bar in your Mac app built with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSToolbar": {
      "abstract": [
        {
          "text": "An object that manages the space above your app’s custom content and either below or integrated with the window’s title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSToolbar",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbar",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbar"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-toolbar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbarStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/autoHidesToolbarInFullScreen"
      ],
      "title": "Configuring the toolbar"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "toolbar"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-toolbar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/toolbarStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarToolbarStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/autoHidesToolbarInFullScreen"
              ],
              "title": "Configuring the toolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSToolbar",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSToolbar",
                    "text": "NSToolbar"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "toolbar"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1autoHidesToolbarInFullScreen/title",
          "value": "autoHidesToolbarInFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1autoHidesToolbarInFullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoHidesToolbarInFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle/title",
          "value": "UITitlebarToolbarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarToolbarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarToolbarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar/title",
          "value": "UITitlebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1toolbar/title",
          "value": "toolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1toolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSToolbar/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbar"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1toolbarStyle/title",
          "value": "toolbarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1toolbarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uititlebar/toolbar"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uititlebar/toolbar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
