{
  "abstract": [
    {
      "text": "Each pair of consecutive indices in the submesh refers to two vertices to be rendered as a line segment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/lines"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLGeometryType@MDLGeometryTypeLines",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lines"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLGeometryTypeLines"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MDLGeometryType.lines"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lines"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType": {
      "abstract": [
        {
          "text": "Types of geometric primitives for rendering a submesh, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLGeometryType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryType"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/lines": {
      "abstract": [
        {
          "text": "Each pair of consecutive indices in the submesh refers to two vertices to be rendered as a line segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lines"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/lines",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryTypeLines"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType.lines",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype/lines"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/points": {
      "abstract": [
        {
          "text": "Each index in the submesh refers to a vertex to be rendered as a single point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "points"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/points",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryTypePoints"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType.points",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype/points"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/quads": {
      "abstract": [
        {
          "text": "Each set of four consecutive indices in the submesh refers to four vertices to be rendered as a quadrilateral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quads"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/quads",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryTypeQuads"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType.quads",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype/quads"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangleStrips": {
      "abstract": [
        {
          "text": "The first three consecutive indices in the submesh refer to three vertices to be rendered as a triangle. Each subsequent index refers to another vertex that completes a triangle formed by connecting it to the previous two vertices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleStrips"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangleStrips",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryTypeTriangleStrips"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType.triangleStrips",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype/trianglestrips"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangles": {
      "abstract": [
        {
          "text": "Each set of three consecutive indices in the submesh refers to three vertices to be rendered as a triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangles"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryTypeTriangles"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType.triangles",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype/triangles"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/variableTopology": {
      "abstract": [
        {
          "text": "The submesh’s index buffer does not contain a uniform set of primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "variableTopology"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/variableTopology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLGeometryTypeVariableTopology"
        }
      ],
      "role": "symbol",
      "title": "MDLGeometryType.variableTopology",
      "type": "topic",
      "url": "/documentation/modelio/mdlgeometrytype/variabletopology"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType": {
      "abstract": [
        {
          "text": "The type of geometric primitives described by the submesh’s index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLGeometryType",
          "text": "MDLGeometryType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh/geometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometryType"
        }
      ],
      "role": "symbol",
      "title": "geometryType",
      "type": "topic",
      "url": "/documentation/modelio/mdlsubmesh/geometrytype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/points",
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangles",
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangleStrips",
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/quads",
        "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/variableTopology"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLGeometryTypeLines"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypeLines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/points",
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangles",
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/triangleStrips",
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/quads",
                "doc://com.apple.modelio/documentation/ModelIO/MDLGeometryType/variableTopology"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLGeometryTypeLines"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/title",
          "value": "MDLGeometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1variableTopology/title",
          "value": "MDLGeometryTypeVariableTopology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1variableTopology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypeVariableTopology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1lines/title",
          "value": "MDLGeometryTypeLines"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1lines/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypeLines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1quads/title",
          "value": "MDLGeometryTypeQuads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1quads/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypeQuads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1triangles/title",
          "value": "MDLGeometryTypeTriangles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1triangles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypeTriangles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1geometryType/title",
          "value": "geometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh~1geometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1triangleStrips/title",
          "value": "MDLGeometryTypeTriangleStrips"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1triangleStrips/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypeTriangleStrips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1points/title",
          "value": "MDLGeometryTypePoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLGeometryType~1points/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLGeometryTypePoints"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlgeometrytype/lines"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlgeometrytype/lines"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
