{
  "abstract": [
    {
      "text": "The argument is an intersection function table.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLArgumentType@MTLArgumentTypeIntersectionFunctionTable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "intersectionFunctionTable"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLArgumentTypeIntersectionFunctionTable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLArgumentType.intersectionFunctionTable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "intersectionFunctionTable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType": {
      "abstract": [
        {
          "text": "The resource type for an argument of a function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentType"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer": {
      "abstract": [
        {
          "text": "The argument is a buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.buffer",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/buffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock": {
      "abstract": [
        {
          "text": "The argument is an imageblock.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageblock"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeImageblock"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.imageblock",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/imageblock"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData": {
      "abstract": [
        {
          "text": "The argument is imageblock data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageblockData"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeImageblockData"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.imageblockData",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/imageblockdata"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure": {
      "abstract": [
        {
          "text": "The argument is a top-level ray tracing acceleration structure for a set of instances.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeInstanceAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.instanceAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/instanceaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable": {
      "abstract": [
        {
          "text": "The argument is an intersection function table.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intersectionFunctionTable"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeIntersectionFunctionTable"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.intersectionFunctionTable",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/intersectionfunctiontable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure": {
      "abstract": [
        {
          "text": "The argument is a bottom-level ray tracing acceleraton structure for a set of primitives.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primitiveAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypePrimitiveAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.primitiveAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/primitiveaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler": {
      "abstract": [
        {
          "text": "The argument is a texture sampler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampler"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeSampler"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.sampler",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/sampler"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture": {
      "abstract": [
        {
          "text": "The argument is a texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeTexture"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.texture",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/texture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory": {
      "abstract": [
        {
          "text": "The argument is a pointer to threadgroup memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadgroupMemory"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeThreadgroupMemory"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.threadgroupMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/threadgroupmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable": {
      "abstract": [
        {
          "text": "The argument is a visible function table.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleFunctionTable"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeVisibleFunctionTable"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.visibleFunctionTable",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/visiblefunctiontable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Argument-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure"
      ],
      "title": "Argument Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLArgumentTypeIntersectionFunctionTable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeIntersectionFunctionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Argument-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure"
              ],
              "title": "Argument Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLArgumentTypeIntersectionFunctionTable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1intersectionFunctionTable/title",
          "value": "MTLArgumentTypeIntersectionFunctionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1intersectionFunctionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeIntersectionFunctionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblock/title",
          "value": "MTLArgumentTypeImageblock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeImageblock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1primitiveAccelerationStructure/title",
          "value": "MTLArgumentTypePrimitiveAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1primitiveAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypePrimitiveAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1threadgroupMemory/title",
          "value": "MTLArgumentTypeThreadgroupMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1threadgroupMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeThreadgroupMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblockData/title",
          "value": "MTLArgumentTypeImageblockData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblockData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeImageblockData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1sampler/title",
          "value": "MTLArgumentTypeSampler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1sampler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1instanceAccelerationStructure/title",
          "value": "MTLArgumentTypeInstanceAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1instanceAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeInstanceAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/title",
          "value": "MTLArgumentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1buffer/title",
          "value": "MTLArgumentTypeBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1texture/title",
          "value": "MTLArgumentTypeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1visibleFunctionTable/title",
          "value": "MTLArgumentTypeVisibleFunctionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1visibleFunctionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeVisibleFunctionTable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlargumenttype/intersectionfunctiontable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlargumenttype/intersectionfunctiontable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
