{
  "abstract": [
    {
      "text": "A large square area that ClockKit displays on the X-Large watch face.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLKComplicationFamily@CLKComplicationFamilyGraphicExtraLarge",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "graphicExtraLarge"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplicationFamilyGraphicExtraLarge"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLKComplicationFamily.graphicExtraLarge"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "graphicExtraLarge"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the size and location of the graphic rectangular complication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3667212",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " family is for 40 mm and 44 mm Apple Watches only. When available, the system prefers the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " family over the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily": {
      "abstract": [
        {
          "text": "Constants indicating the template groups.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge": {
      "abstract": [
        {
          "text": "A large square area that ClockKit displays on the X-Large watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraLarge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.extraLarge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/extralarge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel": {
      "abstract": [
        {
          "text": "A circular area with optional curved text that ClockKit displays along the bezel of the Infograph watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicBezel"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicBezel"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicBezel",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicbezel"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular": {
      "abstract": [
        {
          "text": "A circular area that ClockKit displays on the Infograph and Infograph Modular watch faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicCircular"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicCircular"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicCircular",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphiccircular"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner": {
      "abstract": [
        {
          "text": "A curved area that fills the corners in the Infograph watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicCorner"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicCorner"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicCorner",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphiccorner"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge": {
      "abstract": [
        {
          "text": "A large square area that ClockKit displays on the X-Large watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicExtraLarge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicExtraLarge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicextralarge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular": {
      "abstract": [
        {
          "text": "A large rectangular area that ClockKit displays in the center of the Infograph Modular watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicRectangular"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicRectangular"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicRectangular",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicrectangular"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3667212": {
      "alt": "Diagram showing the size and position of a graphic extra large complication.",
      "identifier": "media-3667212",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c6ff466a49d7b5db89d3b67b4e08c45a/media-3667212@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphic",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular"
      ],
      "title": "Graphic"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplicationFamilyGraphicExtraLarge"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphic",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular"
              ],
              "title": "Graphic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLKComplicationFamilyGraphicExtraLarge"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/title",
          "value": "CLKComplicationFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicExtraLarge/title",
          "value": "CLKComplicationFamilyGraphicExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCorner/title",
          "value": "CLKComplicationFamilyGraphicCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCircular/title",
          "value": "CLKComplicationFamilyGraphicCircular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCircular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicCircular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1extraLarge/title",
          "value": "CLKComplicationFamilyExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1extraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicRectangular/title",
          "value": "CLKComplicationFamilyGraphicRectangular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicRectangular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicRectangular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicBezel/title",
          "value": "CLKComplicationFamilyGraphicBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicBezel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicBezel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationfamily/graphicextralarge"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationfamily/graphicextralarge"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
