{
  "abstract": [
    {
      "text": "The raw usage code 74 (decimal)/4A (hexadecimal).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardHome"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIKeyboardHIDUsage@UIKeyboardHIDUsageKeyboardHome",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "keyboardHome"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIKeyboardHIDUsageKeyboardHome"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIKeyboardHIDUsage.keyboardHome"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "keyboardHome"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage": {
      "abstract": [
        {
          "text": "A set of HID usage codes that identify the keys of a USB keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteForward": {
      "abstract": [
        {
          "text": "The raw usage code 76 (decimal)/4C (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardDeleteForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardDeleteForward"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardDeleteForward",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboarddeleteforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteOrBackspace": {
      "abstract": [
        {
          "text": "The raw usage code 42 (decimal)/2A (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardDeleteOrBackspace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteOrBackspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardDeleteOrBackspace"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardDeleteOrBackspace",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboarddeleteorbackspace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDownArrow": {
      "abstract": [
        {
          "text": "The raw usage code 81 (decimal)/51 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardDownArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDownArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardDownArrow"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardDownArrow",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboarddownarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEnd": {
      "abstract": [
        {
          "text": "The raw usage code 77 (decimal)/4D (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardEnd"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardEnd"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardEnd",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardend"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEscape": {
      "abstract": [
        {
          "text": "The raw usage code 41 (decimal)/29 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardEscape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEscape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardEscape"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardEscape",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardescape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardHome": {
      "abstract": [
        {
          "text": "The raw usage code 74 (decimal)/4A (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardHome"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardHome"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardHome",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardhome"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardInsert": {
      "abstract": [
        {
          "text": "The raw usage code 73 (decimal)/49 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardInsert"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardInsert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardInsert"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardInsert",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardinsert"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardLeftArrow": {
      "abstract": [
        {
          "text": "The raw usage code 80 (decimal)/50 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardLeftArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardLeftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardLeftArrow"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardLeftArrow",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardleftarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageDown": {
      "abstract": [
        {
          "text": "The raw usage code 78 (decimal)/4E (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardPageDown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardPageDown"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardPageDown",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardpagedown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageUp": {
      "abstract": [
        {
          "text": "The raw usage code 75 (decimal)/4B (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardPageUp"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardPageUp"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardPageUp",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardpageup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardReturn": {
      "abstract": [
        {
          "text": "The raw usage code 158 (decimal)/9E (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardReturn"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardReturn"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardReturn",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardreturn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardRightArrow": {
      "abstract": [
        {
          "text": "The raw usage code 79 (decimal)/4F (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardRightArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardRightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardRightArrow"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardRightArrow",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardrightarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardTab": {
      "abstract": [
        {
          "text": "The raw usage code 43 (decimal)/2B (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardTab"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardTab"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardTab",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardtab"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardUpArrow": {
      "abstract": [
        {
          "text": "The raw usage code 82 (decimal)/52 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardUpArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardUpArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardUpArrow"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardUpArrow",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboarduparrow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardLeftArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardRightArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardUpArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDownArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageUp",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageDown",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEnd",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteForward",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteOrBackspace",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEscape",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardInsert",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardReturn",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardTab"
      ],
      "title": "Navigation keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIKeyboardHIDUsageKeyboardHome"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardLeftArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardRightArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardUpArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDownArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageUp",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardPageDown",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEnd",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteForward",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardDeleteOrBackspace",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardEscape",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardInsert",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardReturn",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardTab"
              ],
              "title": "Navigation keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIKeyboardHIDUsageKeyboardHome"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardEscape/title",
          "value": "UIKeyboardHIDUsageKeyboardEscape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardEscape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardEscape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardTab/title",
          "value": "UIKeyboardHIDUsageKeyboardTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardEnd/title",
          "value": "UIKeyboardHIDUsageKeyboardEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardInsert/title",
          "value": "UIKeyboardHIDUsageKeyboardInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardInsert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardInsert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardReturn/title",
          "value": "UIKeyboardHIDUsageKeyboardReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardDeleteOrBackspace/title",
          "value": "UIKeyboardHIDUsageKeyboardDeleteOrBackspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardDeleteOrBackspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardDeleteOrBackspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardLeftArrow/title",
          "value": "UIKeyboardHIDUsageKeyboardLeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardLeftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardLeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/title",
          "value": "UIKeyboardHIDUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardDownArrow/title",
          "value": "UIKeyboardHIDUsageKeyboardDownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardDownArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardDownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardRightArrow/title",
          "value": "UIKeyboardHIDUsageKeyboardRightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardRightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardRightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardUpArrow/title",
          "value": "UIKeyboardHIDUsageKeyboardUpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardUpArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardUpArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardHome/title",
          "value": "UIKeyboardHIDUsageKeyboardHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardPageDown/title",
          "value": "UIKeyboardHIDUsageKeyboardPageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardPageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardPageDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardPageUp/title",
          "value": "UIKeyboardHIDUsageKeyboardPageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardPageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardPageUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardDeleteForward/title",
          "value": "UIKeyboardHIDUsageKeyboardDeleteForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardDeleteForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardDeleteForward"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikeyboardhidusage/keyboardhome"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikeyboardhidusage/keyboardhome"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
