{
  "abstract": [
    {
      "text": "The raw usage code 30 (decimal)/1E (hexadecimal).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIKeyboardHIDUsage@UIKeyboardHIDUsageKeyboard1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "keyboard1"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIKeyboardHIDUsageKeyboard1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIKeyboardHIDUsage.keyboard1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "keyboard1"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage": {
      "abstract": [
        {
          "text": "A set of HID usage codes that identify the keys of a USB keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard0": {
      "abstract": [
        {
          "text": "The raw usage code 39 (decimal)/27 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard0"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard0"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard0",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard0"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard1": {
      "abstract": [
        {
          "text": "The raw usage code 30 (decimal)/1E (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard1"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard1"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard1",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard1"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard2": {
      "abstract": [
        {
          "text": "The raw usage code 31 (decimal)/1F (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard2"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard2"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard2",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard2"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard3": {
      "abstract": [
        {
          "text": "The raw usage code 32 (decimal)/20 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard3"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard3"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard3",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard3"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard4": {
      "abstract": [
        {
          "text": "The raw usage code 33 (decimal)/21 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard4"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard4"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard4",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard4"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard5": {
      "abstract": [
        {
          "text": "The raw usage code 34 (decimal)/22 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard5"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard5"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard5",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard6": {
      "abstract": [
        {
          "text": "The raw usage code 35 (decimal)/23 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard6"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard6"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard6",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard6"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard7": {
      "abstract": [
        {
          "text": "The raw usage code 36 (decimal)/24 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard7"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard7"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard7",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard7"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard8": {
      "abstract": [
        {
          "text": "The raw usage code 37 (decimal)/25 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard8"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard8"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard8",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard8"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard9": {
      "abstract": [
        {
          "text": "The raw usage code 38 (decimal)/26 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboard9"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboard9"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboard9",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboard9"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Numerical-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard0",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard2",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard3",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard4",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard5",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard6",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard7",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard8",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard9"
      ],
      "title": "Numerical keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIKeyboardHIDUsageKeyboard1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Numerical-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard0",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard2",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard3",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard4",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard5",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard6",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard7",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard8",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboard9"
              ],
              "title": "Numerical keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIKeyboardHIDUsageKeyboard1"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard5/title",
          "value": "UIKeyboardHIDUsageKeyboard5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard3/title",
          "value": "UIKeyboardHIDUsageKeyboard3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard8/title",
          "value": "UIKeyboardHIDUsageKeyboard8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard7/title",
          "value": "UIKeyboardHIDUsageKeyboard7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard4/title",
          "value": "UIKeyboardHIDUsageKeyboard4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard0/title",
          "value": "UIKeyboardHIDUsageKeyboard0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/title",
          "value": "UIKeyboardHIDUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard1/title",
          "value": "UIKeyboardHIDUsageKeyboard1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard2/title",
          "value": "UIKeyboardHIDUsageKeyboard2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard6/title",
          "value": "UIKeyboardHIDUsageKeyboard6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard9/title",
          "value": "UIKeyboardHIDUsageKeyboard9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboard9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboard9"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikeyboardhidusage/keyboard1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikeyboardhidusage/keyboard1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
