{
  "abstract": [
    {
      "text": "The raw usage code 7 (decimal)/07 (hexadecimal).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIKeyboardHIDUsage@UIKeyboardHIDUsageKeyboardD",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "keyboardD"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIKeyboardHIDUsageKeyboardD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIKeyboardHIDUsage.keyboardD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "keyboardD"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage": {
      "abstract": [
        {
          "text": "A set of HID usage codes that identify the keys of a USB keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsage"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardA": {
      "abstract": [
        {
          "text": "The raw usage code 4 (decimal)/04 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardA"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardA"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardA",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboarda"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardB": {
      "abstract": [
        {
          "text": "The raw usage code 5 (decimal)/05 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardB"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardB"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardB",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardb"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardC": {
      "abstract": [
        {
          "text": "The raw usage code 6 (decimal)/06 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardC"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardC"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardC",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardc"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardD": {
      "abstract": [
        {
          "text": "The raw usage code 7 (decimal)/07 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardD"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardD"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardD",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardd"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardE": {
      "abstract": [
        {
          "text": "The raw usage code 8 (decimal)/08 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardE"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardE"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardE",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboarde"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardF": {
      "abstract": [
        {
          "text": "The raw usage code 9 (decimal)/09 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardF"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardF"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardF",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardf"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardG": {
      "abstract": [
        {
          "text": "The raw usage code 10 (decimal)/0A (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardG"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardG"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardG",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardg"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardH": {
      "abstract": [
        {
          "text": "The raw usage code 11 (decimal)/0B (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardH"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardH"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardH",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardh"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardI": {
      "abstract": [
        {
          "text": "The raw usage code 12 (decimal)/0C (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardI"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardI"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardI",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardi"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardJ": {
      "abstract": [
        {
          "text": "The raw usage code 13 (decimal)/0D (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardJ"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardJ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardJ"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardJ",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardj"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardK": {
      "abstract": [
        {
          "text": "The raw usage code 14 (decimal)/0E (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardK"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardK"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardK",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardk"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardL": {
      "abstract": [
        {
          "text": "The raw usage code 15 (decimal)/0F (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardL"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardL"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardL",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardM": {
      "abstract": [
        {
          "text": "The raw usage code 16 (decimal)/10 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardM"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardM"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardM",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardm"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardN": {
      "abstract": [
        {
          "text": "The raw usage code 17 (decimal)/11 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardN"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardN",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardO": {
      "abstract": [
        {
          "text": "The raw usage code 18 (decimal)/12 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardO"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardO"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardO",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardP": {
      "abstract": [
        {
          "text": "The raw usage code 19 (decimal)/13 (hexadecimal).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardP"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardHIDUsageKeyboardP"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardHIDUsage.keyboardP",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardhidusage/keyboardp"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Alphabetical-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardA",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardB",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardC",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardE",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardF",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardG",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardH",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardI",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardJ",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardK",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardL",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardM",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardN",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardO",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardP"
      ],
      "title": "Alphabetical keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIKeyboardHIDUsageKeyboardD"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Alphabetical-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardA",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardB",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardC",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardE",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardF",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardG",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardH",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardI",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardJ",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardK",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardL",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardM",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardN",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardO",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardHIDUsage/keyboardP"
              ],
              "title": "Alphabetical keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIKeyboardHIDUsageKeyboardD"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardK/title",
          "value": "UIKeyboardHIDUsageKeyboardK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardF/title",
          "value": "UIKeyboardHIDUsageKeyboardF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardJ/title",
          "value": "UIKeyboardHIDUsageKeyboardJ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardJ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardJ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardA/title",
          "value": "UIKeyboardHIDUsageKeyboardA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardM/title",
          "value": "UIKeyboardHIDUsageKeyboardM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardD/title",
          "value": "UIKeyboardHIDUsageKeyboardD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardB/title",
          "value": "UIKeyboardHIDUsageKeyboardB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardL/title",
          "value": "UIKeyboardHIDUsageKeyboardL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardN/title",
          "value": "UIKeyboardHIDUsageKeyboardN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardI/title",
          "value": "UIKeyboardHIDUsageKeyboardI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardE/title",
          "value": "UIKeyboardHIDUsageKeyboardE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardO/title",
          "value": "UIKeyboardHIDUsageKeyboardO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/title",
          "value": "UIKeyboardHIDUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardP/title",
          "value": "UIKeyboardHIDUsageKeyboardP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardH/title",
          "value": "UIKeyboardHIDUsageKeyboardH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardG/title",
          "value": "UIKeyboardHIDUsageKeyboardG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardC/title",
          "value": "UIKeyboardHIDUsageKeyboardC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardHIDUsage~1keyboardC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardHIDUsageKeyboardC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikeyboardhidusage/keyboardd"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikeyboardhidusage/keyboardd"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
