{
  "abstract": [
    {
      "text": "The second user-definable type for a variant of concern.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ENVariantOfConcernType@ENVariantOfConcernType2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "type2"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENVariantOfConcernType2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ENVariantOfConcernType.type2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType": {
      "abstract": [
        {
          "text": "A set of user-definable types that indicate variants of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1": {
      "abstract": [
        {
          "text": "The first user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type1"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType1"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type1",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type1"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2": {
      "abstract": [
        {
          "text": "The second user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType2"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type2",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type2"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3": {
      "abstract": [
        {
          "text": "The third user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type3"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType3"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type3",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type3"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4": {
      "abstract": [
        {
          "text": "The fourth user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type4"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType4"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type4",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type4"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown": {
      "abstract": [
        {
          "text": "The unknown type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeUnknown"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.typeUnknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/typeunknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Defined-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown"
      ],
      "title": "User-Defined Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENVariantOfConcernType2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Defined-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown"
              ],
              "title": "User-Defined Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ENVariantOfConcernType2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type2/title",
          "value": "ENVariantOfConcernType2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type1/title",
          "value": "ENVariantOfConcernType1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType/title",
          "value": "ENVariantOfConcernType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type3/title",
          "value": "ENVariantOfConcernType3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type4/title",
          "value": "ENVariantOfConcernType4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1typeUnknown/title",
          "value": "ENVariantOfConcernTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1typeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernTypeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/envariantofconcerntype/type2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/envariantofconcerntype/type2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
