{
  "abstract": [
    {
      "text": "FSKit recognizes the resource, but the resource isn’t usable.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSError",
        "doc://FSKit/documentation/FSKit/FSError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnusable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@FSErrorCode@FSErrorResourceUnusable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resourceUnusable"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FSErrorResourceUnusable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "FSError.Code.resourceUnusable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resourceUnusable"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, this error occurs when a resource uses a file system’s internal feature flags.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If the only modules that support the file system don’t support those feature flags, this code indicates an unusable resource.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The error tells the person using the module why the resource isn’t usable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSError": {
      "abstract": [
        {
          "text": "An error encountered when performing an FSKit operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSError"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSError"
        }
      ],
      "role": "symbol",
      "title": "FSError",
      "type": "topic",
      "url": "/documentation/fskit/fserror"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code": {
      "abstract": [
        {
          "text": "A code that indicates a specific FSKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/invalidDirectoryCookie": {
      "abstract": [
        {
          "text": "While enumerating a directory, the given cookie didn’t resolve to a valid directory entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDirectoryCookie"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/invalidDirectoryCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorInvalidDirectoryCookie"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.invalidDirectoryCookie",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/invaliddirectorycookie"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/moduleLoadFailed": {
      "abstract": [
        {
          "text": "The module failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moduleLoadFailed"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/moduleLoadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorModuleLoadFailed"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.moduleLoadFailed",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/moduleloadfailed"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/resourceDamaged": {
      "abstract": [
        {
          "text": "The resource is damaged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceDamaged"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/resourceDamaged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorResourceDamaged"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.resourceDamaged",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/resourcedamaged"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnrecognized": {
      "abstract": [
        {
          "text": "FSKit didn’t recognize the resource, and probing failed to find a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUnrecognized"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnrecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorResourceUnrecognized"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.resourceUnrecognized",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/resourceunrecognized"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnusable": {
      "abstract": [
        {
          "text": "FSKit recognizes the resource, but the resource isn’t usable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceUnusable"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnusable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorResourceUnusable"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.resourceUnusable",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/resourceunusable"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationInProgress": {
      "abstract": [
        {
          "text": "An operation is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOperationInProgress"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorStatusOperationInProgress"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.statusOperationInProgress",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/statusoperationinprogress"
    },
    "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationPaused": {
      "abstract": [
        {
          "text": "An operation is paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusOperationPaused"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationPaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSErrorStatusOperationPaused"
        }
      ],
      "role": "symbol",
      "title": "FSError.Code.statusOperationPaused",
      "type": "topic",
      "url": "/documentation/fskit/fserror/code/statusoperationpaused"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-errors",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSError/Code/invalidDirectoryCookie",
        "doc://FSKit/documentation/FSKit/FSError/Code/moduleLoadFailed",
        "doc://FSKit/documentation/FSKit/FSError/Code/resourceDamaged",
        "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnrecognized",
        "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationInProgress",
        "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationPaused"
      ],
      "title": "Identifying errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSErrorResourceUnusable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorResourceUnusable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit",
                "doc://FSKit/documentation/FSKit/FSError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-errors",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSError/Code/invalidDirectoryCookie",
                "doc://FSKit/documentation/FSKit/FSError/Code/moduleLoadFailed",
                "doc://FSKit/documentation/FSKit/FSError/Code/resourceDamaged",
                "doc://FSKit/documentation/FSKit/FSError/Code/resourceUnrecognized",
                "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationInProgress",
                "doc://FSKit/documentation/FSKit/FSError/Code/statusOperationPaused"
              ],
              "title": "Identifying errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "FSErrorResourceUnusable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1resourceUnusable/title",
          "value": "FSErrorResourceUnusable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1resourceUnusable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorResourceUnusable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1resourceUnrecognized/title",
          "value": "FSErrorResourceUnrecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1resourceUnrecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorResourceUnrecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1resourceDamaged/title",
          "value": "FSErrorResourceDamaged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1resourceDamaged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorResourceDamaged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1statusOperationInProgress/title",
          "value": "FSErrorStatusOperationInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1statusOperationInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorStatusOperationInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1invalidDirectoryCookie/title",
          "value": "FSErrorInvalidDirectoryCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1invalidDirectoryCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorInvalidDirectoryCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1statusOperationPaused/title",
          "value": "FSErrorStatusOperationPaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1statusOperationPaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorStatusOperationPaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/title",
          "value": "FSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1moduleLoadFailed/title",
          "value": "FSErrorModuleLoadFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSError~1Code~1moduleLoadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSErrorModuleLoadFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fserror/code/resourceunusable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fserror/code/resourceunusable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
