{
  "abstract": [
    {
      "text": "The currently selected functional unit on the scanner.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ICScannerDevice(py)selectedFunctionalUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "selectedFunctionalUnit"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ICScannerFunctionalUnit",
        "text": "ICScannerFunctionalUnit"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "selectedFunctionalUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "selectedFunctionalUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "selectedFunctionalUnit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ICScannerFunctionalUnit",
              "text": "ICScannerFunctionalUnit"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice": {
      "abstract": [
        {
          "text": "An object that represents a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerDevice"
        }
      ],
      "role": "symbol",
      "title": "ICScannerDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes": {
      "abstract": [
        {
          "text": "An array of functional unit types available on this scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableFunctionalUnitTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableFunctionalUnitTypes"
        }
      ],
      "role": "symbol",
      "title": "availableFunctionalUnitTypes",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/availablefunctionalunittypes"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)": {
      "abstract": [
        {
          "text": "Requests to select a functional unit on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSelect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICScannerFunctionalUnitType",
          "text": "ICScannerFunctionalUnitType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestSelectFunctionalUnit:"
        }
      ],
      "role": "symbol",
      "title": "requestSelect(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/requestselect(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit": {
      "abstract": [
        {
          "text": "The currently selected functional unit on the scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedFunctionalUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICScannerFunctionalUnit",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/selectedFunctionalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedFunctionalUnit"
        }
      ],
      "role": "symbol",
      "title": "selectedFunctionalUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerdevice/selectedfunctionalunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit": {
      "abstract": [
        {
          "text": "An abstract class that represents a scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnit"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnit",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunit"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState": {
      "abstract": [
        {
          "text": "Flags to indicate the state of the scanner functional unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitState"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitState"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitState",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitstate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType": {
      "abstract": [
        {
          "text": "The types of scanner functional units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunittype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-a-Functional-Unit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState"
      ],
      "title": "Selecting a Functional Unit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "selectedFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-a-Functional-Unit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/availableFunctionalUnitTypes",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerDevice/requestSelect(_:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitType",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitState"
              ],
              "title": "Selecting a Functional Unit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnit",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ICScannerFunctionalUnit",
                    "text": "ICScannerFunctionalUnit"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "selectedFunctionalUnit"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1availableFunctionalUnitTypes/title",
          "value": "availableFunctionalUnitTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1availableFunctionalUnitTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableFunctionalUnitTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/title",
          "value": "ICScannerFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1selectedFunctionalUnit/title",
          "value": "selectedFunctionalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1selectedFunctionalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedFunctionalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitState/title",
          "value": "ICScannerFunctionalUnitState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/title",
          "value": "ICScannerDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestSelect(_:)/title",
          "value": "requestSelectFunctionalUnit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerDevice~1requestSelect(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestSelectFunctionalUnit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitType/title",
          "value": "ICScannerFunctionalUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdevice/selectedfunctionalunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerdevice/selectedfunctionalunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
