{
  "abstract": [
    {
      "text": "Ends the generation of playback notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/endGeneratingPlaybackNotifications()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPMusicPlayerController(im)endGeneratingPlaybackNotifications",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "endGeneratingPlaybackNotifications"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "endGeneratingPlaybackNotifications"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "endGeneratingPlaybackNotifications()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "endGeneratingPlaybackNotifications"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController": {
      "abstract": [
        {
          "text": "An object that plays audio media items from the device’s Music app library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMusicPlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()": {
      "abstract": [
        {
          "text": "Starts the generation of playback notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginGeneratingPlaybackNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginGeneratingPlaybackNotifications"
        }
      ],
      "role": "symbol",
      "title": "beginGeneratingPlaybackNotifications()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller/begingeneratingplaybacknotifications()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/endGeneratingPlaybackNotifications()": {
      "abstract": [
        {
          "text": "Ends the generation of playback notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endGeneratingPlaybackNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/endGeneratingPlaybackNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endGeneratingPlaybackNotifications"
        }
      ],
      "role": "symbol",
      "title": "endGeneratingPlaybackNotifications()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontroller/endgeneratingplaybacknotifications()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerNowPlayingItemDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the currently playing media item has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerControllerNowPlayingItemDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerNowPlayingItemDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMusicPlayerControllerNowPlayingItemDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontrollernowplayingitemdidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerPlaybackStateDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the playback state changes programmatically or by user action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerControllerPlaybackStateDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerPlaybackStateDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMusicPlayerControllerPlaybackStateDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontrollerplaybackstatedidchangenotification"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerVolumeDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the audio playback volume for the music player has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPMusicPlayerControllerVolumeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerVolumeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPMusicPlayerControllerVolumeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplayercontrollervolumedidchangenotification"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Using-music-player-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()"
      ],
      "title": "Using music player notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "endGeneratingPlaybackNotifications"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endGeneratingPlaybackNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Using-music-player-notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerController/beginGeneratingPlaybackNotifications()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerPlaybackStateDidChangeNotification",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerNowPlayingItemDidChangeNotification",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlayerControllerVolumeDidChangeNotification"
              ],
              "title": "Using music player notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "endGeneratingPlaybackNotifications"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/title",
          "value": "MPMusicPlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1beginGeneratingPlaybackNotifications()/title",
          "value": "beginGeneratingPlaybackNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1beginGeneratingPlaybackNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginGeneratingPlaybackNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1endGeneratingPlaybackNotifications()/title",
          "value": "endGeneratingPlaybackNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlayerController~1endGeneratingPlaybackNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endGeneratingPlaybackNotifications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmusicplayercontroller/endgeneratingplaybacknotifications()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmusicplayercontroller/endgeneratingplaybacknotifications()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
