{
  "abstract": [
    {
      "text": "Constants for names of directional pad elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/input"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Directional Gamepad Input Names"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad": {
      "abstract": [
        {
          "text": "A profile that supports only the directional pad, without motion or rotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionalGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionalGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionalGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionalgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCardinalDpad": {
      "abstract": [
        {
          "text": "The name of the controller’s optional secondary directional pad element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDirectionalCardinalDpad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCardinalDpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputDirectionalCardinalDpad"
        }
      ],
      "role": "symbol",
      "title": "GCInputDirectionalCardinalDpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdirectionalcardinaldpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCenterButton": {
      "abstract": [
        {
          "text": "The name of the controller’s optional button on the directional gamepad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDirectionalCenterButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCenterButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputDirectionalCenterButton"
        }
      ],
      "role": "symbol",
      "title": "GCInputDirectionalCenterButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdirectionalcenterbutton"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalDpad": {
      "abstract": [
        {
          "text": "The name of the controller’s primary directional pad element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDirectionalDpad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalDpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputDirectionalDpad"
        }
      ],
      "role": "symbol",
      "title": "GCInputDirectionalDpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdirectionaldpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalTouchSurfaceButton": {
      "abstract": [
        {
          "text": "The name of the controller’s touch surface button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDirectionalTouchSurfaceButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalTouchSurfaceButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputDirectionalTouchSurfaceButton"
        }
      ],
      "role": "symbol",
      "title": "GCInputDirectionalTouchSurfaceButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdirectionaltouchsurfacebutton"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input element name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputelementname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName": {
      "abstract": [
        {
          "text": "A type-safe name for accessing elements of a physical input element collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementTypedName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementtypedname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of DualShock 4 elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DualShock controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/dualshock-controller-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of extended gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/extended-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/input": {
      "abstract": [
        {
          "text": "Receive controller input in the way that best integrates with the flow of your game or game engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input",
      "type": "topic",
      "url": "/documentation/gamecontroller/input"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of micro gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Micro gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/micro-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of Xbox elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Xbox controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/xbox-controller-input-names"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names"
      ],
      "title": "Element names"
    }
  ],
  "topicSections": [
    {
      "anchor": "Directional-Pad-Names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalDpad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCardinalDpad"
      ],
      "title": "Directional Pad Names"
    },
    {
      "anchor": "Directional-Pad-Button-Names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalTouchSurfaceButton",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCenterButton"
      ],
      "title": "Directional Pad Button Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Directional-Pad-Names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalDpad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCardinalDpad"
              ],
              "title": "Directional Pad Names"
            },
            {
              "anchor": "Directional-Pad-Button-Names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalTouchSurfaceButton",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionalCenterButton"
              ],
              "title": "Directional Pad Button Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names"
              ],
              "title": "Element names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalDpad/title",
          "value": "GCInputDirectionalDpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalDpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputDirectionalDpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalTouchSurfaceButton/title",
          "value": "GCInputDirectionalTouchSurfaceButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalTouchSurfaceButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputDirectionalTouchSurfaceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalCardinalDpad/title",
          "value": "GCInputDirectionalCardinalDpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalCardinalDpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputDirectionalCardinalDpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionalGamepad/title",
          "value": "GCDirectionalGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionalGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionalGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionalGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionalGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalCenterButton/title",
          "value": "GCInputDirectionalCenterButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputDirectionalCenterButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputDirectionalCenterButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/directional-gamepad-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/directional-gamepad-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
