{
  "abstract": [
    {
      "text": "Constants for names of DualShock 4 elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/input"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DualShock controller input names"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants as the keys when accessing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " elements by name using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, ",
              "type": "text"
            },
            {
              "code": "subscript(_:)",
              "type": "codeVoice"
            },
            {
              "text": " notation, or similar ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the DualShock 4 controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDualShockGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDualShockGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCDualShockGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualshockgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadButton-47b5w": {
      "abstract": [
        {
          "text": "The name of the button functionality of the DualShock 4 touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputDualShockTouchpadButton"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadButton-47b5w",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDualShockTouchpadButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdualshocktouchpadbutton-47b5w"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadButton-74k1l": {
      "abstract": [
        {
          "text": "The name of the button functionality of the DualShock 4 touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDualShockTouchpadButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadButton-74k1l",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDualShockTouchpadButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdualshocktouchpadbutton-74k1l"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadOne-55wgz": {
      "abstract": [
        {
          "text": "The name of the first finger element to touch down on the DualShock 4 touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDualShockTouchpadOne"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadOne-55wgz",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDualShockTouchpadOne",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdualshocktouchpadone-55wgz"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadOne-5u54s": {
      "abstract": [
        {
          "text": "The name of the first finger element to touch down on the DualShock 4 touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputDualShockTouchpadOne"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadOne-5u54s",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDualShockTouchpadOne",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdualshocktouchpadone-5u54s"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadTwo-38d95": {
      "abstract": [
        {
          "text": "The name of the second finger element to touch down on the DualShock 4 touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputDualShockTouchpadTwo"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadTwo-38d95",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDualShockTouchpadTwo",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdualshocktouchpadtwo-38d95"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadTwo-5f8r9": {
      "abstract": [
        {
          "text": "The name of the second finger element to touch down on the DualShock 4 touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDualShockTouchpadTwo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadTwo-5f8r9",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDualShockTouchpadTwo",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdualshocktouchpadtwo-5f8r9"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input element name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputelementname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName": {
      "abstract": [
        {
          "text": "A type-safe name for accessing elements of a physical input element collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementTypedName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementtypedname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile": {
      "abstract": [
        {
          "text": "The base class for controller profiles that support physical buttons, thumbsticks, and directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements": {
      "abstract": [
        {
          "text": "The elements in the profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allElements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerElement",
          "text": "GCControllerElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allElements"
        }
      ],
      "role": "symbol",
      "title": "allElements",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile/allelements"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of directional pad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Directional Gamepad Input Names",
      "type": "topic",
      "url": "/documentation/gamecontroller/directional-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of extended gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/extended-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/input": {
      "abstract": [
        {
          "text": "Receive controller input in the way that best integrates with the flow of your game or game engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input",
      "type": "topic",
      "url": "/documentation/gamecontroller/input"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of micro gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Micro gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/micro-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of Xbox elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Xbox controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/xbox-controller-input-names"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
      ],
      "title": "Element names"
    }
  ],
  "topicSections": [
    {
      "anchor": "DualShock-controller-button-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadButton-74k1l",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadOne-55wgz",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadTwo-5f8r9"
      ],
      "title": "DualShock controller button names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "DualShock-controller-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadButton-47b5w",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadOne-5u54s",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDualShockTouchpadTwo-38d95"
              ],
              "title": "DualShock controller button names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
              ],
              "title": "Element names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualShockGamepad/title",
          "value": "GCDualShockGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualShockGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualShockGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualShockGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualShockGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/title",
          "value": "GCPhysicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1allElements/title",
          "value": "allElements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1allElements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allElements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/dualshock-controller-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/dualshock-controller-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
