{
  "abstract": [
    {
      "text": "Constants for names of extended gamepad elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/input"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Extended gamepad input names"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants as the keys when accessing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " elements by name using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, ",
              "type": "text"
            },
            {
              "code": "subscript(_:)",
              "type": "codeVoice"
            },
            {
              "text": " notation, or similar ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the extended set of gamepad controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputArcadeButtonName": {
      "abstract": [
        {
          "text": "Returns the name of the arcade stick button at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputArcadeButtonName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputArcadeButtonName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputArcadeButtonName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputarcadebuttonname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputBackLeftButton": {
      "abstract": [
        {
          "text": "Returns the name of the back left button at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputBackLeftButton"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputBackLeftButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputBackLeftButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbackleftbutton"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputBackRightButton": {
      "abstract": [
        {
          "text": "Returns the name of the back right button at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputBackRightButton"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputBackRightButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputBackRightButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbackrightbutton"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonA-8z15w": {
      "abstract": [
        {
          "text": "The name for the controller’s A button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonA-8z15w",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttona-8z15w"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonA-a2w2": {
      "abstract": [
        {
          "text": "The name for the controller’s A button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonA"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonA-a2w2",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttona-a2w2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonB-6z361": {
      "abstract": [
        {
          "text": "The name for the controller’s B button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonB-6z361",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonB",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonb-6z361"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonB-a2w1": {
      "abstract": [
        {
          "text": "The name for the controller’s B button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonB"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonB-a2w1",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonB",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonb-a2w1"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonHome-7xxwm": {
      "abstract": [
        {
          "text": "The name of the home or logo button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonHome"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonHome-7xxwm",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonHome",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonhome-7xxwm"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonHome-8qxo4": {
      "abstract": [
        {
          "text": "The name of the home or logo button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonHome"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonHome-8qxo4",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonHome",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonhome-8qxo4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonMenu-196mn": {
      "abstract": [
        {
          "text": "The name of the primary menu button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonMenu-196mn",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonMenu",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonmenu-196mn"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonMenu-83i52": {
      "abstract": [
        {
          "text": "The name of the primary menu button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonMenu"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonMenu-83i52",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonMenu",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonmenu-83i52"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonOptions-52c9a": {
      "abstract": [
        {
          "text": "The name of the secondary menu button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonOptions"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonOptions-52c9a",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonOptions",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonoptions-52c9a"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonOptions-84kj": {
      "abstract": [
        {
          "text": "The name of the secondary menu button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonOptions-84kj",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonOptions",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonoptions-84kj"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonX-32i2z": {
      "abstract": [
        {
          "text": "The name for the controller’s X button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonX-32i2z",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonx-32i2z"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonX-a2wr": {
      "abstract": [
        {
          "text": "The name for the controller’s X button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonX"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonX-a2wr",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonx-a2wr"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonY-9x9i9": {
      "abstract": [
        {
          "text": "The name for the controller’s Y button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonY-9x9i9",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttony-9x9i9"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonY-a2wq": {
      "abstract": [
        {
          "text": "The name for the controller’s Y button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonY"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonY-a2wq",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttony-a2wq"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionPad-115st": {
      "abstract": [
        {
          "text": "The name of the directional pad element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputDirectionPad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionPad-115st",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDirectionPad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdirectionpad-115st"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionPad-8igy2": {
      "abstract": [
        {
          "text": "The name of the directional pad element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionPad-8igy2",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputDirectionPad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputdirectionpad-8igy2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input element name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputelementname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftBumper": {
      "abstract": [
        {
          "text": "The name of the additional left shoulder button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputLeftBumper"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftBumper",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftBumper",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftbumper"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftShoulder-3i8m0": {
      "abstract": [
        {
          "text": "The name of the left shoulder button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputLeftShoulder"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftShoulder-3i8m0",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftshoulder-3i8m0"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftShoulder-9assr": {
      "abstract": [
        {
          "text": "The name of the left shoulder button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputLeftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftShoulder-9assr",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftshoulder-9assr"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstick-3hlff": {
      "abstract": [
        {
          "text": "The name of the left thumbstick element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputLeftThumbstick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstick-3hlff",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftThumbstick",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftthumbstick-3hlff"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstick-5tkci": {
      "abstract": [
        {
          "text": "The name of the left thumbstick element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputLeftThumbstick"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstick-5tkci",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftThumbstick",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftthumbstick-5tkci"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstickButton-4oxvn": {
      "abstract": [
        {
          "text": "The name of the left thumbstick button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputLeftThumbstickButton"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstickButton-4oxvn",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftThumbstickButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftthumbstickbutton-4oxvn"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstickButton-7gej3": {
      "abstract": [
        {
          "text": "The name of the left thumbstick button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputLeftThumbstickButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstickButton-7gej3",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftThumbstickButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputleftthumbstickbutton-7gej3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftTrigger-4gjmx": {
      "abstract": [
        {
          "text": "The name of the left trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputLeftTrigger"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftTrigger-4gjmx",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputlefttrigger-4gjmx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftTrigger-80png": {
      "abstract": [
        {
          "text": "The name of the left trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputLeftTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftTrigger-80png",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputLeftTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputlefttrigger-80png"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightBumper": {
      "abstract": [
        {
          "text": "The name of the additional right shoulder button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputRightBumper"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightBumper",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightBumper",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightbumper"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightShoulder-513b5": {
      "abstract": [
        {
          "text": "The name of the right shoulder button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputRightShoulder"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightShoulder-513b5",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightshoulder-513b5"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightShoulder-5lcq1": {
      "abstract": [
        {
          "text": "The name of the right shoulder button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputRightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightShoulder-5lcq1",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightshoulder-5lcq1"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstick-5o085": {
      "abstract": [
        {
          "text": "The name of the right thumbstick element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputRightThumbstick"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstick-5o085",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightThumbstick",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightthumbstick-5o085"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstick-8469p": {
      "abstract": [
        {
          "text": "The name of the right thumbstick element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputRightThumbstick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstick-8469p",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightThumbstick",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightthumbstick-8469p"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstickButton-3k0ld": {
      "abstract": [
        {
          "text": "The name of the right thumbstick button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputRightThumbstickButton"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstickButton-3k0ld",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightThumbstickButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightthumbstickbutton-3k0ld"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstickButton-4to77": {
      "abstract": [
        {
          "text": "The name of the right thumbstick button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputRightThumbstickButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstickButton-4to77",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightThumbstickButton",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrightthumbstickbutton-4to77"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightTrigger-6hvns": {
      "abstract": [
        {
          "text": "The name of the right trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputRightTrigger"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightTrigger-6hvns",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrighttrigger-6hvns"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightTrigger-96vtj": {
      "abstract": [
        {
          "text": "The name of the right trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputRightTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightTrigger-96vtj",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputRightTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputrighttrigger-96vtj"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName": {
      "abstract": [
        {
          "text": "A type-safe name for accessing elements of a physical input element collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementTypedName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementtypedname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile": {
      "abstract": [
        {
          "text": "The base class for controller profiles that support physical buttons, thumbsticks, and directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements": {
      "abstract": [
        {
          "text": "The elements in the profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allElements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerElement",
          "text": "GCControllerElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allElements"
        }
      ],
      "role": "symbol",
      "title": "allElements",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile/allelements"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of directional pad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Directional Gamepad Input Names",
      "type": "topic",
      "url": "/documentation/gamecontroller/directional-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of DualShock 4 elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DualShock controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/dualshock-controller-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/input": {
      "abstract": [
        {
          "text": "Receive controller input in the way that best integrates with the flow of your game or game engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input",
      "type": "topic",
      "url": "/documentation/gamecontroller/input"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of micro gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Micro gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/micro-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of Xbox elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Xbox controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/xbox-controller-input-names"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
      ],
      "title": "Element names"
    }
  ],
  "topicSections": [
    {
      "anchor": "Shoulder-button-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftShoulder-9assr",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightShoulder-5lcq1"
      ],
      "title": "Shoulder button names"
    },
    {
      "anchor": "Trigger-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftTrigger-80png",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightTrigger-96vtj"
      ],
      "title": "Trigger names"
    },
    {
      "anchor": "Face-button-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonMenu-196mn",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonHome-7xxwm",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonOptions-84kj",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonA-8z15w",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonB-6z361",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonX-32i2z",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonY-9x9i9"
      ],
      "title": "Face button names"
    },
    {
      "anchor": "Directional-pad-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionPad-115st"
      ],
      "title": "Directional pad names"
    },
    {
      "anchor": "Thumbstick-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstick-3hlff",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstick-8469p",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstickButton-7gej3",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstickButton-4to77"
      ],
      "title": "Thumbstick names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Shoulder-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftShoulder-3i8m0",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightShoulder-513b5",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftBumper",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightBumper"
              ],
              "title": "Shoulder button names"
            },
            {
              "anchor": "Trigger-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftTrigger-4gjmx",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightTrigger-6hvns"
              ],
              "title": "Trigger names"
            },
            {
              "anchor": "Face-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonMenu-83i52",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonHome-8qxo4",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonOptions-52c9a",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonA-a2w2",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonB-a2w1",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonX-a2wr",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonY-a2wq"
              ],
              "title": "Face button names"
            },
            {
              "anchor": "Directional-pad-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputDirectionPad-8igy2"
              ],
              "title": "Directional pad names"
            },
            {
              "anchor": "Thumbstick-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstick-5tkci",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstick-5o085",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputLeftThumbstickButton-4oxvn",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputRightThumbstickButton-3k0ld"
              ],
              "title": "Thumbstick names"
            },
            {
              "anchor": "Arcade-stick-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputArcadeButtonName"
              ],
              "title": "Arcade stick button names"
            },
            {
              "anchor": "Additional-back-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputBackLeftButton",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputBackRightButton"
              ],
              "title": "Additional back button names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
              ],
              "title": "Element names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1allElements/title",
          "value": "allElements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1allElements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allElements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/title",
          "value": "GCPhysicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/title",
          "value": "GCExtendedGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/extended-gamepad-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/extended-gamepad-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
