{
  "abstract": [
    {
      "text": "The common properties of inputs that provide a normalized point in a two-dimensional coordinate system with a fixed origin.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCAxis2DInput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCAxis2DInput"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCAxis2DInput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "GCAxis2DInput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCAxis2DInput"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The normalized point with coordinates that range between ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ". The origin ",
              "type": "text"
            },
            {
              "code": "(0, 0)",
              "type": "codeVoice"
            },
            {
              "text": " represents the neutral state of the input.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput": {
      "abstract": [
        {
          "text": "The common properties of inputs that provide a normalized point in a two-dimensional coordinate system with a fixed origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxis2DInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxis2DInput"
        }
      ],
      "role": "symbol",
      "title": "GCAxis2DInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/canWrap": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the value wraps when it reaches the range’s minimum or maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canWrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/canWrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canWrap"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "canWrap",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/canwrap"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/isAnalog": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the input provides analog values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAnalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/isAnalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analog"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isAnalog",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/isanalog"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueLatency": {
      "abstract": [
        {
          "text": "The time in seconds between the last value change and the current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastValueLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastValueLatency"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lastValueLatency",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/lastvaluelatency"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueTimestamp": {
      "abstract": [
        {
          "text": "The time of the most recent value change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastValueTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastValueTimestamp"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lastValueTimestamp",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/lastvaluetimestamp"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/sources": {
      "abstract": [
        {
          "text": "One or more physical actions the user performs to manipulate the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/sources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sources"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sources",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/sources"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/value": {
      "abstract": [
        {
          "text": "The axis input represented as a normalized point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@GCPoint2",
          "text": "GCPoint2"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/value"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/valueDidChangeHandler": {
      "abstract": [
        {
          "text": "The block that the axis element calls when its value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueDidChangeHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCAxis2DInput",
          "text": "GCAxis2DInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@GCPoint2",
          "text": "GCPoint2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/valueDidChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueDidChangeHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "valueDidChangeHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxis2dinput/valuedidchangehandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xAxis": {
      "abstract": [
        {
          "text": "The input object that represents the x-axis on the directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xAxis"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCAxisInput",
          "text": "GCAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xAxis"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "xAxis",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelement/xaxis"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xyAxes": {
      "abstract": [
        {
          "text": "The location of the directional pad represented as a point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xyAxes"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCAxis2DInput",
          "text": "GCAxis2DInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xyAxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xyAxes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "xyAxes",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelement/xyaxes"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/yAxis": {
      "abstract": [
        {
          "text": "The input object that represents the y-axis on the directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yAxis"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCAxisInput",
          "text": "GCAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/yAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yAxis"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "yAxis",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelement/yaxis"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPoint2": {
      "abstract": [
        {
          "text": "A structure that represents a normalized point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPoint2"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPoint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPoint2"
        }
      ],
      "role": "symbol",
      "title": "GCPoint2",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcpoint2"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Axes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xAxis",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/yAxis",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xyAxes"
      ],
      "title": "Axes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-characteristics",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/canWrap",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/isAnalog"
      ],
      "title": "Getting the characteristics"
    },
    {
      "anchor": "Getting-the-value",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/value",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPoint2",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/valueDidChangeHandler",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueTimestamp",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueLatency"
      ],
      "title": "Getting the value"
    },
    {
      "anchor": "Getting-user-actions",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/sources"
      ],
      "title": "Getting user actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCAxis2DInput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxis2DInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxis2DInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-characteristics",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/canWrap",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/isAnalog"
              ],
              "title": "Getting the characteristics"
            },
            {
              "anchor": "Getting-the-value",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/value",
                "doc://com.apple.gamecontroller/documentation/GameController/GCPoint2",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/valueDidChangeHandler",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueTimestamp",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/lastValueLatency"
              ],
              "title": "Getting the value"
            },
            {
              "anchor": "Getting-user-actions",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxis2DInput/sources"
              ],
              "title": "Getting user actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Axes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xAxis",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/yAxis",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement/xyAxes"
              ],
              "title": "Axes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCAxis2DInput"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement~1xAxis/title",
          "value": "xAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement~1xAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1valueDidChangeHandler/title",
          "value": "valueDidChangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1valueDidChangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "valueDidChangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput/title",
          "value": "GCAxis2DInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxis2DInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxis2DInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1isAnalog/title",
          "value": "analog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1isAnalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "analog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1canWrap/title",
          "value": "canWrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1canWrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canWrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPoint2/title",
          "value": "GCPoint2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPoint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPoint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPoint2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPoint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement~1xyAxes/title",
          "value": "xyAxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement~1xyAxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xyAxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1lastValueTimestamp/title",
          "value": "lastValueTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1lastValueTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastValueTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1lastValueLatency/title",
          "value": "lastValueLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1lastValueLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastValueLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement~1yAxis/title",
          "value": "yAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement~1yAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1sources/title",
          "value": "sources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxis2DInput~1sources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sources"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcaxis2dinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcaxis2dinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
