{
  "abstract": [
    {
      "text": "A notification that posts after a controller disconnects from the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDidDisconnectNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@GCControllerDidDisconnectNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GCControllerDidDisconnectNotification"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCControllerDidDisconnectNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GCControllerDidDisconnectNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCControllerDidDisconnectNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamecontroller/documentation/GameController/adding-touch-controls-to-games-that-support-game-controllers-in-ios"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The notification object is the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that disconnects from the device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458856-gccontrollerdidconnect": {
      "abstract": [
        {
          "text": "A notification that posts after a controller connects to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "GCControllerDidConnect"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458856-gccontrollerdidconnect",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCControllerDidConnect",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1458856-gccontrollerdidconnect"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458875-gccontrollerdiddisconnect": {
      "abstract": [
        {
          "text": "A notification that posts after a controller disconnects from the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "GCControllerDidDisconnect"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458875-gccontrollerdiddisconnect",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCControllerDidDisconnect",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1458875-gccontrollerdiddisconnect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/controllers()": {
      "abstract": [
        {
          "text": "Returns the connected controllers for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controllers"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCController",
          "text": "GCController"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/controllers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controllers"
        }
      ],
      "role": "symbol",
      "title": "controllers()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/controllers()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/startWirelessControllerDiscovery(completionHandler:)": {
      "abstract": [
        {
          "text": "Starts searching for nearby wireless controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startWirelessControllerDiscovery"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/startWirelessControllerDiscovery(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startWirelessControllerDiscoveryWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "startWirelessControllerDiscovery(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/startwirelesscontrollerdiscovery(completionhandler:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/stopWirelessControllerDiscovery()": {
      "abstract": [
        {
          "text": "Stops searching for nearby wireless controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopWirelessControllerDiscovery"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/stopWirelessControllerDiscovery()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopWirelessControllerDiscovery"
        }
      ],
      "role": "symbol",
      "title": "stopWirelessControllerDiscovery()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/stopwirelesscontrollerdiscovery()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDidConnectNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a controller connects to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCControllerDidConnectNotification"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDidConnectNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCControllerDidConnectNotification",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdidconnectnotification"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDidDisconnectNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a controller disconnects from the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCControllerDidDisconnectNotification"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDidDisconnectNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCControllerDidDisconnectNotification",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdiddisconnectnotification"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/adding-touch-controls-to-games-that-support-game-controllers-in-ios": {
      "abstract": [
        {
          "text": "Use touch input and virtual controllers to make your game available to players without controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/adding-touch-controls-to-games-that-support-game-controllers-in-ios",
      "kind": "article",
      "role": "article",
      "title": "Adding touch controls to games that support game controllers in iOS",
      "type": "topic",
      "url": "/documentation/gamecontroller/adding-touch-controls-to-games-that-support-game-controllers-in-ios"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Discovering-controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/controllers()",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/startWirelessControllerDiscovery(completionHandler:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/stopWirelessControllerDiscovery()",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458856-gccontrollerdidconnect",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1458875-gccontrollerdiddisconnect",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDidConnectNotification"
      ],
      "title": "Discovering controllers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1controllers()/title",
          "value": "controllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1controllers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1stopWirelessControllerDiscovery()/title",
          "value": "stopWirelessControllerDiscovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1stopWirelessControllerDiscovery()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "stopWirelessControllerDiscovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1startWirelessControllerDiscovery(completionHandler:)/title",
          "value": "startWirelessControllerDiscoveryWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1startWirelessControllerDiscovery(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "startWirelessControllerDiscoveryWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gccontrollerdiddisconnectnotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
