{
  "abstract": [
    {
      "text": "A control element associated with a directional pad or a thumbstick.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCControllerDirectionPad",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCControllerDirectionPad"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCControllerDirectionPad"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GCControllerDirectionPad"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You get the input values for this element from its subelements. You can use either the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/xAxis",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/yAxis",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to get coordinates, or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/up",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/down",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/left",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/right",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " buttons that simulate directional pad buttons.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput": {
      "abstract": [
        {
          "text": "A control element that tracks movement along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerAxisInput"
        }
      ],
      "role": "symbol",
      "title": "GCControllerAxisInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrolleraxisinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput": {
      "abstract": [
        {
          "text": "A control element that represents a button touch or press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "role": "symbol",
      "title": "GCControllerButtonInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerbuttoninput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad": {
      "abstract": [
        {
          "text": "A control element associated with a directional pad or a thumbstick.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPad"
        }
      ],
      "role": "symbol",
      "title": "GCControllerDirectionPad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/down": {
      "abstract": [
        {
          "text": "The button element used for the negative y-axis direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "role": "symbol",
      "title": "down",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/down"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/left": {
      "abstract": [
        {
          "text": "The button element that changes the negative x-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/left"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/right": {
      "abstract": [
        {
          "text": "The button element that changes the positive x-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/right"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/setValueForXAxis(_:yAxis:)": {
      "abstract": [
        {
          "text": "Sets the input values of a snapshot of a directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValueForXAxis"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "yAxis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/setValueForXAxis(_:yAxis:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValueForXAxis:yAxis:"
        }
      ],
      "role": "symbol",
      "title": "setValueForXAxis(_:yAxis:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/setvalueforxaxis(_:yaxis:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/up": {
      "abstract": [
        {
          "text": "The button element that changes the positive y-axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "role": "symbol",
      "title": "up",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/up"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/valueChangedHandler": {
      "abstract": [
        {
          "text": "The block that the directional pad calls when the user changes its values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCControllerDirectionPadValueChangedHandler",
          "text": "GCControllerDirectionPadValueChangedHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/valueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "valueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/valuechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/xAxis": {
      "abstract": [
        {
          "text": "The x-axis element of the directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xAxis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerAxisInput",
          "text": "GCControllerAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/xAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xAxis"
        }
      ],
      "role": "symbol",
      "title": "xAxis",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/xaxis"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/yAxis": {
      "abstract": [
        {
          "text": "The y-axis element of the directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yAxis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerAxisInput",
          "text": "GCControllerAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/yAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yAxis"
        }
      ],
      "role": "symbol",
      "title": "yAxis",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad/yaxis"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPadValueChangedHandler": {
      "abstract": [
        {
          "text": "The signature for the block that executes when either axis changes values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPadValueChangedHandler"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPadValueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPadValueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "GCControllerDirectionPadValueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpadvaluechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement": {
      "abstract": [
        {
          "text": "An input for a physical control, such as a button or thumbstick.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerElement"
        }
      ],
      "role": "symbol",
      "title": "GCControllerElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad": {
      "abstract": [
        {
          "text": "A control element that represents a touch event on a touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerTouchpad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerTouchpad"
        }
      ],
      "role": "symbol",
      "title": "GCControllerTouchpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollertouchpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor": {
      "abstract": [
        {
          "text": "A control element for the cursor used as a directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceCursor"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceCursor"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceCursor",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicecursor"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger": {
      "abstract": [
        {
          "text": "A class that encapsulates the features of a DualSense adaptive trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDualSenseAdaptiveTrigger"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDualSenseAdaptiveTrigger"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseAdaptiveTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-controller-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger"
      ],
      "title": "Accessing controller elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-values-using-the-axes",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/xAxis",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/yAxis"
      ],
      "title": "Accessing values using the axes"
    },
    {
      "anchor": "Accessing-values-using-directional-buttons",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/right",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/left",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/up",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/down"
      ],
      "title": "Accessing values using directional buttons"
    },
    {
      "anchor": "Getting-change-information",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/valueChangedHandler",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPadValueChangedHandler"
      ],
      "title": "Getting change information"
    },
    {
      "anchor": "Setting-snapshot-values",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/setValueForXAxis(_:yAxis:)"
      ],
      "title": "Setting snapshot values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCControllerDirectionPad"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-values-using-the-axes",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/xAxis",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/yAxis"
              ],
              "title": "Accessing values using the axes"
            },
            {
              "anchor": "Accessing-values-using-directional-buttons",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/right",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/left",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/up",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/down"
              ],
              "title": "Accessing values using directional buttons"
            },
            {
              "anchor": "Getting-change-information",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/valueChangedHandler",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPadValueChangedHandler"
              ],
              "title": "Getting change information"
            },
            {
              "anchor": "Setting-snapshot-values",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad/setValueForXAxis(_:yAxis:)"
              ],
              "title": "Setting snapshot values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-controller-elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger"
              ],
              "title": "Accessing controller elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCControllerDirectionPad"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GCControllerElement",
                    "text": "GCControllerElement"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1xAxis/title",
          "value": "xAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1xAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPadValueChangedHandler/title",
          "value": "GCControllerDirectionPadValueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPadValueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPadValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPadValueChangedHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPadValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger/title",
          "value": "GCDualSenseAdaptiveTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1down/title",
          "value": "down"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "down"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1left/title",
          "value": "left"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "left"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1setValueForXAxis(_:yAxis:)/title",
          "value": "setValueForXAxis:yAxis:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1setValueForXAxis(_:yAxis:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValueForXAxis:yAxis:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerAxisInput/title",
          "value": "GCControllerAxisInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerAxisInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerAxisInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement/title",
          "value": "GCControllerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1right/title",
          "value": "right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerTouchpad/title",
          "value": "GCControllerTouchpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerTouchpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerTouchpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerTouchpad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerTouchpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1up/title",
          "value": "up"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "up"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1yAxis/title",
          "value": "yAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1yAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/title",
          "value": "GCControllerButtonInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceCursor/title",
          "value": "GCDeviceCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1valueChangedHandler/title",
          "value": "valueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad~1valueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "valueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/title",
          "value": "GCControllerDirectionPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gccontrollerdirectionpad"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gccontrollerdirectionpad"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
