{
  "abstract": [
    {
      "text": "An alias for a symbol name for backward compatibility with a previous SDK version.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceDirectionPad"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@GCDeviceDirectionPad",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCDeviceDirectionPad"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCDeviceDirectionPad"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "GCDeviceDirectionPad"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCDeviceDirectionPad"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GCControllerDirectionPad",
              "text": "GCControllerDirectionPad"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad": {
      "abstract": [
        {
          "text": "A control element associated with a directional pad or a thumbstick.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPad"
        }
      ],
      "role": "symbol",
      "title": "GCControllerDirectionPad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceAxisInput": {
      "abstract": [
        {
          "text": "An alias for a symbol name for backward compatibility with a previous SDK version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceAxisInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceAxisInput"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceAxisInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdeviceaxisinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceButtonInput": {
      "abstract": [
        {
          "text": "An alias for a symbol name for backward compatibility with a previous SDK version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceButtonInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceButtonInput"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceButtonInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicebuttoninput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceDirectionPad": {
      "abstract": [
        {
          "text": "An alias for a symbol name for backward compatibility with a previous SDK version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceDirectionPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceDirectionPad"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceDirectionPad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicedirectionpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceElement": {
      "abstract": [
        {
          "text": "An alias for a symbol name for backward compatibility with a previous SDK version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceElement"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdeviceelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceTouchpad": {
      "abstract": [
        {
          "text": "An alias for a symbol name for backward compatibility with a previous SDK version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceTouchpad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceTouchpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceTouchpad"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceTouchpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicetouchpad"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Aliases-for-backward-compatibility",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceAxisInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceButtonInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceTouchpad"
      ],
      "title": "Aliases for backward compatibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/title",
          "value": "GCControllerDirectionPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcdevicedirectionpad"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
