{
  "abstract": [
    {
      "text": "A protocol that defines a common interface for game input devices.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCDevice"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "GCDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCDevice"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This protocol provides common properties for game controllers, and mouse and keyboard devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice": {
      "abstract": [
        {
          "text": "A protocol that defines a common interface for game input devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevice"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevice"
        }
      ],
      "role": "symbol",
      "title": "GCDevice",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/handlerQueue": {
      "abstract": [
        {
          "text": "The dispatch queue that the framework uses to call element value change handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handlerQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/handlerQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handlerQueue"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handlerQueue",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/handlerqueue"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/physicalInputProfile": {
      "abstract": [
        {
          "text": "The device’s physical input profile, such as a controller’s extended gamepad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalInputProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCPhysicalInputProfile",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/physicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "physicalInputProfile"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "physicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/physicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory": {
      "abstract": [
        {
          "text": "The product category that identifies the type of controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productCategory"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "productCategory",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/productcategory"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName": {
      "abstract": [
        {
          "text": "The manufacturer-provided name for the device, or the user’s name for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorName"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "vendorName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/vendorname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard": {
      "abstract": [
        {
          "text": "An object that represents a physical keyboard connected to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyboard"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyboard"
        }
      ],
      "role": "symbol",
      "title": "GCKeyboard",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyboard"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMouse": {
      "abstract": [
        {
          "text": "An object that represents a physical mouse connected to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMouse"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMouse"
        }
      ],
      "role": "symbol",
      "title": "GCMouse",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmouse"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel": {
      "abstract": [
        {
          "text": "An object that represents a physical racing wheel controller connected to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCRacingWheel"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRacingWheel"
        }
      ],
      "role": "symbol",
      "title": "GCRacingWheel",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcracingwheel"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/letting-players-use-their-second-generation-siri-remote-as-a-game-controller": {
      "abstract": [
        {
          "text": "Support the second-generation Siri Remote as a game controller in your Apple TV game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/letting-players-use-their-second-generation-siri-remote-as-a-game-controller",
      "kind": "article",
      "role": "article",
      "title": "Letting players use their second-generation Siri Remote as a game controller",
      "type": "topic",
      "url": "/documentation/gamecontroller/letting-players-use-their-second-generation-siri-remote-as-a-game-controller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/product-category-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/product-category-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Product category constants",
      "type": "topic",
      "url": "/documentation/gamecontroller/product-category-constants"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/supporting-game-controllers": {
      "abstract": [
        {
          "text": "Support a physical controller or add a virtual controller to enhance how people interact with your game through haptics, lighting, and motion sensing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/supporting-game-controllers",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Game Controllers",
      "type": "topic",
      "url": "/documentation/gamecontroller/supporting-game-controllers"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMouse",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Game-controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/supporting-game-controllers",
        "doc://com.apple.gamecontroller/documentation/GameController/letting-players-use-their-second-generation-siri-remote-as-a-game-controller",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMouse"
      ],
      "title": "Game controllers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-device-information",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory",
        "doc://com.apple.gamecontroller/documentation/GameController/product-category-constants"
      ],
      "title": "Getting device information"
    },
    {
      "anchor": "Handling-input",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/handlerQueue",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/physicalInputProfile"
      ],
      "title": "Handling input"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-device-information",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory",
                "doc://com.apple.gamecontroller/documentation/GameController/product-category-constants"
              ],
              "title": "Getting device information"
            },
            {
              "anchor": "Handling-input",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/handlerQueue",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/physicalInputProfile"
              ],
              "title": "Handling input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMouse",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Game-controllers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/letting-players-use-their-second-generation-siri-remote-as-a-game-controller",
                "doc://com.apple.gamecontroller/documentation/GameController/GCController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMouse"
              ],
              "title": "Game controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCDevice"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1handlerQueue/title",
          "value": "handlerQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1handlerQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "handlerQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1vendorName/title",
          "value": "vendorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1vendorName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboard/title",
          "value": "GCKeyboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1physicalInputProfile/title",
          "value": "physicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1physicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "physicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1productCategory/title",
          "value": "productCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1productCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouse/title",
          "value": "GCMouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/title",
          "value": "GCDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRacingWheel/title",
          "value": "GCRacingWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRacingWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRacingWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRacingWheel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRacingWheel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
