{
  "abstract": [
    {
      "text": "A class that encapsulates the features of a DualSense adaptive trigger.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCDualSenseAdaptiveTrigger",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCDualSenseAdaptiveTrigger"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCDualSenseAdaptiveTrigger"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GCDualSenseAdaptiveTrigger"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "GCDualSenseAdaptiveTrigger",
              "type": "codeVoice"
            },
            {
              "text": " object allows you to specify a dynamic resistance force that the DualSense controller applies when the user pulls the trigger. For example, set the resistance to give the user the feeling of pulling back on a bow string, firing a weapon, or pulling a lever.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput": {
      "abstract": [
        {
          "text": "A control element that tracks movement along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerAxisInput"
        }
      ],
      "role": "symbol",
      "title": "GCControllerAxisInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrolleraxisinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput": {
      "abstract": [
        {
          "text": "A control element that represents a button touch or press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "role": "symbol",
      "title": "GCControllerButtonInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerbuttoninput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad": {
      "abstract": [
        {
          "text": "A control element associated with a directional pad or a thumbstick.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerDirectionPad"
        }
      ],
      "role": "symbol",
      "title": "GCControllerDirectionPad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerdirectionpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement": {
      "abstract": [
        {
          "text": "An input for a physical control, such as a button or thumbstick.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerElement"
        }
      ],
      "role": "symbol",
      "title": "GCControllerElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad": {
      "abstract": [
        {
          "text": "A control element that represents a touch event on a touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerTouchpad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerTouchpad"
        }
      ],
      "role": "symbol",
      "title": "GCControllerTouchpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollertouchpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor": {
      "abstract": [
        {
          "text": "A control element for the cursor used as a directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceCursor"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceCursor"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceCursor",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicecursor"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger": {
      "abstract": [
        {
          "text": "A class that encapsulates the features of a DualSense adaptive trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDualSenseAdaptiveTrigger"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDualSenseAdaptiveTrigger"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseAdaptiveTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Mode-swift.enum": {
      "abstract": [
        {
          "text": "The possible modes of an adaptive trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Mode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseAdaptiveTrigger.Mode",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/mode-swift.enum"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalAmplitudes": {
      "abstract": [
        {
          "text": "The amplitudes for multiple positions on a trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PositionalAmplitudes"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalAmplitudes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PositionalAmplitudes"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseAdaptiveTrigger.PositionalAmplitudes",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/positionalamplitudes"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalResistiveStrengths": {
      "abstract": [
        {
          "text": "The resistive strengths for multiple positions on a trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PositionalResistiveStrengths"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalResistiveStrengths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PositionalResistiveStrengths"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseAdaptiveTrigger.PositionalResistiveStrengths",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/positionalresistivestrengths"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Status-swift.enum": {
      "abstract": [
        {
          "text": "The possible states of an adaptive trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Status-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseAdaptiveTrigger.Status",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/status-swift.enum"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/armPosition": {
      "abstract": [
        {
          "text": "The position of the trigger’s arm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "armPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/armPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "armPosition"
        }
      ],
      "role": "symbol",
      "title": "armPosition",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/armposition"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/discretePositionCount": {
      "abstract": [
        {
          "text": "The number of discrete control positions that the DualSense adaptive triggers support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discretePositionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/discretePositionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDualSenseAdaptiveTriggerDiscretePositionCount"
        }
      ],
      "role": "symbol",
      "title": "discretePositionCount",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/discretepositioncount"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/mode-swift.property": {
      "abstract": [
        {
          "text": "The current configuration of the adaptive trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCDualSenseAdaptiveTrigger",
          "text": "GCDualSenseAdaptiveTrigger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCDualSenseAdaptiveTriggerMode",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/mode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/mode-swift.property"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedback(resistiveStrengths:)": {
      "abstract": [
        {
          "text": "Sets the mode to provide feedback with the specified strengths for each possible trigger position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeFeedback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resistiveStrengths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCDualSenseAdaptiveTrigger",
          "text": "GCDualSenseAdaptiveTrigger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCDualSenseAdaptiveTriggerPositionalResistiveStrengths",
          "text": "PositionalResistiveStrengths"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedback(resistiveStrengths:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeFeedbackWithResistiveStrengths:"
        }
      ],
      "role": "symbol",
      "title": "setModeFeedback(resistiveStrengths:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodefeedback(resistivestrengths:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedbackWithStartPosition(_:resistiveStrength:)": {
      "abstract": [
        {
          "text": "Sets the mode to provide feedback when the user depresses the trigger at the start position or at a greater value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeFeedbackWithStartPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resistiveStrength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedbackWithStartPosition(_:resistiveStrength:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeFeedbackWithStartPosition:resistiveStrength:"
        }
      ],
      "role": "symbol",
      "title": "setModeFeedbackWithStartPosition(_:resistiveStrength:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodefeedbackwithstartposition(_:resistivestrength:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeOff()": {
      "abstract": [
        {
          "text": "Sets the mode to off and stops any trigger effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeOff"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeOff()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeOff"
        }
      ],
      "role": "symbol",
      "title": "setModeOff()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodeoff()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)": {
      "abstract": [
        {
          "text": "Sets the mode to provide feedback when the user tilts the trigger between the start and the end positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeSlopeFeedback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "startPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startStrength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endStrength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeSlopeFeedbackWithStartPosition:endPosition:startStrength:endStrength:"
        }
      ],
      "role": "symbol",
      "title": "setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodeslopefeedback(startposition:endposition:startstrength:endstrength:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibration(amplitudes:frequency:)": {
      "abstract": [
        {
          "text": "Sets the mode to vibrate with the specified amplitudes for each possible trigger position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeVibration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "amplitudes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCDualSenseAdaptiveTrigger",
          "text": "GCDualSenseAdaptiveTrigger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCDualSenseAdaptiveTriggerPositionalAmplitudes",
          "text": "PositionalAmplitudes"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibration(amplitudes:frequency:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeVibrationWithAmplitudes:frequency:"
        }
      ],
      "role": "symbol",
      "title": "setModeVibration(amplitudes:frequency:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodevibration(amplitudes:frequency:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibrationWithStartPosition(_:amplitude:frequency:)": {
      "abstract": [
        {
          "text": "Sets the mode to vibrate when the user depresses the trigger at the start position or at a greater value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeVibrationWithStartPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "amplitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibrationWithStartPosition(_:amplitude:frequency:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeVibrationWithStartPosition:amplitude:frequency:"
        }
      ],
      "role": "symbol",
      "title": "setModeVibrationWithStartPosition(_:amplitude:frequency:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodevibrationwithstartposition(_:amplitude:frequency:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)": {
      "abstract": [
        {
          "text": "Sets the mode to provide feedback when the user depresses the trigger between the start and the end positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModeWeaponWithStartPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resistiveStrength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setModeWeaponWithStartPosition:endPosition:resistiveStrength:"
        }
      ],
      "role": "symbol",
      "title": "setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/setmodeweaponwithstartposition(_:endposition:resistivestrength:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/status-swift.property": {
      "abstract": [
        {
          "text": "The current status of the adaptive trigger and whether it’s applying effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCDualSenseAdaptiveTrigger",
          "text": "GCDualSenseAdaptiveTrigger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCDualSenseAdaptiveTriggerStatus",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/status-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsenseadaptivetrigger/status-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-controller-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor"
      ],
      "title": "Accessing controller elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-mode",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/mode-swift.property",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Mode-swift.enum",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeOff()"
      ],
      "title": "Getting the mode"
    },
    {
      "anchor": "Configuring-the-trigger",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedbackWithStartPosition(_:resistiveStrength:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalResistiveStrengths",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedback(resistiveStrengths:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibrationWithStartPosition(_:amplitude:frequency:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibration(amplitudes:frequency:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalAmplitudes",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)"
      ],
      "title": "Configuring the trigger"
    },
    {
      "anchor": "Getting-the-arm-position",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/armPosition",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/discretePositionCount"
      ],
      "title": "Getting the arm position"
    },
    {
      "anchor": "Checking-the-status",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/status-swift.property",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Status-swift.enum"
      ],
      "title": "Checking the status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCDualSenseAdaptiveTrigger"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-mode",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/mode-swift.property",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Mode-swift.enum",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeOff()"
              ],
              "title": "Getting the mode"
            },
            {
              "anchor": "Configuring-the-trigger",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedbackWithStartPosition(_:resistiveStrength:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalResistiveStrengths",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeFeedback(resistiveStrengths:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibrationWithStartPosition(_:amplitude:frequency:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeVibration(amplitudes:frequency:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/PositionalAmplitudes",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)"
              ],
              "title": "Configuring the trigger"
            },
            {
              "anchor": "Getting-the-arm-position",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/armPosition",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/discretePositionCount"
              ],
              "title": "Getting the arm position"
            },
            {
              "anchor": "Checking-the-status",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/status-swift.property",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseAdaptiveTrigger/Status-swift.enum"
              ],
              "title": "Checking the status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-controller-elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerAxisInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerTouchpad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCControllerDirectionPad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceCursor"
              ],
              "title": "Accessing controller elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCDualSenseAdaptiveTrigger"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
                    "text": "GCControllerButtonInput"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement/title",
          "value": "GCControllerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1PositionalResistiveStrengths/title",
          "value": "GCDualSenseAdaptiveTriggerPositionalResistiveStrengths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1PositionalResistiveStrengths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerPositionalResistiveStrengths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1PositionalResistiveStrengths/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerPositionalResistiveStrengths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeFeedback(resistiveStrengths:)/title",
          "value": "setModeFeedbackWithResistiveStrengths:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeFeedback(resistiveStrengths:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeFeedbackWithResistiveStrengths:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/title",
          "value": "GCControllerDirectionPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerDirectionPad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerDirectionPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1Mode-swift.enum/title",
          "value": "GCDualSenseAdaptiveTriggerMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1Mode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1Mode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeVibrationWithStartPosition(_:amplitude:frequency:)/title",
          "value": "setModeVibrationWithStartPosition:amplitude:frequency:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeVibrationWithStartPosition(_:amplitude:frequency:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeVibrationWithStartPosition:amplitude:frequency:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/title",
          "value": "GCControllerButtonInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerAxisInput/title",
          "value": "GCControllerAxisInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerAxisInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerAxisInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1PositionalAmplitudes/title",
          "value": "GCDualSenseAdaptiveTriggerPositionalAmplitudes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1PositionalAmplitudes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerPositionalAmplitudes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1PositionalAmplitudes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerPositionalAmplitudes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1discretePositionCount/title",
          "value": "GCDualSenseAdaptiveTriggerDiscretePositionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1discretePositionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerDiscretePositionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerTouchpad/title",
          "value": "GCControllerTouchpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerTouchpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerTouchpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerTouchpad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerTouchpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeVibration(amplitudes:frequency:)/title",
          "value": "setModeVibrationWithAmplitudes:frequency:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeVibration(amplitudes:frequency:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeVibrationWithAmplitudes:frequency:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger/title",
          "value": "GCDualSenseAdaptiveTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)/title",
          "value": "setModeSlopeFeedbackWithStartPosition:endPosition:startStrength:endStrength:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeSlopeFeedback(startPosition:endPosition:startStrength:endStrength:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeSlopeFeedbackWithStartPosition:endPosition:startStrength:endStrength:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1status-swift.property/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1status-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeOff()/title",
          "value": "setModeOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeOff()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)/title",
          "value": "setModeWeaponWithStartPosition:endPosition:resistiveStrength:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeWeaponWithStartPosition(_:endPosition:resistiveStrength:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeWeaponWithStartPosition:endPosition:resistiveStrength:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1Status-swift.enum/title",
          "value": "GCDualSenseAdaptiveTriggerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1Status-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1Status-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseAdaptiveTriggerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceCursor/title",
          "value": "GCDeviceCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1mode-swift.property/title",
          "value": "mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1mode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1armPosition/title",
          "value": "armPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1armPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "armPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeFeedbackWithStartPosition(_:resistiveStrength:)/title",
          "value": "setModeFeedbackWithStartPosition:resistiveStrength:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseAdaptiveTrigger~1setModeFeedbackWithStartPosition(_:resistiveStrength:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setModeFeedbackWithStartPosition:resistiveStrength:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcdualsenseadaptivetrigger"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcdualsenseadaptivetrigger"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
