{
  "abstract": [
    {
      "text": "A structure that holds a snapshot of an extended gamepad controller’s input data.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the -[GCController controllerWithExtendedGamepad] method instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@GCExtendedGamepadSnapShotDataV100",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCExtendedGamepadSnapShotDataV100"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCExtendedGamepadSnapShotDataV100"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "7.0",
        "message": "Use the -[GCController controllerWithExtendedGamepad] method instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "7.0",
        "message": "Use the -[GCController controllerWithExtendedGamepad] method instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use the -[GCController controllerWithExtendedGamepad] method instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "Use the -[GCController controllerWithExtendedGamepad] method instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "message": "Use the -[GCController controllerWithExtendedGamepad] method instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use the -[GCController controllerWithExtendedGamepad] method instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "GCExtendedGamepadSnapShotDataV100"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapShotDataV100"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100": {
      "abstract": [
        {
          "text": "A structure that holds a snapshot of an extended gamepad controller’s input data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapShotDataV100"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapShotDataV100"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepadSnapShotDataV100",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonA": {
      "abstract": [
        {
          "text": "The value of the A button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonA"
        }
      ],
      "role": "symbol",
      "title": "buttonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/buttona"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonB": {
      "abstract": [
        {
          "text": "The value of the B button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonB"
        }
      ],
      "role": "symbol",
      "title": "buttonB",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/buttonb"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonX": {
      "abstract": [
        {
          "text": "The value of the X button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonX"
        }
      ],
      "role": "symbol",
      "title": "buttonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/buttonx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonY": {
      "abstract": [
        {
          "text": "The value of the Y button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonY"
        }
      ],
      "role": "symbol",
      "title": "buttonY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/buttony"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadX": {
      "abstract": [
        {
          "text": "The value of the horizontal axis of the dpad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpadX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dpadX"
        }
      ],
      "role": "symbol",
      "title": "dpadX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/dpadx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadY": {
      "abstract": [
        {
          "text": "The value of the vertical axis of the dpad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpadY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dpadY"
        }
      ],
      "role": "symbol",
      "title": "dpadY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/dpady"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/init()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/init()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/init(version:size:dpadX:dpadY:buttonA:buttonB:buttonX:buttonY:leftShoulder:rightShoulder:leftThumbstickX:leftThumbstickY:rightThumbstickX:rightThumbstickY:leftTrigger:rightTrigger:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dpadX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dpadY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "buttonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "buttonB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "buttonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "buttonY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leftThumbstickX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leftThumbstickY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightThumbstickX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightThumbstickY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leftTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/init(version:size:dpadX:dpadY:buttonA:buttonB:buttonX:buttonY:leftShoulder:rightShoulder:leftThumbstickX:leftThumbstickY:rightThumbstickX:rightThumbstickY:leftTrigger:rightTrigger:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:size:dpadX:dpadY:buttonA:buttonB:buttonX:buttonY:leftShoulder:rightShoulder:leftThumbstickX:leftThumbstickY:rightThumbstickX:rightThumbstickY:leftTrigger:rightTrigger:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/init(version:size:dpadx:dpady:buttona:buttonb:buttonx:buttony:leftshoulder:rightshoulder:leftthumbstickx:leftthumbsticky:rightthumbstickx:rightthumbsticky:lefttrigger:righttrigger:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftShoulder": {
      "abstract": [
        {
          "text": "The value of the left shoulder button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftShoulder"
        }
      ],
      "role": "symbol",
      "title": "leftShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/leftshoulder"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickX": {
      "abstract": [
        {
          "text": "The value of the horizontal axis of the left thumbstick.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftThumbstickX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftThumbstickX"
        }
      ],
      "role": "symbol",
      "title": "leftThumbstickX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/leftthumbstickx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickY": {
      "abstract": [
        {
          "text": "The value of the vertical axis of the left thumbstick.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftThumbstickY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftThumbstickY"
        }
      ],
      "role": "symbol",
      "title": "leftThumbstickY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/leftthumbsticky"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftTrigger": {
      "abstract": [
        {
          "text": "The value of the left trigger.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftTrigger"
        }
      ],
      "role": "symbol",
      "title": "leftTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/lefttrigger"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightShoulder": {
      "abstract": [
        {
          "text": "The value of the right shoulder button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightShoulder"
        }
      ],
      "role": "symbol",
      "title": "rightShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/rightshoulder"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickX": {
      "abstract": [
        {
          "text": "The value of the horizontal axis of the right thumbstick.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightThumbstickX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightThumbstickX"
        }
      ],
      "role": "symbol",
      "title": "rightThumbstickX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/rightthumbstickx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickY": {
      "abstract": [
        {
          "text": "The value of the vertical axis of the right thumbstick.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightThumbstickY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightThumbstickY"
        }
      ],
      "role": "symbol",
      "title": "rightThumbstickY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/rightthumbsticky"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightTrigger": {
      "abstract": [
        {
          "text": "The value of the right trigger.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightTrigger"
        }
      ],
      "role": "symbol",
      "title": "rightTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/righttrigger"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/size": {
      "abstract": [
        {
          "text": "The size of the recorded structure, in bytes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/size"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/version": {
      "abstract": [
        {
          "text": "A value that indicates the version number of the data structure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100/version"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)": {
      "abstract": [
        {
          "text": "Copies the recorded data from an extended gamepad snapshot into a readable structure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapShotDataV100FromNSData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCExtendedGamepadSnapShotDataV100",
          "text": "GCExtendedGamepadSnapShotDataV100"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapShotDataV100FromNSData"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100fromnsdata(_:_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapShotDataV100(_:)": {
      "abstract": [
        {
          "text": "Encapsulates the controller data from an extended gamepad structure into a data object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDataFromGCExtendedGamepadSnapShotDataV100"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCExtendedGamepadSnapShotDataV100",
          "text": "GCExtendedGamepadSnapShotDataV100"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapShotDataV100(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDataFromGCExtendedGamepadSnapShotDataV100"
        }
      ],
      "role": "symbol",
      "title": "NSDataFromGCExtendedGamepadSnapShotDataV100(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/nsdatafromgcextendedgamepadsnapshotdatav100(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flattening-a-Snapshot-to-Memory",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapShotDataV100(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)"
      ],
      "title": "Flattening a Snapshot to Memory"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonA",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonB",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonY",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadY",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftShoulder",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickY",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftTrigger",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightShoulder",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickY",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightTrigger",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/size",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/version"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/init()",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/init(version:size:dpadX:dpadY:buttonA:buttonB:buttonX:buttonY:leftShoulder:rightShoulder:leftThumbstickX:leftThumbstickY:rightThumbstickX:rightThumbstickY:leftTrigger:rightTrigger:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCExtendedGamepadSnapShotDataV100"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonA",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonB",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/buttonY",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/dpadY",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftShoulder",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftThumbstickY",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/leftTrigger",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightShoulder",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightThumbstickY",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/rightTrigger",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/size",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Flattening-a-Snapshot-to-Memory",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapShotDataV100(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)"
              ],
              "title": "Flattening a Snapshot to Memory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCExtendedGamepadSnapShotDataV100"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightTrigger/title",
          "value": "rightTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightThumbstickX/title",
          "value": "rightThumbstickX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightThumbstickX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightThumbstickX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftTrigger/title",
          "value": "leftTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100/title",
          "value": "GCExtendedGamepadSnapShotDataV100"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightThumbstickY/title",
          "value": "rightThumbstickY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightThumbstickY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightThumbstickY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightShoulder/title",
          "value": "rightShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1rightShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1NSDataFromGCExtendedGamepadSnapShotDataV100(_:)/title",
          "value": "NSDataFromGCExtendedGamepadSnapShotDataV100"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1NSDataFromGCExtendedGamepadSnapShotDataV100(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDataFromGCExtendedGamepadSnapShotDataV100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftShoulder/title",
          "value": "leftShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonY/title",
          "value": "buttonY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftThumbstickX/title",
          "value": "leftThumbstickX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftThumbstickX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftThumbstickX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonX/title",
          "value": "buttonX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftThumbstickY/title",
          "value": "leftThumbstickY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1leftThumbstickY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftThumbstickY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonA/title",
          "value": "buttonA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonB/title",
          "value": "buttonB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1buttonB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1dpadX/title",
          "value": "dpadX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1dpadX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpadX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)/title",
          "value": "GCExtendedGamepadSnapShotDataV100FromNSData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100FromNSData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapShotDataV100FromNSData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1dpadY/title",
          "value": "dpadY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapShotDataV100~1dpadY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpadY"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcextendedgamepadsnapshotdatav100"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
