{
  "abstract": [
    {
      "text": "The standard set of gamepad controls.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCGamepad",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCGamepad"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCGamepad"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "7.0",
        "name": "iOS",
        "renamed": "GCExtendedGamepad",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "7.0",
        "name": "iPadOS",
        "renamed": "GCExtendedGamepad",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "GCExtendedGamepad",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.9",
        "name": "macOS",
        "renamed": "GCExtendedGamepad",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "renamed": "GCExtendedGamepad",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "GCExtendedGamepad",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GCGamepad"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCGamepad"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The controls associated with the gamepad profile include the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Two shoulder buttons.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Four face buttons arranged in a diamond pattern.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "One directional pad (D-pad).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2556316",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentExtendedGamepadSnapshotDataVersion": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCCurrentExtendedGamepadSnapshotDataVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCExtendedGamepadSnapshotDataVersion",
          "text": "GCExtendedGamepadSnapshotDataVersion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentExtendedGamepadSnapshotDataVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCCurrentExtendedGamepadSnapshotDataVersion"
        }
      ],
      "role": "symbol",
      "title": "GCCurrentExtendedGamepadSnapshotDataVersion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccurrentextendedgamepadsnapshotdataversion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentMicroGamepadSnapshotDataVersion": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCCurrentMicroGamepadSnapshotDataVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GCMicroGamepadSnapshotDataVersion",
          "text": "GCMicroGamepadSnapshotDataVersion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentMicroGamepadSnapshotDataVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCCurrentMicroGamepadSnapshotDataVersion"
        }
      ],
      "role": "symbol",
      "title": "GCCurrentMicroGamepadSnapshotDataVersion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccurrentmicrogamepadsnapshotdataversion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the extended set of gamepad controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshot": {
      "abstract": [
        {
          "text": "A recording of all of the values provided by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshot"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshot"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepadSnapshot",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshot"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshotData"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshotData"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepadSnapshotData",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdata"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataFromNSData(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshotDataFromNSData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCExtendedGamepadSnapshotData",
          "text": "GCExtendedGamepadSnapshotData"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataFromNSData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshotDataFromNSData"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepadSnapshotDataFromNSData(_:_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdatafromnsdata(_:_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataVersion": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshotDataVersion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepadSnapshotDataVersion"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepadSnapshotDataVersion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepadsnapshotdataversion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad": {
      "abstract": [
        {
          "text": "The standard set of gamepad controls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonA": {
      "abstract": [
        {
          "text": "The bottom face button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonA"
        }
      ],
      "role": "symbol",
      "title": "buttonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/buttona"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonB": {
      "abstract": [
        {
          "text": "The right face button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonB"
        }
      ],
      "role": "symbol",
      "title": "buttonB",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/buttonb"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonX": {
      "abstract": [
        {
          "text": "The left face button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonX"
        }
      ],
      "role": "symbol",
      "title": "buttonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/buttonx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonY": {
      "abstract": [
        {
          "text": "The top face button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonY"
        }
      ],
      "role": "symbol",
      "title": "buttonY",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/buttony"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/controller": {
      "abstract": [
        {
          "text": "The controller this profile is associated with.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCController",
          "text": "GCController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/controller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controller"
        }
      ],
      "role": "symbol",
      "title": "controller",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/controller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/dpad": {
      "abstract": [
        {
          "text": "The D-pad element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerDirectionPad",
          "text": "GCControllerDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/dpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dpad"
        }
      ],
      "role": "symbol",
      "title": "dpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/dpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/leftShoulder": {
      "abstract": [
        {
          "text": "The left shoulder button element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/leftShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftShoulder"
        }
      ],
      "role": "symbol",
      "title": "leftShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/leftshoulder"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/rightShoulder": {
      "abstract": [
        {
          "text": "The right shoulder button element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightShoulder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/rightShoulder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightShoulder"
        }
      ],
      "role": "symbol",
      "title": "rightShoulder",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/rightshoulder"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/saveSnapshot()": {
      "abstract": [
        {
          "text": "Saves a snapshot of all of the profile’s elements.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveSnapshot"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCGamepadSnapshot",
          "text": "GCGamepadSnapshot"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/saveSnapshot()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveSnapshot"
        }
      ],
      "role": "symbol",
      "title": "saveSnapshot()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/savesnapshot()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/valueChangedHandler": {
      "abstract": [
        {
          "text": "A block called when any element in the profile changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCGamepadValueChangedHandler",
          "text": "GCGamepadValueChangedHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/valueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "valueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepad/valuechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadSnapshot": {
      "abstract": [
        {
          "text": "A recording of all of the values provided by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCGamepadSnapshot"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCGamepadSnapshot"
        }
      ],
      "role": "symbol",
      "title": "GCGamepadSnapshot",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepadsnapshot"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadValueChangedHandler": {
      "abstract": [
        {
          "text": "Signature for the block executed if any element in the gamepad profile changes value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCGamepadValueChangedHandler"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadValueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCGamepadValueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "GCGamepadValueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgamepadvaluechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Siri Remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot": {
      "abstract": [
        {
          "text": "A recording of all of the values provided by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshot"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshot"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadSnapshot",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshot"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotData": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshotData"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshotData"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadSnapshotData",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdata"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataFromNSData(_:_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshotDataFromNSData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCMicroGamepadSnapshotData",
          "text": "GCMicroGamepadSnapshotData"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataFromNSData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshotDataFromNSData"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadSnapshotDataFromNSData(_:_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdatafromnsdata(_:_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataVersion": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshotDataVersion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshotDataVersion"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadSnapshotDataVersion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshotdataversion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile": {
      "abstract": [
        {
          "text": "The base class for controller profiles that support physical buttons, thumbsticks, and directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapshotData(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDataFromGCExtendedGamepadSnapshotData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCExtendedGamepadSnapshotData",
          "text": "GCExtendedGamepadSnapshotData"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapshotData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDataFromGCExtendedGamepadSnapshotData"
        }
      ],
      "role": "symbol",
      "title": "NSDataFromGCExtendedGamepadSnapshotData(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/nsdatafromgcextendedgamepadsnapshotdata(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCMicroGamepadSnapshotData(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDataFromGCMicroGamepadSnapshotData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCMicroGamepadSnapshotData",
          "text": "GCMicroGamepadSnapshotData"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCMicroGamepadSnapshotData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDataFromGCMicroGamepadSnapshotData"
        }
      ],
      "role": "symbol",
      "title": "NSDataFromGCMicroGamepadSnapshotData(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/nsdatafromgcmicrogamepadsnapshotdata(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-2556316": {
      "alt": null,
      "identifier": "media-2556316",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/57237c8130783a4f106842ba76f1ac3b/media-2556316@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadSnapshot"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshot",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadSnapshot",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotData",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotData",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataVersion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataVersion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentExtendedGamepadSnapshotDataVersion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentMicroGamepadSnapshotDataVersion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataFromNSData(_:_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataFromNSData(_:_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapshotData(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCMicroGamepadSnapshotData(_:)"
      ],
      "title": "Deprecated symbols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-the-Controller-That-Owns-This-Profile",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/controller"
      ],
      "title": "Determining the Controller That Owns This Profile"
    },
    {
      "anchor": "Determining-When-Any-Element-in-the-Profile-Changes",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/valueChangedHandler"
      ],
      "title": "Determining When Any Element in the Profile Changes"
    },
    {
      "anchor": "Reading-Shoulder-Button-Inputs",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/leftShoulder",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/rightShoulder"
      ],
      "title": "Reading Shoulder Button Inputs"
    },
    {
      "anchor": "Reading-Directional-Pad-Inputs",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/dpad"
      ],
      "title": "Reading Directional Pad Inputs"
    },
    {
      "anchor": "Reading-Face-Button-Inputs",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonA",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonB",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonY"
      ],
      "title": "Reading Face Button Inputs"
    },
    {
      "anchor": "Saving-a-Snapshot",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/saveSnapshot()"
      ],
      "title": "Saving a Snapshot"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadValueChangedHandler"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.12",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCGamepad"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-the-Controller-That-Owns-This-Profile",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/controller"
              ],
              "title": "Determining the Controller That Owns This Profile"
            },
            {
              "anchor": "Determining-When-Any-Element-in-the-Profile-Changes",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/valueChangedHandler"
              ],
              "title": "Determining When Any Element in the Profile Changes"
            },
            {
              "anchor": "Reading-Shoulder-Button-Inputs",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/leftShoulder",
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/rightShoulder"
              ],
              "title": "Reading Shoulder Button Inputs"
            },
            {
              "anchor": "Reading-Directional-Pad-Inputs",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/dpad"
              ],
              "title": "Reading Directional Pad Inputs"
            },
            {
              "anchor": "Reading-Face-Button-Inputs",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonA",
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonB",
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/buttonY"
              ],
              "title": "Reading Face Button Inputs"
            },
            {
              "anchor": "Saving-a-Snapshot",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepad/saveSnapshot()"
              ],
              "title": "Saving a Snapshot"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadValueChangedHandler"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadSnapshot"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshot",
                "doc://com.apple.gamecontroller/documentation/GameController/GCGamepadSnapshot",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotData",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotData",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataVersion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataVersion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentExtendedGamepadSnapshotDataVersion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCCurrentMicroGamepadSnapshotDataVersion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepadSnapshotDataFromNSData(_:_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshotDataFromNSData(_:_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCExtendedGamepadSnapshotData(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/NSDataFromGCMicroGamepadSnapshotData(_:)"
              ],
              "title": "Deprecated symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCGamepad"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GCPhysicalInputProfile",
                    "text": "GCPhysicalInputProfile"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1saveSnapshot()/title",
          "value": "saveSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1saveSnapshot()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotDataFromNSData(_:_:)/title",
          "value": "GCExtendedGamepadSnapshotDataFromNSData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotDataFromNSData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshotDataFromNSData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad/title",
          "value": "GCGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1dpad/title",
          "value": "dpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1dpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCCurrentMicroGamepadSnapshotDataVersion/title",
          "value": "GCCurrentMicroGamepadSnapshotDataVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCCurrentMicroGamepadSnapshotDataVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCCurrentMicroGamepadSnapshotDataVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1NSDataFromGCMicroGamepadSnapshotData(_:)/title",
          "value": "NSDataFromGCMicroGamepadSnapshotData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1NSDataFromGCMicroGamepadSnapshotData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDataFromGCMicroGamepadSnapshotData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonA/title",
          "value": "buttonA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshot/title",
          "value": "GCExtendedGamepadSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotDataVersion/title",
          "value": "GCExtendedGamepadSnapshotDataVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotDataVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshotDataVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotDataVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshotDataVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1leftShoulder/title",
          "value": "leftShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1leftShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepadSnapshot/title",
          "value": "GCGamepadSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepadSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepadSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonB/title",
          "value": "buttonB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepadValueChangedHandler/title",
          "value": "GCGamepadValueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepadValueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepadValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepadValueChangedHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGamepadValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/title",
          "value": "GCMicroGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1NSDataFromGCExtendedGamepadSnapshotData(_:)/title",
          "value": "NSDataFromGCExtendedGamepadSnapshotData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1NSDataFromGCExtendedGamepadSnapshotData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDataFromGCExtendedGamepadSnapshotData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshot/title",
          "value": "GCMicroGamepadSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonY/title",
          "value": "buttonY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonX/title",
          "value": "buttonX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1buttonX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1rightShoulder/title",
          "value": "rightShoulder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1rightShoulder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightShoulder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotData/title",
          "value": "GCMicroGamepadSnapshotData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshotData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshotData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/title",
          "value": "GCPhysicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/title",
          "value": "GCExtendedGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotDataFromNSData(_:_:)/title",
          "value": "GCMicroGamepadSnapshotDataFromNSData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotDataFromNSData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshotDataFromNSData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotData/title",
          "value": "GCExtendedGamepadSnapshotData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshotData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepadSnapshotData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepadSnapshotData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1valueChangedHandler/title",
          "value": "valueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1valueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "valueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1controller/title",
          "value": "controller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGamepad~1controller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCCurrentExtendedGamepadSnapshotDataVersion/title",
          "value": "GCCurrentExtendedGamepadSnapshotDataVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCCurrentExtendedGamepadSnapshotDataVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCCurrentExtendedGamepadSnapshotDataVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotDataVersion/title",
          "value": "GCMicroGamepadSnapshotDataVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotDataVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshotDataVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshotDataVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshotDataVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcgamepad"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcgamepad"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
