{
  "abstract": [
    {
      "text": "The location of one or more haptics actuators on a game controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@GCHapticsLocality",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCHapticsLocality"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCHapticsLocality"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "GCHapticsLocality"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCHapticsLocality"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this symbol to specify the location of the actuators when creating a haptic engine.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics/supportedLocalities": {
      "abstract": [
        {
          "text": "The locations of haptic actuators on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedLocalities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics/supportedLocalities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedLocalities"
        }
      ],
      "role": "symbol",
      "title": "supportedLocalities",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicehaptics/supportedlocalities"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality": {
      "abstract": [
        {
          "text": "The location of one or more haptics actuators on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocality"
        }
      ],
      "role": "symbol",
      "title": "GCHapticsLocality",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/all": {
      "abstract": [
        {
          "text": "All locations of haptics actuators on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/all"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/default": {
      "abstract": [
        {
          "text": "The default location of a haptics actuator on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/default"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/handles": {
      "abstract": [
        {
          "text": "All handles on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/handles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityHandles"
        }
      ],
      "role": "symbol",
      "title": "handles",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/handles"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a locality structure with a string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/init(rawvalue:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftHandle": {
      "abstract": [
        {
          "text": "The left handle on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityLeftHandle"
        }
      ],
      "role": "symbol",
      "title": "leftHandle",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/lefthandle"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftTrigger": {
      "abstract": [
        {
          "text": "The left trigger on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityLeftTrigger"
        }
      ],
      "role": "symbol",
      "title": "leftTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/lefttrigger"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightHandle": {
      "abstract": [
        {
          "text": "The right handle on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityRightHandle"
        }
      ],
      "role": "symbol",
      "title": "rightHandle",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/righthandle"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightTrigger": {
      "abstract": [
        {
          "text": "The right trigger on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightTrigger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityRightTrigger"
        }
      ],
      "role": "symbol",
      "title": "rightTrigger",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/righttrigger"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/triggers": {
      "abstract": [
        {
          "text": "All triggers on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triggers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCHapticsLocality",
          "text": "GCHapticsLocality"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/triggers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCHapticsLocalityTriggers"
        }
      ],
      "role": "symbol",
      "title": "triggers",
      "type": "topic",
      "url": "/documentation/gamecontroller/gchapticslocality/triggers"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-localities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics/supportedLocalities"
      ],
      "title": "Getting the localities"
    }
  ],
  "topicSections": [
    {
      "anchor": "Localities",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/default",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/all",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/handles",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftHandle",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightHandle",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/triggers",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftTrigger",
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightTrigger"
      ],
      "title": "Localities"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCHapticsLocality"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Localities",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/default",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/all",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/handles",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftHandle",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightHandle",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/triggers",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/leftTrigger",
                "doc://com.apple.gamecontroller/documentation/GameController/GCHapticsLocality/rightTrigger"
              ],
              "title": "Localities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-localities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics/supportedLocalities"
              ],
              "title": "Getting the localities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCHapticsLocality"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1triggers/title",
          "value": "GCHapticsLocalityTriggers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1triggers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityTriggers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality/title",
          "value": "GCHapticsLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1all/title",
          "value": "GCHapticsLocalityAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1leftHandle/title",
          "value": "GCHapticsLocalityLeftHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1leftHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityLeftHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1leftTrigger/title",
          "value": "GCHapticsLocalityLeftTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1leftTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityLeftTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1rightHandle/title",
          "value": "GCHapticsLocalityRightHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1rightHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityRightHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1default/title",
          "value": "GCHapticsLocalityDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceHaptics~1supportedLocalities/title",
          "value": "supportedLocalities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceHaptics~1supportedLocalities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedLocalities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1rightTrigger/title",
          "value": "GCHapticsLocalityRightTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1rightTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityRightTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1handles/title",
          "value": "GCHapticsLocalityHandles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCHapticsLocality~1handles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCHapticsLocalityHandles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gchapticslocality"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gchapticslocality"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
