{
  "abstract": [
    {
      "text": "The Objective-C type for an input axis name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCInputAxisName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@GCInputAxisName",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GCInputAxisName"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCInputAxisName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "GCInputAxisName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSStringobjc(pl)GCAxisElementName",
              "text": "NSString<GCAxisElementName>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCInputAxisName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput": {
      "abstract": [
        {
          "text": "The common properties of inputs that provide absolute values along an axis with a fixed origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisInput"
        }
      ],
      "role": "symbol",
      "title": "GCAxisInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxisinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement": {
      "abstract": [
        {
          "text": "An element that represents either a pattern or a sequential gear shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCGearShifterElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCGearShifterElement"
        }
      ],
      "role": "symbol",
      "title": "GCGearShifterElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgearshifterelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputAxisName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input axis name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputAxisName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputAxisName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputAxisName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputaxisname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput": {
      "abstract": [
        {
          "text": "The common properties of inputs that provide positions along an axis that are relative to the previous position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCRelativeInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRelativeInput"
        }
      ],
      "role": "symbol",
      "title": "GCRelativeInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Gear-shifter-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput"
      ],
      "title": "Gear shifter elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput/title",
          "value": "GCRelativeInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/title",
          "value": "GCGearShifterElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGearShifterElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGearShifterElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisInput/title",
          "value": "GCAxisInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcinputaxisname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
