{
  "abstract": [
    {
      "text": "The keyboard code for the keypad 3 or Page Down key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@GCKeyKeypad3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCKeyKeypad3"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCKeyKeypad3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GCKeyKeypad3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCKeyKeypad3"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad0": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 0 or Insert key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad0"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad0",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad0"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad1": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 1 or End key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad1"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad1",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad1"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad2": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 2 or Down Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad2"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad2",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad3": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 3 or Page Down key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad3"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad3",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad4": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 4 or Left Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad4"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad4",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad5": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 5 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad5"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad5",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad5"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad6": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 6 or Right Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad6"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad6",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad6"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad7": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 7 or Home key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad7"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad7",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad7"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad8": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 8 or Up Arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad8"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad8",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad8"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad9": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad 9 or Page Up key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypad9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypad9"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypad9",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypad9"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadAsterisk": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad * key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypadAsterisk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadAsterisk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypadAsterisk"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypadAsterisk",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypadasterisk"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadEnter": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad Enter key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypadEnter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadEnter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypadEnter"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypadEnter",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypadenter"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadHyphen": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad - key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypadHyphen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadHyphen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypadHyphen"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypadHyphen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypadhyphen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadNumLock": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad Num Lock or Clear key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypadNumLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadNumLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypadNumLock"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypadNumLock",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypadnumlock"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadPlus": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad + key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypadPlus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadPlus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypadPlus"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypadPlus",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypadplus"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadSlash": {
      "abstract": [
        {
          "text": "The keyboard code for the keypad / key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyKeypadSlash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadSlash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyKeypadSlash"
        }
      ],
      "role": "symbol",
      "title": "GCKeyKeypadSlash",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeykeypadslash"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Keypad-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadNumLock",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadSlash",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadAsterisk",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadHyphen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadPlus",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadEnter",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad1",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad2",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad4",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad5",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad6",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad7",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad8",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad9",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad0"
      ],
      "title": "Keypad Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCKeyKeypad3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Keypad-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadNumLock",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadSlash",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadAsterisk",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadHyphen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadPlus",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypadEnter",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad1",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad2",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad4",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad5",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad6",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad7",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad8",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad9",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyKeypad0"
              ],
              "title": "Keypad Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCKeyKeypad3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadAsterisk/title",
          "value": "GCKeyKeypadAsterisk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadAsterisk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypadAsterisk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadSlash/title",
          "value": "GCKeyKeypadSlash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadSlash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypadSlash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad3/title",
          "value": "GCKeyKeypad3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad0/title",
          "value": "GCKeyKeypad0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadPlus/title",
          "value": "GCKeyKeypadPlus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadPlus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypadPlus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad1/title",
          "value": "GCKeyKeypad1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad9/title",
          "value": "GCKeyKeypad9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad2/title",
          "value": "GCKeyKeypad2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad8/title",
          "value": "GCKeyKeypad8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadNumLock/title",
          "value": "GCKeyKeypadNumLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadNumLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypadNumLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadEnter/title",
          "value": "GCKeyKeypadEnter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadEnter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypadEnter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad5/title",
          "value": "GCKeyKeypad5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad4/title",
          "value": "GCKeyKeypad4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad6/title",
          "value": "GCKeyKeypad6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadHyphen/title",
          "value": "GCKeyKeypadHyphen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypadHyphen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypadHyphen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad7/title",
          "value": "GCKeyKeypad7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyKeypad7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyKeypad7"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gckeykeypad3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gckeykeypad3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
