{
  "abstract": [
    {
      "text": "The keyboard code for the [ or { key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyOpenBracket"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@GCKeyOpenBracket",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCKeyOpenBracket"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCKeyOpenBracket"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GCKeyOpenBracket"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCKeyOpenBracket"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyBackslash": {
      "abstract": [
        {
          "text": "The keyboard code for the \\ or | key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyBackslash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyBackslash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyBackslash"
        }
      ],
      "role": "symbol",
      "title": "GCKeyBackslash",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeybackslash"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCapsLock": {
      "abstract": [
        {
          "text": "The keyboard code for the Caps Lock key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyCapsLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCapsLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCapsLock"
        }
      ],
      "role": "symbol",
      "title": "GCKeyCapsLock",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycapslock"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCloseBracket": {
      "abstract": [
        {
          "text": "The keyboard code for the ] or } key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyCloseBracket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCloseBracket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCloseBracket"
        }
      ],
      "role": "symbol",
      "title": "GCKeyCloseBracket",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyclosebracket"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyComma": {
      "abstract": [
        {
          "text": "The keyboard code for the Comma or < key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyComma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyComma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyComma"
        }
      ],
      "role": "symbol",
      "title": "GCKeyComma",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycomma"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyDeleteOrBackspace": {
      "abstract": [
        {
          "text": "The keyboard code for the Delete or Backspace key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyDeleteOrBackspace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyDeleteOrBackspace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyDeleteOrBackspace"
        }
      ],
      "role": "symbol",
      "title": "GCKeyDeleteOrBackspace",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeydeleteorbackspace"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyEqualSign": {
      "abstract": [
        {
          "text": "The keyboard code for the = or + key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyEqualSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyEqualSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyEqualSign"
        }
      ],
      "role": "symbol",
      "title": "GCKeyEqualSign",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyequalsign"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyGraveAccentAndTilde": {
      "abstract": [
        {
          "text": "The keyboard code for the Grave Accent or Tilde key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyGraveAccentAndTilde"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyGraveAccentAndTilde",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyGraveAccentAndTilde"
        }
      ],
      "role": "symbol",
      "title": "GCKeyGraveAccentAndTilde",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeygraveaccentandtilde"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyHyphen": {
      "abstract": [
        {
          "text": "The keyboard code for the - or _ key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyHyphen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyHyphen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyHyphen"
        }
      ],
      "role": "symbol",
      "title": "GCKeyHyphen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyhyphen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyNonUSPound": {
      "abstract": [
        {
          "text": "The keyboard code for the non-US Pound or _ key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyNonUSPound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyNonUSPound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyNonUSPound"
        }
      ],
      "role": "symbol",
      "title": "GCKeyNonUSPound",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeynonuspound"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyOpenBracket": {
      "abstract": [
        {
          "text": "The keyboard code for the [ or { key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyOpenBracket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyOpenBracket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyOpenBracket"
        }
      ],
      "role": "symbol",
      "title": "GCKeyOpenBracket",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyopenbracket"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyPeriod": {
      "abstract": [
        {
          "text": "The keyboard code for the Period or > key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyPeriod"
        }
      ],
      "role": "symbol",
      "title": "GCKeyPeriod",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyperiod"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyQuote": {
      "abstract": [
        {
          "text": "The keyboard code for the ’ or “ key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyQuote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyQuote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyQuote"
        }
      ],
      "role": "symbol",
      "title": "GCKeyQuote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyquote"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeySemicolon": {
      "abstract": [
        {
          "text": "The keyboard code for the ; or : key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeySemicolon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeySemicolon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeySemicolon"
        }
      ],
      "role": "symbol",
      "title": "GCKeySemicolon",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeysemicolon"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeySlash": {
      "abstract": [
        {
          "text": "The keyboard code for the / or ? key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeySlash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeySlash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeySlash"
        }
      ],
      "role": "symbol",
      "title": "GCKeySlash",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyslash"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeySpacebar": {
      "abstract": [
        {
          "text": "The keyboard code for the Space Bar key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeySpacebar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeySpacebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeySpacebar"
        }
      ],
      "role": "symbol",
      "title": "GCKeySpacebar",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyspacebar"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyTab": {
      "abstract": [
        {
          "text": "The keyboard code for the Tab key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyTab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyTab"
        }
      ],
      "role": "symbol",
      "title": "GCKeyTab",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeytab"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Punctuation-and-Command-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyTab",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeySpacebar",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyHyphen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyEqualSign",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCloseBracket",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyBackslash",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyNonUSPound",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeySemicolon",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyQuote",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyGraveAccentAndTilde",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyComma",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyPeriod",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeySlash",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCapsLock",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyDeleteOrBackspace"
      ],
      "title": "Punctuation and Command Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCKeyOpenBracket"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyOpenBracket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Punctuation-and-Command-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyTab",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeySpacebar",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyHyphen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyEqualSign",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCloseBracket",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyBackslash",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyNonUSPound",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeySemicolon",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyQuote",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyGraveAccentAndTilde",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyComma",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyPeriod",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeySlash",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCapsLock",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyDeleteOrBackspace"
              ],
              "title": "Punctuation and Command Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCKeyOpenBracket"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyBackslash/title",
          "value": "GCKeyBackslash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyBackslash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyBackslash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyPeriod/title",
          "value": "GCKeyPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyComma/title",
          "value": "GCKeyComma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyComma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyComma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyOpenBracket/title",
          "value": "GCKeyOpenBracket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyOpenBracket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyOpenBracket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeySlash/title",
          "value": "GCKeySlash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeySlash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeySlash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyTab/title",
          "value": "GCKeyTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyHyphen/title",
          "value": "GCKeyHyphen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyHyphen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyHyphen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyNonUSPound/title",
          "value": "GCKeyNonUSPound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyNonUSPound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyNonUSPound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyQuote/title",
          "value": "GCKeyQuote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyQuote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyQuote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyGraveAccentAndTilde/title",
          "value": "GCKeyGraveAccentAndTilde"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyGraveAccentAndTilde/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyGraveAccentAndTilde"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyDeleteOrBackspace/title",
          "value": "GCKeyDeleteOrBackspace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyDeleteOrBackspace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyDeleteOrBackspace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCloseBracket/title",
          "value": "GCKeyCloseBracket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCloseBracket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCloseBracket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeySemicolon/title",
          "value": "GCKeySemicolon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeySemicolon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeySemicolon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCapsLock/title",
          "value": "GCKeyCapsLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCapsLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCapsLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeySpacebar/title",
          "value": "GCKeySpacebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeySpacebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeySpacebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyEqualSign/title",
          "value": "GCKeyEqualSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyEqualSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyEqualSign"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gckeyopenbracket"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gckeyopenbracket"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
