{
  "abstract": [
    {
      "text": "A controller profile that supports the Siri Remote.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCMicroGamepad",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCMicroGamepad"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCMicroGamepad"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GCMicroGamepad"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The micro gamepad controller profile supports the following input elements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Two digital face buttons (A and X).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "One analog directional pad (D-pad) that functions as a touchpad.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Users can rotate game controllers that support the micro gamepad profile, switching them between landscape and portrait orientation. If you want to get directional values according to the orientation, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/allowsRotation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3830807",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/extendedGamepad": {
      "abstract": [
        {
          "text": "The extended gamepad profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedGamepad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCExtendedGamepad",
          "text": "GCExtendedGamepad"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/extendedGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedGamepad"
        }
      ],
      "role": "symbol",
      "title": "extendedGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/extendedgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/gamepad": {
      "abstract": [
        {
          "text": "The gamepad profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gamepad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCGamepad",
          "text": "GCGamepad"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/gamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gamepad"
        }
      ],
      "role": "symbol",
      "title": "gamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/gamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/microGamepad": {
      "abstract": [
        {
          "text": "The micro gamepad profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microGamepad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCMicroGamepad",
          "text": "GCMicroGamepad"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/microGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "microGamepad"
        }
      ],
      "role": "symbol",
      "title": "microGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/microgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion": {
      "abstract": [
        {
          "text": "The motion input profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCMotion",
          "text": "GCMotion"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motion"
        }
      ],
      "role": "symbol",
      "title": "motion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/motion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/physicalInputProfile": {
      "abstract": [
        {
          "text": "The physical input profile for the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalInputProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCPhysicalInputProfile",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/physicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "physicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "physicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/physicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad": {
      "abstract": [
        {
          "text": "A profile that supports only the directional pad, without motion or rotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionalGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionalGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionalGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionalgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supported the DualSense controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDualSenseGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDualSenseGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCDualSenseGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualsensegamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the DualShock 4 controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDualShockGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDualShockGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCDualShockGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdualshockgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the extended set of gamepad controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCExtendedGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCExtendedGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcextendedgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput": {
      "abstract": [
        {
          "text": "A controller profile that uses the keyboard as the input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyboardInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyboardInput"
        }
      ],
      "role": "symbol",
      "title": "GCKeyboardInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyboardinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Siri Remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/allowsRotation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the profile reports the directional pad values relative to its current orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/allowsRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsRotation"
        }
      ],
      "role": "symbol",
      "title": "allowsRotation",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/allowsrotation"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonA": {
      "abstract": [
        {
          "text": "The button that the user activates by pressing harder on the touchpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonA"
        }
      ],
      "role": "symbol",
      "title": "buttonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/buttona"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonMenu": {
      "abstract": [
        {
          "text": "The menu face button that players use to enter the main menu and pause the game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonMenu"
        }
      ],
      "role": "symbol",
      "title": "buttonMenu",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/buttonmenu"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonX": {
      "abstract": [
        {
          "text": "The second face button element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonX"
        }
      ],
      "role": "symbol",
      "title": "buttonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/buttonx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/controller": {
      "abstract": [
        {
          "text": "The controller associated with this profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCController",
          "text": "GCController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/controller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controller"
        }
      ],
      "role": "symbol",
      "title": "controller",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/controller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/dpad": {
      "abstract": [
        {
          "text": "The controller’s directional pad element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerDirectionPad",
          "text": "GCControllerDirectionPad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/dpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dpad"
        }
      ],
      "role": "symbol",
      "title": "dpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/dpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/reportsAbsoluteDpadValues": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the directional pad reports absolute or relative values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportsAbsoluteDpadValues"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/reportsAbsoluteDpadValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportsAbsoluteDpadValues"
        }
      ],
      "role": "symbol",
      "title": "reportsAbsoluteDpadValues",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/reportsabsolutedpadvalues"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/saveSnapshot()": {
      "abstract": [
        {
          "text": "Saves a snapshot of all of the profile’s elements.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveSnapshot"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCMicroGamepadSnapshot",
          "text": "GCMicroGamepadSnapshot"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/saveSnapshot()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveSnapshot"
        }
      ],
      "role": "symbol",
      "title": "saveSnapshot()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/savesnapshot()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/setStateFrom(_:)": {
      "abstract": [
        {
          "text": "Copies the input values from a specified micro gamepad to a snapshot of a micro gamepad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStateFrom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCMicroGamepad",
          "text": "GCMicroGamepad"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/setStateFrom(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStateFromMicroGamepad:"
        }
      ],
      "role": "symbol",
      "title": "setStateFrom(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/setstatefrom(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/valueChangedHandler": {
      "abstract": [
        {
          "text": "The block that this profile calls when an element’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCMicroGamepadValueChangedHandler",
          "text": "GCMicroGamepadValueChangedHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/valueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "valueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad/valuechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot": {
      "abstract": [
        {
          "text": "A recording of all of the values provided by a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshot"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadSnapshot"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadSnapshot",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadsnapshot"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadValueChangedHandler": {
      "abstract": [
        {
          "text": "Signature for the block that this profile calls when an element’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepadValueChangedHandler"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadValueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepadValueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepadValueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepadvaluechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMouseInput": {
      "abstract": [
        {
          "text": "A controller profile that tracks input from a mouse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMouseInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMouseInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMouseInput"
        }
      ],
      "role": "symbol",
      "title": "GCMouseInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmouseinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile": {
      "abstract": [
        {
          "text": "The base class for controller profiles that support physical buttons, thumbsticks, and directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Xbox controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCXboxGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCXboxGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCXboxGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of micro gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Micro gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/micro-gamepad-input-names"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3830807": {
      "alt": "An illustration of a Siri Remote with callouts for the digital face buttons, the Button menu, and the analog directional pad.",
      "identifier": "media-3830807",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/484a6ffc804aba9b7e2d68ed5f16ad37/media-3830807@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/852bb015728eeba3bd6f23612e2132c5/media-3830807~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-controller-profiles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/extendedGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMouseInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/microGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/physicalInputProfile",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController/gamepad"
      ],
      "title": "Accessing controller profiles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-controller",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/controller"
      ],
      "title": "Getting the controller"
    },
    {
      "anchor": "Receiving-a-callback-when-input-values-change",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/valueChangedHandler",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadValueChangedHandler"
      ],
      "title": "Receiving a callback when input values change"
    },
    {
      "anchor": "Getting-face-button-inputs",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonMenu",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonA",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonX"
      ],
      "title": "Getting face button inputs"
    },
    {
      "anchor": "Getting-directional-pad-inputs",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/dpad",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/reportsAbsoluteDpadValues",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/allowsRotation"
      ],
      "title": "Getting directional pad inputs"
    },
    {
      "anchor": "Accessing-elements-by-name",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names"
      ],
      "title": "Accessing elements by name"
    },
    {
      "anchor": "Setting-snapshot-avlues",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/setStateFrom(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/saveSnapshot()"
      ],
      "title": "Setting snapshot avlues"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCMicroGamepad"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-controller",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/controller"
              ],
              "title": "Getting the controller"
            },
            {
              "anchor": "Receiving-a-callback-when-input-values-change",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/valueChangedHandler",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadValueChangedHandler"
              ],
              "title": "Receiving a callback when input values change"
            },
            {
              "anchor": "Getting-face-button-inputs",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonMenu",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonA",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/buttonX"
              ],
              "title": "Getting face button inputs"
            },
            {
              "anchor": "Getting-directional-pad-inputs",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/dpad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/reportsAbsoluteDpadValues",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/allowsRotation"
              ],
              "title": "Getting directional pad inputs"
            },
            {
              "anchor": "Accessing-elements-by-name",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names"
              ],
              "title": "Accessing elements by name"
            },
            {
              "anchor": "Setting-snapshot-avlues",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/setStateFrom(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad/saveSnapshot()"
              ],
              "title": "Setting snapshot avlues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepadSnapshot"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-controller-profiles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCController/extendedGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMouseInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCExtendedGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualShockGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDualSenseGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCController/microGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionalGamepad",
                "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCController/physicalInputProfile",
                "doc://com.apple.gamecontroller/documentation/GameController/GCController/gamepad"
              ],
              "title": "Accessing controller profiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCMicroGamepad"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GCPhysicalInputProfile",
                    "text": "GCPhysicalInputProfile"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput/title",
          "value": "GCKeyboardInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboardInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboardInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1allowsRotation/title",
          "value": "allowsRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1allowsRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1buttonA/title",
          "value": "buttonA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1buttonA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadValueChangedHandler/title",
          "value": "GCMicroGamepadValueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadValueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadValueChangedHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseGamepad/title",
          "value": "GCDualSenseGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualSenseGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualSenseGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1setStateFrom(_:)/title",
          "value": "setStateFromMicroGamepad:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1setStateFrom(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStateFromMicroGamepad:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1buttonX/title",
          "value": "buttonX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1buttonX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/title",
          "value": "GCMicroGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1gamepad/title",
          "value": "gamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1gamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1extendedGamepad/title",
          "value": "extendedGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1extendedGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/title",
          "value": "GCExtendedGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCExtendedGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCExtendedGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1dpad/title",
          "value": "dpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1dpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1motion/title",
          "value": "motion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1motion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionalGamepad/title",
          "value": "GCDirectionalGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionalGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionalGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionalGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionalGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouseInput/title",
          "value": "GCMouseInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouseInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMouseInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouseInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMouseInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshot/title",
          "value": "GCMicroGamepadSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepadSnapshot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepadSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1buttonMenu/title",
          "value": "buttonMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1buttonMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1valueChangedHandler/title",
          "value": "valueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1valueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "valueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1reportsAbsoluteDpadValues/title",
          "value": "reportsAbsoluteDpadValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1reportsAbsoluteDpadValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportsAbsoluteDpadValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1physicalInputProfile/title",
          "value": "physicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1physicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "physicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1microGamepad/title",
          "value": "microGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1microGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "microGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/title",
          "value": "GCPhysicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1controller/title",
          "value": "controller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1controller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualShockGamepad/title",
          "value": "GCDualShockGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualShockGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualShockGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDualShockGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDualShockGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1saveSnapshot()/title",
          "value": "saveSnapshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad~1saveSnapshot()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveSnapshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/title",
          "value": "GCXboxGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCXboxGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCXboxGamepad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcmicrogamepad"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcmicrogamepad"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
