{
  "abstract": [
    {
      "text": "A controller profile that supports orientation and motion.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCMotion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCMotion"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCMotion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GCMotion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCMotion"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The motion controller profile provides attitude and rotation data, as well as acceleration and sensor information. Use this profile to get motion input from a controller that measures acceleration and rotation rate. If the controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is a ",
              "type": "text"
            },
            {
              "code": "GCMotion",
              "type": "codeVoice"
            },
            {
              "text": " object, the controller supports motion.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This illustration shows the direction of the x, y, and z axes of an iPhone when held upright.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2930224",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAcceleration": {
      "abstract": [
        {
          "text": "A three-dimensional acceleration vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAcceleration"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAcceleration"
        }
      ],
      "role": "symbol",
      "title": "GCAcceleration",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcacceleration"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion": {
      "abstract": [
        {
          "text": "The motion input profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCMotion",
          "text": "GCMotion"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController/motion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motion"
        }
      ],
      "role": "symbol",
      "title": "motion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller/motion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceBattery": {
      "abstract": [
        {
          "text": "The charge level and state of a device’s battery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceBattery"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceBattery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceBattery"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceBattery",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicebattery"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics": {
      "abstract": [
        {
          "text": "The locations of haptic actuators on a game controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceHaptics"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceHaptics"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceHaptics",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicehaptics"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceLight": {
      "abstract": [
        {
          "text": "The colored light on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDeviceLight"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDeviceLight"
        }
      ],
      "role": "symbol",
      "title": "GCDeviceLight",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicelight"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles": {
      "abstract": [
        {
          "text": "A structure that specifies the controller’s attitude as a series of rotations around the x, y, and z axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCEulerAngles"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCEulerAngles"
        }
      ],
      "role": "symbol",
      "title": "GCEulerAngles",
      "type": "topic",
      "url": "/documentation/gamecontroller/gceulerangles"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion": {
      "abstract": [
        {
          "text": "A controller profile that supports orientation and motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMotion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMotion"
        }
      ],
      "role": "symbol",
      "title": "GCMotion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/acceleration": {
      "abstract": [
        {
          "text": "The total acceleration of the controller that includes gravity and the acceleration the user applies to the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCAcceleration",
          "text": "GCAcceleration"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/acceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceleration"
        }
      ],
      "role": "symbol",
      "title": "acceleration",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/acceleration"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude": {
      "abstract": [
        {
          "text": "The attitude of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@GCQuaternion",
          "text": "GCQuaternion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attitude"
        }
      ],
      "role": "symbol",
      "title": "attitude",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/attitude"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/controller": {
      "abstract": [
        {
          "text": "The controller for the profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCController",
          "text": "GCController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/controller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controller"
        }
      ],
      "role": "symbol",
      "title": "controller",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/controller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/gravity": {
      "abstract": [
        {
          "text": "The gravity acceleration vector from the controller’s reference frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gravity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCAcceleration",
          "text": "GCAcceleration"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/gravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gravity"
        }
      ],
      "role": "symbol",
      "title": "gravity",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/gravity"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitude": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the controller provides attitude data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAttitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasAttitude"
        }
      ],
      "role": "symbol",
      "title": "hasAttitude",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/hasattitude"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitudeAndRotationRate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the controller provides attitude and rotation data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAttitudeAndRotationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitudeAndRotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasAttitudeAndRotationRate"
        }
      ],
      "role": "symbol",
      "title": "hasAttitudeAndRotationRate",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/hasattitudeandrotationrate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasGravityAndUserAcceleration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the controller provides gravity and user acceleration data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasGravityAndUserAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasGravityAndUserAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasGravityAndUserAcceleration"
        }
      ],
      "role": "symbol",
      "title": "hasGravityAndUserAcceleration",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/hasgravityanduseracceleration"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasRotationRate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the controller provides rotation data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasRotationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasRotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasRotationRate"
        }
      ],
      "role": "symbol",
      "title": "hasRotationRate",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/hasrotationrate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate": {
      "abstract": [
        {
          "text": "The rotation rate of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCRotationRate",
          "text": "GCRotationRate"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotationRate"
        }
      ],
      "role": "symbol",
      "title": "rotationRate",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/rotationrate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsActive": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the sensors that compute the motion data are active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorsActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorsActive"
        }
      ],
      "role": "symbol",
      "title": "sensorsActive",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/sensorsactive"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsRequireManualActivation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the sensors that compute the motion data require manual activation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorsRequireManualActivation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsRequireManualActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sensorsRequireManualActivation"
        }
      ],
      "role": "symbol",
      "title": "sensorsRequireManualActivation",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/sensorsrequiremanualactivation"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAcceleration(_:)": {
      "abstract": [
        {
          "text": "Sets the total acceleration of the controller that includes gravity and the user’s acceleration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAcceleration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCAcceleration",
          "text": "GCAcceleration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAcceleration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAcceleration:"
        }
      ],
      "role": "symbol",
      "title": "setAcceleration(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/setacceleration(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAttitude(_:)": {
      "abstract": [
        {
          "text": "Sets the controller’s attitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAttitude"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@GCQuaternion",
          "text": "GCQuaternion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAttitude(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAttitude:"
        }
      ],
      "role": "symbol",
      "title": "setAttitude(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/setattitude(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setGravity(_:)": {
      "abstract": [
        {
          "text": "Sets the controller’s gravity data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setGravity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCAcceleration",
          "text": "GCAcceleration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setGravity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setGravity:"
        }
      ],
      "role": "symbol",
      "title": "setGravity(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/setgravity(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setRotationRate(_:)": {
      "abstract": [
        {
          "text": "Sets the controller’s rotation rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRotationRate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCRotationRate",
          "text": "GCRotationRate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setRotationRate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRotationRate:"
        }
      ],
      "role": "symbol",
      "title": "setRotationRate(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/setrotationrate(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setStateFrom(_:)": {
      "abstract": [
        {
          "text": "Copies the input values from a specified motion profile to a snapshot of a motion profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStateFrom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCMotion",
          "text": "GCMotion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setStateFrom(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStateFromMotion:"
        }
      ],
      "role": "symbol",
      "title": "setStateFrom(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/setstatefrom(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setUserAcceleration(_:)": {
      "abstract": [
        {
          "text": "Sets the acceleration the user applies to the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setUserAcceleration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCAcceleration",
          "text": "GCAcceleration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setUserAcceleration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setUserAcceleration:"
        }
      ],
      "role": "symbol",
      "title": "setUserAcceleration(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/setuseracceleration(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/userAcceleration": {
      "abstract": [
        {
          "text": "The acceleration that the user applies to the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCAcceleration",
          "text": "GCAcceleration"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/userAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userAcceleration"
        }
      ],
      "role": "symbol",
      "title": "userAcceleration",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/useracceleration"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/valueChangedHandler": {
      "abstract": [
        {
          "text": "The block that the profile calls when an element’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCMotionValueChangedHandler",
          "text": "GCMotionValueChangedHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/valueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "valueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/valuechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotionValueChangedHandler": {
      "abstract": [
        {
          "text": "The signature for the block that the profile calls when an element’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMotionValueChangedHandler"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotionValueChangedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMotionValueChangedHandler"
        }
      ],
      "role": "symbol",
      "title": "GCMotionValueChangedHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotionvaluechangedhandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion": {
      "abstract": [
        {
          "text": "A quaternion that represents a controller’s measurement of attitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCQuaternion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCQuaternion"
        }
      ],
      "role": "symbol",
      "title": "GCQuaternion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcquaternion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate": {
      "abstract": [
        {
          "text": "A structure that represents rotation rates around the x, y, and z axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCRotationRate"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRotationRate"
        }
      ],
      "role": "symbol",
      "title": "GCRotationRate",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/input": {
      "abstract": [
        {
          "text": "Receive controller input in the way that best integrates with the flow of your game or game engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input",
      "type": "topic",
      "url": "/documentation/gamecontroller/input"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-2930224": {
      "alt": "An illustration of a vertical iPhone with the  x-axis passing through its center from side to side, the y-axis passing through its center from top to bottom, and the z-axis passing through its center from back to front.",
      "identifier": "media-2930224",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bfa00799a86f2c65db1da8219375e6dd/media-2930224@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c8ae5da5406413176d4bcc9bebfc5928/media-2930224~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Game-controller-profiles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/input",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceBattery",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceLight"
      ],
      "title": "Game controller profiles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Controller",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/controller"
      ],
      "title": "Getting the Controller"
    },
    {
      "anchor": "Receiving-a-Callback-When-Input-Values-Change",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/valueChangedHandler",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotionValueChangedHandler"
      ],
      "title": "Receiving a Callback When Input Values Change"
    },
    {
      "anchor": "Verifying-Capabilities",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitude",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasRotationRate",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasGravityAndUserAcceleration",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitudeAndRotationRate"
      ],
      "title": "Verifying Capabilities"
    },
    {
      "anchor": "Accessing-Attitude-and-Rotation-Data",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude",
        "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate",
        "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles"
      ],
      "title": "Accessing Attitude and Rotation Data"
    },
    {
      "anchor": "Accessing-Gravity-and-Acceleration-Data",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/acceleration",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/gravity",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/userAcceleration",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAcceleration"
      ],
      "title": "Accessing Gravity and Acceleration Data"
    },
    {
      "anchor": "Accessing-Sensor-Data",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsRequireManualActivation",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsActive"
      ],
      "title": "Accessing Sensor Data"
    },
    {
      "anchor": "Setting-Snapshot-Values",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setStateFrom(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAttitude(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setRotationRate(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAcceleration(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setGravity(_:)",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setUserAcceleration(_:)"
      ],
      "title": "Setting Snapshot Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCMotion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Controller",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/controller"
              ],
              "title": "Getting the Controller"
            },
            {
              "anchor": "Receiving-a-Callback-When-Input-Values-Change",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/valueChangedHandler",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotionValueChangedHandler"
              ],
              "title": "Receiving a Callback When Input Values Change"
            },
            {
              "anchor": "Verifying-Capabilities",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitude",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasRotationRate",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasGravityAndUserAcceleration",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/hasAttitudeAndRotationRate"
              ],
              "title": "Verifying Capabilities"
            },
            {
              "anchor": "Accessing-Attitude-and-Rotation-Data",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude",
                "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate",
                "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles"
              ],
              "title": "Accessing Attitude and Rotation Data"
            },
            {
              "anchor": "Accessing-Gravity-and-Acceleration-Data",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/acceleration",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/gravity",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/userAcceleration",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAcceleration"
              ],
              "title": "Accessing Gravity and Acceleration Data"
            },
            {
              "anchor": "Accessing-Sensor-Data",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsRequireManualActivation",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/sensorsActive"
              ],
              "title": "Accessing Sensor Data"
            },
            {
              "anchor": "Setting-Snapshot-Values",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setStateFrom(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAttitude(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setRotationRate(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setAcceleration(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setGravity(_:)",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/setUserAcceleration(_:)"
              ],
              "title": "Setting Snapshot Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Game-controller-profiles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/input",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceBattery",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceHaptics",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDeviceLight"
              ],
              "title": "Game controller profiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCMotion"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setRotationRate(_:)/title",
          "value": "setRotationRate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setRotationRate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRotationRate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setGravity(_:)/title",
          "value": "setGravity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setGravity(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setGravity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setStateFrom(_:)/title",
          "value": "setStateFromMotion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setStateFrom(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStateFromMotion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setAcceleration(_:)/title",
          "value": "setAcceleration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setAcceleration(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAcceleration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceBattery/title",
          "value": "GCDeviceBattery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceBattery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceBattery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceBattery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceBattery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1gravity/title",
          "value": "gravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1gravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setAttitude(_:)/title",
          "value": "setAttitude:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setAttitude(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAttitude:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotionValueChangedHandler/title",
          "value": "GCMotionValueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotionValueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMotionValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotionValueChangedHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMotionValueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1sensorsActive/title",
          "value": "sensorsActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1sensorsActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensorsActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceHaptics/title",
          "value": "GCDeviceHaptics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceHaptics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceHaptics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceHaptics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceHaptics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasRotationRate/title",
          "value": "hasRotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasRotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1acceleration/title",
          "value": "acceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1acceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasGravityAndUserAcceleration/title",
          "value": "hasGravityAndUserAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasGravityAndUserAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasGravityAndUserAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCQuaternion/title",
          "value": "GCQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCEulerAngles/title",
          "value": "GCEulerAngles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCEulerAngles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCEulerAngles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCEulerAngles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCEulerAngles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1valueChangedHandler/title",
          "value": "valueChangedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1valueChangedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "valueChangedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate/title",
          "value": "GCRotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1rotationRate/title",
          "value": "rotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1rotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1userAcceleration/title",
          "value": "userAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1userAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setUserAcceleration(_:)/title",
          "value": "setUserAcceleration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1setUserAcceleration(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setUserAcceleration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion/title",
          "value": "GCMotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceLight/title",
          "value": "GCDeviceLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDeviceLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDeviceLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasAttitude/title",
          "value": "hasAttitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasAttitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasAttitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasAttitudeAndRotationRate/title",
          "value": "hasAttitudeAndRotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1hasAttitudeAndRotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasAttitudeAndRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1attitude/title",
          "value": "attitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1attitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1controller/title",
          "value": "controller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1controller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1sensorsRequireManualActivation/title",
          "value": "sensorsRequireManualActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1sensorsRequireManualActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sensorsRequireManualActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAcceleration/title",
          "value": "GCAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAcceleration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1motion/title",
          "value": "motion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController~1motion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcmotion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcmotion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
