{
  "abstract": [
    {
      "text": "The common properties of physical input elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCPhysicalInputElement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCPhysicalInputElement"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCPhysicalInputElement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "GCPhysicalInputElement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement": {
      "abstract": [
        {
          "text": "The common properties for an element that represents an absolute or relative input value along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElement"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement": {
      "abstract": [
        {
          "text": "The common properties of an element that represents a momentary switch, such as a push button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElement"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement": {
      "abstract": [
        {
          "text": "The common properties of elements that represent directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElement"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement": {
      "abstract": [
        {
          "text": "An element that represents either a pattern or a sequential gear shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCGearShifterElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCGearShifterElement"
        }
      ],
      "role": "symbol",
      "title": "GCGearShifterElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgearshifterelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement": {
      "abstract": [
        {
          "text": "The common properties of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElement"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/aliases": {
      "abstract": [
        {
          "text": "The element’s aliases to use when accessing it with the subscript notation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aliases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/aliases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "aliases"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "aliases",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelement/aliases"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/localizedName": {
      "abstract": [
        {
          "text": "The localized name for the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelement/localizedname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/sfSymbolsName": {
      "abstract": [
        {
          "text": "A system symbol for the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sfSymbolsName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/sfSymbolsName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sfSymbolsName"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sfSymbolsName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelement/sfsymbolsname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class": {
      "abstract": [
        {
          "text": "A collection of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementCollection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementCollection",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-swift.struct": {
      "abstract": [
        {
          "text": "A collection of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementCollection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementCollection"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementCollection",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement": {
      "abstract": [
        {
          "text": "The element that represents the wheel of a racing wheel controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSteeringWheelElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSteeringWheelElement"
        }
      ],
      "role": "symbol",
      "title": "GCSteeringWheelElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcsteeringwheelelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement": {
      "abstract": [
        {
          "text": "The common properties for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElement"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelement"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement"
      ],
      "title": "Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-a-localized-name",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/localizedName"
      ],
      "title": "Getting a localized name"
    },
    {
      "anchor": "Displaying-a-symbol",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/sfSymbolsName"
      ],
      "title": "Displaying a symbol"
    },
    {
      "anchor": "Accessing-elements-by-key",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/aliases"
      ],
      "title": "Accessing elements by key"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCPhysicalInputElement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-a-localized-name",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/localizedName"
              ],
              "title": "Getting a localized name"
            },
            {
              "anchor": "Displaying-a-symbol",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/sfSymbolsName"
              ],
              "title": "Displaying a symbol"
            },
            {
              "anchor": "Accessing-elements-by-key",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement/aliases"
              ],
              "title": "Accessing elements by key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement"
              ],
              "title": "Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCPhysicalInputElement"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCButtonElement/title",
          "value": "GCButtonElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCButtonElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCButtonElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCButtonElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCButtonElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchElement/title",
          "value": "GCSwitchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement/title",
          "value": "GCDirectionPadElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionPadElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionPadElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement~1aliases/title",
          "value": "aliases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement~1aliases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement~1sfSymbolsName/title",
          "value": "sfSymbolsName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement~1sfSymbolsName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sfSymbolsName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/title",
          "value": "GCAxisElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSteeringWheelElement/title",
          "value": "GCSteeringWheelElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSteeringWheelElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSteeringWheelElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSteeringWheelElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSteeringWheelElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/title",
          "value": "GCPhysicalInputElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/title",
          "value": "GCGearShifterElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGearShifterElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGearShifterElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcphysicalinputelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcphysicalinputelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
