{
  "abstract": [
    {
      "text": "A collection of physical input elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCPhysicalInputElementCollection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GCPhysicalInputElementCollection"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCPhysicalInputElementCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GCPhysicalInputElementCollection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElementCollection"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement": {
      "abstract": [
        {
          "text": "The common properties for an element that represents an absolute or relative input value along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElement"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement": {
      "abstract": [
        {
          "text": "The common properties of an element that represents a momentary switch, such as a push button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElement"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement": {
      "abstract": [
        {
          "text": "The common properties of elements that represent directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElement"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement": {
      "abstract": [
        {
          "text": "The common properties of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElement"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class": {
      "abstract": [
        {
          "text": "A collection of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementCollection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementCollection",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/count": {
      "abstract": [
        {
          "text": "The number of elements in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class/count"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/elementEnumerator": {
      "abstract": [
        {
          "text": "Returns an enumerator to iterate the elements in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "elementEnumerator"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/elementEnumerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementEnumerator"
        }
      ],
      "role": "symbol",
      "title": "elementEnumerator",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class/elementenumerator"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/elementForAlias:": {
      "abstract": [
        {
          "text": "Returns the element in the collection that uses the specified alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "elementForAlias:"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/elementForAlias:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementForAlias:"
        }
      ],
      "role": "symbol",
      "title": "elementForAlias:",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class/elementforalias:"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/objectForKeyedSubscript:": {
      "abstract": [
        {
          "text": "Returns the element in the collection for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/objectForKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "objectForKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class/objectforkeyedsubscript:"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement": {
      "abstract": [
        {
          "text": "The common properties for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElement"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelement"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to support fast enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSFastEnumeration"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFastEnumeration",
      "type": "topic",
      "url": "/documentation/foundation/nsfastenumeration"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElement",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElement"
      ],
      "title": "Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-elements-in-the-collection",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/elementEnumerator",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/count"
      ],
      "title": "Getting elements in the collection"
    },
    {
      "anchor": "Accessing-elements-by-key-and-alias",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/objectForKeyedSubscript:",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-c.class/elementForAlias:"
      ],
      "title": "Accessing elements by key and alias"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/title",
          "value": "GCAxisElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchElement/title",
          "value": "GCSwitchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/title",
          "value": "GCPhysicalInputElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCButtonElement/title",
          "value": "GCButtonElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCButtonElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCButtonElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCButtonElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCButtonElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement/title",
          "value": "GCDirectionPadElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionPadElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDirectionPadElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDirectionPadElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcphysicalinputelementcollection-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
