{
  "abstract": [
    {
      "text": "The virtual remote in the Control Center on iOS and tvOS devices for controlling the Apple TV.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@GCProductCategoryControlCenterRemote",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCProductCategoryControlCenterRemote"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCProductCategoryControlCenterRemote"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GCProductCategoryControlCenterRemote"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCProductCategoryControlCenterRemote"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote": {
      "abstract": [
        {
          "text": "The Apple TV Remote product category for physical and virtual remotes that Game Center combines into a single device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryCoalescedRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryCoalescedRemote"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryCoalescedRemote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorycoalescedremote"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote": {
      "abstract": [
        {
          "text": "The virtual remote in the Control Center on iOS and tvOS devices for controlling the Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryControlCenterRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryControlCenterRemote"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryControlCenterRemote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorycontrolcenterremote"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen": {
      "abstract": [
        {
          "text": "The first-generation Siri Remote or first-generation Apple TV Remote product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote1stGen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote1stGen"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategorySiriRemote1stGen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorysiriremote1stgen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen": {
      "abstract": [
        {
          "text": "The second-generation Siri Remote or second-generation Apple TV Remote product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote2ndGen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote2ndGen"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategorySiriRemote2ndGen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorysiriremote2ndgen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote": {
      "abstract": [
        {
          "text": "The product category for a Universal Electronics remote that works with Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryUniversalElectronicsRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryUniversalElectronicsRemote"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryUniversalElectronicsRemote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategoryuniversalelectronicsremote"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-TV-remote-categories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote"
      ],
      "title": "Apple TV remote categories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCProductCategoryControlCenterRemote"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryControlCenterRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Apple-TV-remote-categories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote"
              ],
              "title": "Apple TV remote categories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCProductCategoryControlCenterRemote"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote1stGen/title",
          "value": "GCProductCategorySiriRemote1stGen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote1stGen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategorySiriRemote1stGen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryControlCenterRemote/title",
          "value": "GCProductCategoryControlCenterRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryControlCenterRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryControlCenterRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote2ndGen/title",
          "value": "GCProductCategorySiriRemote2ndGen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote2ndGen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategorySiriRemote2ndGen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryCoalescedRemote/title",
          "value": "GCProductCategoryCoalescedRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryCoalescedRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryCoalescedRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryUniversalElectronicsRemote/title",
          "value": "GCProductCategoryUniversalElectronicsRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryUniversalElectronicsRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryUniversalElectronicsRemote"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcproductcategorycontrolcenterremote"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcproductcategorycontrolcenterremote"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
