{
  "abstract": [
    {
      "text": "The common properties of inputs that provide positions along an axis that are relative to the previous position.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCRelativeInput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCRelativeInput"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCRelativeInput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "GCRelativeInput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput": {
      "abstract": [
        {
          "text": "The common properties of inputs that provide absolute values along an axis with a fixed origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisInput"
        }
      ],
      "role": "symbol",
      "title": "GCAxisInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxisinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement": {
      "abstract": [
        {
          "text": "An element that represents either a pattern or a sequential gear shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCGearShifterElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCGearShifterElement"
        }
      ],
      "role": "symbol",
      "title": "GCGearShifterElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcgearshifterelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputAxisName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input axis name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputAxisName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputAxisName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputAxisName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputaxisname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput": {
      "abstract": [
        {
          "text": "The common properties of inputs that provide positions along an axis that are relative to the previous position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCRelativeInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRelativeInput"
        }
      ],
      "role": "symbol",
      "title": "GCRelativeInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/delta": {
      "abstract": [
        {
          "text": "The most recent amount of change in values that the profile records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/delta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delta"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "delta",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput/delta"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/deltaDidChangeHandler": {
      "abstract": [
        {
          "text": "The block that the profile calls when the element’s input changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deltaDidChangeHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCRelativeInput",
          "text": "GCRelativeInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/deltaDidChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deltaDidChangeHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deltaDidChangeHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput/deltadidchangehandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/isAnalog": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the input provides analog values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAnalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/isAnalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analog"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isAnalog",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput/isanalog"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaLatency": {
      "abstract": [
        {
          "text": "The time in seconds between the current and the previous delta values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastDeltaLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastDeltaLatency"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lastDeltaLatency",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput/lastdeltalatency"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaTimestamp": {
      "abstract": [
        {
          "text": "A timestamp for when the profile reports the delta value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastDeltaTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastDeltaTimestamp"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lastDeltaTimestamp",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput/lastdeltatimestamp"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/sources": {
      "abstract": [
        {
          "text": "One or more physical actions the user performs to manipulate the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/sources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sources"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sources",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrelativeinput/sources"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Gear-shifter-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput",
        "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement"
      ],
      "title": "Gear shifter elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-characteristics",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/isAnalog"
      ],
      "title": "Getting the characteristics"
    },
    {
      "anchor": "Getting-the-delta-value-and-timestamp",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/delta",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/deltaDidChangeHandler",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaTimestamp",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaLatency"
      ],
      "title": "Getting the delta value and timestamp"
    },
    {
      "anchor": "Getting-user-actions",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/sources"
      ],
      "title": "Getting user actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCRelativeInput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-characteristics",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/isAnalog"
              ],
              "title": "Getting the characteristics"
            },
            {
              "anchor": "Getting-the-delta-value-and-timestamp",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/delta",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/deltaDidChangeHandler",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaTimestamp",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/lastDeltaLatency"
              ],
              "title": "Getting the delta value and timestamp"
            },
            {
              "anchor": "Getting-user-actions",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCRelativeInput/sources"
              ],
              "title": "Getting user actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Gear-shifter-elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisInput",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputAxisName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCGearShifterElement"
              ],
              "title": "Gear shifter elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCRelativeInput"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1lastDeltaLatency/title",
          "value": "lastDeltaLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1lastDeltaLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastDeltaLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1isAnalog/title",
          "value": "analog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1isAnalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "analog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput/title",
          "value": "GCRelativeInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRelativeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisInput/title",
          "value": "GCAxisInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1lastDeltaTimestamp/title",
          "value": "lastDeltaTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1lastDeltaTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastDeltaTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1delta/title",
          "value": "delta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1delta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/title",
          "value": "GCGearShifterElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGearShifterElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCGearShifterElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCGearShifterElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1deltaDidChangeHandler/title",
          "value": "deltaDidChangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1deltaDidChangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deltaDidChangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1sources/title",
          "value": "sources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRelativeInput~1sources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sources"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcrelativeinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcrelativeinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
