{
  "abstract": [
    {
      "text": "A structure that represents rotation rates around the x, y, and z axes.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@GCRotationRate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCRotationRate"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCRotationRate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "GCRotationRate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles": {
      "abstract": [
        {
          "text": "A structure that specifies the controller’s attitude as a series of rotations around the x, y, and z axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCEulerAngles"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCEulerAngles"
        }
      ],
      "role": "symbol",
      "title": "GCEulerAngles",
      "type": "topic",
      "url": "/documentation/gamecontroller/gceulerangles"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude": {
      "abstract": [
        {
          "text": "The attitude of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@GCQuaternion",
          "text": "GCQuaternion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attitude"
        }
      ],
      "role": "symbol",
      "title": "attitude",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/attitude"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate": {
      "abstract": [
        {
          "text": "The rotation rate of the controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotationRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@GCRotationRate",
          "text": "GCRotationRate"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotationRate"
        }
      ],
      "role": "symbol",
      "title": "rotationRate",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmotion/rotationrate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion": {
      "abstract": [
        {
          "text": "A quaternion that represents a controller’s measurement of attitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCQuaternion"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCQuaternion"
        }
      ],
      "role": "symbol",
      "title": "GCQuaternion",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcquaternion"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate": {
      "abstract": [
        {
          "text": "A structure that represents rotation rates around the x, y, and z axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCRotationRate"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRotationRate"
        }
      ],
      "role": "symbol",
      "title": "GCRotationRate",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/init()": {
      "abstract": [
        {
          "text": "Creates a rotation rate structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate/init()"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/init(x:y:z:)": {
      "abstract": [
        {
          "text": "Creates a rotation rate structure with the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/init(x:y:z:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(x:y:z:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate/init(x:y:z:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/x": {
      "abstract": [
        {
          "text": "The rotation rate around the x-axis in radians per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "x"
        }
      ],
      "role": "symbol",
      "title": "x",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate/x"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/y": {
      "abstract": [
        {
          "text": "The rotation rate around the y-axis in radians per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "y"
        }
      ],
      "role": "symbol",
      "title": "y",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate/y"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/z": {
      "abstract": [
        {
          "text": "The rotation rate around the z-axis in radians per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "z"
        }
      ],
      "role": "symbol",
      "title": "z",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcrotationrate/z"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Attitude-and-Rotation-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude",
        "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate",
        "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles"
      ],
      "title": "Accessing Attitude and Rotation Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Rotation-Rate-Values",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/x",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/y",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/z"
      ],
      "title": "Getting Rotation Rate Values"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/init()",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/init(x:y:z:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCRotationRate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Rotation-Rate-Values",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/x",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/y",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRotationRate/z"
              ],
              "title": "Getting Rotation Rate Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Attitude-and-Rotation-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/attitude",
                "doc://com.apple.gamecontroller/documentation/GameController/GCQuaternion",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMotion/rotationRate",
                "doc://com.apple.gamecontroller/documentation/GameController/GCEulerAngles"
              ],
              "title": "Accessing Attitude and Rotation Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCRotationRate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate~1y/title",
          "value": "y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate~1y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate/title",
          "value": "GCRotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate~1z/title",
          "value": "z"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate~1z/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "z"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1rotationRate/title",
          "value": "rotationRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1rotationRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotationRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate~1x/title",
          "value": "x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRotationRate~1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1attitude/title",
          "value": "attitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMotion~1attitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCQuaternion/title",
          "value": "GCQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCEulerAngles/title",
          "value": "GCEulerAngles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCEulerAngles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCEulerAngles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCEulerAngles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCEulerAngles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcrotationrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcrotationrate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
