{
  "abstract": [
    {
      "text": "The common properties of inputs that switch between two or more positions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCSwitchPositionInput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GCSwitchPositionInput"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GCSwitchPositionInput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "GCSwitchPositionInput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GCSwitchPositionInput"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputSwitchName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input switch name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputSwitchName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputSwitchName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputSwitchName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputswitchname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement": {
      "abstract": [
        {
          "text": "The element that represents the wheel of a racing wheel controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSteeringWheelElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSteeringWheelElement"
        }
      ],
      "role": "symbol",
      "title": "GCSteeringWheelElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcsteeringwheelelement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput": {
      "abstract": [
        {
          "text": "The common properties of inputs that switch between two or more positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchPositionInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchPositionInput"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchPositionInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/canWrap": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the position value wraps when it reaches the range’s minimum or maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canWrap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/canWrap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canWrap"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "canWrap",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/canwrap"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/isSequential": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the position change is sequential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSequential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/isSequential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sequential"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isSequential",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/issequential"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionLatency": {
      "abstract": [
        {
          "text": "The time in seconds between the current and previous positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPositionLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastPositionLatency"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lastPositionLatency",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/lastpositionlatency"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionTimestamp": {
      "abstract": [
        {
          "text": "A timestamp for when the profile reports the last position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPositionTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastPositionTimestamp"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lastPositionTimestamp",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/lastpositiontimestamp"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/position": {
      "abstract": [
        {
          "text": "The position of the switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/position"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionDidChangeHandler": {
      "abstract": [
        {
          "text": "The block that the profile calls when the value of the switch changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positionDidChangeHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCSwitchPositionInput",
          "text": "GCSwitchPositionInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionDidChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "positionDidChangeHandler"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "positionDidChangeHandler",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/positiondidchangehandler"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionRange": {
      "abstract": [
        {
          "text": "The range of possible values for the switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positionRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "positionRange"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "positionRange",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/positionrange"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/sources": {
      "abstract": [
        {
          "text": "One or more physical actions the user performs to manipulate the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/sources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sources"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sources",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchpositioninput/sources"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Steering-and-switch-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement"
      ],
      "title": "Steering and switch elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-characteristics",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionRange",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/isSequential",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/canWrap"
      ],
      "title": "Getting the characteristics"
    },
    {
      "anchor": "Getting-the-position",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/position",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionDidChangeHandler",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionTimestamp",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionLatency"
      ],
      "title": "Getting the position"
    },
    {
      "anchor": "Getting-user-actions",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/sources"
      ],
      "title": "Getting user actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GCSwitchPositionInput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchPositionInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchPositionInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-characteristics",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionRange",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/isSequential",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/canWrap"
              ],
              "title": "Getting the characteristics"
            },
            {
              "anchor": "Getting-the-position",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/position",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/positionDidChangeHandler",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionTimestamp",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/lastPositionLatency"
              ],
              "title": "Getting the position"
            },
            {
              "anchor": "Getting-user-actions",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchPositionInput/sources"
              ],
              "title": "Getting user actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Steering-and-switch-elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCSteeringWheelElement",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputSwitchName"
              ],
              "title": "Steering and switch elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GCSwitchPositionInput"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput/title",
          "value": "GCSwitchPositionInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchPositionInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSwitchPositionInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1lastPositionTimestamp/title",
          "value": "lastPositionTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1lastPositionTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastPositionTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1lastPositionLatency/title",
          "value": "lastPositionLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1lastPositionLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastPositionLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1canWrap/title",
          "value": "canWrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1canWrap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canWrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1isSequential/title",
          "value": "sequential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1isSequential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sequential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSteeringWheelElement/title",
          "value": "GCSteeringWheelElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSteeringWheelElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSteeringWheelElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSteeringWheelElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCSteeringWheelElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1positionDidChangeHandler/title",
          "value": "positionDidChangeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1positionDidChangeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "positionDidChangeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1sources/title",
          "value": "sources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1sources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1positionRange/title",
          "value": "positionRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCSwitchPositionInput~1positionRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "positionRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcswitchpositioninput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gcswitchpositioninput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
