{
  "abstract": [
    {
      "text": "A key that specifies whether the device is a game controller synthetic HID device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/kIOHIDGCSyntheticDeviceKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kIOHIDGCSyntheticDeviceKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kIOHIDGCSyntheticDeviceKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOHIDGCSyntheticDeviceKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kIOHIDGCSyntheticDeviceKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kIOHIDGCSyntheticDeviceKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamecontroller/documentation/GameController/understanding-game-controller-backward-compatibility"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is present with a Boolean value of ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " on all game controller synthetic HID devices that the Game Controller framework creates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app needs to exclude these synthetic HID devices from discovery by ",
              "type": "text"
            },
            {
              "text": "doc://com.apple.documentation/documentation/iokit/iohidmanagerref",
              "type": "text"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/iokit/1514494-ioservicegetmatchingservices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/iokit/1514362-ioserviceaddmatchingnotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/kIOHIDGCSyntheticDeviceKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with a value of ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " in the matching criteria.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "IOHIDManagerRef manager = IOHIDManagerCreate(kCFAllocatorDefault, kIOHIDManagerOptionNone);",
            "IOHIDManagerSetDeviceMatching(manager, (__bridge CFDictionaryRef)@{",
            "    @kIOProviderClassKey: @kIOHIDDeviceKey,",
            "    @kIOHIDGCSyntheticDeviceKey: @(NO)",
            "});"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Your code can check whether an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/iokit/io_service_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/iokit/iohiddeviceref",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " refers to a game controller synthetic HID device by querying the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/kIOHIDGCSyntheticDeviceKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if ( IOHIDDeviceGetProperty(device, CFSTR(kIOHIDGCSyntheticDeviceKey)) == kCFBooleanTrue ) {",
            "    // This is a synthetic HID device.",
            "}"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/iokit/1514362-ioserviceaddmatchingnotification": {
      "abstract": [
        {
          "text": "Look up registered IOService objects that match a matching dictionary, and install a notification request of new IOServices that match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "IOServiceAddMatchingNotification"
        },
        {
          "kind": "text",
          "text": "(IONotificationPortRef!, UnsafePointer<CChar>!, CFDictionary!, IOServiceMatchingCallback!, UnsafeMutableRawPointer!, UnsafeMutablePointer<io_iterator_t>!) -> kern_return_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/1514362-ioserviceaddmatchingnotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOServiceAddMatchingNotification(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iokit/1514362-ioserviceaddmatchingnotification"
    },
    "doc://com.apple.documentation/documentation/iokit/1514494-ioservicegetmatchingservices": {
      "abstract": [
        {
          "text": "Look up registered IOService objects that match a matching dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "IOServiceGetMatchingServices"
        },
        {
          "kind": "text",
          "text": "(mach_port_t, CFDictionary!, UnsafeMutablePointer<io_iterator_t>!) -> kern_return_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/1514494-ioservicegetmatchingservices",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOServiceGetMatchingServices(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iokit/1514494-ioservicegetmatchingservices"
    },
    "doc://com.apple.documentation/documentation/iokit/io_service_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "io_service_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/io_service_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "io_service_t",
      "type": "topic",
      "url": "/documentation/iokit/io_service_t"
    },
    "doc://com.apple.documentation/documentation/iokit/iohiddeviceref": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iohiddeviceref",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOHIDDeviceRef",
      "type": "topic",
      "url": "/documentation/iokit/iohiddeviceref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/kIOHIDGCSyntheticDeviceKey": {
      "abstract": [
        {
          "text": "A key that specifies whether the device is a game controller synthetic HID device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOHIDGCSyntheticDeviceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/kIOHIDGCSyntheticDeviceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOHIDGCSyntheticDeviceKey"
        }
      ],
      "role": "symbol",
      "title": "kIOHIDGCSyntheticDeviceKey",
      "type": "topic",
      "url": "/documentation/gamecontroller/kiohidgcsyntheticdevicekey"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/understanding-game-controller-backward-compatibility": {
      "abstract": [
        {
          "text": "Learn how macOS brings support for the latest game controllers to software that predates the introduction of the Game Controller framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/understanding-game-controller-backward-compatibility",
      "kind": "article",
      "role": "article",
      "title": "Understanding game controller backward compatibility",
      "type": "topic",
      "url": "/documentation/gamecontroller/understanding-game-controller-backward-compatibility"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Game-Controller-framework-migration-from-IOKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/understanding-game-controller-backward-compatibility"
      ],
      "title": "Game Controller framework migration from IOKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOHIDGCSyntheticDeviceKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOHIDGCSyntheticDeviceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Game-Controller-framework-migration-from-IOKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/understanding-game-controller-backward-compatibility"
              ],
              "title": "Game Controller framework migration from IOKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kIOHIDGCSyntheticDeviceKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1iokit~11514494-ioservicegetmatchingservices/title",
          "value": "IOServiceGetMatchingServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1iokit~11514362-ioserviceaddmatchingnotification/title",
          "value": "IOServiceAddMatchingNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1kIOHIDGCSyntheticDeviceKey/title",
          "value": "kIOHIDGCSyntheticDeviceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1kIOHIDGCSyntheticDeviceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOHIDGCSyntheticDeviceKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/kiohidgcsyntheticdevicekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/kiohidgcsyntheticdevicekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
