{
  "abstract": [
    {
      "text": "Support the second-generation Siri Remote as a game controller in your Apple TV game.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/letting-players-use-their-second-generation-siri-remote-as-a-game-controller"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Letting players use their second-generation Siri Remote as a game controller"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add support for the second-generation Siri Remote in your Apple TV game, you make a few changes to your Xcode project and code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-your-project",
          "level": 3,
          "text": "Configure your project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "First configure your Xcode project to handle directional gamepads and multiple micro gamepads.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On the Signing & Capabilities tab in the project editor, add the Game Controllers capability to your project and check Directional Gamepad under Game Controllers. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/configuring-game-controllers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On the Info tab, add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key and set the value to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ". For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/managing-your-app-s-information-property-list",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Handle-multiple-micro-gamepads",
          "level": 3,
          "text": "Handle multiple micro gamepads",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In your code, handle multiple micro gamepad connections. When a game controller connects, check if the controller is a directional gamepad using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418511-iskind",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if controller.microGamepad isKind(of: GCDirectionalGamepad.class) {",
            "   ...",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Check if the device category is second-generation Siri Remote using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if device.productCategory == GCProductCategorySiriRemote2ndGen {",
            "   ...",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If these conditions are true, you can use the connected second-generation Siri Remote as a game controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Access-the-remote-buttons-and-directional-pad",
          "level": 3,
          "text": "Access the remote buttons and directional pad",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To access the center button of the second-generation Siri Remote, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "controller.physicalInputProfile.buttons[GCInputDirectionalCenterButton]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then to access the directional pad, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "controller.physicalInputProfile.dpads[GCInputDirectionalCardinalDpad]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If your game requires an analog touch surface, check whether the directional pad is digital using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement/isAnalog",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if physicalInputProfile.dpads[GCInputDirectionalDpad].isAnalog == false"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the Universal Electronic remote that works with Apple TV is a directional gamepad but with physical non-analog buttons.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the physical Apple TV Remote and the Apple TV Remote app operate as separate game controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCSupportsMultipleMicroGamepads",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/GCSupportsMultipleMicroGamepads"
    },
    "doc://com.apple.documentation/documentation/BundleResources/managing-your-app-s-information-property-list": {
      "abstract": [
        {
          "text": "Create and customize an information property list file for your app using Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/managing-your-app-s-information-property-list",
      "kind": "article",
      "role": "article",
      "title": "Managing Your App’s Information Property List",
      "type": "topic",
      "url": "/documentation/BundleResources/managing-your-app-s-information-property-list"
    },
    "doc://com.apple.documentation/documentation/Xcode/configuring-game-controllers": {
      "abstract": [
        {
          "text": "Enhance gameplay input by enabling the discovery, configuration, and use of physical game controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/configuring-game-controllers",
      "kind": "article",
      "role": "article",
      "title": "Configuring game controllers",
      "type": "topic",
      "url": "/documentation/Xcode/configuring-game-controllers"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418511-iskind": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the receiver is an instance of given class or an instance of any class that inherits from that class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "isKind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": AnyClass) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418511-iskind",
      "kind": "symbol",
      "role": "symbol",
      "title": "isKind(of:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol/1418511-iskind"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement/isAnalog": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the element provides analog data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAnalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerElement/isAnalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analog"
        }
      ],
      "role": "symbol",
      "title": "isAnalog",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerelement/isanalog"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice": {
      "abstract": [
        {
          "text": "A protocol that defines a common interface for game input devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevice"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevice"
        }
      ],
      "role": "symbol",
      "title": "GCDevice",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory": {
      "abstract": [
        {
          "text": "The product category that identifies the type of controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productCategory"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "productCategory",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/productcategory"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g": {
      "abstract": [
        {
          "text": "The device’s buttons as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "buttons"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttons",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/buttons-3257g"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x": {
      "abstract": [
        {
          "text": "The device’s directional pads as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dpads"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x",
      "kind": "symbol",
      "role": "symbol",
      "title": "dpads",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/dpads-5yr9x"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard": {
      "abstract": [
        {
          "text": "An object that represents a physical keyboard connected to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyboard"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyboard"
        }
      ],
      "role": "symbol",
      "title": "GCKeyboard",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyboard"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMouse": {
      "abstract": [
        {
          "text": "An object that represents a physical mouse connected to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMouse"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMouse"
        }
      ],
      "role": "symbol",
      "title": "GCMouse",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmouse"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel": {
      "abstract": [
        {
          "text": "An object that represents a physical racing wheel controller connected to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCRacingWheel"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCRacingWheel"
        }
      ],
      "role": "symbol",
      "title": "GCRacingWheel",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcracingwheel"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/supporting-game-controllers": {
      "abstract": [
        {
          "text": "Support a physical controller or add a virtual controller to enhance how people interact with your game through haptics, lighting, and motion sensing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/supporting-game-controllers",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Game Controllers",
      "type": "topic",
      "url": "/documentation/gamecontroller/supporting-game-controllers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Game-controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/supporting-game-controllers",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMouse"
      ],
      "title": "Game controllers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Game-controllers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice",
                "doc://com.apple.gamecontroller/documentation/GameController/GCController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCRacingWheel",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboard",
                "doc://com.apple.gamecontroller/documentation/GameController/GCMouse"
              ],
              "title": "Game controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1productCategory/title",
          "value": "productCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1productCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/title",
          "value": "GCDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouse/title",
          "value": "GCMouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMouse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboard/title",
          "value": "GCKeyboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobjectprotocol~11418511-iskind/title",
          "value": "isKindOfClass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement~1isAnalog/title",
          "value": "analog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerElement~1isAnalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "analog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRacingWheel/title",
          "value": "GCRacingWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRacingWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRacingWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCRacingWheel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCRacingWheel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/letting-players-use-their-second-generation-siri-remote-as-a-game-controller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/letting-players-use-their-second-generation-siri-remote-as-a-game-controller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
