{
  "abstract": [
    {
      "text": "Constants for names of micro gamepad elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/input"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Micro gamepad input names"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input element name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputelementname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonA": {
      "abstract": [
        {
          "text": "The name of the micro gamepad’s primary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadButtonA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadButtonA"
        }
      ],
      "role": "symbol",
      "title": "GCInputMicroGamepadButtonA",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputmicrogamepadbuttona"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonMenu": {
      "abstract": [
        {
          "text": "The name of the micro gamepad’s menu button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadButtonMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadButtonMenu"
        }
      ],
      "role": "symbol",
      "title": "GCInputMicroGamepadButtonMenu",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputmicrogamepadbuttonmenu"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonX": {
      "abstract": [
        {
          "text": "The name of the micro gamepad’s secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadButtonX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadButtonX"
        }
      ],
      "role": "symbol",
      "title": "GCInputMicroGamepadButtonX",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputmicrogamepadbuttonx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadDpad": {
      "abstract": [
        {
          "text": "The name of the micro gamepad’s primary directional pad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadDpad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadDpad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCInputMicroGamepadDpad"
        }
      ],
      "role": "symbol",
      "title": "GCInputMicroGamepadDpad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputmicrogamepaddpad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Siri Remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCMicroGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCMicroGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCMicroGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcmicrogamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName": {
      "abstract": [
        {
          "text": "A type-safe name for accessing elements of a physical input element collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementTypedName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementtypedname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of directional pad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Directional Gamepad Input Names",
      "type": "topic",
      "url": "/documentation/gamecontroller/directional-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of DualShock 4 elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DualShock controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/dualshock-controller-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of extended gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/extended-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/input": {
      "abstract": [
        {
          "text": "Receive controller input in the way that best integrates with the flow of your game or game engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input",
      "type": "topic",
      "url": "/documentation/gamecontroller/input"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of Xbox elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Xbox controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/xbox-controller-input-names"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
      ],
      "title": "Element names"
    }
  ],
  "topicSections": [
    {
      "anchor": "Micro-gamepad-directional-pad-name",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadDpad"
      ],
      "title": "Micro gamepad directional pad name"
    },
    {
      "anchor": "Micro-gamepad-button-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonA",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonX",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonMenu"
      ],
      "title": "Micro gamepad button names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Micro-gamepad-directional-pad-name",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadDpad"
              ],
              "title": "Micro gamepad directional pad name"
            },
            {
              "anchor": "Micro-gamepad-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonA",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonX",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputMicroGamepadButtonMenu"
              ],
              "title": "Micro gamepad button names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
              ],
              "title": "Element names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadButtonX/title",
          "value": "GCInputMicroGamepadButtonX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadButtonX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputMicroGamepadButtonX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadButtonA/title",
          "value": "GCInputMicroGamepadButtonA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadButtonA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputMicroGamepadButtonA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadDpad/title",
          "value": "GCInputMicroGamepadDpad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadDpad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputMicroGamepadDpad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadButtonMenu/title",
          "value": "GCInputMicroGamepadButtonMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCInputMicroGamepadButtonMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCInputMicroGamepadButtonMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/title",
          "value": "GCMicroGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCMicroGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCMicroGamepad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/micro-gamepad-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/micro-gamepad-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
