{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/product-category-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Product category constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice": {
      "abstract": [
        {
          "text": "A protocol that defines a common interface for game input devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevice"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevice"
        }
      ],
      "role": "symbol",
      "title": "GCDevice",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory": {
      "abstract": [
        {
          "text": "The product category that identifies the type of controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "productCategory"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "productCategory",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/productcategory"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName": {
      "abstract": [
        {
          "text": "The manufacturer-provided name for the device, or the user’s name for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vendorName"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "vendorName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevice/vendorname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryArcadeStick": {
      "abstract": [
        {
          "text": "The arcade stick product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryArcadeStick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryArcadeStick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryArcadeStick"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryArcadeStick",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategoryarcadestick"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote": {
      "abstract": [
        {
          "text": "The Apple TV Remote product category for physical and virtual remotes that Game Center combines into a single device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryCoalescedRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryCoalescedRemote"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryCoalescedRemote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorycoalescedremote"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote": {
      "abstract": [
        {
          "text": "The virtual remote in the Control Center on iOS and tvOS devices for controlling the Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryControlCenterRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryControlCenterRemote"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryControlCenterRemote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorycontrolcenterremote"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualSense": {
      "abstract": [
        {
          "text": "The DualSense product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryDualSense"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualSense",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryDualSense"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryDualSense",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorydualsense"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualShock4": {
      "abstract": [
        {
          "text": "The DualShock 4 product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryDualShock4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualShock4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryDualShock4"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryDualShock4",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorydualshock4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryHID": {
      "abstract": [
        {
          "text": "The category for products that support the human interface device (HID) protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryHID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryHID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryHID"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryHID",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategoryhid"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryKeyboard": {
      "abstract": [
        {
          "text": "The keyboard product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryKeyboard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryKeyboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryKeyboard"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryKeyboard",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorykeyboard"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMFi": {
      "abstract": [
        {
          "text": "The MFi product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryMFi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMFi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryMFi"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryMFi",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorymfi"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMouse": {
      "abstract": [
        {
          "text": "The mouse product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryMouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryMouse"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryMouse",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorymouse"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen": {
      "abstract": [
        {
          "text": "The first-generation Siri Remote or first-generation Apple TV Remote product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote1stGen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote1stGen"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategorySiriRemote1stGen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorysiriremote1stgen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen": {
      "abstract": [
        {
          "text": "The second-generation Siri Remote or second-generation Apple TV Remote product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote2ndGen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategorySiriRemote2ndGen"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategorySiriRemote2ndGen",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategorysiriremote2ndgen"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote": {
      "abstract": [
        {
          "text": "The product category for a Universal Electronics remote that works with Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryUniversalElectronicsRemote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryUniversalElectronicsRemote"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryUniversalElectronicsRemote",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategoryuniversalelectronicsremote"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryXboxOne": {
      "abstract": [
        {
          "text": "The Xbox product category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCProductCategoryXboxOne"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryXboxOne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCProductCategoryXboxOne"
        }
      ],
      "role": "symbol",
      "title": "GCProductCategoryXboxOne",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcproductcategoryxboxone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-device-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory"
      ],
      "title": "Getting device information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Game-controller-categories",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualSense",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualShock4",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMFi",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryXboxOne",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryArcadeStick",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryHID"
      ],
      "title": "Game controller categories"
    },
    {
      "anchor": "Apple-TV-remote-categories",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote"
      ],
      "title": "Apple TV remote categories"
    },
    {
      "anchor": "Mouse-and-keyboard-categories",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMouse",
        "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryKeyboard"
      ],
      "title": "Mouse and keyboard categories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Game-controller-categories",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualSense",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryDualShock4",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMFi",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryXboxOne",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryArcadeStick",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryHID"
              ],
              "title": "Game controller categories"
            },
            {
              "anchor": "Apple-TV-remote-categories",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote1stGen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategorySiriRemote2ndGen",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryControlCenterRemote",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryUniversalElectronicsRemote",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryCoalescedRemote"
              ],
              "title": "Apple TV remote categories"
            },
            {
              "anchor": "Mouse-and-keyboard-categories",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryMouse",
                "doc://com.apple.gamecontroller/documentation/GameController/GCProductCategoryKeyboard"
              ],
              "title": "Mouse and keyboard categories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-device-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/vendorName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDevice/productCategory"
              ],
              "title": "Getting device information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryUniversalElectronicsRemote/title",
          "value": "GCProductCategoryUniversalElectronicsRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryUniversalElectronicsRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryUniversalElectronicsRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryXboxOne/title",
          "value": "GCProductCategoryXboxOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryXboxOne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryXboxOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryHID/title",
          "value": "GCProductCategoryHID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryHID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryHID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryMFi/title",
          "value": "GCProductCategoryMFi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryMFi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryMFi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryDualSense/title",
          "value": "GCProductCategoryDualSense"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryDualSense/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryDualSense"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryControlCenterRemote/title",
          "value": "GCProductCategoryControlCenterRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryControlCenterRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryControlCenterRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/title",
          "value": "GCDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryKeyboard/title",
          "value": "GCProductCategoryKeyboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryKeyboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryKeyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryDualShock4/title",
          "value": "GCProductCategoryDualShock4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryDualShock4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryDualShock4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryArcadeStick/title",
          "value": "GCProductCategoryArcadeStick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryArcadeStick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryArcadeStick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1productCategory/title",
          "value": "productCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1productCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "productCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote1stGen/title",
          "value": "GCProductCategorySiriRemote1stGen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote1stGen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategorySiriRemote1stGen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryMouse/title",
          "value": "GCProductCategoryMouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryMouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryMouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1vendorName/title",
          "value": "vendorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice~1vendorName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vendorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryCoalescedRemote/title",
          "value": "GCProductCategoryCoalescedRemote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategoryCoalescedRemote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategoryCoalescedRemote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote2ndGen/title",
          "value": "GCProductCategorySiriRemote2ndGen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCProductCategorySiriRemote2ndGen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCProductCategorySiriRemote2ndGen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/product-category-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/product-category-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
