{
  "abstract": [
    {
      "text": "Constants for names of Xbox elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/input"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/xbox-controller-input-names"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Xbox controller input names"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants as the keys when accessing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " elements by name using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, ",
              "type": "text"
            },
            {
              "code": "subscript(_:)",
              "type": "codeVoice"
            },
            {
              "text": " notation, or similar ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for the elements that provide values along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElementName"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names of the button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCButtonElementName"
        }
      ],
      "role": "symbol",
      "title": "GCButtonElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcbuttonelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCController": {
      "abstract": [
        {
          "text": "A representation of a real game controller, a virtual controller, or a snapshot of a controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCController"
        }
      ],
      "role": "symbol",
      "title": "GCController",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct": {
      "abstract": [
        {
          "text": "The names for directional pad elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDirectionPadElementName"
        }
      ],
      "role": "symbol",
      "title": "GCDirectionPadElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdirectionpadelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonShare-2xxjg": {
      "abstract": [
        {
          "text": "The name of the share button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputButtonShare"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonShare-2xxjg",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonShare",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonshare-2xxjg"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonShare-87tha": {
      "abstract": [
        {
          "text": "The name of the share button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputButtonShare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonShare-87tha",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputButtonShare",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputbuttonshare-87tha"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName": {
      "abstract": [
        {
          "text": "The Objective-C type for an input element name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputelementname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleFour-1obrw": {
      "abstract": [
        {
          "text": "The name for the controller’s P4 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleFour"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleFour-1obrw",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleFour",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddlefour-1obrw"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleFour-4n8ze": {
      "abstract": [
        {
          "text": "The name for the controller’s P4 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleFour"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleFour-4n8ze",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleFour",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddlefour-4n8ze"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleOne-795e3": {
      "abstract": [
        {
          "text": "The name for the controller’s P1 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleOne"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleOne-795e3",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleOne",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddleone-795e3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleOne-offv": {
      "abstract": [
        {
          "text": "The name for the controller’s P1 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleOne"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleOne-offv",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleOne",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddleone-offv"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleThree-6zcw8": {
      "abstract": [
        {
          "text": "The name for the controller’s P3 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleThree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleThree-6zcw8",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleThree",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddlethree-6zcw8"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleThree-7u2xy": {
      "abstract": [
        {
          "text": "The name for the controller’s P3 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleThree"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleThree-7u2xy",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleThree",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddlethree-7u2xy"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleTwo-4vrw4": {
      "abstract": [
        {
          "text": "The name for the controller’s P2 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleTwo"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleTwo-4vrw4",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleTwo",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddletwo-4vrw4"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleTwo-4ya43": {
      "abstract": [
        {
          "text": "The name for the controller’s P2 paddle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCInputXboxPaddleTwo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleTwo-4ya43",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCInputXboxPaddleTwo",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcinputxboxpaddletwo-4ya43"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name of a physical input element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName": {
      "abstract": [
        {
          "text": "A type-safe name for accessing elements of a physical input element collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementTypedName"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementTypedName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementtypedname"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile": {
      "abstract": [
        {
          "text": "The base class for controller profiles that support physical buttons, thumbsticks, and directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements": {
      "abstract": [
        {
          "text": "The elements in the profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allElements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerElement",
          "text": "GCControllerElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/allElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allElements"
        }
      ],
      "role": "symbol",
      "title": "allElements",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile/allelements"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-c.protocol"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct": {
      "abstract": [
        {
          "text": "The name for an element that represents a switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCSwitchElementName"
        }
      ],
      "role": "symbol",
      "title": "GCSwitchElementName",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcswitchelementname-swift.struct"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad": {
      "abstract": [
        {
          "text": "A controller profile that supports the Xbox controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCXboxGamepad"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCXboxGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCXboxGamepad"
        }
      ],
      "role": "symbol",
      "title": "GCXboxGamepad",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcxboxgamepad"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of directional pad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Directional Gamepad Input Names",
      "type": "topic",
      "url": "/documentation/gamecontroller/directional-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names": {
      "abstract": [
        {
          "text": "Constants for names of DualShock 4 elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DualShock controller input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/dualshock-controller-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of extended gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extended gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/extended-gamepad-input-names"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/input": {
      "abstract": [
        {
          "text": "Receive controller input in the way that best integrates with the flow of your game or game engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Input",
      "type": "topic",
      "url": "/documentation/gamecontroller/input"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names": {
      "abstract": [
        {
          "text": "Constants for names of micro gamepad elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Micro gamepad input names",
      "type": "topic",
      "url": "/documentation/gamecontroller/micro-gamepad-input-names"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Element-names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementTypedName",
        "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-swift.struct",
        "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
        "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
      ],
      "title": "Element names"
    }
  ],
  "topicSections": [
    {
      "anchor": "Xbox-controller-button-names",
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonShare-87tha",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleOne-offv",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleTwo-4ya43",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleThree-6zcw8",
        "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleFour-1obrw"
      ],
      "title": "Xbox controller button names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Xbox-controller-button-names",
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputButtonShare-2xxjg",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleOne-795e3",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleTwo-4vrw4",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleThree-7u2xy",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputXboxPaddleFour-4n8ze"
              ],
              "title": "Xbox controller button names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Element-names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCInputElementName",
                "doc://com.apple.gamecontroller/documentation/GameController/GCButtonElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCSwitchElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/GCDirectionPadElementName-c.protocol",
                "doc://com.apple.gamecontroller/documentation/GameController/extended-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/dualshock-controller-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/micro-gamepad-input-names",
                "doc://com.apple.gamecontroller/documentation/GameController/directional-gamepad-input-names"
              ],
              "title": "Element names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/title",
          "value": "GCPhysicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1allElements/title",
          "value": "allElements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1allElements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allElements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/title",
          "value": "GCController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/title",
          "value": "GCXboxGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCXboxGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCXboxGamepad/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCXboxGamepad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/xbox-controller-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/xbox-controller-input-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
