{
  "abstract": [
    {
      "text": "Creates a fixed group that a person can’t move or remove from the navigation bar during layout customization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/fixedGroupWithRepresentativeItem:items:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIBarButtonItemGroup(cm)fixedGroupWithRepresentativeItem:items:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "fixedGroupWithRepresentativeItem:items:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fixedGroupWithRepresentativeItem:items:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "fixedGroupWithRepresentativeItem:items:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIBarButtonItemGroup",
              "text": "UIBarButtonItemGroup"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "fixedGroupWithRepresentativeItem:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
              "text": "UIBarButtonItem"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "representativeItem"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "items:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<UIBarButtonItem *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "items"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The item to display for the group when space is constrained.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "representativeItem"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The items to include in the group.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "items"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup": {
      "abstract": [
        {
          "text": "A group of one or more bar button items for placement on a navigation bar or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItemGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItemGroup"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItemGroup",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitemgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/fixedGroupWithRepresentativeItem:items:": {
      "abstract": [
        {
          "text": "Creates a fixed group that a person can’t move or remove from the navigation bar during layout customization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedGroupWithRepresentativeItem:items:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/fixedGroupWithRepresentativeItem:items:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedGroupWithRepresentativeItem:items:"
        }
      ],
      "role": "symbol",
      "title": "fixedGroupWithRepresentativeItem:items:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitemgroup/fixedgroupwithrepresentativeitem:items:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/init(barButtonItems:representativeItem:)": {
      "abstract": [
        {
          "text": "Creates a fixed group with the specified items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "barButtonItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "representativeItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/init(barButtonItems:representativeItem:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBarButtonItems:representativeItem:"
        }
      ],
      "role": "symbol",
      "title": "init(barButtonItems:representativeItem:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitemgroup/init(barbuttonitems:representativeitem:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a bar button item group from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitemgroup/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/movableGroupWithCustomizationIdentifier:representativeItem:items:": {
      "abstract": [
        {
          "text": "Creates a movable group that a person can move but can’t remove from the navigation bar during layout customization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "movableGroupWithCustomizationIdentifier:representativeItem:items:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/movableGroupWithCustomizationIdentifier:representativeItem:items:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "movableGroupWithCustomizationIdentifier:representativeItem:items:"
        }
      ],
      "role": "symbol",
      "title": "movableGroupWithCustomizationIdentifier:representativeItem:items:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitemgroup/movablegroupwithcustomizationidentifier:representativeitem:items:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/optionalGroupWithCustomizationIdentifier:inDefaultCustomization:representativeItem:items:": {
      "abstract": [
        {
          "text": "Creates an optional group that a person can move, add to, or remove from the navigation bar during layout customization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "optionalGroupWithCustomizationIdentifier:inDefaultCustomization:representativeItem:items:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/optionalGroupWithCustomizationIdentifier:inDefaultCustomization:representativeItem:items:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optionalGroupWithCustomizationIdentifier:inDefaultCustomization:representativeItem:items:"
        }
      ],
      "role": "symbol",
      "title": "optionalGroupWithCustomizationIdentifier:inDefaultCustomization:representativeItem:items:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitemgroup/optionalgroupwithcustomizationidentifier:indefaultcustomization:representativeitem:items:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-group",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/movableGroupWithCustomizationIdentifier:representativeItem:items:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/optionalGroupWithCustomizationIdentifier:inDefaultCustomization:representativeItem:items:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/init(barButtonItems:representativeItem:)",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItemGroup/init(coder:)"
      ],
      "title": "Creating a group"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup~1init(barButtonItems:representativeItem:)/title",
          "value": "initWithBarButtonItems:representativeItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup~1init(barButtonItems:representativeItem:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBarButtonItems:representativeItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup/title",
          "value": "UIBarButtonItemGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItemGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItemGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItemGroup~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitemgroup/fixedgroupwithrepresentativeitem:items:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
