{
  "abstract": [
    {
      "text": "Right tab stop.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSAccessibilityRulerMarkerType@NSAccessibilityRulerMarkerTypeTabStopRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tabStopRight"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityRulerMarkerTypeTabStopRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSAccessibilityRulerMarkerType.tabStopRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tabStopRight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType": {
      "abstract": [
        {
          "text": "Values that indicate the marker type of an accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerType"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentFirstLine": {
      "abstract": [
        {
          "text": "First line indent marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indentFirstLine"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentFirstLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeIndentFirstLine"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.indentFirstLine",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/indentfirstline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentHead": {
      "abstract": [
        {
          "text": "Head indent marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indentHead"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeIndentHead"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.indentHead",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/indenthead"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentTail": {
      "abstract": [
        {
          "text": "Tail indent marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indentTail"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentTail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeIndentTail"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.indentTail",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/indenttail"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopCenter": {
      "abstract": [
        {
          "text": "Center tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStopCenter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeTabStopCenter"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.tabStopCenter",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/tabstopcenter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopDecimal": {
      "abstract": [
        {
          "text": "Decimal tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStopDecimal"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopDecimal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeTabStopDecimal"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.tabStopDecimal",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/tabstopdecimal"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopLeft": {
      "abstract": [
        {
          "text": "Left tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStopLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeTabStopLeft"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.tabStopLeft",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/tabstopleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopRight": {
      "abstract": [
        {
          "text": "Right tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStopRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeTabStopRight"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.tabStopRight",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/tabstopright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/unknown": {
      "abstract": [
        {
          "text": "Unknown marker type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/unknown",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopLeft",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopCenter",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopDecimal",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentHead",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentTail",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentFirstLine"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityRulerMarkerTypeTabStopRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeTabStopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/unknown",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopLeft",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopCenter",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/tabStopDecimal",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentHead",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentTail",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType/indentFirstLine"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityRulerMarkerTypeTabStopRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopRight/title",
          "value": "NSAccessibilityRulerMarkerTypeTabStopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeTabStopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopLeft/title",
          "value": "NSAccessibilityRulerMarkerTypeTabStopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeTabStopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1indentFirstLine/title",
          "value": "NSAccessibilityRulerMarkerTypeIndentFirstLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1indentFirstLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeIndentFirstLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopDecimal/title",
          "value": "NSAccessibilityRulerMarkerTypeTabStopDecimal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopDecimal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeTabStopDecimal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType/title",
          "value": "NSAccessibilityRulerMarkerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1unknown/title",
          "value": "NSAccessibilityRulerMarkerTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1indentTail/title",
          "value": "NSAccessibilityRulerMarkerTypeIndentTail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1indentTail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeIndentTail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1indentHead/title",
          "value": "NSAccessibilityRulerMarkerTypeIndentHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1indentHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeIndentHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopCenter/title",
          "value": "NSAccessibilityRulerMarkerTypeTabStopCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType~1tabStopCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeTabStopCenter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityrulermarkertype/tabstopright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibilityrulermarkertype/tabstopright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
