{
  "abstract": [
    {
      "text": "Geo-tracking accuracy is undetermined.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/undetermined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARGeoTrackingAccuracy@ARGeoTrackingAccuracyUndetermined",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "undetermined"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARGeoTrackingAccuracyUndetermined"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARGeoTrackingStatus.Accuracy.undetermined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "undetermined"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value indicates that because the session has not completed visual localization, geo-tracking accuracy is indeterminate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus": {
      "abstract": [
        {
          "text": "The state, accuracy, and reason that are possible for geo-tracking’s current condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingStatus"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum": {
      "abstract": [
        {
          "text": "Values that are possible for the current accuracy of geo tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Accuracy"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Accuracy"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.Accuracy",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/high": {
      "abstract": [
        {
          "text": "Geo-tracking accuracy is high.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingAccuracyHigh"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.Accuracy.high",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum/high"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/low": {
      "abstract": [
        {
          "text": "Geo-tracking accuracy is low.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingAccuracyLow"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.Accuracy.low",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum/low"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/medium": {
      "abstract": [
        {
          "text": "Geo-tracking accuracy is average.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingAccuracyMedium"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.Accuracy.medium",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum/medium"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/undetermined": {
      "abstract": [
        {
          "text": "Geo-tracking accuracy is undetermined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undetermined"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/undetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoTrackingAccuracyUndetermined"
        }
      ],
      "role": "symbol",
      "title": "ARGeoTrackingStatus.Accuracy.undetermined",
      "type": "topic",
      "url": "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum/undetermined"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accuracies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/high",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/low",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/medium"
      ],
      "title": "Accuracies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARGeoTrackingAccuracyUndetermined"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracyUndetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accuracies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/high",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/low",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoTrackingStatus/Accuracy-swift.enum/medium"
              ],
              "title": "Accuracies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ARGeoTrackingAccuracyUndetermined"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1high/title",
          "value": "ARGeoTrackingAccuracyHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracyHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1low/title",
          "value": "ARGeoTrackingAccuracyLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracyLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/title",
          "value": "ARGeoTrackingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1undetermined/title",
          "value": "ARGeoTrackingAccuracyUndetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1undetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracyUndetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum/title",
          "value": "ARGeoTrackingAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1medium/title",
          "value": "ARGeoTrackingAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoTrackingStatus~1Accuracy-swift.enum~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoTrackingAccuracyMedium"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum/undetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/argeotrackingstatus/accuracy-swift.enum/undetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
