{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.matter/documentation/Matter","doc://com.apple.matter/documentation/Matter/MTRKeypair"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.matter/documentation/Matter/MTRKeypair/signMessageECDSA_RAW(_:)"},"metadata":{"modules":[{"name":"Matter"}],"externalID":"c:objc(pl)MTRKeypair(im)signMessageECDSA_RAW:","symbolKind":"method","platforms":[{"beta":false,"unavailable":false,"introducedAt":"16.1","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"16.1","name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"16.1","name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"13.0","name":"macOS","deprecated":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"16.1"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false,"introducedAt":"9.1"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"signMessageECDSA_RAW","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"navigatorTitle":[{"kind":"identifier","text":"signMessageECDSA_RAW:"}],"roleHeading":"Instance Method","role":"symbol","title":"signMessageECDSA_RAW(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signMessageECDSA_RAW","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","preciseIdentifier":"s:10Foundation4DataV"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","preciseIdentifier":"s:10Foundation4DataV"}]}]}],"variants":[{"paths":["/documentation/matter/mtrkeypair/signmessageecdsa_raw(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/matter/mtrkeypair/signmessageecdsa_raw(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSData":{"url":"/documentation/foundation/nsdata","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","abstract":[{"type":"text","text":"A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior."}],"role":"symbol","type":"topic","title":"NSData","kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSData"}]},"doc://com.apple.matter/documentation/Matter/MTRKeypair/signMessageECDSA_RAW(_:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signMessageECDSA_RAW"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"kind":"symbol","title":"signMessageECDSA_RAW(_:)","identifier":"doc://com.apple.matter/documentation/Matter/MTRKeypair/signMessageECDSA_RAW(_:)","navigatorTitle":[{"kind":"identifier","text":"signMessageECDSA_RAW:"}],"url":"/documentation/matter/mtrkeypair/signmessageecdsa_raw(_:)","type":"topic"},"doc://com.apple.matter/documentation/Matter":{"abstract":[{"text":"Communicate with and control smart home devices from a variety of manufacturers.","type":"text"}],"type":"topic","role":"collection","kind":"symbol","url":"/documentation/matter","title":"Matter","identifier":"doc://com.apple.matter/documentation/Matter"},"doc://com.apple.matter/documentation/Matter/MTRKeypair":{"abstract":[],"role":"symbol","identifier":"doc://com.apple.matter/documentation/Matter/MTRKeypair","url":"/documentation/matter/mtrkeypair","kind":"symbol","title":"MTRKeypair","navigatorTitle":[{"kind":"identifier","text":"MTRKeypair"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MTRKeypair"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"type":"topic","title":"Data","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Data"}],"abstract":[{"type":"text","text":"A byte buffer in memory."}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","role":"symbol","url":"/documentation/foundation/data"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"16.1","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"16.1","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"16.1","unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"13.0","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"16.1"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"},{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false,"introducedAt":"9.1"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"signMessageECDSA_RAW:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"signMessageECDSA_RAW:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.matter/documentation/Matter","doc://com.apple.matter/documentation/Matter/MTRKeypair"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"signMessageECDSA_RAW:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}},{"op":"replace","value":[{"type":"text","text":"A static byte buffer in memory."}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract"},{"op":"replace","value":"signMessageECDSA_RAW:","path":"/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair~1signMessageECDSA_RAW(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"signMessageECDSA_RAW:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair~1signMessageECDSA_RAW(_:)/fragments"},{"op":"replace","value":"MTRKeypair","path":"/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair/title"},{"op":"replace","value":[{"text":"MTRKeypair","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MTRKeypair"}],"path":"/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRKeypair/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}