{
  "abstract": [
    {
      "text": "An object that controls participant access and permission options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKAllowedSharingOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKAllowedSharingOptions"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKAllowedSharingOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CKAllowedSharingOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Register an instance of this class with an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or when preparing a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/ExportedShare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " before your app invokes the share sheet. The share sheet uses the registered ",
              "type": "text"
            },
            {
              "code": "CKAllowedSharingOptions",
              "type": "codeVoice"
            },
            {
              "text": " object to let the user choose between the allowed options when sharing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions": {
      "abstract": [
        {
          "text": "An object that controls participant access and permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "role": "symbol",
      "title": "CKAllowedSharingOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can share publicly or privately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedParticipantAccessOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantAccessOption",
          "text": "CKSharingParticipantAccessOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedParticipantAccessOptions"
        }
      ],
      "role": "symbol",
      "title": "allowedParticipantAccessOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/allowedparticipantaccessoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can grant read-only or write access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedParticipantPermissionOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedParticipantPermissionOptions"
        }
      ],
      "role": "symbol",
      "title": "allowedParticipantPermissionOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/allowedparticipantpermissionoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)": {
      "abstract": [
        {
          "text": "Creates and initializes an allowed sharing options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allowedParticipantPermissionOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
          "text": "CKSharingParticipantPermissionOption"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allowedParticipantAccessOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantAccessOption",
          "text": "CKSharingParticipantAccessOption"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAllowedParticipantPermissionOptions:allowedParticipantAccessOptions:"
        }
      ],
      "role": "symbol",
      "title": "init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/init(allowedparticipantpermissionoptions:allowedparticipantaccessoptions:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard": {
      "abstract": [
        {
          "text": "An object set to the most permissive sharing options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKAllowedSharingOptions",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standardOptions"
        }
      ],
      "role": "symbol",
      "title": "standard",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions/standard"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSharePreparationCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharePreparationCompletionHandler",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharepreparationcompletionhandler"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSharePreparationHandler"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharePreparationHandler",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharepreparationhandler"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation": {
      "abstract": [
        {
          "text": "A transfer representation the system uses to share an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShareTransferRepresentation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareTransferRepresentation"
        }
      ],
      "role": "symbol",
      "title": "CKShareTransferRepresentation",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharetransferrepresentation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/ExportedShare": {
      "abstract": [
        {
          "text": "An intermediate structure that returns an existing share or prepares a new one if it doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExportedShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/ExportedShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExportedShare"
        }
      ],
      "role": "symbol",
      "title": "CKShareTransferRepresentation.ExportedShare",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharetransferrepresentation/exportedshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantAccessOption": {
      "abstract": [
        {
          "text": "An object that controls participant access options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSharingParticipantAccessOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantAccessOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingParticipantAccessOption"
        }
      ],
      "role": "symbol",
      "title": "CKSharingParticipantAccessOption",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharingparticipantaccessoption"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption": {
      "abstract": [
        {
          "text": "An object that controls participant permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "role": "symbol",
      "title": "CKSharingParticipantPermissionOption",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharingparticipantpermissionoption"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver": {
      "abstract": [
        {
          "text": "An object the system uses to monitor changes in sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "role": "symbol",
      "title": "CKSystemSharingUIObserver",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users": {
      "abstract": [
        {
          "text": "Create and share private CloudKit data with other users by implementing the sharing UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing CloudKit Data with Other iCloud Users",
      "type": "topic",
      "url": "/documentation/cloudkit/sharing-cloudkit-data-with-other-icloud-users"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates your app supports CloudKit Sharing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharingSupported",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CKSharingSupported"
    },
    "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users": {
      "abstract": [
        {
          "text": "Use Core Data and CloudKit to synchronize data between devices of an iCloud user and share data between different iCloud users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Core Data objects between iCloud users",
      "type": "topic",
      "url": "/documentation/CoreData/sharing-core-data-objects-between-icloud-users"
    },
    "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController": {
      "abstract": [
        {
          "text": "A view controller that presents standard screens for adding and removing people from a CloudKit share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICloudSharingController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICloudSharingController",
      "type": "topic",
      "url": "/documentation/UIKit/UICloudSharingController"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider": {
      "abstract": [
        {
          "text": "An item provider for conveying data or a file between processes during drag-and-drop or copy-and-paste activities, or from a host app to an app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSItemProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProvider",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collaboration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
        "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
        "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported"
      ],
      "title": "Collaboration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-sharing-options",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)"
      ],
      "title": "Creating sharing options"
    },
    {
      "anchor": "Using-the-standard-options",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard"
      ],
      "title": "Using the standard options"
    },
    {
      "anchor": "Configuring-the-options",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantAccessOption",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption"
      ],
      "title": "Configuring the options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKAllowedSharingOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-sharing-options",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)"
              ],
              "title": "Creating sharing options"
            },
            {
              "anchor": "Using-the-standard-options",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/standard"
              ],
              "title": "Using the standard options"
            },
            {
              "anchor": "Configuring-the-options",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantAccessOptions",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions/allowedParticipantPermissionOptions",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantAccessOption",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption"
              ],
              "title": "Configuring the options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Collaboration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
                "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
                "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported"
              ],
              "title": "Collaboration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKAllowedSharingOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/title",
          "value": "CKAllowedSharingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption/title",
          "value": "CKSharingParticipantPermissionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantPermissionOptions/title",
          "value": "allowedParticipantPermissionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantPermissionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedParticipantPermissionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)/title",
          "value": "initWithAllowedParticipantPermissionOptions:allowedParticipantAccessOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1init(allowedParticipantPermissionOptions:allowedParticipantAccessOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAllowedParticipantPermissionOptions:allowedParticipantAccessOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantAccessOptions/title",
          "value": "allowedParticipantAccessOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1allowedParticipantAccessOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedParticipantAccessOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/title",
          "value": "CKShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1standard/title",
          "value": "standardOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standardOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/title",
          "value": "CKSystemSharingUIObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantAccessOption/title",
          "value": "CKSharingParticipantAccessOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantAccessOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantAccessOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantAccessOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantAccessOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICloudSharingController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICloudSharingController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckallowedsharingoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckallowedsharingoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
