{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8CloudKit40CKContainer_Application_PermissionStatusa",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKContainer_Application_PermissionStatus"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKContainer_Application_PermissionStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "8.0",
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "8.0",
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "13.1",
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "10.10",
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "9.0",
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "introducedAt": "3.0",
        "message": "renamed to CKContainer.ApplicationPermissionStatus",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CKContainer_Application_PermissionStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKContainer_Application_PermissionStatus"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKContainer",
              "text": "CKContainer"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKApplicationPermissionStatus",
              "text": "ApplicationPermissionStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus": {
      "abstract": [
        {
          "text": "Constants that represent the status of a permission.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationPermissionStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer/ApplicationPermissionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationPermissionStatus"
        }
      ],
      "role": "symbol",
      "title": "CKContainer.ApplicationPermissionStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer/applicationpermissionstatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionBlock"
        }
      ],
      "role": "symbol",
      "title": "CKContainer_Application_PermissionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer_application_permissionblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionStatus"
        }
      ],
      "role": "symbol",
      "title": "CKContainer_Application_PermissionStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer_application_permissionstatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_Permissions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer_Application_Permissions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_Permissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer_Application_Permissions"
        }
      ],
      "role": "symbol",
      "title": "CKContainer_Application_Permissions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer_application_permissions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord_Reference_Action": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecord_Reference_Action"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord_Reference_Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecord_Reference_Action"
        }
      ],
      "role": "symbol",
      "title": "CKRecord_Reference_Action",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord_reference_action"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_AcceptanceStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_AcceptanceStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_AcceptanceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_AcceptanceStatus"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_AcceptanceStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_acceptancestatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_ParticipantType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_ParticipantType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_ParticipantType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_ParticipantType"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_ParticipantType",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_participanttype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Permission": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Permission"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Permission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Permission"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_Permission",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_permission"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Role": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Role"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Role",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Role"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_Role",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_role"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-type-aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionBlock",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_Permissions",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord_Reference_Action",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_AcceptanceStatus",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_ParticipantType",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Permission",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Role"
      ],
      "title": "Deprecated type aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/title",
          "value": "CKContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus/title",
          "value": "CKApplicationPermissionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer~1ApplicationPermissionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKApplicationPermissionStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckcontainer_application_permissionstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
