{
  "abstract": [
    {
      "text": "An operation for fetching subscriptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKFetchSubscriptionsOperation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKFetchSubscriptionsOperation"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKFetchSubscriptionsOperation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CKFetchSubscriptionsOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKFetchSubscriptionsOperation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A fetch subscriptions operation retrieves subscriptions (with IDs you already know) from iCloud and can fetch all subscriptions for the current user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You might fetch subscriptions so you can examine or modify their parameters — for example, to adjust the delivery options for push notifications that the subscription generates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you assign a handler to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/operation/1408085-completionblock",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, the operation calls it after it executes and passes it the results. Use the handler to perform any housekeeping tasks for the operation. The handler you specify should manage any failures, whether due to an error or an explicit cancellation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation": {
      "abstract": [
        {
          "text": "The abstract base class for operations that act upon databases in CloudKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabaseOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabaseOperation"
        }
      ],
      "role": "symbol",
      "title": "CKDatabaseOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabaseoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation": {
      "abstract": [
        {
          "text": "An operation for fetching subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKFetchSubscriptionsOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKFetchSubscriptionsOperation"
        }
      ],
      "role": "symbol",
      "title": "CKFetchSubscriptionsOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchAllSubscriptionsOperation()": {
      "abstract": [
        {
          "text": "Returns an operation that fetches all of the user’s subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAllSubscriptionsOperation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchAllSubscriptionsOperation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAllSubscriptionsOperation"
        }
      ],
      "role": "symbol",
      "title": "fetchAllSubscriptionsOperation()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/fetchallsubscriptionsoperation()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionCompletionBlock-207ep": {
      "abstract": [
        {
          "text": "The block to execute after the operation fetches the subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fetchSubscriptionCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionCompletionBlock-207ep",
      "kind": "symbol",
      "role": "symbol",
      "title": "fetchSubscriptionCompletionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/fetchsubscriptioncompletionblock-207ep"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionCompletionBlock-6hhpi": {
      "abstract": [
        {
          "text": "The block to execute with the fetch results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchSubscriptionCompletionBlock"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionCompletionBlock-6hhpi",
      "kind": "symbol",
      "role": "symbol",
      "title": "fetchSubscriptionCompletionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/fetchsubscriptioncompletionblock-6hhpi"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionsResultBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchSubscriptionsResultBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionsResultBlock",
      "kind": "symbol",
      "role": "symbol",
      "title": "fetchSubscriptionsResultBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/fetchsubscriptionsresultblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init()": {
      "abstract": [
        {
          "text": "Creates an empty fetch subscriptions operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/init()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init(subscriptionIDs:)": {
      "abstract": [
        {
          "text": "Creates an operation for fetching the specified subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "subscriptionIDs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init(subscriptionIDs:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(subscriptionIDs:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/init(subscriptionids:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/initWithSubscriptionIDs:": {
      "abstract": [
        {
          "text": "Creates an operation for fetching the specified subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithSubscriptionIDs:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/initWithSubscriptionIDs:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSubscriptionIDs:"
        }
      ],
      "role": "symbol",
      "title": "initWithSubscriptionIDs:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/initwithsubscriptionids:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/perSubscriptionCompletionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "perSubscriptionCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/perSubscriptionCompletionBlock",
      "kind": "symbol",
      "role": "symbol",
      "title": "perSubscriptionCompletionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/persubscriptioncompletionblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/perSubscriptionResultBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perSubscriptionResultBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/perSubscriptionResultBlock",
      "kind": "symbol",
      "role": "symbol",
      "title": "perSubscriptionResultBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/persubscriptionresultblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/subscriptionIDs-17f4q": {
      "abstract": [
        {
          "text": "The IDs of the subscriptions to fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionIDs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/subscriptionIDs-17f4q",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscriptionIDs",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/subscriptionids-17f4q"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/subscriptionIDs-714ct": {
      "abstract": [
        {
          "text": "The IDs of the subscriptions to fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subscriptionIDs"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/subscriptionIDs-714ct",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscriptionIDs",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchsubscriptionsoperation/subscriptionids-714ct"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKModifySubscriptionsOperation": {
      "abstract": [
        {
          "text": "An operation for modifying one or more subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKModifySubscriptionsOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKModifySubscriptionsOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKModifySubscriptionsOperation"
        }
      ],
      "role": "symbol",
      "title": "CKModifySubscriptionsOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckmodifysubscriptionsoperation"
    },
    "doc://com.apple.documentation/documentation/foundation/operation/1408085-completionblock": {
      "abstract": [
        {
          "text": "The block to execute after the operation’s main task is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": () -> Void)?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/operation/1408085-completionblock",
      "kind": "symbol",
      "role": "symbol",
      "title": "completionBlock",
      "type": "topic",
      "url": "/documentation/foundation/operation/1408085-completionblock"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Subscription-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKModifySubscriptionsOperation"
      ],
      "title": "Subscription Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Fetch-Subscriptions-Operation",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init(subscriptionIDs:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init()"
      ],
      "title": "Creating a Fetch Subscriptions Operation"
    },
    {
      "anchor": "Getting-All-Subscriptions",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchAllSubscriptionsOperation()"
      ],
      "title": "Getting All Subscriptions"
    },
    {
      "anchor": "Configuring-the-Fetch-Subscriptions-Operation",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/subscriptionIDs-17f4q"
      ],
      "title": "Configuring the Fetch Subscriptions Operation"
    },
    {
      "anchor": "Processing-the-Fetch-Subscription-Results",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionCompletionBlock-6hhpi"
      ],
      "title": "Processing the Fetch Subscription Results"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionsResultBlock",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/perSubscriptionResultBlock"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKFetchSubscriptionsOperation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchSubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchSubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Fetch-Subscriptions-Operation",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/initWithSubscriptionIDs:",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/init()"
              ],
              "title": "Creating a Fetch Subscriptions Operation"
            },
            {
              "anchor": "Getting-All-Subscriptions",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchAllSubscriptionsOperation()"
              ],
              "title": "Getting All Subscriptions"
            },
            {
              "anchor": "Configuring-the-Fetch-Subscriptions-Operation",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/subscriptionIDs-714ct"
              ],
              "title": "Configuring the Fetch Subscriptions Operation"
            },
            {
              "anchor": "Processing-the-Fetch-Subscription-Results",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/fetchSubscriptionCompletionBlock-207ep"
              ],
              "title": "Processing the Fetch Subscription Results"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchSubscriptionsOperation/perSubscriptionCompletionBlock"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Subscription-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKModifySubscriptionsOperation"
              ],
              "title": "Subscription Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKFetchSubscriptionsOperation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CKDatabaseOperation",
                    "text": "CKDatabaseOperation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifySubscriptionsOperation/title",
          "value": "CKModifySubscriptionsOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifySubscriptionsOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKModifySubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKModifySubscriptionsOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKModifySubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation/title",
          "value": "CKFetchSubscriptionsOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchSubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchSubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation~1fetchAllSubscriptionsOperation()/title",
          "value": "fetchAllSubscriptionsOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchSubscriptionsOperation~1fetchAllSubscriptionsOperation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchAllSubscriptionsOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseOperation/title",
          "value": "CKDatabaseOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckfetchsubscriptionsoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckfetchsubscriptionsoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
