{
  "abstract": [
    {
      "text": "The abstract base class for CloudKit notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKNotification"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CKNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use subclasses of ",
              "type": "text"
            },
            {
              "code": "CKNotification",
              "type": "codeVoice"
            },
            {
              "text": " to extract data from push notifications that the system receives, or to fetch a container’s previous push notifications. In both cases, the object indicates the changed data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "CKNotification",
              "type": "codeVoice"
            },
            {
              "text": " is an abstract class. When you create a notification from a payload dictionary, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/init(fromRemoteNotificationDictionary:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method returns an instance of the appropriate subclass. Similarly, when you fetch notifications from a container, you receive instances of a concrete subclass. ",
              "type": "text"
            },
            {
              "code": "CKNotification",
              "type": "codeVoice"
            },
            {
              "text": " provides information about the push notification and its method of delivery. Subclasses contain specific data that provides the changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseNotification": {
      "abstract": [
        {
          "text": "A notification that triggers when the contents of a database change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabaseNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabaseNotification"
        }
      ],
      "role": "symbol",
      "title": "CKDatabaseNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabasenotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation": {
      "abstract": [
        {
          "text": "The abstract base class for operations that act upon databases in CloudKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDatabaseOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDatabaseOperation"
        }
      ],
      "role": "symbol",
      "title": "CKDatabaseOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdatabaseoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification": {
      "abstract": [
        {
          "text": "The abstract base class for CloudKit notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotification"
        }
      ],
      "role": "symbol",
      "title": "CKNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a push notification that a container sends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/id"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the type of event that generates the push notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationType"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertActionLocalizationKey": {
      "abstract": [
        {
          "text": "The key that identifies the localized string for the notification’s action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertActionLocalizationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertActionLocalizationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertActionLocalizationKey"
        }
      ],
      "role": "symbol",
      "title": "alertActionLocalizationKey",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/alertactionlocalizationkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertBody": {
      "abstract": [
        {
          "text": "The notification’s alert body.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertBody"
        }
      ],
      "role": "symbol",
      "title": "alertBody",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/alertbody"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLaunchImage": {
      "abstract": [
        {
          "text": "The filename of an image to use as a launch image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertLaunchImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLaunchImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertLaunchImage"
        }
      ],
      "role": "symbol",
      "title": "alertLaunchImage",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/alertlaunchimage"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationArgs": {
      "abstract": [
        {
          "text": "The fields for building a notification’s alert.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertLocalizationArgs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationArgs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertLocalizationArgs"
        }
      ],
      "role": "symbol",
      "title": "alertLocalizationArgs",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/alertlocalizationargs"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationKey": {
      "abstract": [
        {
          "text": "The key that identifies the localized text for the alert body.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertLocalizationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alertLocalizationKey"
        }
      ],
      "role": "symbol",
      "title": "alertLocalizationKey",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/alertlocalizationkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/badge": {
      "abstract": [
        {
          "text": "The value that the app icon’s badge displays.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/badge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "badge"
        }
      ],
      "role": "symbol",
      "title": "badge",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/badge"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/category": {
      "abstract": [
        {
          "text": "The name of the action group that corresponds to this notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "category"
        }
      ],
      "role": "symbol",
      "title": "category",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/category"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier": {
      "abstract": [
        {
          "text": "The ID of the container with the content that triggers the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containerIdentifier"
        }
      ],
      "role": "symbol",
      "title": "containerIdentifier",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/containeridentifier"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/init(fromRemoteNotificationDictionary:)": {
      "abstract": [
        {
          "text": "Creates a new notification using the specified payload data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "fromRemoteNotificationDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/init(fromRemoteNotificationDictionary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationFromRemoteNotificationDictionary:"
        }
      ],
      "role": "symbol",
      "title": "init(fromRemoteNotificationDictionary:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/init(fromremotenotificationdictionary:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/isPruned": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system removes some push notification content before delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPruned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/isPruned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPruned"
        }
      ],
      "role": "symbol",
      "title": "isPruned",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/ispruned"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID": {
      "abstract": [
        {
          "text": "The notification’s ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKNotification",
          "text": "CKNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKNotificationID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationID"
        }
      ],
      "role": "symbol",
      "title": "notificationID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property": {
      "abstract": [
        {
          "text": "The type of event that generates the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKNotification",
          "text": "CKNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKNotificationType",
          "text": "NotificationType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationType"
        }
      ],
      "role": "symbol",
      "title": "notificationType",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.property"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/soundName": {
      "abstract": [
        {
          "text": "The name of the sound file to play when a notification arrives.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soundName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/soundName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "soundName"
        }
      ],
      "role": "symbol",
      "title": "soundName",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/soundname"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionID-16ygj": {
      "abstract": [
        {
          "text": "The ID of the subscription that triggers the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKSubscription",
          "text": "CKSubscription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14CKSubscriptionC8CloudKitE2IDa",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionID-16ygj",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscriptionID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/subscriptionid-16ygj"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionID-90zhj": {
      "abstract": [
        {
          "text": "The ID of the subscription that triggers the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subscriptionID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionID-90zhj",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscriptionID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/subscriptionid-90zhj"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionOwnerUserRecordID": {
      "abstract": [
        {
          "text": "The ID of the user record that creates the subscription that generates the push notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionOwnerUserRecordID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionOwnerUserRecordID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptionOwnerUserRecordID"
        }
      ],
      "role": "symbol",
      "title": "subscriptionOwnerUserRecordID",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/subscriptionowneruserrecordid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitle": {
      "abstract": [
        {
          "text": "The notification’s subtitle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/subtitle"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationArgs": {
      "abstract": [
        {
          "text": "The fields for building a notification’s subtitle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleLocalizationArgs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationArgs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitleLocalizationArgs"
        }
      ],
      "role": "symbol",
      "title": "subtitleLocalizationArgs",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/subtitlelocalizationargs"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationKey": {
      "abstract": [
        {
          "text": "The key that identifies the localized string for the notification’s subtitle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleLocalizationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitleLocalizationKey"
        }
      ],
      "role": "symbol",
      "title": "subtitleLocalizationKey",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/subtitlelocalizationkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/title": {
      "abstract": [
        {
          "text": "The notification’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/title"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationArgs": {
      "abstract": [
        {
          "text": "The fields for building a notification’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleLocalizationArgs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationArgs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleLocalizationArgs"
        }
      ],
      "role": "symbol",
      "title": "titleLocalizationArgs",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/titlelocalizationargs"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationKey": {
      "abstract": [
        {
          "text": "The key that identifies the localized string for the notification’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleLocalizationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleLocalizationKey"
        }
      ],
      "role": "symbol",
      "title": "titleLocalizationKey",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/titlelocalizationkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKQueryNotification": {
      "abstract": [
        {
          "text": "A notification that triggers when a record that matches the subscription’s predicate changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKQueryNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKQueryNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKQueryNotification"
        }
      ],
      "role": "symbol",
      "title": "CKQueryNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/ckquerynotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZoneNotification": {
      "abstract": [
        {
          "text": "A notification that triggers when the contents of a record zone change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordZoneNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZoneNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordZoneNotification"
        }
      ],
      "role": "symbol",
      "title": "CKRecordZoneNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordzonenotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription": {
      "abstract": [
        {
          "text": "An abstract base class for subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSubscription"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSubscription"
        }
      ],
      "role": "symbol",
      "title": "CKSubscription",
      "type": "topic",
      "url": "/documentation/cloudkit/cksubscription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseNotification",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKQueryNotification",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZoneNotification"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Base-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation"
      ],
      "title": "Base Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Notification",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/init(fromRemoteNotificationDictionary:)"
      ],
      "title": "Creating a Notification"
    },
    {
      "anchor": "Identifying-the-Notification",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier"
      ],
      "title": "Identifying the Notification"
    },
    {
      "anchor": "Getting-the-Notifications-Status",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/isPruned"
      ],
      "title": "Getting the Notification’s Status"
    },
    {
      "anchor": "Accessing-the-Notification-Info",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertBody",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationArgs",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertActionLocalizationKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLaunchImage",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/soundName",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/badge",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/category",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionID-16ygj",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionOwnerUserRecordID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/title",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationArgs",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitle",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationArgs"
      ],
      "title": "Accessing the Notification Info"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Notification",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/init(fromRemoteNotificationDictionary:)"
              ],
              "title": "Creating a Notification"
            },
            {
              "anchor": "Identifying-the-Notification",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/ID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/notificationType-swift.property",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/containerIdentifier"
              ],
              "title": "Identifying the Notification"
            },
            {
              "anchor": "Getting-the-Notifications-Status",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/isPruned"
              ],
              "title": "Getting the Notification’s Status"
            },
            {
              "anchor": "Accessing-the-Notification-Info",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertBody",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLocalizationArgs",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertActionLocalizationKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/alertLaunchImage",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/soundName",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/badge",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/category",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionID-90zhj",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subscriptionOwnerUserRecordID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/title",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/titleLocalizationArgs",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitle",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/subtitleLocalizationArgs"
              ],
              "title": "Accessing the Notification Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseNotification",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKQueryNotification",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZoneNotification"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Base-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSubscription",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKDatabaseOperation"
              ],
              "title": "Base Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKNotification"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subtitleLocalizationKey/title",
          "value": "subtitleLocalizationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subtitleLocalizationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitleLocalizationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1containerIdentifier/title",
          "value": "containerIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1containerIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "containerIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1soundName/title",
          "value": "soundName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1soundName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "soundName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertLocalizationArgs/title",
          "value": "alertLocalizationArgs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertLocalizationArgs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertLocalizationArgs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKQueryNotification/title",
          "value": "CKQueryNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKQueryNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKQueryNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKQueryNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKQueryNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertLaunchImage/title",
          "value": "alertLaunchImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertLaunchImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertLaunchImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1titleLocalizationArgs/title",
          "value": "titleLocalizationArgs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1titleLocalizationArgs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleLocalizationArgs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertBody/title",
          "value": "alertBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subtitleLocalizationArgs/title",
          "value": "subtitleLocalizationArgs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subtitleLocalizationArgs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitleLocalizationArgs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1init(fromRemoteNotificationDictionary:)/title",
          "value": "notificationFromRemoteNotificationDictionary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1init(fromRemoteNotificationDictionary:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "notificationFromRemoteNotificationDictionary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1isPruned/title",
          "value": "isPruned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1isPruned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isPruned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subtitle/title",
          "value": "subtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertLocalizationKey/title",
          "value": "alertLocalizationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertLocalizationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertLocalizationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1ID/title",
          "value": "CKNotificationID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1ID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseNotification/title",
          "value": "CKDatabaseNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZoneNotification/title",
          "value": "CKRecordZoneNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZoneNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZoneNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZoneNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZoneNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/title",
          "value": "CKNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subscriptionOwnerUserRecordID/title",
          "value": "subscriptionOwnerUserRecordID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1subscriptionOwnerUserRecordID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptionOwnerUserRecordID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSubscription/title",
          "value": "CKSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSubscription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1badge/title",
          "value": "badge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1badge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "badge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1titleLocalizationKey/title",
          "value": "titleLocalizationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1titleLocalizationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleLocalizationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationID/title",
          "value": "notificationID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertActionLocalizationKey/title",
          "value": "alertActionLocalizationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1alertActionLocalizationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alertActionLocalizationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/title",
          "value": "CKNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseOperation/title",
          "value": "CKDatabaseOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDatabaseOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDatabaseOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1category/title",
          "value": "category"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationType-swift.property/title",
          "value": "notificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1notificationType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cknotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cknotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
