{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreatorUserRecordIDKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CKRecordCreatorUserRecordIDKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CKRecordCreatorUserRecordIDKey"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKRecordCreatorUserRecordIDKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CKRecordCreatorUserRecordIDKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CKRecordFieldKey",
              "text": "CKRecordFieldKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKRecordCreatorUserRecordIDKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys": {
      "abstract": [
        {
          "text": "Returns an array of the record’s keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "role": "symbol",
      "title": "allKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/allkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys": {
      "abstract": [
        {
          "text": "Returns an array of keys with recent changes to their values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "role": "symbol",
      "title": "changedKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/changedkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/objectForKey:": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/objectForKey:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "role": "symbol",
      "title": "objectForKey:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/objectforkey:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKey:": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKey:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKey:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKey:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKey:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/setobject:forkey:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKeyedSubscript:": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/setobject:forkeyedsubscript:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/subscript(_:)-51whk"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreationDateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordCreationDateKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreationDateKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordCreationDateKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordcreationdatekey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreatorUserRecordIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordCreatorUserRecordIDKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreatorUserRecordIDKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordCreatorUserRecordIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordcreatoruserrecordidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey": {
      "abstract": [
        {
          "text": "A data type that CloudKit requires for record field names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordFieldKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordFieldKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordfieldkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting": {
      "abstract": [
        {
          "text": "A protocol for managing the key-value pairs of a CloudKit record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueSetting"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueSetting"
        }
      ],
      "role": "symbol",
      "title": "CKRecordKeyValueSetting",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordLastModifiedUserRecordIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordLastModifiedUserRecordIDKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordLastModifiedUserRecordIDKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordLastModifiedUserRecordIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordlastmodifieduserrecordidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordModificationDateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordModificationDateKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordModificationDateKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordModificationDateKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordmodificationdatekey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordParentKey-2kx8l": {
      "abstract": [
        {
          "text": "The key constant that a record uses for its parent reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordParentKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordParentKey-2kx8l",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordParentKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordparentkey-2kx8l"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordRecordIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordRecordIDKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordRecordIDKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordRecordIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordrecordidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordShareKey-rrat": {
      "abstract": [
        {
          "text": "The key constant that a record uses for its share reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordShareKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordShareKey-rrat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordShareKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordsharekey-rrat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Records-Fields",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/objectForKey:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKey:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKeyedSubscript:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreationDateKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordLastModifiedUserRecordIDKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordModificationDateKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordRecordIDKey",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordParentKey-2kx8l",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordShareKey-rrat"
      ],
      "title": "Accessing the Record’s Fields"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/title",
          "value": "CKRecordKeyValueSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1subscript(_:)-51whk/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1subscript(_:)-51whk/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckrecordcreatoruserrecordidkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
