{
  "abstract": [
    {
      "text": "A protocol for managing the key-value pairs of a CloudKit record.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CKRecordKeyValueSetting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKRecordKeyValueSetting"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKRecordKeyValueSetting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CKRecordKeyValueSetting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord": {
      "abstract": [
        {
          "text": "A collection of key-value pairs that store your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "role": "symbol",
      "title": "CKRecord",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys": {
      "abstract": [
        {
          "text": "Returns an array of the record’s keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "role": "symbol",
      "title": "allKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/allkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys()": {
      "abstract": [
        {
          "text": "Returns an array of the record’s keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8CKRecordC8CloudKitE8FieldKeya",
          "text": "FieldKey"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys()",
      "kind": "symbol",
      "role": "symbol",
      "title": "allKeys()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/allkeys()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys": {
      "abstract": [
        {
          "text": "Returns an array of keys with recent changes to their values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "role": "symbol",
      "title": "changedKeys",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/changedkeys"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys()": {
      "abstract": [
        {
          "text": "Returns an array of keys with recent changes to their values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8CKRecordC8CloudKitE8FieldKeya",
          "text": "FieldKey"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys()",
      "kind": "symbol",
      "role": "symbol",
      "title": "changedKeys()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/changedkeys()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/object(forKey:)": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8CKRecordC8CloudKitE8FieldKeya",
          "text": "FieldKey"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/object(forKey:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "object(forKey:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/object(forkey:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/objectForKey:": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/objectForKey:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "role": "symbol",
      "title": "objectForKey:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/objectforkey:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject(_:forKey:)": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setObject"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8CKRecordC8CloudKitE8FieldKeya",
          "text": "FieldKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject(_:forKey:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setObject(_:forKey:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/setobject(_:forkey:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKey:": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKey:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKey:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKey:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKey:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/setobject:forkey:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKeyedSubscript:": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/setobject:forkeyedsubscript:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-4g91i": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8CKRecordC8CloudKitE8FieldKeya",
          "text": "FieldKey"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-4g91i",
      "kind": "symbol",
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/subscript(_:)-4g91i"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/subscript(_:)-51whk"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreationDateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordCreationDateKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreationDateKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordCreationDateKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordcreationdatekey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreatorUserRecordIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordCreatorUserRecordIDKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreatorUserRecordIDKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordCreatorUserRecordIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordcreatoruserrecordidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueIterator": {
      "abstract": [
        {
          "text": "An iterator of the record’s key-value pairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueIterator"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueIterator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueIterator"
        }
      ],
      "role": "symbol",
      "title": "CKRecordKeyValueIterator",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvalueiterator"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting": {
      "abstract": [
        {
          "text": "A protocol for managing the key-value pairs of a CloudKit record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueSetting"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueSetting"
        }
      ],
      "role": "symbol",
      "title": "CKRecordKeyValueSetting",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()": {
      "abstract": [
        {
          "text": "Returns an array of the record’s keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "allKeys()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/allkeys()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()": {
      "abstract": [
        {
          "text": "Returns an array of keys with recent changes to their values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "changedKeys()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/changedkeys()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "object(forKey:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/object(forkey:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setObject"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setObject(_:forKey:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/setobject(_:forkey:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject:forKeyedSubscript:": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject:forKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/setobject:forkeyedsubscript:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "defaultImplementations": 2,
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/subscript(_:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordLastModifiedUserRecordIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordLastModifiedUserRecordIDKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordLastModifiedUserRecordIDKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordLastModifiedUserRecordIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordlastmodifieduserrecordidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordModificationDateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordModificationDateKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordModificationDateKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordModificationDateKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordmodificationdatekey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordParentKey-2kx8l": {
      "abstract": [
        {
          "text": "The key constant that a record uses for its parent reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordParentKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordParentKey-2kx8l",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordParentKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordparentkey-2kx8l"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordRecordIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordRecordIDKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordRecordIDKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordRecordIDKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordrecordidkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordShareKey-rrat": {
      "abstract": [
        {
          "text": "The key constant that a record uses for its share reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordShareKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordShareKey-rrat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordShareKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordsharekey-rrat"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordValue-swift.typealias": {
      "abstract": [
        {
          "text": "A data type for objects that CloudKit stores on the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordValue"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordValue-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordValue"
        }
      ],
      "role": "symbol",
      "title": "CKRecordValue",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordvalue-swift.typealias"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordValueProtocol": {
      "abstract": [
        {
          "text": "A description of a CloudKit record value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordValueProtocol"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordValueProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordValueProtocol"
        }
      ],
      "role": "symbol",
      "title": "CKRecordValueProtocol",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordvalueprotocol"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Records-Fields",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/object(forKey:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-4g91i",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject(_:forKey:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys()",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys()",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueIterator",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordValueProtocol",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordValue-swift.typealias"
      ],
      "title": "Accessing the Record’s Fields"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-a-Records-Fields",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()"
      ],
      "title": "Accessing a Record’s Fields"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKRecordKeyValueSetting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-a-Records-Fields",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject:forKeyedSubscript:",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()"
              ],
              "title": "Accessing a Record’s Fields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Records-Fields",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/objectForKey:",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/subscript(_:)-51whk",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKey:",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/setObject:forKeyedSubscript:",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/allKeys",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/changedKeys",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreationDateKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordCreatorUserRecordIDKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordLastModifiedUserRecordIDKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordModificationDateKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordRecordIDKey",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordParentKey-2kx8l",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordShareKey-rrat"
              ],
              "title": "Accessing the Record’s Fields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKRecordKeyValueSetting"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/title",
          "value": "CKRecordKeyValueSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/title",
          "value": "CKRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1subscript(_:)-51whk/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1subscript(_:)-51whk/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/title",
          "value": "CKShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1object(forKey:)/title",
          "value": "objectForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1object(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1changedKeys()/title",
          "value": "changedKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1changedKeys()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changedKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1setObject(_:forKey:)/title",
          "value": "setObject:forKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1setObject(_:forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setObject:forKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1allKeys()/title",
          "value": "allKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1allKeys()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckrecordkeyvaluesetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckrecordkeyvaluesetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
