{
  "abstract": [
    {
      "text": "The system type that identifies a user record.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordTypeUserRecord-49k30"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CKRecordTypeUserRecord",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CKRecordTypeUserRecord"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKRecordTypeUserRecord"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CKRecordTypeUserRecord"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CKRecordType",
              "text": "CKRecordType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKRecordTypeUserRecord"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "CloudKit automatically creates a user record for each unique user of the app. User records are empty initially. You can add data to the user record using the same rules that apply for all records. Specifically, the type of data for a particular field name must be the same in all user records. However, you can’t create new user records using this record type and you can’t query for records of this type. To locate user records, you must know the ID of the user record or use the methods that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides to discover user records.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:": {
      "abstract": [
        {
          "text": "Creates a new record of the specified type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithRecordType:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRecordType:"
        }
      ],
      "role": "symbol",
      "title": "initWithRecordType:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/initwithrecordtype:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:recordID:": {
      "abstract": [
        {
          "text": "Creates a record using an ID that you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithRecordType:recordID:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:recordID:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRecordType:recordID:"
        }
      ],
      "role": "symbol",
      "title": "initWithRecordType:recordID:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/initwithrecordtype:recordid:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:zoneID:": {
      "abstract": [
        {
          "text": "Creates a record in the specified zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithRecordType:zoneID:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:zoneID:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRecordType:zoneID:"
        }
      ],
      "role": "symbol",
      "title": "initWithRecordType:zoneID:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/initwithrecordtype:zoneid:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey": {
      "abstract": [
        {
          "text": "A data type that CloudKit requires for record field names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordFieldKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordFieldKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordfieldkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordType": {
      "abstract": [
        {
          "text": "A data type that CloudKit requires for record types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordType",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordtype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordTypeShare-8b6yt": {
      "abstract": [
        {
          "text": "The system type that identifies a share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordTypeShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordTypeShare-8b6yt",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordTypeShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordtypeshare-8b6yt"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordTypeUserRecord-49k30": {
      "abstract": [
        {
          "text": "The system type that identifies a user record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordTypeUserRecord"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordTypeUserRecord-49k30",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordTypeUserRecord",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordtypeuserrecord-49k30"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Record",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:zoneID:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/initWithRecordType:recordID:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordType",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordTypeShare-8b6yt",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey"
      ],
      "title": "Creating a Record"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/title",
          "value": "CKContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckrecordtypeuserrecord-49k30"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
