{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CKSharePreparationHandler",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CKSharePreparationHandler"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKSharePreparationHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CKSharePreparationHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:BFv(#BFv(#*$objc(cs)CKShare#*$objc(cs)NSError))",
              "text": "void (^)(void (^)(CKShare *, NSError *))"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKSharePreparationHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions": {
      "abstract": [
        {
          "text": "An object that controls participant access and permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "role": "symbol",
      "title": "CKAllowedSharingOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSharePreparationCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharePreparationCompletionHandler",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharepreparationcompletionhandler"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSharePreparationHandler"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharePreparationHandler",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharepreparationhandler"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver": {
      "abstract": [
        {
          "text": "An object the system uses to monitor changes in sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "role": "symbol",
      "title": "CKSystemSharingUIObserver",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users": {
      "abstract": [
        {
          "text": "Create and share private CloudKit data with other users by implementing the sharing UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing CloudKit Data with Other iCloud Users",
      "type": "topic",
      "url": "/documentation/cloudkit/sharing-cloudkit-data-with-other-icloud-users"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates your app supports CloudKit Sharing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharingSupported",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CKSharingSupported"
    },
    "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users": {
      "abstract": [
        {
          "text": "Use Core Data and CloudKit to synchronize data between devices of an iCloud user and share data between different iCloud users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Core Data objects between iCloud users",
      "type": "topic",
      "url": "/documentation/CoreData/sharing-core-data-objects-between-icloud-users"
    },
    "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController": {
      "abstract": [
        {
          "text": "A view controller that presents standard screens for adding and removing people from a CloudKit share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICloudSharingController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICloudSharingController",
      "type": "topic",
      "url": "/documentation/UIKit/UICloudSharingController"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collaboration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
        "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
        "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported"
      ],
      "title": "Collaboration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICloudSharingController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICloudSharingController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/title",
          "value": "CKAllowedSharingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/title",
          "value": "CKShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/title",
          "value": "CKSystemSharingUIObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksharepreparationhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
