{
  "abstract": [
    {
      "text": "A transfer representation the system uses to share an item.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8CloudKit29CKShareTransferRepresentationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKShareTransferRepresentation"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKShareTransferRepresentation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CKShareTransferRepresentation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKShareTransferRepresentation"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "Item"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Item"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:16CoreTransferable0B0P",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:16CoreTransferable0B0P",
              "text": "Transferable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions": {
      "abstract": [
        {
          "text": "An object that controls participant access and permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "role": "symbol",
      "title": "CKAllowedSharingOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation": {
      "abstract": [
        {
          "text": "A transfer representation the system uses to share an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShareTransferRepresentation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareTransferRepresentation"
        }
      ],
      "role": "symbol",
      "title": "CKShareTransferRepresentation",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharetransferrepresentation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/ExportedShare": {
      "abstract": [
        {
          "text": "An intermediate structure that returns an existing share or prepares a new one if it doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExportedShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/ExportedShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExportedShare"
        }
      ],
      "role": "symbol",
      "title": "CKShareTransferRepresentation.ExportedShare",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharetransferrepresentation/exportedshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/init(exporter:)": {
      "abstract": [
        {
          "text": "Creates and initializes a transfer representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "exporter"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "text": "Item"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit29CKShareTransferRepresentationV",
          "text": "CKShareTransferRepresentation"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Item"
        },
        {
          "kind": "text",
          "text": ">."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit29CKShareTransferRepresentationV13ExportedShareV",
          "text": "ExportedShare"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/init(exporter:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(exporter:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharetransferrepresentation/init(exporter:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver": {
      "abstract": [
        {
          "text": "An object the system uses to monitor changes in sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "role": "symbol",
      "title": "CKSystemSharingUIObserver",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users": {
      "abstract": [
        {
          "text": "Create and share private CloudKit data with other users by implementing the sharing UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing CloudKit Data with Other iCloud Users",
      "type": "topic",
      "url": "/documentation/cloudkit/sharing-cloudkit-data-with-other-icloud-users"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates your app supports CloudKit Sharing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharingSupported",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CKSharingSupported"
    },
    "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users": {
      "abstract": [
        {
          "text": "Use Core Data and CloudKit to synchronize data between devices of an iCloud user and share data between different iCloud users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Core Data objects between iCloud users",
      "type": "topic",
      "url": "/documentation/CoreData/sharing-core-data-objects-between-icloud-users"
    },
    "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController": {
      "abstract": [
        {
          "text": "A view controller that presents standard screens for adding and removing people from a CloudKit share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICloudSharingController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICloudSharingController",
      "type": "topic",
      "url": "/documentation/UIKit/UICloudSharingController"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:16CoreTransferable0B0P": {
      "abstract": [
        {
          "text": "A protocol that describes how a type interacts with transport APIs such as drag and drop or copy and paste.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Transferable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:16CoreTransferable0B0P",
      "kind": "symbol",
      "role": "symbol",
      "title": "Transferable",
      "type": "topic",
      "url": "/documentation/CoreTransferable/Transferable"
    },
    "doc://com.externally.resolved.symbol/s:16CoreTransferable22TransferRepresentationP": {
      "abstract": [
        {
          "text": "A declarative description of the process of importing and exporting a transferable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransferRepresentation"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16CoreTransferable22TransferRepresentationP4ItemQa",
          "text": "Item"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:16CoreTransferable22TransferRepresentationP",
      "kind": "symbol",
      "role": "symbol",
      "title": "TransferRepresentation",
      "type": "topic",
      "url": "/documentation/CoreTransferable/TransferRepresentation"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:16CoreTransferable22TransferRepresentationP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collaboration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
        "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
        "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported"
      ],
      "title": "Collaboration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-transfer-representation",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/init(exporter:)"
      ],
      "title": "Creating a transfer representation"
    },
    {
      "anchor": "Accessing-transfer-representation-attributes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation/ExportedShare"
      ],
      "title": "Accessing transfer representation attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/title",
          "value": "CKSystemSharingUIObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/title",
          "value": "CKShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/title",
          "value": "CKAllowedSharingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICloudSharingController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICloudSharingController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksharetransferrepresentation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
