{
  "abstract": [
    {
      "text": "An object the system uses to monitor changes in sharing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKSystemSharingUIObserver",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKSystemSharingUIObserver"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKSystemSharingUIObserver"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CKSystemSharingUIObserver"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize a ",
              "type": "text"
            },
            {
              "code": "CKSystemSharingUIObserver",
              "type": "codeVoice"
            },
            {
              "text": " instance with your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when preparing to share an item using the share sheet. Use your implementation to update the local state of a shared item when your app receives a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or to delete a locally cached share when the system notifies your app about a share deletion.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system only propagates changes on the local device using ",
              "type": "text"
            },
            {
              "code": "CKSystemSharingUIObserver",
              "type": "codeVoice"
            },
            {
              "text": ". The system doesn’t notify your app about any remote changes on the server. For more information about how to keep your local cache in sync with remote changes, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/remote-records",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions": {
      "abstract": [
        {
          "text": "An object that controls participant access and permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAllowedSharingOptions"
        }
      ],
      "role": "symbol",
      "title": "CKAllowedSharingOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckallowedsharingoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer": {
      "abstract": [
        {
          "text": "A conduit to your app’s databases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer"
        }
      ],
      "role": "symbol",
      "title": "CKContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSharePreparationCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharePreparationCompletionHandler",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharepreparationcompletionhandler"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSharePreparationHandler"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharePreparationHandler",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharepreparationhandler"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation": {
      "abstract": [
        {
          "text": "A transfer representation the system uses to share an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShareTransferRepresentation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShareTransferRepresentation"
        }
      ],
      "role": "symbol",
      "title": "CKShareTransferRepresentation",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharetransferrepresentation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver": {
      "abstract": [
        {
          "text": "An object the system uses to monitor changes in sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSystemSharingUIObserver"
        }
      ],
      "role": "symbol",
      "title": "CKSystemSharingUIObserver",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/init(container:)": {
      "abstract": [
        {
          "text": "Creates and initializes an observer using the provided container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "container"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKContainer",
          "text": "CKContainer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/init(container:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContainer:"
        }
      ],
      "role": "symbol",
      "title": "init(container:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver/init(container:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidSaveShareBlock-39zlv": {
      "abstract": [
        {
          "text": "A callback block the system invokes after the success or failure of a system sharing UI save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "systemSharingUIDidSaveShareBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidSaveShareBlock-39zlv",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemSharingUIDidSaveShareBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver/systemsharinguididsaveshareblock-39zlv"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidSaveShareBlock-8c9vi": {
      "abstract": [
        {
          "text": "A callback block the system invokes after the success or failure of a system sharing UI save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemSharingUIDidSaveShareBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKShare",
          "text": "CKShare"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidSaveShareBlock-8c9vi",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemSharingUIDidSaveShareBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver/systemsharinguididsaveshareblock-8c9vi"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidStopSharingBlock-4g5bn": {
      "abstract": [
        {
          "text": "A callback block the system invokes after the success or failure of a system sharing UI delete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "systemSharingUIDidStopSharingBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidStopSharingBlock-4g5bn",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemSharingUIDidStopSharingBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver/systemsharinguididstopsharingblock-4g5bn"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidStopSharingBlock-7nmiw": {
      "abstract": [
        {
          "text": "A callback block the system invokes after the success or failure of a system sharing UI delete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemSharingUIDidStopSharingBlock"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecord",
          "text": "CKRecord"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidStopSharingBlock-7nmiw",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemSharingUIDidStopSharingBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/cksystemsharinguiobserver/systemsharinguididstopsharingblock-7nmiw"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/remote-records": {
      "abstract": [
        {
          "text": "Use subscriptions and change tokens to efficiently manage modifications to remote records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/remote-records",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Remote Records",
      "type": "topic",
      "url": "/documentation/cloudkit/remote-records"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users": {
      "abstract": [
        {
          "text": "Create and share private CloudKit data with other users by implementing the sharing UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing CloudKit Data with Other iCloud Users",
      "type": "topic",
      "url": "/documentation/cloudkit/sharing-cloudkit-data-with-other-icloud-users"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates your app supports CloudKit Sharing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSharingSupported",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CKSharingSupported"
    },
    "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users": {
      "abstract": [
        {
          "text": "Use Core Data and CloudKit to synchronize data between devices of an iCloud user and share data between different iCloud users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
      "kind": "article",
      "role": "sampleCode",
      "title": "Sharing Core Data objects between iCloud users",
      "type": "topic",
      "url": "/documentation/CoreData/sharing-core-data-objects-between-icloud-users"
    },
    "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController": {
      "abstract": [
        {
          "text": "A view controller that presents standard screens for adding and removing people from a CloudKit share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICloudSharingController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICloudSharingController",
      "type": "topic",
      "url": "/documentation/UIKit/UICloudSharingController"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collaboration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
        "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShareTransferRepresentation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
        "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported"
      ],
      "title": "Collaboration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-sharing-observer",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/init(container:)"
      ],
      "title": "Creating a sharing observer"
    },
    {
      "anchor": "Accessing-sharing-blocks",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidSaveShareBlock-8c9vi",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidStopSharingBlock-7nmiw"
      ],
      "title": "Accessing sharing blocks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKSystemSharingUIObserver"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-sharing-observer",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/init(container:)"
              ],
              "title": "Creating a sharing observer"
            },
            {
              "anchor": "Accessing-sharing-blocks",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidSaveShareBlock-39zlv",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSystemSharingUIObserver/systemSharingUIDidStopSharingBlock-4g5bn"
              ],
              "title": "Accessing sharing blocks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Collaboration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/sharing-cloudkit-data-with-other-icloud-users",
                "doc://com.apple.documentation/documentation/CoreData/sharing-core-data-objects-between-icloud-users",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKShare",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAllowedSharingOptions",
                "doc://com.apple.documentation/documentation/UIKit/UICloudSharingController",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationCompletionHandler",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharePreparationHandler",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CKSharingSupported"
              ],
              "title": "Collaboration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKSystemSharingUIObserver"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/title",
          "value": "CKSystemSharingUIObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSystemSharingUIObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UICloudSharingController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICloudSharingController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver~1init(container:)/title",
          "value": "initWithContainer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSystemSharingUIObserver~1init(container:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContainer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/title",
          "value": "CKContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/title",
          "value": "CKShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/title",
          "value": "CKAllowedSharingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAllowedSharingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAllowedSharingOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksystemsharinguiobserver"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cksystemsharinguiobserver"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
