{
  "abstract": [
    {
      "text": "Describes a change to the device’s iCloud account.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKSyncEngineAccountChangeType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CKSyncEngineAccountChangeType"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKSyncEngineAccountChangeType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKSyncEngineAccountChangeType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/changeType": {
      "abstract": [
        {
          "text": "The iCloud account’s change type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "changeType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/changeType",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent/changetype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/currentUser": {
      "abstract": [
        {
          "text": "The current iCloud account’s record identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "currentUser"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/currentUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentUser",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent/currentuser"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/previousUser": {
      "abstract": [
        {
          "text": "The previous iCloud account’s record identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "previousUser"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/previousUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "previousUser",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangeevent/previoususer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType": {
      "abstract": [
        {
          "text": "Describes a change to the device’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeType"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineAccountChangeType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangetype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangetype/init(rawvalue:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signIn": {
      "abstract": [
        {
          "text": "A change indicating a sign-in to an iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signIn"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeTypeSignIn"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineAccountChangeType.signIn",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangetype/signin"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signOut": {
      "abstract": [
        {
          "text": "A change indicating a sign-out of an iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signOut"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeTypeSignOut"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineAccountChangeType.signOut",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangetype/signout"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/switchAccounts": {
      "abstract": [
        {
          "text": "A change indicating a switch between two iCloud accounts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchAccounts"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/switchAccounts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngineAccountChangeTypeSwitchAccounts"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngineAccountChangeType.switchAccounts",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengineaccountchangetype/switchaccounts"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Account-change-types",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signIn",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signOut",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/switchAccounts"
      ],
      "title": "Account change types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKSyncEngineAccountChangeType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Account-change-types",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signIn",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/signOut",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeType/switchAccounts"
              ],
              "title": "Account change types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Understanding-the-change",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/changeType",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/previousUser",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineAccountChangeEvent/currentUser"
              ],
              "title": "Understanding the change"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKSyncEngineAccountChangeType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType/title",
          "value": "CKSyncEngineAccountChangeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType~1signOut/title",
          "value": "CKSyncEngineAccountChangeTypeSignOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType~1signOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeTypeSignOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType~1switchAccounts/title",
          "value": "CKSyncEngineAccountChangeTypeSwitchAccounts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType~1switchAccounts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeTypeSwitchAccounts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType~1signIn/title",
          "value": "CKSyncEngineAccountChangeTypeSignIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEngineAccountChangeType~1signIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEngineAccountChangeTypeSignIn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncengineaccountchangetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cksyncengineaccountchangetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
