{
  "abstract": [
    {
      "text": "An object that describes an unsent database modification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKSyncEnginePendingDatabaseChange",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CKSyncEnginePendingDatabaseChange"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKSyncEnginePendingDatabaseChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CKSyncEnginePendingDatabaseChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKSyncEnginePendingDatabaseChange"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange": {
      "abstract": [
        {
          "text": "An object that describes an unsent database modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingDatabaseChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEnginePendingDatabaseChange",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingdatabasechange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange/type": {
      "abstract": [
        {
          "text": "The type of database change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange/type",
      "kind": "symbol",
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingdatabasechange/type"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange/zoneID": {
      "abstract": [
        {
          "text": "The identifier of the record zone to change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "zoneID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange/zoneID",
      "kind": "symbol",
      "role": "symbol",
      "title": "zoneID",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingdatabasechange/zoneid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChangeType": {
      "abstract": [
        {
          "text": "Describes the type of a pending database change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingDatabaseChangeType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChangeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingDatabaseChangeType"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEnginePendingDatabaseChangeType",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingdatabasechangetype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingRecordZoneChange": {
      "abstract": [
        {
          "text": "Describes an unsent record modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingRecordZoneChange"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingRecordZoneChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEnginePendingRecordZoneChange",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingrecordzonechange"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneDelete": {
      "abstract": [
        {
          "text": "An object that describes an unsent record zone deletion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingZoneDelete"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneDelete",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEnginePendingZoneDelete",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingzonedelete"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneSave": {
      "abstract": [
        {
          "text": "An object that describes an unsent record zone modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKSyncEnginePendingZoneSave"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneSave",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKSyncEnginePendingZoneSave",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginependingzonesave"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/addPendingDatabaseChanges:": {
      "abstract": [
        {
          "text": "Adds the specified database changes to the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addPendingDatabaseChanges:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/addPendingDatabaseChanges:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPendingDatabaseChanges:"
        }
      ],
      "role": "symbol",
      "title": "addPendingDatabaseChanges:",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginestate/addpendingdatabasechanges:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/addPendingRecordZoneChanges:": {
      "abstract": [
        {
          "text": "Adds the specified record zone changes to the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addPendingRecordZoneChanges:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/addPendingRecordZoneChanges:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPendingRecordZoneChanges:"
        }
      ],
      "role": "symbol",
      "title": "addPendingRecordZoneChanges:",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginestate/addpendingrecordzonechanges:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/removePendingDatabaseChanges:": {
      "abstract": [
        {
          "text": "Removes the specified database changes from the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removePendingDatabaseChanges:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/removePendingDatabaseChanges:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removePendingDatabaseChanges:"
        }
      ],
      "role": "symbol",
      "title": "removePendingDatabaseChanges:",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginestate/removependingdatabasechanges:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/removePendingRecordZoneChanges:": {
      "abstract": [
        {
          "text": "Removes the specified record zone changes from the state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removePendingRecordZoneChanges:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/removePendingRecordZoneChanges:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removePendingRecordZoneChanges:"
        }
      ],
      "role": "symbol",
      "title": "removePendingRecordZoneChanges:",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncenginestate/removependingrecordzonechanges:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneDelete",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneSave"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-pending-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/addPendingDatabaseChanges:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/removePendingDatabaseChanges:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneDelete",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingZoneSave",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/addPendingRecordZoneChanges:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngineState/removePendingRecordZoneChanges:",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingRecordZoneChange"
      ],
      "title": "Modifying pending changes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Understanding-the-change",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange/type",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChangeType",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEnginePendingDatabaseChange/zoneID"
      ],
      "title": "Understanding the change"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEnginePendingDatabaseChangeType/title",
          "value": "CKSyncEnginePendingDatabaseChangeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEnginePendingDatabaseChangeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEnginePendingDatabaseChangeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSyncEnginePendingDatabaseChangeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSyncEnginePendingDatabaseChangeType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncenginependingdatabasechange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
