{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionBlock"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionBlock"
        }
      ],
      "role": "symbol",
      "title": "CKContainer_Application_PermissionBlock",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer_application_permissionblock"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer_Application_PermissionStatus"
        }
      ],
      "role": "symbol",
      "title": "CKContainer_Application_PermissionStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer_application_permissionstatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_Permissions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKContainer_Application_Permissions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_Permissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKContainer_Application_Permissions"
        }
      ],
      "role": "symbol",
      "title": "CKContainer_Application_Permissions",
      "type": "topic",
      "url": "/documentation/cloudkit/ckcontainer_application_permissions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverAllUserIdentitiesOperation": {
      "abstract": [
        {
          "text": "An operation that uses the device’s contacts to search for discoverable iCloud users.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDiscoverAllUserIdentitiesOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverAllUserIdentitiesOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDiscoverAllUserIdentitiesOperation"
        }
      ],
      "role": "symbol",
      "title": "CKDiscoverAllUserIdentitiesOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdiscoveralluseridentitiesoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverUserIdentitiesOperation": {
      "abstract": [
        {
          "text": "An operation that uses the provided criteria to search for discoverable iCloud users.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKDiscoverUserIdentitiesOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverUserIdentitiesOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKDiscoverUserIdentitiesOperation"
        }
      ],
      "role": "symbol",
      "title": "CKDiscoverUserIdentitiesOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckdiscoveruseridentitiesoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation": {
      "abstract": [
        {
          "text": "An operation that reports on the changed and deleted records in the specified record zone.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKFetchRecordChangesOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKFetchRecordChangesOperation"
        }
      ],
      "role": "symbol",
      "title": "CKFetchRecordChangesOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordchangesoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord_Reference_Action": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecord_Reference_Action"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord_Reference_Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecord_Reference_Action"
        }
      ],
      "role": "symbol",
      "title": "CKRecord_Reference_Action",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord_reference_action"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_AcceptanceStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_AcceptanceStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_AcceptanceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_AcceptanceStatus"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_AcceptanceStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_acceptancestatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_ParticipantType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_ParticipantType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_ParticipantType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_ParticipantType"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_ParticipantType",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_participanttype"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Permission": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Permission"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Permission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Permission"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_Permission",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_permission"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Role": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Role"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Role",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKShare_Participant_Role"
        }
      ],
      "role": "symbol",
      "title": "CKShare_Participant_Role",
      "type": "topic",
      "url": "/documentation/cloudkit/ckshare_participant_role"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-classes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverAllUserIdentitiesOperation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverUserIdentitiesOperation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation"
      ],
      "title": "Deprecated classes"
    },
    {
      "anchor": "Deprecated-type-aliases",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionBlock",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_PermissionStatus",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKContainer_Application_Permissions",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord_Reference_Action",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_AcceptanceStatus",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_ParticipantType",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Permission",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKShare_Participant_Role"
      ],
      "title": "Deprecated type aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-classes",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverAllUserIdentitiesOperation",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKDiscoverUserIdentitiesOperation",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordChangesOperation"
              ],
              "title": "Deprecated classes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDiscoverAllUserIdentitiesOperation/title",
          "value": "CKDiscoverAllUserIdentitiesOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDiscoverAllUserIdentitiesOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDiscoverAllUserIdentitiesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDiscoverAllUserIdentitiesOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDiscoverAllUserIdentitiesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDiscoverUserIdentitiesOperation/title",
          "value": "CKDiscoverUserIdentitiesOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDiscoverUserIdentitiesOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDiscoverUserIdentitiesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKDiscoverUserIdentitiesOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKDiscoverUserIdentitiesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordChangesOperation/title",
          "value": "CKFetchRecordChangesOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordChangesOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordChangesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordChangesOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordChangesOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
