{
  "abstract": [
    {
      "text": "Inspect and modify the schema and data for your app’s iCloud container.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/managing-icloud-containers-with-cloudkit-database-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Managing iCloud Containers with CloudKit Database App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The CloudKit Database app is a web-based tool for developers to manage their iCloud containers. You can sign in to the CloudKit Database app through the Apple Developer web portal or through the CloudKit Console at ",
              "type": "text"
            },
            {
              "identifier": "https://icloud.developer.apple.com/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "With the CloudKit Database app, you can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "See all the containers for your account.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "View and edit your development schema, and view your production schema.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "View and edit your test data during development or debugging.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "View logs and metrics for your containers.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Deploy your schema to production. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/deploying-an-icloud-container-s-schema",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Obtain API tokens for use with CloudKit web services and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/cloudkitjs",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/obtaining-an-api-token-for-an-icloud-container",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Navigate-to-an-iCloud-Containers-Schema-Management-Page",
          "level": 3,
          "text": "Navigate to an iCloud Container’s Schema Management Page",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A schema defines record types and the possible relationships between them. You can use CloudKit Database Console or code to create your app’s schema. If you use code to create a just-in-time schema, the CloudKit Database app can help you verify the schema is correct.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To navigate to the iCloud container’s schema management page:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sign in to CloudKit Console at ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://icloud.developer.apple.com/",
                      "isActive": true,
                      "overridingTitle": "https://icloud.developer.apple.com/",
                      "overridingTitleInlineContent": [
                        {
                          "text": "https://icloud.developer.apple.com/",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the CloudKit Database from the app list.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From the container selection drop-down at the top of the page, choose your app’s container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Record Types menu item in the Schema section to open the container’s schema management page.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4452780",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you select the container you want to manage, you can access information about the schema quickly by using the menu items. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/inspecting-and-editing-an-icloud-container-s-schema",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Navigate-to-an-iCloud-containers-data-management-page",
          "level": 3,
          "text": "Navigate to an iCloud container’s data management page",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the CloudKit Database app to inspect data within the public database of an iCloud container. If you develop using the same iCloud account to store private data, you can also use the CloudKit Database app to inspect and edit private data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t use the CloudKit Database app as a general data editor. Although you can create, modify, and delete records using CloudKit Dashboard, the intent of this functionality is to help you debug your schema during the design phase.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To navigate to the iCloud container’s data management page:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sign in to CloudKit Console at ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://icloud.developer.apple.com/",
                      "isActive": true,
                      "overridingTitle": "https://icloud.developer.apple.com/",
                      "overridingTitleInlineContent": [
                        {
                          "text": "https://icloud.developer.apple.com/",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the CloudKit Database from the app list.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From the container selection drop-down at the top of the page, choose your app’s container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Records menu item in the Data section to open the container’s data management page.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3699100",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about inspecting a container’s data, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/handling-an-icloud-container-s-data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAsset": {
      "abstract": [
        {
          "text": "An external file that belongs to a record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAsset"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAsset"
        }
      ],
      "role": "symbol",
      "title": "CKAsset",
      "type": "topic",
      "url": "/documentation/cloudkit/ckasset"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord": {
      "abstract": [
        {
          "text": "A collection of key-value pairs that store your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecord"
        }
      ],
      "role": "symbol",
      "title": "CKRecord",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/Reference": {
      "abstract": [
        {
          "text": "A relationship between two records in a record zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reference"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/Reference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reference"
        }
      ],
      "role": "symbol",
      "title": "CKRecord.Reference",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord/reference"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone": {
      "abstract": [
        {
          "text": "A database partition that contains related records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordZone"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordZone"
        }
      ],
      "role": "symbol",
      "title": "CKRecordZone",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordzone"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/deploying-an-icloud-container-s-schema": {
      "abstract": [
        {
          "text": "Reset your container’s state during development and deploy your container’s schema to production.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/deploying-an-icloud-container-s-schema",
      "kind": "article",
      "role": "article",
      "title": "Deploying an iCloud Container’s Schema",
      "type": "topic",
      "url": "/documentation/cloudkit/deploying-an-icloud-container-s-schema"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/designing-and-creating-a-cloudkit-database": {
      "abstract": [
        {
          "text": "Create a schema to store your app’s objects as records in iCloud using CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/designing-and-creating-a-cloudkit-database",
      "kind": "article",
      "role": "article",
      "title": "Designing and Creating a CloudKit Database",
      "type": "topic",
      "url": "/documentation/cloudkit/designing-and-creating-a-cloudkit-database"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/handling-an-icloud-container-s-data": {
      "abstract": [
        {
          "text": "Inspect and manage your app’s iCloud container data using the CloudKit Database app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/handling-an-icloud-container-s-data",
      "kind": "article",
      "role": "article",
      "title": "Handling an iCloud Container’s Data",
      "type": "topic",
      "url": "/documentation/cloudkit/handling-an-icloud-container-s-data"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/inspecting-and-editing-an-icloud-container-s-schema": {
      "abstract": [
        {
          "text": "Review and edit the schema for your app’s container using the CloudKit Database app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/inspecting-and-editing-an-icloud-container-s-schema",
      "kind": "article",
      "role": "article",
      "title": "Inspecting and Editing an iCloud Container’s Schema",
      "type": "topic",
      "url": "/documentation/cloudkit/inspecting-and-editing-an-icloud-container-s-schema"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/integrating-a-text-based-schema-into-your-workflow": {
      "abstract": [
        {
          "text": "Define and update your schema with the CloudKit Schema Language.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/integrating-a-text-based-schema-into-your-workflow",
      "kind": "article",
      "role": "article",
      "title": "Integrating a Text-Based Schema into Your Workflow",
      "type": "topic",
      "url": "/documentation/cloudkit/integrating-a-text-based-schema-into-your-workflow"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/obtaining-an-api-token-for-an-icloud-container": {
      "abstract": [
        {
          "text": "Generate an API token to access CloudKit web services or use CloudKit JS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/obtaining-an-api-token-for-an-icloud-container",
      "kind": "article",
      "role": "article",
      "title": "Obtaining an API Token for an iCloud Container",
      "type": "topic",
      "url": "/documentation/cloudkit/obtaining-an-api-token-for-an-icloud-container"
    },
    "doc://com.apple.documentation/documentation/cloudkitjs": {
      "abstract": [
        {
          "text": "Provide access from your web app to your CloudKit app’s containers and databases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/cloudkitjs",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit JS",
      "type": "topic",
      "url": "/documentation/cloudkitjs"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://icloud.developer.apple.com/": {
      "identifier": "https://icloud.developer.apple.com/",
      "title": "https://icloud.developer.apple.com/",
      "titleInlineContent": [
        {
          "text": "https://icloud.developer.apple.com/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://icloud.developer.apple.com/"
    },
    "media-3699100": {
      "alt": "A screenshot showing a selected container in the CloudKit Database app. The screenshot highlights the Records menu item in the Data section on the left.",
      "identifier": "media-3699100",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d598350781d941fdf06e38a1e0f58f88/media-3699100@2x.png"
        }
      ]
    },
    "media-4452780": {
      "alt": "A screenshot showing a selected container in the CloudKit Database app. The screenshot highlights the Record Types menu item in the Schema section on the left.",
      "identifier": "media-4452780",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5c5ea351fa523f12db5077e11d5eafd2/media-4452780@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Schemas",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/designing-and-creating-a-cloudkit-database",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/Reference",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAsset",
        "doc://com.apple.cloudkit/documentation/CloudKit/integrating-a-text-based-schema-into-your-workflow"
      ],
      "title": "Schemas"
    }
  ],
  "topicSections": [
    {
      "anchor": "Container-Management",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/inspecting-and-editing-an-icloud-container-s-schema",
        "doc://com.apple.cloudkit/documentation/CloudKit/handling-an-icloud-container-s-data",
        "doc://com.apple.cloudkit/documentation/CloudKit/deploying-an-icloud-container-s-schema",
        "doc://com.apple.cloudkit/documentation/CloudKit/obtaining-an-api-token-for-an-icloud-container"
      ],
      "title": "Container Management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Container-Management",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/inspecting-and-editing-an-icloud-container-s-schema",
                "doc://com.apple.cloudkit/documentation/CloudKit/handling-an-icloud-container-s-data",
                "doc://com.apple.cloudkit/documentation/CloudKit/deploying-an-icloud-container-s-schema",
                "doc://com.apple.cloudkit/documentation/CloudKit/obtaining-an-api-token-for-an-icloud-container"
              ],
              "title": "Container Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Schemas",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/designing-and-creating-a-cloudkit-database",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord/Reference",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAsset",
                "doc://com.apple.cloudkit/documentation/CloudKit/integrating-a-text-based-schema-into-your-workflow"
              ],
              "title": "Schemas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/title",
          "value": "CKRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone/title",
          "value": "CKRecordZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAsset/title",
          "value": "CKAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1Reference/title",
          "value": "CKReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1Reference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecord~1Reference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKReference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/managing-icloud-containers-with-cloudkit-database-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/managing-icloud-containers-with-cloudkit-database-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
