{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress/init(mSelector:mScope:mElement:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So26AudioObjectPropertyAddressV9mSelector6mScope8mElementABs6UInt32V_A2Gtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "mSelector"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mScope"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertyScope",
        "text": "AudioObjectPropertyScope"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mElement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertyElement",
        "text": "AudioObjectPropertyElement"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(mSelector:mScope:mElement:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "mSelector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mScope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertyScope",
              "text": "AudioObjectPropertyScope"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mElement"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertyElement",
              "text": "AudioObjectPropertyElement"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress/init(mSelector:mScope:mElement:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyScope",
          "text": "AudioObjectPropertyScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyElement",
          "text": "AudioObjectPropertyElement"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress/init(mSelector:mScope:mElement:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mSelector:mScope:mElement:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress/init(mselector:mscope:melement:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyElement"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyElement"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyElement",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyelement"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyScope"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyScope"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyScope",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyscope"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/title",
          "value": "AudioObjectPropertyScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/title",
          "value": "AudioObjectPropertyElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audioobjectpropertyaddress/init(mselector:mscope:melement:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
