{
  "abstract": [
    {
      "text": "Determines the actual mode based on the user preference settings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFontRenderingMode@NSFontDefaultRenderingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "defaultRenderingMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontDefaultRenderingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSFontRenderingMode.defaultRenderingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "defaultRenderingMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode": {
      "abstract": [
        {
          "text": "The font rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode": {
      "abstract": [
        {
          "text": "Specifies antialiased, integer advancements rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "antialiasedIntegerAdvancementsRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAntialiasedIntegerAdvancementsRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.antialiasedIntegerAdvancementsRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/antialiasedintegeradvancementsrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode": {
      "abstract": [
        {
          "text": "Specifies antialiased, floating-point advancements rendering mode (synonymous with printerFont).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "antialiasedRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontAntialiasedRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.antialiasedRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/antialiasedrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode": {
      "abstract": [
        {
          "text": "Determines the actual mode based on the user preference settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/defaultRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDefaultRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.defaultRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/defaultrenderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode": {
      "abstract": [
        {
          "text": "Specifies integer advancements rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integerAdvancementsRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontIntegerAdvancementsRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSFontRenderingMode.integerAdvancementsRenderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsfontrenderingmode/integeradvancementsrenderingmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontDefaultRenderingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDefaultRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedRenderingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/integerAdvancementsRenderingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSFontRenderingMode/antialiasedIntegerAdvancementsRenderingMode"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFontDefaultRenderingMode"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/title",
          "value": "NSFontRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedRenderingMode/title",
          "value": "NSFontAntialiasedRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAntialiasedRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedIntegerAdvancementsRenderingMode/title",
          "value": "NSFontAntialiasedIntegerAdvancementsRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1antialiasedIntegerAdvancementsRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontAntialiasedIntegerAdvancementsRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1integerAdvancementsRenderingMode/title",
          "value": "NSFontIntegerAdvancementsRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1integerAdvancementsRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontIntegerAdvancementsRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1defaultRenderingMode/title",
          "value": "NSFontDefaultRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontRenderingMode~1defaultRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDefaultRenderingMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontrenderingmode/defaultrenderingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontrenderingmode/defaultrenderingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
