{
  "abstract": [
    {
      "text": "Mucus the color and consistency of egg whites.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/eggWhite"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKCategoryValueCervicalMucusQuality@HKCategoryValueCervicalMucusQualityEggWhite",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eggWhite"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValueCervicalMucusQualityEggWhite"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKCategoryValueCervicalMucusQuality.eggWhite"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eggWhite"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality": {
      "abstract": [
        {
          "text": "Categories that represent the user’s cervical mucus quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQuality"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQuality"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/creamy": {
      "abstract": [
        {
          "text": "Creamy mucus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creamy"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/creamy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQualityCreamy"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality.creamy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/creamy"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/dry": {
      "abstract": [
        {
          "text": "Little or no mucus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dry"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/dry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQualityDry"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality.dry",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/dry"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/eggWhite": {
      "abstract": [
        {
          "text": "Mucus the color and consistency of egg whites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eggWhite"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/eggWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQualityEggWhite"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality.eggWhite",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/eggwhite"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/sticky": {
      "abstract": [
        {
          "text": "Sticky mucus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sticky"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/sticky",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQualitySticky"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality.sticky",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/sticky"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/watery": {
      "abstract": [
        {
          "text": "Watery mucus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/watery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueCervicalMucusQualityWatery"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueCervicalMucusQuality.watery",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/watery"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/dry",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/sticky",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/creamy",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/watery"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryValueCervicalMucusQualityEggWhite"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQualityEggWhite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/dry",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/sticky",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/creamy",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueCervicalMucusQuality/watery"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKCategoryValueCervicalMucusQualityEggWhite"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1eggWhite/title",
          "value": "HKCategoryValueCervicalMucusQualityEggWhite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1eggWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQualityEggWhite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1sticky/title",
          "value": "HKCategoryValueCervicalMucusQualitySticky"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1sticky/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQualitySticky"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1watery/title",
          "value": "HKCategoryValueCervicalMucusQualityWatery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1watery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQualityWatery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1dry/title",
          "value": "HKCategoryValueCervicalMucusQualityDry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1dry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQualityDry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality/title",
          "value": "HKCategoryValueCervicalMucusQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1creamy/title",
          "value": "HKCategoryValueCervicalMucusQualityCreamy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueCervicalMucusQuality~1creamy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueCervicalMucusQualityCreamy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/eggwhite"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvaluecervicalmucusquality/eggwhite"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
