{
  "abstract": [
    {
      "text": "A style that ignores the background corner radius and uses a medium system-defined corner radius.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButton",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/medium"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So8UIButtonC5UIKitE13ConfigurationV11CornerStyleO6mediumyA2GmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "medium"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIButton.Configuration.CornerStyle.medium"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "medium"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum": {
      "abstract": [
        {
          "text": "Settings that determine the appearance of the background corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CornerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CornerStyle"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/capsule": {
      "abstract": [
        {
          "text": "A style that ignores the background corner radius and uses a corner radius that generates a capsule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capsule"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/capsule",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle.capsule",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/capsule"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/dynamic": {
      "abstract": [
        {
          "text": "A style that adjusts the background corner radius for dynamic type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/dynamic",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle.dynamic",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/dynamic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/fixed": {
      "abstract": [
        {
          "text": "A style that uses the background corner radius without modification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/fixed",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle.fixed",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/fixed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/large": {
      "abstract": [
        {
          "text": "A style that ignores the background corner radius and uses a large system-defined corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/large",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle.large",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/large"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/medium": {
      "abstract": [
        {
          "text": "A style that ignores the background corner radius and uses a medium system-defined corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/medium",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle.medium",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/medium"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/small": {
      "abstract": [
        {
          "text": "A style that ignores the background corner radius and uses a small system-defined corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "small"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/small",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButton.Configuration.CornerStyle.small",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/small"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Corner-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/dynamic",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/fixed",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/capsule",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/large",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/CornerStyle-swift.enum/small"
      ],
      "title": "Corner styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton/configuration-swift.struct/cornerstyle-swift.enum/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
