{
  "abstract": [
    {
      "text": "Enumerated error codes related to ad network testing in the testing environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKAdTestErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SKAdTestError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/conflictingSource": {
      "abstract": [
        {
          "text": "This error code is unused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conflictingSource"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/conflictingSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeConflictingSource"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.conflictingSource",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/conflictingsource"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks": {
      "abstract": [
        {
          "text": "Too many postbacks submitted to the test session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excessivePostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeExcessivePostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.excessivePostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/excessivepostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/init(rawvalue:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidCampaignId": {
      "abstract": [
        {
          "text": "The campaign ID isn’t an integer between one and one hundred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCampaignId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidCampaignId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidCampaignId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidCampaignId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidcampaignid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue": {
      "abstract": [
        {
          "text": "The conversion value isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConversionValue"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidConversionValue"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidConversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidconversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId": {
      "abstract": [
        {
          "text": "The impression ID isn’t a valid UUID string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidImpressionId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidImpressionId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidImpressionId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidimpressionid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL": {
      "abstract": [
        {
          "text": "The URL for the postback isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPostbackURL"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidPostbackURL"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidPostbackURL",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidpostbackurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback": {
      "abstract": [
        {
          "text": "A non-winning postback is defined with a version prior to version 3, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRunnerUpPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidRunnerUpPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidrunneruppostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId": {
      "abstract": [
        {
          "text": "The app ID is less than zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceAppAdamId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidSourceAppAdamId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain": {
      "abstract": [
        {
          "text": "The source domain isn’t in the correct format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceDomain"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidSourceDomain"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier": {
      "abstract": [
        {
          "text": "The postback’s identifier isn’t two, three, or four digits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion": {
      "abstract": [
        {
          "text": "A postback contains an incorrect version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidVersion"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidVersion",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidversion"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount": {
      "abstract": [
        {
          "text": "The number of winning postbacks isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWinningPostbackCount"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidWinningPostbackCount"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidWinningPostbackCount",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidwinningpostbackcount"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks": {
      "abstract": [
        {
          "text": "The postback in the testing environment is malformed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malformedPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMalformedPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.malformedPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/malformedpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback": {
      "abstract": [
        {
          "text": "A winning postback wasn’t found in the first position, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "misplacedWinnerPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMisplacedWinnerPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.misplacedWinnerPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/misplacedwinnerpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks": {
      "abstract": [
        {
          "text": "The testing environment doesn’t have any postbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMissingPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.missingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/missingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature": {
      "abstract": [
        {
          "text": "The signature for the ad is missing, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingSignature"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMissingSignature"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.missingSignature",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/missingsignature"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback": {
      "abstract": [
        {
          "text": "The testing environment is missing a winning postback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingWinningPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMissingWinningPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.missingWinningPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/missingwinningpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks": {
      "abstract": [
        {
          "text": "The test session doesn’t have any pending postbacks to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPendingPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeNoPendingPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.noPendingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/nopendingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey": {
      "abstract": [
        {
          "text": "The public key isn’t a valid cryptographic key, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidKey"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureInvalidKey"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureInvalidKey",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureinvalidkey"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder": {
      "abstract": [
        {
          "text": "The order of the parameters in the signature is invalid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidOrder"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureInvalidOrder"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureInvalidOrder",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureinvalidorder"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId": {
      "abstract": [
        {
          "text": "The signature is missing an ad network identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAdNetworkId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingAdNetworkId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingAdNetworkId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingadnetworkid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the app item identifier for the advertised app, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAppAdamId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingAppAdamId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingCampaignId": {
      "abstract": [
        {
          "text": "The signature is missing the campaign identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingCampaignId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingCampaignId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingCampaignId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingCampaignId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingcampaignid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType": {
      "abstract": [
        {
          "text": "The signature is missing the fidelity type, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingFidelityType"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingFidelityType"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingFidelityType",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingfidelitytype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce": {
      "abstract": [
        {
          "text": "The signature is missing the nonce, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingNonce"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingNonce"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingNonce",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingnonce"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the source app item identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceAppAdamId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingSourceAppAdamId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain": {
      "abstract": [
        {
          "text": "The signature is missing the source domain, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceDomain"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingSourceDomain"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier": {
      "abstract": [
        {
          "text": "The signature is missing the source identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingSourceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp": {
      "abstract": [
        {
          "text": "The signature is missing a timestamp, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingTimestamp"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingTimestamp"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingTimestamp",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingtimestamp"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred with the signature in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureUnknownError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureUnknownError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureUnknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureunknownerror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed": {
      "abstract": [
        {
          "text": "The signature verification failed in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureVerificationFailed"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureVerificationFailed"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureVerificationFailed",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureverificationfailed"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeUnknownError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/unknownerror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks": {
      "abstract": [
        {
          "text": "The postbacks aren’t correctly related to one another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlinkedWinningPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeUnlinkedWinningPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.unlinkedWinningPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/unlinkedwinningpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the error domain for SKAdNetwork testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestErrorDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Signature-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed"
      ],
      "title": "Signature Errors"
    },
    {
      "anchor": "Postback-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks"
      ],
      "title": "Postback Errors"
    },
    {
      "anchor": "Other-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError"
      ],
      "title": "Other Errors"
    },
    {
      "anchor": "Older-Errors",
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidCampaignId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingCampaignId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/conflictingSource",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidCampaignId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingCampaignId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/conflictingSource"
      ],
      "title": "Older Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Signature-Errors",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed"
              ],
              "title": "Signature Errors"
            },
            {
              "anchor": "Postback-Errors",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks"
              ],
              "title": "Postback Errors"
            },
            {
              "anchor": "Other-Errors",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError"
              ],
              "title": "Other Errors"
            },
            {
              "anchor": "Older-Errors",
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidCampaignId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingCampaignId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/conflictingSource",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidCampaignId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingCampaignId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/conflictingSource"
              ],
              "title": "Older Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ad-impression-and-postback-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestErrorDomain"
              ],
              "title": "Ad impression and postback errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKAdTestErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1noPendingPostbacks/title",
          "value": "SKAdTestErrorCodeNoPendingPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1noPendingPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeNoPendingPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureVerificationFailed/title",
          "value": "SKAdTestErrorCodeSignatureVerificationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureVerificationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureVerificationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1excessivePostbacks/title",
          "value": "SKAdTestErrorCodeExcessivePostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1excessivePostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeExcessivePostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureUnknownError/title",
          "value": "SKAdTestErrorCodeSignatureUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureUnknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceAppAdamId/title",
          "value": "SKAdTestErrorCodeInvalidSourceAppAdamId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceAppAdamId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceAppAdamId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingSignature/title",
          "value": "SKAdTestErrorCodeMissingSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMissingSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidConversionValue/title",
          "value": "SKAdTestErrorCodeInvalidConversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidConversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidKey/title",
          "value": "SKAdTestErrorCodeSignatureInvalidKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureInvalidKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1misplacedWinnerPostback/title",
          "value": "SKAdTestErrorCodeMisplacedWinnerPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1misplacedWinnerPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMisplacedWinnerPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1malformedPostbacks/title",
          "value": "SKAdTestErrorCodeMalformedPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1malformedPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMalformedPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingPostbacks/title",
          "value": "SKAdTestErrorCodeMissingPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMissingPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceAppAdamId/title",
          "value": "SKAdTestErrorCodeSignatureMissingSourceAppAdamId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceAppAdamId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingSourceAppAdamId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingCampaignId/title",
          "value": "SKAdTestErrorCodeSignatureMissingCampaignId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingCampaignId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingCampaignId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1conflictingSource/title",
          "value": "SKAdTestErrorCodeConflictingSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1conflictingSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeConflictingSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceIdentifier/title",
          "value": "SKAdTestErrorCodeInvalidSourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceDomain/title",
          "value": "SKAdTestErrorCodeInvalidSourceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceIdentifier/title",
          "value": "SKAdTestErrorCodeSignatureMissingSourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unlinkedWinningPostbacks/title",
          "value": "SKAdTestErrorCodeUnlinkedWinningPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unlinkedWinningPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeUnlinkedWinningPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidPostbackURL/title",
          "value": "SKAdTestErrorCodeInvalidPostbackURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidPostbackURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidPostbackURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unknownError/title",
          "value": "SKAdTestErrorCodeUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidOrder/title",
          "value": "SKAdTestErrorCodeSignatureInvalidOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureInvalidOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidWinningPostbackCount/title",
          "value": "SKAdTestErrorCodeInvalidWinningPostbackCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidWinningPostbackCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidWinningPostbackCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidVersion/title",
          "value": "SKAdTestErrorCodeInvalidVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestErrorDomain/title",
          "value": "SKAdTestErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAdNetworkId/title",
          "value": "SKAdTestErrorCodeSignatureMissingAdNetworkId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAdNetworkId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingAdNetworkId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceDomain/title",
          "value": "SKAdTestErrorCodeSignatureMissingSourceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingSourceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidRunnerUpPostback/title",
          "value": "SKAdTestErrorCodeInvalidRunnerUpPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidRunnerUpPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingWinningPostback/title",
          "value": "SKAdTestErrorCodeMissingWinningPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingWinningPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMissingWinningPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingNonce/title",
          "value": "SKAdTestErrorCodeSignatureMissingNonce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingNonce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingNonce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingTimestamp/title",
          "value": "SKAdTestErrorCodeSignatureMissingTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidCampaignId/title",
          "value": "SKAdTestErrorCodeInvalidCampaignId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidCampaignId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidCampaignId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidImpressionId/title",
          "value": "SKAdTestErrorCodeInvalidImpressionId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidImpressionId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidImpressionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAppAdamId/title",
          "value": "SKAdTestErrorCodeSignatureMissingAppAdamId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAppAdamId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingAppAdamId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingFidelityType/title",
          "value": "SKAdTestErrorCodeSignatureMissingFidelityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingFidelityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingFidelityType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
