{
  "abstract": [
    {
      "text": "A non-winning postback is defined with a version prior to version 3, in the testing environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidRunnerUpPostback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17SKAdTestErrorCodeLeV23invalidRunnerUpPostbackSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidRunnerUpPostback"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
        "text": "SKAdTestError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKAdTestErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidRunnerUpPostback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidRunnerUpPostback"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
              "text": "SKAdTestError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKAdTestErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Check that all non-winning postback you create with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " specify version 3 (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") or later. Non-winning postbacks are available starting in version 3. For more information about versions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes": {
      "abstract": [
        {
          "text": "Learn about the features in each SKAdNetwork version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork release notes",
      "type": "topic",
      "url": "/documentation/StoreKit/skadnetwork-release-notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/excessivePostbacks": {
      "abstract": [
        {
          "text": "Too many postbacks submitted to the test session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excessivePostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/excessivePostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "excessivePostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/excessivepostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidConversionValue": {
      "abstract": [
        {
          "text": "The conversion value isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidConversionValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidConversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidconversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidPostbackURL": {
      "abstract": [
        {
          "text": "The URL for the postback isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPostbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidPostbackURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidPostbackURL",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidpostbackurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidRunnerUpPostback": {
      "abstract": [
        {
          "text": "A non-winning postback is defined with a version prior to version 3, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRunnerUpPostback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidRunnerUpPostback",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidRunnerUpPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidrunneruppostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidWinningPostbackCount": {
      "abstract": [
        {
          "text": "The number of winning postbacks isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWinningPostbackCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidWinningPostbackCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidWinningPostbackCount",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/invalidwinningpostbackcount"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/malformedPostbacks": {
      "abstract": [
        {
          "text": "The postback in the testing environment is malformed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malformedPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/malformedPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "malformedPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/malformedpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/misplacedWinnerPostback": {
      "abstract": [
        {
          "text": "A winning postback wasn’t found in the first position, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "misplacedWinnerPostback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/misplacedWinnerPostback",
      "kind": "symbol",
      "role": "symbol",
      "title": "misplacedWinnerPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/misplacedwinnerpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingPostbacks": {
      "abstract": [
        {
          "text": "The testing environment doesn’t have any postbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/missingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingWinningPostback": {
      "abstract": [
        {
          "text": "The testing environment is missing a winning postback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingWinningPostback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingWinningPostback",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingWinningPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/missingwinningpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/noPendingPostbacks": {
      "abstract": [
        {
          "text": "The test session doesn’t have any pending postbacks to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPendingPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/noPendingPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "noPendingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/nopendingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unlinkedWinningPostbacks": {
      "abstract": [
        {
          "text": "The postbacks aren’t correctly related to one another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlinkedWinningPostbacks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unlinkedWinningPostbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "unlinkedWinningPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/unlinkedwinningpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback": {
      "abstract": [
        {
          "text": "A test postback that contains ad conversion information in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)": {
      "abstract": [
        {
          "text": "Creates a test postback for an in-app ad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adNetworkIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adCampaignIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "appStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceAppStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isRedownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didWin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "postbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
        }
      ],
      "role": "symbol",
      "title": "init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/init(version:adnetworkidentifier:adcampaignidentifier:appstoreitemidentifier:sourceappstoreitemidentifier:conversionvalue:fidelitytype:isredownload:didwin:postbackurl:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0": {
      "abstract": [
        {
          "text": "A constant that represents SKAdNetwork version 3.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion3_0"
        }
      ],
      "role": "symbol",
      "title": "version3_0",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/version3_0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Postback-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/excessivePostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidPostbackURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/invalidWinningPostbackCount",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/malformedPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/misplacedWinnerPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingWinningPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/noPendingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/unlinkedWinningPostbacks"
      ],
      "title": "Getting Postback Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)/title",
          "value": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/title",
          "value": "SKAdTestPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version3_0/title",
          "value": "SKAdTestPostbackVersion3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion3_0"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/invalidrunneruppostback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
