{
  "abstract": [
    {
      "text": "The signature verification failed in the testing environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureVerificationFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17SKAdTestErrorCodeLeV27signatureVerificationFailedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "signatureVerificationFailed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
        "text": "SKAdTestError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKAdTestErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "signatureVerificationFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "signatureVerificationFailed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
              "text": "SKAdTestError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKAdTestErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ad impression signature isn’t valid. Check the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You use the same cryptographic key-pair when you sign the ad impression and validate it in the testing environment. If you use different key pairs in these two steps, signature verification will fail. For more information about signing the ad, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/signing-and-providing-ads",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". For more information about validating the ad impression in the testing environment, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You use the correct signature instructions for the SKAdNetwork version that your app uses. For more information about SKAdNetwork versions, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your signature contains all the parameters in the correct order for the version you’re using.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your signature uses the correct separator character.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about signatures, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/signing-and-providing-ads",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/signing-and-providing-ads": {
      "abstract": [
        {
          "text": "Advertise apps by signing and providing StoreKit-rendered ads, view-through ads, or attributable web ads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/signing-and-providing-ads",
      "kind": "article",
      "role": "article",
      "title": "Signing and providing ads",
      "type": "topic",
      "url": "/documentation/StoreKit/signing-and-providing-ads"
    },
    "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes": {
      "abstract": [
        {
          "text": "Learn about the features in each SKAdNetwork version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork release notes",
      "type": "topic",
      "url": "/documentation/StoreKit/skadnetwork-release-notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingSignature": {
      "abstract": [
        {
          "text": "The signature for the ad is missing, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingSignature",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingSignature",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/missingsignature"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidKey": {
      "abstract": [
        {
          "text": "The public key isn’t a valid cryptographic key, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureInvalidKey",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureinvalidkey"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidOrder": {
      "abstract": [
        {
          "text": "The order of the parameters in the signature is invalid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureInvalidOrder",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureinvalidorder"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAdNetworkId": {
      "abstract": [
        {
          "text": "The signature is missing an ad network identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAdNetworkId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAdNetworkId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingAdNetworkId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingadnetworkid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the app item identifier for the advertised app, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAppAdamId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAppAdamId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingFidelityType": {
      "abstract": [
        {
          "text": "The signature is missing the fidelity type, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingFidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingFidelityType",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingFidelityType",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingfidelitytype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingNonce": {
      "abstract": [
        {
          "text": "The signature is missing the nonce, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingNonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingNonce",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingNonce",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingnonce"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the source app item identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceAppAdamId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceAppAdamId",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceDomain": {
      "abstract": [
        {
          "text": "The signature is missing the source domain, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceIdentifier": {
      "abstract": [
        {
          "text": "The signature is missing the source identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingTimestamp": {
      "abstract": [
        {
          "text": "The signature is missing a timestamp, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingTimestamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureMissingTimestamp",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signaturemissingtimestamp"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureUnknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred with the signature in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureUnknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureUnknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureUnknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureunknownerror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureVerificationFailed": {
      "abstract": [
        {
          "text": "The signature verification failed in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureVerificationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17SKAdTestErrorCodeLeV",
          "text": "SKAdTestError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKAdTestErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureVerificationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "signatureVerificationFailed",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/signatureverificationfailed"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)": {
      "abstract": [
        {
          "text": "Validates an impression for a view-through ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKAdImpression",
          "text": "SKAdImpression"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "publicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validate(_:publicKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateImpression:publicKey:error:"
        }
      ],
      "role": "symbol",
      "title": "validate(_:publicKey:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/validate(_:publickey:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)": {
      "abstract": [
        {
          "text": "Validates an impression for a StoreKit-rendered ad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validateImpression"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "publicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestSession/validateImpression(parameters:publicKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validateImpressionWithParameters:publicKey:error:"
        }
      ],
      "role": "symbol",
      "title": "validateImpression(parameters:publicKey:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestsession/validateimpression(parameters:publickey:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Signature-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/missingSignature",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidKey",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureInvalidOrder",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAdNetworkId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingFidelityType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingNonce",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureMissingTimestamp",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/signatureUnknownError"
      ],
      "title": "Getting Signature Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validateImpression(parameters:publicKey:)/title",
          "value": "validateImpressionWithParameters:publicKey:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validateImpression(parameters:publicKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateImpressionWithParameters:publicKey:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validate(_:publicKey:)/title",
          "value": "validateImpression:publicKey:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestSession~1validate(_:publicKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validateImpression:publicKey:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/signatureverificationfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
