{
  "abstract": [
    {
      "text": "An activity in preparation for sleep such as personal grooming or reviewing the next day’s agenda.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepWrapUpYourDay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INShortcutAvailabilityOptions@INShortcutAvailabilityOptionSleepWrapUpYourDay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sleepWrapUpYourDay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
        "text": "INShortcutAvailabilityOptions"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "sleepWrapUpYourDay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sleepWrapUpYourDay"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
              "text": "INShortcutAvailabilityOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions": {
      "abstract": [
        {
          "text": "Defined contexts in which an intent or activity might be relevant to a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "role": "symbol",
      "title": "INShortcutAvailabilityOptions",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepJournaling": {
      "abstract": [
        {
          "text": "Writing and other daily logging activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepJournaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepJournaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepJournaling"
        }
      ],
      "role": "symbol",
      "title": "sleepJournaling",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleepjournaling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMindfulness": {
      "abstract": [
        {
          "text": "Meditation and other activities intended to facilitate mindfulness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepMindfulness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMindfulness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepMindfulness"
        }
      ],
      "role": "symbol",
      "title": "sleepMindfulness",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleepmindfulness"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMusic": {
      "abstract": [
        {
          "text": "Music suitable for falling asleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepMusic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepMusic"
        }
      ],
      "role": "symbol",
      "title": "sleepMusic",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleepmusic"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepPodcasts": {
      "abstract": [
        {
          "text": "A podcast or other spoken audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepPodcasts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepPodcasts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepPodcasts"
        }
      ],
      "role": "symbol",
      "title": "sleepPodcasts",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleeppodcasts"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepReading": {
      "abstract": [
        {
          "text": "A book or other reading material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepReading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepReading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepReading"
        }
      ],
      "role": "symbol",
      "title": "sleepReading",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleepreading"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepWrapUpYourDay": {
      "abstract": [
        {
          "text": "An activity in preparation for sleep such as personal grooming or reviewing the next day’s agenda.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepWrapUpYourDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepWrapUpYourDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
        }
      ],
      "role": "symbol",
      "title": "sleepWrapUpYourDay",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleepwrapupyourday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepYogaAndStretching": {
      "abstract": [
        {
          "text": "Physical activity to prepare for sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sleepYogaAndStretching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INShortcutAvailabilityOptions",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepYogaAndStretching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptionSleepYogaAndStretching"
        }
      ],
      "role": "symbol",
      "title": "sleepYogaAndStretching",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions/sleepyogaandstretching"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Contexts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMindfulness",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepJournaling",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMusic",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepPodcasts",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepReading",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepYogaAndStretching"
      ],
      "title": "Providing Contexts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Contexts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMindfulness",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepJournaling",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepMusic",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepPodcasts",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepReading",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions/sleepYogaAndStretching"
              ],
              "title": "Providing Contexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepPodcasts/title",
          "value": "INShortcutAvailabilityOptionSleepPodcasts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepPodcasts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepPodcasts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepMusic/title",
          "value": "INShortcutAvailabilityOptionSleepMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepWrapUpYourDay/title",
          "value": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepWrapUpYourDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepWrapUpYourDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepJournaling/title",
          "value": "INShortcutAvailabilityOptionSleepJournaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepJournaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepJournaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepReading/title",
          "value": "INShortcutAvailabilityOptionSleepReading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepReading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/title",
          "value": "INShortcutAvailabilityOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepMindfulness/title",
          "value": "INShortcutAvailabilityOptionSleepMindfulness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepMindfulness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepMindfulness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepYogaAndStretching/title",
          "value": "INShortcutAvailabilityOptionSleepYogaAndStretching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions~1sleepYogaAndStretching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptionSleepYogaAndStretching"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inshortcutavailabilityoptions/sleepwrapupyourday"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inshortcutavailabilityoptions/sleepwrapupyourday"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
