{
  "abstract": [
    {
      "text": "A reaction that displays a dark and stormy night.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVCaptureReactionTypeRain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVCaptureReactionType",
        "text": "AVCaptureReactionType"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureReactionTypeRain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "rain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVCaptureReactionType",
              "text": "AVCaptureReactionType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of reaction that an effect can perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionType"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureReactionType",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons": {
      "abstract": [
        {
          "text": "A reaction that displays balloons rising through the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balloons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeBalloons"
        }
      ],
      "role": "symbol",
      "title": "balloons",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/balloons"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti": {
      "abstract": [
        {
          "text": "A reaction that displays festive spots of color falling through the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confetti"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeConfetti"
        }
      ],
      "role": "symbol",
      "title": "confetti",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/confetti"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks": {
      "abstract": [
        {
          "text": "A reaction that displays fireworks bursting in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fireworks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeFireworks"
        }
      ],
      "role": "symbol",
      "title": "fireworks",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/fireworks"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart": {
      "abstract": [
        {
          "text": "A reaction that displays one or more heart symbols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeHeart"
        }
      ],
      "role": "symbol",
      "title": "heart",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/heart"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers": {
      "abstract": [
        {
          "text": "A reaction that displays a bright laser show projecting into the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lasers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeLasers"
        }
      ],
      "role": "symbol",
      "title": "lasers",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/lasers"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain": {
      "abstract": [
        {
          "text": "A reaction that displays a dark and stormy night.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeRain"
        }
      ],
      "role": "symbol",
      "title": "rain",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/rain"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown": {
      "abstract": [
        {
          "text": "A reaction that displays a thumbs-down symbol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbsDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeThumbsDown"
        }
      ],
      "role": "symbol",
      "title": "thumbsDown",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/thumbsdown"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp": {
      "abstract": [
        {
          "text": "A reaction that displays a thumbs-up symbol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbsUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeThumbsUp"
        }
      ],
      "role": "symbol",
      "title": "thumbsUp",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/thumbsup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reaction-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown"
      ],
      "title": "Reaction types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureReactionTypeRain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeRain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reaction-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown"
              ],
              "title": "Reaction types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVCaptureReactionType",
                    "text": "AVCaptureReactionType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCaptureReactionTypeRain"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1balloons/title",
          "value": "AVCaptureReactionTypeBalloons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1balloons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeBalloons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsUp/title",
          "value": "AVCaptureReactionTypeThumbsUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeThumbsUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1confetti/title",
          "value": "AVCaptureReactionTypeConfetti"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1confetti/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeConfetti"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1heart/title",
          "value": "AVCaptureReactionTypeHeart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1heart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeHeart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsDown/title",
          "value": "AVCaptureReactionTypeThumbsDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeThumbsDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1fireworks/title",
          "value": "AVCaptureReactionTypeFireworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1fireworks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeFireworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType/title",
          "value": "AVCaptureReactionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1rain/title",
          "value": "AVCaptureReactionTypeRain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1rain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeRain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1lasers/title",
          "value": "AVCaptureReactionTypeLasers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1lasers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeLasers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturereactiontype/rain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturereactiontype/rain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
