{
  "abstract": [
    {
      "text": "Connects to the given enterprise network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(toEnterpriseNetwork:identity:username:password:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CWInterface(im)associateToEnterpriseNetwork:identity:username:password:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "associate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "toEnterpriseNetwork"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CWNetwork",
        "text": "CWNetwork"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "identity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SecIdentityRef",
        "text": "SecIdentity"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "username"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "password"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?) "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "associateToEnterpriseNetwork:identity:username:password:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "associate(toEnterpriseNetwork:identity:username:password:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "associate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "toEnterpriseNetwork"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "network"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CWNetwork",
              "text": "CWNetwork"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "identity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SecIdentityRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SecIdentityRef",
              "text": "SecIdentity"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "username"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "password"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?) "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The network to which the interface will associate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "network"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identity to use for IEEE 802.1X authentication. Holds the corresponding client certificate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "identity"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The username to use for IEEE 802.1X authentication.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "username"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The password to use for IEEE 802.1X authentication.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "password"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method will block for the duration of the association. This operation may require an administrator password.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In Swift, this method returns ",
                  "type": "text"
                },
                {
                  "code": "Void",
                  "type": "codeVoice"
                },
                {
                  "text": " and is marked with the ",
                  "type": "text"
                },
                {
                  "code": "throws",
                  "type": "codeVoice"
                },
                {
                  "text": " keyword to indicate that it throws an error in cases of failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "You call this method in a ",
                  "type": "text"
                },
                {
                  "code": "try",
                  "type": "codeVoice"
                },
                {
                  "text": " expression and handle any errors in the ",
                  "type": "text"
                },
                {
                  "code": "catch",
                  "type": "codeVoice"
                },
                {
                  "text": " clauses of a ",
                  "type": "text"
                },
                {
                  "code": "do",
                  "type": "codeVoice"
                },
                {
                  "text": " statement, as described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "About Imported Cocoa Error Parameters",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Handling Errors in Swift",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface": {
      "abstract": [
        {
          "text": "Encapsulates an IEEE 802.11 interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWInterface"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWInterface"
        }
      ],
      "role": "symbol",
      "title": "CWInterface",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterface"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(to:password:)": {
      "abstract": [
        {
          "text": "Associates to a given network using the given network passphrase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "associate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetwork",
          "text": "CWNetwork"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(to:password:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "associateToNetwork:password:error:"
        }
      ],
      "role": "symbol",
      "title": "associate(to:password:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterface/associate(to:password:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(toEnterpriseNetwork:identity:username:password:)": {
      "abstract": [
        {
          "text": "Connects to the given enterprise network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "associate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toEnterpriseNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CWNetwork",
          "text": "CWNetwork"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecIdentityRef",
          "text": "SecIdentity"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(toEnterpriseNetwork:identity:username:password:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "associateToEnterpriseNetwork:identity:username:password:error:"
        }
      ],
      "role": "symbol",
      "title": "associate(toEnterpriseNetwork:identity:username:password:)",
      "type": "topic",
      "url": "/documentation/corewlan/cwinterface/associate(toenterprisenetwork:identity:username:password:)"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork": {
      "abstract": [
        {
          "text": "Encapsulates an IEEE 802.11 network, providing read-only accessors to various properties of the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWNetwork"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWNetwork"
        }
      ],
      "role": "symbol",
      "title": "CWNetwork",
      "type": "topic",
      "url": "/documentation/corewlan/cwnetwork"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@SecIdentityRef": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SecIdentityRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "SecIdentity",
      "type": "topic",
      "url": "/documentation/Security/SecIdentity"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "https://docs.swift.org/swift-book/": {
      "identifier": "https://docs.swift.org/swift-book/",
      "title": "The Swift Programming Language",
      "titleInlineContent": [
        {
          "text": "The Swift Programming Language",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/"
    },
    "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html": {
      "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
      "title": "Error Handling",
      "titleInlineContent": [
        {
          "text": "Error Handling",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Associating-to-a-network",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(to:password:)"
      ],
      "title": "Associating to a network"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "associateToEnterpriseNetwork:identity:username:password:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "associateToEnterpriseNetwork:identity:username:password:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Associating-to-a-network",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWInterface/associate(to:password:)"
              ],
              "title": "Associating to a network"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "associateToEnterpriseNetwork:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWNetwork",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CWNetwork",
                    "text": "CWNetwork"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "network"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "identity:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@SecIdentityRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SecIdentityRef",
                    "text": "SecIdentityRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "identity"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "username:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "username"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "password:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "password"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The network to which the interface will associate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "network"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identity to use for IEEE 802.1X authentication. Holds the corresponding client certificate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "identity"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The username to use for IEEE 802.1X authentication.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "username"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The password to use for IEEE 802.1X authentication.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "password"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An NSError object passed by reference, which will be populated with the error code and the error description if an error occurs during the execution of this method. This parameter is optional and can be passed as ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "nil",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A Boolean value which will indicate whether or not a failure occurred during execution. ",
                    "type": "text"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "YES",
                        "type": "text"
                      }
                    ],
                    "type": "emphasis"
                  },
                  {
                    "text": " indicates no error occurred.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface~1associate(to:password:)/title",
          "value": "associateToNetwork:password:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface~1associate(to:password:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "associateToNetwork:password:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface~1associate(toEnterpriseNetwork:identity:username:password:)/title",
          "value": "associateToEnterpriseNetwork:identity:username:password:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface~1associate(toEnterpriseNetwork:identity:username:password:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "associateToEnterpriseNetwork:identity:username:password:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/title",
          "value": "CWNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWNetwork/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface/title",
          "value": "CWInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecIdentityRef/title",
          "value": "SecIdentityRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@SecIdentityRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@__SecIdentity",
              "text": "__SecIdentity"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwinterface/associate(toenterprisenetwork:identity:username:password:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwinterface/associate(toenterprisenetwork:identity:username:password:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
