{"seeAlsoSections":[{"title":"Reading user activity sensors","identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram"],"anchor":"Reading-user-activity-sensors","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wristTemperature","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor","preciseIdentifier":"c:@T@SRSensor","text":"SRSensor","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample","isActive":true},{"type":"text","text":" type for this sensor is "},{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to provide a reason to record wrist temperatures by adding the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature"},{"type":"text","text":" dictionary to the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail"},{"type":"text","text":" key in the information property list."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Property","title":"wristTemperature","symbolKind":"property","extendedModule":"SensorKit","externalID":"c:@SRSensorWristTemperature","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wristTemperature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"modules":[{"name":"SensorKit"}],"platforms":[{"introducedAt":"17.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"17.0","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"deprecated":false,"unavailable":false,"introducedAt":"17.0","beta":false,"name":"Mac Catalyst"}],"navigatorTitle":[{"kind":"identifier","text":"SRSensorWristTemperature"}]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/sensorkit/srsensor/wristtemperature"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/sensorkit/srsensor/wristtemperature"]}],"abstract":[{"type":"text","text":"A sensor that provides wrist temperature while the user sleeps."}],"references":{"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents":{"role":"symbol","abstract":[{"text":"A sensor that provides information about interactions with media, such as images and videos, in messaging apps.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents","title":"mediaEvents","url":"/documentation/sensorkit/srsensor/mediaevents","navigatorTitle":[{"kind":"identifier","text":"SRSensorMediaEvents"}],"kind":"symbol","type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram":{"abstract":[{"type":"text","text":"A sensor that streams sample ECG sensor data."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"electrocardiogram"},{"kind":"text","text":": "},{"text":"SRSensor","kind":"typeIdentifier","preciseIdentifier":"c:@T@SRSensor"}],"navigatorTitle":[{"text":"SRSensorElectrocardiogram","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/electrocardiogram","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram","title":"electrocardiogram"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor":{"abstract":[{"text":"The sensors an app can read.","type":"text"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor","url":"/documentation/sensorkit/srsensor","title":"SRSensor","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRSensor","kind":"identifier"}],"navigatorTitle":[{"text":"SRSensor","kind":"identifier"}],"type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit":{"type":"topic","title":"SensorKit","abstract":[{"type":"text","text":"Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch."}],"url":"/documentation/sensorkit","role":"collection","identifier":"doc://com.apple.sensorkit/documentation/SensorKit","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature","title":"SRWristTemperature","abstract":[{"text":"The temperature of the user’s wrist while the user sleeps.","type":"text"}],"url":"/documentation/sensorkit/srwristtemperature","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRWristTemperature","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SRWristTemperature","kind":"identifier"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics":{"kind":"symbol","title":"faceMetrics","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics","abstract":[{"type":"text","text":"A sensor that provides data describing a user’s face."}],"navigatorTitle":[{"text":"SRSensorFaceMetrics","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceMetrics"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SRSensor","text":"SRSensor","kind":"typeIdentifier"}],"url":"/documentation/sensorkit/srsensor/facemetrics"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature","title":"wristTemperature","abstract":[{"text":"A sensor that provides wrist temperature while the user sleeps.","type":"text"}],"url":"/documentation/sensorkit/srsensor/wristtemperature","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wristTemperature","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SRSensor","text":"SRSensor","kind":"typeIdentifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SRSensorWristTemperature","kind":"identifier"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate":{"abstract":[{"text":"A sensor that provides rotation motion data.","type":"text"}],"title":"rotationRate","kind":"symbol","url":"/documentation/sensorkit/srsensor/rotationrate","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"rotationRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","kind":"typeIdentifier","preciseIdentifier":"c:@T@SRSensor"}],"navigatorTitle":[{"text":"SRSensorRotationRate","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics":{"abstract":[{"type":"text","text":"A sensor that provides data describing speech during phone calls."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"telephonySpeechMetrics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SRSensorTelephonySpeechMetrics","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/telephonyspeechmetrics","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics","title":"telephonySpeechMetrics"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData":{"abstract":[{"type":"text","text":"A sensor that provides information about the user’s steps."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pedometerData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SRSensorPedometerData","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/pedometerdata","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData","title":"pedometerData"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer":{"abstract":[{"type":"text","text":"A sensor that provides information about speed and slope."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRSensorOdometer"}],"url":"/documentation/sensorkit/srsensor/odometer","type":"topic","role":"symbol","title":"odometer","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"odometer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail":{"abstract":[{"type":"text","text":"A dictionary that includes keys for the specific information your app collects."}],"type":"topic","url":"/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail","role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail","title":"NSSensorKitUsageDetail"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram":{"url":"/documentation/sensorkit/srsensor/photoplethysmogram","title":"photoplethysmogram","abstract":[{"type":"text","text":"A sensor that streams sample PPG sensor data."}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SRSensorPhotoplethysmogram","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photoplethysmogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","kind":"typeIdentifier","preciseIdentifier":"c:@T@SRSensor"}],"type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer":{"role":"symbol","abstract":[{"text":"A sensor that provides acceleration motion data.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accelerometer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer","title":"accelerometer","url":"/documentation/sensorkit/srsensor/accelerometer","navigatorTitle":[{"kind":"identifier","text":"SRSensorAccelerometer"}],"kind":"symbol","type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics":{"abstract":[{"type":"text","text":"A sensor that provides data describing a user’s speech to Siri."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"siriSpeechMetrics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SRSensorSiriSpeechMetrics","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/sirispeechmetrics","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics","title":"siriSpeechMetrics"},"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature":{"identifier":"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature","type":"topic","role":"symbol","url":"/documentation/BundleResources/Information-Property-List/NSSensorKitUsageDetail/SRSensorUsageWristTemperature","abstract":[{"type":"text","text":"A collection of properties that explains your app’s need to observe the user’s wrist temperature while the user sleeps."}],"kind":"symbol","title":"SRSensorUsageWristTemperature"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate":{"abstract":[{"type":"text","text":"A sensor that provides the user’s heart rate data."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"heartRate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"navigatorTitle":[{"kind":"identifier","text":"SRSensorHeartRate"}],"type":"topic","url":"/documentation/sensorkit/srsensor/heartrate","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate","title":"heartRate"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits":{"kind":"symbol","title":"visits","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits","abstract":[{"text":"A sensor that provides information about frequently visited locations.","type":"text"}],"navigatorTitle":[{"text":"SRSensorVisits","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"visits"},{"kind":"text","text":": "},{"text":"SRSensor","kind":"typeIdentifier","preciseIdentifier":"c:@T@SRSensor"}],"url":"/documentation/sensorkit/srsensor/visits"},"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample":{"navigatorTitle":[{"kind":"identifier","text":"sample"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SampleType"}],"url":"/documentation/sensorkit/srfetchresult/sample","kind":"symbol","title":"sample","abstract":[{"type":"text","text":"A recording that the sensor reader fetches."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"17.0","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"17.0","beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"17.0","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Global Variable"},{"path":"/metadata/title","op":"replace","value":"SRSensorWristTemperature"},{"path":"/metadata/symbolKind","op":"replace","value":"var"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"SRSensorWristTemperature","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/photoplethysmogram","doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/electrocardiogram"],"anchor":"Reading-user-activity-sensors","title":"Reading user activity sensors"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRSensorWristTemperature","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1mediaEvents/title","value":"SRSensorMediaEvents","op":"replace"},{"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1mediaEvents/fragments","value":[{"kind":"identifier","text":"SRSensorMediaEvents"}],"op":"replace"},{"value":"SRSensorElectrocardiogram","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1electrocardiogram/title","op":"replace"},{"value":[{"kind":"identifier","text":"SRSensorElectrocardiogram"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1electrocardiogram/fragments","op":"replace"},{"value":"SRSensor","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/title","op":"replace"},{"value":[{"text":"SRSensor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SRSensor"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor/navigatorTitle","op":"replace"},{"value":"SRWristTemperature","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/title","op":"replace"},{"value":[{"text":"SRWristTemperature","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/fragments","op":"replace"},{"value":[{"text":"SRWristTemperature","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/navigatorTitle","op":"replace"},{"value":"SRSensorFaceMetrics","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1faceMetrics/title"},{"value":[{"kind":"identifier","text":"SRSensorFaceMetrics"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1faceMetrics/fragments"},{"value":"SRSensorWristTemperature","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1wristTemperature/title"},{"value":[{"kind":"identifier","text":"SRSensorWristTemperature"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1wristTemperature/fragments"},{"value":"SRSensorRotationRate","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1rotationRate/title"},{"value":[{"kind":"identifier","text":"SRSensorRotationRate"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1rotationRate/fragments"},{"value":"SRSensorTelephonySpeechMetrics","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1telephonySpeechMetrics/title"},{"value":[{"kind":"identifier","text":"SRSensorTelephonySpeechMetrics"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1telephonySpeechMetrics/fragments"},{"value":"SRSensorPedometerData","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1pedometerData/title"},{"value":[{"kind":"identifier","text":"SRSensorPedometerData"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1pedometerData/fragments"},{"value":"SRSensorOdometer","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1odometer/title"},{"value":[{"kind":"identifier","text":"SRSensorOdometer"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1odometer/fragments"},{"value":"SRSensorPhotoplethysmogram","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1photoplethysmogram/title"},{"value":[{"kind":"identifier","text":"SRSensorPhotoplethysmogram"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1photoplethysmogram/fragments"},{"value":"SRSensorAccelerometer","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1accelerometer/title"},{"value":[{"kind":"identifier","text":"SRSensorAccelerometer"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1accelerometer/fragments"},{"value":"SRSensorSiriSpeechMetrics","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/title"},{"value":[{"kind":"identifier","text":"SRSensorSiriSpeechMetrics"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/fragments"},{"value":"SRSensorHeartRate","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1heartRate/title"},{"value":[{"text":"SRSensorHeartRate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1heartRate/fragments"},{"value":"SRSensorVisits","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1visits/title"},{"value":[{"kind":"identifier","text":"SRSensorVisits"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1visits/fragments"},{"value":"sample","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1sample/title"},{"value":[{"text":"sample","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1sample/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}