{
  "abstract": [
    {
      "text": "Creates an SGD optimizer with the descriptor you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCSGDOptimizer(cm)optimizerWithDescriptor:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "descriptor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLCOptimizerDescriptor",
        "text": "MLCOptimizerDescriptor"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "optimizerWithDescriptor:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(descriptor:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "descriptor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "optimizerDescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLCOptimizerDescriptor",
              "text": "MLCOptimizerDescriptor"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object you use to configure the optimizer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "optimizerDescriptor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An SGD optimizer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sets ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/momentumScale",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/usesNesterovMomentum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " by default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create an optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCOptimizerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCOptimizerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCOptimizerDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcoptimizerdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that represents the stochastic gradient decent algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCSGDOptimizer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCSGDOptimizer"
        }
      ],
      "role": "symbol",
      "title": "MLCSGDOptimizer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:)": {
      "abstract": [
        {
          "text": "Creates an SGD optimizer with the descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCOptimizerDescriptor",
          "text": "MLCOptimizerDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optimizerWithDescriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer/init(descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:momentumScale:usesNesterovMomentum:)": {
      "abstract": [
        {
          "text": "Create an SGD optimizer with the descriptor, momentum scale, and option to enable Nesterov momentum that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCOptimizerDescriptor",
          "text": "MLCOptimizerDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "momentumScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "usesNesterovMomentum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:momentumScale:usesNesterovMomentum:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "optimizerWithDescriptor:momentumScale:usesNesterovMomentum:"
        }
      ],
      "role": "symbol",
      "title": "init(descriptor:momentumScale:usesNesterovMomentum:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer/init(descriptor:momentumscale:usesnesterovmomentum:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/momentumScale": {
      "abstract": [
        {
          "text": "A hyper-parameter specifying the momentum factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentumScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/momentumScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "momentumScale"
        }
      ],
      "role": "symbol",
      "title": "momentumScale",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer/momentumscale"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/usesNesterovMomentum": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you enable Nesterov momentum.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesNesterovMomentum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/usesNesterovMomentum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesNesterovMomentum"
        }
      ],
      "role": "symbol",
      "title": "usesNesterovMomentum",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcsgdoptimizer/usesnesterovmomentum"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-SGD-Optimizer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:momentumScale:usesNesterovMomentum:)"
      ],
      "title": "Creating an SGD Optimizer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "optimizerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "optimizerWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-SGD-Optimizer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCSGDOptimizer/init(descriptor:momentumScale:usesNesterovMomentum:)"
              ],
              "title": "Creating an SGD Optimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "optimizerWithDescriptor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCOptimizerDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCOptimizerDescriptor",
                    "text": "MLCOptimizerDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "optimizerDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object you use to configure the optimizer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "optimizerDescriptor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An SGD optimizer.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1init(descriptor:momentumScale:usesNesterovMomentum:)/title",
          "value": "optimizerWithDescriptor:momentumScale:usesNesterovMomentum:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1init(descriptor:momentumScale:usesNesterovMomentum:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "optimizerWithDescriptor:momentumScale:usesNesterovMomentum:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1init(descriptor:)/title",
          "value": "optimizerWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1init(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "optimizerWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/title",
          "value": "MLCOptimizerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCOptimizerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCOptimizerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1usesNesterovMomentum/title",
          "value": "usesNesterovMomentum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1usesNesterovMomentum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesNesterovMomentum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1momentumScale/title",
          "value": "momentumScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer~1momentumScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "momentumScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/title",
          "value": "MLCSGDOptimizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSGDOptimizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCSGDOptimizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCSGDOptimizer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcsgdoptimizer/init(descriptor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcsgdoptimizer/init(descriptor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
