{
  "abstract": [
    {
      "text": "The error codes for the File Provider extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSFileProviderError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError": {
      "abstract": [
        {
          "text": "A structure that contains information about File Provider extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code": {
      "abstract": [
        {
          "text": "The error codes for the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/applicationExtensionNotFound": {
      "abstract": [
        {
          "text": "An error indicating that there isn’t an app extension within the app bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationExtensionNotFound"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/applicationExtensionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorApplicationExtensionNotFound"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.applicationExtensionNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/applicationextensionnotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize": {
      "abstract": [
        {
          "text": "An error indicating a failed sync attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotSynchronize"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorCannotSynchronize"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.cannotSynchronize",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/cannotsynchronize"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected": {
      "abstract": [
        {
          "text": "An error indicating a failed deletion action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletionRejected"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDeletionRejected"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.deletionRejected",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/deletionrejected"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty": {
      "abstract": [
        {
          "text": "An error indicating an attempt to nonrecursively delete a directory that isn’t empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryNotEmpty"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDirectoryNotEmpty"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.directoryNotEmpty",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/directorynotempty"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/domainDisabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domainDisabled"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/domainDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDomainDisabled"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.domainDisabled",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/domaindisabled"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/excludedFromSync": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludedFromSync"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/excludedFromSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorExcludedFromSync"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.excludedFromSync",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/excludedfromsync"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision": {
      "abstract": [
        {
          "text": "An error indicating that an item with the same name already exists in the same directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filenameCollision"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorFilenameCollision"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.filenameCollision",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/filenamecollision"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/init(rawvalue:)"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t upload the item because it would push the account over its quota.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientQuota"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorInsufficientQuota"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.insufficientQuota",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/insufficientquota"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is a newer version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newerExtensionVersionFound"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNewerExtensionVersionFound"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.newerExtensionVersionFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/newerextensionversionfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem": {
      "abstract": [
        {
          "text": "An error indicating that the specified item doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchItem"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNoSuchItem"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.noSuchItem",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/nosuchitem"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictable"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonEvictable"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.nonEvictable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/nonevictable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict a directory because it contains nonevictable items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictableChildren"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonEvictableChildren"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.nonEvictableChildren",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/nonevictablechildren"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated": {
      "abstract": [
        {
          "text": "An error indicating that you can’t verify the user’s credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNotAuthenticated"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.notAuthenticated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/notauthenticated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is an older version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "olderExtensionVersionRunning"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorOlderExtensionVersionRunning"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.olderExtensionVersionRunning",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/olderextensionversionrunning"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/pageExpired": {
      "abstract": [
        {
          "text": "An error indicating that the page is too old, and that the system must restart the enumeration operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/pageExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "pageExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/pageexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainNotFound": {
      "abstract": [
        {
          "text": "An error indicating that there isn’t a registered domain for the corresponding identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDomainNotFound"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorProviderDomainNotFound"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.providerDomainNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/providerdomainnotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An error indicating that the system is unable to service requests for the domain temporarily, and you can try again later.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDomainTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorProviderDomainTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.providerDomainTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/providerdomaintemporarilyunavailable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider manager can’t find the specified provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerNotFound"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorProviderNotFound"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.providerNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/providernotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated": {
      "abstract": [
        {
          "text": "An error indicating the File Provider extension is in a disabled state due to Gatekeeper’s restrictions for apps from outside the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerTranslocated"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorProviderTranslocated"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.providerTranslocated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/providertranslocated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t reach the remote server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverUnreachable"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorServerUnreachable"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.serverUnreachable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/serverunreachable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired": {
      "abstract": [
        {
          "text": "An error indicating that the sync anchor is too old, and that the system must restart the sync operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncAnchorExpired"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorSyncAnchorExpired"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.syncAnchorExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/syncanchorexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits": {
      "abstract": [
        {
          "text": "An error indicating that the item contains unsynced changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsyncedEdits"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorUnsyncedEdits"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.unsyncedEdits",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/unsyncededits"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/versionNoLongerAvailable": {
      "abstract": [
        {
          "text": "An error indicating that the specified version is no longer available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionNoLongerAvailable"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/versionNoLongerAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorVersionNoLongerAvailable"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.versionNoLongerAvailable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/versionnolongeravailable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCode/NSFileProviderErrorPageExpired": {
      "abstract": [
        {
          "text": "An error indicating that the page is too old, and that the system must restart the enumeration operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorPageExpired"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCode/NSFileProviderErrorPageExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileProviderErrorPageExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrorcode/nsfileprovidererrorpageexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey": {
      "abstract": [
        {
          "text": "The key for accessing the existing item from a filename collision error’s user info dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorCollidingItemKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorCollidingItemKey"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorCollidingItemKey",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrorcollidingitemkey"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorDomain",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrordomain"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey": {
      "abstract": [
        {
          "text": "The key for accessing information about sync-related errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorItemKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorItemKey"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorItemKey",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererroritemkey"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey": {
      "abstract": [
        {
          "text": "The key for accessing the specified item’s identifier when the item doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonExistentItemIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorNonExistentItemIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderErrorNonExistentItemIdentifierKey",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererrornonexistentitemidentifierkey"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/pageExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/versionNoLongerAvailable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/domainDisabled",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/excludedFromSync",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/applicationExtensionNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainTemporarilyUnavailable"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-codes",
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/filenameCollision",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/insufficientQuota",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/noSuchItem",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/notAuthenticated",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/serverUnreachable",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/syncAnchorExpired",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/directoryNotEmpty",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerNotFound",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerTranslocated",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/olderExtensionVersionRunning",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/newerExtensionVersionFound",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictable",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/nonEvictableChildren",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/unsyncedEdits",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/cannotSynchronize",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/versionNoLongerAvailable",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/domainDisabled",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/excludedFromSync",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/applicationExtensionNotFound",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainNotFound",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/providerDomainTemporarilyUnavailable"
              ],
              "title": "Error codes"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCode/NSFileProviderErrorPageExpired"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorDomain",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorItemKey",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorNonExistentItemIdentifierKey",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderErrorCollidingItemKey"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1unsyncedEdits/title",
          "value": "NSFileProviderErrorUnsyncedEdits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1unsyncedEdits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorUnsyncedEdits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1serverUnreachable/title",
          "value": "NSFileProviderErrorServerUnreachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1serverUnreachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorServerUnreachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1cannotSynchronize/title",
          "value": "NSFileProviderErrorCannotSynchronize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1cannotSynchronize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCannotSynchronize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictable/title",
          "value": "NSFileProviderErrorNonEvictable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNonEvictable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1excludedFromSync/title",
          "value": "NSFileProviderErrorExcludedFromSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1excludedFromSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorExcludedFromSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerTranslocated/title",
          "value": "NSFileProviderErrorProviderTranslocated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerTranslocated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderTranslocated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerDomainTemporarilyUnavailable/title",
          "value": "NSFileProviderErrorProviderDomainTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerDomainTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderDomainTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorNonExistentItemIdentifierKey/title",
          "value": "NSFileProviderErrorNonExistentItemIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorNonExistentItemIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNonExistentItemIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1noSuchItem/title",
          "value": "NSFileProviderErrorNoSuchItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1noSuchItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNoSuchItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1domainDisabled/title",
          "value": "NSFileProviderErrorDomainDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1domainDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDomainDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1versionNoLongerAvailable/title",
          "value": "NSFileProviderErrorVersionNoLongerAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1versionNoLongerAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorVersionNoLongerAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerNotFound/title",
          "value": "NSFileProviderErrorProviderNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1notAuthenticated/title",
          "value": "NSFileProviderErrorNotAuthenticated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1notAuthenticated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNotAuthenticated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1insufficientQuota/title",
          "value": "NSFileProviderErrorInsufficientQuota"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1insufficientQuota/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorInsufficientQuota"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1applicationExtensionNotFound/title",
          "value": "NSFileProviderErrorApplicationExtensionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1applicationExtensionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorApplicationExtensionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1filenameCollision/title",
          "value": "NSFileProviderErrorFilenameCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1filenameCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorFilenameCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerDomainNotFound/title",
          "value": "NSFileProviderErrorProviderDomainNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1providerDomainNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorProviderDomainNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictableChildren/title",
          "value": "NSFileProviderErrorNonEvictableChildren"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1nonEvictableChildren/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNonEvictableChildren"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1deletionRejected/title",
          "value": "NSFileProviderErrorDeletionRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1deletionRejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDeletionRejected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1newerExtensionVersionFound/title",
          "value": "NSFileProviderErrorNewerExtensionVersionFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1newerExtensionVersionFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorNewerExtensionVersionFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorDomain/title",
          "value": "NSFileProviderErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1directoryNotEmpty/title",
          "value": "NSFileProviderErrorDirectoryNotEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1directoryNotEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDirectoryNotEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1syncAnchorExpired/title",
          "value": "NSFileProviderErrorSyncAnchorExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1syncAnchorExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorSyncAnchorExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1olderExtensionVersionRunning/title",
          "value": "NSFileProviderErrorOlderExtensionVersionRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1olderExtensionVersionRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorOlderExtensionVersionRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/title",
          "value": "NSFileProviderErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorItemKey/title",
          "value": "NSFileProviderErrorItemKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorItemKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorItemKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorCollidingItemKey/title",
          "value": "NSFileProviderErrorCollidingItemKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderErrorCollidingItemKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCollidingItemKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidererror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidererror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
