{
  "abstract": [
    {
      "text": "An error indicating a failed deletion action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/deletionRejected"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC23NSFileProviderErrorCodeLeV16deletionRejectedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deletionRejected"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
        "text": "NSFileProviderError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "deletionRejected"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deletionRejected"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
              "text": "NSFileProviderError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user tries to delete an item, but your extension needs to reject the deletion (for example, due to a conflicting remote change), return an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " error. The system recreates the deleted item based on the latest metadata available from your extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/3603574-fileprovidererrorforrejecteddele",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create the error object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror/3603574-fileprovidererrorforrejecteddele": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "fileProviderErrorForRejectedDeletion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": NSFileProviderItem) -> Self"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/3603574-fileprovidererrorforrejecteddele",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileProviderErrorForRejectedDeletion(of:)",
      "type": "topic",
      "url": "/documentation/foundation/nserror/3603574-fileprovidererrorforrejecteddele"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError": {
      "abstract": [
        {
          "text": "A structure that contains information about File Provider extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderError"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code": {
      "abstract": [
        {
          "text": "The error codes for the File Provider extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected": {
      "abstract": [
        {
          "text": "An error indicating a failed deletion action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletionRejected"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code/deletionRejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderErrorDeletionRejected"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderError.Code.deletionRejected",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/code/deletionrejected"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/deletionRejected": {
      "abstract": [
        {
          "text": "An error indicating a failed deletion action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletionRejected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/deletionRejected",
      "kind": "symbol",
      "role": "symbol",
      "title": "deletionRejected",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/deletionrejected"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/directoryNotEmpty": {
      "abstract": [
        {
          "text": "An error indicating an attempt to nonrecursively delete a directory that isn’t empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directoryNotEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/directoryNotEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "directoryNotEmpty",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/directorynotempty"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/filenameCollision": {
      "abstract": [
        {
          "text": "An error indicating that an item with the same name already exists in the same directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filenameCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/filenameCollision",
      "kind": "symbol",
      "role": "symbol",
      "title": "filenameCollision",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/filenamecollision"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/insufficientQuota": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t upload the item because it would push the account over its quota.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientQuota"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/insufficientQuota",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientQuota",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/insufficientquota"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/newerExtensionVersionFound": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is a newer version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newerExtensionVersionFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/newerExtensionVersionFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "newerExtensionVersionFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/newerextensionversionfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/noSuchItem": {
      "abstract": [
        {
          "text": "An error indicating that the specified item doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/noSuchItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "noSuchItem",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/nosuchitem"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictable",
      "kind": "symbol",
      "role": "symbol",
      "title": "nonEvictable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/nonevictable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictableChildren": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t evict a directory because it contains nonevictable items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonEvictableChildren"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictableChildren",
      "kind": "symbol",
      "role": "symbol",
      "title": "nonEvictableChildren",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/nonevictablechildren"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/notAuthenticated": {
      "abstract": [
        {
          "text": "An error indicating that you can’t verify the user’s credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/notAuthenticated",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthenticated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/notauthenticated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/olderExtensionVersionRunning": {
      "abstract": [
        {
          "text": "An error indicating that the registered provider in the system is an older version than the one the app uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "olderExtensionVersionRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/olderExtensionVersionRunning",
      "kind": "symbol",
      "role": "symbol",
      "title": "olderExtensionVersionRunning",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/olderextensionversionrunning"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/pageExpired": {
      "abstract": [
        {
          "text": "An error indicating that the page is too old, and that the system must restart the enumeration operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/pageExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "pageExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/pageexpired"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerNotFound": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider manager can’t find the specified provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerNotFound",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/providernotfound"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerTranslocated": {
      "abstract": [
        {
          "text": "An error indicating the File Provider extension is in a disabled state due to Gatekeeper’s restrictions for apps from outside the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerTranslocated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerTranslocated",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerTranslocated",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/providertranslocated"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/serverUnreachable": {
      "abstract": [
        {
          "text": "An error indicating that the File Provider extension can’t reach the remote server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverUnreachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/serverUnreachable",
      "kind": "symbol",
      "role": "symbol",
      "title": "serverUnreachable",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/serverunreachable"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/syncAnchorExpired": {
      "abstract": [
        {
          "text": "An error indicating that the sync anchor is too old, and that the system must restart the sync operation from the beginning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncAnchorExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC23NSFileProviderErrorCodeLeV",
          "text": "NSFileProviderError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/syncAnchorExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "syncAnchorExpired",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidererror/syncanchorexpired"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/Code",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/filenameCollision",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/insufficientQuota",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/noSuchItem",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/notAuthenticated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/pageExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/serverUnreachable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/syncAnchorExpired",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/directoryNotEmpty",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerNotFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/providerTranslocated",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/olderExtensionVersionRunning",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/newerExtensionVersionFound",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictable",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderError/nonEvictableChildren"
      ],
      "title": "Accessing error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1deletionRejected/title",
          "value": "NSFileProviderErrorDeletionRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code~1deletionRejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorDeletionRejected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/title",
          "value": "NSFileProviderErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nserror~13603574-fileprovidererrorforrejecteddele/title",
          "value": "fileProviderErrorForRejectedDeletionOfItem:"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidererror/deletionrejected"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
