{
  "abstract": [
    {
      "text": "A view that is always displayed using a left-to-right layout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceLeftToRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKInterfaceSemanticContentAttribute@WKInterfaceSemanticContentAttributeForceLeftToRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "forceLeftToRight"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKInterfaceSemanticContentAttributeForceLeftToRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKInterfaceSemanticContentAttribute.forceLeftToRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forceLeftToRight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSemanticContentAttribute",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacesemanticcontentattribute"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceLeftToRight": {
      "abstract": [
        {
          "text": "A view that is always displayed using a left-to-right layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceLeftToRight"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceLeftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttributeForceLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSemanticContentAttribute.forceLeftToRight",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacesemanticcontentattribute/forcelefttoright"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceRightToLeft": {
      "abstract": [
        {
          "text": "A view that is always displayed using a left-to-right layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceRightToLeft"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceRightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttributeForceRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSemanticContentAttribute.forceRightToLeft",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacesemanticcontentattribute/forcerighttoleft"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/playback": {
      "abstract": [
        {
          "text": "A view representing the playback controls, such as Play, Rewind, or Fast Forward buttons or playhead scrubbers. These views are not flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/playback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttributePlayback"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSemanticContentAttribute.playback",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacesemanticcontentattribute/playback"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/spatial": {
      "abstract": [
        {
          "text": "A view representing a directional control, for example a segment control for text alignment, or a D-pad control for a game. These views are not flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatial"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/spatial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttributeSpatial"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSemanticContentAttribute.spatial",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacesemanticcontentattribute/spatial"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/unspecified": {
      "abstract": [
        {
          "text": "The default value for views. The view is flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSemanticContentAttributeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSemanticContentAttribute.unspecified",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacesemanticcontentattribute/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/unspecified",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/playback",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/spatial",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceRightToLeft"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKInterfaceSemanticContentAttributeForceLeftToRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttributeForceLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/unspecified",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/playback",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/spatial",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSemanticContentAttribute/forceRightToLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKInterfaceSemanticContentAttributeForceLeftToRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1forceRightToLeft/title",
          "value": "WKInterfaceSemanticContentAttributeForceRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1forceRightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttributeForceRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1forceLeftToRight/title",
          "value": "WKInterfaceSemanticContentAttributeForceLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1forceLeftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttributeForceLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1unspecified/title",
          "value": "WKInterfaceSemanticContentAttributeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttributeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1spatial/title",
          "value": "WKInterfaceSemanticContentAttributeSpatial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1spatial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttributeSpatial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute/title",
          "value": "WKInterfaceSemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1playback/title",
          "value": "WKInterfaceSemanticContentAttributePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSemanticContentAttribute~1playback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSemanticContentAttributePlayback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkinterfacesemanticcontentattribute/forcelefttoright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkinterfacesemanticcontentattribute/forcelefttoright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
