{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:6Speech25SFCustomLanguageModelDataC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFCustomLanguageModelData"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFCustomLanguageModelData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SFCustomLanguageModelData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFCustomLanguageModelData"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCustomLanguageModelData"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCustomLanguageModelData"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/CompoundTemplate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompoundTemplate"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/CompoundTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompoundTemplate"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.CompoundTemplate",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/compoundtemplate"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/CustomPronunciation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomPronunciation"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/CustomPronunciation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CustomPronunciation"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.CustomPronunciation",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/custompronunciation"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/DataInsertableBuilder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataInsertableBuilder"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/DataInsertableBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataInsertableBuilder"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.DataInsertableBuilder",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/datainsertablebuilder"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhraseCount"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhraseCount"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.PhraseCount",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/phrasecount"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCountGenerator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhraseCountGenerator"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCountGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhraseCountGenerator"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.PhraseCountGenerator",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/phrasecountgenerator"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCountsFromTemplates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhraseCountsFromTemplates"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCountsFromTemplates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhraseCountsFromTemplates"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.PhraseCountsFromTemplates",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/phrasecountsfromtemplates"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/TemplateInsertableBuilder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TemplateInsertableBuilder"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/TemplateInsertableBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TemplateInsertableBuilder"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.TemplateInsertableBuilder",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/templateinsertablebuilder"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/TemplatePhraseCountGenerator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TemplatePhraseCountGenerator"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/TemplatePhraseCountGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TemplatePhraseCountGenerator"
        }
      ],
      "role": "symbol",
      "title": "SFCustomLanguageModelData.TemplatePhraseCountGenerator",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/templatephrasecountgenerator"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/export(to:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "export"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/export(to:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "export(to:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/export(to:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/identifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/identifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/identifier"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/init(locale:identifier:version:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/init(locale:identifier:version:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(locale:identifier:version:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/init(locale:identifier:version:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/init(locale:identifier:version:builder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "builder"
        },
        {
          "kind": "text",
          "text": ": () -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech14DataInsertableP",
          "text": "DataInsertable"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/init(locale:identifier:version:builder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(locale:identifier:version:builder:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/init(locale:identifier:version:builder:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(phraseCount:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "phraseCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech25SFCustomLanguageModelDataC",
          "text": "SFCustomLanguageModelData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech25SFCustomLanguageModelDataC11PhraseCountV",
          "text": "PhraseCount"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(phraseCount:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(phraseCount:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/insert(phrasecount:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(phraseCountGenerator:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "phraseCountGenerator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech25SFCustomLanguageModelDataC",
          "text": "SFCustomLanguageModelData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech25SFCustomLanguageModelDataC20PhraseCountGeneratorC",
          "text": "PhraseCountGenerator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(phraseCountGenerator:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(phraseCountGenerator:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/insert(phrasecountgenerator:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(term:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "term"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech25SFCustomLanguageModelDataC",
          "text": "SFCustomLanguageModelData"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Speech25SFCustomLanguageModelDataC19CustomPronunciationV",
          "text": "CustomPronunciation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(term:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(term:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/insert(term:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/locale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/locale",
      "kind": "symbol",
      "role": "symbol",
      "title": "locale",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/locale"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/supportedPhonemes(locale:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedPhonemes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/supportedPhonemes(locale:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedPhonemes(locale:)",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/supportedphonemes(locale:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/version": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/version",
      "kind": "symbol",
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/speech/sfcustomlanguagemodeldata/version"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechLanguageModel"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechLanguageModel"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechLanguageModel",
      "type": "topic",
      "url": "/documentation/speech/sfspeechlanguagemodel"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechLanguageModel.Configuration",
      "type": "topic",
      "url": "/documentation/speech/sfspeechlanguagemodel/configuration"
    },
    "doc://com.externally.resolved.symbol/s:SE": {
      "abstract": [
        {
          "text": "A type that can encode itself to an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Encodable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SE",
      "kind": "symbol",
      "role": "symbol",
      "title": "Encodable",
      "type": "topic",
      "url": "/documentation/Swift/Encodable"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:Se": {
      "abstract": [
        {
          "text": "A type that can decode itself from an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Decodable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Se",
      "kind": "symbol",
      "role": "symbol",
      "title": "Decodable",
      "type": "topic",
      "url": "/documentation/Swift/Decodable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:Se",
        "doc://com.externally.resolved.symbol/s:SE",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel",
        "doc://com.apple.speech/documentation/Speech/SFSpeechLanguageModel/Configuration"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/init(locale:identifier:version:)",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/init(locale:identifier:version:builder:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/identifier",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/locale",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/version"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/export(to:)",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(phraseCount:)",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(phraseCountGenerator:)",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/insert(term:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/supportedPhonemes(locale:)"
      ],
      "title": "Type Methods"
    },
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCountGenerator",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/TemplatePhraseCountGenerator"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/CompoundTemplate",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/CustomPronunciation",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/DataInsertableBuilder",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCount",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/PhraseCountsFromTemplates",
        "doc://com.apple.speech/documentation/Speech/SFCustomLanguageModelData/TemplateInsertableBuilder"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel/title",
          "value": "SFSpeechLanguageModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel~1Configuration/title",
          "value": "SFSpeechLanguageModelConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel~1Configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechLanguageModel~1Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechLanguageModelConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfcustomlanguagemodeldata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
