{
  "abstract": [
    {
      "text": "A request to recognize speech in a recorded audio file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFSpeechURLRecognitionRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFSpeechURLRecognitionRequest"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSpeechURLRecognitionRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SFSpeechURLRecognitionRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this object to perform speech recognition on the contents of an audio file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows a method that performs recognition on an audio file based on the user’s default language and prints out the transcription.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Getting a speech recognizer and making a recognition request",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func recognizeFile(url: URL) {",
            "    // Create a speech recognizer associated with the user's default language.",
            "    guard let myRecognizer = SFSpeechRecognizer() else {",
            "        // The system doesn't support the user's default language.",
            "        return",
            "    }",
            "    ",
            "    guard myRecognizer.isAvailable else {",
            "        // The recognizer isn't available.",
            "        return",
            "    }",
            "    ",
            "    // Create and execute a speech recognition request for the audio file at the URL.",
            "    let request = SFSpeechURLRecognitionRequest(url: url)",
            "    myRecognizer.recognitionTask(with: request) { (result, error) in",
            "        guard let result else {",
            "            // Recognition failed, so check the error for details and handle it.",
            "            return",
            "        }",
            "        ",
            "        // Print the speech transcription with the highest confidence that the",
            "        // system recognized.",
            "        if result.isFinal {",
            "            print(result.bestTranscription.formattedString)",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest": {
      "abstract": [
        {
          "text": "A request to recognize speech from captured audio content, such as audio from the device’s microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechAudioBufferRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechAudioBufferRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechAudioBufferRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest": {
      "abstract": [
        {
          "text": "An abstract class that represents a request to recognize speech from an audio source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest": {
      "abstract": [
        {
          "text": "A request to recognize speech in a recorded audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechURLRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechURLRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechURLRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechurlrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/init(url:)": {
      "abstract": [
        {
          "text": "Creates a speech recognition request, initialized with the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/init(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:"
        }
      ],
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/speech/sfspeechurlrecognitionrequest/init(url:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/url": {
      "abstract": [
        {
          "text": "The URL of the audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/speech/sfspeechurlrecognitionrequest/url"
    },
    "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio": {
      "abstract": [
        {
          "text": "Perform speech recognition on audio coming from the microphone of an iOS device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
      "kind": "article",
      "role": "sampleCode",
      "title": "Recognizing speech in live audio",
      "type": "topic",
      "url": "/documentation/speech/recognizing-speech-in-live-audio"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
        "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
      ],
      "title": "Audio sources"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Speech-Recognition-Request",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/init(url:)"
      ],
      "title": "Creating a Speech Recognition Request"
    },
    {
      "anchor": "Accessing-the-URL-of-the-Audio-File",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/url"
      ],
      "title": "Accessing the URL of the Audio File"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSpeechURLRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Speech-Recognition-Request",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/init(url:)"
              ],
              "title": "Creating a Speech Recognition Request"
            },
            {
              "anchor": "Accessing-the-URL-of-the-Audio-File",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest/url"
              ],
              "title": "Accessing the URL of the Audio File"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-sources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
                "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
              ],
              "title": "Audio sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SFSpeechURLRecognitionRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SFSpeechRecognitionRequest",
                    "text": "SFSpeechRecognitionRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/title",
          "value": "SFSpeechRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/title",
          "value": "SFSpeechAudioBufferRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest~1init(url:)/title",
          "value": "initWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest~1init(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/title",
          "value": "SFSpeechURLRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfspeechurlrecognitionrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfspeechurlrecognitionrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
