{
  "abstract": [
    {
      "text": "A request to recognize speech from captured audio content, such as audio from the device’s microphone.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFSpeechAudioBufferRecognitionRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFSpeechAudioBufferRecognitionRequest"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSpeechAudioBufferRecognitionRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SFSpeechAudioBufferRecognitionRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to perform speech recognition on live audio, or on a set of existing audio buffers. For example, use this request object to route audio from a device’s microphone to the speech recognizer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The request object contains no audio initially. As you capture audio, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/append(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/appendAudioSampleBuffer(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to add audio samples to the request object. The speech recognizer continuously analyzes the audio you appended, stopping only when you call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/endAudio()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. You must call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/endAudio()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " explicitly to stop the speech recognition process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For a complete example of how to use audio buffers with speech recognition, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/samplecode/SpeakToMe/Introduction/Intro.html#//apple_ref/doc/uid/TP40017110",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest": {
      "abstract": [
        {
          "text": "A request to recognize speech from captured audio content, such as audio from the device’s microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechAudioBufferRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechAudioBufferRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechAudioBufferRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/append(_:)": {
      "abstract": [
        {
          "text": "Appends audio in the PCM format to the end of the recognition request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioPCMBuffer",
          "text": "AVAudioPCMBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/append(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appendAudioPCMBuffer:"
        }
      ],
      "role": "symbol",
      "title": "append(_:)",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest/append(_:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/appendAudioSampleBuffer(_:)": {
      "abstract": [
        {
          "text": "Appends audio to the end of the recognition request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendAudioSampleBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/appendAudioSampleBuffer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appendAudioSampleBuffer:"
        }
      ],
      "role": "symbol",
      "title": "appendAudioSampleBuffer(_:)",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest/appendaudiosamplebuffer(_:)"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/endAudio()": {
      "abstract": [
        {
          "text": "Marks the end of audio input for the recognition request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endAudio"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/endAudio()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endAudio"
        }
      ],
      "role": "symbol",
      "title": "endAudio()",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest/endaudio()"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/nativeAudioFormat": {
      "abstract": [
        {
          "text": "The preferred audio format for optimal speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeAudioFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioFormat",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/nativeAudioFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nativeAudioFormat"
        }
      ],
      "role": "symbol",
      "title": "nativeAudioFormat",
      "type": "topic",
      "url": "/documentation/speech/sfspeechaudiobufferrecognitionrequest/nativeaudioformat"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest": {
      "abstract": [
        {
          "text": "An abstract class that represents a request to recognize speech from an audio source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest": {
      "abstract": [
        {
          "text": "A request to recognize speech in a recorded audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechURLRecognitionRequest"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechURLRecognitionRequest"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechURLRecognitionRequest",
      "type": "topic",
      "url": "/documentation/speech/sfspeechurlrecognitionrequest"
    },
    "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio": {
      "abstract": [
        {
          "text": "Perform speech recognition on audio coming from the microphone of an iOS device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
      "kind": "article",
      "role": "sampleCode",
      "title": "Recognizing speech in live audio",
      "type": "topic",
      "url": "/documentation/speech/recognizing-speech-in-live-audio"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/samplecode/SpeakToMe/Introduction/Intro.html#//apple_ref/doc/uid/TP40017110": {
      "identifier": "https://developer.apple.com/library/archive/samplecode/SpeakToMe/Introduction/Intro.html#//apple_ref/doc/uid/TP40017110",
      "title": "SpeakToMe: Using Speech Recognition with AVAudioEngine",
      "titleInlineContent": [
        {
          "text": "SpeakToMe: Using Speech Recognition with AVAudioEngine",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/samplecode/SpeakToMe/Introduction/Intro.html#//apple_ref/doc/uid/TP40017110"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
        "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
      ],
      "title": "Audio sources"
    }
  ],
  "topicSections": [
    {
      "anchor": "Appending-Audio-Buffers",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/append(_:)",
        "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/appendAudioSampleBuffer(_:)",
        "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/endAudio()"
      ],
      "title": "Appending Audio Buffers"
    },
    {
      "anchor": "Getting-the-Audio-Format",
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/nativeAudioFormat"
      ],
      "title": "Getting the Audio Format"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSpeechAudioBufferRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Appending-Audio-Buffers",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/append(_:)",
                "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/appendAudioSampleBuffer(_:)",
                "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/endAudio()"
              ],
              "title": "Appending Audio Buffers"
            },
            {
              "anchor": "Getting-the-Audio-Format",
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechAudioBufferRecognitionRequest/nativeAudioFormat"
              ],
              "title": "Getting the Audio Format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-sources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/recognizing-speech-in-live-audio",
                "doc://com.apple.speech/documentation/Speech/SFSpeechURLRecognitionRequest",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest"
              ],
              "title": "Audio sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SFSpeechAudioBufferRecognitionRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SFSpeechRecognitionRequest",
                    "text": "SFSpeechRecognitionRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/title",
          "value": "SFSpeechAudioBufferRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechAudioBufferRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1nativeAudioFormat/title",
          "value": "nativeAudioFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1nativeAudioFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nativeAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1append(_:)/title",
          "value": "appendAudioPCMBuffer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1append(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "appendAudioPCMBuffer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1endAudio()/title",
          "value": "endAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1endAudio()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1appendAudioSampleBuffer(_:)/title",
          "value": "appendAudioSampleBuffer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechAudioBufferRecognitionRequest~1appendAudioSampleBuffer(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "appendAudioSampleBuffer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/title",
          "value": "SFSpeechURLRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechURLRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechURLRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/title",
          "value": "SFSpeechRecognitionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfspeechaudiobufferrecognitionrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfspeechaudiobufferrecognitionrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
