{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions/NSWritingToolsResultDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWritingToolsResultOptions@NSWritingToolsResultDefault",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSWritingToolsResultDefault"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWritingToolsResultDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSWritingToolsResultDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultDefault"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions": {
      "abstract": [
        {
          "text": "Constants to specify what type of content to allow in Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions or rewrites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsResultOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions/NSWritingToolsResultDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions/NSWritingToolsResultDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWritingToolsResultDefault",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions/nswritingtoolsresultdefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/title",
          "value": "NSWritingToolsResultOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswritingtoolsresultoptions/nswritingtoolsresultdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
