{"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)"],"title":"Zooming Window","generated":true,"anchor":"Zooming-Window"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","title":"windowWillUseStandardFrame(_:defaultFrame:)","externalID":"c:objc(pl)NSWindowDelegate(im)windowWillUseStandardFrame:defaultFrame:","modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowWillUseStandardFrame","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"defaultFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"}],"platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"navigatorTitle":[{"text":"windowWillUseStandardFrame:defaultFrame:","kind":"identifier"}]},"sections":[],"variants":[{"paths":["/documentation/appkit/nswindowdelegate/windowwillusestandardframe(_:defaultframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindowdelegate/windowwillusestandardframe(_:defaultframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowWillUseStandardFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"window","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":", ","kind":"text"},{"text":"defaultFrame","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"newFrame","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"window","content":[{"inlineContent":[{"text":"The window whose frame size is being determined.","type":"text"}],"type":"paragraph"}]},{"name":"newFrame","content":[{"inlineContent":[{"type":"text","text":"The size of the current screen, which is the screen containing the largest part of the window’s current frame, possibly reduced on the top, bottom, left, or right, depending on the current interface style. The frame is reduced on the top to leave room for the menu bar."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The specified window’s standard frame.","type":"text"}]}],"kind":"content"},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The standard frame for a window should supply the size and location that are “best” for the type of information shown in the window, taking into account the available display or displays. For example, the best width for a window that displays a word-processing document is the width of a page or the width of the display, whichever is smaller. The best height can be determined similarly. On return from this method, the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","isActive":true},{"type":"text","text":" method modifies the returned standard frame, if necessary, to fit on the current screen."}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate"]]},"abstract":[{"text":"Called by ","type":"text"},{"type":"codeVoice","code":"NSWindow"},{"text":"’s ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","isActive":true,"type":"reference"},{"text":" method while determining the frame a window may be zoomed to.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowWillUseStandardFrame","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"defaultFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"}],"url":"/documentation/appkit/nswindowdelegate/windowwillusestandardframe(_:defaultframe:)","navigatorTitle":[{"text":"windowWillUseStandardFrame:defaultFrame:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Called by "},{"type":"codeVoice","code":"NSWindow"},{"text":"’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)"},{"text":" method while determining the frame a window may be zoomed to.","type":"text"}],"title":"windowWillUseStandardFrame(_:defaultFrame:)","role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)":{"type":"topic","url":"/documentation/appkit/nswindowdelegate/windowshouldzoom(_:toframe:)","role":"symbol","abstract":[{"text":"Asks the delegate whether the specified window should zoom to the specified frame.","type":"text"}],"navigatorTitle":[{"text":"windowShouldZoom:toFrame:","kind":"identifier"}],"title":"windowShouldZoom(_:toFrame:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"windowShouldZoom"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)":{"title":"zoom(_:)","navigatorTitle":[{"kind":"identifier","text":"zoom:"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","role":"symbol","url":"/documentation/appkit/nswindow/zoom(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Toggles the size and location of the window between its standard state (which the application provides as the best size to display the window’s data) and its user state (a new size and location the user may have set by moving or resizing the window).","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate":{"kind":"symbol","navigatorTitle":[{"text":"NSWindowDelegate","kind":"identifier"}],"role":"symbol","title":"NSWindowDelegate","abstract":[{"type":"text","text":"A set of optional methods that a window’s delegate can implement to respond to events, such as window resizing, moving, exposing, and minimizing."}],"url":"/documentation/appkit/nswindowdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSWindowDelegate"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"windowWillUseStandardFrame:defaultFrame:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"windowWillUseStandardFrame:defaultFrame:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Zooming-Window","title":"Zooming Window","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") ","kind":"text"},{"text":"windowWillUseStandardFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"window","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"defaultFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"newFrame"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"window","content":[{"type":"paragraph","inlineContent":[{"text":"The window whose frame size is being determined.","type":"text"}]}]},{"name":"newFrame","content":[{"type":"paragraph","inlineContent":[{"text":"The size of the current screen, which is the screen containing the largest part of the window’s current frame, possibly reduced on the top, bottom, left, or right, depending on the current interface style. The frame is reduced on the top to leave room for the menu bar.","type":"text"}]}]}]}},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"text":"The specified window’s standard frame.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowWillUseStandardFrame(_:defaultFrame:)/title","value":"windowWillUseStandardFrame:defaultFrame:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowWillUseStandardFrame(_:defaultFrame:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"windowWillUseStandardFrame:defaultFrame:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","value":"NSWindow"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","value":[{"kind":"identifier","text":"NSWindow"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","value":[{"kind":"identifier","text":"NSWindow"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowShouldZoom(_:toFrame:)/title","value":"windowShouldZoom:toFrame:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowShouldZoom(_:toFrame:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"windowShouldZoom:toFrame:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1zoom(_:)/title","value":"zoom:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1zoom(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"zoom:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate/title","value":"NSWindowDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate/fragments","value":[{"kind":"identifier","text":"NSWindowDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate/navigatorTitle","value":[{"text":"NSWindowDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}