{
  "abstract": [
    {
      "text": "The size of the packet, in bytes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vmnet/documentation/vmnet",
        "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_size"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vmpktdesc@FI@vm_pkt_size",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vm_pkt_size"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "vmnet"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vm_pkt_size"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "vm_pkt_size"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vm_pkt_size"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vmnet/documentation/vmnet": {
      "abstract": [
        {
          "text": "Connect with network interfaces to read and write packets on guest operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet",
      "kind": "symbol",
      "role": "collection",
      "title": "vmnet",
      "type": "topic",
      "url": "/documentation/vmnet"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc": {
      "abstract": [
        {
          "text": "Describes a packet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vmpktdesc"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vmpktdesc"
        }
      ],
      "role": "symbol",
      "title": "vmpktdesc",
      "type": "topic",
      "url": "/documentation/vmnet/vmpktdesc"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_flags": {
      "abstract": [
        {
          "text": "Option flags. Should be set to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " on read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vm_flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vm_flags"
        }
      ],
      "role": "symbol",
      "title": "vm_flags",
      "type": "topic",
      "url": "/documentation/vmnet/vmpktdesc/vm_flags"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iov": {
      "abstract": [
        {
          "text": "An array of packet buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vm_pkt_iov"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@iovec",
          "text": "iovec"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vm_pkt_iov"
        }
      ],
      "role": "symbol",
      "title": "vm_pkt_iov",
      "type": "topic",
      "url": "/documentation/vmnet/vmpktdesc/vm_pkt_iov"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iovcnt": {
      "abstract": [
        {
          "text": "The number of packet buffers in ",
          "type": "text"
        },
        {
          "code": "vm_pkt_iov",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vm_pkt_iovcnt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iovcnt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vm_pkt_iovcnt"
        }
      ],
      "role": "symbol",
      "title": "vm_pkt_iovcnt",
      "type": "topic",
      "url": "/documentation/vmnet/vmpktdesc/vm_pkt_iovcnt"
    },
    "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_size": {
      "abstract": [
        {
          "text": "The size of the packet, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vm_pkt_size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vm_pkt_size"
        }
      ],
      "role": "symbol",
      "title": "vm_pkt_size",
      "type": "topic",
      "url": "/documentation/vmnet/vmpktdesc/vm_pkt_size"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fields",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_flags",
        "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iov",
        "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iovcnt"
      ],
      "title": "Fields"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vm_pkt_size"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vm_pkt_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vmnet/documentation/vmnet",
                "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fields",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_flags",
                "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iov",
                "doc://com.apple.vmnet/documentation/vmnet/vmpktdesc/vm_pkt_iovcnt"
              ],
              "title": "Fields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vm_pkt_size"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc/title",
          "value": "vmpktdesc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vmpktdesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vmpktdesc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_pkt_size/title",
          "value": "vm_pkt_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_pkt_size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vm_pkt_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_pkt_iov/title",
          "value": "vm_pkt_iov"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_pkt_iov/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vm_pkt_iov"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_flags/title",
          "value": "vm_flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vm_flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_pkt_iovcnt/title",
          "value": "vm_pkt_iovcnt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vmnet~1documentation~1vmnet~1vmpktdesc~1vm_pkt_iovcnt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vm_pkt_iovcnt"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vmnet/vmpktdesc/vm_pkt_size"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vmnet/vmpktdesc/vm_pkt_size"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
