{
  "abstract": [
    {
      "text": "The F24 key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f24"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "s:So7NSEventC6AppKitE10SpecialKeyV3f24AEvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "f24"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSEvent",
        "text": "NSEvent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
        "text": "SpecialKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "f24"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "f24"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSEvent",
              "text": "NSEvent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
              "text": "SpecialKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is unavailable on most Macintosh keyboards.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct": {
      "abstract": [
        {
          "text": "Constants for reserved function keys on the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SpecialKey"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.SpecialKey",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f1": {
      "abstract": [
        {
          "text": "The F1 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f1",
      "kind": "symbol",
      "role": "symbol",
      "title": "f1",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f10": {
      "abstract": [
        {
          "text": "The F10 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f10",
      "kind": "symbol",
      "role": "symbol",
      "title": "f10",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f10"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f11": {
      "abstract": [
        {
          "text": "The F11 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f11",
      "kind": "symbol",
      "role": "symbol",
      "title": "f11",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f11"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f12": {
      "abstract": [
        {
          "text": "The F12 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f12",
      "kind": "symbol",
      "role": "symbol",
      "title": "f12",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f12"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f13": {
      "abstract": [
        {
          "text": "The F13 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f13",
      "kind": "symbol",
      "role": "symbol",
      "title": "f13",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f13"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f14": {
      "abstract": [
        {
          "text": "The F14 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f14",
      "kind": "symbol",
      "role": "symbol",
      "title": "f14",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f14"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f15": {
      "abstract": [
        {
          "text": "The F15 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f15"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f15",
      "kind": "symbol",
      "role": "symbol",
      "title": "f15",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f15"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f2": {
      "abstract": [
        {
          "text": "The F2 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f2",
      "kind": "symbol",
      "role": "symbol",
      "title": "f2",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f24": {
      "abstract": [
        {
          "text": "The F24 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f24",
      "kind": "symbol",
      "role": "symbol",
      "title": "f24",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f24"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f3": {
      "abstract": [
        {
          "text": "The F3 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f3",
      "kind": "symbol",
      "role": "symbol",
      "title": "f3",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f4": {
      "abstract": [
        {
          "text": "The F4 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f4",
      "kind": "symbol",
      "role": "symbol",
      "title": "f4",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f4"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f5": {
      "abstract": [
        {
          "text": "The F5 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f5",
      "kind": "symbol",
      "role": "symbol",
      "title": "f5",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f5"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f6": {
      "abstract": [
        {
          "text": "The F6 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f6",
      "kind": "symbol",
      "role": "symbol",
      "title": "f6",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f6"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f7": {
      "abstract": [
        {
          "text": "The F7 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f7",
      "kind": "symbol",
      "role": "symbol",
      "title": "f7",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f7"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f8": {
      "abstract": [
        {
          "text": "The F8 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f8",
      "kind": "symbol",
      "role": "symbol",
      "title": "f8",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f8"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f9": {
      "abstract": [
        {
          "text": "The F9 key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "f9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f9",
      "kind": "symbol",
      "role": "symbol",
      "title": "f9",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/f9"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Function-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f1",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f2",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f3",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f4",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f5",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f6",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f7",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f8",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f9",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f10",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f11",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f12",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f13",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f14",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/f15"
      ],
      "title": "Getting the Function Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/specialkey-swift.struct/f24"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
