{
  "abstract": [
    {
      "text": "The system request key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/sysReq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "s:So7NSEventC6AppKitE10SpecialKeyV6sysReqAEvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sysReq"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSEvent",
        "text": "NSEvent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
        "text": "SpecialKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "sysReq"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sysReq"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSEvent",
              "text": "NSEvent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
              "text": "SpecialKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is unavailable on most Macintosh keyboards.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct": {
      "abstract": [
        {
          "text": "Constants for reserved function keys on the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SpecialKey"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.SpecialKey",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/begin": {
      "abstract": [
        {
          "text": "The begin key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "begin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "begin",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/begin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/break": {
      "abstract": [
        {
          "text": "The break key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`break`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/break",
      "kind": "symbol",
      "role": "symbol",
      "title": "break",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/break"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/clearDisplay": {
      "abstract": [
        {
          "text": "The clear display key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/clearDisplay",
      "kind": "symbol",
      "role": "symbol",
      "title": "clearDisplay",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/cleardisplay"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/clearLine": {
      "abstract": [
        {
          "text": "The clear line key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/clearLine",
      "kind": "symbol",
      "role": "symbol",
      "title": "clearLine",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/clearline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/deleteCharacter": {
      "abstract": [
        {
          "text": "The delete character key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/deleteCharacter",
      "kind": "symbol",
      "role": "symbol",
      "title": "deleteCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/deletecharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/deleteLine": {
      "abstract": [
        {
          "text": "The delete line key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/deleteLine",
      "kind": "symbol",
      "role": "symbol",
      "title": "deleteLine",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/deleteline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/execute": {
      "abstract": [
        {
          "text": "The execute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/execute",
      "kind": "symbol",
      "role": "symbol",
      "title": "execute",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/execute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/find": {
      "abstract": [
        {
          "text": "The find key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "find"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/find",
      "kind": "symbol",
      "role": "symbol",
      "title": "find",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/find"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/formFeed": {
      "abstract": [
        {
          "text": "The form feed key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formFeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/formFeed",
      "kind": "symbol",
      "role": "symbol",
      "title": "formFeed",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/formfeed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/help": {
      "abstract": [
        {
          "text": "The help key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "help"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/help",
      "kind": "symbol",
      "role": "symbol",
      "title": "help",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/help"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insert": {
      "abstract": [
        {
          "text": "The insert key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insert",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/insert"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insertCharacter": {
      "abstract": [
        {
          "text": "The insert character key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertCharacter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insertCharacter",
      "kind": "symbol",
      "role": "symbol",
      "title": "insertCharacter",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/insertcharacter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insertLine": {
      "abstract": [
        {
          "text": "The insert line key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insertLine",
      "kind": "symbol",
      "role": "symbol",
      "title": "insertLine",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/insertline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/lineSeparator": {
      "abstract": [
        {
          "text": "The line separator key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineSeparator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/lineSeparator",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineSeparator",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/lineseparator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/menu": {
      "abstract": [
        {
          "text": "The menu key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/menu",
      "kind": "symbol",
      "role": "symbol",
      "title": "menu",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/menu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/sysReq": {
      "abstract": [
        {
          "text": "The system request key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sysReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So7NSEventC6AppKitE10SpecialKeyV",
          "text": "SpecialKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/sysReq",
      "kind": "symbol",
      "role": "symbol",
      "title": "sysReq",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/specialkey-swift.struct/sysreq"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Special-Behavior-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/begin",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/break",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/clearDisplay",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/clearLine",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/deleteCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/deleteLine",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/execute",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/find",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/formFeed",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/help",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insert",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insertCharacter",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/insertLine",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/lineSeparator",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/SpecialKey-swift.struct/menu"
      ],
      "title": "Getting Special Behavior Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/specialkey-swift.struct/sysreq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
