{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612464-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612465-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612466-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612468-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612469-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612470-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612471-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612472-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612473-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612474-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612475-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612476-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612477-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612478-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612479-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellDeviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbellDeviceAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbelldeviceaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellDeviceAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellDeviceAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellDeviceAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellDeviceAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbellDeviceAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbelldeviceaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellEndpointAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellEndpointAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellEndpointAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellEndpointAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbellEndpointAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbellendpointaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellEndpointAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellEndpointAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellEndpointAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellEndpointAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbellEndpointAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbellendpointaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellStreamID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellStreamID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellStreamID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellStreamID"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbellStreamID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbellstreamid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellStreamIDPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellStreamIDPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellStreamIDPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbellStreamIDPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbellStreamIDPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbellstreamidphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Enumerations",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellDeviceAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellDeviceAddressPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellEndpointAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellEndpointAddressPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellStreamID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbellStreamIDPhase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellStreamIDPhase/title",
          "value": "IOUSBHostCIDoorbellStreamIDPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellStreamIDPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbellStreamIDPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellDeviceAddressPhase/title",
          "value": "IOUSBHostCIDoorbellDeviceAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellDeviceAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbellDeviceAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellEndpointAddress/title",
          "value": "IOUSBHostCIDoorbellEndpointAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellEndpointAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbellEndpointAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellEndpointAddressPhase/title",
          "value": "IOUSBHostCIDoorbellEndpointAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellEndpointAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbellEndpointAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellDeviceAddress/title",
          "value": "IOUSBHostCIDoorbellDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbellDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellStreamID/title",
          "value": "IOUSBHostCIDoorbellStreamID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbellStreamID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbellStreamID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/3612467-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
