{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612464-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612465-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612466-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612467-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612468-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612469-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612470-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612472-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612473-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612474-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612475-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612476-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612477-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612478-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612479-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlASAP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferControlASAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlASAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferControlASAP"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferControlASAP",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransfercontrolasap"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlFrameNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferControlFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlFrameNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferControlFrameNumber"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferControlFrameNumber",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransfercontrolframenumber"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlFrameNumberPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferControlFrameNumberPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlFrameNumberPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferControlFrameNumberPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferControlFrameNumberPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransfercontrolframenumberphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData0Length": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData0Length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData0Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData0Length"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferData0Length",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransferdata0length"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData0LengthPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData0LengthPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData0LengthPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData0LengthPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferData0LengthPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransferdata0lengthphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData1Buffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData1Buffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData1Buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData1Buffer"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferData1Buffer",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransferdata1buffer"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData1BufferPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData1BufferPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData1BufferPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIIsochronousTransferData1BufferPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIIsochronousTransferData1BufferPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciisochronoustransferdata1bufferphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Enumerations",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlASAP",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlFrameNumber",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferControlFrameNumberPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData0Length",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData0LengthPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData1Buffer",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIIsochronousTransferData1BufferPhase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferControlASAP/title",
          "value": "IOUSBHostCIIsochronousTransferControlASAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferControlASAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferControlASAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData0Length/title",
          "value": "IOUSBHostCIIsochronousTransferData0Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData0Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferData0Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData0LengthPhase/title",
          "value": "IOUSBHostCIIsochronousTransferData0LengthPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData0LengthPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferData0LengthPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData1BufferPhase/title",
          "value": "IOUSBHostCIIsochronousTransferData1BufferPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData1BufferPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferData1BufferPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferControlFrameNumber/title",
          "value": "IOUSBHostCIIsochronousTransferControlFrameNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferControlFrameNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferControlFrameNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferControlFrameNumberPhase/title",
          "value": "IOUSBHostCIIsochronousTransferControlFrameNumberPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferControlFrameNumberPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferControlFrameNumberPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData1Buffer/title",
          "value": "IOUSBHostCIIsochronousTransferData1Buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIIsochronousTransferData1Buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIIsochronousTransferData1Buffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/3612471-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
