{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612464-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612465-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612467-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612468-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612469-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612470-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612471-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612472-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612473-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612474-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612475-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612476-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612477-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612478-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612479-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RootPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0RootPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RootPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0RootPort"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceCreateCommandData0RootPort",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicecreatecommanddata0rootport"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RootPortPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0RootPortPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RootPortPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0RootPortPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceCreateCommandData0RootPortPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicecreatecommanddata0rootportphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0Route": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0Route"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0Route",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0Route"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceCreateCommandData0Route",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicecreatecommanddata0route"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RoutePhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0RoutePhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RoutePhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData0RoutePhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceCreateCommandData0RoutePhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicecreatecommanddata0routephase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData1DeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData1DeviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData1DeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData1DeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceCreateCommandData1DeviceAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicecreatecommanddata1deviceaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicecreatecommanddata1deviceaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Enumerations",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RootPort",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RootPortPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0Route",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData0RoutePhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData1DeviceAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase/title",
          "value": "IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceCreateCommandData1DeviceAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0Route/title",
          "value": "IOUSBHostCIDeviceCreateCommandData0Route"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0Route/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceCreateCommandData0Route"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0RoutePhase/title",
          "value": "IOUSBHostCIDeviceCreateCommandData0RoutePhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0RoutePhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceCreateCommandData0RoutePhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0RootPortPhase/title",
          "value": "IOUSBHostCIDeviceCreateCommandData0RootPortPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0RootPortPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceCreateCommandData0RootPortPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0RootPort/title",
          "value": "IOUSBHostCIDeviceCreateCommandData0RootPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData0RootPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceCreateCommandData0RootPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData1DeviceAddress/title",
          "value": "IOUSBHostCIDeviceCreateCommandData1DeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceCreateCommandData1DeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceCreateCommandData1DeviceAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/3612466-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
