{
  "abstract": [
    {
      "text": "Properties for implementing the matching service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@IOUSBHostMatchingPropertyKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostMatchingPropertyKey"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostMatchingPropertyKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "IOUSBHostMatchingPropertyKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey": {
      "abstract": [
        {
          "text": "Properties of a USB device that describe its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDevicePropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey": {
      "abstract": [
        {
          "text": "Properties of a USB interface that describe its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostInterfacePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostInterfacePropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterfacepropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey": {
      "abstract": [
        {
          "text": "Properties for implementing the matching service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostMatchingPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue": {
      "abstract": [
        {
          "text": "The matching property for the device’s current configuration value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyConfigurationValue"
        }
      ],
      "role": "symbol",
      "title": "configurationValue",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/configurationvalue"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceClass": {
      "abstract": [
        {
          "text": "The matching property for the device’s class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyDeviceClass"
        }
      ],
      "role": "symbol",
      "title": "deviceClass",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/deviceclass"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceProtocol": {
      "abstract": [
        {
          "text": "The matching property for the device’s protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyDeviceProtocol"
        }
      ],
      "role": "symbol",
      "title": "deviceProtocol",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/deviceprotocol"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber": {
      "abstract": [
        {
          "text": "The matching property for the device’s release number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceReleaseNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyDeviceReleaseNumber"
        }
      ],
      "role": "symbol",
      "title": "deviceReleaseNumber",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/devicereleasenumber"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceSubClass": {
      "abstract": [
        {
          "text": "The matching property for the device’s subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSubClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceSubClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyDeviceSubClass"
        }
      ],
      "role": "symbol",
      "title": "deviceSubClass",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/devicesubclass"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates the structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/init(rawvalue:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceClass": {
      "abstract": [
        {
          "text": "The matching property for the interface’s class ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyInterfaceClass"
        }
      ],
      "role": "symbol",
      "title": "interfaceClass",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/interfaceclass"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceNumber": {
      "abstract": [
        {
          "text": "The matching property for the device’s interface number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyInterfaceNumber"
        }
      ],
      "role": "symbol",
      "title": "interfaceNumber",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/interfacenumber"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceProtocol": {
      "abstract": [
        {
          "text": "The matching property for the interface’s protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyInterfaceProtocol"
        }
      ],
      "role": "symbol",
      "title": "interfaceProtocol",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/interfaceprotocol"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceSubClass": {
      "abstract": [
        {
          "text": "The matching property for the interface’s subclass ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceSubClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceSubClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyInterfaceSubClass"
        }
      ],
      "role": "symbol",
      "title": "interfaceSubClass",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/interfacesubclass"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID": {
      "abstract": [
        {
          "text": "The matching property for the device’s product ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyProductID"
        }
      ],
      "role": "symbol",
      "title": "productID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/productid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray": {
      "abstract": [
        {
          "text": "The matching property on a list of product IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIDArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
        }
      ],
      "role": "symbol",
      "title": "productIDArray",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/productidarray"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask": {
      "abstract": [
        {
          "text": "The matching property on a mask of product IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIDMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyProductIDMask"
        }
      ],
      "role": "symbol",
      "title": "productIDMask",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/productidmask"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed": {
      "abstract": [
        {
          "text": "The matching property for the device’s enumeration speed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeySpeed"
        }
      ],
      "role": "symbol",
      "title": "speed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/speed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID": {
      "abstract": [
        {
          "text": "The matching property for the device’s vendor ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyVendorID"
        }
      ],
      "role": "symbol",
      "title": "vendorID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/vendorid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey": {
      "abstract": [
        {
          "text": "Properties that the USB host device and interface classes share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpropertykey"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IOServicePlane-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
      ],
      "title": "IOServicePlane Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Device-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask"
      ],
      "title": "Device Properties"
    },
    {
      "anchor": "Interface-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceNumber",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceClass",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceSubClass",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceProtocol"
      ],
      "title": "Interface Properties"
    },
    {
      "anchor": "Protocol-and-Class-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceProtocol",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceClass",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceSubClass"
      ],
      "title": "Protocol and Class Properties"
    },
    {
      "anchor": "Initializing-the-Structure",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/init(rawValue:)"
      ],
      "title": "Initializing the Structure"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostMatchingPropertyKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Device-Properties",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask"
              ],
              "title": "Device Properties"
            },
            {
              "anchor": "Interface-Properties",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceNumber",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceClass",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceSubClass",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/interfaceProtocol"
              ],
              "title": "Interface Properties"
            },
            {
              "anchor": "Protocol-and-Class-Properties",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceProtocol",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceClass",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceSubClass"
              ],
              "title": "Protocol and Class Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IOServicePlane-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterfacePropertyKey",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
              ],
              "title": "IOServicePlane Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostMatchingPropertyKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceProtocol/title",
          "value": "IOUSBHostMatchingPropertyKeyInterfaceProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyInterfaceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceSubClass/title",
          "value": "IOUSBHostMatchingPropertyKeyInterfaceSubClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceSubClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyInterfaceSubClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceSubClass/title",
          "value": "IOUSBHostMatchingPropertyKeyDeviceSubClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceSubClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyDeviceSubClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceClass/title",
          "value": "IOUSBHostMatchingPropertyKeyDeviceClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyDeviceClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/title",
          "value": "IOUSBHostInterfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterfacePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1speed/title",
          "value": "IOUSBHostMatchingPropertyKeySpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1speed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeySpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productID/title",
          "value": "IOUSBHostMatchingPropertyKeyProductID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceProtocol/title",
          "value": "IOUSBHostMatchingPropertyKeyDeviceProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyDeviceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDArray/title",
          "value": "IOUSBHostMatchingPropertyKeyProductIDArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1vendorID/title",
          "value": "IOUSBHostMatchingPropertyKeyVendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1vendorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyVendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/title",
          "value": "IOUSBHostMatchingPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1configurationValue/title",
          "value": "IOUSBHostMatchingPropertyKeyConfigurationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1configurationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyConfigurationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceReleaseNumber/title",
          "value": "IOUSBHostMatchingPropertyKeyDeviceReleaseNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceReleaseNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyDeviceReleaseNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/title",
          "value": "IOUSBHostDevicePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceClass/title",
          "value": "IOUSBHostMatchingPropertyKeyInterfaceClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyInterfaceClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceNumber/title",
          "value": "IOUSBHostMatchingPropertyKeyInterfaceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1interfaceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyInterfaceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDMask/title",
          "value": "IOUSBHostMatchingPropertyKeyProductIDMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductIDMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/title",
          "value": "IOUSBHostPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostmatchingpropertykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostmatchingpropertykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
