{
  "abstract": [
    {
      "text": "A completion handler for asynchronous isochronous transfers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@IOUSBHostIsochronousCompletionHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostIsochronousCompletionHandler"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostIsochronousCompletionHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "IOUSBHostIsochronousCompletionHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOReturn",
              "text": "IOReturn"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
              "text": "IOUSBHostIsochronousFrame"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The result code for isochronous transfer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "status"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The frame list of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " passes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frameList"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler": {
      "abstract": [
        {
          "text": "A completion handler for asynchronous isochronous transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronouscompletionhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame": {
      "abstract": [
        {
          "text": "A structure that represents a single frame in an isochronous transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousFrame"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousFrame"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousFrame",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests synchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "role": "symbol",
      "title": "abortWithError:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/abortwitherror:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "role": "symbol",
      "title": "abortWithOption:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/abortwithoption:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)": {
      "abstract": [
        {
          "text": "Enqueues a request on an isochronous endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
          "text": "IOUSBHostIsochronousFrame"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "frameListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostIsochronousCompletionHandler",
          "text": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueueiorequest(with:framelist:framelistcount:firstframenumber:completionhandler:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)": {
      "abstract": [
        {
          "text": "Sends a request on an isochronous endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
          "text": "IOUSBHostIsochronousFrame"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "frameListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
        }
      ],
      "role": "symbol",
      "title": "sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendiorequest(with:framelist:framelistcount:firstframenumber:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime": {
      "abstract": [
        {
          "text": "The absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostTime"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostTime"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostTime",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhosttime"
    },
    "doc://com.externally.resolved.symbol/c:@T@IOReturn": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOReturn",
      "type": "topic",
      "url": "/documentation/iokit/ioreturn"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sending-Isochronous-IO",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)"
      ],
      "title": "Sending Isochronous I/O"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sending-Isochronous-IO",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:"
              ],
              "title": "Sending Isochronous I/O"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#I#*$@S@IOUSBHostIsochronousFrame)",
                    "text": "void (^)(int, struct IOUSBHostIsochronousFrame *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostIsochronousCompletionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:frameList:frameListCount:firstFrameNumber:)/title",
          "value": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:frameList:frameListCount:firstFrameNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)/title",
          "value": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/title",
          "value": "IOUSBHostIsochronousFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/title",
          "value": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/title",
          "value": "IOUSBHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostisochronouscompletionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostisochronouscompletionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
