{
  "abstract": [
    {
      "text": "The class that sends control, bulk, interrupt, and isochronous input/output requests for function drivers, and manages stream capabilities.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOUSBHostPipe",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostPipe"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostPipe"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "IOUSBHostPipe"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The client creates pipe objects using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface/copyPipe(withAddress:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler": {
      "abstract": [
        {
          "text": "The completion handler for asynchronous control, bulk, and interrupt transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcompletionhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDefaultControlCompletionTimeout": {
      "abstract": [
        {
          "text": "The default completion timeout for input/output requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDefaultControlCompletionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDefaultControlCompletionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDefaultControlCompletionTimeout"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDefaultControlCompletionTimeout",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdefaultcontrolcompletiontimeout"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDeviceRequestType(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates the request type field of a device request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDeviceRequestType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@tIOUSBDeviceRequestDirectionValue",
          "text": "tIOUSBDeviceRequestDirectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@tIOUSBDeviceRequestTypeValue",
          "text": "tIOUSBDeviceRequestTypeValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@tIOUSBDeviceRequestRecipientValue",
          "text": "tIOUSBDeviceRequestRecipientValue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDeviceRequestType(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDeviceRequestType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDeviceRequestType(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicerequesttype(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource": {
      "abstract": [
        {
          "text": "This class provides basic functionality for deriving pipe and stream classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSource"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSource"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIOSource",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosource"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors": {
      "abstract": [
        {
          "text": "The descriptors for a single endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSourceDescriptors"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSourceDescriptors"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIOSourceDescriptors",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosourcedescriptors"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface": {
      "abstract": [
        {
          "text": "The class for accessing USB-related services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostInterface"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostInterface"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostInterface",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterface"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface/copyPipe(withAddress:)": {
      "abstract": [
        {
          "text": "Copies a pipe for a specific endpoint address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyPipe"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOUSBHostPipe",
          "text": "IOUSBHostPipe"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface/copyPipe(withAddress:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyPipeWithAddress:error:"
        }
      ],
      "role": "symbol",
      "title": "copyPipe(withAddress:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostinterface/copypipe(withaddress:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler": {
      "abstract": [
        {
          "text": "A completion handler for asynchronous isochronous transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronouscompletionhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame": {
      "abstract": [
        {
          "text": "A structure that represents a single frame in an isochronous transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousFrame"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousFrame"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousFrame",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe": {
      "abstract": [
        {
          "text": "The class that sends control, bulk, interrupt, and isochronous input/output requests for function drivers, and manages stream capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostPipe"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostPipe"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostPipe",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests synchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "role": "symbol",
      "title": "abortWithError:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/abortwitherror:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "role": "symbol",
      "title": "abortWithOption:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/abortwithoption:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/adjust(with:)": {
      "abstract": [
        {
          "text": "Adjusts the behavior of periodic endpoints to consume a different amount of bus bandwidth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjust"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIOSourceDescriptors",
          "text": "IOUSBHostIOSourceDescriptors"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/adjust(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustPipeWithDescriptors:error:"
        }
      ],
      "role": "symbol",
      "title": "adjust(with:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/adjust(with:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/clearStall()": {
      "abstract": [
        {
          "text": "Clears the halt condition of the pipe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearStall"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/clearStall()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearStallWithError:"
        }
      ],
      "role": "symbol",
      "title": "clearStall()",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/clearstall()"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/copyStream(withStreamID:)": {
      "abstract": [
        {
          "text": "Returns the stream for a stream ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withStreamID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOUSBHostStream",
          "text": "IOUSBHostStream"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/copyStream(withStreamID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyStreamWithStreamID:error:"
        }
      ],
      "role": "symbol",
      "title": "copyStream(withStreamID:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/copystream(withstreamid:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/descriptors": {
      "abstract": [
        {
          "text": "A property that retrieves the current endpoint descriptors controlling the endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIOSourceDescriptors",
          "text": "IOUSBHostIOSourceDescriptors"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/descriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptors"
        }
      ],
      "role": "symbol",
      "title": "descriptors",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/descriptors"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/disableStreams()": {
      "abstract": [
        {
          "text": "Disables streams for the pipe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableStreams"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/disableStreams()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableStreamsWithError:"
        }
      ],
      "role": "symbol",
      "title": "disableStreams()",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/disablestreams()"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enableStreams()": {
      "abstract": [
        {
          "text": "Enables streams for the pipe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableStreams"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enableStreams()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableStreamsWithError:"
        }
      ],
      "role": "symbol",
      "title": "enableStreams()",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enablestreams()"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:data:completionTimeout:error:completionHandler:": {
      "abstract": [
        {
          "text": "Enqueues a request on a control endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enqueueControlRequest:data:completionTimeout:error:completionHandler:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:data:completionTimeout:error:completionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueControlRequest:data:completionTimeout:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueControlRequest:data:completionTimeout:error:completionHandler:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueuecontrolrequest:data:completiontimeout:error:completionhandler:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:data:error:completionHandler:": {
      "abstract": [
        {
          "text": "Enqueues a request on a control endpoint with a default completion timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enqueueControlRequest:data:error:completionHandler:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:data:error:completionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueControlRequest:data:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueControlRequest:data:error:completionHandler:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueuecontrolrequest:data:error:completionhandler:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:error:completionHandler:": {
      "abstract": [
        {
          "text": "Enqueues a request on a control endpoint without a data phase and a default completion timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enqueueControlRequest:error:completionHandler:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:error:completionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueControlRequest:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueControlRequest:error:completionHandler:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueuecontrolrequest:error:completionhandler:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:completionTimeout:completionHandler:)": {
      "abstract": [
        {
          "text": "Enqueues an input/output request on the pipe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostCompletionHandler",
          "text": "IOUSBHostCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:completionTimeout:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueIORequestWithData:completionTimeout:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueIORequest(with:completionTimeout:completionHandler:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueueiorequest(with:completiontimeout:completionhandler:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)": {
      "abstract": [
        {
          "text": "Enqueues a request on an isochronous endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
          "text": "IOUSBHostIsochronousFrame"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "frameListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostIsochronousCompletionHandler",
          "text": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueueiorequest(with:framelist:framelistcount:firstframenumber:completionhandler:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transactionList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousTransaction",
          "text": "IOUSBHostIsochronousTransaction"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "transactionListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOUSBHostIsochronousTransferOptions",
          "text": "IOUSBHostIsochronousTransferOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostIsochronousTransactionCompletionHandler",
          "text": "IOUSBHostIsochronousTransactionCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueIORequestWithData:transactionList:transactionListCount:firstFrameNumber:options:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueueiorequest(with:transactionlist:transactionlistcount:firstframenumber:options:completionhandler:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/idleTimeout": {
      "abstract": [
        {
          "text": "A property that retrieves the current idle suspend timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idleTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/idleTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "idleTimeout"
        }
      ],
      "role": "symbol",
      "title": "idleTimeout",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/idletimeout"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/originalDescriptors": {
      "abstract": [
        {
          "text": "A property that retrieves the original endpoint descriptors from the pipe at the point of creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originalDescriptors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIOSourceDescriptors",
          "text": "IOUSBHostIOSourceDescriptors"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/originalDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "originalDescriptors"
        }
      ],
      "role": "symbol",
      "title": "originalDescriptors",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/originaldescriptors"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:data:bytesTransferred:completionTimeout:error:": {
      "abstract": [
        {
          "text": "Sends a request on a control endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sendControlRequest:data:bytesTransferred:completionTimeout:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:data:bytesTransferred:completionTimeout:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendControlRequest:data:bytesTransferred:completionTimeout:error:"
        }
      ],
      "role": "symbol",
      "title": "sendControlRequest:data:bytesTransferred:completionTimeout:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendcontrolrequest:data:bytestransferred:completiontimeout:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:data:bytesTransferred:error:": {
      "abstract": [
        {
          "text": "Sends a request on a control endpoint with a default timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sendControlRequest:data:bytesTransferred:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:data:bytesTransferred:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendControlRequest:data:bytesTransferred:error:"
        }
      ],
      "role": "symbol",
      "title": "sendControlRequest:data:bytesTransferred:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendcontrolrequest:data:bytestransferred:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:error:": {
      "abstract": [
        {
          "text": "Sends a request on a control endpoint without a data phase and a default completion timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sendControlRequest:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendControlRequest:error:"
        }
      ],
      "role": "symbol",
      "title": "sendControlRequest:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendcontrolrequest:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)": {
      "abstract": [
        {
          "text": "Sends a request on an isochronous endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
          "text": "IOUSBHostIsochronousFrame"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "frameListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
        }
      ],
      "role": "symbol",
      "title": "sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendiorequest(with:framelist:framelistcount:firstframenumber:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transactionList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousTransaction",
          "text": "IOUSBHostIsochronousTransaction"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "transactionListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOUSBHostIsochronousTransferOptions",
          "text": "IOUSBHostIsochronousTransferOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:transactionList:transactionListCount:firstFrameNumber:options:error:"
        }
      ],
      "role": "symbol",
      "title": "sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendiorequest(with:transactionlist:transactionlistcount:firstframenumber:options:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequestWithData:bytesTransferred:completionTimeout:error:": {
      "abstract": [
        {
          "text": "Sends an input/output request on the pipe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:bytesTransferred:completionTimeout:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequestWithData:bytesTransferred:completionTimeout:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:bytesTransferred:completionTimeout:error:"
        }
      ],
      "role": "symbol",
      "title": "sendIORequestWithData:bytesTransferred:completionTimeout:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendiorequestwithdata:bytestransferred:completiontimeout:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/setIdleTimeout(_:)": {
      "abstract": [
        {
          "text": "Sets the desired idle suspend timeout for the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIdleTimeout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/setIdleTimeout(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIdleTimeout:error:"
        }
      ],
      "role": "symbol",
      "title": "setIdleTimeout(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/setidletimeout(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream": {
      "abstract": [
        {
          "text": "The class responsible for sending stream data for function drivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostStream"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostStream"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostStream",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhoststream"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime": {
      "abstract": [
        {
          "text": "The absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostTime"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostTime"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostTime",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhosttime"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Function-Drivers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream"
      ],
      "title": "Function Drivers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sending-Bulk-and-Interrupt-IO",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDefaultControlCompletionTimeout",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:completionTimeout:completionHandler:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/clearStall()"
      ],
      "title": "Sending Bulk and Interrupt I/O"
    },
    {
      "anchor": "Sending-Isochronous-IO",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)"
      ],
      "title": "Sending Isochronous I/O"
    },
    {
      "anchor": "Sending-Control-Requests",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDeviceRequestType(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDefaultControlCompletionTimeout",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler"
      ],
      "title": "Sending Control Requests"
    },
    {
      "anchor": "Managing-Periodic-Bandwidth",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/adjust(with:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/descriptors",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/originalDescriptors"
      ],
      "title": "Managing Periodic Bandwidth"
    },
    {
      "anchor": "Enabling-Power-Savings",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/setIdleTimeout(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/idleTimeout"
      ],
      "title": "Enabling Power Savings"
    },
    {
      "anchor": "Managing-Streams",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enableStreams()",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/copyStream(withStreamID:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/disableStreams()"
      ],
      "title": "Managing Streams"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostPipe"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sending-Bulk-and-Interrupt-IO",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDefaultControlCompletionTimeout",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:completionTimeout:completionHandler:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequestWithData:bytesTransferred:completionTimeout:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/clearStall()"
              ],
              "title": "Sending Bulk and Interrupt I/O"
            },
            {
              "anchor": "Sending-Isochronous-IO",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:"
              ],
              "title": "Sending Isochronous I/O"
            },
            {
              "anchor": "Sending-Control-Requests",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDeviceRequestType(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDefaultControlCompletionTimeout",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCompletionHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:data:completionTimeout:error:completionHandler:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:data:error:completionHandler:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueControlRequest:error:completionHandler:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:data:bytesTransferred:completionTimeout:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:data:bytesTransferred:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendControlRequest:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:"
              ],
              "title": "Sending Control Requests"
            },
            {
              "anchor": "Managing-Periodic-Bandwidth",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/adjust(with:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/descriptors",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/originalDescriptors"
              ],
              "title": "Managing Periodic Bandwidth"
            },
            {
              "anchor": "Enabling-Power-Savings",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/setIdleTimeout(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/idleTimeout"
              ],
              "title": "Enabling Power Savings"
            },
            {
              "anchor": "Managing-Streams",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enableStreams()",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/copyStream(withStreamID:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/disableStreams()"
              ],
              "title": "Managing Streams"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Function-Drivers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostInterface",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostStream"
              ],
              "title": "Function Drivers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostPipe"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSource",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)IOUSBHostIOSource",
                    "text": "IOUSBHostIOSource"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1disableStreams()/title",
          "value": "disableStreamsWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1disableStreams()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disableStreamsWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSource/title",
          "value": "IOUSBHostIOSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface/title",
          "value": "IOUSBHostInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/title",
          "value": "IOUSBHostIsochronousFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1adjust(with:)/title",
          "value": "adjustPipeWithDescriptors:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1adjust(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "adjustPipeWithDescriptors:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:frameList:frameListCount:firstFrameNumber:)/title",
          "value": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:frameList:frameListCount:firstFrameNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1clearStall()/title",
          "value": "clearStallWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1clearStall()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearStallWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors/title",
          "value": "IOUSBHostIOSourceDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSourceDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSourceDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/title",
          "value": "IOUSBHostStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostStream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1idleTimeout/title",
          "value": "idleTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1idleTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "idleTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1copyStream(withStreamID:)/title",
          "value": "copyStreamWithStreamID:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1copyStream(withStreamID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyStreamWithStreamID:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)/title",
          "value": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:completionTimeout:completionHandler:)/title",
          "value": "enqueueIORequestWithData:completionTimeout:error:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:completionTimeout:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueIORequestWithData:completionTimeout:error:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)/title",
          "value": "enqueueIORequestWithData:transactionList:transactionListCount:firstFrameNumber:options:error:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueIORequestWithData:transactionList:transactionListCount:firstFrameNumber:options:error:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDeviceRequestType(_:_:_:)/title",
          "value": "IOUSBHostDeviceRequestType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDeviceRequestType(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDeviceRequestType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1descriptors/title",
          "value": "descriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1descriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1setIdleTimeout(_:)/title",
          "value": "setIdleTimeout:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1setIdleTimeout(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIdleTimeout:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface~1copyPipe(withAddress:)/title",
          "value": "copyPipeWithAddress:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostInterface~1copyPipe(withAddress:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyPipeWithAddress:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enableStreams()/title",
          "value": "enableStreamsWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enableStreams()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableStreamsWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe/title",
          "value": "IOUSBHostPipe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPipe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDefaultControlCompletionTimeout/title",
          "value": "IOUSBHostDefaultControlCompletionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDefaultControlCompletionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDefaultControlCompletionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/title",
          "value": "IOUSBHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCompletionHandler/title",
          "value": "IOUSBHostCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/title",
          "value": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1originalDescriptors/title",
          "value": "originalDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1originalDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originalDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)/title",
          "value": "sendIORequestWithData:transactionList:transactionListCount:firstFrameNumber:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:transactionList:transactionListCount:firstFrameNumber:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendIORequestWithData:transactionList:transactionListCount:firstFrameNumber:options:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostpipe"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostpipe"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
