{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1OvercurrentChange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@IOUSBHostCIPortStatusCommandData1Powered@IOUSBHostCIPortStatusCommandData1OvercurrentChange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ChangeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1ChangeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ChangeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1ChangeMask"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1ChangeMask",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1changemask"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ConnectChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1ConnectChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ConnectChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1ConnectChange"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1ConnectChange",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1connectchange"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Connected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Connected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Connected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Connected"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1Connected",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1connected"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1LinkState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1LinkState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1LinkState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1linkstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStateChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1LinkStateChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStateChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1LinkStateChange"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1LinkStateChange",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1linkstatechange"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStatePhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1LinkStatePhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStatePhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1LinkStatePhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1LinkStatePhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1linkstatephase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Overcurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Overcurrent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Overcurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Overcurrent"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1Overcurrent",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1overcurrent"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1OvercurrentChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1OvercurrentChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1OvercurrentChange",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1overcurrentchange"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Powered": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Powered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Powered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Powered"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1Powered",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1powered"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Speed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Speed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Speed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1Speed"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1Speed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1speed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1SpeedPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1SpeedPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1SpeedPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatusCommandData1SpeedPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatusCommandData1SpeedPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatuscommanddata1speedphase"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ChangeMask",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ConnectChange",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Connected",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkState",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStateChange",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStatePhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Overcurrent",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Powered",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Speed",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1SpeedPhase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ChangeMask",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1ConnectChange",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Connected",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStateChange",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1LinkStatePhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Overcurrent",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Powered",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1Speed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatusCommandData1SpeedPhase"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Speed/title",
          "value": "IOUSBHostCIPortStatusCommandData1Speed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Speed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1Speed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1LinkStatePhase/title",
          "value": "IOUSBHostCIPortStatusCommandData1LinkStatePhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1LinkStatePhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1LinkStatePhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Overcurrent/title",
          "value": "IOUSBHostCIPortStatusCommandData1Overcurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Overcurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1Overcurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Powered/title",
          "value": "IOUSBHostCIPortStatusCommandData1Powered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Powered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1Powered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1LinkState/title",
          "value": "IOUSBHostCIPortStatusCommandData1LinkState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1LinkState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1LinkState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1ChangeMask/title",
          "value": "IOUSBHostCIPortStatusCommandData1ChangeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1ChangeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1ChangeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Connected/title",
          "value": "IOUSBHostCIPortStatusCommandData1Connected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1Connected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1Connected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1ConnectChange/title",
          "value": "IOUSBHostCIPortStatusCommandData1ConnectChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1ConnectChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1ConnectChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1LinkStateChange/title",
          "value": "IOUSBHostCIPortStatusCommandData1LinkStateChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1LinkStateChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1LinkStateChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1SpeedPhase/title",
          "value": "IOUSBHostCIPortStatusCommandData1SpeedPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1SpeedPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1SpeedPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1OvercurrentChange/title",
          "value": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatusCommandData1OvercurrentChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatusCommandData1OvercurrentChange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostciportstatuscommanddata1overcurrentchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostciportstatuscommanddata1overcurrentchange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
