{
  "abstract": [
    {
      "text": "A structure that represents a single frame in an isochronous transfer.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@IOUSBHostIsochronousFrame",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostIsochronousFrame"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostIsochronousFrame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.15",
        "message": "Use IOUSBHostIsochronousTransaction instead",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "IOUSBHostIsochronousFrame"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler": {
      "abstract": [
        {
          "text": "A completion handler for asynchronous isochronous transfers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronouscompletionhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame": {
      "abstract": [
        {
          "text": "A structure that represents a single frame in an isochronous transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousFrame"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousFrame"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousFrame",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/completeCount": {
      "abstract": [
        {
          "text": "The number of bytes that the system actually transferred for the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/completeCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completeCount"
        }
      ],
      "role": "symbol",
      "title": "completeCount",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/completecount"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/init()": {
      "abstract": [
        {
          "text": "Creates a new frame structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/init()"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/init(status:requestCount:completeCount:reserved:timeStamp:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "requestCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostTime",
          "text": "IOUSBHostTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/init(status:requestCount:completeCount:reserved:timeStamp:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(status:requestCount:completeCount:reserved:timeStamp:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/init(status:requestcount:completecount:reserved:timestamp:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/requestCount": {
      "abstract": [
        {
          "text": "The number of requested bytes to transfer for the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/requestCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestCount"
        }
      ],
      "role": "symbol",
      "title": "requestCount",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/requestcount"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/reserved"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/status": {
      "abstract": [
        {
          "text": "The completion status for an individual frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/status"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/timeStamp": {
      "abstract": [
        {
          "text": "The observed time for the frame’s completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostTime",
          "text": "IOUSBHostTime"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/timeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStamp"
        }
      ],
      "role": "symbol",
      "title": "timeStamp",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronousframe/timestamp"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests synchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithError:"
        }
      ],
      "role": "symbol",
      "title": "abortWithError:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/abortwitherror:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:": {
      "abstract": [
        {
          "text": "Aborts pending input/output requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "abortWithOption:error:"
        }
      ],
      "role": "symbol",
      "title": "abortWithOption:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/abortwithoption:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)": {
      "abstract": [
        {
          "text": "Enqueues a request on an isochronous endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
          "text": "IOUSBHostIsochronousFrame"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "frameListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostIsochronousCompletionHandler",
          "text": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/enqueueiorequest(with:framelist:framelistcount:firstframenumber:completionhandler:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)": {
      "abstract": [
        {
          "text": "Sends a request on an isochronous endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendIORequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBHostIsochronousFrame",
          "text": "IOUSBHostIsochronousFrame"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "frameListCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "firstFrameNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
        }
      ],
      "role": "symbol",
      "title": "sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpipe/sendiorequest(with:framelist:framelistcount:firstframenumber:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime": {
      "abstract": [
        {
          "text": "The absolute time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostTime"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostTime"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostTime",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhosttime"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sending-Isochronous-IO",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)"
      ],
      "title": "Sending Isochronous I/O"
    }
  ],
  "topicSections": [
    {
      "anchor": "Frame-Structure",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/status",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/requestCount",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/completeCount",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/timeStamp"
      ],
      "title": "Frame Structure"
    },
    {
      "anchor": "Initializing-the-Structure",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/init()"
      ],
      "title": "Initializing the Structure"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/init(status:requestCount:completeCount:reserved:timeStamp:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/reserved",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/completeCount",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/requestCount",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/reserved",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/status",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/timeStamp"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostIsochronousFrame"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Frame-Structure",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/status",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/requestCount",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/completeCount",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/timeStamp"
              ],
              "title": "Frame Structure"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/reserved",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/completeCount",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/requestCount",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/reserved",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/status",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousFrame/timeStamp"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sending-Isochronous-IO",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousCompletionHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostTime",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/sendIORequest(with:frameList:frameListCount:firstFrameNumber:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithOption:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPipe/abortWithError:"
              ],
              "title": "Sending Isochronous I/O"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostIsochronousFrame"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostIsochronousFrame"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:frameList:frameListCount:firstFrameNumber:)/title",
          "value": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1sendIORequest(with:frameList:frameListCount:firstFrameNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendIORequestWithData:frameList:frameListCount:firstFrameNumber:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1requestCount/title",
          "value": "requestCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1requestCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1timeStamp/title",
          "value": "timeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1timeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1completeCount/title",
          "value": "completeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1completeCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1reserved/title",
          "value": "reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/title",
          "value": "IOUSBHostIsochronousFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousFrame~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/title",
          "value": "IOUSBHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)/title",
          "value": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPipe~1enqueueIORequest(with:frameList:frameListCount:firstFrameNumber:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueIORequestWithData:frameList:frameListCount:firstFrameNumber:error:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/title",
          "value": "IOUSBHostIsochronousCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousCompletionHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostisochronousframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostisochronousframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
