{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@IOUSBHostCITransferCompletionMessageControlStatus@IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlDeviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageControlDeviceAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontroldeviceaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontroldeviceaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageControlEndpointAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontrolendpointaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontrolendpointaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageControlStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontrolstatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatusPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlStatusPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatusPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageControlStatusPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageControlStatusPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontrolstatusphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData0TransferLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData0TransferLength"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageData0TransferLength",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagedata0transferlength"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLengthPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData0TransferLengthPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLengthPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData0TransferLengthPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageData0TransferLengthPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagedata0transferlengthphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData1TransferStructure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData1TransferStructure"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageData1TransferStructure",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagedata1transferstructure"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructurePhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData1TransferStructurePhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructurePhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCITransferCompletionMessageData1TransferStructurePhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCITransferCompletionMessageData1TransferStructurePhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcitransfercompletionmessagedata1transferstructurephase"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatus",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatusPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLength",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLengthPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructure",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructurePhase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddress",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlEndpointAddress",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatus",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageControlStatusPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLength",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData0TransferLengthPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructure",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCITransferCompletionMessageData1TransferStructurePhase"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData1TransferStructurePhase/title",
          "value": "IOUSBHostCITransferCompletionMessageData1TransferStructurePhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData1TransferStructurePhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageData1TransferStructurePhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData0TransferLengthPhase/title",
          "value": "IOUSBHostCITransferCompletionMessageData0TransferLengthPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData0TransferLengthPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageData0TransferLengthPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlEndpointAddress/title",
          "value": "IOUSBHostCITransferCompletionMessageControlEndpointAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlEndpointAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase/title",
          "value": "IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlDeviceAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData0TransferLength/title",
          "value": "IOUSBHostCITransferCompletionMessageData0TransferLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData0TransferLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageData0TransferLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData1TransferStructure/title",
          "value": "IOUSBHostCITransferCompletionMessageData1TransferStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageData1TransferStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageData1TransferStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlStatusPhase/title",
          "value": "IOUSBHostCITransferCompletionMessageControlStatusPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlStatusPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlStatusPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlDeviceAddress/title",
          "value": "IOUSBHostCITransferCompletionMessageControlDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase/title",
          "value": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlEndpointAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlStatus/title",
          "value": "IOUSBHostCITransferCompletionMessageControlStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCITransferCompletionMessageControlStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCITransferCompletionMessageControlStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontrolendpointaddressphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcitransfercompletionmessagecontrolendpointaddressphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
