{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@IOUSBHostIsochronousTransactionCompletionHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostIsochronousTransactionCompletionHandler"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostIsochronousTransactionCompletionHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "IOUSBHostIsochronousTransactionCompletionHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOReturn",
              "text": "IOReturn"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransaction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBHostIsochronousTransaction",
              "text": "IOUSBHostIsochronousTransaction"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbell"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbell"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbell",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbell"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceCommandHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceCommandHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostControllerInterfaceCommandHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterfacecommandhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceDoorbellHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceDoorbellHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostControllerInterfaceDoorbellHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterfacedoorbellhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransaction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransaction"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransaction"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransaction",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransaction"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransactionCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransactioncompletionhandler"
    },
    "doc://com.externally.resolved.symbol/c:@T@IOReturn": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOReturn",
      "type": "topic",
      "url": "/documentation/iokit/ioreturn"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostIsochronousTransactionCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#I#*$@S@IOUSBHostIsochronousTransaction)",
                    "text": "void (^)(int, struct IOUSBHostIsochronousTransaction *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostIsochronousTransactionCompletionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceCommandHandler/title",
          "value": "IOUSBHostControllerInterfaceCommandHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceCommandHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceCommandHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceCommandHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceCommandHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatus/title",
          "value": "IOUSBHostCIPortStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionCompletionHandler/title",
          "value": "IOUSBHostIsochronousTransactionCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbell/title",
          "value": "IOUSBHostCIDoorbell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransaction/title",
          "value": "IOUSBHostIsochronousTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceDoorbellHandler/title",
          "value": "IOUSBHostControllerInterfaceDoorbellHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceDoorbellHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceDoorbellHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceDoorbellHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceDoorbellHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostisochronoustransactioncompletionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostisochronoustransactioncompletionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
