{"seeAlsoSections":[{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous","doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost"]]},"variants":[{"paths":["/documentation/iousbhost/iousbhostciendpointstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iousbhost/iousbhostciendpointstate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"metadata":{"externalID":"c:@EA@IOUSBHostCIEndpointState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"role":"symbol","modules":[{"name":"IOUSBHost"}],"platforms":[{"introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"10.15","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"navigatorTitle":[{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"title":"IOUSBHostCIEndpointState","symbolKind":"struct","roleHeading":"Structure"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointState"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState"},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/init(_:)","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/init(rawValue:)"]},{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStatePaused"]},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/rawValue"]}],"kind":"symbol","references":{"doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous":{"title":"Anonymous","role":"collectionGroup","kind":"article","url":"/documentation/iousbhost/3612470-anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous","type":"topic"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus":{"kind":"symbol","title":"IOUSBHostCIMessageStatus","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIMessageStatus","kind":"identifier"}],"navigatorTitle":[{"text":"IOUSBHostCIMessageStatus","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/iousbhost/iousbhostcimessagestatus"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous":{"title":"Anonymous","role":"collectionGroup","kind":"article","url":"/documentation/iousbhost/3612475-anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous","type":"topic"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState","title":"IOUSBHostCIDeviceState","role":"symbol","abstract":[],"url":"/documentation/iousbhost/iousbhostcidevicestate","navigatorTitle":[{"text":"IOUSBHostCIDeviceState","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceState","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted","role":"symbol","kind":"symbol","url":"/documentation/iousbhost/iousbhostciendpointstatehalted","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"abstract":[],"title":"IOUSBHostCIEndpointStateHalted","navigatorTitle":[{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous":{"title":"Anonymous","role":"collectionGroup","kind":"article","url":"/documentation/iousbhost/3612469-anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous","type":"topic"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion","title":"IOUSBHostCIUserClientVersion","role":"symbol","abstract":[],"url":"/documentation/iousbhost/iousbhostciuserclientversion","navigatorTitle":[{"text":"IOUSBHostCIUserClientVersion","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIUserClientVersion","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"role":"symbol","abstract":[{"text":"","type":"text"}],"kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous":{"kind":"article","type":"topic","role":"collectionGroup","url":"/documentation/iousbhost/3612471-anonymous","title":"Anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous","title":"Anonymous","role":"collectionGroup","url":"/documentation/iousbhost/3612473-anonymous","type":"topic","kind":"article","abstract":[]},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous":{"kind":"article","type":"topic","role":"collectionGroup","url":"/documentation/iousbhost/3612466-anonymous","title":"Anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive":{"navigatorTitle":[{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstateactive","abstract":[],"title":"IOUSBHostCIEndpointStateActive","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost":{"abstract":[{"text":"Create host-mode user space drivers for USB devices.","type":"text"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost","url":"/documentation/iousbhost","role":"collection","title":"IOUSBHost","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous":{"title":"Anonymous","role":"collectionGroup","kind":"article","url":"/documentation/iousbhost/3612474-anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous","type":"topic"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed":{"abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed","url":"/documentation/iousbhost/iousbhostcidevicespeed","title":"IOUSBHostCIDeviceSpeed","kind":"symbol","navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SY":{"identifier":"doc://com.externally.resolved.symbol/s:SY","title":"RawRepresentable","role":"symbol","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"url":"/documentation/Swift/RawRepresentable","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/rawValue":{"title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/rawValue","url":"/documentation/iousbhost/iousbhostciendpointstate/rawvalue","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType":{"abstract":[],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType","url":"/documentation/iousbhost/iousbhostciexceptiontype","role":"symbol","title":"IOUSBHostCIExceptionType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIExceptionType"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIExceptionType"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIPortState"}],"url":"/documentation/iousbhost/iousbhostciportstate","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIPortState"}],"role":"symbol","abstract":[],"kind":"symbol","title":"IOUSBHostCIPortState","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous":{"url":"/documentation/iousbhost/3612477-anonymous","abstract":[],"title":"Anonymous","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous","type":"topic","kind":"article","role":"collectionGroup"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType":{"role":"symbol","url":"/documentation/iousbhost/iousbhostcimessagetype","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIMessageType"}],"type":"topic","title":"IOUSBHostCIMessageType","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIMessageType"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"}],"url":"/documentation/iousbhost/iousbhostciendpointstatedestroyed","abstract":[],"title":"IOUSBHostCIEndpointStateDestroyed","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","kind":"typeIdentifier","text":"IOUSBHostCIEndpointState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous":{"kind":"article","type":"topic","role":"collectionGroup","url":"/documentation/iousbhost/3612464-anonymous","title":"Anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions":{"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostIsochronousTransferOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostIsochronousTransferOptions"}],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions","title":"IOUSBHostIsochronousTransferOptions","type":"topic","url":"/documentation/iousbhost/iousbhostisochronoustransferoptions"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous","title":"Anonymous","role":"collectionGroup","url":"/documentation/iousbhost/3612472-anonymous","type":"topic","kind":"article","abstract":[]},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","role":"symbol","title":"Hashable","url":"/documentation/Swift/Hashable","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Equatable","preciseIdentifier":"s:SQ"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","role":"overview","title":"Technologies","kind":"technologies"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/init(_:)":{"title":"init(_:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/init(_:)","type":"topic","url":"/documentation/iousbhost/iousbhostciendpointstate/init(_:)","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState":{"navigatorTitle":[{"text":"IOUSBHostCIControllerState","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState","role":"symbol","url":"/documentation/iousbhost/iousbhostcicontrollerstate","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIControllerState","kind":"identifier"}],"title":"IOUSBHostCIControllerState"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sendable"}],"url":"/documentation/Swift/Sendable","kind":"symbol","title":"Sendable","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous":{"url":"/documentation/iousbhost/3612468-anonymous","role":"collectionGroup","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous","abstract":[],"kind":"article","title":"Anonymous","type":"topic"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState":{"kind":"symbol","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstate","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"role":"symbol","title":"IOUSBHostCIEndpointState"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous":{"kind":"article","type":"topic","role":"collectionGroup","url":"/documentation/iousbhost/3612476-anonymous","title":"Anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous":{"kind":"article","type":"topic","role":"collectionGroup","url":"/documentation/iousbhost/3612467-anonymous","title":"Anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions":{"role":"symbol","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions","kind":"symbol","abstract":[],"url":"/documentation/iousbhost/iousbhostisochronoustransactionoptions","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"IOUSBHostIsochronousTransactionOptions","kind":"identifier"}],"navigatorTitle":[{"text":"IOUSBHostIsochronousTransactionOptions","kind":"identifier"}],"type":"topic","title":"IOUSBHostIsochronousTransactionOptions"},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous":{"url":"/documentation/iousbhost/3612465-anonymous","kind":"article","type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous","title":"Anonymous","role":"collectionGroup","abstract":[]},"doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous":{"kind":"article","type":"topic","role":"collectionGroup","url":"/documentation/iousbhost/3612478-anonymous","title":"Anonymous","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStatePaused":{"title":"IOUSBHostCIEndpointStatePaused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIEndpointStatePaused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","text":"IOUSBHostCIEndpointState","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"IOUSBHostCIEndpointStatePaused","kind":"identifier"}],"abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStatePaused","url":"/documentation/iousbhost/iousbhostciendpointstatepaused","role":"symbol","kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"type":"topic","role":"symbol","title":"Equatable","url":"/documentation/Swift/Equatable","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/init(rawValue:)":{"kind":"symbol","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState/init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/iousbhost/iousbhostciendpointstate/init(rawvalue:)","abstract":[],"role":"symbol","title":"init(rawValue:)"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCILinkState"}],"type":"topic","url":"/documentation/iousbhost/iousbhostcilinkstate","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCILinkState"}],"title":"IOUSBHostCILinkState","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"14.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.15","deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration"},{"path":"/metadata/title","op":"replace","value":"IOUSBHostCIEndpointState"},{"path":"/metadata/symbolKind","op":"replace","value":"enum"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost"]]}},{"path":"/topicSections","op":"replace","value":[{"title":"Constants","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStatePaused"],"anchor":"Constants"}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Enumerations","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions"],"generated":true,"anchor":"Enumerations"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/title","value":"IOUSBHostCIMessageStatus"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/fragments","value":[{"text":"IOUSBHostCIMessageStatus","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostCIMessageStatus"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/title","value":"IOUSBHostCIDeviceState"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/fragments","value":[{"text":"IOUSBHostCIDeviceState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostCIDeviceState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateHalted/title","value":"IOUSBHostCIEndpointStateHalted"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateHalted/fragments","value":[{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/title","value":"IOUSBHostCIUserClientVersion"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIUserClientVersion"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/navigatorTitle","value":[{"text":"IOUSBHostCIUserClientVersion","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateActive/title","value":"IOUSBHostCIEndpointStateActive"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateActive/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateActive"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/title","value":"IOUSBHostCIDeviceSpeed"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/fragments","value":[{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/navigatorTitle","value":[{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/title","value":"IOUSBHostCIExceptionType"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIExceptionType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/navigatorTitle","value":[{"text":"IOUSBHostCIExceptionType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/title","value":"IOUSBHostCIPortState"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/fragments","value":[{"text":"IOUSBHostCIPortState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostCIPortState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/title","value":"IOUSBHostCIMessageType"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIMessageType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/navigatorTitle","value":[{"text":"IOUSBHostCIMessageType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateDestroyed/title","value":"IOUSBHostCIEndpointStateDestroyed"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateDestroyed/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/title","value":"IOUSBHostIsochronousTransferOptions"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/fragments","value":[{"kind":"identifier","text":"IOUSBHostIsochronousTransferOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostIsochronousTransferOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/title","value":"IOUSBHostCIControllerState"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/fragments","value":[{"text":"IOUSBHostCIControllerState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostCIControllerState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/title","value":"IOUSBHostCIEndpointState"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/title","value":"IOUSBHostIsochronousTransactionOptions"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/fragments","value":[{"kind":"identifier","text":"IOUSBHostIsochronousTransactionOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/navigatorTitle","value":[{"kind":"identifier","text":"IOUSBHostIsochronousTransactionOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStatePaused/title","value":"IOUSBHostCIEndpointStatePaused"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStatePaused/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointStatePaused"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/title","value":"IOUSBHostCILinkState"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/fragments","value":[{"text":"IOUSBHostCILinkState","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/navigatorTitle","value":[{"text":"IOUSBHostCILinkState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"minor":{"change":"modified","platform":"Xcode","versions":["16.2","16.3 beta 2"]},"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}