{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOUSBHost Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbell"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDoorbell"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDoorbell",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidoorbell"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceCommandHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceCommandHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostControllerInterfaceCommandHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterfacecommandhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceDoorbellHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostControllerInterfaceDoorbellHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostControllerInterfaceDoorbellHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcontrollerinterfacedoorbellhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransactionCompletionHandler",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransactioncompletionhandler"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Constants",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-constants"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Enumerations",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-enumerations"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Functions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-functions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Structures",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDoorbell",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortStatus",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceCommandHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostControllerInterfaceDoorbellHandler",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionCompletionHandler"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatus/title",
          "value": "IOUSBHostCIPortStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceDoorbellHandler/title",
          "value": "IOUSBHostControllerInterfaceDoorbellHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceDoorbellHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceDoorbellHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceDoorbellHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceDoorbellHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceCommandHandler/title",
          "value": "IOUSBHostControllerInterfaceCommandHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceCommandHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceCommandHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostControllerInterfaceCommandHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostControllerInterfaceCommandHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionCompletionHandler/title",
          "value": "IOUSBHostIsochronousTransactionCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbell/title",
          "value": "IOUSBHostCIDoorbell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDoorbell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDoorbell"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhost-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhost-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
