{
  "abstract": [
    {
      "text": "Obtains the number of an endpoint from an endpoint descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOUSBGetEndpointNumber",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBGetEndpointNumber"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
        "text": "IOUSBEndpointDescriptor"
      },
      {
        "kind": "text",
        "text": ">!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBGetEndpointNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOUSBGetEndpointNumber(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointNumber"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "descriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBEndpointDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
              "text": "IOUSBEndpointDescriptor"
            },
            {
              "kind": "text",
              "text": ">!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An endpoint descriptor to parse.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "descriptor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The representing endpoint number.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method parses an endpoint descriptor to determine its number, excluding the endpoint’s data direction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)": {
      "abstract": [
        {
          "text": "Obtains the direction and number of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointAddress(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointaddress(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)": {
      "abstract": [
        {
          "text": "Obtains the direction of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointDirection"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointDirection(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointdirection(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the interval of an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalEncodedMicroframes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalEncodedMicroframes"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointintervalencodedmicroframes(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the interval of an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalFrames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalFrames"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointIntervalFrames(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointintervalframes(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the interval of an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalMicroframes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalMicroframes"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointIntervalMicroframes(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointintervalmicroframes(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the maximum packet size from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxPacketSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxPacketSize"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointMaxPacketSize(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointmaxpacketsize(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the number of supported streams.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreams"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBSuperSpeedEndpointCompanionDescriptor",
          "text": "IOUSBSuperSpeedEndpointCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreams"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointMaxStreams(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointmaxstreams(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the number of streams that an endpoint supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreamsEncoded"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBSuperSpeedEndpointCompanionDescriptor",
          "text": "IOUSBSuperSpeedEndpointCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreamsEncoded"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointmaxstreamsencoded(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)": {
      "abstract": [
        {
          "text": "Obtains the number of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointNumber"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointNumber"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointNumber(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointnumber(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)": {
      "abstract": [
        {
          "text": "Obtains the type of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointType(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointtype(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next endpoint descriptor for an interface descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBInterfaceDescriptor",
          "text": "IOUSBInterfaceDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextEndpointDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextEndpointDescriptor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextendpointdescriptor(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@IOUSBEndpointDescriptor": {
      "abstract": [
        {
          "text": "The structure for storing an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBEndpointDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBEndpointDescriptor",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBEndpointDescriptor"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Endpoint-Descriptor-Parsing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)"
      ],
      "title": "Endpoint Descriptor Parsing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBGetEndpointNumber"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Endpoint-Descriptor-Parsing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)"
              ],
              "title": "Endpoint Descriptor Parsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBGetEndpointNumber"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBEndpointDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
                    "text": "IOUSBEndpointDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "descriptor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An endpoint descriptor to parse.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "descriptor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The representing endpoint number.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxPacketSize(_:_:)/title",
          "value": "IOUSBGetEndpointMaxPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxPacketSize(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointMaxPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)/title",
          "value": "IOUSBGetEndpointMaxStreamsEncoded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointMaxStreamsEncoded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)/title",
          "value": "IOUSBGetEndpointIntervalEncodedMicroframes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointIntervalEncodedMicroframes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointNumber(_:)/title",
          "value": "IOUSBGetEndpointNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointNumber(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointDirection(_:)/title",
          "value": "IOUSBGetEndpointDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointDirection(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreams(_:_:_:)/title",
          "value": "IOUSBGetEndpointMaxStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreams(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointMaxStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointAddress(_:)/title",
          "value": "IOUSBGetEndpointAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointType(_:)/title",
          "value": "IOUSBGetEndpointType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalMicroframes(_:_:)/title",
          "value": "IOUSBGetEndpointIntervalMicroframes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalMicroframes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointIntervalMicroframes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextEndpointDescriptor(_:_:_:)/title",
          "value": "IOUSBGetNextEndpointDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextEndpointDescriptor(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextEndpointDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalFrames(_:_:)/title",
          "value": "IOUSBGetEndpointIntervalFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalFrames(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointIntervalFrames"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbgetendpointnumber(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbgetendpointnumber(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
