{"seeAlsoSections":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost"]]},"metadata":{"navigatorTitle":[{"text":"IOUSBHostCIEndpointStateDestroyed","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateDestroyed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"title":"IOUSBHostCIEndpointStateDestroyed","externalID":"c:@EA@IOUSBHostCIEndpointState@IOUSBHostCIEndpointStateDestroyed","modules":[{"name":"IOUSBHost"}],"roleHeading":"Global Variable","symbolKind":"var","role":"symbol","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.15","name":"macOS"}]},"sections":[],"identifier":{"url":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState","kind":"typeIdentifier","text":"IOUSBHostCIEndpointState"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/iousbhost/iousbhostciendpointstatedestroyed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iousbhost/iousbhostciendpointstatedestroyed"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive":{"navigatorTitle":[{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstateactive","abstract":[],"title":"IOUSBHostCIEndpointStateActive","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2":{"title":"IOUSBHostCIDeviceSpeedSuperPlusBy2","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedsuperplusby2","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedSuperPlusBy2","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedSuperPlusBy2","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus":{"title":"IOUSBHostCIDeviceSpeedSuperPlus","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedsuperplus","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedSuperPlus","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedSuperPlus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow":{"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostcidevicespeedlow","abstract":[],"title":"IOUSBHostCIDeviceSpeedLow","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted","role":"symbol","kind":"symbol","url":"/documentation/iousbhost/iousbhostciendpointstatehalted","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"abstract":[],"title":"IOUSBHostCIEndpointStateHalted","navigatorTitle":[{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull","title":"IOUSBHostCIDeviceSpeedFull","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedfull","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedFull"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","kind":"typeIdentifier","text":"IOUSBHostCIDeviceSpeed"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedFull"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","role":"overview","title":"Technologies","kind":"technologies"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper":{"title":"IOUSBHostCIDeviceSpeedSuper","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedsuper","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedSuper","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedSuper","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone":{"title":"IOUSBHostCIDeviceSpeedNone","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeednone","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedNone","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedNone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive":{"navigatorTitle":[{"text":"IOUSBHostCIControllerStateActive","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostcicontrollerstateactive","abstract":[],"title":"IOUSBHostCIControllerStateActive","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIControllerStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIControllerState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIControllerState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIControllerStateOff"}],"url":"/documentation/iousbhost/iousbhostcicontrollerstateoff","abstract":[],"title":"IOUSBHostCIControllerStateOff","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIControllerStateOff"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIControllerState","kind":"typeIdentifier","text":"IOUSBHostCIControllerState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused":{"navigatorTitle":[{"text":"IOUSBHostCIDeviceStatePaused","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostcidevicestatepaused","abstract":[],"title":"IOUSBHostCIDeviceStatePaused","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIDeviceStatePaused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIDeviceStateDestroyed"}],"url":"/documentation/iousbhost/iousbhostcidevicestatedestroyed","abstract":[],"title":"IOUSBHostCIDeviceStateDestroyed","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIDeviceStateDestroyed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceState","kind":"typeIdentifier","text":"IOUSBHostCIDeviceState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh":{"title":"IOUSBHostCIDeviceSpeedHigh","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedhigh","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedHigh","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedHigh","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused":{"title":"IOUSBHostCIControllerStatePaused","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcicontrollerstatepaused","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIControllerStatePaused","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIControllerStatePaused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIControllerState","text":"IOUSBHostCIControllerState","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"}],"url":"/documentation/iousbhost/iousbhostciendpointstatedestroyed","abstract":[],"title":"IOUSBHostCIEndpointStateDestroyed","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","kind":"typeIdentifier","text":"IOUSBHostCIEndpointState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost":{"abstract":[{"text":"Create host-mode user space drivers for USB devices.","type":"text"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost","url":"/documentation/iousbhost","role":"collection","title":"IOUSBHost","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState":{"kind":"symbol","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstate","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"role":"symbol","title":"IOUSBHostCIEndpointState"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive":{"title":"IOUSBHostCIDeviceStateActive","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicestateactive","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceStateActive","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceState"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst"},{"name":"macOS","deprecated":false,"introducedAt":"10.15","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"IOUSBHostCIEndpointStateDestroyed","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"IOUSBHostCIEndpointStateDestroyed","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Constants","generated":true,"title":"Constants","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"IOUSBHostCIEndpointStateDestroyed","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateActive/title","value":"IOUSBHostCIEndpointStateActive","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateActive/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateActive"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlusBy2/title","value":"IOUSBHostCIDeviceSpeedSuperPlusBy2","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlusBy2/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedSuperPlusBy2"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlus/title","value":"IOUSBHostCIDeviceSpeedSuperPlus","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlus/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedSuperPlus"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedLow/title","value":"IOUSBHostCIDeviceSpeedLow","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedLow/fragments","value":[{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateHalted/title","value":"IOUSBHostCIEndpointStateHalted","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateHalted/fragments","value":[{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedFull/title","value":"IOUSBHostCIDeviceSpeedFull","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedFull/fragments","value":[{"text":"IOUSBHostCIDeviceSpeedFull","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuper/title","value":"IOUSBHostCIDeviceSpeedSuper","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuper/fragments","value":[{"text":"IOUSBHostCIDeviceSpeedSuper","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedNone/title","value":"IOUSBHostCIDeviceSpeedNone","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedNone/fragments","value":[{"text":"IOUSBHostCIDeviceSpeedNone","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateActive/title","value":"IOUSBHostCIControllerStateActive","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateActive/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIControllerStateActive"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateOff/title","value":"IOUSBHostCIControllerStateOff","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateOff/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIControllerStateOff"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStatePaused/title","value":"IOUSBHostCIDeviceStatePaused","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStatePaused/fragments","value":[{"text":"IOUSBHostCIDeviceStatePaused","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateDestroyed/title","value":"IOUSBHostCIDeviceStateDestroyed","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateDestroyed/fragments","value":[{"text":"IOUSBHostCIDeviceStateDestroyed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedHigh/title","value":"IOUSBHostCIDeviceSpeedHigh","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedHigh/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedHigh"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStatePaused/title","value":"IOUSBHostCIControllerStatePaused","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStatePaused/fragments","value":[{"text":"IOUSBHostCIControllerStatePaused","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateDestroyed/title","value":"IOUSBHostCIEndpointStateDestroyed","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateDestroyed/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/title","value":"IOUSBHostCIEndpointState","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/navigatorTitle","value":[{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateActive/title","value":"IOUSBHostCIDeviceStateActive","op":"replace"},{"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateActive/fragments","value":[{"kind":"identifier","text":"IOUSBHostCIDeviceStateActive"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}