{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddressPhase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@IOUSBHostCICommandMessageControlStatus@IOUSBHostCICommandMessageData0EndpointAddressPhase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageControlStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageControlStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageControlStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagecontrolstatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatusPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageControlStatusPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatusPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageControlStatusPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageControlStatusPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagecontrolstatusphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0DeviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0DeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0DeviceAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0deviceaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0DeviceAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0DeviceAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0DeviceAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0deviceaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0EndpointAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0EndpointAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0EndpointAddress",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0endpointaddress"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddressPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddressPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0EndpointAddressPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0endpointaddressphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0RootPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0RootPort"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0RootPort",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0rootport"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPortPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0RootPortPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPortPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0RootPortPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0RootPortPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0rootportphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0StreamID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0StreamID"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0StreamID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0streamid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamIDPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0StreamIDPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamIDPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCICommandMessageData0StreamIDPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCICommandMessageData0StreamIDPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicommandmessagedata0streamidphase"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatus",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatusPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddressPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddress",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPort",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPortPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamIDPhase"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatus",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageControlStatusPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddress",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0DeviceAddressPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0EndpointAddress",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPort",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0RootPortPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamID",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCICommandMessageData0StreamIDPhase"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageControlStatusPhase/title",
          "value": "IOUSBHostCICommandMessageControlStatusPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageControlStatusPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageControlStatusPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0DeviceAddressPhase/title",
          "value": "IOUSBHostCICommandMessageData0DeviceAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0DeviceAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0DeviceAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0DeviceAddress/title",
          "value": "IOUSBHostCICommandMessageData0DeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0DeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0DeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0RootPortPhase/title",
          "value": "IOUSBHostCICommandMessageData0RootPortPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0RootPortPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0RootPortPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0EndpointAddress/title",
          "value": "IOUSBHostCICommandMessageData0EndpointAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0EndpointAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0EndpointAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0EndpointAddressPhase/title",
          "value": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0EndpointAddressPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0EndpointAddressPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0StreamID/title",
          "value": "IOUSBHostCICommandMessageData0StreamID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0StreamID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0StreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0RootPort/title",
          "value": "IOUSBHostCICommandMessageData0RootPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0RootPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0RootPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageControlStatus/title",
          "value": "IOUSBHostCICommandMessageControlStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageControlStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageControlStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0StreamIDPhase/title",
          "value": "IOUSBHostCICommandMessageData0StreamIDPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCICommandMessageData0StreamIDPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCICommandMessageData0StreamIDPhase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcicommandmessagedata0endpointaddressphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcicommandmessagedata0endpointaddressphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
