{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@IOUSBHostCIExceptionType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostCIExceptionType"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostCIExceptionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "IOUSBHostCIExceptionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612464-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612465-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612466-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612467-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612468-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612469-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612470-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612471-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612472-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612473-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612474-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612475-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612476-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612477-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612478-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIControllerState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicontrollerstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceSpeed"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceSpeed"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceSpeed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicespeed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicestate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIEndpointState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciendpointstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontype/init(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontype/init(rawvalue:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontype/rawvalue"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCapabilitiesInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCapabilitiesInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCapabilitiesInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCapabilitiesInvalid"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeCapabilitiesInvalid",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypecapabilitiesinvalid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandFailure"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeCommandFailure",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypecommandfailure"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandReadCollision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandReadCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandReadCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandReadCollision"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeCommandReadCollision",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypecommandreadcollision"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandTimeout"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeCommandTimeout",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypecommandtimeout"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandWriteFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandWriteFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandWriteFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeCommandWriteFailed"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeCommandWriteFailed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypecommandwritefailed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellOverflow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeDoorbellOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeDoorbellOverflow"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeDoorbellOverflow",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypedoorbelloverflow"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellReadCollision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeDoorbellReadCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellReadCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeDoorbellReadCollision"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeDoorbellReadCollision",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypedoorbellreadcollision"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeFrameUpdateError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeFrameUpdateError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeFrameUpdateError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeFrameUpdateError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeFrameUpdateError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypeframeupdateerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeInterruptInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeInterruptInvalid"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeInterruptInvalid",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypeinterruptinvalid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptOverflow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeInterruptOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeInterruptOverflow"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeInterruptOverflow",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypeinterruptoverflow"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeProtocolError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeProtocolError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeProtocolError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeProtocolError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeProtocolError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypeprotocolerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeTerminated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeTerminated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeTerminated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeTerminated"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeTerminated",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypeterminated"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIExceptionType",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionTypeUnknown",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontypeunknown"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCILinkState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCILinkState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCILinkState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcilinkstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagetype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIUserClientVersion"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIUserClientVersion"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIUserClientVersion",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciuserclientversion"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransactionOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransactionoptions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransferOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransferOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransferOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransferoptions"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/init(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCapabilitiesInvalid",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandFailure",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandReadCollision",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandTimeout",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandWriteFailed",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellOverflow",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellReadCollision",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeFrameUpdateError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptInvalid",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptOverflow",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeProtocolError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeTerminated",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeUnknown"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostCIExceptionType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCapabilitiesInvalid",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandFailure",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandReadCollision",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandTimeout",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeCommandWriteFailed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellOverflow",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeDoorbellReadCollision",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeFrameUpdateError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptInvalid",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeInterruptOverflow",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeProtocolError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeTerminated",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionTypeUnknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostCIExceptionType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/title",
          "value": "IOUSBHostCIDeviceSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/title",
          "value": "IOUSBHostCIPortState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeFrameUpdateError/title",
          "value": "IOUSBHostCIExceptionTypeFrameUpdateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeFrameUpdateError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeFrameUpdateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/title",
          "value": "IOUSBHostCIControllerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeInterruptInvalid/title",
          "value": "IOUSBHostCIExceptionTypeInterruptInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeInterruptInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeInterruptInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeDoorbellOverflow/title",
          "value": "IOUSBHostCIExceptionTypeDoorbellOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeDoorbellOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeDoorbellOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandWriteFailed/title",
          "value": "IOUSBHostCIExceptionTypeCommandWriteFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandWriteFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeCommandWriteFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCapabilitiesInvalid/title",
          "value": "IOUSBHostCIExceptionTypeCapabilitiesInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCapabilitiesInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeCapabilitiesInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeInterruptOverflow/title",
          "value": "IOUSBHostCIExceptionTypeInterruptOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeInterruptOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeInterruptOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/title",
          "value": "IOUSBHostCIEndpointState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/title",
          "value": "IOUSBHostIsochronousTransactionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/title",
          "value": "IOUSBHostCILinkState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCILinkState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCILinkState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandTimeout/title",
          "value": "IOUSBHostCIExceptionTypeCommandTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeCommandTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeUnknown/title",
          "value": "IOUSBHostCIExceptionTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/title",
          "value": "IOUSBHostCIUserClientVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIUserClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIUserClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/title",
          "value": "IOUSBHostCIMessageStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeDoorbellReadCollision/title",
          "value": "IOUSBHostCIExceptionTypeDoorbellReadCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeDoorbellReadCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeDoorbellReadCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandFailure/title",
          "value": "IOUSBHostCIExceptionTypeCommandFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeCommandFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/title",
          "value": "IOUSBHostCIDeviceState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandReadCollision/title",
          "value": "IOUSBHostCIExceptionTypeCommandReadCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeCommandReadCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeCommandReadCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeTerminated/title",
          "value": "IOUSBHostCIExceptionTypeTerminated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeTerminated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeTerminated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeProtocolError/title",
          "value": "IOUSBHostCIExceptionTypeProtocolError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionTypeProtocolError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionTypeProtocolError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/title",
          "value": "IOUSBHostIsochronousTransferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/title",
          "value": "IOUSBHostCIMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/title",
          "value": "IOUSBHostCIExceptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostciexceptiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostciexceptiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
