{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@IOUSBHostCIPortCapabilitiesMessageControlPortNumber@IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlConnectorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlConnectorType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageControlConnectorType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagecontrolconnectortype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagecontrolconnectortypephase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlInternalConnector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlInternalConnector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlInternalConnector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlInternalConnector"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageControlInternalConnector",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagecontrolinternalconnector"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlPortNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlPortNumber"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageControlPortNumber",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagecontrolportnumber"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagecontrolportnumberphase"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPower"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageData0MaxPower",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagedata0maxpower"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportcapabilitiesmessagedata0maxpowerphase"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorType",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlInternalConnector",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumber",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPower"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorType",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlInternalConnector",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumber",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortCapabilitiesMessageData0MaxPower"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageControlPortNumberPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageControlConnectorTypePhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlConnectorType/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageControlConnectorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlConnectorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageControlConnectorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageData0MaxPower/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageData0MaxPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageData0MaxPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlPortNumber/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageControlPortNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlPortNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageControlPortNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlInternalConnector/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageControlInternalConnector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageControlInternalConnector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageControlInternalConnector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase/title",
          "value": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortCapabilitiesMessageData0MaxPowerPhase"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostciportcapabilitiesmessagedata0maxpowerphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostciportcapabilitiesmessagedata0maxpowerphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
