{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@IOUSBHostCIMessageStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBHostCIMessageStatus"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostCIMessageStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "IOUSBHostCIMessageStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612464-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612465-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612466-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612467-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612468-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612469-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612470-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612471-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612472-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612473-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612474-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612475-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612476-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612477-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612478-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIControllerState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicontrollerstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceSpeed"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceSpeed"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceSpeed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicespeed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicestate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIEndpointState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciendpointstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCILinkState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCILinkState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCILinkState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcilinkstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatus/init(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatus/init(rawvalue:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatus/rawvalue"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusBadArgument": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusBadArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusBadArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusBadArgument"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusBadArgument",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusbadargument"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusEndpointStopped": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusEndpointStopped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusEndpointStopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusEndpointStopped"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusEndpointStopped",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusendpointstopped"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatuserror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusMissedServiceError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusMissedServiceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusMissedServiceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusMissedServiceError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusMissedServiceError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusmissedserviceerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNoResources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusNoResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNoResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusNoResources"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusNoResources",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusnoresources"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNotPermitted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusNotPermitted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusNotPermitted",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusnotpermitted"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOffline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusOffline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOffline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusOffline"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusOffline",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusoffline"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOverrunError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusOverrunError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOverrunError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusOverrunError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusOverrunError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusoverrunerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusProtocolError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusProtocolError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusProtocolError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusProtocolError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusProtocolError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusprotocolerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusReserved"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusReserved",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusreserved"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusStallError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusStallError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusStallError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusStallError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusStallError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatusstallerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusSuccess"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusSuccess",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatussuccess"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusTimeout"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusTimeout",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatustimeout"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTransactionError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusTransactionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@IOUSBHostCIMessageStatus",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTransactionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatusTransactionError"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatusTransactionError",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatustransactionerror"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagetype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIUserClientVersion"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIUserClientVersion"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIUserClientVersion",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciuserclientversion"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransactionOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransactionoptions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransferOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransferOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransferOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransferoptions"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/init(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusBadArgument",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusEndpointStopped",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusMissedServiceError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNoResources",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNotPermitted",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOffline",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOverrunError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusProtocolError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusReserved",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusStallError",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusSuccess",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTimeout",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTransactionError"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostCIMessageStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusBadArgument",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusEndpointStopped",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusMissedServiceError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNoResources",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusNotPermitted",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOffline",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusOverrunError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusProtocolError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusReserved",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusStallError",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusSuccess",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTimeout",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatusTransactionError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostCIMessageStatus"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/title",
          "value": "IOUSBHostCIExceptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusNotPermitted/title",
          "value": "IOUSBHostCIMessageStatusNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusNotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/title",
          "value": "IOUSBHostIsochronousTransactionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusNoResources/title",
          "value": "IOUSBHostCIMessageStatusNoResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusNoResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusNoResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/title",
          "value": "IOUSBHostCIDeviceSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusTimeout/title",
          "value": "IOUSBHostCIMessageStatusTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/title",
          "value": "IOUSBHostCIMessageStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusTransactionError/title",
          "value": "IOUSBHostCIMessageStatusTransactionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusTransactionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusOverrunError/title",
          "value": "IOUSBHostCIMessageStatusOverrunError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusOverrunError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusOverrunError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/title",
          "value": "IOUSBHostCILinkState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCILinkState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCILinkState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/title",
          "value": "IOUSBHostCIUserClientVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIUserClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIUserClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusStallError/title",
          "value": "IOUSBHostCIMessageStatusStallError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusStallError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusStallError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusError/title",
          "value": "IOUSBHostCIMessageStatusError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusReserved/title",
          "value": "IOUSBHostCIMessageStatusReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusOffline/title",
          "value": "IOUSBHostCIMessageStatusOffline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusOffline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusOffline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/title",
          "value": "IOUSBHostCIDeviceState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/title",
          "value": "IOUSBHostCIPortState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/title",
          "value": "IOUSBHostIsochronousTransferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/title",
          "value": "IOUSBHostCIControllerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusBadArgument/title",
          "value": "IOUSBHostCIMessageStatusBadArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusBadArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusBadArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusProtocolError/title",
          "value": "IOUSBHostCIMessageStatusProtocolError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusProtocolError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusProtocolError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusMissedServiceError/title",
          "value": "IOUSBHostCIMessageStatusMissedServiceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusMissedServiceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusMissedServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusSuccess/title",
          "value": "IOUSBHostCIMessageStatusSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusEndpointStopped/title",
          "value": "IOUSBHostCIMessageStatusEndpointStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatusEndpointStopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatusEndpointStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/title",
          "value": "IOUSBHostCIMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/title",
          "value": "IOUSBHostCIEndpointState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcimessagestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostcimessagestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
