{
  "abstract": [
    {
      "text": "Obtains the next associated descriptor in a configuration descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOUSBGetNextAssociatedDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBGetNextAssociatedDescriptor"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
        "text": "IOUSBConfigurationDescriptor"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
        "text": "IOUSBDescriptorHeader"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
        "text": "IOUSBDescriptorHeader"
      },
      {
        "kind": "text",
        "text": ">!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
        "text": "IOUSBDescriptorHeader"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBGetNextAssociatedDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOUSBGetNextAssociatedDescriptor(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBGetNextAssociatedDescriptor"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "configurationDescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBConfigurationDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
              "text": "IOUSBConfigurationDescriptor"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parentDescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
              "text": "IOUSBDescriptorHeader"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "currentDescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
              "text": "IOUSBDescriptorHeader"
            },
            {
              "kind": "text",
              "text": ">!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
              "text": "IOUSBDescriptorHeader"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A configuration descriptor that contains the descriptors to iterate through.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "configurationDescriptor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A descriptor pointer within the bounds of ",
                  "type": "text"
                },
                {
                  "code": "configurationDescriptor",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "parentDescriptor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A descriptor pointer within the bounds of ",
                  "type": "text"
                },
                {
                  "code": "configurationDescriptor",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "currentDescriptor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A descriptor pointer, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no matching descriptor returns.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", but returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if it finds another descriptor with a ",
              "type": "text"
            },
            {
              "code": "bDescriptorType",
              "type": "codeVoice"
            },
            {
              "text": " field that matches the value for ",
              "type": "text"
            },
            {
              "code": "parentDescripto",
              "type": "codeVoice"
            },
            {
              "text": "r’s ",
              "type": "text"
            },
            {
              "code": "bDescriptorType",
              "type": "codeVoice"
            },
            {
              "text": ". Use ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for ",
              "type": "text"
            },
            {
              "code": "currentDescriptor",
              "type": "codeVoice"
            },
            {
              "text": " to return the first descriptor after ",
              "type": "text"
            },
            {
              "code": "parentDescriptor",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the maximum bus current that a configuration descriptor requires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetConfigurationMaxPowerMilliAmps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetConfigurationMaxPowerMilliAmps"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetconfigurationmaxpowermilliamps(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next associated descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextAssociatedDescriptor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextassociateddescriptor(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next associated descriptor in a configuration descriptor and matches the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptorWithType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptorWithType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextassociateddescriptorwithtype(_:_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextdescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next descriptor in a configuration descriptor that matches the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptorWithType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptorWithType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextDescriptorWithType(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextdescriptorwithtype(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next interface association descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceAssociationDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBInterfaceAssociationDescriptor",
          "text": "IOUSBInterfaceAssociationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceAssociationDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextinterfaceassociationdescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next interface descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBInterfaceDescriptor",
          "text": "IOUSBInterfaceDescriptor"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextInterfaceDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextinterfacedescriptor(_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@IOUSBConfigurationDescriptor": {
      "abstract": [
        {
          "text": "The structure for storing a USB configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBConfigurationDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBConfigurationDescriptor",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBConfigurationDescriptor"
    },
    "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader": {
      "abstract": [
        {
          "text": "The base descriptor header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBDescriptorHeader",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBDescriptorHeader"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuration-Descriptor-Parsing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)"
      ],
      "title": "Configuration Descriptor Parsing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBGetNextAssociatedDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextAssociatedDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuration-Descriptor-Parsing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)"
              ],
              "title": "Configuration Descriptor Parsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
                    "text": "IOUSBDescriptorHeader"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBGetNextAssociatedDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBConfigurationDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
                    "text": "IOUSBConfigurationDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "configurationDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
                    "text": "IOUSBDescriptorHeader"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "parentDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDescriptorHeader",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
                    "text": "IOUSBDescriptorHeader"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "currentDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A configuration descriptor that contains the descriptors to iterate through.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "configurationDescriptor"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A descriptor pointer within the bounds of ",
                        "type": "text"
                      },
                      {
                        "code": "configurationDescriptor",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "parentDescriptor"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A descriptor pointer within the bounds of ",
                        "type": "text"
                      },
                      {
                        "code": "configurationDescriptor",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "currentDescriptor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A descriptor pointer, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if no matching descriptor returns.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptor(_:_:)/title",
          "value": "IOUSBGetNextDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptorWithType(_:_:_:)/title",
          "value": "IOUSBGetNextDescriptorWithType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptorWithType(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextDescriptorWithType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)/title",
          "value": "IOUSBGetConfigurationMaxPowerMilliAmps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetConfigurationMaxPowerMilliAmps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptor(_:_:_:)/title",
          "value": "IOUSBGetNextAssociatedDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptor(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextAssociatedDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)/title",
          "value": "IOUSBGetNextAssociatedDescriptorWithType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextAssociatedDescriptorWithType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceAssociationDescriptor(_:_:)/title",
          "value": "IOUSBGetNextInterfaceAssociationDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceAssociationDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextInterfaceAssociationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceDescriptor(_:_:)/title",
          "value": "IOUSBGetNextInterfaceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextInterfaceDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbgetnextassociateddescriptor(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbgetnextassociateddescriptor(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
