{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOUSBHost Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612464-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612465-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612466-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612467-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612468-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612469-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612470-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612471-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612472-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612473-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612474-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612475-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612476-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612477-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612478-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3612479-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3857646-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3857646-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3857646-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3857647-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3857647-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3857647-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/3857648-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/3857648-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iousbhost/3857648-anonymous"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIControllerState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIControllerState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcicontrollerstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceSpeed"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceSpeed"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceSpeed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicespeed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIDeviceState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIDeviceState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcidevicestate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIEndpointState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIEndpointState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciendpointstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIExceptionType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIExceptionType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciexceptiontype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCILinkState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCILinkState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCILinkState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcilinkstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageStatus"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageStatus",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagestatus"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageType"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIMessageType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIMessageType",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostcimessagetype"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortState"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIPortState"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIPortState",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciportstate"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostCIUserClientVersion"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostCIUserClientVersion"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostCIUserClientVersion",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostciuserclientversion"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransactionOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransactionOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransactionoptions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransferOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIsochronousTransferOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIsochronousTransferOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostisochronoustransferoptions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Constants",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-constants"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Data Types",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-data-types"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Functions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-functions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOUSBHost Structures",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhost-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612464-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612465-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612466-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612467-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612468-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612469-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612470-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612471-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612472-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612473-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612474-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612475-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612476-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612477-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612478-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3612479-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3857646-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3857647-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/3857648-anonymous",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIExceptionType",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCILinkState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageType",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIPortState",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIUserClientVersion",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransactionOptions",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIsochronousTransferOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-structures",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-constants",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-functions",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/iousbhost-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/title",
          "value": "IOUSBHostCIExceptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIExceptionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIExceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/title",
          "value": "IOUSBHostCIDeviceSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/title",
          "value": "IOUSBHostCIMessageStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/title",
          "value": "IOUSBHostIsochronousTransactionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransactionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransactionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/title",
          "value": "IOUSBHostCIDeviceState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIDeviceState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/title",
          "value": "IOUSBHostCIUserClientVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIUserClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIUserClientVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIUserClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/title",
          "value": "IOUSBHostCIPortState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIPortState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIPortState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/title",
          "value": "IOUSBHostIsochronousTransferOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIsochronousTransferOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIsochronousTransferOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/title",
          "value": "IOUSBHostCIMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/title",
          "value": "IOUSBHostCIEndpointState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIEndpointState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/title",
          "value": "IOUSBHostCIControllerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCIControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/title",
          "value": "IOUSBHostCILinkState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCILinkState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCILinkState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostCILinkState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhost-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhost-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
