{
  "abstract": [
    {
      "text": "Obtains the first SuperSpeed capability descriptor in a BOS descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOUSBGetSuperSpeedDeviceCapabilityDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
        "text": "IOUSBBOSDescriptor"
      },
      {
        "kind": "text",
        "text": ">!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
        "text": "IOUSBDeviceCapabilitySuperSpeedUSB"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "bosDescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBBOSDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
              "text": "IOUSBBOSDescriptor"
            },
            {
              "kind": "text",
              "text": ">!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
              "text": "IOUSBDeviceCapabilitySuperSpeedUSB"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A BOS descriptor that contains the descriptors to iterate through.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bosDescriptor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A SuperSpeed capability pointer, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no matching descriptor returns.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to find the first SuperSpeed capability descriptor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first billboard capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetBillboardDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityBillboard",
          "text": "IOUSBDeviceCapabilityBillboard"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetBillboardDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetBillboardDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetbillboarddescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first container ID capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetContainerIDDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityContainerID",
          "text": "IOUSBDeviceCapabilityContainerID"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetContainerIDDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetContainerIDDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetcontaineriddescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next device capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextCapabilityDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextcapabilitydescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next descriptor matching a specific type within a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptorWithType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptorWithType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextcapabilitydescriptorwithtype(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first SuperSpeed capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
          "text": "IOUSBDeviceCapabilitySuperSpeedUSB"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetsuperspeeddevicecapabilitydescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first USB 2.0 extension capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityUSB2Extension",
          "text": "IOUSBDeviceCapabilityUSB2Extension"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetusb20extensiondevicecapabilitydescriptor(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@IOUSBBOSDescriptor": {
      "abstract": [
        {
          "text": "The structure for storing a binary object store (BOS) descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBBOSDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBBOSDescriptor",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBBOSDescriptor"
    },
    "doc://com.externally.resolved.symbol/c:@S@IOUSBDeviceCapabilitySuperSpeedUSB": {
      "abstract": [
        {
          "text": "The structure for the super-speed USB device capability.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBDeviceCapabilitySuperSpeedUSB"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBDeviceCapabilitySuperSpeedUSB",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBDeviceCapabilitySuperSpeedUSB"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "BOS-Descriptor-Parsing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)"
      ],
      "title": "BOS Descriptor Parsing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "BOS-Descriptor-Parsing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)"
              ],
              "title": "BOS Descriptor Parsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
                    "text": "IOUSBDeviceCapabilitySuperSpeedUSB"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBBOSDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
                    "text": "IOUSBBOSDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bosDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A BOS descriptor that contains the descriptors to iterate through.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bosDescriptor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A SuperSpeed capability pointer, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if no matching descriptor returns.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)/title",
          "value": "IOUSBGetNextCapabilityDescriptorWithType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextCapabilityDescriptorWithType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptor(_:_:)/title",
          "value": "IOUSBGetNextCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)/title",
          "value": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetBillboardDescriptor(_:)/title",
          "value": "IOUSBGetBillboardDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetBillboardDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetBillboardDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)/title",
          "value": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetContainerIDDescriptor(_:)/title",
          "value": "IOUSBGetContainerIDDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetContainerIDDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetContainerIDDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbgetsuperspeeddevicecapabilitydescriptor(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbgetsuperspeeddevicecapabilitydescriptor(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
