{"sections":[],"identifier":{"url":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iousbhost/iousbhostcidevicespeedlow"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iousbhost/iousbhostcidevicespeedlow"]}],"seeAlsoSections":[{"title":"Constants","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted"],"anchor":"Constants","generated":true}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedLow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOUSBHostCIDeviceSpeed","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed"}],"externalID":"c:@EA@IOUSBHostCIDeviceSpeed@IOUSBHostCIDeviceSpeedLow","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0"},{"deprecated":false,"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.15"}],"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedLow"}],"symbolKind":"var","title":"IOUSBHostCIDeviceSpeedLow","modules":[{"name":"IOUSBHost"}],"roleHeading":"Global Variable"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone":{"title":"IOUSBHostCIDeviceSpeedNone","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeednone","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedNone","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedNone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow":{"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostcidevicespeedlow","abstract":[],"title":"IOUSBHostCIDeviceSpeedLow","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedLow","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive":{"title":"IOUSBHostCIDeviceStateActive","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicestateactive","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceStateActive","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceState"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost":{"abstract":[{"text":"Create host-mode user space drivers for USB devices.","type":"text"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost","url":"/documentation/iousbhost","role":"collection","title":"IOUSBHost","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"}],"url":"/documentation/iousbhost/iousbhostciendpointstatedestroyed","abstract":[],"title":"IOUSBHostCIEndpointStateDestroyed","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointStateDestroyed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","kind":"typeIdentifier","text":"IOUSBHostCIEndpointState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh":{"title":"IOUSBHostCIDeviceSpeedHigh","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedhigh","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedHigh","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedHigh","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus":{"title":"IOUSBHostCIDeviceSpeedSuperPlus","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedsuperplus","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedSuperPlus","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedSuperPlus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused":{"title":"IOUSBHostCIControllerStatePaused","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcicontrollerstatepaused","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIControllerStatePaused","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIControllerStatePaused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIControllerState","text":"IOUSBHostCIControllerState","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed":{"abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed","url":"/documentation/iousbhost/iousbhostcidevicespeed","title":"IOUSBHostCIDeviceSpeed","kind":"symbol","navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted","role":"symbol","kind":"symbol","url":"/documentation/iousbhost/iousbhostciendpointstatehalted","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"abstract":[],"title":"IOUSBHostCIEndpointStateHalted","navigatorTitle":[{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2":{"title":"IOUSBHostCIDeviceSpeedSuperPlusBy2","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedsuperplusby2","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedSuperPlusBy2","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedSuperPlusBy2","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive":{"navigatorTitle":[{"text":"IOUSBHostCIControllerStateActive","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostcicontrollerstateactive","abstract":[],"title":"IOUSBHostCIControllerStateActive","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIControllerStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIControllerState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIControllerState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull","title":"IOUSBHostCIDeviceSpeedFull","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedfull","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedFull"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed","kind":"typeIdentifier","text":"IOUSBHostCIDeviceSpeed"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedFull"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIDeviceStateDestroyed"}],"url":"/documentation/iousbhost/iousbhostcidevicestatedestroyed","abstract":[],"title":"IOUSBHostCIDeviceStateDestroyed","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIDeviceStateDestroyed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIDeviceState","kind":"typeIdentifier","text":"IOUSBHostCIDeviceState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","role":"overview","title":"Technologies","kind":"technologies"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff":{"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIControllerStateOff"}],"url":"/documentation/iousbhost/iousbhostcicontrollerstateoff","abstract":[],"title":"IOUSBHostCIControllerStateOff","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIControllerStateOff"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIControllerState","kind":"typeIdentifier","text":"IOUSBHostCIControllerState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused":{"navigatorTitle":[{"text":"IOUSBHostCIDeviceStatePaused","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostcidevicestatepaused","abstract":[],"title":"IOUSBHostCIDeviceStatePaused","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIDeviceStatePaused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive":{"navigatorTitle":[{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstateactive","abstract":[],"title":"IOUSBHostCIEndpointStateActive","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper":{"title":"IOUSBHostCIDeviceSpeedSuper","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcidevicespeedsuper","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIDeviceSpeedSuper","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeedSuper","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIDeviceSpeed","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIDeviceSpeed"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"14.0","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.15","beta":false,"deprecated":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"IOUSBHostCIDeviceSpeedLow"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedLow"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeed"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Constants","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStateOff","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIControllerStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedFull","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedHigh","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedNone","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuper","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlus","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceSpeedSuperPlusBy2","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIDeviceStatePaused","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateActive","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateDestroyed","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateHalted"],"generated":true,"anchor":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedLow"}]}],"kind":"declarations"}},{"value":"IOUSBHostCIDeviceSpeedNone","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedNone/title","op":"replace"},{"value":[{"text":"IOUSBHostCIDeviceSpeedNone","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedNone/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeedLow","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedLow/title","op":"replace"},{"value":[{"text":"IOUSBHostCIDeviceSpeedLow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedLow/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceStateActive","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateActive/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceStateActive"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateActive/fragments","op":"replace"},{"value":"IOUSBHostCIEndpointStateDestroyed","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateDestroyed/title","op":"replace"},{"value":[{"text":"IOUSBHostCIEndpointStateDestroyed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateDestroyed/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeedHigh","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedHigh/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedHigh"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedHigh/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeedSuperPlus","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlus/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedSuperPlus"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlus/fragments","op":"replace"},{"value":"IOUSBHostCIControllerStatePaused","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStatePaused/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIControllerStatePaused"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStatePaused/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeed","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeed"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/fragments","op":"replace"},{"value":[{"text":"IOUSBHostCIDeviceSpeed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeed/navigatorTitle","op":"replace"},{"value":"IOUSBHostCIEndpointStateHalted","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateHalted/title","op":"replace"},{"value":[{"text":"IOUSBHostCIEndpointStateHalted","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateHalted/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeedSuperPlusBy2","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlusBy2/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedSuperPlusBy2"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuperPlusBy2/fragments","op":"replace"},{"value":"IOUSBHostCIControllerStateActive","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateActive/title","op":"replace"},{"value":[{"text":"IOUSBHostCIControllerStateActive","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateActive/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeedFull","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedFull/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceSpeedFull"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedFull/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceStateDestroyed","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateDestroyed/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIDeviceStateDestroyed"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStateDestroyed/fragments","op":"replace"},{"value":"IOUSBHostCIControllerStateOff","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateOff/title","op":"replace"},{"value":[{"kind":"identifier","text":"IOUSBHostCIControllerStateOff"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIControllerStateOff/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceStatePaused","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStatePaused/title","op":"replace"},{"value":[{"text":"IOUSBHostCIDeviceStatePaused","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceStatePaused/fragments","op":"replace"},{"value":"IOUSBHostCIEndpointStateActive","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateActive/title","op":"replace"},{"value":[{"text":"IOUSBHostCIEndpointStateActive","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateActive/fragments","op":"replace"},{"value":"IOUSBHostCIDeviceSpeedSuper","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuper/title","op":"replace"},{"value":[{"text":"IOUSBHostCIDeviceSpeedSuper","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIDeviceSpeedSuper/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}