{
  "abstract": [
    {
      "text": "Extract information from various USB descriptors using helper methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/parsing-usb-descriptors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Parsing USB Descriptors"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first billboard capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetBillboardDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityBillboard",
          "text": "IOUSBDeviceCapabilityBillboard"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetBillboardDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetBillboardDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetbillboarddescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the maximum bus current that a configuration descriptor requires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetConfigurationMaxPowerMilliAmps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetConfigurationMaxPowerMilliAmps"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetconfigurationmaxpowermilliamps(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first container ID capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetContainerIDDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityContainerID",
          "text": "IOUSBDeviceCapabilityContainerID"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetContainerIDDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetContainerIDDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetcontaineriddescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)": {
      "abstract": [
        {
          "text": "Obtains the direction and number of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointAddress"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointAddress(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointaddress(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)": {
      "abstract": [
        {
          "text": "Obtains the direction of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointDirection"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointDirection(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointdirection(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the interval of an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalEncodedMicroframes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalEncodedMicroframes"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointintervalencodedmicroframes(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the interval of an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalFrames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalFrames"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointIntervalFrames(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointintervalframes(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the interval of an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalMicroframes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointIntervalMicroframes"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointIntervalMicroframes(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointintervalmicroframes(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the maximum packet size from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxPacketSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxPacketSize"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointMaxPacketSize(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointmaxpacketsize(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the number of supported streams.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreams"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBSuperSpeedEndpointCompanionDescriptor",
          "text": "IOUSBSuperSpeedEndpointCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreams"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointMaxStreams(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointmaxstreams(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the number of streams that an endpoint supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreamsEncoded"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBSuperSpeedEndpointCompanionDescriptor",
          "text": "IOUSBSuperSpeedEndpointCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointMaxStreamsEncoded"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointmaxstreamsencoded(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)": {
      "abstract": [
        {
          "text": "Obtains the number of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointNumber"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointNumber"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointNumber(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointnumber(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)": {
      "abstract": [
        {
          "text": "Obtains the type of an endpoint from an endpoint descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetEndpointType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetEndpointType(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetendpointtype(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next associated descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextAssociatedDescriptor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextassociateddescriptor(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next associated descriptor in a configuration descriptor and matches the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptorWithType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextAssociatedDescriptorWithType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextassociateddescriptorwithtype(_:_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next device capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextCapabilityDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextcapabilitydescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next descriptor matching a specific type within a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptorWithType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityDescriptorHeader",
          "text": "IOUSBDeviceCapabilityDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextCapabilityDescriptorWithType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextcapabilitydescriptorwithtype(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextdescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next descriptor in a configuration descriptor that matches the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptorWithType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextDescriptorWithType"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextDescriptorWithType(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextdescriptorwithtype(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next endpoint descriptor for an interface descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBInterfaceDescriptor",
          "text": "IOUSBInterfaceDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextEndpointDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextEndpointDescriptor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextendpointdescriptor(_:_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next interface association descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceAssociationDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBInterfaceAssociationDescriptor",
          "text": "IOUSBInterfaceAssociationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceAssociationDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextinterfaceassociationdescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)": {
      "abstract": [
        {
          "text": "Obtains the next interface descriptor in a configuration descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBConfigurationDescriptor",
          "text": "IOUSBConfigurationDescriptor"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBInterfaceDescriptor",
          "text": "IOUSBInterfaceDescriptor"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetNextInterfaceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetNextInterfaceDescriptor(_:_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetnextinterfacedescriptor(_:_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first SuperSpeed capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilitySuperSpeedUSB",
          "text": "IOUSBDeviceCapabilitySuperSpeedUSB"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetsuperspeeddevicecapabilitydescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)": {
      "abstract": [
        {
          "text": "Obtains the first USB 2.0 extension capability descriptor in a BOS descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBBOSDescriptor",
          "text": "IOUSBBOSDescriptor"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDeviceCapabilityUSB2Extension",
          "text": "IOUSBDeviceCapabilityUSB2Extension"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
        }
      ],
      "role": "symbol",
      "title": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbgetusb20extensiondevicecapabilitydescriptor(_:)"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject": {
      "abstract": [
        {
          "text": "This class provides basic functionality for sending device requests and retrieving descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostObject"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostObject"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostObject",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:error:": {
      "abstract": [
        {
          "text": "Retrieves a descriptor with default arguments from the cache or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:error:"
        }
      ],
      "role": "symbol",
      "title": "descriptorWithType:length:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:error:": {
      "abstract": [
        {
          "text": "Retrieves a string descriptor from the cache or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:error:"
        }
      ],
      "role": "symbol",
      "title": "descriptorWithType:length:index:languageID:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:index:languageid:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:requestType:requestRecipient:error:": {
      "abstract": [
        {
          "text": "Retrieves a descriptor from the cache or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:requestType:requestRecipient:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
        }
      ],
      "role": "symbol",
      "title": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:index:languageid:requesttype:requestrecipient:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:error:": {
      "abstract": [
        {
          "text": "Retrieves an English-language string from a string descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringWithIndex:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringWithIndex:error:"
        }
      ],
      "role": "symbol",
      "title": "stringWithIndex:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/stringwithindex:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:languageID:error:": {
      "abstract": [
        {
          "text": "Retrieves a string from a string descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringWithIndex:languageID:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:languageID:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringWithIndex:languageID:error:"
        }
      ],
      "role": "symbol",
      "title": "stringWithIndex:languageID:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/stringwithindex:languageid:error:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Base-Class-Descriptors",
      "generated": true,
      "identifiers": [],
      "title": "Retrieving Base Class Descriptors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration-Descriptor-Parsing",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)"
      ],
      "title": "Configuration Descriptor Parsing"
    },
    {
      "anchor": "BOS-Descriptor-Parsing",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)"
      ],
      "title": "BOS Descriptor Parsing"
    },
    {
      "anchor": "Endpoint-Descriptor-Parsing",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)"
      ],
      "title": "Endpoint Descriptor Parsing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration-Descriptor-Parsing",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextDescriptorWithType(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptor(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceAssociationDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextInterfaceDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)"
              ],
              "title": "Configuration Descriptor Parsing"
            },
            {
              "anchor": "BOS-Descriptor-Parsing",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextCapabilityDescriptor(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetContainerIDDescriptor(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetBillboardDescriptor(_:)"
              ],
              "title": "BOS Descriptor Parsing"
            },
            {
              "anchor": "Endpoint-Descriptor-Parsing",
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetNextEndpointDescriptor(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointDirection(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointAddress(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointNumber(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointType(_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxPacketSize(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalMicroframes(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointIntervalFrames(_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBGetEndpointMaxStreams(_:_:_:)"
              ],
              "title": "Endpoint Descriptor Parsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-Base-Class-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:requestType:requestRecipient:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:languageID:error:",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:error:"
              ],
              "title": "Retrieving Base Class Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetContainerIDDescriptor(_:)/title",
          "value": "IOUSBGetContainerIDDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetContainerIDDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetContainerIDDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointType(_:)/title",
          "value": "IOUSBGetEndpointType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)/title",
          "value": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetSuperSpeedDeviceCapabilityDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetSuperSpeedDeviceCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)/title",
          "value": "IOUSBGetNextCapabilityDescriptorWithType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptorWithType(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextCapabilityDescriptorWithType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointAddress(_:)/title",
          "value": "IOUSBGetEndpointAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)/title",
          "value": "IOUSBGetNextAssociatedDescriptorWithType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptorWithType(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextAssociatedDescriptorWithType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)/title",
          "value": "IOUSBGetConfigurationMaxPowerMilliAmps"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetConfigurationMaxPowerMilliAmps(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetConfigurationMaxPowerMilliAmps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)/title",
          "value": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetUSB20ExtensionDeviceCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointNumber(_:)/title",
          "value": "IOUSBGetEndpointNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointNumber(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/title",
          "value": "IOUSBHostObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalMicroframes(_:_:)/title",
          "value": "IOUSBGetEndpointIntervalMicroframes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalMicroframes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointIntervalMicroframes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceDescriptor(_:_:)/title",
          "value": "IOUSBGetNextInterfaceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextInterfaceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptorWithType(_:_:_:)/title",
          "value": "IOUSBGetNextDescriptorWithType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptorWithType(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextDescriptorWithType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceAssociationDescriptor(_:_:)/title",
          "value": "IOUSBGetNextInterfaceAssociationDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextInterfaceAssociationDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextInterfaceAssociationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxPacketSize(_:_:)/title",
          "value": "IOUSBGetEndpointMaxPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxPacketSize(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointMaxPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)/title",
          "value": "IOUSBGetEndpointMaxStreamsEncoded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreamsEncoded(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointMaxStreamsEncoded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)/title",
          "value": "IOUSBGetEndpointIntervalEncodedMicroframes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalEncodedMicroframes(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointIntervalEncodedMicroframes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextEndpointDescriptor(_:_:_:)/title",
          "value": "IOUSBGetNextEndpointDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextEndpointDescriptor(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextEndpointDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptor(_:_:)/title",
          "value": "IOUSBGetNextCapabilityDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextCapabilityDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextCapabilityDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptor(_:_:)/title",
          "value": "IOUSBGetNextDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextDescriptor(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptor(_:_:_:)/title",
          "value": "IOUSBGetNextAssociatedDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetNextAssociatedDescriptor(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetNextAssociatedDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreams(_:_:_:)/title",
          "value": "IOUSBGetEndpointMaxStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointMaxStreams(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointMaxStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointDirection(_:)/title",
          "value": "IOUSBGetEndpointDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointDirection(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetBillboardDescriptor(_:)/title",
          "value": "IOUSBGetBillboardDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetBillboardDescriptor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetBillboardDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalFrames(_:_:)/title",
          "value": "IOUSBGetEndpointIntervalFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBGetEndpointIntervalFrames(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBGetEndpointIntervalFrames"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/parsing-usb-descriptors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/parsing-usb-descriptors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
