{
  "abstract": [
    {
      "text": "The signal noise is unreliable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/unreliableNoise"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:@SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unreliableNoise"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
        "text": "SRPhotoplethysmogramOpticalSample"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SRPhotoplethysmogramOpticalSampleCondition",
        "text": "Condition"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unreliableNoise"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unreliableNoise"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
              "text": "SRPhotoplethysmogramOpticalSample"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRPhotoplethysmogramOpticalSampleCondition",
              "text": "Condition"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample": {
      "abstract": [
        {
          "text": "A data sample from the photoplethysmogram (PPG) optical sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition": {
      "abstract": [
        {
          "text": "The conditions that may occur when recording photoplethysmogram optical data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample.Condition",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/condition"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/signalSaturation": {
      "abstract": [
        {
          "text": "The signal exceeds the measurement capacity of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signalSaturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
          "text": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramOpticalSampleCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/signalSaturation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSampleConditionSignalSaturation"
        }
      ],
      "role": "symbol",
      "title": "signalSaturation",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/condition/signalsaturation"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/unreliableNoise": {
      "abstract": [
        {
          "text": "The signal noise is unreliable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unreliableNoise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
          "text": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramOpticalSampleCondition",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/unreliableNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
        }
      ],
      "role": "symbol",
      "title": "unreliableNoise",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/condition/unreliablenoise"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-condition",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/signalSaturation"
      ],
      "title": "Getting the condition"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-condition",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition/signalSaturation"
              ],
              "title": "Getting the condition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SRPhotoplethysmogramOpticalSampleCondition",
                    "text": "SRPhotoplethysmogramOpticalSampleCondition"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition~1unreliableNoise/title",
          "value": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition~1unreliableNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleConditionUnreliableNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/title",
          "value": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition/title",
          "value": "SRPhotoplethysmogramOpticalSampleCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition~1signalSaturation/title",
          "value": "SRPhotoplethysmogramOpticalSampleConditionSignalSaturation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition~1signalSaturation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleConditionSignalSaturation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramopticalsample/condition/unreliablenoise"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramopticalsample/condition/unreliablenoise"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
