{
  "abstract": [
    {
      "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established. Any traffic directed to the specified name or address will initiate the connection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnTraffic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNetworkReachabilityFlags@kSCNetworkReachabilityFlagsConnectionOnTraffic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "connectionOnTraffic"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
        "text": "SCNetworkReachabilityFlags"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "connectionOnTraffic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "connectionOnTraffic"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
              "text": "SCNetworkReachabilityFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This flag was previously named ",
              "type": "text"
            },
            {
              "code": "kSCNetworkReachabilityFlagsConnectionAutomatic",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags": {
      "abstract": [
        {
          "text": "Flags that indicate the reachability of a network node name or address, including whether a connection is required, and whether some user intervention might be required when establishing a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkReachabilityFlags",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionAutomatic": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established. Any traffic directed to the specified name or address will initiate the connection. This flag is a synonym for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnTraffic",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionAutomatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionAutomatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsConnectionAutomatic"
        }
      ],
      "role": "symbol",
      "title": "connectionAutomatic",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/connectionautomatic"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnDemand": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionOnDemand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnDemand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsConnectionOnDemand"
        }
      ],
      "role": "symbol",
      "title": "connectionOnDemand",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/connectionondemand"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnTraffic": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established. Any traffic directed to the specified name or address will initiate the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionOnTraffic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnTraffic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
        }
      ],
      "role": "symbol",
      "title": "connectionOnTraffic",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/connectionontraffic"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionRequired": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established. If this flag is set, the ",
          "type": "text"
        },
        {
          "code": "kSCNetworkReachabilityFlagsConnectionOnTraffic",
          "type": "codeVoice"
        },
        {
          "text": " flag, ",
          "type": "text"
        },
        {
          "code": "kSCNetworkReachabilityFlagsConnectionOnDemand",
          "type": "codeVoice"
        },
        {
          "text": " flag, or ",
          "type": "text"
        },
        {
          "code": "kSCNetworkReachabilityFlagsIsWWAN",
          "type": "codeVoice"
        },
        {
          "text": " flag is also typically set to indicate the type of connection required. If the user must manually make the connection, the ",
          "type": "text"
        },
        {
          "code": "kSCNetworkReachabilityFlagsInterventionRequired",
          "type": "codeVoice"
        },
        {
          "text": " flag is also set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsConnectionRequired"
        }
      ],
      "role": "symbol",
      "title": "connectionRequired",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/connectionrequired"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/interventionRequired": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interventionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/interventionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsInterventionRequired"
        }
      ],
      "role": "symbol",
      "title": "interventionRequired",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/interventionrequired"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isDirect": {
      "abstract": [
        {
          "text": "Network traffic to the specified node name or address will not go through a gateway, but is routed directly to one of the interfaces in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsIsDirect"
        }
      ],
      "role": "symbol",
      "title": "isDirect",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/isdirect"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isLocalAddress": {
      "abstract": [
        {
          "text": "The specified node name or address is one that is associated with a network interface on the current system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLocalAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isLocalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsIsLocalAddress"
        }
      ],
      "role": "symbol",
      "title": "isLocalAddress",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/islocaladdress"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isWWAN": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached via a cellular connection, such as EDGE or GPRS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isWWAN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isWWAN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsIsWWAN"
        }
      ],
      "role": "symbol",
      "title": "isWWAN",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/iswwan"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/reachable": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/reachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsReachable"
        }
      ],
      "role": "symbol",
      "title": "reachable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/reachable"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/transientConnection": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached via a transient connection, such as PPP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transientConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNetworkReachabilityFlags",
          "text": "SCNetworkReachabilityFlags"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/transientConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkReachabilityFlagsTransientConnection"
        }
      ],
      "role": "symbol",
      "title": "transientConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachabilityflags/transientconnection"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/transientConnection",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/reachable",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionRequired",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/interventionRequired",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnDemand",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isLocalAddress",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isDirect",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isWWAN",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionAutomatic"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/transientConnection",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/reachable",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionRequired",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/interventionRequired",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionOnDemand",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isLocalAddress",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isDirect",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/isWWAN",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkReachabilityFlags/connectionAutomatic"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionOnDemand/title",
          "value": "kSCNetworkReachabilityFlagsConnectionOnDemand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionOnDemand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsConnectionOnDemand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1isDirect/title",
          "value": "kSCNetworkReachabilityFlagsIsDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1isDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsIsDirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1interventionRequired/title",
          "value": "kSCNetworkReachabilityFlagsInterventionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1interventionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsInterventionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1isLocalAddress/title",
          "value": "kSCNetworkReachabilityFlagsIsLocalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1isLocalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsIsLocalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1transientConnection/title",
          "value": "kSCNetworkReachabilityFlagsTransientConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1transientConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsTransientConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionAutomatic/title",
          "value": "kSCNetworkReachabilityFlagsConnectionAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionAutomatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsConnectionAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionRequired/title",
          "value": "kSCNetworkReachabilityFlagsConnectionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsConnectionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1reachable/title",
          "value": "kSCNetworkReachabilityFlagsReachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1reachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsReachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionOnTraffic/title",
          "value": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1connectionOnTraffic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsConnectionOnTraffic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1isWWAN/title",
          "value": "kSCNetworkReachabilityFlagsIsWWAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags~1isWWAN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkReachabilityFlagsIsWWAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags/title",
          "value": "SCNetworkReachabilityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkReachabilityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkReachabilityFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkReachabilityFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworkreachabilityflags/connectionontraffic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworkreachabilityflags/connectionontraffic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
