{
  "abstract": [
    {
      "text": "Returns the starting location of the text range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextRange"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextRange/location"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextRange(py)location",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "location"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)NSTextLocation",
        "text": "NSTextLocation"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "location"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "location"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSTextLocation",
              "text": "NSTextLocation"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLocation": {
      "abstract": [
        {
          "text": "An interface you implement that represents an abstract location inside your document’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLocation"
        }
      ],
      "role": "symbol",
      "title": "NSTextLocation",
      "type": "topic",
      "url": "/documentation/uikit/nstextlocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextRange": {
      "abstract": [
        {
          "text": "A class that represents a contiguous range between two locations inside document contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextRange"
        }
      ],
      "role": "symbol",
      "title": "NSTextRange",
      "type": "topic",
      "url": "/documentation/uikit/nstextrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextRange/endLocation": {
      "abstract": [
        {
          "text": "Returns the ending location of the text range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endLocation"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange/endLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endLocation"
        }
      ],
      "role": "symbol",
      "title": "endLocation",
      "type": "topic",
      "url": "/documentation/uikit/nstextrange/endlocation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextRange/isEmpty": {
      "abstract": [
        {
          "text": "Returns whether the text range is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange/isEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "empty"
        }
      ],
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/uikit/nstextrange/isempty"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextRange/location": {
      "abstract": [
        {
          "text": "Returns the starting location of the text range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextRange/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/uikit/nstextrange/location"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Characteristics-of-the-text-range",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextRange/endLocation",
        "doc://com.apple.uikit/documentation/UIKit/NSTextRange/isEmpty"
      ],
      "title": "Characteristics of the text range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSTextRange"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Characteristics-of-the-text-range",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextRange/endLocation",
                "doc://com.apple.uikit/documentation/UIKit/NSTextRange/isEmpty"
              ],
              "title": "Characteristics of the text range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)NSTextLocation",
                    "text": "id<NSTextLocation>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "location"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange~1endLocation/title",
          "value": "endLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange~1endLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/title",
          "value": "NSTextLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange~1isEmpty/title",
          "value": "empty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange~1isEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "empty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange/title",
          "value": "NSTextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextrange/location"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextrange/location"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
