{"identifier":{"url":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedLabel","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"attributedLabel","kind":"identifier"}],"modules":[{"name":"Accessibility"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedLabel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"}],"externalID":"c:objc(cs)AXCustomContent(py)attributedLabel","symbolKind":"property","role":"symbol","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"14.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"introducedAt":"14.0","beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS"},{"deprecated":false,"introducedAt":"7.0","beta":false,"unavailable":false,"name":"watchOS"}],"roleHeading":"Instance Property","title":"attributedLabel"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Accessibility/documentation/Accessibility","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent"]]},"seeAlsoSections":[{"generated":true,"title":"Defining custom content","identifiers":["doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/label","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/value","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedValue","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/importance-swift.property","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/Importance-swift.enum"],"anchor":"Defining-custom-content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"A localized attributed string that identifies the label for this content."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@NSCopying","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["/documentation/accessibility/axcustomcontent/attributedlabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accessibility/axcustomcontent/attributedlabel"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent":{"title":"AXCustomContent","type":"topic","identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent","role":"symbol","url":"/documentation/accessibility/axcustomcontent","navigatorTitle":[{"kind":"identifier","text":"AXCustomContent"}],"kind":"symbol","abstract":[{"type":"text","text":"Objects that define custom content and the timing of its output."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXCustomContent"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","kind":"technologies","role":"overview","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedLabel":{"title":"attributedLabel","type":"topic","identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedLabel","role":"symbol","url":"/documentation/accessibility/axcustomcontent/attributedlabel","navigatorTitle":[{"text":"attributedLabel","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A localized attributed string that identifies the label for this content."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributedLabel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"}]},"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/Importance-swift.enum":{"url":"/documentation/accessibility/axcustomcontent/importance-swift.enum","navigatorTitle":[{"text":"Importance","kind":"identifier"}],"identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/Importance-swift.enum","kind":"symbol","role":"symbol","type":"topic","title":"AXCustomContent.Importance","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Importance","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects that control the timing of content output."}]},"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedValue":{"url":"/documentation/accessibility/axcustomcontent/attributedvalue","navigatorTitle":[{"text":"attributedValue","kind":"identifier"}],"identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedValue","kind":"symbol","role":"symbol","type":"topic","title":"attributedValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attributedValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A localized attributed string that provides a value for the label."}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString":{"url":"/documentation/foundation/nsattributedstring","kind":"symbol","abstract":[{"type":"text","text":"A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering."}],"title":"NSAttributedString","fragments":[{"kind":"text","text":"class "},{"text":"NSAttributedString","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString"},"Accessibility-PageImage-card.png":{"type":"image","identifier":"Accessibility-PageImage-card.png","alt":"","variants":[{"url":"https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png","traits":["2x","dark"]}]},"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/importance-swift.property":{"title":"importance","type":"topic","identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/importance-swift.property","role":"symbol","url":"/documentation/accessibility/axcustomcontent/importance-swift.property","navigatorTitle":[{"kind":"identifier","text":"importance"}],"kind":"symbol","abstract":[{"type":"text","text":"An object that determines when to output custom accessibility content."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"importance"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AXCustomContent","text":"AXCustomContent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AXCustomContentImportance","text":"Importance","kind":"typeIdentifier"}]},"doc://com.apple.Accessibility/documentation/Accessibility":{"kind":"symbol","images":[{"type":"card","identifier":"Accessibility-PageImage-card.png"}],"identifier":"doc://com.apple.Accessibility/documentation/Accessibility","url":"/documentation/accessibility","abstract":[{"type":"text","text":"Make your apps accessible to everyone who uses Apple devices."}],"title":"Accessibility","type":"topic","role":"collection"},"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/value":{"title":"value","type":"topic","identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/value","role":"symbol","url":"/documentation/accessibility/axcustomcontent/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A localized string that provides a value for the label."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/label":{"title":"label","type":"topic","identifier":"doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/label","role":"symbol","url":"/documentation/accessibility/axcustomcontent/label","navigatorTitle":[{"kind":"identifier","text":"label"}],"kind":"symbol","abstract":[{"type":"text","text":"A localized string that identifies the label for this content."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"11.0","beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"14.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false},{"deprecated":false,"introducedAt":"7.0","beta":false,"unavailable":false,"name":"watchOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"attributedLabel","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"attributedLabel"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.Accessibility/documentation/Accessibility","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Defining-custom-content","title":"Defining custom content","identifiers":["doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/label","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/value","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/attributedValue","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/importance-swift.property","doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent/Importance-swift.enum"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString"},{"text":" * ","kind":"text"},{"text":"attributedLabel","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"value":"AXCustomContent","op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent/title"},{"value":[{"kind":"identifier","text":"AXCustomContent"}],"op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent/fragments"},{"value":[{"kind":"identifier","text":"AXCustomContent"}],"op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent/navigatorTitle"},{"value":"attributedLabel","op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1attributedLabel/title"},{"value":[{"kind":"identifier","text":"attributedLabel"}],"op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1attributedLabel/fragments"},{"value":"AXCustomContentImportance","op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1Importance-swift.enum/title"},{"value":[{"kind":"identifier","text":"AXCustomContentImportance"}],"op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1Importance-swift.enum/fragments"},{"value":[{"text":"AXCustomContentImportance","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1Importance-swift.enum/navigatorTitle"},{"value":"attributedValue","op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1attributedValue/title"},{"value":[{"text":"attributedValue","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1attributedValue/fragments"},{"op":"replace","value":"importance","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1importance-swift.property/title"},{"op":"replace","value":[{"kind":"identifier","text":"importance"}],"path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1importance-swift.property/fragments"},{"op":"replace","value":"value","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1value/title"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1value/fragments"},{"op":"replace","value":"label","path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1label/title"},{"op":"replace","value":[{"text":"label","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent~1label/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}