{
  "abstract": [
    {
      "text": "An edge makes the text appear pushed in.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/depressed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MACaptionAppearanceTextEdgeStyle@kMACaptionAppearanceTextEdgeStyleDepressed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "depressed"
      }
    ],
    "modules": [
      {
        "name": "Media Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMACaptionAppearanceTextEdgeStyleDepressed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MACaptionAppearanceTextEdgeStyle.depressed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "depressed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/mediaaccessibility"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle": {
      "abstract": [
        {
          "text": "A value that specifies a style for the outside of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceTextEdgeStyle"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MACaptionAppearanceTextEdgeStyle"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/depressed": {
      "abstract": [
        {
          "text": "An edge makes the text appear pushed in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depressed"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/depressed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceTextEdgeStyleDepressed"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle.depressed",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/depressed"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/dropShadow": {
      "abstract": [
        {
          "text": "An edge makes the text appear to float above the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropShadow"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/dropShadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceTextEdgeStyleDropShadow"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle.dropShadow",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/dropshadow"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/none": {
      "abstract": [
        {
          "text": "The text should not have a styled edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceTextEdgeStyleNone"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle.none",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/none"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/raised": {
      "abstract": [
        {
          "text": "An edge makes the text appear to rise above the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raised"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/raised",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceTextEdgeStyleRaised"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle.raised",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/raised"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/undefined": {
      "abstract": [
        {
          "text": "An edge style has not been specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceTextEdgeStyleUndefined"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle.undefined",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/undefined"
    },
    "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/uniform": {
      "abstract": [
        {
          "text": "A thin outline lies along the edge of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniform"
        }
      ],
      "identifier": "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/uniform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMACaptionAppearanceTextEdgeStyleUniform"
        }
      ],
      "role": "symbol",
      "title": "MACaptionAppearanceTextEdgeStyle.uniform",
      "type": "topic",
      "url": "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/uniform"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/undefined",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/none",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/raised",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/uniform",
        "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/dropShadow"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMACaptionAppearanceTextEdgeStyleDepressed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleDepressed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/undefined",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/none",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/raised",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/uniform",
                "doc://com.apple.mediaaccessibility/documentation/MediaAccessibility/MACaptionAppearanceTextEdgeStyle/dropShadow"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMACaptionAppearanceTextEdgeStyleDepressed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1none/title",
          "value": "kMACaptionAppearanceTextEdgeStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1raised/title",
          "value": "kMACaptionAppearanceTextEdgeStyleRaised"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1raised/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleRaised"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1depressed/title",
          "value": "kMACaptionAppearanceTextEdgeStyleDepressed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1depressed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleDepressed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle/title",
          "value": "MACaptionAppearanceTextEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceTextEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MACaptionAppearanceTextEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1undefined/title",
          "value": "kMACaptionAppearanceTextEdgeStyleUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1uniform/title",
          "value": "kMACaptionAppearanceTextEdgeStyleUniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1uniform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1dropShadow/title",
          "value": "kMACaptionAppearanceTextEdgeStyleDropShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaaccessibility~1documentation~1MediaAccessibility~1MACaptionAppearanceTextEdgeStyle~1dropShadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMACaptionAppearanceTextEdgeStyleDropShadow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/depressed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaaccessibility/macaptionappearancetextedgestyle/depressed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
