{
  "abstract": [
    {
      "text": "Constants for Video Toolbox operation error codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/1490398-error-code-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Code Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTAllocationFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTAllocationFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTAllocationFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtallocationfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionImageRotationFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionImageRotationFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTColorCorrectionImageRotationFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcolorcorrectionimagerotationfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionPixelTransferFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionPixelTransferFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTColorCorrectionPixelTransferFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcolorcorrectionpixeltransferfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTColorSyncTransformConvertFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTColorSyncTransformConvertFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTColorSyncTransformConvertFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcolorsynctransformconvertfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateColorCorrectionDataErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateColorCorrectionDataErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotCreateColorCorrectionDataErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotcreatecolorcorrectiondataerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateInstanceErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateInstanceErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotCreateInstanceErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotcreateinstanceerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindExtensionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindExtensionErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindExtensionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindExtensionErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindExtensionErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindextensionerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindTemporalFilterErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindTemporalFilterErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindTemporalFilterErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindtemporalfiltererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoDecoderErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoDecoderErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindVideoDecoderErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindvideodecodererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoEncoderErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoEncoderErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindVideoEncoderErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindvideoencodererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotOutputTaggedBufferGroupErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotOutputTaggedBufferGroupErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotOutputTaggedBufferGroupErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotoutputtaggedbuffergrouperr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionConflictErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTExtensionConflictErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionConflictErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionConflictErr"
        }
      ],
      "role": "symbol",
      "title": "kVTExtensionConflictErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtextensionconflicterr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionDisabledErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTExtensionDisabledErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionDisabledErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionDisabledErr"
        }
      ],
      "role": "symbol",
      "title": "kVTExtensionDisabledErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtextensiondisablederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTFormatDescriptionChangeNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTFormatDescriptionChangeNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTFormatDescriptionChangeNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtformatdescriptionchangenotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeRangeErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeRangeErr"
        }
      ],
      "role": "symbol",
      "title": "kVTFrameSiloInvalidTimeRangeErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtframesiloinvalidtimerangeerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeStampErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeStampErr"
        }
      ],
      "role": "symbol",
      "title": "kVTFrameSiloInvalidTimeStampErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtframesiloinvalidtimestamperr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTImageRotationNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTImageRotationNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTImageRotationNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtimagerotationnotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTInsufficientSourceColorDataErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTInsufficientSourceColorDataErr"
        }
      ],
      "role": "symbol",
      "title": "kVTInsufficientSourceColorDataErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtinsufficientsourcecolordataerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInvalidSessionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTInvalidSessionErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInvalidSessionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTInvalidSessionErr"
        }
      ],
      "role": "symbol",
      "title": "kVTInvalidSessionErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtinvalidsessionerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageIdentifierMismatchErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTMultiPassStorageIdentifierMismatchErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageIdentifierMismatchErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTMultiPassStorageIdentifierMismatchErr"
        }
      ],
      "role": "symbol",
      "title": "kVTMultiPassStorageIdentifierMismatchErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtmultipassstorageidentifiermismatcherr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageInvalidErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTMultiPassStorageInvalidErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageInvalidErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTMultiPassStorageInvalidErr"
        }
      ],
      "role": "symbol",
      "title": "kVTMultiPassStorageInvalidErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtmultipassstorageinvaliderr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTParameterErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTParameterErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTParameterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTParameterErr"
        }
      ],
      "role": "symbol",
      "title": "kVTParameterErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtparametererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationnotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotPermittedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferNotPermittedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotPermittedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferNotPermittedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferNotPermittedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransfernotpermittederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransfernotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertynotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyReadOnlyErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyReadOnlyErr"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyReadOnlyErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyreadonlyerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSessionMalfunctionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTSessionMalfunctionErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSessionMalfunctionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTSessionMalfunctionErr"
        }
      ],
      "role": "symbol",
      "title": "kVTSessionMalfunctionErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtsessionmalfunctionerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderAuthorizationErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderAuthorizationErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderAuthorizationErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderAuthorizationErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderAuthorizationErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderauthorizationerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderBadDataErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderBadDataErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderBadDataErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderBadDataErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderBadDataErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderbaddataerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderCallbackMessagingErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderCallbackMessagingErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderCallbackMessagingErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderCallbackMessagingErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderCallbackMessagingErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecodercallbackmessagingerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderMalfunctionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderMalfunctionErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderMalfunctionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderMalfunctionErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderMalfunctionErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecodermalfunctionerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNeedsRosettaErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderNeedsRosettaErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNeedsRosettaErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderNeedsRosettaErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderNeedsRosettaErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderneedsrosettaerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNotAvailableNowErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderNotAvailableNowErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNotAvailableNowErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderNotAvailableNowErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderNotAvailableNowErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecodernotavailablenowerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderReferenceMissingErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderReferenceMissingErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderReferenceMissingErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderReferenceMissingErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderReferenceMissingErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderreferencemissingerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderRemovedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderRemovedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderRemovedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderRemovedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderRemovedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderremovederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnknownErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderUnknownErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnknownErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderUnknownErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderUnknownErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderunknownerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnsupportedDataFormatErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderUnsupportedDataFormatErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnsupportedDataFormatErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderUnsupportedDataFormatErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderUnsupportedDataFormatErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderunsupporteddataformaterr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderAuthorizationErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderAuthorizationErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderAuthorizationErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderAuthorizationErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderAuthorizationErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderauthorizationerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencodermvhevcvideolayeridsmismatcherr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMalfunctionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderMalfunctionErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMalfunctionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderMalfunctionErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderMalfunctionErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencodermalfunctionerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNeedsRosettaErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderNeedsRosettaErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNeedsRosettaErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderNeedsRosettaErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderNeedsRosettaErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderneedsrosettaerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNotAvailableNowErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderNotAvailableNowErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNotAvailableNowErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderNotAvailableNowErr"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderNotAvailableNowErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencodernotavailablenowerr"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Errors-Codes",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInvalidSessionErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageIdentifierMismatchErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageInvalidErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTParameterErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotPermittedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSessionMalfunctionErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderAuthorizationErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderBadDataErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderCallbackMessagingErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderMalfunctionErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNeedsRosettaErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNotAvailableNowErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderReferenceMissingErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderRemovedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnknownErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnsupportedDataFormatErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderAuthorizationErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMalfunctionErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNeedsRosettaErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNotAvailableNowErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindExtensionErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionConflictErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionDisabledErr"
      ],
      "title": "Errors Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors-Codes",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInvalidSessionErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageIdentifierMismatchErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTMultiPassStorageInvalidErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTParameterErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotPermittedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSessionMalfunctionErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderAuthorizationErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderBadDataErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderCallbackMessagingErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderMalfunctionErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNeedsRosettaErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderNotAvailableNowErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderReferenceMissingErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderRemovedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnknownErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderUnsupportedDataFormatErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderAuthorizationErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderMalfunctionErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNeedsRosettaErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderNotAvailableNowErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindExtensionErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionConflictErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionDisabledErr"
              ],
              "title": "Errors Codes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFormatDescriptionChangeNotSupportedErr/title",
          "value": "kVTFormatDescriptionChangeNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFormatDescriptionChangeNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTFormatDescriptionChangeNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeRangeErr/title",
          "value": "kVTFrameSiloInvalidTimeRangeErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeRangeErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTFrameSiloInvalidTimeRangeErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderNeedsRosettaErr/title",
          "value": "kVTVideoDecoderNeedsRosettaErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderNeedsRosettaErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderNeedsRosettaErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationNotSupportedErr/title",
          "value": "kVTPixelRotationNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTParameterErr/title",
          "value": "kVTParameterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTParameterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTParameterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindExtensionErr/title",
          "value": "kVTCouldNotFindExtensionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindExtensionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindExtensionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionPixelTransferFailedErr/title",
          "value": "kVTColorCorrectionPixelTransferFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionPixelTransferFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTColorCorrectionPixelTransferFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderMalfunctionErr/title",
          "value": "kVTVideoEncoderMalfunctionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderMalfunctionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderMalfunctionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadOnlyErr/title",
          "value": "kVTPropertyReadOnlyErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadOnlyErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyReadOnlyErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderBadDataErr/title",
          "value": "kVTVideoDecoderBadDataErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderBadDataErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderBadDataErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTSessionMalfunctionErr/title",
          "value": "kVTSessionMalfunctionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTSessionMalfunctionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTSessionMalfunctionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotOutputTaggedBufferGroupErr/title",
          "value": "kVTCouldNotOutputTaggedBufferGroupErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotOutputTaggedBufferGroupErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotOutputTaggedBufferGroupErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderUnsupportedDataFormatErr/title",
          "value": "kVTVideoDecoderUnsupportedDataFormatErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderUnsupportedDataFormatErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderUnsupportedDataFormatErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTInsufficientSourceColorDataErr/title",
          "value": "kVTInsufficientSourceColorDataErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTInsufficientSourceColorDataErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTInsufficientSourceColorDataErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateColorCorrectionDataErr/title",
          "value": "kVTCouldNotCreateColorCorrectionDataErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateColorCorrectionDataErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotCreateColorCorrectionDataErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTAllocationFailedErr/title",
          "value": "kVTAllocationFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTAllocationFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTAllocationFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeStampErr/title",
          "value": "kVTFrameSiloInvalidTimeStampErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeStampErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTFrameSiloInvalidTimeStampErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderRemovedErr/title",
          "value": "kVTVideoDecoderRemovedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderRemovedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderRemovedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderAuthorizationErr/title",
          "value": "kVTVideoDecoderAuthorizationErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderAuthorizationErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderAuthorizationErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTInvalidSessionErr/title",
          "value": "kVTInvalidSessionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTInvalidSessionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTInvalidSessionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderCallbackMessagingErr/title",
          "value": "kVTVideoDecoderCallbackMessagingErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderCallbackMessagingErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderCallbackMessagingErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferNotPermittedErr/title",
          "value": "kVTPixelTransferNotPermittedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferNotPermittedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferNotPermittedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr/title",
          "value": "kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderMVHEVCVideoLayerIDsMismatchErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorSyncTransformConvertFailedErr/title",
          "value": "kVTColorSyncTransformConvertFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorSyncTransformConvertFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTColorSyncTransformConvertFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderAuthorizationErr/title",
          "value": "kVTVideoEncoderAuthorizationErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderAuthorizationErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderAuthorizationErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoDecoderErr/title",
          "value": "kVTCouldNotFindVideoDecoderErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoDecoderErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindVideoDecoderErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTExtensionConflictErr/title",
          "value": "kVTExtensionConflictErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTExtensionConflictErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionConflictErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTMultiPassStorageInvalidErr/title",
          "value": "kVTMultiPassStorageInvalidErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTMultiPassStorageInvalidErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTMultiPassStorageInvalidErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionImageRotationFailedErr/title",
          "value": "kVTColorCorrectionImageRotationFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionImageRotationFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTColorCorrectionImageRotationFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderNotAvailableNowErr/title",
          "value": "kVTVideoEncoderNotAvailableNowErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderNotAvailableNowErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderNotAvailableNowErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferNotSupportedErr/title",
          "value": "kVTPixelTransferNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindTemporalFilterErr/title",
          "value": "kVTCouldNotFindTemporalFilterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindTemporalFilterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindTemporalFilterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyNotSupportedErr/title",
          "value": "kVTPropertyNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoEncoderErr/title",
          "value": "kVTCouldNotFindVideoEncoderErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoEncoderErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindVideoEncoderErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderUnknownErr/title",
          "value": "kVTVideoDecoderUnknownErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderUnknownErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderUnknownErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTImageRotationNotSupportedErr/title",
          "value": "kVTImageRotationNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTImageRotationNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTImageRotationNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateInstanceErr/title",
          "value": "kVTCouldNotCreateInstanceErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateInstanceErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotCreateInstanceErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderMalfunctionErr/title",
          "value": "kVTVideoDecoderMalfunctionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderMalfunctionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderMalfunctionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderNotAvailableNowErr/title",
          "value": "kVTVideoDecoderNotAvailableNowErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderNotAvailableNowErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderNotAvailableNowErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderNeedsRosettaErr/title",
          "value": "kVTVideoEncoderNeedsRosettaErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderNeedsRosettaErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderNeedsRosettaErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTMultiPassStorageIdentifierMismatchErr/title",
          "value": "kVTMultiPassStorageIdentifierMismatchErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTMultiPassStorageIdentifierMismatchErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTMultiPassStorageIdentifierMismatchErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderReferenceMissingErr/title",
          "value": "kVTVideoDecoderReferenceMissingErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderReferenceMissingErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderReferenceMissingErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTExtensionDisabledErr/title",
          "value": "kVTExtensionDisabledErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTExtensionDisabledErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionDisabledErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/1490398-error-code-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/1490398-error-code-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
