{
  "abstract": [
    {
      "text": "Properties used to configure a VideoToolbox decompression session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/decompression-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Decompression Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection": {
      "abstract": [
        {
          "text": "An object that decompresses video data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection": {
      "abstract": [
        {
          "text": "An abstract object that provides the common interface to configure VideoToolbox session objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)": {
      "abstract": [
        {
          "text": "Sets multiple properties at once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionSetProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "propertyDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionSetProperties"
        }
      ],
      "role": "symbol",
      "title": "VTSessionSetProperties(_:propertyDictionary:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessionsetproperties(_:propertydictionary:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)": {
      "abstract": [
        {
          "text": "Sets a property on a VideoToolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionSetProperty"
        }
      ],
      "role": "symbol",
      "title": "VTSessionSetProperty(_:key:value:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessionsetproperty(_:key:value:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTVideoDecoderExtensionProperties(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTVideoDecoderExtensionProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTVideoDecoderExtensionProperties(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTVideoDecoderExtensionProperties(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtvideodecoderextensionproperties(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_allowbitstreamtochangeframedimensions"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ContentHasInterframeDependencies": {
      "abstract": [
        {
          "text": "An optional Boolean property indicating if the content being decoded has interframe dependencies, if the decoder knows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ContentHasInterframeDependencies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ContentHasInterframeDependencies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ContentHasInterframeDependencies"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_ContentHasInterframeDependencies",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_contenthasinterframedependencies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_decoderproducesrawoutput"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DeinterlaceMode": {
      "abstract": [
        {
          "text": "Modes for requesting a specific deinterlacing technique.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_DeinterlaceMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DeinterlaceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_DeinterlaceMode"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_DeinterlaceMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_deinterlacemode"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_FieldMode": {
      "abstract": [
        {
          "text": "Modes for special handling of interlaced content (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_FieldMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_FieldMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_FieldMode"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_FieldMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_fieldmode"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata": {
      "abstract": [
        {
          "text": "A key that indicates to generate per frame HDR Metadata and attach it to the resulting decoded pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_generateperframehdrdisplaymetadata"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded": {
      "abstract": [
        {
          "text": "The maximum output presentation timestamp of the frames currently being decoded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_maxoutputpresentationtimestampofframesbeingdecoded"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaximizePowerEfficiency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_MaximizePowerEfficiency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaximizePowerEfficiency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_MaximizePowerEfficiency"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_MaximizePowerEfficiency",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_maximizepowerefficiency"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded": {
      "abstract": [
        {
          "text": "The minimum output presentation timestamp of the frames currently being decoded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_minoutputpresentationtimestampofframesbeingdecoded"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded": {
      "abstract": [
        {
          "text": "Returns the number of frames currently being decoded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_numberofframesbeingdecoded"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OnlyTheseFrames": {
      "abstract": [
        {
          "text": "Requests that frames be filtered by type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_OnlyTheseFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OnlyTheseFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_OnlyTheseFrames"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_OnlyTheseFrames",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_onlytheseframes"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount": {
      "abstract": [
        {
          "text": "The requested minimum buffer count that a decompression session should use for its output pixel buffer pool, without releasing buffers while the number in use is below this level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_outputpoolrequestedminimumbuffercount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPool": {
      "abstract": [
        {
          "text": "A pixel buffer pool for pixel buffers being output by the decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelBufferPool"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelBufferPool"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PixelBufferPool",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_pixelbufferpool"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPoolIsShared": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a common pixel buffer pool is shared between the video decoder and the session client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelBufferPoolIsShared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPoolIsShared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelBufferPoolIsShared"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PixelBufferPoolIsShared",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_pixelbufferpoolisshared"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport": {
      "abstract": [
        {
          "text": "Pixel formats that support reduced-resolution decoding (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_pixelformatswithreducedresolutionsupport"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties": {
      "abstract": [
        {
          "text": "Specific pixel transfer features to be used during decompression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelTransferProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelTransferProperties"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PixelTransferProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_pixeltransferproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_propagateperframehdrdisplaymetadata"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RealTime": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether it’s recommended that the video decoder perform decompression in real time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RealTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RealTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RealTime"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_RealTime",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_realtime"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedCoefficientDecode": {
      "abstract": [
        {
          "text": "Requests approximation during decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ReducedCoefficientDecode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedCoefficientDecode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ReducedCoefficientDecode"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_ReducedCoefficientDecode",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_reducedcoefficientdecode"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedFrameDelivery": {
      "abstract": [
        {
          "text": "The proportion of frames that should be delivered, indicating that the rest may be dropped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ReducedFrameDelivery"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedFrameDelivery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ReducedFrameDelivery"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_ReducedFrameDelivery",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_reducedframedelivery"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedResolutionDecode": {
      "abstract": [
        {
          "text": "Request decoding at smaller resolutions than full-size (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ReducedResolutionDecode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedResolutionDecode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ReducedResolutionDecode"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_ReducedResolutionDecode",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_reducedresolutiondecode"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_RequestRAWOutput",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_requestrawoutput"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs": {
      "abstract": [
        {
          "text": "Requests multi-image decoding of specific MV-HEVC video layers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_requestedmvhevcvideolayerids"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers": {
      "abstract": [
        {
          "text": "An array of dictionaries that describe decreasing quality-of-service levels that clients can use to maintain realtime playback (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_suggestedqualityofservicetiers"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance": {
      "abstract": [
        {
          "text": "An array indicating speed tradeoffs between pixel formats (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_supportedpixelformatsorderedbyperformance"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality": {
      "abstract": [
        {
          "text": "An array indicating quality levels among pixel formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_supportedpixelformatsorderedbyquality"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount": {
      "abstract": [
        {
          "text": "The number of threads used by a codec or the suggested number of threads to use (optional).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ThreadCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_ThreadCount"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_ThreadCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_threadcount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_UsingGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_UsingGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_UsingGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_usinggpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder": {
      "abstract": [
        {
          "text": "Indicates if a hardware-accelerated video decoder is being used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_usinghardwareacceleratedvideodecoder"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionProperty_TemporalLevelLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionProperty_TemporalLevelLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionProperty_TemporalLevelLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionProperty_TemporalLevelLimit"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionProperty_TemporalLevelLimit",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionproperty_temporallevellimit"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether VideoToolbox uses a hardware-accelerated video decoder, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderspecification_enablehardwareacceleratedvideodecoder"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderspecification_preferreddecodergpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to require hardware-accelerated decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderspecification_requirehardwareacceleratedvideodecoder"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderspecification_requireddecodergpuregistryid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-Session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTVideoDecoderExtensionProperties(_:)"
      ],
      "title": "Configuring a Session"
    }
  ],
  "topicSections": [
    {
      "anchor": "Pixel-Buffer-Pools",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPool",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPoolIsShared",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount"
      ],
      "title": "Pixel Buffer Pools"
    },
    {
      "anchor": "Asynchronous-State",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded"
      ],
      "title": "Asynchronous State"
    },
    {
      "anchor": "Content",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ContentHasInterframeDependencies"
      ],
      "title": "Content"
    },
    {
      "anchor": "Hardware-Acceleration",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder"
      ],
      "title": "Hardware Acceleration"
    },
    {
      "anchor": "Decoder-Behavior",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RealTime",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaximizePowerEfficiency",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_FieldMode",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DeinterlaceMode",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedResolutionDecode",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedCoefficientDecode",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedFrameDelivery",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OnlyTheseFrames",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionProperty_TemporalLevelLimit",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions"
      ],
      "title": "Decoder Behavior"
    },
    {
      "anchor": "Post-Decompression-Processing",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput"
      ],
      "title": "Post-Decompression Processing"
    },
    {
      "anchor": "Multiview-Decompression",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs"
      ],
      "title": "Multiview Decompression"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Pixel-Buffer-Pools",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPool",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelBufferPoolIsShared",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount"
              ],
              "title": "Pixel Buffer Pools"
            },
            {
              "anchor": "Asynchronous-State",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded"
              ],
              "title": "Asynchronous State"
            },
            {
              "anchor": "Content",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ContentHasInterframeDependencies"
              ],
              "title": "Content"
            },
            {
              "anchor": "Hardware-Acceleration",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder"
              ],
              "title": "Hardware Acceleration"
            },
            {
              "anchor": "Decoder-Behavior",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RealTime",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_MaximizePowerEfficiency",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ThreadCount",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_FieldMode",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DeinterlaceMode",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedResolutionDecode",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedCoefficientDecode",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_ReducedFrameDelivery",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_OnlyTheseFrames",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionProperty_TemporalLevelLimit",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions"
              ],
              "title": "Decoder Behavior"
            },
            {
              "anchor": "Post-Decompression-Processing",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput"
              ],
              "title": "Post-Decompression Processing"
            },
            {
              "anchor": "Multiview-Decompression",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs"
              ],
              "title": "Multiview Decompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-Session",
              "generated": true,
              "identifiers": [],
              "title": "Configuring a Session"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionProperty_TemporalLevelLimit/title",
          "value": "kVTDecompressionProperty_TemporalLevelLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionProperty_TemporalLevelLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionProperty_TemporalLevelLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_DeinterlaceMode/title",
          "value": "kVTDecompressionPropertyKey_DeinterlaceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_DeinterlaceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_DeinterlaceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ReducedFrameDelivery/title",
          "value": "kVTDecompressionPropertyKey_ReducedFrameDelivery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ReducedFrameDelivery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_ReducedFrameDelivery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelBufferPool/title",
          "value": "kVTDecompressionPropertyKey_PixelBufferPool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelBufferPool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PixelBufferPool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID/title",
          "value": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelTransferProperties/title",
          "value": "kVTDecompressionPropertyKey_PixelTransferProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelTransferProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PixelTransferProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperty(_:key:value:)/title",
          "value": "VTSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperty(_:key:value:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelBufferPoolIsShared/title",
          "value": "kVTDecompressionPropertyKey_PixelBufferPoolIsShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelBufferPoolIsShared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PixelBufferPoolIsShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs/title",
          "value": "kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_RequestedMVHEVCVideoLayerIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers/title",
          "value": "kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_SuggestedQualityOfServiceTiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded/title",
          "value": "kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_NumberOfFramesBeingDecoded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_OnlyTheseFrames/title",
          "value": "kVTDecompressionPropertyKey_OnlyTheseFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_OnlyTheseFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_OnlyTheseFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata/title",
          "value": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded/title",
          "value": "kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_MinOutputPresentationTimeStampOfFramesBeingDecoded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded/title",
          "value": "kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_MaxOutputPresentationTimeStampOfFramesBeingDecoded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport/title",
          "value": "kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PixelFormatsWithReducedResolutionSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ContentHasInterframeDependencies/title",
          "value": "kVTDecompressionPropertyKey_ContentHasInterframeDependencies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ContentHasInterframeDependencies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_ContentHasInterframeDependencies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ReducedResolutionDecode/title",
          "value": "kVTDecompressionPropertyKey_ReducedResolutionDecode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ReducedResolutionDecode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_ReducedResolutionDecode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions/title",
          "value": "kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_AllowBitstreamToChangeFrameDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ReducedCoefficientDecode/title",
          "value": "kVTDecompressionPropertyKey_ReducedCoefficientDecode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ReducedCoefficientDecode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_ReducedCoefficientDecode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_MaximizePowerEfficiency/title",
          "value": "kVTDecompressionPropertyKey_MaximizePowerEfficiency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_MaximizePowerEfficiency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_MaximizePowerEfficiency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance/title",
          "value": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByPerformance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperties(_:propertyDictionary:)/title",
          "value": "VTSessionSetProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperties(_:propertyDictionary:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionSetProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ThreadCount/title",
          "value": "kVTDecompressionPropertyKey_ThreadCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_ThreadCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_ThreadCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder/title",
          "value": "kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_UsingHardwareAcceleratedVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_FieldMode/title",
          "value": "kVTDecompressionPropertyKey_FieldMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_FieldMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_FieldMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder/title",
          "value": "kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_UsingGPURegistryID/title",
          "value": "kVTDecompressionPropertyKey_UsingGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_UsingGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_UsingGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RequestRAWOutput/title",
          "value": "kVTDecompressionPropertyKey_RequestRAWOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RequestRAWOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder/title",
          "value": "kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality/title",
          "value": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_SupportedPixelFormatsOrderedByQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount/title",
          "value": "kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_OutputPoolRequestedMinimumBufferCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RealTime/title",
          "value": "kVTDecompressionPropertyKey_RealTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RealTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_RealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata/title",
          "value": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_DecoderProducesRAWOutput/title",
          "value": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_DecoderProducesRAWOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID/title",
          "value": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/decompression-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/decompression-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
