{
  "abstract": [
    {
      "text": "The recommended minimum number of video frames for a given subdivision in a parallel encoding configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For best results, ensure that the total number of frames of a parallelized subdivision is greater than or equal to this value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This configuration isn’t supported by all video encoders.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EnableLTR": {
      "abstract": [
        {
          "text": "Enables Long Term Reference (LTR) frames during encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_EnableLTR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EnableLTR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_EnableLTR"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_EnableLTR",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_enableltr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EncoderID": {
      "abstract": [
        {
          "text": "Specifies a particular video encoder by its ID string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_EncoderID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EncoderID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_EncoderID"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_EncoderID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_encoderid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxAllowedFrameQP": {
      "abstract": [
        {
          "text": "The maximum allowed encoded frame QP (Quantization Parameter).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaxAllowedFrameQP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxAllowedFrameQP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaxAllowedFrameQP"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_MaxAllowedFrameQP",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_maxallowedframeqp"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MinAllowedFrameQP": {
      "abstract": [
        {
          "text": "The minimum allowed encoded frame QP (Quantization Parameter).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MinAllowedFrameQP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MinAllowedFrameQP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MinAllowedFrameQP"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_MinAllowedFrameQP",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_minallowedframeqp"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_PreserveDynamicHDRMetadata": {
      "abstract": [
        {
          "text": "Specifies whether to preserve dynamic HDR metadata on the input pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_PreserveDynamicHDRMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_PreserveDynamicHDRMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_PreserveDynamicHDRMetadata"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_PreserveDynamicHDRMetadata",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_preservedynamichdrmetadata"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizationLimit": {
      "abstract": [
        {
          "text": "The recommended number of compression sessions to instantiate in a parallel encoding configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RecommendedParallelizationLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizationLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RecommendedParallelizationLimit"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_RecommendedParallelizationLimit",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_recommendedparallelizationlimit"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration": {
      "abstract": [
        {
          "text": "The recommended minimum duration for a given subdivision in a parallel encoding configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_recommendedparallelizedsubdivisionminimumduration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount": {
      "abstract": [
        {
          "text": "The recommended minimum number of video frames for a given subdivision in a parallel encoding configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_recommendedparallelizedsubdivisionminimumframecount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_AcknowledgedLTRTokens": {
      "abstract": [
        {
          "text": "Enable Long Term Reference (LTR) frames during encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTEncodeFrameOptionKey_AcknowledgedLTRTokens"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_AcknowledgedLTRTokens",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTEncodeFrameOptionKey_AcknowledgedLTRTokens"
        }
      ],
      "role": "symbol",
      "title": "kVTEncodeFrameOptionKey_AcknowledgedLTRTokens",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtencodeframeoptionkey_acknowledgedltrtokens"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_ForceLTRRefresh": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to force Long Term Reference (LTR).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTEncodeFrameOptionKey_ForceLTRRefresh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_ForceLTRRefresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTEncodeFrameOptionKey_ForceLTRRefresh"
        }
      ],
      "role": "symbol",
      "title": "kVTEncodeFrameOptionKey_ForceLTRRefresh",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtencodeframeoptionkey_forceltrrefresh"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSampleAttachmentKey_RequireLTRAcknowledgementToken": {
      "abstract": [
        {
          "text": "A number value that contains a unique token for this Long Term Reference (LTR).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTSampleAttachmentKey_RequireLTRAcknowledgementToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSampleAttachmentKey_RequireLTRAcknowledgementToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTSampleAttachmentKey_RequireLTRAcknowledgementToken"
        }
      ],
      "role": "symbol",
      "title": "kVTSampleAttachmentKey_RequireLTRAcknowledgementToken",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtsampleattachmentkey_requireltracknowledgementtoken"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableLowLatencyRateControl": {
      "abstract": [
        {
          "text": "Specifies to select an encoder that supports low-latency operation and enables low-latency mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_EnableLowLatencyRateControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableLowLatencyRateControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_EnableLowLatencyRateControl"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderSpecification_EnableLowLatencyRateControl",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderspecification_enablelowlatencyratecontrol"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EncoderID": {
      "abstract": [
        {
          "text": "A key that indicates a particular video encoder to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_EncoderID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EncoderID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_EncoderID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderSpecification_EncoderID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderspecification_encoderid"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encoder-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EncoderID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizationLimit",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EnableLTR",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EncoderID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MinAllowedFrameQP",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxAllowedFrameQP",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_PreserveDynamicHDRMetadata",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_AcknowledgedLTRTokens",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_ForceLTRRefresh",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSampleAttachmentKey_RequireLTRAcknowledgementToken",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableLowLatencyRateControl"
      ],
      "title": "Encoder Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encoder-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EncoderID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizationLimit",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EnableLTR",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_EncoderID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MinAllowedFrameQP",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxAllowedFrameQP",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_PreserveDynamicHDRMetadata",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_AcknowledgedLTRTokens",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTEncodeFrameOptionKey_ForceLTRRefresh",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTSampleAttachmentKey_RequireLTRAcknowledgementToken",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableLowLatencyRateControl"
              ],
              "title": "Encoder Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration/title",
          "value": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_EnableLowLatencyRateControl/title",
          "value": "kVTVideoEncoderSpecification_EnableLowLatencyRateControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_EnableLowLatencyRateControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_EnableLowLatencyRateControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_PreserveDynamicHDRMetadata/title",
          "value": "kVTCompressionPropertyKey_PreserveDynamicHDRMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_PreserveDynamicHDRMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_PreserveDynamicHDRMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTEncodeFrameOptionKey_ForceLTRRefresh/title",
          "value": "kVTEncodeFrameOptionKey_ForceLTRRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTEncodeFrameOptionKey_ForceLTRRefresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTEncodeFrameOptionKey_ForceLTRRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount/title",
          "value": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_RecommendedParallelizedSubdivisionMinimumFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_EnableLTR/title",
          "value": "kVTCompressionPropertyKey_EnableLTR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_EnableLTR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_EnableLTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTEncodeFrameOptionKey_AcknowledgedLTRTokens/title",
          "value": "kVTEncodeFrameOptionKey_AcknowledgedLTRTokens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTEncodeFrameOptionKey_AcknowledgedLTRTokens/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTEncodeFrameOptionKey_AcknowledgedLTRTokens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_EncoderID/title",
          "value": "kVTVideoEncoderSpecification_EncoderID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_EncoderID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_EncoderID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MinAllowedFrameQP/title",
          "value": "kVTCompressionPropertyKey_MinAllowedFrameQP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MinAllowedFrameQP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MinAllowedFrameQP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaxAllowedFrameQP/title",
          "value": "kVTCompressionPropertyKey_MaxAllowedFrameQP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaxAllowedFrameQP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MaxAllowedFrameQP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTSampleAttachmentKey_RequireLTRAcknowledgementToken/title",
          "value": "kVTSampleAttachmentKey_RequireLTRAcknowledgementToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTSampleAttachmentKey_RequireLTRAcknowledgementToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTSampleAttachmentKey_RequireLTRAcknowledgementToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_EncoderID/title",
          "value": "kVTCompressionPropertyKey_EncoderID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_EncoderID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_EncoderID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RecommendedParallelizationLimit/title",
          "value": "kVTCompressionPropertyKey_RecommendedParallelizationLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RecommendedParallelizationLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_RecommendedParallelizationLimit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtcompressionpropertykey_recommendedparallelizedsubdivisionminimumframecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtcompressionpropertykey_recommendedparallelizedsubdivisionminimumframecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
