{
  "abstract": [
    {
      "text": "The maximum number of frames that a compressor is allowed to hold before it must output a compressed frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxFrameDelayCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTCompressionPropertyKey_MaxFrameDelayCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTCompressionPropertyKey_MaxFrameDelayCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value limits the number of frames that may be held in the compression window. If the maximum frame delay count is M, then before the call to encode frame N returns, frame N-M must have been emitted. The default is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTUnlimitedFrameDelayCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which sets no limit on the compression window.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxFrameDelayCount": {
      "abstract": [
        {
          "text": "The maximum number of frames that a compressor is allowed to hold before it must output a compressed frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxFrameDelayCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_MaxFrameDelayCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_maxframedelaycount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxH264SliceBytes": {
      "abstract": [
        {
          "text": "The maximum slice size for H.264 encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaxH264SliceBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxH264SliceBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaxH264SliceBytes"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_MaxH264SliceBytes",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_maxh264slicebytes"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaximizePowerEfficiency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaximizePowerEfficiency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaximizePowerEfficiency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_MaximizePowerEfficiency"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_MaximizePowerEfficiency",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_maximizepowerefficiency"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RealTime": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether it’s recommended that the video encoder perform compression in real time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RealTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RealTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_RealTime"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_RealTime",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_realtime"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTUnlimitedFrameDelayCount": {
      "abstract": [
        {
          "text": "Indicates that no limit should be set on the compression window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTUnlimitedFrameDelayCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTUnlimitedFrameDelayCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTUnlimitedFrameDelayCount"
        }
      ],
      "role": "symbol",
      "title": "kVTUnlimitedFrameDelayCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtunlimitedframedelaycount"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Runtime-Restrictions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxH264SliceBytes",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaximizePowerEfficiency",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RealTime"
      ],
      "title": "Runtime Restrictions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Delay-Counts",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTUnlimitedFrameDelayCount"
      ],
      "title": "Delay Counts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTCompressionPropertyKey_MaxFrameDelayCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Delay-Counts",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTUnlimitedFrameDelayCount"
              ],
              "title": "Delay Counts"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Runtime-Restrictions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaxH264SliceBytes",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_MaximizePowerEfficiency",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_RealTime"
              ],
              "title": "Runtime Restrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTUnlimitedFrameDelayCount/title",
          "value": "kVTUnlimitedFrameDelayCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTUnlimitedFrameDelayCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTUnlimitedFrameDelayCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaximizePowerEfficiency/title",
          "value": "kVTCompressionPropertyKey_MaximizePowerEfficiency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaximizePowerEfficiency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MaximizePowerEfficiency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RealTime/title",
          "value": "kVTCompressionPropertyKey_RealTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_RealTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_RealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaxFrameDelayCount/title",
          "value": "kVTCompressionPropertyKey_MaxFrameDelayCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaxFrameDelayCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MaxFrameDelayCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaxH264SliceBytes/title",
          "value": "kVTCompressionPropertyKey_MaxH264SliceBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_MaxH264SliceBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_MaxH264SliceBytes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtcompressionpropertykey_maxframedelaycount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtcompressionpropertykey_maxframedelaycount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
