{
  "abstract": [
    {
      "text": "A value that requests that the encoder retain the specified number of frames during encoding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTCompressionPropertyKey_SuggestedLookAheadFrameCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These frames will be used for additional analysis and statistics gathering before the frame is finally encoded at the end of the window. When this property is not set, video encoder will automatically determine the number of lookahead frames.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Encoder will choose number of lookahead frames closer to the suggested value based on internal configuration. This property directly affects latency",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of the video encoder. The following properties also affect look ahead frames:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Value of this property must be less than or equal to ",
                      "type": "text"
                    },
                    {
                      "code": "kVTCompressionPropertyKey_MaxFrameDelayCount",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "This property is ignored when ",
                      "type": "text"
                    },
                    {
                      "code": "VTVideoEncoderSpecification_EnableLowLatencyRateControl",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is set to true",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "This property is ignored when ",
                      "type": "text"
                    },
                    {
                      "code": "kVTCompressionPropertyKey_Quality",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is set to 1.0",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "This property can not be used in conjunction with multi-pass feature (",
                      "type": "text"
                    },
                    {
                      "code": "kVTCompressionPropertyKey_MultiPassStorage",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HeroEye": {
      "abstract": [
        {
          "text": "A value that indicates which eye is the primary eye when rendering in 2D.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_HeroEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HeroEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_HeroEye"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_HeroEye",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_heroeye"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HorizontalDisparityAdjustment": {
      "abstract": [
        {
          "text": "A value that indicates a relative shift of the left and right images, which changes the zero parallax plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_HorizontalDisparityAdjustment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HorizontalDisparityAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_HorizontalDisparityAdjustment"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_HorizontalDisparityAdjustment",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_horizontaldisparityadjustment"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ProjectionKind": {
      "abstract": [
        {
          "text": "A value that indicates the projection kind.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_ProjectionKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ProjectionKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_ProjectionKind"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_ProjectionKind",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_projectionkind"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SpatialAdaptiveQPLevel": {
      "abstract": [
        {
          "text": "A value that controls spatial adaptation of the quantization parameter (QP) based on per-frame statistics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_SpatialAdaptiveQPLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SpatialAdaptiveQPLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_SpatialAdaptiveQPLevel"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_SpatialAdaptiveQPLevel",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_spatialadaptiveqplevel"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_StereoCameraBaseline": {
      "abstract": [
        {
          "text": "A value that specifies the distance between centers of the lenses of the camera system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_StereoCameraBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_StereoCameraBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_StereoCameraBaseline"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_StereoCameraBaseline",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_stereocamerabaseline"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SuggestedLookAheadFrameCount": {
      "abstract": [
        {
          "text": "A value that requests that the encoder retain the specified number of frames during encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SuggestedLookAheadFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_suggestedlookaheadframecount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ViewPackingKind": {
      "abstract": [
        {
          "text": "A value that indicates the view packing kind.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_ViewPackingKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ViewPackingKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_ViewPackingKind"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_ViewPackingKind",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_viewpackingkind"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Video-Extended-Usage-VEXU-Signaling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HeroEye",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_StereoCameraBaseline",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HorizontalDisparityAdjustment",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ProjectionKind",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SpatialAdaptiveQPLevel",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ViewPackingKind"
      ],
      "title": "Video Extended Usage (VEXU) Signaling"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Video-Extended-Usage-VEXU-Signaling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HeroEye",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_StereoCameraBaseline",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_HorizontalDisparityAdjustment",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ProjectionKind",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SpatialAdaptiveQPLevel",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_ViewPackingKind"
              ],
              "title": "Video Extended Usage (VEXU) Signaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_SuggestedLookAheadFrameCount/title",
          "value": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_SuggestedLookAheadFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_SuggestedLookAheadFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_ViewPackingKind/title",
          "value": "kVTCompressionPropertyKey_ViewPackingKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_ViewPackingKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_ViewPackingKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_HeroEye/title",
          "value": "kVTCompressionPropertyKey_HeroEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_HeroEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_HeroEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_ProjectionKind/title",
          "value": "kVTCompressionPropertyKey_ProjectionKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_ProjectionKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_ProjectionKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_StereoCameraBaseline/title",
          "value": "kVTCompressionPropertyKey_StereoCameraBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_StereoCameraBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_StereoCameraBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_SpatialAdaptiveQPLevel/title",
          "value": "kVTCompressionPropertyKey_SpatialAdaptiveQPLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_SpatialAdaptiveQPLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_SpatialAdaptiveQPLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_HorizontalDisparityAdjustment/title",
          "value": "kVTCompressionPropertyKey_HorizontalDisparityAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_HorizontalDisparityAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_HorizontalDisparityAdjustment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtcompressionpropertykey_suggestedlookaheadframecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtcompressionpropertykey_suggestedlookaheadframecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
