{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTDecompressionPropertyKey_RequestRAWOutput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTDecompressionPropertyKey_RequestRAWOutput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "code": [
            "@constant       kVTDecompressionPropertyKey_RequestRAWOutput",
            "@abstract",
            "\tFor decoders which produce RAW output, this property requests that the VTDecompressionSession provide output which has not been processed.",
            "@discussion",
            "\tWhen a decoder produces RAW output (signalled by kVTDecompressionPropertyKey_DecoderProducesRAWOutput) the VTDecompressionSession will automatically",
            "\tinvoke a VTRAWProcessingSession with default settings and emit processed frames by default, or when kVTDecompressionPropertyKey_RequestRAWOutput is set",
            "\tto kCFBooleanFalse.",
            "\tIf a client wants to run a VTRAWProcessingSession on the RAW output themselves in order to control the post-decode processing of the decoded CVPixelBuffers,",
            "\tthey must set kVTDecompressionPropertyKey_RequestRAWOutput to kCFBooleanTrue.",
            "\tIf kVTDecompressionPropertyKey_RequestRAWOutput has been enabled and the decoder produces RAW output, the VTDecompressionSession ",
            "\twill return CVPixelBuffers in the decoder's native RAW format.  Any destinationImageBufferAttributes set on the VTDecompressionSession will be ignored."
          ],
          "syntax": "not specified",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_decoderproducesrawoutput"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata": {
      "abstract": [
        {
          "text": "A key that indicates to generate per frame HDR Metadata and attach it to the resulting decoded pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_generateperframehdrdisplaymetadata"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties": {
      "abstract": [
        {
          "text": "Specific pixel transfer features to be used during decompression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelTransferProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PixelTransferProperties"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PixelTransferProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_pixeltransferproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_propagateperframehdrdisplaymetadata"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_RequestRAWOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_RequestRAWOutput",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_requestrawoutput"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_UsingGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecompressionPropertyKey_UsingGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTDecompressionPropertyKey_UsingGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtdecompressionpropertykey_usinggpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderspecification_preferreddecodergpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideodecoderspecification_requireddecodergpuregistryid"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Post-Decompression-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
      ],
      "title": "Post-Decompression Processing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTDecompressionPropertyKey_RequestRAWOutput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Post-Decompression-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PixelTransferProperties",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_UsingGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
              ],
              "title": "Post-Decompression Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata/title",
          "value": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_GeneratePerFrameHDRDisplayMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID/title",
          "value": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderSpecification_PreferredDecoderGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RequestRAWOutput/title",
          "value": "kVTDecompressionPropertyKey_RequestRAWOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_RequestRAWOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_RequestRAWOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata/title",
          "value": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PropagatePerFrameHDRDisplayMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_UsingGPURegistryID/title",
          "value": "kVTDecompressionPropertyKey_UsingGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_UsingGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_UsingGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID/title",
          "value": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoDecoderSpecification_RequiredDecoderGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_DecoderProducesRAWOutput/title",
          "value": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_DecoderProducesRAWOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_DecoderProducesRAWOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelTransferProperties/title",
          "value": "kVTDecompressionPropertyKey_PixelTransferProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTDecompressionPropertyKey_PixelTransferProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecompressionPropertyKey_PixelTransferProperties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtdecompressionpropertykey_requestrawoutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtdecompressionpropertykey_requestrawoutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
