{
  "abstract": [
    {
      "text": "Specifies that DolbyVision data should be generated and attached for each pixel buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTHDRPerFrameMetadataGenerationHDRFormatType",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType": {
      "abstract": [
        {
          "text": "The HDR format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        }
      ],
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationHDRFormatType",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationhdrformattype"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionRef": {
      "abstract": [
        {
          "text": "A mechanism for generating HDR Per Frame Metadata and attaching that metadata to a pixel buffer and the backing IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSessionRef"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSessionRef",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsessionref"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision": {
      "abstract": [
        {
          "text": "Specifies that DolbyVision data should be generated and attached for each pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvthdrperframemetadatagenerationhdrformattype_dolbyvision"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats": {
      "abstract": [
        {
          "text": "Specifies an array of HDR formats to generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
        }
      ],
      "role": "symbol",
      "title": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvthdrperframemetadatagenerationoptionskey_hdrformats"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionRef",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
      ],
      "title": "Data types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/title",
          "value": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats/title",
          "value": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvthdrperframemetadatagenerationhdrformattype_dolbyvision"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
