{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kVTPropertyNotSupportedErr@kVTPropertyReadOnlyErr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTPropertyReadOnlyErr"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTPropertyReadOnlyErr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTPropertyReadOnlyErr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTPropertyReadOnlyErr"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTAllocationFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTAllocationFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTAllocationFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtallocationfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionImageRotationFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionImageRotationFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTColorCorrectionImageRotationFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcolorcorrectionimagerotationfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionPixelTransferFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTColorCorrectionPixelTransferFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTColorCorrectionPixelTransferFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcolorcorrectionpixeltransferfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTColorSyncTransformConvertFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTColorSyncTransformConvertFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTColorSyncTransformConvertFailedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcolorsynctransformconvertfailederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateColorCorrectionDataErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateColorCorrectionDataErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotCreateColorCorrectionDataErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotcreatecolorcorrectiondataerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateInstanceErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotCreateInstanceErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotCreateInstanceErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotcreateinstanceerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindTemporalFilterErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindTemporalFilterErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindTemporalFilterErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindtemporalfiltererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoDecoderErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoDecoderErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindVideoDecoderErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindvideodecodererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoEncoderErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotFindVideoEncoderErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotFindVideoEncoderErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotfindvideoencodererr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCouldNotOutputTaggedBufferGroupErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCouldNotOutputTaggedBufferGroupErr"
        }
      ],
      "role": "symbol",
      "title": "kVTCouldNotOutputTaggedBufferGroupErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcouldnotoutputtaggedbuffergrouperr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTFormatDescriptionChangeNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTFormatDescriptionChangeNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTFormatDescriptionChangeNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtformatdescriptionchangenotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeRangeErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeRangeErr"
        }
      ],
      "role": "symbol",
      "title": "kVTFrameSiloInvalidTimeRangeErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtframesiloinvalidtimerangeerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeStampErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTFrameSiloInvalidTimeStampErr"
        }
      ],
      "role": "symbol",
      "title": "kVTFrameSiloInvalidTimeStampErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtframesiloinvalidtimestamperr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTImageRotationNotSupportedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTImageRotationNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "kVTImageRotationNotSupportedErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtimagerotationnotsupportederr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTInsufficientSourceColorDataErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTInsufficientSourceColorDataErr"
        }
      ],
      "role": "symbol",
      "title": "kVTInsufficientSourceColorDataErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtinsufficientsourcecolordataerr"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyReadOnlyErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadOnlyErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyReadOnlyErr"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyReadOnlyErr",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyreadonlyerr"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr"
      ],
      "title": "Errors Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTPropertyReadOnlyErr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyReadOnlyErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTAllocationFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionImageRotationFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorCorrectionPixelTransferFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTColorSyncTransformConvertFailedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateColorCorrectionDataErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotCreateInstanceErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindTemporalFilterErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoDecoderErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotFindVideoEncoderErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCouldNotOutputTaggedBufferGroupErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFormatDescriptionChangeNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeRangeErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTFrameSiloInvalidTimeStampErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTImageRotationNotSupportedErr",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTInsufficientSourceColorDataErr"
              ],
              "title": "Errors Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kVTPropertyReadOnlyErr"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindTemporalFilterErr/title",
          "value": "kVTCouldNotFindTemporalFilterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindTemporalFilterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindTemporalFilterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTInsufficientSourceColorDataErr/title",
          "value": "kVTInsufficientSourceColorDataErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTInsufficientSourceColorDataErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTInsufficientSourceColorDataErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFormatDescriptionChangeNotSupportedErr/title",
          "value": "kVTFormatDescriptionChangeNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFormatDescriptionChangeNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTFormatDescriptionChangeNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotOutputTaggedBufferGroupErr/title",
          "value": "kVTCouldNotOutputTaggedBufferGroupErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotOutputTaggedBufferGroupErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotOutputTaggedBufferGroupErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTImageRotationNotSupportedErr/title",
          "value": "kVTImageRotationNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTImageRotationNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTImageRotationNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateInstanceErr/title",
          "value": "kVTCouldNotCreateInstanceErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateInstanceErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotCreateInstanceErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTAllocationFailedErr/title",
          "value": "kVTAllocationFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTAllocationFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTAllocationFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorSyncTransformConvertFailedErr/title",
          "value": "kVTColorSyncTransformConvertFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorSyncTransformConvertFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTColorSyncTransformConvertFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionImageRotationFailedErr/title",
          "value": "kVTColorCorrectionImageRotationFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionImageRotationFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTColorCorrectionImageRotationFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeStampErr/title",
          "value": "kVTFrameSiloInvalidTimeStampErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeStampErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTFrameSiloInvalidTimeStampErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionPixelTransferFailedErr/title",
          "value": "kVTColorCorrectionPixelTransferFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTColorCorrectionPixelTransferFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTColorCorrectionPixelTransferFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoEncoderErr/title",
          "value": "kVTCouldNotFindVideoEncoderErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoEncoderErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindVideoEncoderErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeRangeErr/title",
          "value": "kVTFrameSiloInvalidTimeRangeErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTFrameSiloInvalidTimeRangeErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTFrameSiloInvalidTimeRangeErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoDecoderErr/title",
          "value": "kVTCouldNotFindVideoDecoderErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotFindVideoDecoderErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotFindVideoDecoderErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadOnlyErr/title",
          "value": "kVTPropertyReadOnlyErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadOnlyErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyReadOnlyErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateColorCorrectionDataErr/title",
          "value": "kVTCouldNotCreateColorCorrectionDataErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCouldNotCreateColorCorrectionDataErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCouldNotCreateColorCorrectionDataErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtpropertyreadonlyerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtpropertyreadonlyerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
