{
  "abstract": [
    {
      "text": "A key that specifies the amount of rotation in degrees.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTPixelRotationPropertyKey_Rotation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTPixelRotationPropertyKey_Rotation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTPixelRotationPropertyKey_Rotation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTPixelRotationPropertyKey_Rotation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_Rotation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation": {
      "abstract": [
        {
          "text": "A key that specifies a horizontal flip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationpropertykey_fliphorizontalorientation"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation": {
      "abstract": [
        {
          "text": "A key that specifies a vertical flip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationPropertyKey_FlipVerticalOrientation",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationpropertykey_flipverticalorientation"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation": {
      "abstract": [
        {
          "text": "A key that specifies the amount of rotation in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_Rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_Rotation"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationPropertyKey_Rotation",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationpropertykey_rotation"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_0": {
      "abstract": [
        {
          "text": "A constant that indicates a rotation of 0 degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTRotation_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTRotation_0"
        }
      ],
      "role": "symbol",
      "title": "kVTRotation_0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrotation_0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_180": {
      "abstract": [
        {
          "text": "A constant that indicates a rotation of 180 degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTRotation_180"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_180",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTRotation_180"
        }
      ],
      "role": "symbol",
      "title": "kVTRotation_180",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrotation_180"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CCW90": {
      "abstract": [
        {
          "text": "A constant that indicates a counterclockwise rotation of 90 degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTRotation_CCW90"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CCW90",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTRotation_CCW90"
        }
      ],
      "role": "symbol",
      "title": "kVTRotation_CCW90",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrotation_ccw90"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CW90": {
      "abstract": [
        {
          "text": "A constant that indicates a clockwise rotation of 90 degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTRotation_CW90"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CW90",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTRotation_CW90"
        }
      ],
      "role": "symbol",
      "title": "kVTRotation_CW90",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrotation_cw90"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
      ],
      "title": "Configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Rotations",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CW90",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_180",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CCW90"
      ],
      "title": "Rotations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTPixelRotationPropertyKey_Rotation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_Rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Rotations",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CW90",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_180",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRotation_CCW90"
              ],
              "title": "Rotations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
              ],
              "title": "Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTPixelRotationPropertyKey_Rotation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_Rotation/title",
          "value": "kVTPixelRotationPropertyKey_Rotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_Rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_Rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_180/title",
          "value": "kVTRotation_180"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_180/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTRotation_180"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipVerticalOrientation/title",
          "value": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipVerticalOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_CCW90/title",
          "value": "kVTRotation_CCW90"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_CCW90/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTRotation_CCW90"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_0/title",
          "value": "kVTRotation_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTRotation_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_CW90/title",
          "value": "kVTRotation_CW90"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRotation_CW90/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTRotation_CW90"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipHorizontalOrientation/title",
          "value": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipHorizontalOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtpixelrotationpropertykey_rotation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtpixelrotationpropertykey_rotation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
