{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_AutoLevel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTProfileLevel_H264_Baseline_AutoLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTProfileLevel_H264_Baseline_AutoLevel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_1_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_1_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_1_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_1_3"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_1_3",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_1_3"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_3_0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_3_0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_3_0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_3_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_3_1"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_3_1",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_3_1"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_3_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_3_2"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_3_2",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_3_2"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_4_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_4_0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_4_0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_4_0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_4_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_4_1"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_4_1",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_4_1"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_4_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_4_2"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_4_2",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_4_2"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_5_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_5_0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_5_0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_5_0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_5_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_5_1"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_5_1",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_5_1"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_5_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_5_2"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_5_2",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_5_2"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_AutoLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_AutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Baseline_AutoLevel",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_autolevel"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_constrainedbaseline_autolevel"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedHigh_AutoLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_ConstrainedHigh_AutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedHigh_AutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_ConstrainedHigh_AutoLevel"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_ConstrainedHigh_AutoLevel",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_constrainedhigh_autolevel"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_5_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Extended_5_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_5_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Extended_5_0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Extended_5_0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_extended_5_0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_AutoLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Extended_AutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_AutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_Extended_AutoLevel"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_Extended_AutoLevel",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_extended_autolevel"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_High_3_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_High_3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_High_3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_H264_High_3_0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_H264_High_3_0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_h264_high_3_0"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "H264",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_1_3",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_1",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_2",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_1",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_2",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_1",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_2",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedHigh_AutoLevel",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_5_0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_AutoLevel",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_High_3_0"
      ],
      "title": "H.264"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTProfileLevel_H264_Baseline_AutoLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "H264",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_1_3",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_1",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_3_2",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_1",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_4_2",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_1",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Baseline_5_2",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_ConstrainedHigh_AutoLevel",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_5_0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_Extended_AutoLevel",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_H264_High_3_0"
              ],
              "title": "H.264"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_4_2/title",
          "value": "kVTProfileLevel_H264_Baseline_4_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_4_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_4_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_4_0/title",
          "value": "kVTProfileLevel_H264_Baseline_4_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_4_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_4_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_ConstrainedHigh_AutoLevel/title",
          "value": "kVTProfileLevel_H264_ConstrainedHigh_AutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_ConstrainedHigh_AutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_ConstrainedHigh_AutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_5_0/title",
          "value": "kVTProfileLevel_H264_Baseline_5_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_5_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_5_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Extended_AutoLevel/title",
          "value": "kVTProfileLevel_H264_Extended_AutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Extended_AutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Extended_AutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_5_2/title",
          "value": "kVTProfileLevel_H264_Baseline_5_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_5_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_5_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Extended_5_0/title",
          "value": "kVTProfileLevel_H264_Extended_5_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Extended_5_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Extended_5_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_5_1/title",
          "value": "kVTProfileLevel_H264_Baseline_5_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_5_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_5_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_3_2/title",
          "value": "kVTProfileLevel_H264_Baseline_3_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_3_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_3_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel/title",
          "value": "kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_ConstrainedBaseline_AutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_High_3_0/title",
          "value": "kVTProfileLevel_H264_High_3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_High_3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_High_3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_3_0/title",
          "value": "kVTProfileLevel_H264_Baseline_3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_1_3/title",
          "value": "kVTProfileLevel_H264_Baseline_1_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_1_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_1_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_3_1/title",
          "value": "kVTProfileLevel_H264_Baseline_3_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_3_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_3_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_4_1/title",
          "value": "kVTProfileLevel_H264_Baseline_4_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_4_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_4_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_AutoLevel/title",
          "value": "kVTProfileLevel_H264_Baseline_AutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_H264_Baseline_AutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_H264_Baseline_AutoLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_autolevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtprofilelevel_h264_baseline_autolevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
