{
  "abstract": [
    {
      "text": "Dictionary key to access the minimum value of a property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTPropertySupportedValueMinimumKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTPropertySupportedValueMinimumKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTPropertySupportedValueMinimumKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTPropertySupportedValueMinimumKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMinimumKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The associated value is a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
      "kind": "article",
      "role": "article",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber-rjd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey": {
      "abstract": [
        {
          "text": "Dictionary key to access any documentation intended for developers only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyDocumentationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyDocumentationKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyDocumentationKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertydocumentationkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the read/write status of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyReadWriteStatusKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyReadWriteStatusKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyReadWriteStatusKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyreadwritestatuskey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the serializable status of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyShouldBeSerializedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyShouldBeSerializedKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyShouldBeSerializedKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyshouldbeserializedkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the array of of supported values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueListKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueListKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueListKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvaluelistkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the maximum value of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMaximumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMaximumKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueMaximumKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvaluemaximumkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the minimum value of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMinimumKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueMinimumKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvalueminimumkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey": {
      "abstract": [
        {
          "text": "Dictionary key used to access the property type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyTypeKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertytypekey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants": {
      "abstract": [
        {
          "text": "Supported constant values for ",
          "type": "text"
        },
        {
          "code": "kVTPropertyTypeKey",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Type Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/property-type-constants"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants": {
      "abstract": [
        {
          "text": "Supported constant values for ",
          "type": "text"
        },
        {
          "code": "kVTPropertyReadWriteStatusKey",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Read/Write Status Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/read-write-status-constants"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMinimumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTPropertySupportedValueMinimumKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueListKey/title",
          "value": "kVTPropertySupportedValueListKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueListKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueListKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadWriteStatusKey/title",
          "value": "kVTPropertyReadWriteStatusKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadWriteStatusKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyReadWriteStatusKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyDocumentationKey/title",
          "value": "kVTPropertyDocumentationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyDocumentationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyDocumentationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyTypeKey/title",
          "value": "kVTPropertyTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyShouldBeSerializedKey/title",
          "value": "kVTPropertyShouldBeSerializedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyShouldBeSerializedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyShouldBeSerializedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMinimumKey/title",
          "value": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMinimumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMinimumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMaximumKey/title",
          "value": "kVTPropertySupportedValueMaximumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMaximumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMaximumKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtpropertysupportedvalueminimumkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtpropertysupportedvalueminimumkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
