{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTProfileLevel_MP4V_Main_L3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTProfileLevel_MP4V_Main_L3"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTProfileLevel_MP4V_Main_L3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTProfileLevel_MP4V_Main_L3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Main_L3"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_AdvancedSimple_L0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_advancedsimple_l0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L1"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_AdvancedSimple_L1",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_advancedsimple_l1"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L2"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_AdvancedSimple_L2",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_advancedsimple_l2"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L3"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_AdvancedSimple_L3",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_advancedsimple_l3"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_AdvancedSimple_L4"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_AdvancedSimple_L4",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_advancedsimple_l4"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Main_L2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Main_L2"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Main_L2",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_main_l2"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Main_L3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Main_L3"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Main_L3",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_main_l3"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Main_L4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Main_L4"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Main_L4",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_main_l4"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L0"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Simple_L0",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_simple_l0"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L1"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Simple_L1",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_simple_l1"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L2"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Simple_L2",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_simple_l2"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTProfileLevel_MP4V_Simple_L3"
        }
      ],
      "role": "symbol",
      "title": "kVTProfileLevel_MP4V_Simple_L3",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtprofilelevel_mp4v_simple_l3"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "MP4V",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L1",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L2",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L3",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L0",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L1",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L2",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L3",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L4",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L2",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L4"
      ],
      "title": "MP4V"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTProfileLevel_MP4V_Main_L3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Main_L3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "MP4V",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L1",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L2",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Simple_L3",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L0",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L1",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L2",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L3",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_AdvancedSimple_L4",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L2",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTProfileLevel_MP4V_Main_L4"
              ],
              "title": "MP4V"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTProfileLevel_MP4V_Main_L3"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L3/title",
          "value": "kVTProfileLevel_MP4V_Simple_L3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Simple_L3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L4/title",
          "value": "kVTProfileLevel_MP4V_AdvancedSimple_L4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_AdvancedSimple_L4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Main_L4/title",
          "value": "kVTProfileLevel_MP4V_Main_L4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Main_L4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Main_L4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L1/title",
          "value": "kVTProfileLevel_MP4V_AdvancedSimple_L1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_AdvancedSimple_L1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Main_L3/title",
          "value": "kVTProfileLevel_MP4V_Main_L3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Main_L3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Main_L3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Main_L2/title",
          "value": "kVTProfileLevel_MP4V_Main_L2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Main_L2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Main_L2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L2/title",
          "value": "kVTProfileLevel_MP4V_AdvancedSimple_L2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_AdvancedSimple_L2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L0/title",
          "value": "kVTProfileLevel_MP4V_Simple_L0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Simple_L0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L2/title",
          "value": "kVTProfileLevel_MP4V_Simple_L2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Simple_L2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L3/title",
          "value": "kVTProfileLevel_MP4V_AdvancedSimple_L3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_AdvancedSimple_L3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L1/title",
          "value": "kVTProfileLevel_MP4V_Simple_L1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_Simple_L1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_Simple_L1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L0/title",
          "value": "kVTProfileLevel_MP4V_AdvancedSimple_L0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTProfileLevel_MP4V_AdvancedSimple_L0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTProfileLevel_MP4V_AdvancedSimple_L0"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtprofilelevel_mp4v_main_l3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtprofilelevel_mp4v_main_l3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
