{
  "abstract": [
    {
      "text": "The color transfer function to be used for destination image buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationTransferFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTPixelTransferPropertyKey_DestinationTransferFunction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specifying this value may lead to performance degradation, as a color matching operation may need to be performed between the source and the destination.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "text": "doc://com.apple.documentation/documentation/coremedia/kcmformatdescriptionextension_transferfunction",
              "type": "text"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "code": "CMFormatDescription.h",
              "type": "codeVoice"
            },
            {
              "text": " for possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/downsampling-mode-constants": {
      "abstract": [
        {
          "text": "Supported constant values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DownsamplingMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/downsampling-mode-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Downsampling Mode Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/downsampling-mode-constants"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationCleanAperture": {
      "abstract": [
        {
          "text": "The clean aperture for destination image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationCleanAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationCleanAperture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationCleanAperture"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DestinationCleanAperture",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationcleanaperture"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationColorPrimaries": {
      "abstract": [
        {
          "text": "The color primaries to be used for destination image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationColorPrimaries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationColorPrimaries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationColorPrimaries"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DestinationColorPrimaries",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationcolorprimaries"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationICCProfile": {
      "abstract": [
        {
          "text": "The International Color Consortium (ICC) profile for destination image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationICCProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationICCProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationICCProfile"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DestinationICCProfile",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationiccprofile"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationPixelAspectRatio": {
      "abstract": [
        {
          "text": "The pixel aspect ratio for destination image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationPixelAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationPixelAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationPixelAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DestinationPixelAspectRatio",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationpixelaspectratio"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationTransferFunction": {
      "abstract": [
        {
          "text": "The color transfer function to be used for destination image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DestinationTransferFunction",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationtransferfunction"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationYCbCrMatrix": {
      "abstract": [
        {
          "text": "The color matrix to be used for YCbCr to RGB conversions involving the destination image buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationYCbCrMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationYCbCrMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DestinationYCbCrMatrix"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DestinationYCbCrMatrix",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationycbcrmatrix"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DownsamplingMode": {
      "abstract": [
        {
          "text": "The specific chroma downsampling technique to be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DownsamplingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DownsamplingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_DownsamplingMode"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_DownsamplingMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_downsamplingmode"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_RealTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_RealTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_RealTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_RealTime"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_RealTime",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_realtime"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_ScalingMode": {
      "abstract": [
        {
          "text": "Scaling mode for images during transfer between source and destination buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_ScalingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_ScalingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelTransferPropertyKey_ScalingMode"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelTransferPropertyKey_ScalingMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixeltransferpropertykey_scalingmode"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/scaling-mode-constants": {
      "abstract": [
        {
          "text": "Supported constant values for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_ScalingMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/scaling-mode-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scaling Mode Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/scaling-mode-constants"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_ScalingMode",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/scaling-mode-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationCleanAperture",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationPixelAspectRatio",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DownsamplingMode",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/downsampling-mode-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationColorPrimaries",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationICCProfile",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationYCbCrMatrix",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_RealTime"
      ],
      "title": "Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_ScalingMode",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/scaling-mode-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationCleanAperture",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationPixelAspectRatio",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DownsamplingMode",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/downsampling-mode-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationColorPrimaries",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationICCProfile",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_DestinationYCbCrMatrix",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelTransferPropertyKey_RealTime"
              ],
              "title": "Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationPixelAspectRatio/title",
          "value": "kVTPixelTransferPropertyKey_DestinationPixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationPixelAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationPixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationColorPrimaries/title",
          "value": "kVTPixelTransferPropertyKey_DestinationColorPrimaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationColorPrimaries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationColorPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationCleanAperture/title",
          "value": "kVTPixelTransferPropertyKey_DestinationCleanAperture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationCleanAperture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationCleanAperture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_RealTime/title",
          "value": "kVTPixelTransferPropertyKey_RealTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_RealTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_RealTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationYCbCrMatrix/title",
          "value": "kVTPixelTransferPropertyKey_DestinationYCbCrMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationYCbCrMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationYCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_ScalingMode/title",
          "value": "kVTPixelTransferPropertyKey_ScalingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_ScalingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_ScalingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationICCProfile/title",
          "value": "kVTPixelTransferPropertyKey_DestinationICCProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationICCProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationICCProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationTransferFunction/title",
          "value": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DestinationTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DestinationTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DownsamplingMode/title",
          "value": "kVTPixelTransferPropertyKey_DownsamplingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelTransferPropertyKey_DownsamplingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelTransferPropertyKey_DownsamplingMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationtransferfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtpixeltransferpropertykey_destinationtransferfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
