{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTVideoEncoderList_SupportsFrameReordering",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTVideoEncoderList_SupportsFrameReordering"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTVideoEncoderList_SupportsFrameReordering"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTVideoEncoderList_SupportsFrameReordering"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_SupportsFrameReordering"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlistoption_includestandarddefinitiondvencoders"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName": {
      "abstract": [
        {
          "text": "The encoder’s codec name key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecName"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_CodecName",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_codecname"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType": {
      "abstract": [
        {
          "text": "The encoder’s codec type key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecType"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_CodecType",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_codectype"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName": {
      "abstract": [
        {
          "text": "The encoder’s display name key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_DisplayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_DisplayName"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_DisplayName",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_displayname"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID": {
      "abstract": [
        {
          "text": "A key that identifies the encoder ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_EncoderID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_encoderid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName": {
      "abstract": [
        {
          "text": "A key for the encoder’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderName"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_EncoderName",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_encodername"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_GPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_GPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_GPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_gpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_InstanceLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_InstanceLimit"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_InstanceLimit",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_instancelimit"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_IsHardwareAccelerated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_IsHardwareAccelerated"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_IsHardwareAccelerated",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_ishardwareaccelerated"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_PerformanceRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_PerformanceRating"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_PerformanceRating",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_performancerating"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_QualityRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_QualityRating"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_QualityRating",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_qualityrating"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportedSelectionProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportedSelectionProperties"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_SupportedSelectionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_supportedselectionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportsFrameReordering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportsFrameReordering"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_SupportsFrameReordering",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_supportsframereordering"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsMultiPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportsMultiPass"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsMultiPass",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTVideoEncoderList_SupportsMultiPass",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_supportsmultipass"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encoder-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
      ],
      "title": "Encoder Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTVideoEncoderList_SupportsFrameReordering"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_SupportsFrameReordering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encoder-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsMultiPass",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
              ],
              "title": "Encoder Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTVideoEncoderList_SupportsFrameReordering"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_GPURegistryID/title",
          "value": "kVTVideoEncoderList_GPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_GPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_GPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecName/title",
          "value": "kVTVideoEncoderList_CodecName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_CodecName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_IsHardwareAccelerated/title",
          "value": "kVTVideoEncoderList_IsHardwareAccelerated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_IsHardwareAccelerated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_IsHardwareAccelerated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_QualityRating/title",
          "value": "kVTVideoEncoderList_QualityRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_QualityRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_QualityRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_InstanceLimit/title",
          "value": "kVTVideoEncoderList_InstanceLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_InstanceLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_InstanceLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportedSelectionProperties/title",
          "value": "kVTVideoEncoderList_SupportedSelectionProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportedSelectionProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_SupportedSelectionProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecType/title",
          "value": "kVTVideoEncoderList_CodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_CodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_DisplayName/title",
          "value": "kVTVideoEncoderList_DisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_DisplayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_DisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportsFrameReordering/title",
          "value": "kVTVideoEncoderList_SupportsFrameReordering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportsFrameReordering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_SupportsFrameReordering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderID/title",
          "value": "kVTVideoEncoderList_EncoderID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_EncoderID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders/title",
          "value": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_PerformanceRating/title",
          "value": "kVTVideoEncoderList_PerformanceRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_PerformanceRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_PerformanceRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderName/title",
          "value": "kVTVideoEncoderList_EncoderName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_EncoderName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtvideoencoderlist_supportsframereordering"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtvideoencoderlist_supportsframereordering"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
