{
  "abstract": [
    {
      "text": "A Boolean value indicating whether hardware-accelerated video encoding is allowed, if available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key is set in the ",
              "type": "text"
            },
            {
              "code": "encoderSpecification",
              "type": "codeVoice"
            },
            {
              "text": " passed in to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSessionCreate(allocator:width:height:codecType:encoderSpecification:imageBufferAttributes:compressedDataAllocator:outputCallback:refcon:compressionSessionOut:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".  Set it to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to allow hardware-accelerated encoding.  To specifically prevent hardware encoding, set this property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This setting is useful for clients doing realtime encoding operations because it allows VideoToolbox to choose the optimal encoding path.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSessionCreate(allocator:width:height:codecType:encoderSpecification:imageBufferAttributes:compressedDataAllocator:outputCallback:refcon:compressionSessionOut:)": {
      "abstract": [
        {
          "text": "Creates an object that compresses video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTCompressionSessionCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "codecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "encoderSpecification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "imageBufferAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "compressedDataAllocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "outputCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTCompressionOutputCallback",
          "text": "VTCompressionOutputCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "compressionSessionOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTCompressionSessionRef",
          "text": "VTCompressionSession"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCompressionSessionCreate(allocator:width:height:codecType:encoderSpecification:imageBufferAttributes:compressedDataAllocator:outputCallback:refcon:compressionSessionOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTCompressionSessionCreate"
        }
      ],
      "role": "symbol",
      "title": "VTCompressionSessionCreate(allocator:width:height:codecType:encoderSpecification:imageBufferAttributes:compressedDataAllocator:outputCallback:refcon:compressionSessionOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcompressionsessioncreate(allocator:width:height:codectype:encoderspecification:imagebufferattributes:compresseddataallocator:outputcallback:refcon:compressionsessionout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SupportsBaseFrameQP": {
      "abstract": [
        {
          "text": "A value that indicates whether the encoder supports base frame QP requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_SupportsBaseFrameQP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SupportsBaseFrameQP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_SupportsBaseFrameQP"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_SupportsBaseFrameQP",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_supportsbaseframeqp"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_UsingGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_UsingGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_UsingGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_usinggpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a hardware-accelerated video encoder is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder"
        }
      ],
      "role": "symbol",
      "title": "kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtcompressionpropertykey_usinghardwareacceleratedvideoencoder"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether hardware-accelerated video encoding is allowed, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderspecification_enablehardwareacceleratedvideoencoder"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderspecification_preferredencodergpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether hardware-accelerated encoding is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderspecification_requirehardwareacceleratedvideoencoder"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderspecification_requiredencodergpuregistryid"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Hardware-Acceleration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SupportsBaseFrameQP",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID"
      ],
      "title": "Hardware Acceleration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Hardware-Acceleration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_SupportsBaseFrameQP",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID"
              ],
              "title": "Hardware Acceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_UsingGPURegistryID/title",
          "value": "kVTCompressionPropertyKey_UsingGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_UsingGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_UsingGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCompressionSessionCreate(allocator:width:height:codecType:encoderSpecification:imageBufferAttributes:compressedDataAllocator:outputCallback:refcon:compressionSessionOut:)/title",
          "value": "VTCompressionSessionCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCompressionSessionCreate(allocator:width:height:codecType:encoderSpecification:imageBufferAttributes:compressedDataAllocator:outputCallback:refcon:compressionSessionOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTCompressionSessionCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID/title",
          "value": "kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_RequiredEncoderGPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder/title",
          "value": "kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_RequireHardwareAcceleratedVideoEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_SupportsBaseFrameQP/title",
          "value": "kVTCompressionPropertyKey_SupportsBaseFrameQP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_SupportsBaseFrameQP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_SupportsBaseFrameQP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder/title",
          "value": "kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTCompressionPropertyKey_UsingHardwareAcceleratedVideoEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder/title",
          "value": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_EnableHardwareAcceleratedVideoEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID/title",
          "value": "kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderSpecification_PreferredEncoderGPURegistryID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/kvtvideoencoderspecification_enablehardwareacceleratedvideoencoder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/kvtvideoencoderspecification_enablehardwareacceleratedvideoencoder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
