{
  "abstract": [
    {
      "text": "Properties used to configure a VideoToolbox pixel rotation session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/pixel-rotation-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Pixel Rotation Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection": {
      "abstract": [
        {
          "text": "An object that rotates source pixel buffers to destination pixel buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTPixelRotationSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation": {
      "abstract": [
        {
          "text": "A key that specifies a horizontal flip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationpropertykey_fliphorizontalorientation"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation": {
      "abstract": [
        {
          "text": "A key that specifies a vertical flip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationPropertyKey_FlipVerticalOrientation",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationpropertykey_flipverticalorientation"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation": {
      "abstract": [
        {
          "text": "A key that specifies the amount of rotation in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_Rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPixelRotationPropertyKey_Rotation"
        }
      ],
      "role": "symbol",
      "title": "kVTPixelRotationPropertyKey_Rotation",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpixelrotationpropertykey_rotation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Configuration",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
      ],
      "title": "Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_Rotation",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipVerticalOrientation",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
              ],
              "title": "Configuration"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipHorizontalOrientation/title",
          "value": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipHorizontalOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_FlipHorizontalOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipVerticalOrientation/title",
          "value": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_FlipVerticalOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_FlipVerticalOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_Rotation/title",
          "value": "kVTPixelRotationPropertyKey_Rotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPixelRotationPropertyKey_Rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPixelRotationPropertyKey_Rotation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/pixel-rotation-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/pixel-rotation-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
