{
  "abstract": [
    {
      "text": "Supported constant values for ",
      "type": "text"
    },
    {
      "code": "kVTPropertyTypeKey",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Property Type Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection": {
      "abstract": [
        {
          "text": "An abstract object that provides the common interface to configure VideoToolbox session objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey": {
      "abstract": [
        {
          "text": "Dictionary key to access any documentation intended for developers only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyDocumentationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyDocumentationKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyDocumentationKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertydocumentationkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the read/write status of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyReadWriteStatusKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyReadWriteStatusKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyReadWriteStatusKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyreadwritestatuskey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the serializable status of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyShouldBeSerializedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyShouldBeSerializedKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyShouldBeSerializedKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyshouldbeserializedkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the array of of supported values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueListKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueListKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueListKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvaluelistkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the maximum value of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMaximumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMaximumKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueMaximumKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvaluemaximumkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the minimum value of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMinimumKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueMinimumKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvalueminimumkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey": {
      "abstract": [
        {
          "text": "Dictionary key used to access the property type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyTypeKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertytypekey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Boolean": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyType_Boolean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Boolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyType_Boolean"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyType_Boolean",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertytype_boolean"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Enumeration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyType_Enumeration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Enumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyType_Enumeration"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyType_Enumeration",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertytype_enumeration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Number": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyType_Number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Number",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyType_Number"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyType_Number",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertytype_number"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants": {
      "abstract": [
        {
          "text": "Supported constant values for ",
          "type": "text"
        },
        {
          "code": "kVTPropertyReadWriteStatusKey",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Read/Write Status Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/read-write-status-constants"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants": {
      "abstract": [
        {
          "text": "Property dictionary key and constant values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supported Property Dictionary Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/supported-dictionary-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey"
      ],
      "title": "Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Property-Types",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Boolean",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Enumeration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Number"
      ],
      "title": "Property Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Property-Types",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Boolean",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Enumeration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyType_Number"
              ],
              "title": "Property Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyType_Boolean/title",
          "value": "kVTPropertyType_Boolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyType_Boolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyType_Boolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyDocumentationKey/title",
          "value": "kVTPropertyDocumentationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyDocumentationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyDocumentationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMinimumKey/title",
          "value": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMinimumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMinimumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyShouldBeSerializedKey/title",
          "value": "kVTPropertyShouldBeSerializedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyShouldBeSerializedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyShouldBeSerializedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadWriteStatusKey/title",
          "value": "kVTPropertyReadWriteStatusKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadWriteStatusKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyReadWriteStatusKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyType_Number/title",
          "value": "kVTPropertyType_Number"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyType_Number/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyType_Number"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyType_Enumeration/title",
          "value": "kVTPropertyType_Enumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyType_Enumeration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyType_Enumeration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyTypeKey/title",
          "value": "kVTPropertyTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueListKey/title",
          "value": "kVTPropertySupportedValueListKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueListKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueListKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMaximumKey/title",
          "value": "kVTPropertySupportedValueMaximumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMaximumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMaximumKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/property-type-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/property-type-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
