{
  "abstract": [
    {
      "text": "Properties that you use to configure a RAW processing session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RAW Processing Properties"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties": {
      "abstract": [
        {
          "text": "Returns information about the Media Extension RAW processor supporting the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTCopyRAWProcessorExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTCopyRAWProcessorExtensionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyrawprocessorextensionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters": {
      "abstract": [
        {
          "text": "Copies an array of dictionaries describing the parameters provided by the RAW Processor for frame processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCopyProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCopyProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncopyprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters": {
      "abstract": [
        {
          "text": "Sets a collection of RAW Processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionSetProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionSetProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionsetprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessorExtensionProperties(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRAWProcessorExtensionProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessorExtensionProperties(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessorExtensionProperties(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessorextensionproperties(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_MetalDeviceRegistryID": {
      "abstract": [
        {
          "text": "This property requests that the Metal device corresponding to the specified registryID be used for any Metal related processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingPropertyKey_MetalDeviceRegistryID"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_MetalDeviceRegistryID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingPropertyKey_MetalDeviceRegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingpropertykey_metaldeviceregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_OutputColorAttachments": {
      "abstract": [
        {
          "text": "The color-related image buffer keys and values that will be attachments to the returned pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingPropertyKey_OutputColorAttachments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_OutputColorAttachments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingPropertyKey_OutputColorAttachments"
        }
      ],
      "role": "symbol",
      "title": "kVTRAWProcessingPropertyKey_OutputColorAttachments",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingpropertykey_outputcolorattachments"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters": {
      "abstract": [
        {
          "text": "Parameters to set on a RAW processing session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RAW processing parameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/raw-processing-parameters"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters"
      ],
      "title": "Configuring a session"
    }
  ],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_OutputColorAttachments"
      ],
      "title": "Properties"
    },
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessorExtensionProperties(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_MetalDeviceRegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingPropertyKey_OutputColorAttachments"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-session",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties"
              ],
              "title": "Configuring a session"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRAWProcessingPropertyKey_OutputColorAttachments/title",
          "value": "kVTRAWProcessingPropertyKey_OutputColorAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTRAWProcessingPropertyKey_OutputColorAttachments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTRAWProcessingPropertyKey_OutputColorAttachments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/raw-processing-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/raw-processing-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
