{
  "abstract": [
    {
      "text": "Parameters to set on a RAW processing session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RAW processing parameters"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties": {
      "abstract": [
        {
          "text": "Returns information about the Media Extension RAW processor supporting the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTCopyRAWProcessorExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTCopyRAWProcessorExtensionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyrawprocessorextensionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters": {
      "abstract": [
        {
          "text": "Copies an array of dictionaries describing the parameters provided by the RAW Processor for frame processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCopyProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCopyProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncopyprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters": {
      "abstract": [
        {
          "text": "Sets a collection of RAW Processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionSetProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionSetProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionsetprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_Description": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a human-readable description for the element, suitable for displaying in a tooltip or other descriptive UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterListElement_Description"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_Description",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterListElement_Description",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameterlistelement_description"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_Label": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a human-readable label for the element, suitable for displaying in a list of options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterListElement_Label"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_Label",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterListElement_Label",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameterlistelement_label"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_ListElementID": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a number indicating the index of a list element parameter in a list in the processing parameters dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterListElement_ListElementID"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_ListElementID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterListElement_ListElementID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameterlistelement_listelementid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Boolean": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a string that indicates a Boolean parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterValueType_Boolean"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Boolean",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterValueType_Boolean",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparametervaluetype_boolean"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Float": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a string that indicates a floating-point parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterValueType_Float"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Float",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterValueType_Float",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparametervaluetype_float"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Integer": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a string that indicates an integer parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterValueType_Integer"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Integer",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterValueType_Integer",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparametervaluetype_integer"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_List": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a string that indicates a list parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterValueType_List"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_List",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterValueType_List",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparametervaluetype_list"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_SubGroup": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a string that indicates a subgroup parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameterValueType_SubGroup"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_SubGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameterValueType_SubGroup",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparametervaluetype_subgroup"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_CameraValue": {
      "abstract": [
        {
          "text": "The value corresponding to this key is the “As Shot” value for this parameter as originally captured by the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_CameraValue"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_CameraValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_CameraValue",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_cameravalue"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_CurrentValue": {
      "abstract": [
        {
          "text": "The value corresponding to this key is the currently configured value for this parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_CurrentValue"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_CurrentValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_CurrentValue",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_currentvalue"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Description": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a localized string with a description of the parameter suitable for display in a tooltip or other descriptive UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_Description"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Description",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_Description",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_description"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Enabled": {
      "abstract": [
        {
          "text": "The value corresponding to this key is Boolean indicating whether the parameter is enabled and can be modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_Enabled"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_Enabled",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_enabled"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_InitialValue": {
      "abstract": [
        {
          "text": "The value corresponding to this key is the initial value for this parameter as defined by the container and metadata provided at creation time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_InitialValue"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_InitialValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_InitialValue",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_initialvalue"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Key": {
      "abstract": [
        {
          "text": "The value corresponding to this key must match the identifier for one of the permitted processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_Key"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Key",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_Key",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_key"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_ListArray": {
      "abstract": [
        {
          "text": "The value corresponding to this key is an array of dictionaries describing each element in the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_ListArray"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_ListArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_ListArray",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_listarray"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_MaximumValue": {
      "abstract": [
        {
          "text": "The value corresponding to this key is the maximum value allowed for this parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_MaximumValue"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_MaximumValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_MaximumValue",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_maximumvalue"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_MinimumValue": {
      "abstract": [
        {
          "text": "The value corresponding to this key is the minimum value allowed for this parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_MinimumValue"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_MinimumValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_MinimumValue",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_minimumvalue"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Name": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a localized string  which can be displayed in UI representing this parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_Name"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Name",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_Name",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_name"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_NeutralValue": {
      "abstract": [
        {
          "text": "The value corresponding to this key is a neutral setting for the processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_NeutralValue"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_NeutralValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_NeutralValue",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_neutralvalue"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_SubGroup": {
      "abstract": [
        {
          "text": "The value corresponding to this key is an array of dictionaries representing the individual sub-parameters in this group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_SubGroup"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_SubGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_SubGroup",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_subgroup"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_ValueType": {
      "abstract": [
        {
          "text": "The value corresponding to this key is the type of the parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTRAWProcessingParameter_ValueType"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_ValueType",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTRAWProcessingParameter_ValueType",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtrawprocessingparameter_valuetype"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties": {
      "abstract": [
        {
          "text": "Properties that you use to configure a RAW processing session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RAW Processing Properties",
      "type": "topic",
      "url": "/documentation/videotoolbox/raw-processing-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties"
      ],
      "title": "Configuring a session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Parameters",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Key",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_Description",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_Label",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterListElement_ListElementID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Boolean",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Float",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_Integer",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_List",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameterValueType_SubGroup",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_CameraValue",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_CurrentValue",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Description",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Enabled",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_InitialValue",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_ListArray",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_MaximumValue",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_MinimumValue",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_Name",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_NeutralValue",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_SubGroup",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTRAWProcessingParameter_ValueType"
              ],
              "title": "Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-session",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties"
              ],
              "title": "Configuring a session"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/raw-processing-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/raw-processing-parameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
