{
  "abstract": [
    {
      "text": "Property dictionary key and constant values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Supported Property Dictionary Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Property dictionary key and constant values for a dictionary populated by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection": {
      "abstract": [
        {
          "text": "An abstract object that provides the common interface to configure VideoToolbox session objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)": {
      "abstract": [
        {
          "text": "Retrieves a property on a Video Toolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionCopyProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "valueOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionCopyProperty"
        }
      ],
      "role": "symbol",
      "title": "VTSessionCopyProperty(_:key:allocator:valueOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessioncopyproperty(_:key:allocator:valueout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)": {
      "abstract": [
        {
          "text": "Retrieves the set of serializable property keys and their current values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionCopySerializableProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "dictionaryOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionCopySerializableProperties"
        }
      ],
      "role": "symbol",
      "title": "VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessioncopyserializableproperties(_:allocator:dictionaryout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)": {
      "abstract": [
        {
          "text": "Retrieves a dictionary enumerating all the supported properties of a video toolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionCopySupportedPropertyDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedPropertyDictionaryOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionCopySupportedPropertyDictionary"
        }
      ],
      "role": "symbol",
      "title": "VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessioncopysupportedpropertydictionary(_:supportedpropertydictionaryout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey": {
      "abstract": [
        {
          "text": "Dictionary key to access any documentation intended for developers only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyDocumentationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyDocumentationKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyDocumentationKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertydocumentationkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the read/write status of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyReadWriteStatusKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyReadWriteStatusKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyReadWriteStatusKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyreadwritestatuskey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the serializable status of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyShouldBeSerializedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyShouldBeSerializedKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyShouldBeSerializedKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertyshouldbeserializedkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the array of of supported values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueListKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueListKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueListKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvaluelistkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the maximum value of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMaximumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMaximumKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueMaximumKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvaluemaximumkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey": {
      "abstract": [
        {
          "text": "Dictionary key to access the minimum value of a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertySupportedValueMinimumKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertySupportedValueMinimumKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertysupportedvalueminimumkey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey": {
      "abstract": [
        {
          "text": "Dictionary key used to access the property type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTPropertyTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTPropertyTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kVTPropertyTypeKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtpropertytypekey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants": {
      "abstract": [
        {
          "text": "Supported constant values for ",
          "type": "text"
        },
        {
          "code": "kVTPropertyTypeKey",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Type Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/property-type-constants"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants": {
      "abstract": [
        {
          "text": "Supported constant values for ",
          "type": "text"
        },
        {
          "code": "kVTPropertyReadWriteStatusKey",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Read/Write Status Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/read-write-status-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)"
      ],
      "title": "Getting Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyTypeKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/property-type-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyReadWriteStatusKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/read-write-status-constants",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyShouldBeSerializedKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueListKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMaximumKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertySupportedValueMinimumKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTPropertyDocumentationKey"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)"
              ],
              "title": "Getting Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadWriteStatusKey/title",
          "value": "kVTPropertyReadWriteStatusKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyReadWriteStatusKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyReadWriteStatusKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopyProperty(_:key:allocator:valueOut:)/title",
          "value": "VTSessionCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopyProperty(_:key:allocator:valueOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionCopyProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)/title",
          "value": "VTSessionCopySerializableProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionCopySerializableProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyDocumentationKey/title",
          "value": "kVTPropertyDocumentationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyDocumentationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyDocumentationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyShouldBeSerializedKey/title",
          "value": "kVTPropertyShouldBeSerializedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyShouldBeSerializedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyShouldBeSerializedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMinimumKey/title",
          "value": "kVTPropertySupportedValueMinimumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMinimumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMinimumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueListKey/title",
          "value": "kVTPropertySupportedValueListKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueListKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueListKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMaximumKey/title",
          "value": "kVTPropertySupportedValueMaximumKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertySupportedValueMaximumKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertySupportedValueMaximumKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)/title",
          "value": "VTSessionCopySupportedPropertyDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionCopySupportedPropertyDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyTypeKey/title",
          "value": "kVTPropertyTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTPropertyTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTPropertyTypeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/supported-dictionary-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/supported-dictionary-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
