{
  "abstract": [
    {
      "text": "Dictionary key constants to use to retrieve video encoder information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/video-encoder-list-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Video Encoder List Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these keys to pass to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)": {
      "abstract": [
        {
          "text": "Builds a list of supported properties and encoder ID for an encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTCopySupportedPropertyDictionaryForEncoder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "codecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "encoderSpecification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "encoderIDOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "externalParam",
          "text": "supportedPropertiesOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTCopySupportedPropertyDictionaryForEncoder"
        }
      ],
      "role": "symbol",
      "title": "VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopysupportedpropertydictionaryforencoder(width:height:codectype:encoderspecification:encoderidout:supportedpropertiesout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)": {
      "abstract": [
        {
          "text": "Builds a list of available video encoders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTCopyVideoEncoderList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTCopyVideoEncoderList"
        }
      ],
      "role": "symbol",
      "title": "VTCopyVideoEncoderList(_:_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyvideoencoderlist(_:_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the current system supports hardware decode for the specified codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTIsHardwareDecodeSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTIsHardwareDecodeSupported"
        }
      ],
      "role": "symbol",
      "title": "VTIsHardwareDecodeSupported(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtishardwaredecodesupported(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()": {
      "abstract": [
        {
          "text": "Loads decoders appropriate for the client’s professional video workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
        }
      ],
      "role": "symbol",
      "title": "VTRegisterProfessionalVideoWorkflowVideoDecoders()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtregisterprofessionalvideoworkflowvideodecoders()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()": {
      "abstract": [
        {
          "text": "Loads encoders appropriate for the client’s professional video workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
        }
      ],
      "role": "symbol",
      "title": "VTRegisterProfessionalVideoWorkflowVideoEncoders()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtregisterprofessionalvideoworkflowvideoencoders()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)": {
      "abstract": [
        {
          "text": "Registers a video decoder for the specified codec type, if one exists on the current system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRegisterSupplementalVideoDecoderIfAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRegisterSupplementalVideoDecoderIfAvailable"
        }
      ],
      "role": "symbol",
      "title": "VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtregistersupplementalvideodecoderifavailable(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlistoption_includestandarddefinitiondvencoders"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName": {
      "abstract": [
        {
          "text": "The encoder’s codec name key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecName"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_CodecName",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_codecname"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType": {
      "abstract": [
        {
          "text": "The encoder’s codec type key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_CodecType"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_CodecType",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_codectype"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName": {
      "abstract": [
        {
          "text": "The encoder’s display name key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_DisplayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_DisplayName"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_DisplayName",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_displayname"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID": {
      "abstract": [
        {
          "text": "A key that identifies the encoder ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_EncoderID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_encoderid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName": {
      "abstract": [
        {
          "text": "A key for the encoder’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_EncoderName"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_EncoderName",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_encodername"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_GPURegistryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_GPURegistryID"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_GPURegistryID",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_gpuregistryid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_InstanceLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_InstanceLimit"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_InstanceLimit",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_instancelimit"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_IsHardwareAccelerated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_IsHardwareAccelerated"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_IsHardwareAccelerated",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_ishardwareaccelerated"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_PerformanceRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_PerformanceRating"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_PerformanceRating",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_performancerating"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_QualityRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_QualityRating"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_QualityRating",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_qualityrating"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportedSelectionProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportedSelectionProperties"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_SupportedSelectionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_supportedselectionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportsFrameReordering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportsFrameReordering"
        }
      ],
      "role": "symbol",
      "title": "kVTVideoEncoderList_SupportsFrameReordering",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_supportsframereordering"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsMultiPass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTVideoEncoderList_SupportsMultiPass"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsMultiPass",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTVideoEncoderList_SupportsMultiPass",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtvideoencoderlist_supportsmultipass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Codec-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)"
      ],
      "title": "Codec Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Encoder-Keys",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
      ],
      "title": "Encoder Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Encoder-Keys",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_EncoderName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_DisplayName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecType",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_CodecName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_GPURegistryID",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_InstanceLimit",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_IsHardwareAccelerated",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_PerformanceRating",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_QualityRating",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportedSelectionProperties",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsFrameReordering",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderList_SupportsMultiPass",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
              ],
              "title": "Encoder Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Codec-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsHardwareDecodeSupported(_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoEncoders()",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterProfessionalVideoWorkflowVideoDecoders()",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRegisterSupplementalVideoDecoderIfAvailable(_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoEncoderList(_:_:)"
              ],
              "title": "Codec Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecType/title",
          "value": "kVTVideoEncoderList_CodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_CodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_PerformanceRating/title",
          "value": "kVTVideoEncoderList_PerformanceRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_PerformanceRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_PerformanceRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterSupplementalVideoDecoderIfAvailable(_:)/title",
          "value": "VTRegisterSupplementalVideoDecoderIfAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterSupplementalVideoDecoderIfAvailable(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRegisterSupplementalVideoDecoderIfAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoDecoders()/title",
          "value": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoDecoders()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRegisterProfessionalVideoWorkflowVideoDecoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_DisplayName/title",
          "value": "kVTVideoEncoderList_DisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_DisplayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_DisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_QualityRating/title",
          "value": "kVTVideoEncoderList_QualityRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_QualityRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_QualityRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_InstanceLimit/title",
          "value": "kVTVideoEncoderList_InstanceLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_InstanceLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_InstanceLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_IsHardwareAccelerated/title",
          "value": "kVTVideoEncoderList_IsHardwareAccelerated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_IsHardwareAccelerated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_IsHardwareAccelerated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders/title",
          "value": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderListOption_IncludeStandardDefinitionDVEncoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportsFrameReordering/title",
          "value": "kVTVideoEncoderList_SupportsFrameReordering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportsFrameReordering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_SupportsFrameReordering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)/title",
          "value": "VTCopySupportedPropertyDictionaryForEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopySupportedPropertyDictionaryForEncoder(width:height:codecType:encoderSpecification:encoderIDOut:supportedPropertiesOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTCopySupportedPropertyDictionaryForEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTIsHardwareDecodeSupported(_:)/title",
          "value": "VTIsHardwareDecodeSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTIsHardwareDecodeSupported(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTIsHardwareDecodeSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecName/title",
          "value": "kVTVideoEncoderList_CodecName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_CodecName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_CodecName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_GPURegistryID/title",
          "value": "kVTVideoEncoderList_GPURegistryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_GPURegistryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_GPURegistryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderName/title",
          "value": "kVTVideoEncoderList_EncoderName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_EncoderName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopyVideoEncoderList(_:_:)/title",
          "value": "VTCopyVideoEncoderList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTCopyVideoEncoderList(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTCopyVideoEncoderList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderID/title",
          "value": "kVTVideoEncoderList_EncoderID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_EncoderID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_EncoderID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoEncoders()/title",
          "value": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRegisterProfessionalVideoWorkflowVideoEncoders()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRegisterProfessionalVideoWorkflowVideoEncoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportedSelectionProperties/title",
          "value": "kVTVideoEncoderList_SupportedSelectionProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTVideoEncoderList_SupportedSelectionProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTVideoEncoderList_SupportedSelectionProperties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/video-encoder-list-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/video-encoder-list-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
