{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@VTDecompressionOutputCallbackRecord",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTDecompressionOutputCallbackRecord"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTDecompressionOutputCallbackRecord"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VTDecompressionOutputCallbackRecord"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags": {
      "abstract": [
        {
          "text": "Flags to pass to a decompression session and the video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeFrameFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags": {
      "abstract": [
        {
          "text": "Flags that provide information about the status of a decode operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeInfoFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeinfoflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback": {
      "abstract": [
        {
          "text": "The prototype for the callback invoked when frame decompression is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallback"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallback"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionOutputCallback",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallback"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallbackRecord"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallbackRecord"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionOutputCallbackRecord",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decompressionOutputCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionOutputCallback",
          "text": "VTDecompressionOutputCallback"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decompressionOutputCallback"
        }
      ],
      "role": "symbol",
      "title": "decompressionOutputCallback",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord/decompressionoutputcallback"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decompressionOutputRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decompressionOutputRefCon"
        }
      ],
      "role": "symbol",
      "title": "decompressionOutputRefCon",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord/decompressionoutputrefcon"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord/init()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/init(decompressionOutputCallback:decompressionOutputRefCon:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "decompressionOutputCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionOutputCallback",
          "text": "VTDecompressionOutputCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "decompressionOutputRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/init(decompressionOutputCallback:decompressionOutputRefCon:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(decompressionOutputCallback:decompressionOutputRefCon:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord/init(decompressionoutputcallback:decompressionoutputrefcon:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler": {
      "abstract": [
        {
          "text": "The prototype for the block invoked when frame decompression is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputHandler"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputHandler"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionOutputHandler",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputhandler"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession": {
      "abstract": [
        {
          "text": "A reference to a decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsession"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/init()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/init(decompressionOutputCallback:decompressionOutputRefCon:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputCallback",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputRefCon"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTDecompressionOutputCallbackRecord"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputCallback",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord/decompressionOutputRefCon"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTDecompressionOutputCallbackRecord"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/title",
          "value": "VTDecodeFrameFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallback/title",
          "value": "VTDecompressionOutputCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputHandler/title",
          "value": "VTDecompressionOutputHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord/title",
          "value": "VTDecompressionOutputCallbackRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord~1decompressionOutputCallback/title",
          "value": "decompressionOutputCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord~1decompressionOutputCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/title",
          "value": "VTDecodeInfoFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord~1decompressionOutputRefCon/title",
          "value": "decompressionOutputRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord~1decompressionOutputRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decompressionOutputRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/title",
          "value": "VTDecompressionSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
