{
  "abstract": [
    {
      "text": "The prototype for the callback invoked when frame decompression is complete.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@VTDecompressionOutputCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTDecompressionOutputCallback"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTDecompressionOutputCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "VTDecompressionOutputCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
              "text": "VTDecodeInfoFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVImageBufferRef",
              "text": "CVImageBuffer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The callback’s reference value, copied from the ",
                  "type": "text"
                },
                {
                  "code": "decompressionOutputRefCon",
                  "type": "codeVoice"
                },
                {
                  "text": " field of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "decompressionOutputRefCon"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The frame’s reference value, copied from the ",
                  "type": "text"
                },
                {
                  "code": "sourceFrameRefCon",
                  "type": "codeVoice"
                },
                {
                  "text": " argument to ",
                  "type": "text"
                },
                {
                  "code": "VTDecompressionSessionDecodeFrame",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sourceFrameRefCon"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "noErr",
                  "type": "codeVoice"
                },
                {
                  "text": " if decompression was successful; an error code if decompression was not successful.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "status"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Information about the decode operation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/asynchronous",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " bit may be set if the decode ran asynchronously.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/frameDropped",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " bit may be set if the frame was dropped.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "If the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/imageBufferModifiable",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " bit is set, it is safe for the client to modify the imageBuffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "infoFlags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The decompressed frame, if decompression was successful; otherwise, ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "The video decompressor may still be referencing the ",
                      "type": "text"
                    },
                    {
                      "code": "imageBuffer",
                      "type": "codeVoice"
                    },
                    {
                      "text": " returned in this callback if the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/imageBufferModifiable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " flag is not set.  Unless this flag is set, it is not safe to modify the returned ",
                      "type": "text"
                    },
                    {
                      "code": "imageBuffer",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "name": "Important",
              "style": "important",
              "type": "aside"
            }
          ],
          "name": "imageBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The frame’s presentation timestamp, which is determined by calling ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBufferGetOutputPresentationTimeStamp(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "; otherwise, ",
                  "type": "text"
                },
                {
                  "code": "kCMTimeInvalid",
                  "type": "codeVoice"
                },
                {
                  "text": " if the timestamp is not available.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "presentationTimeStamp"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The frame’s presentation duration, which is determined by calling ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBufferGetOutputDuration(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "; otherwise, ",
                  "type": "text"
                },
                {
                  "code": "kCMTimeInvalid",
                  "type": "codeVoice"
                },
                {
                  "text": " if the timestamp is not available.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "presentationDuration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you create a decompression session, you pass in a callback function to be called for decompressed frames.  This function is not necessarily called in display order.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBufferGetOutputDuration(_:)": {
      "abstract": [
        {
          "text": "Returns the output duration of a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBufferGetOutputDuration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "sbuf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBufferGetOutputDuration(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBufferGetOutputDuration(_:)",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBufferGetOutputDuration(_:)"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBufferGetOutputPresentationTimeStamp(_:)": {
      "abstract": [
        {
          "text": "Returns the output presentation timestamp of a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBufferGetOutputPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "sbuf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMSampleBufferGetOutputPresentationTimeStamp(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBufferGetOutputPresentationTimeStamp(_:)",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBufferGetOutputPresentationTimeStamp(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags": {
      "abstract": [
        {
          "text": "Flags to pass to a decompression session and the video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeFrameFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags": {
      "abstract": [
        {
          "text": "Flags that provide information about the status of a decode operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeInfoFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeinfoflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/asynchronous": {
      "abstract": [
        {
          "text": "A flag that indicates the decode operation ran asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asynchronous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/asynchronous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecodeInfo_Asynchronous"
        }
      ],
      "role": "symbol",
      "title": "asynchronous",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeinfoflags/asynchronous"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/frameDropped": {
      "abstract": [
        {
          "text": "A flag that indicates the decode operation dropped a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameDropped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/frameDropped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecodeInfo_FrameDropped"
        }
      ],
      "role": "symbol",
      "title": "frameDropped",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeinfoflags/framedropped"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/imageBufferModifiable": {
      "abstract": [
        {
          "text": "A flag that indicates the image buffer is safe to modify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageBufferModifiable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags/imageBufferModifiable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTDecodeInfo_ImageBufferModifiable"
        }
      ],
      "role": "symbol",
      "title": "imageBufferModifiable",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeinfoflags/imagebuffermodifiable"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback": {
      "abstract": [
        {
          "text": "The prototype for the callback invoked when frame decompression is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallback"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallback"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionOutputCallback",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallback"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallbackRecord"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputCallbackRecord"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionOutputCallbackRecord",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputcallbackrecord"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler": {
      "abstract": [
        {
          "text": "The prototype for the block invoked when frame decompression is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputHandler"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionOutputHandler"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionOutputHandler",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionoutputhandler"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession": {
      "abstract": [
        {
          "text": "A reference to a decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsession"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMTime": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTime",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTime"
    },
    "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef": {
      "abstract": [
        {
          "text": "A reference to a Core Video image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVBufferRef",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CVImageBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVImageBuffer",
      "type": "topic",
      "url": "/documentation/CoreVideo/CVImageBuffer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTDecompressionOutputCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputCallbackRecord",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionOutputHandler"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*v#S2_#I#$@E@VTDecodeInfoFlags#*$@S@__CVBuffer#$@SA@CMTime#S6_)",
                    "text": "void (*)(void *, void *, int, enum VTDecodeInfoFlags, struct __CVBuffer *, CMTime, CMTime)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTDecompressionOutputCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMSampleBufferGetOutputPresentationTimeStamp(_:)/title",
          "value": "CMSampleBufferGetOutputPresentationTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMSampleBufferGetOutputPresentationTimeStamp(_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferGetOutputPresentationTimeStamp"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sbuf"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags~1asynchronous/title",
          "value": "kVTDecodeInfo_Asynchronous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags~1asynchronous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecodeInfo_Asynchronous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags~1imageBufferModifiable/title",
          "value": "kVTDecodeInfo_ImageBufferModifiable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags~1imageBufferModifiable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecodeInfo_ImageBufferModifiable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/title",
          "value": "VTDecodeInfoFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord/title",
          "value": "VTDecompressionOutputCallbackRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallbackRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallbackRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/title",
          "value": "VTDecompressionSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/title",
          "value": "VTDecodeFrameFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputHandler/title",
          "value": "VTDecompressionOutputHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallback/title",
          "value": "VTDecompressionOutputCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionOutputCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionOutputCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTime/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags~1frameDropped/title",
          "value": "kVTDecodeInfo_FrameDropped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags~1frameDropped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTDecodeInfo_FrameDropped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMSampleBufferGetOutputDuration(_:)/title",
          "value": "CMSampleBufferGetOutputDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMSampleBufferGetOutputDuration(_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferGetOutputDuration"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sbuf"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVImageBufferRef/title",
          "value": "CVImageBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVImageBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVBufferRef",
              "text": "CVBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVImageBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionoutputcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionoutputcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
