{
  "abstract": [
    {
      "text": "Indicates whether the session can decode frames with the given format description.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@VTDecompressionSessionCanAcceptFormatDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTDecompressionSessionCanAcceptFormatDescription"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
        "text": "VTDecompressionSession"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "formatDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
        "text": "CMFormatDescription"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTDecompressionSessionCanAcceptFormatDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionCanAcceptFormatDescription"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
              "text": "VTDecompressionSession"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "formatDescription"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "newFormatDesc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMFormatDescriptionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
              "text": "CMFormatDescription"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The decompression session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to test.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "newFormatDesc"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the decompression session accepts the format description; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some video decoders can accommodate minor changes in format without needing to be completely reset in a new session.  Use this function to test whether a format change is sufficiently minor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMFormatDescription"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession": {
      "abstract": [
        {
          "text": "A reference to a decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)": {
      "abstract": [
        {
          "text": "Indicates whether the session can decode frames with the given format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionCanAcceptFormatDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "formatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionCanAcceptFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessioncanacceptformatdescription(_:formatdescription:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)": {
      "abstract": [
        {
          "text": "Copies a black pixel buffer from the decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionCopyBlackPixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pixelBufferOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionCopyBlackPixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessioncopyblackpixelbuffer(_:pixelbufferout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)": {
      "abstract": [
        {
          "text": "Decompresses a video frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionDecodeFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeFrameFlags",
          "text": "VTDecodeFrameFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameRefcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "infoFlagsOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionDecodeFrame"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessiondecodeframe(_:samplebuffer:flags:framerefcon:infoflagsout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:completionHandler:)": {
      "abstract": [
        {
          "text": "Decompresses a video frame and calls the provided output closure when decompression completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionDecodeFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeFrameFlags",
          "text": "VTDecodeFrameFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "infoFlagsOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMTaggedBufferV",
          "text": "CMTaggedBuffer"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:completionHandler:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessiondecodeframe(_:samplebuffer:flags:infoflagsout:completionhandler:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)": {
      "abstract": [
        {
          "text": "Decompresses a video frame and invokes the output callback when the decompression completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionDecodeFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeFrameFlags",
          "text": "VTDecodeFrameFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "infoFlagsOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
          "text": "VTDecodeInfoFlags"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "outputHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionOutputHandler",
          "text": "VTDecompressionOutputHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionDecodeFrameWithOutputHandler"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessiondecodeframe(_:samplebuffer:flags:infoflagsout:outputhandler:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionFinishDelayedFrames(_:)": {
      "abstract": [
        {
          "text": "Directs the decompression session to emit all delayed frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionFinishDelayedFrames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionFinishDelayedFrames(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionFinishDelayedFrames"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSessionFinishDelayedFrames(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessionfinishdelayedframes(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionWaitForAsynchronousFrames(_:)": {
      "abstract": [
        {
          "text": "Waits for any and all outstanding asynchronous and delayed frames to complete, then returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionWaitForAsynchronousFrames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
          "text": "VTDecompressionSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionWaitForAsynchronousFrames(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionWaitForAsynchronousFrames"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSessionWaitForAsynchronousFrames(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessionwaitforasynchronousframes(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMFormatDescriptionRef": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMFormatDescriptionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMFormatDescription"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Decoding-Frames",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:completionHandler:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionFinishDelayedFrames(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionWaitForAsynchronousFrames(_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)"
      ],
      "title": "Decoding Frames"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTDecompressionSessionCanAcceptFormatDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionCanAcceptFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Decoding-Frames",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionFinishDelayedFrames(_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionWaitForAsynchronousFrames(_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)"
              ],
              "title": "Decoding Frames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Boolean",
                    "text": "Boolean"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTDecompressionSessionCanAcceptFormatDescription"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
                    "text": "VTDecompressionSessionRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CMFormatDescriptionRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
                    "text": "CMFormatDescriptionRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "newFormatDesc"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The decompression session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMFormatDescription",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to test.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "newFormatDesc"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the decompression session accepts the format description; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMFormatDescriptionRef/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMFormatDescriptionRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMFormatDescription",
              "text": "opaqueCMFormatDescription"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)/title",
          "value": "VTDecompressionSessionDecodeFrameWithOutputHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:infoFlagsOut:outputHandler:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionDecodeFrameWithOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMFormatDescription",
              "text": "opaqueCMFormatDescription"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)/title",
          "value": "VTDecompressionSessionDecodeFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionDecodeFrame(_:sampleBuffer:flags:frameRefcon:infoFlagsOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionDecodeFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionFinishDelayedFrames(_:)/title",
          "value": "VTDecompressionSessionFinishDelayedFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionFinishDelayedFrames(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionFinishDelayedFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/title",
          "value": "VTDecompressionSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)/title",
          "value": "VTDecompressionSessionCanAcceptFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionCanAcceptFormatDescription(_:formatDescription:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionCanAcceptFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionWaitForAsynchronousFrames(_:)/title",
          "value": "VTDecompressionSessionWaitForAsynchronousFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionWaitForAsynchronousFrames(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionWaitForAsynchronousFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)/title",
          "value": "VTDecompressionSessionCopyBlackPixelBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSessionCopyBlackPixelBuffer(_:pixelBufferOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionCopyBlackPixelBuffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionsessioncanacceptformatdescription(_:formatdescription:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionsessioncanacceptformatdescription(_:formatdescription:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
