{
  "abstract": [
    {
      "text": "Decompresses a multi-image frame and calls the specified output handler upon completion.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler",
    "fragments": [
      {
        "kind": "identifier",
        "text": "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTDecompressionSessionRef",
              "text": "VTDecompressionSessionRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMSampleBufferRef",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sampleBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VTDecodeFrameFlags",
              "text": "VTDecodeFrameFlags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "decodeFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VTDecodeInfoFlags",
              "text": "VTDecodeInfoFlags"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "infoFlagsOut"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionMultiImageCapableOutputHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTDecompressionMultiImageCapableOutputHandler",
              "text": "VTDecompressionMultiImageCapableOutputHandler"
            },
            {
              "kind": "internalParam",
              "text": "multiImageCapableOutputHandler"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The decompression session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A CMSampleBuffer containing one or more video frames.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sampleBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bitfield of directives to the decompression session and decoder.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The kVTDecodeFrame_EnableAsynchronousDecompression bit indicates whether the video decoder may decompress the frame asynchronously.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The kVTDecodeFrame_EnableTemporalProcessing bit indicates whether the decoder may delay calls to the output callback so as to enable processing in temporal (display) order.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If both flags are clear, the decompression shall complete and your output callback function will be called before VTDecompressionSessionDecodeFrame returns.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If either flag is set, VTDecompressionSessionDecodeFrame may return before the output callback function is called.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "decodeFlags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Points to a VTDecodeInfoFlags to receive information about the decode operation. The kVTDecodeInfo_Asynchronous bit may be set if the decode is (or was) running asynchronously. The kVTDecodeInfo_FrameDropped bit may be set if the frame was dropped (synchronously). Pass NULL if you do not want to receive this information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "infoFlagsOut"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block for the system to call when it finished decoding the frame. If the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " call returns an error, the block isn’t called.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "multiImageCapableOutputHandler"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags": {
      "abstract": [
        {
          "text": "Flags to pass to a decompression session and the video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeFrameFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeFrameFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeFrameFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeframeflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags": {
      "abstract": [
        {
          "text": "Flags that provide information about the status of a decode operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecodeInfoFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecodeInfoFlags"
        }
      ],
      "role": "symbol",
      "title": "VTDecodeInfoFlags",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecodeinfoflags"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionMultiImageCapableOutputHandler": {
      "abstract": [
        {
          "text": "A type alias for callback that the system invokes when it finishes decompressing a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionMultiImageCapableOutputHandler"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionMultiImageCapableOutputHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionMultiImageCapableOutputHandler"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionMultiImageCapableOutputHandler",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionmultiimagecapableoutputhandler"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession": {
      "abstract": [
        {
          "text": "A reference to a decompression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSession"
        }
      ],
      "role": "symbol",
      "title": "VTDecompressionSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler": {
      "abstract": [
        {
          "text": "Decompresses a multi-image frame and calls the specified output handler upon completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTDecompressionSessionDecodeFrameWithMultiImageCapableOutputHandler",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessiondecodeframewithmultiimagecapableoutputhandler"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionSetMultiImageCallback": {
      "abstract": [
        {
          "text": "Provides a callback capable of receiving multiple images for individual frame decoding requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTDecompressionSessionSetMultiImageCallback"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionSetMultiImageCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTDecompressionSessionSetMultiImageCallback",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtdecompressionsessionsetmultiimagecallback"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsStereoMVHEVCDecodeSupported()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system supports MV-HEVC decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTIsStereoMVHEVCDecodeSupported"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsStereoMVHEVCDecodeSupported()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTIsStereoMVHEVCDecodeSupported"
        }
      ],
      "role": "symbol",
      "title": "VTIsStereoMVHEVCDecodeSupported()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtisstereomvhevcdecodesupported()"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMSampleBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMSampleBuffer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Decoding-Multi-Image-Frames",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTIsStereoMVHEVCDecodeSupported()",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionSessionSetMultiImageCallback",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionMultiImageCapableOutputHandler"
      ],
      "title": "Decoding Multi-Image Frames"
    }
  ],
  "topicSections": [
    {
      "anchor": "Output-Handler",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTDecompressionMultiImageCapableOutputHandler"
      ],
      "title": "Output Handler"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/title",
          "value": "VTDecompressionSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionMultiImageCapableOutputHandler/title",
          "value": "VTDecompressionMultiImageCapableOutputHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionMultiImageCapableOutputHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionMultiImageCapableOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecompressionMultiImageCapableOutputHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecompressionMultiImageCapableOutputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/title",
          "value": "VTDecodeFrameFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeFrameFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeFrameFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/title",
          "value": "VTDecodeInfoFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTDecodeInfoFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTDecodeInfoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTIsStereoMVHEVCDecodeSupported()/title",
          "value": "VTIsStereoMVHEVCDecodeSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTIsStereoMVHEVCDecodeSupported()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTIsStereoMVHEVCDecodeSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CMSampleBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@opaqueCMSampleBuffer",
              "text": "opaqueCMSampleBuffer"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtdecompressionsessiondecodeframewithmultiimagecapableoutputhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
