{
  "abstract": [
    {
      "text": "A key in a Media Extension extension properties dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@VTExtensionPropertiesKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTExtensionPropertiesKey"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTExtensionPropertiesKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VTExtensionPropertiesKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoDecoderExtensionProperties": {
      "abstract": [
        {
          "text": "Returns information about the Media Extension video decoder required to decode the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTCopyVideoDecoderExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoDecoderExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTCopyVideoDecoderExtensionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyvideodecoderextensionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey": {
      "abstract": [
        {
          "text": "A key in a Media Extension extension properties dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "role": "symbol",
      "title": "VTExtensionPropertiesKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName": {
      "abstract": [
        {
          "text": "A dictionary key for the extension host application localized name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containingBundleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ContainingBundleNameKey"
        }
      ],
      "role": "symbol",
      "title": "containingBundleName",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/containingbundlename"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL": {
      "abstract": [
        {
          "text": "A dictionary key for the URL of the extension host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containingBundleURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ContainingBundleURLKey"
        }
      ],
      "role": "symbol",
      "title": "containingBundleURL",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/containingbundleurl"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier": {
      "abstract": [
        {
          "text": "A dictionary key for the video decoder extension identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ExtensionIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "extensionIdentifier",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/extensionidentifier"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName": {
      "abstract": [
        {
          "text": "A dictionary key for the localized extension name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ExtensionNameKey"
        }
      ],
      "role": "symbol",
      "title": "extensionName",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/extensionname"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL": {
      "abstract": [
        {
          "text": "A dictionary key for the URL of the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ExtensionURLKey"
        }
      ],
      "role": "symbol",
      "title": "extensionURL",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/extensionurl"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/init(rawvalue:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey": {
      "abstract": [
        {
          "text": "A dictionary key for the user readable name string of the codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_CodecNameKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTExtensionProperties_CodecNameKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtextensionproperties_codecnamekey"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Keys",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL"
      ],
      "title": "Keys"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTExtensionPropertiesKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Keys",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL"
              ],
              "title": "Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Extension",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyVideoDecoderExtensionProperties"
              ],
              "title": "Media Extension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTExtensionPropertiesKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleName/title",
          "value": "kVTExtensionProperties_ContainingBundleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ContainingBundleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionIdentifier/title",
          "value": "kVTExtensionProperties_ExtensionIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionName/title",
          "value": "kVTExtensionProperties_ExtensionNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionURL/title",
          "value": "kVTExtensionProperties_ExtensionURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleURL/title",
          "value": "kVTExtensionProperties_ContainingBundleURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ContainingBundleURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/title",
          "value": "VTExtensionPropertiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtextensionpropertieskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtextensionpropertieskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
