{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)VTFrameProcessorConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTFrameProcessorConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTFrameProcessorConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "VTFrameProcessorConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s8SendableP",
              "text": "Sendable"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "@protocol VTFrameProcessorConfiguration",
            "@abstract The VTFrameProcessorConfiguration protocol describes the configuration of a processor to be used during a video processing session.",
            "",
            "@discussion VTFrameProcessorConfiguration protocol conformance is used to start an frame processing session.  These properties can be  queried on an implementation conforming to VTFrameProcessorConfiguration without starting a session."
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/destinationPixelBufferAttributes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationPixelBufferAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/destinationPixelBufferAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destinationPixelBufferAttributes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "destinationPixelBufferAttributes",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/destinationpixelbufferattributes"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/frameSupportedPixelFormats": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameSupportedPixelFormats"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/frameSupportedPixelFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameSupportedPixelFormats"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "frameSupportedPixelFormats",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/framesupportedpixelformats"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/maximumDimensions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/maximumDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumDimensions"
        }
      ],
      "role": "symbol",
      "title": "maximumDimensions",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/maximumdimensions"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/minimumDimensions": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/minimumDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumDimensions"
        }
      ],
      "role": "symbol",
      "title": "minimumDimensions",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/minimumdimensions"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/nextFrameCount": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextFrameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/nextFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextFrameCount"
        }
      ],
      "role": "symbol",
      "title": "nextFrameCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/nextframecount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/previousFrameCount": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousFrameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/previousFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previousFrameCount"
        }
      ],
      "role": "symbol",
      "title": "previousFrameCount",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/previousframecount"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/processorSupported": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processorSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/processorSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processorSupported"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "processorSupported",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/processorsupported"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/sourcePixelBufferAttributes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourcePixelBufferAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/sourcePixelBufferAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourcePixelBufferAttributes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sourcePixelBufferAttributes",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorconfiguration/sourcepixelbufferattributes"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameRateConversionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameRateConversionConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTFrameRateConversionConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframerateconversionconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTMotionBlurConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTMotionBlurConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTMotionBlurConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtmotionblurconfiguration"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTOpticalFlowConfiguration"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTOpticalFlowConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowConfiguration",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowconfiguration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/destinationPixelBufferAttributes",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/frameSupportedPixelFormats",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/nextFrameCount",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/previousFrameCount",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/sourcePixelBufferAttributes"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/maximumDimensions",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/minimumDimensions",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/processorSupported"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTFrameProcessorConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/destinationPixelBufferAttributes",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/frameSupportedPixelFormats",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/nextFrameCount",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/previousFrameCount",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/sourcePixelBufferAttributes"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/maximumDimensions",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/minimumDimensions",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorConfiguration/processorSupported"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameRateConversionConfiguration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTMotionBlurConfiguration",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowConfiguration"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTFrameProcessorConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1processorSupported/title",
          "value": "processorSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1processorSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "processorSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1maximumDimensions/title",
          "value": "maximumDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1maximumDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1previousFrameCount/title",
          "value": "previousFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1previousFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previousFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1frameSupportedPixelFormats/title",
          "value": "frameSupportedPixelFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1frameSupportedPixelFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameSupportedPixelFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration/title",
          "value": "VTMotionBlurConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTMotionBlurConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTMotionBlurConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1minimumDimensions/title",
          "value": "minimumDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1minimumDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration/title",
          "value": "VTFrameRateConversionConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameRateConversionConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameRateConversionConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration/title",
          "value": "VTOpticalFlowConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1destinationPixelBufferAttributes/title",
          "value": "destinationPixelBufferAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1destinationPixelBufferAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destinationPixelBufferAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration/title",
          "value": "VTFrameProcessorConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1sourcePixelBufferAttributes/title",
          "value": "sourcePixelBufferAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1sourcePixelBufferAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourcePixelBufferAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1nextFrameCount/title",
          "value": "nextFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorConfiguration~1nextFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nextFrameCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessorconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessorconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
