{
  "abstract": [
    {
      "text": "Creates a frame silo object using a temporary file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@VTFrameSiloCreate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTFrameSiloCreate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "allocator"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "fileURL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFURLRef",
        "text": "CFURL"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "timeRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTimeRange",
        "text": "CMTimeRange"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "frameSiloOut"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VTFrameSiloRef",
        "text": "VTFrameSilo"
      },
      {
        "kind": "text",
        "text": "?>) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTFrameSiloCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTFrameSiloCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "fileURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFURLRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFURLRef",
              "text": "CFURL"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "timeRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTimeRange",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "frameSiloOut"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTFrameSiloRef",
              "text": "VTFrameSilo"
            },
            {
              "kind": "text",
              "text": "?>) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An allocator for the frame silo.  Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to use the default allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The URL of the backing file for the ",
                  "type": "text"
                },
                {
                  "code": "VTFrameSilo",
                  "type": "codeVoice"
                },
                {
                  "text": " object. If you pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " for ",
                  "type": "text"
                },
                {
                  "code": "fileURL",
                  "type": "codeVoice"
                },
                {
                  "text": ", VideoToolbox will pick a unique temporary file name.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fileURL"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The valid time range for the frame silo. Must be valid for progress reporting.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "timeRange"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Reserved, pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Points to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to receive the newly created object. Call ",
                  "type": "text"
                },
                {
                  "code": "CFRelease",
                  "type": "codeVoice"
                },
                {
                  "text": " to release your retain on the created VTFrameSilo object when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frameSiloOut"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the returned frame silo object to gather frames produced by multipass encoding.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to release the frame silo object when you are done with it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo": {
      "abstract": [
        {
          "text": "An object that stores a large number of sample buffers, as produced by a multipass compression session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameSilo"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameSilo"
        }
      ],
      "role": "symbol",
      "title": "VTFrameSilo",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframesilo"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)": {
      "abstract": [
        {
          "text": "Creates a frame silo object using a temporary file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameSiloCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "fileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "timeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "frameSiloOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTFrameSiloRef",
          "text": "VTFrameSilo"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameSiloCreate"
        }
      ],
      "role": "symbol",
      "title": "VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframesilocreate(allocator:fileurl:timerange:options:framesiloout:)"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange": {
      "abstract": [
        {
          "text": "A structure that represents a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTimeRange",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTimeRange"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFURLRef": {
      "abstract": [
        {
          "text": "A reference to a CFURL object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFURLRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFURL",
      "type": "topic",
      "url": "/documentation/corefoundation/cfurl"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTFrameSiloCreate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameSiloCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTFrameSiloCreate"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allocator"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFURLRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFURLRef",
                    "text": "CFURLRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "fileURL"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTimeRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMTimeRange",
                    "text": "CMTimeRange"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "timeRange"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VTFrameSiloRef",
                    "text": "VTFrameSiloRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "frameSiloOut"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An allocator for the frame silo.  Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to use the default allocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "allocator"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The URL of the backing file for the ",
                        "type": "text"
                      },
                      {
                        "code": "VTFrameSilo",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object. If you pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " for ",
                        "type": "text"
                      },
                      {
                        "code": "fileURL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", VideoToolbox will pick a unique temporary file name.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "fileURL"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The valid time range for the frame silo. Must be valid for progress reporting.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "timeRange"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Reserved, pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Points to a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameSilo",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to receive the newly created object. Call ",
                        "type": "text"
                      },
                      {
                        "code": "CFRelease",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to release your retain on the created VTFrameSilo object when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "frameSiloOut"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)/title",
          "value": "VTFrameSiloCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameSiloCreate(allocator:fileURL:timeRange:options:frameSiloOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameSiloCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFURLRef/title",
          "value": "CFURLRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTimeRange/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameSilo/title",
          "value": "VTFrameSiloRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameSilo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameSiloRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameSilo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameSiloRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtframesilocreate(allocator:fileurl:timerange:options:framesiloout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtframesilocreate(allocator:fileurl:timerange:options:framesiloout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
