{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC21VTFrameProcessorErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VTFrameProcessorError"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTFrameProcessorError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VTFrameProcessorError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/errordomain"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/fatalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fatalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/fatalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "fatalError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/fatalerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/initializationFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initializationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/initializationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "initializationFailed",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/initializationfailed"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/invalidFrameTiming": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFrameTiming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/invalidFrameTiming",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidFrameTiming",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/invalidframetiming"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/invalidParameterError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/invalidParameterError",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameterError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/invalidparametererror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/memoryAllocationFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryAllocationFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/memoryAllocationFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "memoryAllocationFailure",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/memoryallocationfailure"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/processingError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processingError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/processingError",
      "kind": "symbol",
      "role": "symbol",
      "title": "processingError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/processingerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/revisionNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revisionNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/revisionNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "revisionNotSupported",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/revisionnotsupported"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionAlreadyActive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionAlreadyActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionAlreadyActive",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionAlreadyActive",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/sessionalreadyactive"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionLevelError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionLevelError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionLevelError",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionLevelError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/sessionlevelerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionNotStarted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotStarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionNotStarted",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionNotStarted",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/sessionnotstarted"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unknownError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/unknownerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unsupportedInput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unsupportedInput",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedInput",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/unsupportedinput"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unsupportedResolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedResolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21VTFrameProcessorErrorLeV",
          "text": "VTFrameProcessorError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTFrameProcessorError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unsupportedResolution",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedResolution",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/unsupportedresolution"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/errorDomain",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/fatalError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/initializationFailed",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/invalidFrameTiming",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/invalidParameterError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/memoryAllocationFailure",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/processingError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/revisionNotSupported",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionAlreadyActive",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionLevelError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/sessionNotStarted",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unknownError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unsupportedInput",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/unsupportedResolution"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/title",
          "value": "VTFrameProcessorError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessorerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
