{
  "abstract": [
    {
      "text": "An object that generates per-frame HDR metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession-api-collection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "VTHDRPerFrameMetadataGenerationSession"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType": {
      "abstract": [
        {
          "text": "The HDR format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        }
      ],
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationHDRFormatType",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationhdrformattype"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession": {
      "abstract": [
        {
          "text": "An object that generates per-frame HDR metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSession"
        }
      ],
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionAttachMetadata": {
      "abstract": [
        {
          "text": "Attaches per-frame metadata to the pixel buffer and the backing IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSessionAttachMetadata"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionAttachMetadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSessionAttachMetadata",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsessionattachmetadata"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionCreate": {
      "abstract": [
        {
          "text": "Creates a metadata generation session object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSessionCreate"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSessionCreate",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsessioncreate"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionGetTypeID": {
      "abstract": [
        {
          "text": "Retrieves the Core Foundation type identifier for the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSessionGetTypeID"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionGetTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSessionGetTypeID",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsessiongettypeid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionRef": {
      "abstract": [
        {
          "text": "A mechanism for generating HDR Per Frame Metadata and attaching that metadata to a pixel buffer and the backing IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTHDRPerFrameMetadataGenerationSessionRef"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTHDRPerFrameMetadataGenerationSessionRef",
      "type": "topic",
      "url": "/documentation/videotoolbox/vthdrperframemetadatagenerationsessionref"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision": {
      "abstract": [
        {
          "text": "Specifies that DolbyVision data should be generated and attached for each pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvthdrperframemetadatagenerationhdrformattype_dolbyvision"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats": {
      "abstract": [
        {
          "text": "Specifies an array of HDR formats to generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
        }
      ],
      "role": "symbol",
      "title": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvthdrperframemetadatagenerationoptionskey_hdrformats"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSession",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
      ],
      "title": "Data types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-session",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionCreate"
              ],
              "title": "Creating a session"
            },
            {
              "anchor": "Attaching-metadata",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionAttachMetadata"
              ],
              "title": "Attaching metadata"
            },
            {
              "anchor": "Accessing-the-type-identifier",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionGetTypeID"
              ],
              "title": "Accessing the type identifier"
            },
            {
              "anchor": "Data-types",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationSessionRef",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTHDRPerFrameMetadataGenerationHDRFormatType",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationHDRFormatType_DolbyVision",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/title",
          "value": "VTHDRPerFrameMetadataGenerationHDRFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTHDRPerFrameMetadataGenerationHDRFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTHDRPerFrameMetadataGenerationHDRFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats/title",
          "value": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTHDRPerFrameMetadataGenerationOptionsKey_HDRFormats"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vthdrperframemetadatagenerationsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vthdrperframemetadatagenerationsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
