{
  "abstract": [
    {
      "text": "An object that rotates source pixel buffers to destination pixel buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession-api-collection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "VTPixelRotationSession"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create a rotation session, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionCreate(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Optionally configure the session by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To transfer pixels call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionRotateImage(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re done with the session, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to tear it down and release your object reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession": {
      "abstract": [
        {
          "text": "A reference to a pixel rotation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTPixelRotationSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTPixelRotationSession"
        }
      ],
      "role": "symbol",
      "title": "VTPixelRotationSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionCreate(_:_:)": {
      "abstract": [
        {
          "text": "Creates a session to rotate images between pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTPixelRotationSessionRef",
          "text": "VTPixelRotationSession"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionCreate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionCreate"
        }
      ],
      "role": "symbol",
      "title": "VTPixelRotationSessionCreate(_:_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsessioncreate(_:_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier for the rotation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "VTPixelRotationSessionGetTypeID()",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsessiongettypeid()"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionInvalidate(_:)": {
      "abstract": [
        {
          "text": "Tears down a pixel rotation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionInvalidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTPixelRotationSessionRef",
          "text": "VTPixelRotationSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionInvalidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionInvalidate"
        }
      ],
      "role": "symbol",
      "title": "VTPixelRotationSessionInvalidate(_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsessioninvalidate(_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionRotateImage(_:_:_:)": {
      "abstract": [
        {
          "text": "Rotates a source pixel buffer and writes the output to the destination pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionRotateImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTPixelRotationSessionRef",
          "text": "VTPixelRotationSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionRotateImage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTPixelRotationSessionRotateImage"
        }
      ],
      "role": "symbol",
      "title": "VTPixelRotationSessionRotateImage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixelrotationsessionrotateimage(_:_:_:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection": {
      "abstract": [
        {
          "text": "An object converts video data from source pixel buffers to destination pixel buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "VTPixelTransferSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtpixeltransfersession-api-collection"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)": {
      "abstract": [
        {
          "text": "Sets a property on a VideoToolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionSetProperty"
        }
      ],
      "role": "symbol",
      "title": "VTSessionSetProperty(_:key:value:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessionsetproperty(_:key:value:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/pixel-rotation-properties": {
      "abstract": [
        {
          "text": "Properties used to configure a VideoToolbox pixel rotation session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/pixel-rotation-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Rotation Properties",
      "type": "topic",
      "url": "/documentation/videotoolbox/pixel-rotation-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transformation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection"
      ],
      "title": "Transformation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-a-Session",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionCreate(_:_:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionInvalidate(_:)"
      ],
      "title": "Managing a Session"
    },
    {
      "anchor": "Configuring-a-Session",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/pixel-rotation-properties"
      ],
      "title": "Configuring a Session"
    },
    {
      "anchor": "Rotating-an-Image",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionRotateImage(_:_:_:)"
      ],
      "title": "Rotating an Image"
    },
    {
      "anchor": "Inspecting-the-Type-Identifier",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionGetTypeID()"
      ],
      "title": "Inspecting the Type Identifier"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-a-Session",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionCreate(_:_:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionInvalidate(_:)"
              ],
              "title": "Managing a Session"
            },
            {
              "anchor": "Configuring-a-Session",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/pixel-rotation-properties"
              ],
              "title": "Configuring a Session"
            },
            {
              "anchor": "Rotating-an-Image",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionRotateImage(_:_:_:)"
              ],
              "title": "Rotating an Image"
            },
            {
              "anchor": "Inspecting-the-Type-Identifier",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSessionGetTypeID()"
              ],
              "title": "Inspecting the Type Identifier"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelRotationSession"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transformation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTPixelTransferSession-api-collection"
              ],
              "title": "Transformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSession/title",
          "value": "VTPixelRotationSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTPixelRotationSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTPixelRotationSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionGetTypeID()/title",
          "value": "VTPixelRotationSessionGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTPixelRotationSessionGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionRotateImage(_:_:_:)/title",
          "value": "VTPixelRotationSessionRotateImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionRotateImage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTPixelRotationSessionRotateImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperty(_:key:value:)/title",
          "value": "VTSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperty(_:key:value:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionInvalidate(_:)/title",
          "value": "VTPixelRotationSessionInvalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionInvalidate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTPixelRotationSessionInvalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionCreate(_:_:)/title",
          "value": "VTPixelRotationSessionCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTPixelRotationSessionCreate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTPixelRotationSessionCreate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtpixelrotationsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtpixelrotationsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
