{
  "abstract": [
    {
      "text": "Forces the RAW Processor to complete processing frames.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@VTRAWProcessingSessionCompleteFrames",
    "fragments": [
      {
        "kind": "identifier",
        "text": "VTRAWProcessingSessionCompleteFrames"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTRAWProcessingSessionCompleteFrames"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "VTRAWProcessingSessionCompleteFrames"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionCompleteFrames"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
              "text": "VTRAWProcessingSessionRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The RAW processing session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this after calling a set of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " calls to ensure that all frames have been processed.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Before ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns, the output handler will be invoked for all pending frames.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames": {
      "abstract": [
        {
          "text": "Forces the RAW Processor to complete processing frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCompleteFrames"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCompleteFrames",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncompleteframes"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame": {
      "abstract": [
        {
          "text": "Submits RAW frames for format-specific processing using sequence and frame level parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionProcessFrame"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionProcessFrame",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionprocessframe"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-frames",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame"
      ],
      "title": "Processing frames"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/title",
          "value": "VTRAWProcessingSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtrawprocessingsessioncompleteframes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
