{
  "abstract": [
    {
      "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession-api-collection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "VTRAWProcessingSession"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties": {
      "abstract": [
        {
          "text": "Returns information about the Media Extension RAW processor supporting the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTCopyRAWProcessorExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTCopyRAWProcessorExtensionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyrawprocessorextensionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingOutputHandler": {
      "abstract": [
        {
          "text": "A block the system calls when frame processing is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingOutputHandler"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingOutputHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingOutputHandler",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingoutputhandler"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingParameterChangeHandler": {
      "abstract": [
        {
          "text": "A function the system calls when processing parameters change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingParameterChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingParameterChangeHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingParameterChangeHandler",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingparameterchangehandler"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames": {
      "abstract": [
        {
          "text": "Forces the RAW Processor to complete processing frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCompleteFrames"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCompleteFrames",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncompleteframes"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters": {
      "abstract": [
        {
          "text": "Copies an array of dictionaries describing the parameters provided by the RAW Processor for frame processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCopyProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCopyProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncopyprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCreate": {
      "abstract": [
        {
          "text": "Creates a RAW video frame processing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCreate"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCreate",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncreate"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionGetTypeID": {
      "abstract": [
        {
          "text": "Returns the type identifier for a RAW processing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionGetTypeID"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionGetTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionGetTypeID",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessiongettypeid"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionInvalidate": {
      "abstract": [
        {
          "text": "Tears down a RAW processing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionInvalidate"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionInvalidate",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionInvalidate",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioninvalidate"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame": {
      "abstract": [
        {
          "text": "Submits RAW frames for format-specific processing using sequence and frame level parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionProcessFrame"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionProcessFrame",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionprocessframe"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetParameterChangedHander": {
      "abstract": [
        {
          "text": "Provides a block which will be called when the session changes the set of processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionSetParameterChangedHander"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetParameterChangedHander",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionSetParameterChangedHander",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionsetparameterchangedhander"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters": {
      "abstract": [
        {
          "text": "Sets a collection of RAW Processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionSetProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionSetProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionsetprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters": {
      "abstract": [
        {
          "text": "Parameters to set on a RAW processing session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RAW processing parameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/raw-processing-parameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties": {
      "abstract": [
        {
          "text": "Properties that you use to configure a RAW processing session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RAW Processing Properties",
      "type": "topic",
      "url": "/documentation/videotoolbox/raw-processing-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Configuring-a-session",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties"
      ],
      "title": "Configuring a session"
    },
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession"
      ],
      "title": "Data types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-session",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCreate"
              ],
              "title": "Creating a session"
            },
            {
              "anchor": "Configuring-a-session",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties"
              ],
              "title": "Configuring a session"
            },
            {
              "anchor": "Processing-frames",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionProcessFrame",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCompleteFrames"
              ],
              "title": "Processing frames"
            },
            {
              "anchor": "Invalidating-a-session",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionInvalidate"
              ],
              "title": "Invalidating a session"
            },
            {
              "anchor": "Accessing-the-type-identifier",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionGetTypeID"
              ],
              "title": "Accessing the type identifier"
            },
            {
              "anchor": "Data-types",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingParameterChangeHandler",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetParameterChangedHander",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingOutputHandler"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/title",
          "value": "VTRAWProcessingSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtrawprocessingsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtrawprocessingsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
