{
  "abstract": [
    {
      "text": "Copies an array of dictionaries describing the parameters provided by the RAW Processor for frame processing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@VTRAWProcessingSessionCopyProcessingParameters",
    "fragments": [
      {
        "kind": "identifier",
        "text": "VTRAWProcessingSessionCopyProcessingParameters"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VTRAWProcessingSessionCopyProcessingParameters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "VTRAWProcessingSessionCopyProcessingParameters"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionCopyProcessingParameters"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTRAWProcessingSessionRef",
              "text": "VTRAWProcessingSessionRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArrayRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "outParameterArray"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The RAW processing session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Pointer for receiving the RAW Processing parameter array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outParameterArray"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method returns an array of dictionaries - one for each parameter that can be controlled in the RAW processing operation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The dictionary for each parameter will contain a set of keys whose values provide a name, value type, value range, and current value for each parameter. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The returned values can be used to construct dynamic UI presenting RAW Processing controls allowing the various knobs for this specific RAW Processor to be viewed and manipulated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties": {
      "abstract": [
        {
          "text": "Returns information about the Media Extension RAW processor supporting the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTCopyRAWProcessorExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTCopyRAWProcessorExtensionProperties",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtcopyrawprocessorextensionproperties"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession": {
      "abstract": [
        {
          "text": "An object that processes frames in camera native formats such as RAW or Bayer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSession"
        }
      ],
      "role": "symbol",
      "title": "VTRAWProcessingSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters": {
      "abstract": [
        {
          "text": "Copies an array of dictionaries describing the parameters provided by the RAW Processor for frame processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionCopyProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionCopyProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionCopyProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessioncopyprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters": {
      "abstract": [
        {
          "text": "Sets a collection of RAW Processing parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VTRAWProcessingSessionSetProcessingParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "VTRAWProcessingSessionSetProcessingParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtrawprocessingsessionsetprocessingparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters": {
      "abstract": [
        {
          "text": "Parameters to set on a RAW processing session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RAW processing parameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/raw-processing-parameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties": {
      "abstract": [
        {
          "text": "Properties that you use to configure a RAW processing session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RAW Processing Properties",
      "type": "topic",
      "url": "/documentation/videotoolbox/raw-processing-properties"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTRAWProcessingSessionSetProcessingParameters",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-parameters",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTCopyRAWProcessorExtensionProperties",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/raw-processing-properties"
      ],
      "title": "Configuring a session"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/title",
          "value": "VTRAWProcessingSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTRAWProcessingSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTRAWProcessingSessionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtrawprocessingsessioncopyprocessingparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
