{
  "abstract": [
    {
      "text": "An abstract object that provides the common interface to configure VideoToolbox session objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession-api-collection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "VTSession"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/1441330-frame-delay": {
      "abstract": [
        {
          "text": "Indicates that no limit should be placed on the compression window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/1441330-frame-delay",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Frame Delay",
      "type": "topic",
      "url": "/documentation/videotoolbox/1441330-frame-delay"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point": {
      "abstract": [
        {
          "text": "A structure that represents a 32-bit integer point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTInt32Point"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTInt32Point"
        }
      ],
      "role": "symbol",
      "title": "VTInt32Point",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtint32point"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size": {
      "abstract": [
        {
          "text": "A structure that represents a 32-bit integer size value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTInt32Size"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTInt32Size"
        }
      ],
      "role": "symbol",
      "title": "VTInt32Size",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtint32size"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession": {
      "abstract": [
        {
          "text": "A reference to a VideoToolbox compression session,  decompression session or pixel transfer session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSession"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSession"
        }
      ],
      "role": "symbol",
      "title": "VTSession",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsession"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)": {
      "abstract": [
        {
          "text": "Retrieves a property on a Video Toolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionCopyProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "valueOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionCopyProperty"
        }
      ],
      "role": "symbol",
      "title": "VTSessionCopyProperty(_:key:allocator:valueOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessioncopyproperty(_:key:allocator:valueout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)": {
      "abstract": [
        {
          "text": "Retrieves the set of serializable property keys and their current values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionCopySerializableProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "dictionaryOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionCopySerializableProperties"
        }
      ],
      "role": "symbol",
      "title": "VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessioncopyserializableproperties(_:allocator:dictionaryout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)": {
      "abstract": [
        {
          "text": "Retrieves a dictionary enumerating all the supported properties of a video toolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionCopySupportedPropertyDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "supportedPropertyDictionaryOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionCopySupportedPropertyDictionary"
        }
      ],
      "role": "symbol",
      "title": "VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessioncopysupportedpropertydictionary(_:supportedpropertydictionaryout:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)": {
      "abstract": [
        {
          "text": "Sets multiple properties at once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionSetProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "propertyDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionSetProperties"
        }
      ],
      "role": "symbol",
      "title": "VTSessionSetProperties(_:propertyDictionary:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessionsetproperties(_:propertydictionary:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)": {
      "abstract": [
        {
          "text": "Sets a property on a VideoToolbox session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTSessionSetProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTSessionRef",
          "text": "VTSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTSessionSetProperty"
        }
      ],
      "role": "symbol",
      "title": "VTSessionSetProperty(_:key:value:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtsessionsetproperty(_:key:value:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
        }
      ],
      "role": "symbol",
      "title": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER",
      "type": "topic",
      "url": "/documentation/videotoolbox/vt_support_colorsync_pixel_transfer"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants": {
      "abstract": [
        {
          "text": "Property dictionary key and constant values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supported Property Dictionary Constants",
      "type": "topic",
      "url": "/documentation/videotoolbox/supported-dictionary-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-Properties",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)"
      ],
      "title": "Setting Properties"
    },
    {
      "anchor": "Getting-Properties",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants"
      ],
      "title": "Getting Properties"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/1441330-frame-delay"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-Properties",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperty(_:key:value:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionSetProperties(_:propertyDictionary:)"
              ],
              "title": "Setting Properties"
            },
            {
              "anchor": "Getting-Properties",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopyProperty(_:key:allocator:valueOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/supported-dictionary-constants"
              ],
              "title": "Getting Properties"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTSession"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/1441330-frame-delay"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Point",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTInt32Size",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperties(_:propertyDictionary:)/title",
          "value": "VTSessionSetProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperties(_:propertyDictionary:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionSetProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)/title",
          "value": "VTSessionCopySerializableProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySerializableProperties(_:allocator:dictionaryOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionCopySerializableProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperty(_:key:value:)/title",
          "value": "VTSessionSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionSetProperty(_:key:value:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionSetProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSession/title",
          "value": "VTSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopyProperty(_:key:allocator:valueOut:)/title",
          "value": "VTSessionCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopyProperty(_:key:allocator:valueOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionCopyProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER/title",
          "value": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)/title",
          "value": "VTSessionCopySupportedPropertyDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTSessionCopySupportedPropertyDictionary(_:supportedPropertyDictionaryOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTSessionCopySupportedPropertyDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Point/title",
          "value": "VTInt32Point"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Point/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Point"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Point/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Point"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Size/title",
          "value": "VTInt32Size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTInt32Size/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTInt32Size"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtsession-api-collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
