{
  "abstract": [
    {
      "text": "Error codes in the framework error domain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VSErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VSError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError": {
      "abstract": [
        {
          "text": "Error information in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "role": "symbol",
      "title": "VSError",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code": {
      "abstract": [
        {
          "text": "Error codes in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/accessNotGranted": {
      "abstract": [
        {
          "text": "The user hasn’t granted access to their subscription information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessNotGranted"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/accessNotGranted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeAccessNotGranted"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.accessNotGranted",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/accessnotgranted"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/init(rawvalue:)"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/invalidVerificationToken": {
      "abstract": [
        {
          "text": "The user’s subscription provider rejected the verification token that the app sent with the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVerificationToken"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/invalidVerificationToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeInvalidVerificationToken"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.invalidVerificationToken",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/invalidverificationtoken"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/providerRejected": {
      "abstract": [
        {
          "text": "The user’s subscription provider didn’t allow the request to proceed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerRejected"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/providerRejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeProviderRejected"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.providerRejected",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/providerrejected"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/rejected": {
      "abstract": [
        {
          "text": "The system rejected the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rejected"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/rejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeRejected"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.rejected",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/rejected"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/serviceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "The request failed due to a timeout or unreachable host, but a subsequent attempt might succeed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/serviceTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeServiceTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.serviceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/servicetemporarilyunavailable"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupported": {
      "abstract": [
        {
          "text": "The provider doesn’t support the feature the user requested in the device’s current region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/unsupported"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupportedProvider": {
      "abstract": [
        {
          "text": "The system doesn’t support the user’s subscription provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedProvider"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupportedProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeUnsupportedProvider"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.unsupportedProvider",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/unsupportedprovider"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/userCancelled": {
      "abstract": [
        {
          "text": "The user canceled the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCancelled"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/userCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorCodeUserCancelled"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code.userCancelled",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code/usercancelled"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain": {
      "abstract": [
        {
          "text": "The domain for all errors in the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "VSErrorDomain",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrordomain"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse": {
      "abstract": [
        {
          "text": "The account provider’s error-response object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyAccountProviderResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyAccountProviderResponse"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeyAccountProviderResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeyaccountproviderresponse"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse": {
      "abstract": [
        {
          "text": "The subscription provider’s SAML error response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponse"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeySAMLResponse",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeysamlresponse"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus": {
      "abstract": [
        {
          "text": "The subscription provider’s SAML error-response status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponseStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeySAMLResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeySAMLResponseStatus",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeysamlresponsestatus"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the unsupported subscription provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        }
      ],
      "role": "symbol",
      "title": "VSErrorInfoKeyUnsupportedProviderIdentifier",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserrorinfokeyunsupportedprovideridentifier"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/accessNotGranted",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/invalidVerificationToken",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/providerRejected",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/rejected",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/serviceTemporarilyUnavailable",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupported",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupportedProvider",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/userCancelled"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VSErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/accessNotGranted",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/invalidVerificationToken",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/providerRejected",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/rejected",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/serviceTemporarilyUnavailable",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupported",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/unsupportedProvider",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code/userCancelled"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorDomain",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponse",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeySAMLResponseStatus",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyAccountProviderResponse",
                "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSErrorInfoKeyUnsupportedProviderIdentifier"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VSErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1rejected/title",
          "value": "VSErrorCodeRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1rejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeRejected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1unsupportedProvider/title",
          "value": "VSErrorCodeUnsupportedProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1unsupportedProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeUnsupportedProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1accessNotGranted/title",
          "value": "VSErrorCodeAccessNotGranted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1accessNotGranted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeAccessNotGranted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyAccountProviderResponse/title",
          "value": "VSErrorInfoKeyAccountProviderResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyAccountProviderResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeyAccountProviderResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1unsupported/title",
          "value": "VSErrorCodeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorDomain/title",
          "value": "VSErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/title",
          "value": "VSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyUnsupportedProviderIdentifier/title",
          "value": "VSErrorInfoKeyUnsupportedProviderIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeyUnsupportedProviderIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeyUnsupportedProviderIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1serviceTemporarilyUnavailable/title",
          "value": "VSErrorCodeServiceTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1serviceTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeServiceTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponse/title",
          "value": "VSErrorInfoKeySAMLResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeySAMLResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1providerRejected/title",
          "value": "VSErrorCodeProviderRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1providerRejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeProviderRejected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponseStatus/title",
          "value": "VSErrorInfoKeySAMLResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSErrorInfoKeySAMLResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorInfoKeySAMLResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1userCancelled/title",
          "value": "VSErrorCodeUserCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1userCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeUserCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1invalidVerificationToken/title",
          "value": "VSErrorCodeInvalidVerificationToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code~1invalidVerificationToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCodeInvalidVerificationToken"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vserror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videosubscriberaccount/vserror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
