{
  "abstract": [
    {
      "text": "The user’s subscription provider rejected the verification token that the app sent with the request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/invalidVerificationToken"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11VSErrorCodeLeV24invalidVerificationTokenSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidVerificationToken"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11VSErrorCodeLeV",
        "text": "VSError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VSErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Video Subscriber Account"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidVerificationToken"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidVerificationToken"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11VSErrorCodeLeV",
              "text": "VSError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VSErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount": {
      "abstract": [
        {
          "text": "Support TV provider and Apple TV app functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Subscriber Account",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError": {
      "abstract": [
        {
          "text": "Error information in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VSError"
        }
      ],
      "role": "symbol",
      "title": "VSError",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code": {
      "abstract": [
        {
          "text": "Error codes in the framework error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VSError.Code",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/code"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/accessNotGranted": {
      "abstract": [
        {
          "text": "The user hasn’t granted access to their subscription information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessNotGranted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/accessNotGranted",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessNotGranted",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/accessnotgranted"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/invalidVerificationToken": {
      "abstract": [
        {
          "text": "The user’s subscription provider rejected the verification token that the app sent with the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVerificationToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/invalidVerificationToken",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidVerificationToken",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/invalidverificationtoken"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/providerRejected": {
      "abstract": [
        {
          "text": "The user’s subscription provider didn’t allow the request to proceed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerRejected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/providerRejected",
      "kind": "symbol",
      "role": "symbol",
      "title": "providerRejected",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/providerrejected"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/rejected": {
      "abstract": [
        {
          "text": "The system rejected the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rejected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/rejected",
      "kind": "symbol",
      "role": "symbol",
      "title": "rejected",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/rejected"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/serviceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "The request failed due to a timeout or unreachable host, but a subsequent attempt might succeed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceTemporarilyUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/serviceTemporarilyUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "serviceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/servicetemporarilyunavailable"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupported": {
      "abstract": [
        {
          "text": "The provider doesn’t support the feature the user requested in the device’s current region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupported",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/unsupported"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupportedProvider": {
      "abstract": [
        {
          "text": "The system doesn’t support the user’s subscription provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupportedProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedProvider",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/unsupportedprovider"
    },
    "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/userCancelled": {
      "abstract": [
        {
          "text": "The user canceled the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11VSErrorCodeLeV",
          "text": "VSError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VSErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/userCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCancelled",
      "type": "topic",
      "url": "/documentation/videosubscriberaccount/vserror/usercancelled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/accessNotGranted",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/providerRejected",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/rejected",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/serviceTemporarilyUnavailable",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupported",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/unsupportedProvider",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/userCancelled",
        "doc://com.apple.videosubscriberaccount/documentation/VideoSubscriberAccount/VSError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/title",
          "value": "VSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videosubscriberaccount~1documentation~1VideoSubscriberAccount~1VSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VSErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videosubscriberaccount/vserror/invalidverificationtoken"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
