{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter",
        "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory/start(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTRDeviceControllerFactory(im)startControllerFactory:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "start"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MTRDeviceControllerFactoryParams",
        "text": "MTRDeviceControllerFactoryParams"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startControllerFactory:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "start(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "start"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "startupParams"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTRDeviceControllerFactoryParams",
              "text": "MTRDeviceControllerFactoryParams"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.matter/documentation/Matter/onboarding-a-matter-device"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactory"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactory"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerFactory",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerfactory"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory/start(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTRDeviceControllerFactoryParams",
          "text": "MTRDeviceControllerFactoryParams"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory/start(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startControllerFactory:error:"
        }
      ],
      "role": "symbol",
      "title": "start(_:)",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerfactory/start(_:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactoryParams"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRDeviceControllerFactoryParams"
        }
      ],
      "role": "symbol",
      "title": "MTRDeviceControllerFactoryParams",
      "type": "topic",
      "url": "/documentation/matter/mtrdevicecontrollerfactoryparams"
    },
    "doc://com.apple.matter/documentation/Matter/onboarding-a-matter-device": {
      "abstract": [
        {
          "text": "Prepare your app to discover and control a Matter device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/onboarding-a-matter-device",
      "kind": "article",
      "role": "article",
      "title": "Onboarding a Matter device",
      "type": "topic",
      "url": "/documentation/matter/onboarding-a-matter-device"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startControllerFactory:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startControllerFactory:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter",
                "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startControllerFactory:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.matter/documentation/Matter/MTRDeviceControllerFactoryParams",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTRDeviceControllerFactoryParams",
                    "text": "MTRDeviceControllerFactoryParams"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "startupParams"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory/title",
          "value": "MTRDeviceControllerFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactoryParams/title",
          "value": "MTRDeviceControllerFactoryParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactoryParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactoryParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactoryParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRDeviceControllerFactoryParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory~1start(_:)/title",
          "value": "startControllerFactory:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRDeviceControllerFactory~1start(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startControllerFactory:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrdevicecontrollerfactory/start(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrdevicecontrollerfactory/start(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
