{
  "abstract": [
    {
      "text": "Returns the line number that contains the specified point.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIAccessibilityReadingContent(im)accessibilityLineNumberForPoint:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityLineNumber"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessibilityLineNumberForPoint:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityLineNumber(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLineNumber"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A point within the bounds of the receiver’s view space, in screen coordinates. That is, a point for which ",
                  "type": "text"
                },
                {
                  "code": "[self pointInside:point withEvent:event] == YES",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "point"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The line number that contains the specified point or ",
              "type": "text"
            },
            {
              "code": "NSNotFound",
              "type": "codeVoice"
            },
            {
              "text": " if the point indicates an empty area within the receiver’s rectangle. By default, this method returns ",
              "type": "text"
            },
            {
              "code": "NSNotFound",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called only when ",
              "type": "text"
            },
            {
              "code": "point",
              "type": "codeVoice"
            },
            {
              "text": " is within the bounds of the view or element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/convertToScreenCoordinates(_:in:)-9ziiu": {
      "abstract": [
        {
          "text": "Converts the specified rectangle from view coordinates to screen coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToScreenCoordinates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/convertToScreenCoordinates(_:in:)-9ziiu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityConvertFrameToScreenCoordinates"
        }
      ],
      "role": "symbol",
      "title": "convertToScreenCoordinates(_:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/converttoscreencoordinates(_:in:)-9ziiu"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent": {
      "abstract": [
        {
          "text": "Methods to implement for an object that represents content that users read, such as a book or an article.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityReadingContent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityReadingContent"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityReadingContent",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)": {
      "abstract": [
        {
          "text": "Returns the styled text associated with the specified line number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLineNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityAttributedContentForLineNumber:"
        }
      ],
      "role": "symbol",
      "title": "accessibilityAttributedContent(forLineNumber:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilityattributedcontent(forlinenumber:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()": {
      "abstract": [
        {
          "text": "Returns the styled text displayed on the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedPageContent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityAttributedPageContent"
        }
      ],
      "role": "symbol",
      "title": "accessibilityAttributedPageContent()",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilityattributedpagecontent()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)": {
      "abstract": [
        {
          "text": "Returns the text associated with the specified line number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLineNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityContentForLineNumber:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityContent(forLineNumber:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitycontent(forlinenumber:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)": {
      "abstract": [
        {
          "text": "Returns the onscreen frame associated with the specified line number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLineNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityFrameForLineNumber:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityFrame(forLineNumber:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilityframe(forlinenumber:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)": {
      "abstract": [
        {
          "text": "Returns the line number that contains the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLineNumber"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLineNumberForPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLineNumber(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitylinenumber(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()": {
      "abstract": [
        {
          "text": "Returns the text displayed on the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPageContent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPageContent"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPageContent()",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitypagecontent()"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/convertToScreenCoordinates(_:in:)-9ziiu"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Accessing-the-content-on-a-page",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()"
      ],
      "title": "Accessing the content on a page"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accessibilityLineNumberForPoint:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLineNumberForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/convertToScreenCoordinates(_:in:)-9ziiu"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Accessing-the-content-on-a-page",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()"
              ],
              "title": "Accessing the content on a page"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessibilityLineNumberForPoint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "point"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A point within the bounds of the receiver’s view space, in screen coordinates. That is, a point for which ",
                        "type": "text"
                      },
                      {
                        "code": "[self pointInside:point withEvent:event] == YES",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "point"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The line number that contains the specified point or ",
                    "type": "text"
                  },
                  {
                    "code": "NSNotFound",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the point indicates an empty area within the receiver’s rectangle. By default, this method returns ",
                    "type": "text"
                  },
                  {
                    "code": "NSNotFound",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityContent(forLineNumber:)/title",
          "value": "accessibilityContentForLineNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityContent(forLineNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityContentForLineNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedPageContent()/title",
          "value": "accessibilityAttributedPageContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedPageContent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityAttributedPageContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedContent(forLineNumber:)/title",
          "value": "accessibilityAttributedContentForLineNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedContent(forLineNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityAttributedContentForLineNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent/title",
          "value": "UIAccessibilityReadingContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityLineNumber(for:)/title",
          "value": "accessibilityLineNumberForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityLineNumber(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLineNumberForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityPageContent()/title",
          "value": "accessibilityPageContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityPageContent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPageContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityFrame(forLineNumber:)/title",
          "value": "accessibilityFrameForLineNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityFrame(forLineNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityFrameForLineNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1convertToScreenCoordinates(_:in:)-9ziiu/title",
          "value": "UIAccessibilityConvertFrameToScreenCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1convertToScreenCoordinates(_:in:)-9ziiu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityConvertFrameToScreenCoordinates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitylinenumber(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitylinenumber(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
