{
  "abstract": [
    {
      "text": "The different types of a natural language model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "NaturalLanguage",
    "externalID": "c:@E@NLModelType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ModelType"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ModelType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NLModel.ModelType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ModelType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel": {
      "abstract": [
        {
          "text": "A custom model trained to classify or tag natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "role": "symbol",
      "title": "NLModel",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType": {
      "abstract": [
        {
          "text": "The different types of a natural language model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModelType"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModelType"
        }
      ],
      "role": "symbol",
      "title": "NLModel.ModelType",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel/modeltype"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/classifier": {
      "abstract": [
        {
          "text": "A classifier model type that tags text at the phrase, sentence, paragraph, or higher level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classifier"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/classifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLModelTypeClassifier"
        }
      ],
      "role": "symbol",
      "title": "NLModel.ModelType.classifier",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel/modeltype/classifier"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel/modeltype/init(rawvalue:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/sequence": {
      "abstract": [
        {
          "text": "A sequence model type that tags text at the token level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequence"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/sequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLModelTypeSequence"
        }
      ],
      "role": "symbol",
      "title": "NLModel.ModelType.sequence",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel/modeltype/sequence"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/currentRevision(for:)": {
      "abstract": [
        {
          "text": "Returns the current Natural Language framework version in the OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentRevision"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NLModel",
          "text": "NLModel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLModelType",
          "text": "ModelType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/currentRevision(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentRevisionForType:"
        }
      ],
      "role": "symbol",
      "title": "currentRevision(for:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodelconfiguration/currentrevision(for:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/language": {
      "abstract": [
        {
          "text": "The language the model supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "language"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/language",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "language"
        }
      ],
      "role": "symbol",
      "title": "language",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodelconfiguration/language"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/revision": {
      "abstract": [
        {
          "text": "The version of the Natural Language framework that trained the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/revision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revision"
        }
      ],
      "role": "symbol",
      "title": "revision",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodelconfiguration/revision"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/supportedRevisions(for:)": {
      "abstract": [
        {
          "text": "Returns the versions of the Natural Language framework the OS supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedRevisions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NLModel",
          "text": "NLModel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLModelType",
          "text": "ModelType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/supportedRevisions(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedRevisionsForType:"
        }
      ],
      "role": "symbol",
      "title": "supportedRevisions(for:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodelconfiguration/supportedrevisions(for:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/type": {
      "abstract": [
        {
          "text": "The natural language model type of the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NLModel",
          "text": "NLModel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLModelType",
          "text": "ModelType"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodelconfiguration/type"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/language",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/revision",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/supportedRevisions(for:)",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/currentRevision(for:)",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/type"
      ],
      "title": "Accessing the configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Model-types",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/sequence",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/classifier"
      ],
      "title": "Model types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NLModelType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Model-types",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/sequence",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel/ModelType/classifier"
              ],
              "title": "Model types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/language",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/revision",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/supportedRevisions(for:)",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/currentRevision(for:)",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModelConfiguration/type"
              ],
              "title": "Accessing the configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NLModelType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType~1sequence/title",
          "value": "NLModelTypeSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType~1sequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModelTypeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1supportedRevisions(for:)/title",
          "value": "supportedRevisionsForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1supportedRevisions(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "supportedRevisionsForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType/title",
          "value": "NLModelType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModelType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1currentRevision(for:)/title",
          "value": "currentRevisionForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1currentRevision(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "currentRevisionForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1revision/title",
          "value": "revision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1revision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "revision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType~1classifier/title",
          "value": "NLModelTypeClassifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel~1ModelType~1classifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModelTypeClassifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/title",
          "value": "NLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1language/title",
          "value": "language"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModelConfiguration~1language/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "language"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nlmodel/modeltype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nlmodel/modeltype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
