{"abstract":[{"type":"text","text":"A dictionary key for the URL of the extension host application."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containingBundleURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VTExtensionPropertiesKey","identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This key points to a "},{"code":"CFURLRef","type":"codeVoice"},{"type":"text","text":" value with the URL of the extension host application."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"containingBundleURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VTExtensionPropertiesKey","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"kVTExtensionProperties_ContainingBundleURLKey"}],"externalID":"c:@kVTExtensionProperties_ContainingBundleURLKey","roleHeading":"Type Property","role":"symbol","platforms":[{"introducedAt":"15.0","beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"extendedModule":"VideoToolbox","title":"containingBundleURL","modules":[{"name":"Video Toolbox"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.videotoolbox/documentation/VideoToolbox","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey"]]},"kind":"symbol","variants":[{"paths":["/documentation/videotoolbox/vtextensionpropertieskey/containingbundleurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/videotoolbox/vtextensionpropertieskey/containingbundleurl"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Keys","title":"Keys","generated":true,"identifiers":["doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL"]}],"identifier":{"url":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL","interfaceLanguage":"swift"},"references":{"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier":{"url":"/documentation/videotoolbox/vtextensionpropertieskey/extensionidentifier","abstract":[{"type":"text","text":"A dictionary key for the video decoder extension identifier."}],"kind":"symbol","type":"topic","title":"extensionIdentifier","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensionIdentifier"},{"text":": ","kind":"text"},{"text":"VTExtensionPropertiesKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier","navigatorTitle":[{"text":"kVTExtensionProperties_ExtensionIdentifierKey","kind":"identifier"}]},"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey":{"url":"/documentation/videotoolbox/vtextensionpropertieskey","abstract":[{"text":"A key in a Media Extension extension properties dictionary.","type":"text"}],"kind":"symbol","type":"topic","title":"VTExtensionPropertiesKey","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VTExtensionPropertiesKey","kind":"identifier"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey","navigatorTitle":[{"text":"VTExtensionPropertiesKey","kind":"identifier"}]},"doc://com.apple.videotoolbox/documentation/VideoToolbox":{"abstract":[{"text":"Work directly with hardware-accelerated video encoding and decoding capabilities.","type":"text"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox","kind":"symbol","type":"topic","title":"Video Toolbox","url":"/documentation/videotoolbox","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"role":"overview","type":"topic","url":"/documentation/technologies","kind":"technologies","title":"Technologies"},"doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey":{"url":"/documentation/videotoolbox/kvtextensionproperties_codecnamekey","abstract":[{"text":"A dictionary key for the user readable name string of the codec.","type":"text"}],"kind":"symbol","type":"topic","title":"kVTExtensionProperties_CodecNameKey","role":"symbol","fragments":[{"text":"kVTExtensionProperties_CodecNameKey","kind":"identifier"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey"},"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName":{"url":"/documentation/videotoolbox/vtextensionpropertieskey/containingbundlename","abstract":[{"type":"text","text":"A dictionary key for the extension host application localized name."}],"kind":"symbol","type":"topic","title":"containingBundleName","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"containingBundleName"},{"text":": ","kind":"text"},{"text":"VTExtensionPropertiesKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName","navigatorTitle":[{"text":"kVTExtensionProperties_ContainingBundleNameKey","kind":"identifier"}]},"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL":{"url":"/documentation/videotoolbox/vtextensionpropertieskey/extensionurl","abstract":[{"type":"text","text":"A dictionary key for the URL of the extension."}],"kind":"symbol","type":"topic","title":"extensionURL","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensionURL"},{"text":": ","kind":"text"},{"text":"VTExtensionPropertiesKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL","navigatorTitle":[{"text":"kVTExtensionProperties_ExtensionURLKey","kind":"identifier"}]},"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL":{"url":"/documentation/videotoolbox/vtextensionpropertieskey/containingbundleurl","abstract":[{"text":"A dictionary key for the URL of the extension host application.","type":"text"}],"kind":"symbol","type":"topic","title":"containingBundleURL","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containingBundleURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@VTExtensionPropertiesKey","text":"VTExtensionPropertiesKey","kind":"typeIdentifier"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL","navigatorTitle":[{"text":"kVTExtensionProperties_ContainingBundleURLKey","kind":"identifier"}]},"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName":{"url":"/documentation/videotoolbox/vtextensionpropertieskey/extensionname","abstract":[{"type":"text","text":"A dictionary key for the localized extension name."}],"kind":"symbol","type":"topic","title":"extensionName","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensionName"},{"text":": ","kind":"text"},{"text":"VTExtensionPropertiesKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"}],"identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName","navigatorTitle":[{"text":"kVTExtensionProperties_ExtensionNameKey","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"15.0","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Global Variable","path":"/metadata/roleHeading","op":"replace"},{"value":"kVTExtensionProperties_ContainingBundleURLKey","path":"/metadata/title","op":"replace"},{"value":"var","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"kVTExtensionProperties_ContainingBundleURLKey"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.videotoolbox/documentation/VideoToolbox"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName","doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL"],"anchor":"Keys","generated":true,"title":"Keys"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"VTExtensionPropertiesKey","identifier":"doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey","preciseIdentifier":"c:@T@VTExtensionPropertiesKey"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"kVTExtensionProperties_ContainingBundleURLKey"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionIdentifier/title","op":"replace","value":"kVTExtensionProperties_ExtensionIdentifierKey"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionIdentifier/fragments","op":"replace","value":[{"text":"kVTExtensionProperties_ExtensionIdentifierKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/title","op":"replace","value":"VTExtensionPropertiesKey"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/fragments","op":"replace","value":[{"kind":"identifier","text":"VTExtensionPropertiesKey"}]},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/navigatorTitle","op":"replace","value":[{"text":"VTExtensionPropertiesKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleName/title","op":"replace","value":"kVTExtensionProperties_ContainingBundleNameKey"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleName/fragments","op":"replace","value":[{"text":"kVTExtensionProperties_ContainingBundleNameKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionURL/title","op":"replace","value":"kVTExtensionProperties_ExtensionURLKey"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionURL/fragments","op":"replace","value":[{"kind":"identifier","text":"kVTExtensionProperties_ExtensionURLKey"}]},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleURL/title","op":"replace","value":"kVTExtensionProperties_ContainingBundleURLKey"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleURL/fragments","op":"replace","value":[{"kind":"identifier","text":"kVTExtensionProperties_ContainingBundleURLKey"}]},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionName/title","op":"replace","value":"kVTExtensionProperties_ExtensionNameKey"},{"path":"/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionName/fragments","op":"replace","value":[{"kind":"identifier","text":"kVTExtensionProperties_ExtensionNameKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}