{
  "abstract": [
    {
      "text": "A dictionary key for the video decoder extension identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "VideoToolbox",
    "externalID": "c:@kVTExtensionProperties_ExtensionIdentifierKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extensionIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
        "text": "VTExtensionPropertiesKey"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kVTExtensionProperties_ExtensionIdentifierKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "extensionIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extensionIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key points to a ",
              "type": "text"
            },
            {
              "code": "CFStringRef",
              "type": "codeVoice"
            },
            {
              "text": " value with the extension identifier, corresponding to the ClassImplementationID value from the EXAppExtensionAttributes dictionary in the Info.plist file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey": {
      "abstract": [
        {
          "text": "A key in a Media Extension extension properties dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "role": "symbol",
      "title": "VTExtensionPropertiesKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName": {
      "abstract": [
        {
          "text": "A dictionary key for the extension host application localized name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containingBundleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ContainingBundleNameKey"
        }
      ],
      "role": "symbol",
      "title": "containingBundleName",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/containingbundlename"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL": {
      "abstract": [
        {
          "text": "A dictionary key for the URL of the extension host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containingBundleURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ContainingBundleURLKey"
        }
      ],
      "role": "symbol",
      "title": "containingBundleURL",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/containingbundleurl"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier": {
      "abstract": [
        {
          "text": "A dictionary key for the video decoder extension identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ExtensionIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "extensionIdentifier",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/extensionidentifier"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName": {
      "abstract": [
        {
          "text": "A dictionary key for the localized extension name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ExtensionNameKey"
        }
      ],
      "role": "symbol",
      "title": "extensionName",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/extensionname"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL": {
      "abstract": [
        {
          "text": "A dictionary key for the URL of the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
          "text": "VTExtensionPropertiesKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_ExtensionURLKey"
        }
      ],
      "role": "symbol",
      "title": "extensionURL",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtextensionpropertieskey/extensionurl"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey": {
      "abstract": [
        {
          "text": "A dictionary key for the user readable name string of the codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kVTExtensionProperties_CodecNameKey"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kVTExtensionProperties_CodecNameKey",
      "type": "topic",
      "url": "/documentation/videotoolbox/kvtextensionproperties_codecnamekey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL"
      ],
      "title": "Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kVTExtensionProperties_ExtensionIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/kVTExtensionProperties_CodecNameKey",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/containingBundleURL",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionName",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey/extensionURL"
              ],
              "title": "Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTExtensionPropertiesKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@VTExtensionPropertiesKey",
                    "text": "VTExtensionPropertiesKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kVTExtensionProperties_ExtensionIdentifierKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/title",
          "value": "VTExtensionPropertiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTExtensionPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionName/title",
          "value": "kVTExtensionProperties_ExtensionNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleURL/title",
          "value": "kVTExtensionProperties_ContainingBundleURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ContainingBundleURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionIdentifier/title",
          "value": "kVTExtensionProperties_ExtensionIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleName/title",
          "value": "kVTExtensionProperties_ContainingBundleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1containingBundleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ContainingBundleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionURL/title",
          "value": "kVTExtensionProperties_ExtensionURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTExtensionPropertiesKey~1extensionURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kVTExtensionProperties_ExtensionURLKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtextensionpropertieskey/extensionidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtextensionpropertieskey/extensionidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
