{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Supporting-Accessibility","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()"],"title":"Supporting Accessibility"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformIncrement"},{"kind":"text","text":"() -> "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the action was successfully triggered; otherwise, ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":". This method does not indicate the success or failure of the action, just the fact that the action was successfully triggered.","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method must post an "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/valueChanged","type":"reference"},{"type":"text","text":" notification after changing the stepper’s value."}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilitystepper/accessibilityperformincrement()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilitystepper/accessibilityperformincrement()"]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:objc(pl)NSAccessibilityStepper(im)accessibilityPerformIncrement","required":true,"roleHeading":"Instance Method","title":"accessibilityPerformIncrement()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformIncrement"}],"modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformIncrement"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},"abstract":[{"type":"text","text":"Increments the stepper’s value."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()","title":"accessibilityLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityLabel"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilitylabel()","kind":"symbol","type":"topic","role":"symbol","required":true,"abstract":[{"type":"text","text":"Returns a short description of the stepper."}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityLabel"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformIncrement()","title":"accessibilityPerformIncrement()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformIncrement"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilityperformincrement()","kind":"symbol","type":"topic","role":"symbol","required":true,"abstract":[{"type":"text","text":"Increments the stepper’s value."}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformIncrement"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()":{"type":"topic","abstract":[{"text":"Decrements the stepper’s value.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityPerformDecrement","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformDecrement"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilityperformdecrement()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()","title":"accessibilityPerformDecrement()","required":true},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()","title":"accessibilityValue()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nsaccessibilitystepper/accessibilityvalue()","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns the stepper’s value."}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/valueChanged":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/valueChanged","title":"valueChanged","abstract":[{"type":"text","text":"This notification is posted after an accessibility element’s value changes. Post this notification using the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)","isActive":true},{"type":"text","text":" function instead of an "},{"type":"codeVoice","code":"NSNotificationCenter"},{"type":"text","text":" instance."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAccessibility","preciseIdentifier":"c:@S@NSAccessibility"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"c:@T@NSAccessibilityNotificationName"}],"url":"/documentation/appkit/nsaccessibility-swift.struct/notification/valuechanged","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityValueChangedNotification"}]},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper","title":"NSAccessibilityStepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityStepper"}],"url":"/documentation/appkit/nsaccessibilitystepper","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a stepper."}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityStepper"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"post"},{"kind":"text","text":"("},{"kind":"externalParam","text":"element"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@NSAccessibility","text":"NSAccessibility"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAccessibilityNotificationName","text":"Notification"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Sends a notification to any observing assistive apps."}],"url":"/documentation/appkit/nsaccessibility-swift.struct/post(element:notification:)","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityPostNotification"}],"title":"post(element:notification:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"accessibilityPerformIncrement","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityPerformIncrement","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Supporting-Accessibility","title":"Supporting Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityPerformDecrement()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStepper/accessibilityValue()"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"accessibilityPerformIncrement","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"/primaryContentSections/1","value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the action was successfully triggered; otherwise, ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":". This method does not indicate the success or failure of the action, just the fact that the action was successfully triggered.","type":"text"}]}],"kind":"content"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityLabel()/title","value":"accessibilityLabel","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityLabel()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityLabel","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformIncrement()/title","value":"accessibilityPerformIncrement","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformIncrement()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformIncrement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformDecrement()/title","value":"accessibilityPerformDecrement","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityPerformDecrement()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformDecrement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityValue()/title","value":"accessibilityValue","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper~1accessibilityValue()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityValue"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1valueChanged/title","value":"NSAccessibilityValueChangedNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1valueChanged/fragments","value":[{"text":"NSAccessibilityValueChangedNotification","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper/title","value":"NSAccessibilityStepper","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper/fragments","value":[{"kind":"identifier","text":"NSAccessibilityStepper"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStepper/navigatorTitle","value":[{"text":"NSAccessibilityStepper","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/title","value":"NSAccessibilityPostNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/fragments","value":[{"kind":"identifier","text":"NSAccessibilityPostNotification"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}