{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal"]]},"metadata":{"extendedModule":"UIKit","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Performer"}],"externalID":"c:@E@UITextDropPerformer","modules":[{"name":"UIKit"}],"title":"UITextDropProposal.Performer","role":"symbol","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"11.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"11.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}],"navigatorTitle":[{"kind":"identifier","text":"Performer"}],"symbolKind":"enum"},"abstract":[{"type":"text","text":"The performers that are responsible for handling the drop operation."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer"},"seeAlsoSections":[{"generated":true,"title":"Drop management","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropRequest","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Action","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/ProgressMode"],"anchor":"Drop-management"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Performer"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"A performer is responsible for:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Proving a preview for the drop activity."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Loading data from the item providers."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Inserting the data into the text view."}]}]}],"type":"unorderedList"}]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uitextdropproposal/performer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitextdropproposal/performer"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Performers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate"],"anchor":"Performers"},{"generated":true,"title":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/init(rawValue:)"],"anchor":"Initializers"}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/init(rawValue:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/init(rawValue:)","abstract":[],"url":"/documentation/uikit/uitextdropproposal/performer/init(rawvalue:)","type":"topic","role":"symbol","kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropRequest":{"kind":"symbol","role":"symbol","title":"UITextDropRequest","navigatorTitle":[{"kind":"identifier","text":"UITextDropRequest"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropRequest"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropRequest","url":"/documentation/uikit/uitextdroprequest","abstract":[{"text":"The interface for specifying the attributes of a drop request for a text view.","type":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Action":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Action"}],"kind":"symbol","abstract":[{"text":"The text drop action styles for text views.","type":"text"}],"url":"/documentation/uikit/uitextdropproposal/action","title":"UITextDropProposal.Action","navigatorTitle":[{"kind":"identifier","text":"Action"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Action","role":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view":{"title":"UITextDropProposal.Performer.view","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view","type":"topic","url":"/documentation/uikit/uitextdropproposal/performer/view","abstract":[{"type":"text","text":"A performer type that indicates that the text view is responsible for doing the drop operation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDropPerformerView"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer":{"title":"UITextDropProposal.Performer","abstract":[{"type":"text","text":"The performers that are responsible for handling the drop operation."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer","url":"/documentation/uikit/uitextdropproposal/performer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Performer"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Performer","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/ProgressMode":{"navigatorTitle":[{"text":"ProgressMode","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The text drop progress styles for user-visible progress indication."}],"url":"/documentation/uikit/uitextdropproposal/progressmode","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/ProgressMode","title":"UITextDropProposal.ProgressMode","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressMode","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate":{"title":"UITextDropProposal.Performer.delegate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate","type":"topic","url":"/documentation/uikit/uitextdropproposal/performer/delegate","abstract":[{"type":"text","text":"A performer type that indicates the delegate object is responsible for doing the drop operation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDropPerformerDelegate"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropProposal"}],"role":"symbol","abstract":[{"type":"text","text":"A proposed configuration for the behavior of a text drop interaction."}],"title":"UITextDropProposal","type":"topic","url":"/documentation/uikit/uitextdropproposal","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDropProposal"}]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger","kind":"symbol","type":"topic","title":"NSUInteger"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"11.0","deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"11.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration","op":"replace"},{"path":"/metadata/title","value":"UITextDropPerformer","op":"replace"},{"path":"/metadata/symbolKind","value":"enum","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"UITextDropPerformer","kind":"identifier"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"UITextDropPerformer","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate"],"title":"Performers","anchor":"Performers"}],"op":"replace"},{"path":"/relationshipsSections","value":null,"op":"replace"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropRequest","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Action","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/ProgressMode"],"anchor":"Drop-management","title":"Drop management"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDropPerformer","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropRequest/title","value":"UITextDropRequest","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropRequest/fragments","value":[{"text":"UITextDropRequest","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropRequest/navigatorTitle","value":[{"text":"UITextDropRequest","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Action/title","value":"UITextDropAction","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Action/fragments","value":[{"text":"UITextDropAction","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Action/navigatorTitle","value":[{"text":"UITextDropAction","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1view/title","value":"UITextDropPerformerView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1view/fragments","value":[{"kind":"identifier","text":"UITextDropPerformerView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer/title","value":"UITextDropPerformer","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer/fragments","value":[{"kind":"identifier","text":"UITextDropPerformer"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer/navigatorTitle","value":[{"text":"UITextDropPerformer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1ProgressMode/title","value":"UITextDropProgressMode","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1ProgressMode/fragments","value":[{"text":"UITextDropProgressMode","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1ProgressMode/navigatorTitle","value":[{"text":"UITextDropProgressMode","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1delegate/title","value":"UITextDropPerformerDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1delegate/fragments","value":[{"kind":"identifier","text":"UITextDropPerformerDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal/title","value":"UITextDropProposal","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal/fragments","value":[{"text":"UITextDropProposal","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal/navigatorTitle","value":[{"text":"UITextDropProposal","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}