{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICReturnCode@ICReturnScannerFailedToCompleteScan",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scannerFailedToCompleteScan"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICReturnScannerFailedToCompleteScan"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICReturn.Code.scannerFailedToCompleteScan"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scannerFailedToCompleteScan"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn": {
      "abstract": [
        {
          "text": "An error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ICReturn",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationTimedOut"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnCommunicationTimedOut"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.communicationTimedOut",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/communicationtimedout"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteFilesCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeleteFilesCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deleteFilesCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deletefilescanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteFilesFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeleteFilesFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deleteFilesFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deletefilesfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCommandGeneralFailure"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCommandGeneralFailure"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCommandGeneralFailure",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecommandgeneralfailure"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCouldNotPair"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCouldNotPair"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCouldNotPair",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecouldnotpair"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCouldNotUnpair"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceCouldNotUnpair"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceCouldNotUnpair",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicecouldnotunpair"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToCloseSession"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToCloseSession"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToCloseSession",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtoclosesession"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer": {
      "abstract": [
        {
          "text": "Failed to complete a data transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToCompleteTransfer"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToCompleteTransfer"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToCompleteTransfer",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtocompletetransfer"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToOpenSession"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToOpenSession"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToOpenSession",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtoopensession"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData": {
      "abstract": [
        {
          "text": "Failed to send data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToSendData"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToSendData"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToSendData",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtosenddata"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceFailedToTakePicture"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceFailedToTakePicture"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceFailedToTakePicture",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicefailedtotakepicture"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIsBusyEnumerating"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsBusyEnumerating"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceIsBusyEnumerating",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceisbusyenumerating"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIsPasscodeLocked"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceIsPasscodeLocked"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceIsPasscodeLocked",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceispasscodelocked"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNeedsCredentials"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceNeedsCredentials"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceNeedsCredentials",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/deviceneedscredentials"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSoftwareInstallationCanceled"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnDeviceSoftwareInstallationCanceled"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.deviceSoftwareInstallationCanceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/devicesoftwareinstallationcanceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scannerFailedToCompleteScan"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/scannerFailedToCompleteScan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnScannerFailedToCompleteScan"
        }
      ],
      "role": "symbol",
      "title": "ICReturn.Code.scannerFailedToCompleteScan",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturn/code/scannerfailedtocompletescan"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICReturnScannerFailedToCompleteScan"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerFailedToCompleteScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/communicationTimedOut",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesCanceled",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deleteFilesFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCommandGeneralFailure",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotPair",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceCouldNotUnpair",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCloseSession",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToCompleteTransfer",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToOpenSession",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToSendData",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceFailedToTakePicture",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsBusyEnumerating",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceIsPasscodeLocked",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceNeedsCredentials",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturn/Code/deviceSoftwareInstallationCanceled"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICReturnScannerFailedToCompleteScan"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsPasscodeLocked/title",
          "value": "ICReturnDeviceIsPasscodeLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsPasscodeLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceIsPasscodeLocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCanceled/title",
          "value": "ICReturnDeviceSoftwareInstallationCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceSoftwareInstallationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceSoftwareInstallationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotUnpair/title",
          "value": "ICReturnDeviceCouldNotUnpair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotUnpair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCouldNotUnpair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceNeedsCredentials/title",
          "value": "ICReturnDeviceNeedsCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceNeedsCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceNeedsCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCloseSession/title",
          "value": "ICReturnDeviceFailedToCloseSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCloseSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToCloseSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToCompleteScan/title",
          "value": "ICReturnScannerFailedToCompleteScan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1scannerFailedToCompleteScan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnScannerFailedToCompleteScan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToOpenSession/title",
          "value": "ICReturnDeviceFailedToOpenSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToOpenSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToOpenSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesFailed/title",
          "value": "ICReturnDeleteFilesFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeleteFilesFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/title",
          "value": "ICReturnCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1communicationTimedOut/title",
          "value": "ICReturnCommunicationTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1communicationTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnCommunicationTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsBusyEnumerating/title",
          "value": "ICReturnDeviceIsBusyEnumerating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceIsBusyEnumerating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceIsBusyEnumerating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesCanceled/title",
          "value": "ICReturnDeleteFilesCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deleteFilesCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeleteFilesCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCompleteTransfer/title",
          "value": "ICReturnDeviceFailedToCompleteTransfer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToCompleteTransfer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToCompleteTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotPair/title",
          "value": "ICReturnDeviceCouldNotPair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCouldNotPair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCouldNotPair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCommandGeneralFailure/title",
          "value": "ICReturnDeviceCommandGeneralFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceCommandGeneralFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceCommandGeneralFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToSendData/title",
          "value": "ICReturnDeviceFailedToSendData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToSendData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToSendData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToTakePicture/title",
          "value": "ICReturnDeviceFailedToTakePicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturn~1Code~1deviceFailedToTakePicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnDeviceFailedToTakePicture"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturn/code/scannerfailedtocompletescan"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icreturn/code/scannerfailedtocompletescan"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
