{
  "abstract": [
    {
      "text": "The handler to call when the user is done composing a post.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.social/documentation/Social",
        "doc://com.apple.social/documentation/Social/SLComposeViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SLComposeViewController(py)completionHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SLComposeViewControllerCompletionHandler",
        "text": "SLComposeViewControllerCompletionHandler"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Social"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "completionHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "completionHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SLComposeViewControllerCompletionHandler",
              "text": "SLComposeViewControllerCompletionHandler"
            },
            {
              "kind": "text",
              "text": "! { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The handler has a single parameter that indicates whether the user finished or cancelled composing the post. This block is not guaranteed to be called on any particular thread. Do not dismiss the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your completion handler—the system will do so automatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.social/documentation/Social": {
      "abstract": [
        {
          "text": "Post content to supported social networking services, using standard system interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social",
      "kind": "symbol",
      "role": "collection",
      "title": "Social",
      "type": "topic",
      "url": "/documentation/social"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewController": {
      "abstract": [
        {
          "text": "A view controller that allows the user to compose social media posts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewController",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontroller"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler": {
      "abstract": [
        {
          "text": "The handler to call when the user is done composing a post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SLComposeViewControllerCompletionHandler",
          "text": "SLComposeViewControllerCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionHandler"
        }
      ],
      "role": "symbol",
      "title": "completionHandler",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontroller/completionhandler"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler": {
      "abstract": [
        {
          "text": "Defines a handler to call when the user finishes composing a post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewControllerCompletionHandler",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollercompletionhandler"
    },
    "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult": {
      "abstract": [
        {
          "text": "Possible values for the ",
          "type": "text"
        },
        {
          "code": "result",
          "type": "codeVoice"
        },
        {
          "text": " parameter of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewController/completionHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerResult"
        }
      ],
      "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SLComposeViewControllerResult"
        }
      ],
      "role": "symbol",
      "title": "SLComposeViewControllerResult",
      "type": "topic",
      "url": "/documentation/social/slcomposeviewcontrollerresult"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-the-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler",
        "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult"
      ],
      "title": "Processing the Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "completionHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.social/documentation/Social",
                "doc://com.apple.social/documentation/Social/SLComposeViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Processing-the-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler",
                "doc://com.apple.social/documentation/Social/SLComposeViewControllerResult"
              ],
              "title": "Processing the Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.social/documentation/Social/SLComposeViewControllerCompletionHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SLComposeViewControllerCompletionHandler",
                    "text": "SLComposeViewControllerCompletionHandler"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerCompletionHandler/title",
          "value": "SLComposeViewControllerCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController~1completionHandler/title",
          "value": "completionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController~1completionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController/title",
          "value": "SLComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult/title",
          "value": "SLComposeViewControllerResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.social~1documentation~1Social~1SLComposeViewControllerResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SLComposeViewControllerResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/social/slcomposeviewcontroller/completionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/social/slcomposeviewcontroller/completionhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
