{
  "abstract": [
    {
      "text": "An array of strings that identifies the reasons your app or third-party SDK uses required reason API.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPITypeReasons"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:App_Privacy_Configuration.NSPrivacyAccessedAPITypes.NSPrivacyAccessedAPITypeReasons",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrivacyAccessedAPITypeReasons"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSPrivacyAccessedAPITypeReasons"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Privacy Accessed API Reasons",
        "name": "NSPrivacyAccessedAPITypeReasons",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to display file timestamps to the person using the device.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Information accessed for this reason, or any derived information, may not be sent off-device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "DDA9.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access the timestamps, size, or other metadata of files inside the app container, app group container, or the app’s CloudKit container.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "C617.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access the timestamps, size, or other metadata of files or directories that the user specifically granted access to, such as using a document picker view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "3B52.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason if your third-party SDK is providing a wrapper function around file timestamp API(s) for the app to use, and you only access the file timestamp APIs when the app calls your wrapper function. This reason may only be declared by third-party SDKs. This reason may not be declared if your third-party SDK was created primarily to wrap required reason API(s).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be used for your third-party SDK’s own purposes or sent off-device by your third-party SDK.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "0A2A.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access the system boot time in order to measure the amount of time that has elapsed between events that occurred within the app or to perform calculations to enable timers.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception for information about the amount of time that has elapsed between events that occurred within the app, which may be sent off-device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "35F9.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access the system boot time to calculate absolute timestamps for events that occurred within your app, such as events related to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AVFAudio",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " frameworks.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Absolute timestamps for events that occurred within your app may be sent off-device. System boot time accessed for this reason, or any other information derived from system boot time, may not be sent off-device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "8FFB.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to include system boot time information in an optional bug report that the person using the device chooses to submit. The system boot time information must be prominently displayed to the person as part of the report.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "3D61.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to display disk space information to the person using the device. Disk space may be displayed in units of information (such as bytes) or units of time combined with a media type (such as minutes of HD video).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to send disk space information over the local network to another device operated by the same person only for the purpose of displaying disk space information on that device; this exception only applies if the user has provided explicit permission to send disk space information, and the information may not be sent over the Internet.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "85F4.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to check whether there is sufficient disk space to write files, or to check whether the disk space is low so that the app can delete files when the disk space is low. The app must behave differently based on disk space in a way that is observable to users.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to avoid downloading files from a server when disk space is insufficient.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "E174.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to include disk space information in an optional bug report that the person using the device chooses to submit. The disk space information must be prominently displayed to the person as part of the report.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may be sent off-device only after the user affirmatively chooses to submit the specific bug report including disk space information, and only for the purpose of investigating or responding to the bug report.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "7D9E.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason if your app is a health research app, and you access this API category to detect and inform research participants about low disk space impacting the research data collection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Your app must comply with ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/app-store/review/guidelines/#health-and-health-research",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Your app must not offer any functionality other than providing information about and allowing people to participate in health research.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "B728.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason if your app is a custom keyboard app, and you access this API category to determine the keyboards that are active on the device.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Providing a systemwide custom keyboard to the user must be the primary functionality of the app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be sent off-device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "3EC4.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access active keyboard information to present the correct customized user interface to the person using the device. The app must have text fields for entering or editing text and must behave differently based on active keyboards in a way that is observable to users.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be sent off-device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "54BD.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access user defaults to read and write information that is only accessible to the app itself.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This reason does not permit reading information that was written by other apps or the system, or writing information that can be accessed by other apps.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "CA92.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access user defaults to read and write information that is only accessible to the apps, app extensions, and App Clips that are members of the same App Group as the app itself.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This reason does not permit reading information that was written by apps, app extensions, or App Clips outside the same App Group or by the system. Your app is not responsible if the system provides information from the global domain because a key is not present in your requested domain while your app is attempting to read information that apps, app extensions, or App Clips in your app’s App Group write.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This reason also does not permit writing information that can be accessed by apps, app extensions, or App Clips outside the same App Group.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "1C8F.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason if your third-party SDK is providing a wrapper function around user defaults API(s) for the app to use, and you only access the user defaults APIs when the app calls your wrapper function. This reason may only be declared by third-party SDKs. This reason may not be declared if your third-party SDK was created primarily to wrap required reason API(s).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Information accessed for this reason, or any derived information, may not be used for your third-party SDK’s own purposes or sent off-device by your third-party SDK.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "C56D.1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Declare this reason to access user defaults to read the ",
                  "type": "text"
                },
                {
                  "code": "com.apple.configuration.managed",
                  "type": "codeVoice"
                },
                {
                  "text": " key to retrieve the managed app configuration set by MDM, or to set the ",
                  "type": "text"
                },
                {
                  "code": "com.apple.feedback.managed",
                  "type": "codeVoice"
                },
                {
                  "text": " key to store feedback information to be queried over MDM, as described in the Apple Mobile Device Management Protocol Reference documentation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "AC6B.1"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For information on which reasons your app or third-party SDK declares for each category of required reasons API it uses, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPIType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information on required reason API, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration": {
      "abstract": [
        {
          "text": "A data structure that represents the root object in a privacy manifest file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
      "kind": "symbol",
      "name": "App Privacy Configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "App Privacy Configuration"
        }
      ],
      "role": "symbol",
      "title": "App Privacy Configuration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes": {
      "abstract": [
        {
          "text": "A list of dictionaries that report the privacy accessed API your app or third-party SDK uses.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Accessed API Types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes",
      "kind": "symbol",
      "name": "NSPrivacyAccessedAPITypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyAccessedAPITypes"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyAccessedAPITypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacyaccessedapitypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPIType": {
      "abstract": [
        {
          "text": "A string that describes a category of required reason API your app or third-party SDK uses.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Accessed API Type",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPIType",
      "kind": "symbol",
      "name": "NSPrivacyAccessedAPIType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyAccessedAPIType"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyAccessedAPIType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacyaccessedapitypes/nsprivacyaccessedapitype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPITypeReasons": {
      "abstract": [
        {
          "text": "An array of strings that identifies the reasons your app or third-party SDK uses required reason API.",
          "type": "text"
        }
      ],
      "ideTitle": "Privacy Accessed API Reasons",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPITypeReasons",
      "kind": "symbol",
      "name": "NSPrivacyAccessedAPITypeReasons",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrivacyAccessedAPITypeReasons"
        }
      ],
      "role": "symbol",
      "title": "NSPrivacyAccessedAPITypeReasons",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/app-privacy-configuration/nsprivacyaccessedapitypes/nsprivacyaccessedapitypereasons"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api": {
      "abstract": [
        {
          "text": "Ensure your use of covered API is consistent with policy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/describing-use-of-required-reason-api",
      "kind": "article",
      "role": "article",
      "title": "Describing use of required reason API",
      "type": "topic",
      "url": "/documentation/bundleresources/describing-use-of-required-reason-api"
    },
    "doc://com.apple.documentation/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/AVFAudio"
    },
    "doc://com.apple.documentation/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/UIKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/app-store/review/guidelines/#health-and-health-research": {
      "identifier": "https://developer.apple.com/app-store/review/guidelines/#health-and-health-research",
      "title": "App Store Review Guideline §5.1.3",
      "titleInlineContent": [
        {
          "text": "App Store Review Guideline §5.1.3",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/app-store/review/guidelines/#health-and-health-research"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-privacy-accessed-API-usage",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPIType"
      ],
      "title": "Reporting privacy accessed API usage"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrivacyAccessedAPITypeReasons"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyAccessedAPITypeReasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration",
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-privacy-accessed-API-usage",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/App-Privacy-Configuration/NSPrivacyAccessedAPITypes/NSPrivacyAccessedAPIType"
              ],
              "title": "Reporting privacy accessed API usage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes~1NSPrivacyAccessedAPITypeReasons/title",
          "value": "NSPrivacyAccessedAPITypeReasons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes~1NSPrivacyAccessedAPITypeReasons/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyAccessedAPITypeReasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/title",
          "value": "App Privacy Configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "App Privacy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes/title",
          "value": "NSPrivacyAccessedAPITypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyAccessedAPITypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes~1NSPrivacyAccessedAPIType/title",
          "value": "NSPrivacyAccessedAPIType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1App-Privacy-Configuration~1NSPrivacyAccessedAPITypes~1NSPrivacyAccessedAPIType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrivacyAccessedAPIType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacyaccessedapitypes/nsprivacyaccessedapitypereasons"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/app-privacy-configuration/nsprivacyaccessedapitypes/nsprivacyaccessedapitypereasons"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
