{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_4-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "tvOS 15.4 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The tvOS 15.4 SDK provides support to develop tvOS apps for Apple TV devices running tvOS 15.4. The SDK comes bundled with Xcode 13.3.1, available from the Mac App Store. For information on the compatibility requirements for Xcode 13.3.1, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-13_3_1-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "General",
          "level": 3,
          "text": "General",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Captive Wi-Fi network support on tvOS allows you to use your iPhone or iPad to connect your Apple TV to networks that need additional sign-in steps, like at hotels or dorms. (8351052)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "libc++",
          "level": 3,
          "text": "libc++",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The following new C++20 and C++23 features are now implemented:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "C++20 library concepts defined in ",
                              "type": "text"
                            },
                            {
                              "code": "<concepts>",
                              "type": "codeVoice"
                            },
                            {
                              "text": ".",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "code": "constexpr",
                              "type": "codeVoice"
                            },
                            {
                              "text": " for ",
                              "type": "text"
                            },
                            {
                              "code": "std::swap()",
                              "type": "codeVoice"
                            },
                            {
                              "text": " and swap-related functions.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Miscellaneous ",
                              "type": "text"
                            },
                            {
                              "code": "constexpr",
                              "type": "codeVoice"
                            },
                            {
                              "text": "-ification in the library.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "code": "std::atomic",
                              "type": "codeVoice"
                            },
                            {
                              "text": " now default initializes as expected.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A ",
                              "type": "text"
                            },
                            {
                              "code": ".contains()",
                              "type": "codeVoice"
                            },
                            {
                              "text": " method for associative containers.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Added ",
                              "type": "text"
                            },
                            {
                              "code": "std::bind_front()",
                              "type": "codeVoice"
                            },
                            {
                              "text": ". (88131816)",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Deprecations",
          "level": 4,
          "text": "Deprecations",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Some extensions in ",
                      "type": "text"
                    },
                    {
                      "code": "std::tuple",
                      "type": "codeVoice"
                    },
                    {
                      "text": " were removed to fix bugs caused by those extensions:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Tuples can no longer be constructed from fewer than the number of elements in the tuple. Previously, elements that weren’t specified were default-constructed; now this is a compiler error.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A tuple can no longer be constructed from an array.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "The ",
                              "type": "text"
                            },
                            {
                              "code": "std::result_of",
                              "type": "codeVoice"
                            },
                            {
                              "text": " and ",
                              "type": "text"
                            },
                            {
                              "code": "std::is_literal_type",
                              "type": "codeVoice"
                            },
                            {
                              "text": " type traits are no longer available in C++20 mode, as specified in the Standard.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "StoreKit",
          "level": 3,
          "text": "StoreKit",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKitTest/SKTestSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " has three new methods to simulate a subscription requiring price increase consent, simulate consenting to a pending price increase, and simulate declining a price increase in automated tests. (84556183)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "SKTestSession",
                      "type": "codeVoice"
                    },
                    {
                      "text": " has two new Boolean properties to simulate billing retry and grace period in automated tests. You can identify and simulate the resolution of billing retry issues using the same APIs as interrupted purchases. (83956205)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Users can now test the billing retry and grace period states using StoreKit Testing in Xcode. Use Xcode 13.3 or later to enable billing retry testing and toggle whether the app offers a grace period. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/isInBillingRetry",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/gracePeriodExpirationDate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to handle these states in the app. (83938270)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You can now test offer codes with StoreKit Testing in Xcode. Configure offers for codes in Xcode 13.3 or later, and test redeeming them using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueue/presentCodeRedemptionSheet()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (63692551)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Users can test subscription price increase behavior using StoreKit Testing in Xcode. Use Xcode 13.3 or later to set a price increase, then use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueueDelegate/paymentQueueShouldShowPriceConsent(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueue/showPriceConsentIfNeeded()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/priceIncreaseStatus-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in the app. (58770817)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "StoreKit",
                      "type": "codeVoice"
                    },
                    {
                      "text": " error types now conform to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/localizederror",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (78735204)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Some types in ",
                      "type": "text"
                    },
                    {
                      "code": "StoreKit",
                      "type": "codeVoice"
                    },
                    {
                      "text": " now have a ",
                      "type": "text"
                    },
                    {
                      "code": "localizedDescription",
                      "type": "codeVoice"
                    },
                    {
                      "text": " read-only ",
                      "type": "text"
                    },
                    {
                      "code": "String",
                      "type": "codeVoice"
                    },
                    {
                      "text": " instance property. This property can be used to get a human-readable description of the value, localized for the device’s current locale. These types include: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/ProductType",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalState",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/expirationReason-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/priceIncreaseStatus-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/OfferType-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionOffer/OfferType",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionOffer/PaymentMode-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionPeriod/Unit-swift.enum",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/RevocationReason-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/OwnershipType-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (78735060)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now emits unfinished transactions when iterating for the first time. (85294525)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When using StoreKit Testing in Xcode, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/updates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now emits all updated transactions. (85877689)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/Product/ProductType": {
      "abstract": [
        {
          "text": "The types of in-app purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProductType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/ProductType",
      "kind": "symbol",
      "role": "symbol",
      "title": "Product.ProductType",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/ProductType"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/expirationReason-swift.property": {
      "abstract": [
        {
          "text": "The reason the auto-renewable subscription expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expirationReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV",
          "text": "SubscriptionInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV07RenewalE0V",
          "text": "RenewalInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV07RenewalE0V16ExpirationReasonV",
          "text": "ExpirationReason"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/expirationReason-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "expirationReason",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/expirationReason-swift.property"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/gracePeriodExpirationDate": {
      "abstract": [
        {
          "text": "The date the billing grace period expires for the auto-renewable subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gracePeriodExpirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/gracePeriodExpirationDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "gracePeriodExpirationDate",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/gracePeriodExpirationDate"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/isInBillingRetry": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an auto-renewable subscription is in the billing retry period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInBillingRetry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/isInBillingRetry",
      "kind": "symbol",
      "role": "symbol",
      "title": "isInBillingRetry",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/isInBillingRetry"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/priceIncreaseStatus-swift.property": {
      "abstract": [
        {
          "text": "The status that indicates whether the auto-renewable subscription is subject to a price increase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priceIncreaseStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV",
          "text": "Product"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV",
          "text": "SubscriptionInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV07RenewalE0V",
          "text": "RenewalInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit7ProductV16SubscriptionInfoV07RenewalE0V19PriceIncreaseStatusO",
          "text": "PriceIncreaseStatus"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/priceIncreaseStatus-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "priceIncreaseStatus",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionInfo/RenewalInfo/priceIncreaseStatus-swift.property"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalState": {
      "abstract": [
        {
          "text": "The renewal states of auto-renewable subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RenewalState"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionInfo/RenewalState",
      "kind": "symbol",
      "role": "symbol",
      "title": "Product.SubscriptionInfo.RenewalState",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionInfo/RenewalState"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionOffer/OfferType": {
      "abstract": [
        {
          "text": "The types of offers for auto-renewable subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OfferType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionOffer/OfferType",
      "kind": "symbol",
      "role": "symbol",
      "title": "Product.SubscriptionOffer.OfferType",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionOffer/OfferType"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionOffer/PaymentMode-swift.struct": {
      "abstract": [
        {
          "text": "The payment modes for subscription offers that apply to a transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaymentMode"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionOffer/PaymentMode-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "Product.SubscriptionOffer.PaymentMode",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionOffer/PaymentMode-swift.struct"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionPeriod/Unit-swift.enum": {
      "abstract": [
        {
          "text": "Units of time that describe subscription periods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Product/SubscriptionPeriod/Unit-swift.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "Product.SubscriptionPeriod.Unit",
      "type": "topic",
      "url": "/documentation/StoreKit/Product/SubscriptionPeriod/Unit-swift.enum"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueue/presentCodeRedemptionSheet()": {
      "abstract": [
        {
          "text": "Displays a sheet that enables customers to redeem subscription offer codes that you configure in App Store Connect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentCodeRedemptionSheet"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueue/presentCodeRedemptionSheet()",
      "kind": "symbol",
      "role": "symbol",
      "title": "presentCodeRedemptionSheet()",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPaymentQueue/presentCodeRedemptionSheet()"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueue/showPriceConsentIfNeeded()": {
      "abstract": [
        {
          "text": "Asks the system to display the price consent sheet if the user hasn’t yet responded to a subscription price increase.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showPriceConsentIfNeeded"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueue/showPriceConsentIfNeeded()",
      "kind": "symbol",
      "role": "symbol",
      "title": "showPriceConsentIfNeeded()",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPaymentQueue/showPriceConsentIfNeeded()"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueueDelegate/paymentQueueShouldShowPriceConsent(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to immediately display a price consent sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentQueueShouldShowPriceConsent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "paymentQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
          "text": "SKPaymentQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentQueueDelegate/paymentQueueShouldShowPriceConsent(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "paymentQueueShouldShowPriceConsent(_:)",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPaymentQueueDelegate/paymentQueueShouldShowPriceConsent(_:)"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/OfferType-swift.struct": {
      "abstract": [
        {
          "text": "The types of subscription offers for auto-renewable subscriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OfferType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/OfferType-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "Transaction.OfferType",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/OfferType-swift.struct"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/OwnershipType-swift.struct": {
      "abstract": [
        {
          "text": "The types the system uses to describe whether the user purchased the product or it’s available to them through Family Sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OwnershipType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/OwnershipType-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "Transaction.OwnershipType",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/OwnershipType-swift.struct"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/RevocationReason-swift.struct": {
      "abstract": [
        {
          "text": "Reasons that describe why the App Store may refund a transaction or revoke it from Family Sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RevocationReason"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/RevocationReason-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "Transaction.RevocationReason",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/RevocationReason-swift.struct"
    },
    "doc://com.apple.documentation/documentation/StoreKit/Transaction/updates": {
      "abstract": [
        {
          "text": "The asynchronous sequence that emits a transaction when the system creates or updates transactions that occur outside the app or on other devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV",
          "text": "Transaction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8StoreKit11TransactionV12TransactionsV",
          "text": "Transactions"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/Transaction/updates",
      "kind": "symbol",
      "role": "symbol",
      "title": "updates",
      "type": "topic",
      "url": "/documentation/StoreKit/Transaction/updates"
    },
    "doc://com.apple.documentation/documentation/StoreKitTest/SKTestSession": {
      "abstract": [
        {
          "text": "The controls and environment configuration you use to test StoreKit transactions in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKitTest/SKTestSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKTestSession",
      "type": "topic",
      "url": "/documentation/StoreKitTest/SKTestSession"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-13_3_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-13_3_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 13.3.1 Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes/xcode-13_3_1-release-notes"
    },
    "doc://com.apple.documentation/documentation/foundation/localizederror": {
      "abstract": [
        {
          "text": "A specialized error that provides localized messages describing the error and why it occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "LocalizedError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/localizederror",
      "kind": "symbol",
      "role": "symbol",
      "title": "LocalizedError",
      "type": "topic",
      "url": "/documentation/foundation/localizederror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 15 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-15-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 15.1 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-15_1-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 15.2 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-15_2-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 15.3 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-15_3-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 15.5 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-15_5-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 15.6 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-15_6-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the tvOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "tvOS Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "tvOS-15",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_6-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_5-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_3-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_2-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15_1-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-15-release-notes"
      ],
      "title": "tvOS 15"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentQueueDelegate~1paymentQueueShouldShowPriceConsent(_:)/title",
          "value": "paymentQueueShouldShowPriceConsent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentQueueDelegate~1paymentQueueShouldShowPriceConsent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "paymentQueueShouldShowPriceConsent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKPaymentQueue",
              "text": "SKPaymentQueue"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "paymentQueue"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKitTest~1SKTestSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKTestSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentQueue~1showPriceConsentIfNeeded()/title",
          "value": "showPriceConsentIfNeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentQueue~1showPriceConsentIfNeeded()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "showPriceConsentIfNeeded"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentQueue~1presentCodeRedemptionSheet()/title",
          "value": "presentCodeRedemptionSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentQueue~1presentCodeRedemptionSheet()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "presentCodeRedemptionSheet"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
