{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_2-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "tvOS 12.2 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The tvOS 12.2 SDK provides support for developing tvOS apps for Apple TV devices running tvOS 12.2. The SDK comes bundled with Xcode 10.2 available from the Mac App Store. For information on the compatibility requirements for Xcode 10.2, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "App-Store",
          "level": 3,
          "text": "App Store",
          "type": "heading"
        },
        {
          "anchor": "Promoting-Your-Subscriptions-with-New-Offers",
          "level": 4,
          "text": "Promoting Your Subscriptions with New Offers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "StoreKit now supports subscription offers in addition to introductory offers, so apps with auto-renewable subscriptions can provide a discounted price for a specific duration for existing and previously subscribed customers. You can use subscription offers to help win back subscribers who have canceled their subscriptions or promote an upgrade to another subscription at a special price. Customers can accept the offer even if they’ve already completed an introductory offer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "StoreKit introduces a new array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProductDiscount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects within the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProduct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to display offers within your app to eligible customers. Add a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentDiscount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object within the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to allow these offers to be accepted by the customer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/SKPayment": {
      "abstract": [
        {
          "text": "A request to the App Store to process payment for additional functionality that your app offers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPayment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKPayment",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPayment"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPaymentDiscount": {
      "abstract": [
        {
          "text": "The signed discount to apply to a payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentDiscount"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentDiscount",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKPaymentDiscount",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPaymentDiscount"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKProduct": {
      "abstract": [
        {
          "text": "Information about a registered product in App Store Connect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProduct"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProduct",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKProduct",
      "type": "topic",
      "url": "/documentation/StoreKit/SKProduct"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/StoreKit/SKProductDiscount"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes": {
      "abstract": [
        {
          "text": "Learn about changes to Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes",
      "kind": "article",
      "role": "collection",
      "title": "Xcode Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 12 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-12-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_1_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_1_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 12.1.1 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-12_1_1-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_1_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_1_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 12.1.2 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-12_1_2-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_4-release-notes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "tvOS 12.4 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-12_4-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the tvOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "tvOS Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "tvOS-12",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_4-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_1_2-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12_1_1-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-12-release-notes"
      ],
      "title": "tvOS 12"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentDiscount/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKPaymentDiscount"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPayment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKPayment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKProduct/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKProduct"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
