{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "tvOS 14 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The tvOS 14 SDK provides support to develop tvOS apps for Apple TV devices running tvOS 14. The SDK comes bundled with Xcode 12, available from the Mac App Store. For information on the compatibility requirements for Xcode 12, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "AVKit",
          "level": 3,
          "text": "AVKit",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Picture in Picture on tvOS allows for simultaneous video playback and the ability to swap between full-screen content and Picture in Picture. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPlayerViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for adopting Picture in Picture in a standard player or AVKit framework’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPictureInPictureController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class for your custom player. (54986706)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Game-Center",
          "level": 3,
          "text": "Game Center",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With multiuser support for gaming, your game can switch dynamically between users, and use both Game Center and iCloud to keep track of multiple players’ individual game levels, leaderboards, and invitations. The User Management entitlement has been expanded to include ",
                      "type": "text"
                    },
                    {
                      "code": "runs-as-current-user",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". This new value grants access to a separate set of data for your app for each user from Game Center, iCloud, and local storage. (56116380)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Logging",
          "level": 3,
          "text": "Logging",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "New APIs are available for using ",
                      "type": "text"
                    },
                    {
                      "code": "os_log",
                      "type": "codeVoice"
                    },
                    {
                      "text": " from Swift as part of the framework ",
                      "type": "text"
                    },
                    {
                      "code": "os",
                      "type": "codeVoice"
                    },
                    {
                      "text": ":",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A new type, ",
                              "type": "text"
                            },
                            {
                              "identifier": "doc://com.apple.documentation/documentation/os/Logger",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": ", can be instantiated using a subsystem and category, and provides methods for logging at different levels (",
                              "type": "text"
                            },
                            {
                              "code": "Logger.debug",
                              "type": "codeVoice"
                            },
                            {
                              "text": ", ",
                              "type": "text"
                            },
                            {
                              "code": "Logger.error",
                              "type": "codeVoice"
                            },
                            {
                              "text": ", ",
                              "type": "text"
                            },
                            {
                              "code": "Logger.fault",
                              "type": "codeVoice"
                            },
                            {
                              "text": ").",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "The ",
                              "type": "text"
                            },
                            {
                              "code": "Logger",
                              "type": "codeVoice"
                            },
                            {
                              "text": " APIs support specifying most formatting and privacy options supported by legacy  ",
                              "type": "text"
                            },
                            {
                              "identifier": "doc://com.apple.documentation/documentation/os/logging",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": " APIs.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "The new APIs provide significant performance improvements over the legacy APIs.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "You can now pass Swift string interpolation to the ",
                              "type": "text"
                            },
                            {
                              "identifier": "doc://com.apple.documentation/documentation/os/os_log",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": " function.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                },
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Note:",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " The new APIs can’t be back deployed; however, the existing ",
                      "type": "text"
                    },
                    {
                      "code": "os_log",
                      "type": "codeVoice"
                    },
                    {
                      "text": " API remains available for back deployment. (22539144)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "SwiftUI",
          "level": 3,
          "text": "SwiftUI",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now supports adding a secondary “current value label” that describes the current progress level of the task. Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to describe the overall task, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/CurrentValueLabel-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to provide more specific details about the progress of the task. (63580200)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Introduced ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ToolbarItemGroup",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " as a convenient way to place multiple items in a specific location of non-customizable toolbars. (64178863)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Color",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " can be converted to and from ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/uikit/uicolor/1621943-cgcolor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ColorPicker",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " can also now be configured with a binding to a ",
                      "type": "text"
                    },
                    {
                      "code": "CGColor",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". (56939085)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Image",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now redacted when the ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/anyview/redacted(reason:)",
                      "type": "text"
                    },
                    {
                      "text": " modifier is applied. (65047189)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now available and allows a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to appear in-line with the rest of the content in its surrounding container. The style will adapt its appearance for different containers and platforms, such as individual menu items in a menu. (59868844)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " may now be used with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewReader",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (35471164)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " gains a new initializer accepting a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/formatter",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (63641785)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/view/body-swift.property",
                      "type": "text"
                    },
                    {
                      "text": " is now implicitly a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ViewBuilder",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now implicitly a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SceneBuilder",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (63606493)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVKit/AVPictureInPictureController": {
      "abstract": [
        {
          "text": "A controller that responds to user-initiated Picture in Picture playback of video in a floating, resizable window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPictureInPictureController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPictureInPictureController",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPictureInPictureController",
      "type": "topic",
      "url": "/documentation/AVKit/AVPictureInPictureController"
    },
    "doc://com.apple.documentation/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/AVKit/AVPlayerViewController"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property": {
      "abstract": [
        {
          "text": "The content and behavior of the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:7SwiftUI12SceneBuilderV",
          "text": "SceneBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI3AppP4BodyQa",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/App/body-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "body",
      "type": "topic",
      "url": "/documentation/SwiftUI/App/body-swift.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Color": {
      "abstract": [
        {
          "text": "A representation of a color that adapts to a given context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Color"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Color",
      "kind": "symbol",
      "role": "symbol",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/SwiftUI/Color"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ColorPicker": {
      "abstract": [
        {
          "text": "A control used to select a color from the system color picker UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorPicker"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ColorPicker",
      "kind": "symbol",
      "role": "symbol",
      "title": "ColorPicker",
      "type": "topic",
      "url": "/documentation/SwiftUI/ColorPicker"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Image": {
      "abstract": [
        {
          "text": "A view that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Image",
      "kind": "symbol",
      "role": "symbol",
      "title": "Image",
      "type": "topic",
      "url": "/documentation/SwiftUI/Image"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle": {
      "abstract": [
        {
          "text": "A `PickerStyle` where each option is displayed inline with other views in the current container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InlinePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "InlinePickerStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/InlinePickerStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/List": {
      "abstract": [
        {
          "text": "A container that presents rows of data arranged in a single column, optionally providing the ability to select one or more members.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "List"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
      "kind": "symbol",
      "role": "symbol",
      "title": "List",
      "type": "topic",
      "url": "/documentation/SwiftUI/List"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Picker": {
      "abstract": [
        {
          "text": "A control for selecting from a set of mutually exclusive values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Picker"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
      "kind": "symbol",
      "role": "symbol",
      "title": "Picker",
      "type": "topic",
      "url": "/documentation/SwiftUI/Picker"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressView": {
      "abstract": [
        {
          "text": "A view that shows the progress toward completion of a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProgressView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressView",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProgressView",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/CurrentValueLabel-swift.struct": {
      "abstract": [
        {
          "text": "A type-erased label that describes the current value of a progress view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CurrentValueLabel"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/CurrentValueLabel-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProgressViewStyleConfiguration.CurrentValueLabel",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressViewStyleConfiguration/CurrentValueLabel-swift.struct"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property": {
      "abstract": [
        {
          "text": "A view that describes the task represented by the progress view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI30ProgressViewStyleConfigurationV",
          "text": "ProgressViewStyleConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI30ProgressViewStyleConfigurationV5LabelV",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressViewStyleConfiguration/label-swift.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/SceneBuilder": {
      "abstract": [
        {
          "text": "A result builder for composing a collection of scenes into a single composite scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@resultBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneBuilder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/SceneBuilder",
      "kind": "symbol",
      "role": "symbol",
      "title": "SceneBuilder",
      "type": "topic",
      "url": "/documentation/SwiftUI/SceneBuilder"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewReader": {
      "abstract": [
        {
          "text": "A view that provides programmatic scrolling, by working with a proxy to scroll to known child views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScrollViewReader"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewReader",
      "kind": "symbol",
      "role": "symbol",
      "title": "ScrollViewReader",
      "type": "topic",
      "url": "/documentation/SwiftUI/ScrollViewReader"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
      "kind": "symbol",
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ToolbarItemGroup": {
      "abstract": [
        {
          "text": "A model that represents a group of `ToolbarItem`s which can be placed in the toolbar or navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ToolbarItemGroup"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ToolbarItemGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "ToolbarItemGroup",
      "type": "topic",
      "url": "/documentation/SwiftUI/ToolbarItemGroup"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ViewBuilder": {
      "abstract": [
        {
          "text": "A custom parameter attribute that constructs views from closures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@resultBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ViewBuilder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ViewBuilder",
      "kind": "symbol",
      "role": "symbol",
      "title": "ViewBuilder",
      "type": "topic",
      "url": "/documentation/SwiftUI/ViewBuilder"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12 Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes/xcode-12-release-notes"
    },
    "doc://com.apple.documentation/documentation/foundation/formatter": {
      "abstract": [
        {
          "text": "An abstract class that declares an interface for objects that create, interpret, and validate the textual representation of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Formatter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/formatter",
      "kind": "symbol",
      "role": "symbol",
      "title": "Formatter",
      "type": "topic",
      "url": "/documentation/foundation/formatter"
    },
    "doc://com.apple.documentation/documentation/os/Logger": {
      "abstract": [
        {
          "text": "An object for writing interpolated string messages to the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Logger"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/Logger",
      "kind": "symbol",
      "role": "symbol",
      "title": "Logger",
      "type": "topic",
      "url": "/documentation/os/Logger"
    },
    "doc://com.apple.documentation/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/logging",
      "kind": "article",
      "role": "article",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.documentation/documentation/os/os_log": {
      "abstract": [
        {
          "text": "Sends a default-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "#define"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "internalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "internalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ", ...)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log",
      "type": "topic",
      "url": "/documentation/os/os_log"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/uikit/uicolor/1621943-cgcolor": {
      "abstract": [
        {
          "text": "The Quartz color that corresponds to the color object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/uikit/uicolor/1621943-cgcolor",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/1621943-cgcolor"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 14.2 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-14_2-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 14.3 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-14_3-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 14.4 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-14_4-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 14.5 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-14_5-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 14.6 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-14_6-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_7-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_7-release-notes",
      "kind": "article",
      "role": "article",
      "title": "tvOS 14.7 Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes/tvos-14_7-release-notes"
    },
    "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the tvOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvOS-Release-Notes/documentation/tvos-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "tvOS Release Notes",
      "type": "topic",
      "url": "/documentation/tvos-release-notes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "tvOS-14",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_7-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_6-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_5-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_4-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_3-release-notes",
        "doc://com.apple.tvOS-Release-Notes/documentation/tvOS-Release-Notes/tvos-14_2-release-notes"
      ],
      "title": "tvOS 14"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVKit~1AVPictureInPictureController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1formatter/title",
          "value": "NSFormatter"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
