{
  "abstract": [
    {
      "text": "An error occurred while communicating with the remote process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/remoteConnectionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CSIndexErrorCode@CSIndexErrorCodeRemoteConnectionError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remoteConnectionError"
      }
    ],
    "modules": [
      {
        "name": "Core Spotlight"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSIndexErrorCodeRemoteConnectionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CSIndexError.Code.remoteConnectionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remoteConnectionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corespotlight/documentation/CoreSpotlight": {
      "abstract": [
        {
          "text": "Add search capabilities to your app, and index your content so",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "people can find it from Spotlight and Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Spotlight",
      "type": "topic",
      "url": "/documentation/corespotlight"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError": {
      "abstract": [
        {
          "text": "Index errors returned by Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code": {
      "abstract": [
        {
          "text": "Error codes that describe indexing-specific errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexUnavailableError": {
      "abstract": [
        {
          "text": "The indexer is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexUnavailableError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexUnavailableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeIndexUnavailableError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.indexUnavailableError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/indexunavailableerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexingUnsupported": {
      "abstract": [
        {
          "text": "Indexing isn’t supported on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexingUnsupported"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexingUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeIndexingUnsupported"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.indexingUnsupported",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/indexingunsupported"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidClientStateError": {
      "abstract": [
        {
          "text": "The provided client state data is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidClientStateError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidClientStateError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeInvalidClientStateError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.invalidClientStateError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/invalidclientstateerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidItemError": {
      "abstract": [
        {
          "text": "The searchable item object is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidItemError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidItemError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeInvalidItemError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.invalidItemError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/invaliditemerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/mismatchedClientState": {
      "abstract": [
        {
          "text": "The provided client state did not match the information in the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mismatchedClientState"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/mismatchedClientState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeMismatchedClientState"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.mismatchedClientState",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/mismatchedclientstate"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/quotaExceeded": {
      "abstract": [
        {
          "text": "The quota for the bundle has been exceeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quotaExceeded"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/quotaExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeQuotaExceeded"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.quotaExceeded",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/quotaexceeded"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/remoteConnectionError": {
      "abstract": [
        {
          "text": "An error occurred while communicating with the remote process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteConnectionError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/remoteConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeRemoteConnectionError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.remoteConnectionError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/remoteconnectionerror"
    },
    "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/unknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSIndexErrorCodeUnknownError"
        }
      ],
      "role": "symbol",
      "title": "CSIndexError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/corespotlight/csindexerror/code/unknownerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-indexing-error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexUnavailableError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexingUnsupported",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidClientStateError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidItemError",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/mismatchedClientState",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/quotaExceeded",
        "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/unknownError"
      ],
      "title": "Getting the indexing error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CSIndexErrorCodeRemoteConnectionError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeRemoteConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-indexing-error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexUnavailableError",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/indexingUnsupported",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidClientStateError",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/invalidItemError",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/mismatchedClientState",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/quotaExceeded",
                "doc://com.apple.corespotlight/documentation/CoreSpotlight/CSIndexError/Code/unknownError"
              ],
              "title": "Getting the indexing error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CSIndexErrorCodeRemoteConnectionError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1mismatchedClientState/title",
          "value": "CSIndexErrorCodeMismatchedClientState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1mismatchedClientState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeMismatchedClientState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1remoteConnectionError/title",
          "value": "CSIndexErrorCodeRemoteConnectionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1remoteConnectionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeRemoteConnectionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1unknownError/title",
          "value": "CSIndexErrorCodeUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1invalidClientStateError/title",
          "value": "CSIndexErrorCodeInvalidClientStateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1invalidClientStateError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeInvalidClientStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/title",
          "value": "CSIndexErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1quotaExceeded/title",
          "value": "CSIndexErrorCodeQuotaExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1quotaExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeQuotaExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1indexUnavailableError/title",
          "value": "CSIndexErrorCodeIndexUnavailableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1indexUnavailableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeIndexUnavailableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1indexingUnsupported/title",
          "value": "CSIndexErrorCodeIndexingUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1indexingUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeIndexingUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1invalidItemError/title",
          "value": "CSIndexErrorCodeInvalidItemError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corespotlight~1documentation~1CoreSpotlight~1CSIndexError~1Code~1invalidItemError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSIndexErrorCodeInvalidItemError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corespotlight/csindexerror/code/remoteconnectionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corespotlight/csindexerror/code/remoteconnectionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
