{
  "abstract": [
    {
      "text": "An option that doesn’t modify the intended behavior of a store action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions/MTLStoreActionOptionNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLStoreActionOptions@MTLStoreActionOptionNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MTLStoreActionOptionNone"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLStoreActionOptionNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "MTLStoreActionOptionNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionOptionNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions": {
      "abstract": [
        {
          "text": "Options that modify a store action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStoreActionOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreActionOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreactionoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions/MTLStoreActionOptionNone": {
      "abstract": [
        {
          "text": "An option that doesn’t modify the intended behavior of a store action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionOptionNone"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions/MTLStoreActionOptionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLStoreActionOptionNone",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreactionoptions/mtlstoreactionoptionnone"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions/customSamplePositions": {
      "abstract": [
        {
          "text": "An option that stores data in a sample-position–agnostic representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customSamplePositions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreActionOptions",
          "text": "MTLStoreActionOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions/customSamplePositions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionOptionCustomSamplePositions"
        }
      ],
      "role": "symbol",
      "title": "customSamplePositions",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreactionoptions/customsamplepositions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLStoreActionOptions/customSamplePositions"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreActionOptions~1customSamplePositions/title",
          "value": "MTLStoreActionOptionCustomSamplePositions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreActionOptions~1customSamplePositions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionOptionCustomSamplePositions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreActionOptions/title",
          "value": "MTLStoreActionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreActionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreActionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlstoreactionoptions/mtlstoreactionoptionnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
