{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
        }
      ],
      "role": "symbol",
      "title": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX",
      "type": "topic",
      "url": "/documentation/dnssd/dns_sd_original_encoding_version_number_max"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceAttributeAAAAFallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceAttributeAAAAFallback"
        },
        {
          "kind": "text",
          "text": ": <<error type>>"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceAttributeAAAAFallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceAttributeAAAAFallback"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceAttributeAAAAFallback",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceattributeaaaafallback"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexAny": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexAny"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceInterfaceIndexAny",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceinterfaceindexany"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexBLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexBLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexBLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexBLE"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceInterfaceIndexBLE",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceinterfaceindexble"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexInfra": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexInfra"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexInfra",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexInfra"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceInterfaceIndexInfra",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceinterfaceindexinfra"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexLocalOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexLocalOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexLocalOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexLocalOnly"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceInterfaceIndexLocalOnly",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceinterfaceindexlocalonly"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexP2P": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexP2P"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexP2P",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexP2P"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceInterfaceIndexP2P",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceinterfaceindexp2p"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexUnicast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexUnicast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexUnicast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceInterfaceIndexUnicast"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceInterfaceIndexUnicast",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceinterfaceindexunicast"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxDomainName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxDomainName"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceMaxDomainName",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsservicemaxdomainname"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxServiceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxServiceName"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceMaxServiceName",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsservicemaxservicename"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion": {
      "abstract": [
        {
          "text": "The daemon version property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceProperty_DaemonVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceProperty_DaemonVersion"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceProperty_DaemonVersion",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceproperty_daemonversion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceAttributeAAAAFallback",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexAny",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexBLE",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexInfra",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexLocalOnly",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexP2P",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexUnicast",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dnssd/documentation/dnssd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceAttributeAAAAFallback",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexAny",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexBLE",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexInfra",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexLocalOnly",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexP2P",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceInterfaceIndexUnicast",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexP2P/title",
          "value": "kDNSServiceInterfaceIndexP2P"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexP2P/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceInterfaceIndexP2P"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexInfra/title",
          "value": "kDNSServiceInterfaceIndexInfra"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexInfra/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceInterfaceIndexInfra"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceAttributeAAAAFallback/title",
          "value": "kDNSServiceAttributeAAAAFallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceAttributeAAAAFallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceAttributeAAAAFallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexBLE/title",
          "value": "kDNSServiceInterfaceIndexBLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexBLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceInterfaceIndexBLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxDomainName/title",
          "value": "kDNSServiceMaxDomainName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxDomainName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceMaxDomainName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexUnicast/title",
          "value": "kDNSServiceInterfaceIndexUnicast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexUnicast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceInterfaceIndexUnicast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxServiceName/title",
          "value": "kDNSServiceMaxServiceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxServiceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceMaxServiceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexLocalOnly/title",
          "value": "kDNSServiceInterfaceIndexLocalOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexLocalOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceInterfaceIndexLocalOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX/title",
          "value": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNS_SD_ORIGINAL_ENCODING_VERSION_NUMBER_MAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceProperty_DaemonVersion/title",
          "value": "kDNSServiceProperty_DaemonVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceProperty_DaemonVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceProperty_DaemonVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexAny/title",
          "value": "kDNSServiceInterfaceIndexAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceInterfaceIndexAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceInterfaceIndexAny"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/dns_sd_original_encoding_version_number_max"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/dns_sd_original_encoding_version_number_max"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
