{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/dnssd-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "dnssd Enumerations"
  },
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAAAAPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceAAAAPolicy"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAAAAPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceAAAAPolicy"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceAAAAPolicy",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceaaaapolicy"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Service Discovery C",
      "type": "topic",
      "url": "/documentation/dnssd/dns-service-discovery-c"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "dnssd Constants",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd-constants"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "dnssd Data Types",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd-data-types"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "dnssd Functions",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd-data-types",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAAAAPolicy"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAAAAPolicy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd-data-types",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceAAAAPolicy/title",
          "value": "DNSServiceAAAAPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceAAAAPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceAAAAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceAAAAPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceAAAAPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/dnssd-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/dnssd-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
