{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/dnssd-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "dnssd Data Types"
  },
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/CompileTimeAssertionChecks_DNS_SD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompileTimeAssertionChecks_DNS_SD"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/CompileTimeAssertionChecks_DNS_SD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CompileTimeAssertionChecks_DNS_SD"
        }
      ],
      "role": "symbol",
      "title": "CompileTimeAssertionChecks_DNS_SD",
      "type": "topic",
      "url": "/documentation/dnssd/compiletimeassertionchecks_dns_sd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSRecordRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSRecordRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSRecordRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSRecordRef"
        }
      ],
      "role": "symbol",
      "title": "DNSRecordRef",
      "type": "topic",
      "url": "/documentation/dnssd/dnsrecordref"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DNSServiceAttribute"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "DNSServiceAttribute",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceattribute"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttributeRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceAttributeRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttributeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceAttributeRef"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceAttributeRef",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceattributeref"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceRef"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceRef",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceref"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceSleepKeepaliveReply": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceSleepKeepaliveReply"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceSleepKeepaliveReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceSleepKeepaliveReply"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceSleepKeepaliveReply",
      "type": "topic",
      "url": "/documentation/dnssd/dnsservicesleepkeepalivereply"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Service Discovery C",
      "type": "topic",
      "url": "/documentation/dnssd/dns-service-discovery-c"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "dnssd Constants",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd-constants"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "dnssd Enumerations",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd-enumerations"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "dnssd Functions",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd-functions"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dnssd_sock_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dnssd_sock_t"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dnssd_sock_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dnssd_sock_t"
        }
      ],
      "role": "symbol",
      "title": "dnssd_sock_t",
      "type": "topic",
      "url": "/documentation/dnssd/dnssd_sock_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd-enumerations",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/CompileTimeAssertionChecks_DNS_SD",
        "doc://com.apple.dnssd/documentation/dnssd/DNSRecordRef",
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceSleepKeepaliveReply",
        "doc://com.apple.dnssd/documentation/dnssd/dnssd_sock_t",
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttributeRef"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/CompileTimeAssertionChecks_DNS_SD",
                "doc://com.apple.dnssd/documentation/dnssd/DNSRecordRef",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceSleepKeepaliveReply",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd_sock_t",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttribute",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceAttributeRef"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd-enumerations",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd-functions",
                "doc://com.apple.dnssd/documentation/dnssd/dnssd-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1dnssd_sock_t/title",
          "value": "dnssd_sock_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1dnssd_sock_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dnssd_sock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1dnssd_sock_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "dnssd_sock_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceSleepKeepaliveReply/title",
          "value": "DNSServiceSleepKeepaliveReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceSleepKeepaliveReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceSleepKeepaliveReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceSleepKeepaliveReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceSleepKeepaliveReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSRecordRef/title",
          "value": "DNSRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSRecordRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSRecordRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1CompileTimeAssertionChecks_DNS_SD/title",
          "value": "CompileTimeAssertionChecks_DNS_SD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1CompileTimeAssertionChecks_DNS_SD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CompileTimeAssertionChecks_DNS_SD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1CompileTimeAssertionChecks_DNS_SD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CompileTimeAssertionChecks_DNS_SD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/title",
          "value": "DNSServiceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceAttributeRef/title",
          "value": "DNSServiceAttributeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceAttributeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceAttributeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceAttributeRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceAttributeRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/dnssd-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/dnssd-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
