{
  "abstract": [
    {
      "text": "Reads a reply from the daemon, calling the appropriate application callback.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProcessResult(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@DNSServiceProcessResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DNSServiceProcessResult"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DNSServiceRef",
        "text": "DNSServiceRef"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DNSServiceErrorType",
        "text": "DNSServiceErrorType"
      }
    ],
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DNSServiceProcessResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "DNSServiceProcessResult(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DNSServiceProcessResult"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sdRef"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DNSServiceRef",
              "text": "DNSServiceRef"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DNSServiceErrorType",
              "text": "DNSServiceErrorType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A DNSServiceRef initialized by any of the DNSService calls that take a callback parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sdRef"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on success, otherwise returns an error code indicating the specific failure that occurred.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This call blocks until the daemon’s response is received. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefSockFD(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in conjunction with a run loop or select() to determine the presence of a response from the server before calling this function to process the reply without blocking. Call this function at any point if it is acceptable to block until the daemon’s response arrives. Note that the client is responsible for ensuring that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProcessResult(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is called whenever there is a reply from the daemon - the daemon may terminate its connection with a client that does not process the daemon’s responses.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceErrorType"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceErrorType"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceErrorType",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceerrortype"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProcessResult(_:)": {
      "abstract": [
        {
          "text": "Reads a reply from the daemon, calling the appropriate application callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceProcessResult"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceRef",
          "text": "DNSServiceRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceErrorType",
          "text": "DNSServiceErrorType"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProcessResult(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceProcessResult"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceProcessResult(_:)",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceprocessresult(_:)"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceRef"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceRef",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceref"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)": {
      "abstract": [
        {
          "text": "Terminates a connection with the daemon and frees memory associated with the DNSServiceRef.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceRefDeallocate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceRef",
          "text": "DNSServiceRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceRefDeallocate"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceRefDeallocate(_:)",
      "type": "topic",
      "url": "/documentation/dnssd/dnsservicerefdeallocate(_:)"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefSockFD(_:)": {
      "abstract": [
        {
          "text": "Accesses underlying Unix domain socket for an initialized DNSServiceRef.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceRefSockFD"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceRef",
          "text": "DNSServiceRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dnssd_sock_t",
          "text": "dnssd_sock_t"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefSockFD(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceRefSockFD"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceRefSockFD(_:)",
      "type": "topic",
      "url": "/documentation/dnssd/dnsservicerefsockfd(_:)"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceErr_NoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceErr_NoError"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceErr_NoError",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceerr_noerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unix-Domain-Socket-access-DNSServiceRef-deallocation-and-data-processing-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefSockFD(_:)"
      ],
      "title": "Unix Domain Socket access, DNSServiceRef deallocation, and data processing functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DNSServiceProcessResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceProcessResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dnssd/documentation/dnssd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Unix-Domain-Socket-access-DNSServiceRef-deallocation-and-data-processing-functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefSockFD(_:)"
              ],
              "title": "Unix Domain Socket access, DNSServiceRef deallocation, and data processing functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DNSServiceErrorType",
                    "text": "DNSServiceErrorType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DNSServiceProcessResult"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DNSServiceRef",
                    "text": "DNSServiceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sdRef"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A DNSServiceRef initialized by any of the DNSService calls that take a callback parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sdRef"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " on success, otherwise returns an error code indicating the specific failure that occurred.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRefSockFD(_:)/title",
          "value": "DNSServiceRefSockFD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRefSockFD(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRefSockFD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceErr_NoError/title",
          "value": "kDNSServiceErr_NoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceErr_NoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceErr_NoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/title",
          "value": "DNSServiceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceProcessResult(_:)/title",
          "value": "DNSServiceProcessResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceProcessResult(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceProcessResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRefDeallocate(_:)/title",
          "value": "DNSServiceRefDeallocate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRefDeallocate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRefDeallocate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/title",
          "value": "DNSServiceErrorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceErrorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceErrorType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/dnsserviceprocessresult(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/dnsserviceprocessresult(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
