{
  "abstract": [
    {
      "text": "Enumerates domains that are recommended for registration and browsing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceEnumerateDomains(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@DNSServiceEnumerateDomains",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DNSServiceEnumerateDomains"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DNSServiceRef",
        "text": "DNSServiceRef"
      },
      {
        "kind": "text",
        "text": "?>!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DNSServiceFlags",
        "text": "DNSServiceFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DNSServiceDomainEnumReply",
        "text": "DNSServiceDomainEnumReply"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DNSServiceErrorType",
        "text": "DNSServiceErrorType"
      }
    ],
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DNSServiceEnumerateDomains"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "DNSServiceEnumerateDomains(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DNSServiceEnumerateDomains"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sdRef"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DNSServiceRef",
              "text": "DNSServiceRef"
            },
            {
              "kind": "text",
              "text": "?>!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DNSServiceFlags",
              "text": "DNSServiceFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "interfaceIndex"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "callBack"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceDomainEnumReply",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DNSServiceDomainEnumReply",
              "text": "DNSServiceDomainEnumReply"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DNSServiceErrorType",
              "text": "DNSServiceErrorType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an uninitialized DNSServiceRef. If the call succeeds then it initializes the DNSServiceRef, returns ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and the enumeration operation will run indefinitely until the client terminates it by passing this DNSServiceRef to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sdRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Possible values are: kDNSServiceFlagsBrowseDomains to enumerate domains recommended for browsing. kDNSServiceFlagsRegistrationDomains to enumerate domains recommended for registration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If non-zero, specifies the interface on which to look for domains. (the index for a given interface is determined via the if_nametoindex() family of calls.) Most applications will pass 0 to enumerate domains on all interfaces. See “Constants for specifying an interface index” for more details.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "interfaceIndex"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The function to be called when a domain is found or the call asynchronously fails.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callBack"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An application context pointer which is passed to the callback function (may be NULL).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on success (any subsequent, asynchronous errors are delivered to the callback), otherwise returns an error code indicating the error that occurred (the callback is not invoked and the DNSServiceRef is not initialized).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The enumeration MUST be cancelled via ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when no more domains are to be found.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that the names returned are (like all of DNS-SD) UTF-8 strings, and are escaped using standard DNS escaping rules. (See “Notes on DNS Name Escaping” earlier in this file for more details.) A graphical browser displaying a hierarchical tree-structured view should cut the names at the bare dots to yield individual labels, then de-escape each label according to the escaping rules, and then display the resulting UTF-8 text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceDomainEnumReply": {
      "abstract": [
        {
          "text": "Callback for handling the results of a previous call to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceEnumerateDomains(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceDomainEnumReply"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceDomainEnumReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceDomainEnumReply"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceDomainEnumReply",
      "type": "topic",
      "url": "/documentation/dnssd/dnsservicedomainenumreply"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceEnumerateDomains(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Enumerates domains that are recommended for registration and browsing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceEnumerateDomains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceRef",
          "text": "DNSServiceRef"
        },
        {
          "kind": "text",
          "text": "?>!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceFlags",
          "text": "DNSServiceFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceDomainEnumReply",
          "text": "DNSServiceDomainEnumReply"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceErrorType",
          "text": "DNSServiceErrorType"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceEnumerateDomains(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceEnumerateDomains"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceEnumerateDomains(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceenumeratedomains(_:_:_:_:_:)"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceErrorType"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceErrorType"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceErrorType",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceerrortype"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceFlags"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceFlags"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceFlags",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceflags"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceRef"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceRef",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceref"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)": {
      "abstract": [
        {
          "text": "Terminates a connection with the daemon and frees memory associated with the DNSServiceRef.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceRefDeallocate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DNSServiceRef",
          "text": "DNSServiceRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceRefDeallocate"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceRefDeallocate(_:)",
      "type": "topic",
      "url": "/documentation/dnssd/dnsservicerefdeallocate(_:)"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceErr_NoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceErr_NoError"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceErr_NoError",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceerr_noerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DNSServiceEnumerateDomains"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceEnumerateDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dnssd/documentation/dnssd"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DNSServiceErrorType",
                    "text": "DNSServiceErrorType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DNSServiceEnumerateDomains"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DNSServiceRef",
                    "text": "DNSServiceRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sdRef"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DNSServiceFlags",
                    "text": "DNSServiceFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "interfaceIndex"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceDomainEnumReply",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DNSServiceDomainEnumReply",
                    "text": "DNSServiceDomainEnumReply"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callBack"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to an uninitialized DNSServiceRef. If the call succeeds then it initializes the DNSServiceRef, returns ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", and the enumeration operation will run indefinitely until the client terminates it by passing this DNSServiceRef to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceRefDeallocate(_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sdRef"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Possible values are: kDNSServiceFlagsBrowseDomains to enumerate domains recommended for browsing. kDNSServiceFlagsRegistrationDomains to enumerate domains recommended for registration.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If non-zero, specifies the interface on which to look for domains. (the index for a given interface is determined via the if_nametoindex() family of calls.) Most applications will pass 0 to enumerate domains on all interfaces. See “Constants for specifying an interface index” for more details.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "interfaceIndex"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The function to be called when a domain is found or the call asynchronously fails.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callBack"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An application context pointer which is passed to the callback function (may be NULL).",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceErr_NoError",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " on success (any subsequent, asynchronous errors are delivered to the callback), otherwise returns an error code indicating the error that occurred (the callback is not invoked and the DNSServiceRef is not initialized).",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/title",
          "value": "DNSServiceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/title",
          "value": "DNSServiceErrorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceErrorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceErrorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceDomainEnumReply/title",
          "value": "DNSServiceDomainEnumReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceDomainEnumReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceDomainEnumReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceDomainEnumReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceDomainEnumReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceFlags/title",
          "value": "DNSServiceFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceEnumerateDomains(_:_:_:_:_:)/title",
          "value": "DNSServiceEnumerateDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceEnumerateDomains(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceEnumerateDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceErr_NoError/title",
          "value": "kDNSServiceErr_NoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceErr_NoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceErr_NoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRefDeallocate(_:)/title",
          "value": "DNSServiceRefDeallocate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceRefDeallocate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceRefDeallocate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/dnsserviceenumeratedomains(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/dnsserviceenumeratedomains(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
