{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd",
        "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/miscellaneous-defines"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Miscellaneous Defines"
  },
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/constants-for-specifying-an-interface-index": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/constants-for-specifying-an-interface-index",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Constants for specifying an interface index",
      "type": "topic",
      "url": "/documentation/dnssd/constants-for-specifying-an-interface-index"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Service Discovery C",
      "type": "topic",
      "url": "/documentation/dnssd/dns-service-discovery-c"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dns_sd_h": {
      "abstract": [
        {
          "text": "API version number.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dns_sd_h",
      "kind": "article",
      "role": "article",
      "title": "_DNS_SD_H",
      "type": "topic",
      "url": "/documentation/dnssd/dns_sd_h"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxDomainName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxDomainName"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceMaxDomainName",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsservicemaxdomainname"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxServiceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceMaxServiceName"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceMaxServiceName",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsservicemaxservicename"
    },
    "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion": {
      "abstract": [
        {
          "text": "The daemon version property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDNSServiceProperty_DaemonVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDNSServiceProperty_DaemonVersion"
        }
      ],
      "role": "symbol",
      "title": "kDNSServiceProperty_DaemonVersion",
      "type": "topic",
      "url": "/documentation/dnssd/kdnsserviceproperty_daemonversion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/constants-for-specifying-an-interface-index"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/dns_sd_h",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName",
        "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/dns_sd_h",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxDomainName",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceMaxServiceName",
                "doc://com.apple.dnssd/documentation/dnssd/kDNSServiceProperty_DaemonVersion"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/constants-for-specifying-an-interface-index"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxServiceName/title",
          "value": "kDNSServiceMaxServiceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxServiceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceMaxServiceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxDomainName/title",
          "value": "kDNSServiceMaxDomainName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceMaxDomainName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceMaxDomainName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceProperty_DaemonVersion/title",
          "value": "kDNSServiceProperty_DaemonVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1kDNSServiceProperty_DaemonVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDNSServiceProperty_DaemonVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/miscellaneous-defines"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/miscellaneous-defines"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
