{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd",
        "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
        "doc://com.apple.dnssd/documentation/dnssd/TXTRecordRef"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/Private-Data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "9.3",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "9.3",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.11.4",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.2",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "2.2",
        "name": "watchOS"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Private Data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "char PrivateData[16];"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment",
      "kind": "article",
      "role": "article",
      "title": "Force Natural Alignment",
      "type": "topic",
      "url": "/documentation/dnssd/force-natural-alignment"
    },
    "doc://com.apple.dnssd/documentation/dnssd/TXTRecordRef": {
      "abstract": [
        {
          "text": "Opaque internal data type that represents a DNS-SD TXT record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TXTRecordRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/TXTRecordRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TXTRecordRef"
        }
      ],
      "role": "symbol",
      "title": "TXTRecordRef",
      "type": "topic",
      "url": "/documentation/dnssd/txtrecordref"
    },
    "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/dns-service-discovery-c",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Service Discovery C",
      "type": "topic",
      "url": "/documentation/dnssd/dns-service-discovery-c"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1TXTRecordRef/title",
          "value": "TXTRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1TXTRecordRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1TXTRecordRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/private-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/private-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
