{
  "abstract": [
    {
      "text": "Opaque internal data type that represents a DNS-SD TXT record.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dnssd/documentation/dnssd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dnssd/documentation/dnssd/TXTRecordRef"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@TXTRecordRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TXTRecordRef"
      }
    ],
    "modules": [
      {
        "name": "dnssd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TXTRecordRef"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "TXTRecordRef"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "kind": "typeIdentifier",
              "text": "_TXTRecordRef_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.dnssd/documentation/dnssd": {
      "abstract": [
        {
          "text": "Discover, publish, and resolve network services on a local area or wide area network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd",
      "kind": "symbol",
      "role": "collection",
      "title": "dnssd",
      "type": "topic",
      "url": "/documentation/dnssd"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceErrorType"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceErrorType"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceErrorType",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceerrortype"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceFlags"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceFlags"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceFlags",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceflags"
    },
    "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DNSServiceProtocol"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DNSServiceProtocol"
        }
      ],
      "role": "symbol",
      "title": "DNSServiceProtocol",
      "type": "topic",
      "url": "/documentation/dnssd/dnsserviceprotocol"
    },
    "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment",
      "kind": "article",
      "role": "article",
      "title": "Force Natural Alignment",
      "type": "topic",
      "url": "/documentation/dnssd/force-natural-alignment"
    },
    "doc://com.apple.dnssd/documentation/dnssd/Private-Data": {
      "abstract": [],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/Private-Data",
      "kind": "article",
      "role": "article",
      "title": "Private Data",
      "type": "topic",
      "url": "/documentation/dnssd/private-data"
    },
    "doc://com.apple.dnssd/documentation/dnssd/TXTRecordRef": {
      "abstract": [
        {
          "text": "Opaque internal data type that represents a DNS-SD TXT record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TXTRecordRef"
        }
      ],
      "identifier": "doc://com.apple.dnssd/documentation/dnssd/TXTRecordRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TXTRecordRef"
        }
      ],
      "role": "symbol",
      "title": "TXTRecordRef",
      "type": "topic",
      "url": "/documentation/dnssd/txtrecordref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags",
        "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProtocol"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment",
        "doc://com.apple.dnssd/documentation/dnssd/Private-Data"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TXTRecordRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.dnssd/documentation/dnssd"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/Force-Natural-Alignment",
                "doc://com.apple.dnssd/documentation/dnssd/Private-Data"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceErrorType",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceFlags",
                "doc://com.apple.dnssd/documentation/dnssd/DNSServiceProtocol"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "union"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@U@_TXTRecordRef_t",
                    "text": "_TXTRecordRef_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TXTRecordRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceProtocol/title",
          "value": "DNSServiceProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceFlags/title",
          "value": "DNSServiceFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1TXTRecordRef/title",
          "value": "TXTRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1TXTRecordRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1TXTRecordRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TXTRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/title",
          "value": "DNSServiceErrorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceErrorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dnssd~1documentation~1dnssd~1DNSServiceErrorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DNSServiceErrorType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dnssd/txtrecordref"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/dnssd/txtrecordref"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
