{
  "abstract": [
    {
      "text": "Indicates that the light source is toward the bottom-left of the sensor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SRAmbientLightSensorPlacement@SRAmbientLightSensorPlacementFrontBottomLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "frontBottomLeft"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SRAmbientLightSample.SensorPlacement.frontBottomLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "frontBottomLeft"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample": {
      "abstract": [
        {
          "text": "The amount of ambient light in the user’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSample"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement": {
      "abstract": [
        {
          "text": "Directional values that describe light-source location with respect to the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SensorPlacement"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SensorPlacement"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the bottom of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontBottom"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontBottom"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontBottom",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottom"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the bottom-left of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontBottomLeft"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontBottomLeft",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottomleft"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the bottom-right of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontBottomRight"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontBottomRight"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontBottomRight",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottomright"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the left of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontLeft"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontLeft"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontLeft",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontleft"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the right of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontRight"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontRight"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontRight",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/frontright"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the top of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontTop"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontTop"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontTop",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/fronttop"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the top-left of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontTopLeft"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontTopLeft"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontTopLeft",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/fronttopleft"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight": {
      "abstract": [
        {
          "text": "Indicates that the light source is toward the top-right of the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontTopRight"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementFrontTopRight"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.frontTopRight",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/fronttopright"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown": {
      "abstract": [
        {
          "text": "Indicates that the sensor can’t determine the light source’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRAmbientLightSensorPlacementUnknown"
        }
      ],
      "role": "symbol",
      "title": "SRAmbientLightSample.SensorPlacement.unknown",
      "type": "topic",
      "url": "/documentation/sensorkit/srambientlightsample/sensorplacement/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Placement-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown"
      ],
      "title": "Placement configurations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRAmbientLightSensorPlacementFrontBottomLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Placement-configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottom",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontBottomRight",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontLeft",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontRight",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTop",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopLeft",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/frontTopRight",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample/SensorPlacement/unknown"
              ],
              "title": "Placement configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontRight/title",
          "value": "SRAmbientLightSensorPlacementFrontRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomLeft/title",
          "value": "SRAmbientLightSensorPlacementFrontBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontLeft/title",
          "value": "SRAmbientLightSensorPlacementFrontLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopRight/title",
          "value": "SRAmbientLightSensorPlacementFrontTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottom/title",
          "value": "SRAmbientLightSensorPlacementFrontBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTop/title",
          "value": "SRAmbientLightSensorPlacementFrontTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/title",
          "value": "SRAmbientLightSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1unknown/title",
          "value": "SRAmbientLightSensorPlacementUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomRight/title",
          "value": "SRAmbientLightSensorPlacementFrontBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontBottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopLeft/title",
          "value": "SRAmbientLightSensorPlacementFrontTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement~1frontTopLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacementFrontTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/title",
          "value": "SRAmbientLightSensorPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample~1SensorPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRAmbientLightSensorPlacement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srambientlightsample/sensorplacement/frontbottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
