{
  "abstract": [
    {
      "text": "An icon that depicts a television.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tv"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@DDDeviceCategory@DDDeviceCategoryTV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tv"
      }
    ],
    "modules": [
      {
        "name": "DeviceDiscoveryExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DDDeviceCategoryTV"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "DDDevice.Category.tv"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tv"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension": {
      "abstract": [
        {
          "text": "Stream media to a third-party device that a user selects in a system menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "DeviceDiscoveryExtension",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice": {
      "abstract": [
        {
          "text": "An object that describes a discovered device of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDDevice"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDevice"
        }
      ],
      "role": "symbol",
      "title": "DDDevice",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum": {
      "abstract": [
        {
          "text": "An option that determines the icon for the device in the picker UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/desktopComputer": {
      "abstract": [
        {
          "text": "An icon that depicts a desktop computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desktopComputer"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/desktopComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceCategoryDesktopComputer"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category.desktopComputer",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum/desktopcomputer"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeaker": {
      "abstract": [
        {
          "text": "An icon that depicts a high-fidelity speaker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hifiSpeaker"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceCategoryHiFiSpeaker"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category.hifiSpeaker",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum/hifispeaker"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeakerMultiple": {
      "abstract": [
        {
          "text": "An icon that depicts multiple high-fidelity speakers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hifiSpeakerMultiple"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeakerMultiple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceCategoryHiFiSpeakerMultiple"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category.hifiSpeakerMultiple",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum/hifispeakermultiple"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/laptopComputer": {
      "abstract": [
        {
          "text": "An icon that depicts a laptop computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "laptopComputer"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/laptopComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceCategoryLaptopComputer"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category.laptopComputer",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum/laptopcomputer"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tv": {
      "abstract": [
        {
          "text": "An icon that depicts a television.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tv"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceCategoryTV"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category.tv",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum/tv"
    },
    "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tvWithMediaBox": {
      "abstract": [
        {
          "text": "An icon that depicts a TV with a set-top box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvWithMediaBox"
        }
      ],
      "identifier": "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tvWithMediaBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDDeviceCategoryTVWithMediaBox"
        }
      ],
      "role": "symbol",
      "title": "DDDevice.Category.tvWithMediaBox",
      "type": "topic",
      "url": "/documentation/devicediscoveryextension/dddevice/category-swift.enum/tvwithmediabox"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Choosing-an-icon-for-the-device-picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/desktopComputer",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeaker",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeakerMultiple",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/laptopComputer",
        "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tvWithMediaBox"
      ],
      "title": "Choosing an icon for the device picker"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DDDeviceCategoryTV"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Choosing-an-icon-for-the-device-picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/desktopComputer",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeaker",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/hifiSpeakerMultiple",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/laptopComputer",
                "doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDDevice/Category-swift.enum/tvWithMediaBox"
              ],
              "title": "Choosing an icon for the device picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "DDDeviceCategoryTV"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1tvWithMediaBox/title",
          "value": "DDDeviceCategoryTVWithMediaBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1tvWithMediaBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryTVWithMediaBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1hifiSpeakerMultiple/title",
          "value": "DDDeviceCategoryHiFiSpeakerMultiple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1hifiSpeakerMultiple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryHiFiSpeakerMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice/title",
          "value": "DDDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1hifiSpeaker/title",
          "value": "DDDeviceCategoryHiFiSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1hifiSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryHiFiSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1desktopComputer/title",
          "value": "DDDeviceCategoryDesktopComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1desktopComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryDesktopComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1laptopComputer/title",
          "value": "DDDeviceCategoryLaptopComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1laptopComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryLaptopComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum/title",
          "value": "DDDeviceCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1tv/title",
          "value": "DDDeviceCategoryTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDDevice~1Category-swift.enum~1tv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDDeviceCategoryTV"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/devicediscoveryextension/dddevice/category-swift.enum/tv"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/devicediscoveryextension/dddevice/category-swift.enum/tv"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
