{
  "abstract": [
    {
      "text": "The participant has accepted the event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKParticipantStatus@EKParticipantStatusAccepted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accepted"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKParticipantStatusAccepted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKParticipantStatus.accepted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accepted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus": {
      "abstract": [
        {
          "text": "The participant’s attendance status for an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatus"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted": {
      "abstract": [
        {
          "text": "The participant has accepted the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accepted"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusAccepted"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.accepted",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/accepted"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed": {
      "abstract": [
        {
          "text": "The participant’s event has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completed"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusCompleted"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.completed",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/completed"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined": {
      "abstract": [
        {
          "text": "The participant has declined the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declined"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusDeclined"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.declined",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/declined"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated": {
      "abstract": [
        {
          "text": "The participant has delegated attendance to another participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegated"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusDelegated"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.delegated",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/delegated"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess": {
      "abstract": [
        {
          "text": "The participant’s event is currently in process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProcess"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusInProcess"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.inProcess",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/inprocess"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending": {
      "abstract": [
        {
          "text": "The participant has yet to respond to the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pending"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusPending"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.pending",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/pending"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative": {
      "abstract": [
        {
          "text": "The participant’s attendance status is tentative.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tentative"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusTentative"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.tentative",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/tentative"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown": {
      "abstract": [
        {
          "text": "The participant’s attendance status is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.unknown",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKParticipantStatusAccepted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKParticipantStatusAccepted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1tentative/title",
          "value": "EKParticipantStatusTentative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1tentative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusTentative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1accepted/title",
          "value": "EKParticipantStatusAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1accepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1completed/title",
          "value": "EKParticipantStatusCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1completed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1unknown/title",
          "value": "EKParticipantStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus/title",
          "value": "EKParticipantStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1delegated/title",
          "value": "EKParticipantStatusDelegated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1delegated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusDelegated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1declined/title",
          "value": "EKParticipantStatusDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1declined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1inProcess/title",
          "value": "EKParticipantStatusInProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1inProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusInProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1pending/title",
          "value": "EKParticipantStatusPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1pending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusPending"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekparticipantstatus/accepted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekparticipantstatus/accepted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
