{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GameplayKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraph/triangulationMode": {
      "abstract": [
        {
          "text": "A set of options for how to place graph nodes when triangulating the graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangulationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKMeshGraphTriangulationMode",
          "text": "GKMeshGraphTriangulationMode"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraph/triangulationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triangulationMode"
        }
      ],
      "role": "symbol",
      "title": "triangulationMode",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkmeshgraph/triangulationmode"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraphTriangulationMode": {
      "abstract": [
        {
          "text": "Options for how to place graph nodes when generating the graph, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraph/triangulationMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMeshGraphTriangulationMode"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraphTriangulationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMeshGraphTriangulationMode"
        }
      ],
      "role": "symbol",
      "title": "GKMeshGraphTriangulationMode",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkmeshgraphtriangulationmode"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTree/addElement(_:boundingRectMin:boundingRectMax:splitStrategy:)": {
      "abstract": [
        {
          "text": "Adds the specified object to the tree.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "ElementType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "boundingRectMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "boundingRectMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "splitStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKRTreeSplitStrategy",
          "text": "GKRTreeSplitStrategy"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTree/addElement(_:boundingRectMin:boundingRectMax:splitStrategy:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addElement:boundingRectMin:boundingRectMax:splitStrategy:"
        }
      ],
      "role": "symbol",
      "title": "addElement(_:boundingRectMin:boundingRectMax:splitStrategy:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrtree/addelement(_:boundingrectmin:boundingrectmax:splitstrategy:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTreeSplitStrategy": {
      "abstract": [
        {
          "text": "Options that control how a tree balances its internal structure when adding elements, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTree/addElement(_:boundingRectMin:boundingRectMax:splitStrategy:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRTreeSplitStrategy"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTreeSplitStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRTreeSplitStrategy"
        }
      ],
      "role": "symbol",
      "title": "GKRTreeSplitStrategy",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrtreesplitstrategy"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GameplayKit Constants",
      "type": "topic",
      "url": "/documentation/gameplaykit/gameplaykit-constants"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GameplayKit Structures",
      "type": "topic",
      "url": "/documentation/gameplaykit/gameplaykit-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-constants",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraphTriangulationMode",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTreeSplitStrategy"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMeshGraphTriangulationMode",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRTreeSplitStrategy"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-constants",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMeshGraph~1triangulationMode/title",
          "value": "triangulationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMeshGraph~1triangulationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "triangulationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMeshGraphTriangulationMode/title",
          "value": "GKMeshGraphTriangulationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMeshGraphTriangulationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMeshGraphTriangulationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMeshGraphTriangulationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMeshGraphTriangulationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRTreeSplitStrategy/title",
          "value": "GKRTreeSplitStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRTreeSplitStrategy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRTreeSplitStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRTreeSplitStrategy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRTreeSplitStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRTree~1addElement(_:boundingRectMin:boundingRectMax:splitStrategy:)/title",
          "value": "addElement:boundingRectMin:boundingRectMax:splitStrategy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRTree~1addElement(_:boundingRectMin:boundingRectMax:splitStrategy:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addElement:boundingRectMin:boundingRectMax:splitStrategy:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gameplaykit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gameplaykit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
