{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "GameplayKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/score(for:)": {
      "abstract": [
        {
          "text": "Returns a number rating the desirability of the game model’s current state from the perspective of the specified player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "score"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKGameModelPlayer",
          "text": "GKGameModelPlayer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/score(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scoreForPlayer:"
        }
      ],
      "role": "symbol",
      "title": "score(for:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgamemodel/score(for:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMaxScore": {
      "abstract": [
        {
          "text": "The maximum return value allowed for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/score(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameModelMaxScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMaxScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameModelMaxScore"
        }
      ],
      "role": "symbol",
      "title": "GKGameModelMaxScore",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgamemodelmaxscore"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMinScore": {
      "abstract": [
        {
          "text": "The minimum return value allowed for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModel/score(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameModelMinScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMinScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameModelMinScore"
        }
      ],
      "role": "symbol",
      "title": "GKGameModelMinScore",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgamemodelminscore"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKInspectable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GKInspectable"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKInspectable",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKInspectable",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkinspectable"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_AVAILABLE",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_available"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_BASE_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_BASE_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_base_availability"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_BASE_AVAILABILITY_2"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY_2",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_BASE_AVAILABILITY_2",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_base_availability_2"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_BASE_AVAILABILITY_3"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY_3",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_BASE_AVAILABILITY_3",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_base_availability_3"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_DEFAULT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_DEFAULT",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_default"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_EXPORT",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_export"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_FORCE_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_FORCE_INLINE"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_FORCE_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_FORCE_INLINE",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_force_inline"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_LIKELY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_LIKELY"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_LIKELY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_LIKELY",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_likely"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_UNLIKELY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GK_UNLIKELY"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_UNLIKELY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GK_UNLIKELY",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_unlikely"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GK_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GK_VERSION"
        }
      ],
      "role": "symbol",
      "title": "GK_VERSION",
      "type": "topic",
      "url": "/documentation/gameplaykit/gk_version"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GameplayKit Enumerations",
      "type": "topic",
      "url": "/documentation/gameplaykit/gameplaykit-enumerations"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GameplayKit Structures",
      "type": "topic",
      "url": "/documentation/gameplaykit/gameplaykit-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMaxScore",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMinScore"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_VERSION"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMaxScore",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGameModelMinScore"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKInspectable",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_AVAILABLE",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY_2",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_BASE_AVAILABILITY_3",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_DEFAULT",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_EXPORT",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_FORCE_INLINE",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_LIKELY",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_UNLIKELY",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GK_VERSION"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-structures",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/gameplaykit-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelMaxScore/title",
          "value": "GKGameModelMaxScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelMaxScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameModelMaxScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModel~1score(for:)/title",
          "value": "scoreForPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModel~1score(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scoreForPlayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelMinScore/title",
          "value": "GKGameModelMinScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGameModelMinScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameModelMinScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GK_VERSION/title",
          "value": "GK_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GK_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GK_VERSION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gameplaykit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gameplaykit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
