{
  "abstract": [
    {
      "text": "A set of goals that together influence the movement of an agent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKBehavior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKBehavior"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKBehavior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKBehavior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By combining multiple goals (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects) you can create complex behavior, such as groups of agents  (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects) that move together naturally. To assign a set of goals to an agent, use its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent/behavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about using goals and agents, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent": {
      "abstract": [
        {
          "text": "A component that moves a game entity according to a set of goals and realistic constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgent"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgent"
        }
      ],
      "role": "symbol",
      "title": "GKAgent",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent/behavior": {
      "abstract": [
        {
          "text": "A weighted collection of goals that influence the agent’s movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent/behavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behavior"
        }
      ],
      "role": "symbol",
      "title": "behavior",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent/behavior"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D": {
      "abstract": [
        {
          "text": "An agent that operates in a two-dimensional space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgent2D"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgent2D"
        }
      ],
      "role": "symbol",
      "title": "GKAgent2D",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent2d"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D": {
      "abstract": [
        {
          "text": "An agent that operates in a three-dimensional space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgent3D"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgent3D"
        }
      ],
      "role": "symbol",
      "title": "GKAgent3D",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent3d"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate": {
      "abstract": [
        {
          "text": "Implement this protocol to synchronize the state of an agent with its visual representation in your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgentDelegate"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgentDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKAgentDelegate",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagentdelegate"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior": {
      "abstract": [
        {
          "text": "A set of goals that together influence the movement of an agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKBehavior"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKBehavior"
        }
      ],
      "role": "symbol",
      "title": "GKBehavior",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/goalCount": {
      "abstract": [
        {
          "text": "The number of goals in the behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "goalCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/goalCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "goalCount"
        }
      ],
      "role": "symbol",
      "title": "goalCount",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/goalcount"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goal:weight:)": {
      "abstract": [
        {
          "text": "Creates a behavior with a single goal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "goal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goal:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorWithGoal:weight:"
        }
      ],
      "role": "symbol",
      "title": "init(goal:weight:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/init(goal:weight:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:)": {
      "abstract": [
        {
          "text": "Creates a behavior with the specified goals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "goals"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorWithGoals:"
        }
      ],
      "role": "symbol",
      "title": "init(goals:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/init(goals:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:andWeights:)": {
      "abstract": [
        {
          "text": "Creates a behavior with the specified goals and weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "goals"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "andWeights"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:andWeights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorWithGoals:andWeights:"
        }
      ],
      "role": "symbol",
      "title": "init(goals:andWeights:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/init(goals:andweights:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(weightedGoals:)": {
      "abstract": [
        {
          "text": "Creates a behavior with the specified mapping of goals to their weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "weightedGoals"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(weightedGoals:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorWithWeightedGoals:"
        }
      ],
      "role": "symbol",
      "title": "init(weightedGoals:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/init(weightedgoals:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/remove(_:)": {
      "abstract": [
        {
          "text": "Removes the specified goal from the behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/remove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeGoal:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/remove(_:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/removeAllGoals()": {
      "abstract": [
        {
          "text": "Removes all goals from the behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllGoals"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/removeAllGoals()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllGoals"
        }
      ],
      "role": "symbol",
      "title": "removeAllGoals()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/removeallgoals()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setObject:forKeyedSubscript:": {
      "abstract": [
        {
          "text": "Sets the weight for the goal specified by subscript syntax.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setObject:forKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/setobject:forkeyedsubscript:"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setWeight(_:for:)": {
      "abstract": [
        {
          "text": "Sets the weight for the specified goal’s influence on agents, adding that goal to the behavior if not already present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setWeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setWeight(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setWeight:forGoal:"
        }
      ],
      "role": "symbol",
      "title": "setWeight(_:for:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/setweight(_:for:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-2yvko": {
      "abstract": [
        {
          "text": "Returns the weight associated with the goal specified by subscript syntax.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-2yvko",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/subscript(_:)-2yvko"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-997a9": {
      "abstract": [
        {
          "text": "Returns the goal at the specified index in the behavior’s list of goals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-997a9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectAtIndexedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/subscript(_:)-997a9"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/weight(for:)": {
      "abstract": [
        {
          "text": "Returns the weight for the specified goal’s influence on agents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKGoal",
          "text": "GKGoal"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/weight(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "weightForGoal:"
        }
      ],
      "role": "symbol",
      "title": "weight(for:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior/weight(for:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior": {
      "abstract": [
        {
          "text": "A set of behaviors, each of which is a set of goals, that together influence the movement of an agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCompositeBehavior"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCompositeBehavior"
        }
      ],
      "role": "symbol",
      "title": "GKCompositeBehavior",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal": {
      "abstract": [
        {
          "text": "An influence that motivates the movement of one or more agents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGoal"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGoal"
        }
      ],
      "role": "symbol",
      "title": "GKGoal",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgoal"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath": {
      "abstract": [
        {
          "text": "A polygonal path that can be followed by an agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPath"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPath"
        }
      ],
      "role": "symbol",
      "title": "GKPath",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkpath"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to support fast enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSFastEnumeration"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFastEnumeration",
      "type": "topic",
      "url": "/documentation/foundation/nsfastenumeration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8",
      "title": "Agents, Goals, and Behaviors",
      "titleInlineContent": [
        {
          "text": "Agents, Goals, and Behaviors",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
      "title": "GameplayKit Programming Guide",
      "titleInlineContent": [
        {
          "text": "GameplayKit Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Agents-Goals-and-Behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate"
      ],
      "title": "Agents, Goals, and Behaviors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Behavior",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goal:weight:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:andWeights:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(weightedGoals:)"
      ],
      "title": "Creating a Behavior"
    },
    {
      "anchor": "Managing-a-Behaviors-Set-of-Goals",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setWeight(_:for:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/weight(for:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/remove(_:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/removeAllGoals()",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/goalCount"
      ],
      "title": "Managing a Behavior’s Set of Goals"
    },
    {
      "anchor": "Working-with-Goals-Using-Subscript-Syntax",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-2yvko",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-997a9"
      ],
      "title": "Working with Goals Using Subscript Syntax"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKBehavior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Behavior",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goal:weight:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(goals:andWeights:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/init(weightedGoals:)"
              ],
              "title": "Creating a Behavior"
            },
            {
              "anchor": "Managing-a-Behaviors-Set-of-Goals",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setWeight(_:for:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/weight(for:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/remove(_:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/removeAllGoals()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/goalCount"
              ],
              "title": "Managing a Behavior’s Set of Goals"
            },
            {
              "anchor": "Working-with-Goals-Using-Subscript-Syntax",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-2yvko",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/setObject:forKeyedSubscript:",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior/subscript(_:)-997a9"
              ],
              "title": "Working with Goals Using Subscript Syntax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Agents-Goals-and-Behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate"
              ],
              "title": "Agents, Goals, and Behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPath/title",
          "value": "GKPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgentDelegate/title",
          "value": "GKAgentDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgentDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgentDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1subscript(_:)-2yvko/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1subscript(_:)-2yvko/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1setWeight(_:for:)/title",
          "value": "setWeight:forGoal:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1setWeight(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setWeight:forGoal:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGoal/title",
          "value": "GKGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGoal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1subscript(_:)-997a9/title",
          "value": "objectAtIndexedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1subscript(_:)-997a9/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectAtIndexedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(goals:andWeights:)/title",
          "value": "behaviorWithGoals:andWeights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(goals:andWeights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "behaviorWithGoals:andWeights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent/title",
          "value": "GKAgent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(weightedGoals:)/title",
          "value": "behaviorWithWeightedGoals:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(weightedGoals:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "behaviorWithWeightedGoals:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent2D/title",
          "value": "GKAgent2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent~1behavior/title",
          "value": "behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent~1behavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior/title",
          "value": "GKCompositeBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1goalCount/title",
          "value": "goalCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1goalCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "goalCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(goals:)/title",
          "value": "behaviorWithGoals:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(goals:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "behaviorWithGoals:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent3D/title",
          "value": "GKAgent3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1weight(for:)/title",
          "value": "weightForGoal:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1weight(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "weightForGoal:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior/title",
          "value": "GKBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1removeAllGoals()/title",
          "value": "removeAllGoals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1removeAllGoals()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllGoals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(goal:weight:)/title",
          "value": "behaviorWithGoal:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1init(goal:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "behaviorWithGoal:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1remove(_:)/title",
          "value": "removeGoal:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior~1remove(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeGoal:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkbehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gkbehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
