{
  "abstract": [
    {
      "text": "A set of behaviors, each of which is a set of goals, that together influence the movement of an agent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKCompositeBehavior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKCompositeBehavior"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKCompositeBehavior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKCompositeBehavior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By composing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects into subgroups (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects) and composing those behaviors into composite behaviors, you can control certain aspects of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s movement in concert. To assign a behavior to an agent, use its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent/behavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, you might create a behavior for a set of agents to stay together as a flock (with cohesion, alignment, and separation goals) while loosely following a path. With a single ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, whenever you want to change the importance of the flocking goals relative to the path-following goals, you’d need to individually change the weight of each goal. With a composite behavior, you can adjust the relative influence of a group of goals together, as in the following code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let flock = GKBehavior(goals: [",
                    "    GKGoal(toAlignWith: agents, maxDistance: 10, maxAngle: .pi/4),",
                    "    GKGoal(toCohereWith: agents, maxDistance: 10, maxAngle: .pi/4),",
                    "    GKGoal(toSeparateFrom: agents, maxDistance: 10, maxAngle: .pi/4),",
                    "])",
                    "let meanderOnPath = GKBehavior(goals: [",
                    "    GKGoal(toFollow: path, maxPredictionTime: 1, forward: true),",
                    "    GKGoal(toWander: 10)",
                    "])",
                    "let composite = GKCompositeBehavior(behaviors: [",
                    "    flock, meanderOnPath",
                    "])"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "GKBehavior *flock = [GKBehavior behaviorWithGoals:@[",
                    "    [GKGoal goalToAlignWithAgents:agents maxDistance:10 maxAngle:M_PI_4],",
                    "    [GKGoal goalToCohereWithAgents:agents maxDistance:10 maxAngle:M_PI_4],",
                    "    [GKGoal goalToSeparateFromAgents:agents maxDistance:10 maxAngle:M_PI_4]",
                    "]];",
                    "GKBehavior *meanderOnPath = [GKBehavior behaviorWithgoals:@[",
                    "    [GKGoal goalToFollowPath:path maxPredictionTime:1.0 forward:YES],",
                    "    [GKGoal goalToWander:10]",
                    "]];",
                    "GKCompositeBehavior *composite = [GKCompositeBehavior behaviorWithBehaviors:@[",
                    "    flock, meanderOnPath",
                    "]];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "After constructing this behavior, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setWeight(_:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to increase or decrease the influence of the ",
              "type": "text"
            },
            {
              "code": "flock",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "meanderOnPath",
              "type": "codeVoice"
            },
            {
              "text": " behaviors relative to one another.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about using goals and agents, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent": {
      "abstract": [
        {
          "text": "A component that moves a game entity according to a set of goals and realistic constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgent"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgent"
        }
      ],
      "role": "symbol",
      "title": "GKAgent",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent/behavior": {
      "abstract": [
        {
          "text": "A weighted collection of goals that influence the agent’s movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent/behavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behavior"
        }
      ],
      "role": "symbol",
      "title": "behavior",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent/behavior"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D": {
      "abstract": [
        {
          "text": "An agent that operates in a two-dimensional space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgent2D"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgent2D"
        }
      ],
      "role": "symbol",
      "title": "GKAgent2D",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent2d"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D": {
      "abstract": [
        {
          "text": "An agent that operates in a three-dimensional space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgent3D"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgent3D"
        }
      ],
      "role": "symbol",
      "title": "GKAgent3D",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagent3d"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate": {
      "abstract": [
        {
          "text": "Implement this protocol to synchronize the state of an agent with its visual representation in your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAgentDelegate"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAgentDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKAgentDelegate",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkagentdelegate"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior": {
      "abstract": [
        {
          "text": "A set of goals that together influence the movement of an agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKBehavior"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKBehavior"
        }
      ],
      "role": "symbol",
      "title": "GKBehavior",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbehavior"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior": {
      "abstract": [
        {
          "text": "A set of behaviors, each of which is a set of goals, that together influence the movement of an agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCompositeBehavior"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCompositeBehavior"
        }
      ],
      "role": "symbol",
      "title": "GKCompositeBehavior",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/behaviorCount": {
      "abstract": [
        {
          "text": "The number of individual behaviors in the composite behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behaviorCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/behaviorCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorCount"
        }
      ],
      "role": "symbol",
      "title": "behaviorCount",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/behaviorcount"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:)": {
      "abstract": [
        {
          "text": "Creates a composite behavior from the specified individual behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "behaviors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorWithBehaviors:"
        }
      ],
      "role": "symbol",
      "title": "init(behaviors:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/init(behaviors:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:andWeights:)": {
      "abstract": [
        {
          "text": "Creates a behavior with the specified behaviors and weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "behaviors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "andWeights"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:andWeights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behaviorWithBehaviors:andWeights:"
        }
      ],
      "role": "symbol",
      "title": "init(behaviors:andWeights:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/init(behaviors:andweights:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/remove(_:)": {
      "abstract": [
        {
          "text": "Removes the specified individual behavior from the composite behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/remove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeBehavior:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/remove(_:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/removeAllBehaviors()": {
      "abstract": [
        {
          "text": "Removes all individual behaviors from the composite behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllBehaviors"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/removeAllBehaviors()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllBehaviors"
        }
      ],
      "role": "symbol",
      "title": "removeAllBehaviors()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/removeallbehaviors()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setObject:forKeyedSubscript:": {
      "abstract": [
        {
          "text": "Sets the weight for the behavior specified by subscript syntax.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setObject:forKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/setobject:forkeyedsubscript:"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setWeight(_:for:)": {
      "abstract": [
        {
          "text": "Sets the weight for the specified individual behavior’s influence on agents, adding that behavior to the composite behavior if it is not already present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setWeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setWeight(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setWeight:forBehavior:"
        }
      ],
      "role": "symbol",
      "title": "setWeight(_:for:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/setweight(_:for:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6jng9": {
      "abstract": [
        {
          "text": "Returns the weight associated with the behavior specified by subscript syntax.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6jng9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/subscript(_:)-6jng9"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6krdg": {
      "abstract": [
        {
          "text": "Returns the individual behavior at the specified index in the composite behavior’s list of behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6krdg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectAtIndexedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/subscript(_:)-6krdg"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/weight(for:)": {
      "abstract": [
        {
          "text": "Returns the weight for the specified individual behavior’s influence on agents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKBehavior",
          "text": "GKBehavior"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/weight(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "weightForBehavior:"
        }
      ],
      "role": "symbol",
      "title": "weight(for:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcompositebehavior/weight(for:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal": {
      "abstract": [
        {
          "text": "An influence that motivates the movement of one or more agents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGoal"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGoal"
        }
      ],
      "role": "symbol",
      "title": "GKGoal",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgoal"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath": {
      "abstract": [
        {
          "text": "A polygonal path that can be followed by an agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPath"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPath"
        }
      ],
      "role": "symbol",
      "title": "GKPath",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkpath"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to support fast enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSFastEnumeration"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFastEnumeration",
      "type": "topic",
      "url": "/documentation/foundation/nsfastenumeration"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8",
      "title": "Agents, Goals, and Behaviors",
      "titleInlineContent": [
        {
          "text": "Agents, Goals, and Behaviors",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/Agent.html#//apple_ref/doc/uid/TP40015172-CH8"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
      "title": "GameplayKit Programming Guide",
      "titleInlineContent": [
        {
          "text": "GameplayKit Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSFastEnumeration",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Agents-Goals-and-Behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate"
      ],
      "title": "Agents, Goals, and Behaviors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Composite-Behavior",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:andWeights:)"
      ],
      "title": "Creating a Composite Behavior"
    },
    {
      "anchor": "Managing-the-Individual-Behaviors-in-a-Composite-Behavior",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setWeight(_:for:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/weight(for:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/remove(_:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/removeAllBehaviors()",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/behaviorCount"
      ],
      "title": "Managing the Individual Behaviors in a Composite Behavior"
    },
    {
      "anchor": "Working-with-Behaviors-Using-Subscript-Syntax",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6jng9",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6krdg"
      ],
      "title": "Working with Behaviors Using Subscript Syntax"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKCompositeBehavior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Composite-Behavior",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/init(behaviors:andWeights:)"
              ],
              "title": "Creating a Composite Behavior"
            },
            {
              "anchor": "Managing-the-Individual-Behaviors-in-a-Composite-Behavior",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setWeight(_:for:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/weight(for:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/remove(_:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/removeAllBehaviors()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/behaviorCount"
              ],
              "title": "Managing the Individual Behaviors in a Composite Behavior"
            },
            {
              "anchor": "Working-with-Behaviors-Using-Subscript-Syntax",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6jng9",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/setObject:forKeyedSubscript:",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCompositeBehavior/subscript(_:)-6krdg"
              ],
              "title": "Working with Behaviors Using Subscript Syntax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Agents-Goals-and-Behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent2D",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgent3D",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGoal",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPath",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKAgentDelegate"
              ],
              "title": "Agents, Goals, and Behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKCompositeBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBehavior",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GKBehavior",
                    "text": "GKBehavior"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgentDelegate/title",
          "value": "GKAgentDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgentDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgentDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgentDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent~1behavior/title",
          "value": "behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent~1behavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1subscript(_:)-6krdg/title",
          "value": "objectAtIndexedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1subscript(_:)-6krdg/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectAtIndexedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1removeAllBehaviors()/title",
          "value": "removeAllBehaviors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1removeAllBehaviors()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllBehaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1setWeight(_:for:)/title",
          "value": "setWeight:forBehavior:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1setWeight(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setWeight:forBehavior:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent2D/title",
          "value": "GKAgent2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1subscript(_:)-6jng9/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1subscript(_:)-6jng9/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1init(behaviors:andWeights:)/title",
          "value": "behaviorWithBehaviors:andWeights:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1init(behaviors:andWeights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "behaviorWithBehaviors:andWeights:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1behaviorCount/title",
          "value": "behaviorCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1behaviorCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "behaviorCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGoal/title",
          "value": "GKGoal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGoal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGoal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGoal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent/title",
          "value": "GKAgent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior/title",
          "value": "GKCompositeBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCompositeBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1weight(for:)/title",
          "value": "weightForBehavior:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1weight(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "weightForBehavior:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1init(behaviors:)/title",
          "value": "behaviorWithBehaviors:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1init(behaviors:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "behaviorWithBehaviors:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPath/title",
          "value": "GKPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent3D/title",
          "value": "GKAgent3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKAgent3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAgent3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1remove(_:)/title",
          "value": "removeBehavior:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCompositeBehavior~1remove(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeBehavior:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior/title",
          "value": "GKBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkcompositebehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gkcompositebehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
