{
  "abstract": [
    {
      "text": "A generator for random numbers that follow a ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Gaussian distribution",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " (also known as a ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "normal distribution",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ") across multiple samplings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKGaussianDistribution",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKGaussianDistribution"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKGaussianDistribution"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKGaussianDistribution"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The randomization services provided in GameplayKit are suitable for reliably creating deterministic, pseudorandom gameplay mechanics, but are not cryptographically robust. For cryptography, obfuscation, or cipher uses, use the Security framework, described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2133123",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In a Gaussian distribution, random samplings are most likely to result in a value near the center of the distribution, and have reduced probability of producing higher or lower values. To generate random numbers with a Gaussian distribution, use the methods defined by its superclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A Gaussian distribution is characterized by its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/mean",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/deviation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/mean",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value (also called the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "median",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "expected value",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ") is the value at the center of the distribution (halfway between its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties), and the most likely value to result from a random sampling. The farther any other value is from the mean, the less likely that value is to result from a random sampling. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/deviation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value (also called ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "standard deviation",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "sigma",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ") characterizes those probabilities: 68.27% of values generated by the distribution are within one deviation of the mean, 95% of generated values are within two deviations, and 100% of generated values are within three deviations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In the standard mathematical model of a Gaussian distribution, 99.7% of generated values are within three deviations of the mean and the distribution’s range is infinite. GameplayKit discards the extremely unlikely values more than three deviations from the mean in order to set finite limits on the distribution’s range.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Gaussian distributions appear in many natural phenomena that you might model in a game. For example, the following code creates a distribution whose random number generation is equivalent to rolling three six-sided dice (also called ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "3d6",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ") and summing the results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let random = GKRandomSource()",
                    "let dice3d6 = GKGaussianDistribution(randomSource: random, lowestValue: 3, highestValue: 18)",
                    "// Roll the dice...",
                    "let diceRoll = dice3d6.nextInt()"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "GKRandomSource *random = [[GKRandomSource alloc] init];",
                    "GKRandomDistribution *dice3d6;",
                    "dice3d6 = [[GKGaussianDistribution alloc]",
                    "              initWithRandomSource:random lowestValue:3 highestValue:18];",
                    "// Roll the dice...",
                    "int diceRoll = [dice3d6 nextInt];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on choosing and using randomizers in GameplayKit, read ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the ARC4 algorithm, which is suitable for most gameplay mechanics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKARC4RandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKARC4RandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKARC4RandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkarc4randomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution": {
      "abstract": [
        {
          "text": "A generator for random numbers that follow a ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Gaussian distribution",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " (also known as a ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "normal distribution",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") across multiple samplings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGaussianDistribution"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGaussianDistribution"
        }
      ],
      "role": "symbol",
      "title": "GKGaussianDistribution",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgaussiandistribution"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/deviation": {
      "abstract": [
        {
          "text": "The standard deviation of the distribution (also called ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "sigma",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/deviation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviation"
        }
      ],
      "role": "symbol",
      "title": "deviation",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgaussiandistribution/deviation"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:lowestValue:highestValue:)": {
      "abstract": [
        {
          "text": "Initializes a Gaussian random distribution with the specified lower and upper bounds, using the specified source randomizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "randomSource"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKRandom",
          "text": "GKRandom"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lowestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "highestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:lowestValue:highestValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRandomSource:lowestValue:highestValue:"
        }
      ],
      "role": "symbol",
      "title": "init(randomSource:lowestValue:highestValue:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgaussiandistribution/init(randomsource:lowestvalue:highestvalue:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:mean:deviation:)": {
      "abstract": [
        {
          "text": "Initializes a Gaussian random distribution with the specified mean and deviation, using the specified source randomizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "randomSource"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKRandom",
          "text": "GKRandom"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:mean:deviation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRandomSource:mean:deviation:"
        }
      ],
      "role": "symbol",
      "title": "init(randomSource:mean:deviation:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgaussiandistribution/init(randomsource:mean:deviation:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/mean": {
      "abstract": [
        {
          "text": "The mean value of the distribution (also called the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "expected value",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "median",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/mean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mean"
        }
      ],
      "role": "symbol",
      "title": "mean",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgaussiandistribution/mean"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the linear congruential generator algorithm, which is faster but less random than the default random source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLinearCongruentialRandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLinearCongruentialRandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKLinearCongruentialRandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gklinearcongruentialrandomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the Mersenne Twister algorithm, which is more random, but slower than the default random source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMersenneTwisterRandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMersenneTwisterRandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKMersenneTwisterRandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkmersennetwisterrandomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom": {
      "abstract": [
        {
          "text": "The common interface for all randomization classes in (or usable with) GameplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRandom"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRandom"
        }
      ],
      "role": "symbol",
      "title": "GKRandom",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandom"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution": {
      "abstract": [
        {
          "text": "A generator for random numbers that fall within a specific range and that exhibit a specific distribution over multiple samplings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRandomDistribution"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRandomDistribution"
        }
      ],
      "role": "symbol",
      "title": "GKRandomDistribution",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue": {
      "abstract": [
        {
          "text": "The highest value to be produced by the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highestValue"
        }
      ],
      "role": "symbol",
      "title": "highestValue",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/highestvalue"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue": {
      "abstract": [
        {
          "text": "The lowest value to be produced by the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowestValue"
        }
      ],
      "role": "symbol",
      "title": "lowestValue",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/lowestvalue"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource": {
      "abstract": [
        {
          "text": "The superclass for all basic randomization classes in GameplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKRandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution": {
      "abstract": [
        {
          "text": "A generator for random numbers that are uniformly distributed across many samplings, but where short sequences of similar values are unlikely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKShuffledDistribution"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKShuffledDistribution"
        }
      ],
      "role": "symbol",
      "title": "GKShuffledDistribution",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkshuffleddistribution"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9",
      "title": "Randomization",
      "titleInlineContent": [
        {
          "text": "Randomization",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
      "title": "GameplayKit Programming Guide",
      "titleInlineContent": [
        {
          "text": "GameplayKit Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172"
    },
    "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172",
      "title": "Cryptographic Services Guide",
      "titleInlineContent": [
        {
          "text": "Cryptographic Services Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172"
    },
    "media-2133123": {
      "alt": null,
      "identifier": "media-2133123",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e1590e1293678bcc5374644c27caba72/media-2133123@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Randomization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution"
      ],
      "title": "Randomization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Random-Distribution",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:lowestValue:highestValue:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:mean:deviation:)"
      ],
      "title": "Creating a Random Distribution"
    },
    {
      "anchor": "Working-with-Characteristics-of-a-Distribution",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/mean",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/deviation"
      ],
      "title": "Working with Characteristics of a Distribution"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKGaussianDistribution"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Random-Distribution",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:lowestValue:highestValue:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/init(randomSource:mean:deviation:)"
              ],
              "title": "Creating a Random Distribution"
            },
            {
              "anchor": "Working-with-Characteristics-of-a-Distribution",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/mean",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution/deviation"
              ],
              "title": "Working with Characteristics of a Distribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Randomization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution"
              ],
              "title": "Randomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKGaussianDistribution"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GKRandomDistribution",
                    "text": "GKRandomDistribution"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKShuffledDistribution/title",
          "value": "GKShuffledDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKShuffledDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKShuffledDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKShuffledDistribution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKShuffledDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1init(randomSource:lowestValue:highestValue:)/title",
          "value": "initWithRandomSource:lowestValue:highestValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1init(randomSource:lowestValue:highestValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRandomSource:lowestValue:highestValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKLinearCongruentialRandomSource/title",
          "value": "GKLinearCongruentialRandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKLinearCongruentialRandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLinearCongruentialRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKLinearCongruentialRandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLinearCongruentialRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1init(randomSource:mean:deviation:)/title",
          "value": "initWithRandomSource:mean:deviation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1init(randomSource:mean:deviation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRandomSource:mean:deviation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1deviation/title",
          "value": "deviation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1deviation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandom/title",
          "value": "GKRandom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandom/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKARC4RandomSource/title",
          "value": "GKARC4RandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKARC4RandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKARC4RandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKARC4RandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKARC4RandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution/title",
          "value": "GKRandomDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1mean/title",
          "value": "mean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution~1mean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMersenneTwisterRandomSource/title",
          "value": "GKMersenneTwisterRandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMersenneTwisterRandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMersenneTwisterRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMersenneTwisterRandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMersenneTwisterRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomSource/title",
          "value": "GKRandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution/title",
          "value": "GKGaussianDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1lowestValue/title",
          "value": "lowestValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1lowestValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowestValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1highestValue/title",
          "value": "highestValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1highestValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highestValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkgaussiandistribution"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gkgaussiandistribution"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
