{
  "abstract": [
    {
      "text": "A sample of procedural noise data from which you can read noise values directly or create noise textures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKNoiseMap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKNoiseMap"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKNoiseMap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKNoiseMap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKNoiseMap"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Working with procedural noise involves three main steps, one of each of the three major GameplayKit noise classes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Noise sources (the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class cluster) represent the core algorithms and parameters for generating noise. You choose a general style of noise by instantiating and configuring one of the concrete ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " subclasses.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Noise objects (",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instances) represent the field of noise generated by a noise source. You create a noise object from a noise source, and can then process it or combine it with other noise objects to create more complex noise patterns. Noise objects are lightweight: GameplayKit defers the computation of generating noise and applying noise processing operations until you’re ready to create output.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects are the concrete output of noise generation and processing. Creating a noise map performs the computation described by the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects you create it from, filling a 2D grid of a specific size with noise values based on a slice of the noise object’s 3D noise field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can apply noise maps in many different ways. Some examples include :",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Creating texture images resembling natural phenomena such as clouds, stone surfaces, and wood grain. You can also use noise textures as normal maps to make surfaces appear more natural under lighting. (See the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SpriteKit/SKTexture",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SpriteKit/SKTexture/init(noiseMap:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Generating procedural game-world maps resembling natural terrain. You can create game world of infinite size by using procedural noise as its underlying representation, and manage storage and memory efficiently by creating noise maps (and their visual representations) only for the area around a player’s current position. (See the ",
                      "type": "text"
                    },
                    {
                      "code": "SKTileMap",
                      "type": "codeVoice"
                    },
                    {
                      "text": " class.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adding a degree of randomness to otherwise smooth movements. For example, you can make game characters move in a jittery manner, or apply a hand-held motion effect to a game camera.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The content of a noise map is a field of floating-point values that, by default, range from ",
              "type": "text"
            },
            {
              "code": "-1.0",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ". You can access these values individually with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/value(at:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/interpolatedValue(at:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods, or create SpriteKit resources from the entire noise map’s values with the methods mentioned above.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A noise map is finite and two-dimensional, but the the noise you sample to create it is three-dimensional and infinite in extent. You can create interesting effects by transforming noise in three dimensions before creating a noise map. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "By using a cylindrical noise source and applying the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/rotate(by:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method, you can sample a slice through the cylinders that creates a wood-grain effect.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "By using a Perlin noise source and applying the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/move(by:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method between multiple samples, you can animate a noise map that simulates the way clouds form, billow, and dissipate over time.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2133131",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/SpriteKit/SKTexture": {
      "abstract": [
        {
          "text": "An image, decoded on the GPU, that can be used to render various SpriteKit objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTexture"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SpriteKit/SKTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKTexture",
      "type": "topic",
      "url": "/documentation/SpriteKit/SKTexture"
    },
    "doc://com.apple.documentation/documentation/SpriteKit/SKTexture/init(noiseMap:)": {
      "abstract": [
        {
          "text": "Creates a texture from the specified noise map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "noiseMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoiseMap",
          "text": "GKNoiseMap"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SpriteKit/SKTexture/init(noiseMap:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(noiseMap:)",
      "type": "topic",
      "url": "/documentation/SpriteKit/SKTexture/init(noiseMap:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBillowNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is a type of fractal coherent noise with smooth features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKBillowNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBillowNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKBillowNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKBillowNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkbillownoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCheckerboardNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is an alternating square pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCheckerboardNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCheckerboardNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCheckerboardNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKCheckerboardNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcheckerboardnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource": {
      "abstract": [
        {
          "text": "The abstract superclass for procedural noise generators that create coherent noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCoherentNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCoherentNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKCoherentNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcoherentnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKConstantNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator that outputs a field of a single constant value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKConstantNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKConstantNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKConstantNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKConstantNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkconstantnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCylindersNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is a 3D field of concentric cylindrical shells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCylindersNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCylindersNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCylindersNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKCylindersNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcylindersnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise": {
      "abstract": [
        {
          "text": "A representation of procedural noise, generated by a noise source, that you can use to process, transform, or combine noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKNoise"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKNoise"
        }
      ],
      "role": "symbol",
      "title": "GKNoise",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoise"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/move(by:)": {
      "abstract": [
        {
          "text": "Translates the entire noise field by the specified x, y, and z offsets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "move"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "by"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_double3",
          "text": "vector_double3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/move(by:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveBy:"
        }
      ],
      "role": "symbol",
      "title": "move(by:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoise/move(by:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/rotate(by:)": {
      "abstract": [
        {
          "text": "Rotates the entire noise field by the specified x, y, and z angles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "by"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_double3",
          "text": "vector_double3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/rotate(by:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotateBy:"
        }
      ],
      "role": "symbol",
      "title": "rotate(by:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoise/rotate(by:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap": {
      "abstract": [
        {
          "text": "A sample of procedural noise data from which you can read noise values directly or create noise textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKNoiseMap"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKNoiseMap"
        }
      ],
      "role": "symbol",
      "title": "GKNoiseMap",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init()": {
      "abstract": [
        {
          "text": "Initializes a noise map with a constant noise value of zero throughout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/init()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:)": {
      "abstract": [
        {
          "text": "Initializes a noise map by sampling from the specified noise object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoise",
          "text": "GKNoise"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithNoise:"
        }
      ],
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/init(_:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:size:origin:sampleCount:seamless:)": {
      "abstract": [
        {
          "text": "Creates a noise map by sampling from the specified noise object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoise",
          "text": "GKNoise"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_double2",
          "text": "vector_double2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "origin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_double2",
          "text": "vector_double2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "seamless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:size:origin:sampleCount:seamless:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithNoise:size:origin:sampleCount:seamless:"
        }
      ],
      "role": "symbol",
      "title": "init(_:size:origin:sampleCount:seamless:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/init(_:size:origin:samplecount:seamless:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/interpolatedValue(at:)": {
      "abstract": [
        {
          "text": "Returns the value at the specified position in the noise map, interpolating results for positions not on the discrete sample grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interpolatedValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/interpolatedValue(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interpolatedValueAtPosition:"
        }
      ],
      "role": "symbol",
      "title": "interpolatedValue(at:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/interpolatedvalue(at:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/isSeamless": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the noise map’s output can repeat seamlessly in all directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSeamless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/isSeamless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seamless"
        }
      ],
      "role": "symbol",
      "title": "isSeamless",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/isseamless"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/noiseMapWithNoise:": {
      "abstract": [
        {
          "text": "Creates a noise map by sampling from the specified noise object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "noiseMapWithNoise:"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/noiseMapWithNoise:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noiseMapWithNoise:"
        }
      ],
      "role": "symbol",
      "title": "noiseMapWithNoise:",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/noisemapwithnoise:"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/noiseMapWithNoise:size:origin:sampleCount:seamless:": {
      "abstract": [
        {
          "text": "Creates a noise map by sampling from the specified noise object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "noiseMapWithNoise:size:origin:sampleCount:seamless:"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/noiseMapWithNoise:size:origin:sampleCount:seamless:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noiseMapWithNoise:size:origin:sampleCount:seamless:"
        }
      ],
      "role": "symbol",
      "title": "noiseMapWithNoise:size:origin:sampleCount:seamless:",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/noisemapwithnoise:size:origin:samplecount:seamless:"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/origin": {
      "abstract": [
        {
          "text": "The position of the “slice” of noise samples contained in the noise map relative to the unit coordinate space of the noise object it was created from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "origin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_double2",
          "text": "vector_double2"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/origin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "origin"
        }
      ],
      "role": "symbol",
      "title": "origin",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/origin"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/sampleCount": {
      "abstract": [
        {
          "text": "The width and height of integer grid for which the noise map contains sampled noise values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/sampleCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleCount"
        }
      ],
      "role": "symbol",
      "title": "sampleCount",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/samplecount"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/setValue(_:at:)": {
      "abstract": [
        {
          "text": "Sets the value at the specified position in the noise map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/setValue(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setValue:atPosition:"
        }
      ],
      "role": "symbol",
      "title": "setValue(_:at:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/setvalue(_:at:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/size": {
      "abstract": [
        {
          "text": "The size of the “slice” of noise samples contained in the noise map relative to the unit coordinate space of the noise object it was created from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_double2",
          "text": "vector_double2"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/size"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/value(at:)": {
      "abstract": [
        {
          "text": "Returns the value at the specified position in the noise map’s discrete sample grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/value(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueAtPosition:"
        }
      ],
      "role": "symbol",
      "title": "value(at:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisemap/value(at:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource": {
      "abstract": [
        {
          "text": "The abstract superclass for procedural noise generators.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is a type of fractal coherent noise resembling natural phenomena such as clouds and terrain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPerlinNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPerlinNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKPerlinNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkperlinnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRidgedNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is a type of multifractal coherent noise with sharply defined features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRidgedNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRidgedNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRidgedNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKRidgedNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkridgednoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKSpheresNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is a 3D field of concentric spherical shells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSpheresNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKSpheresNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSpheresNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKSpheresNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkspheresnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKVoronoiNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output (also called Worley noise or cellular noise) divides space into discrete cells surrounding random seed points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoronoiNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKVoronoiNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoronoiNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKVoronoiNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkvoronoinoisesource"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-2133131": {
      "alt": null,
      "identifier": "media-2133131",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bc1d6801d94be741b1d2e819b553f765/media-2133131@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Procedural-Noise",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBillowNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRidgedNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKVoronoiNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCylindersNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKSpheresNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCheckerboardNoiseSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKConstantNoiseSource"
      ],
      "title": "Procedural Noise"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Noise-Map",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:size:origin:sampleCount:seamless:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init()"
      ],
      "title": "Creating a Noise Map"
    },
    {
      "anchor": "Accessing-Noise-Values",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/value(at:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/interpolatedValue(at:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/setValue(_:at:)"
      ],
      "title": "Accessing Noise Values"
    },
    {
      "anchor": "Inspecting-a-Noise-Map",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/size",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/origin",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/sampleCount",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/isSeamless"
      ],
      "title": "Inspecting a Noise Map"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKNoiseMap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoiseMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoiseMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Noise-Map",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init(_:size:origin:sampleCount:seamless:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/init()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/noiseMapWithNoise:",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/noiseMapWithNoise:size:origin:sampleCount:seamless:"
              ],
              "title": "Creating a Noise Map"
            },
            {
              "anchor": "Accessing-Noise-Values",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/value(at:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/interpolatedValue(at:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/setValue(_:at:)"
              ],
              "title": "Accessing Noise Values"
            },
            {
              "anchor": "Inspecting-a-Noise-Map",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/size",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/origin",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/sampleCount",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseMap/isSeamless"
              ],
              "title": "Inspecting a Noise Map"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Procedural-Noise",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKBillowNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRidgedNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKVoronoiNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCylindersNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKSpheresNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCheckerboardNoiseSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKConstantNoiseSource"
              ],
              "title": "Procedural Noise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKNoiseMap"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1interpolatedValue(at:)/title",
          "value": "interpolatedValueAtPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1interpolatedValue(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "interpolatedValueAtPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1sampleCount/title",
          "value": "sampleCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1sampleCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1setValue(_:at:)/title",
          "value": "setValue:atPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1setValue(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setValue:atPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseSource/title",
          "value": "GKNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRidgedNoiseSource/title",
          "value": "GKRidgedNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRidgedNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRidgedNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRidgedNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRidgedNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1rotate(by:)/title",
          "value": "rotateBy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1rotate(by:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotateBy:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1move(by:)/title",
          "value": "moveBy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1move(by:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveBy:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKVoronoiNoiseSource/title",
          "value": "GKVoronoiNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKVoronoiNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoronoiNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKVoronoiNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoronoiNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPerlinNoiseSource/title",
          "value": "GKPerlinNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPerlinNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPerlinNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPerlinNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPerlinNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBillowNoiseSource/title",
          "value": "GKBillowNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBillowNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBillowNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKBillowNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKBillowNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource/title",
          "value": "GKCoherentNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCoherentNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCoherentNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKConstantNoiseSource/title",
          "value": "GKConstantNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKConstantNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKConstantNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKConstantNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKConstantNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1init(_:)/title",
          "value": "initWithNoise:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1init(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithNoise:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1isSeamless/title",
          "value": "seamless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1isSeamless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seamless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKSpheresNoiseSource/title",
          "value": "GKSpheresNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKSpheresNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSpheresNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKSpheresNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSpheresNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise/title",
          "value": "GKNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SpriteKit~1SKTexture~1init(noiseMap:)/title",
          "value": "textureWithNoiseMap:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SpriteKit~1SKTexture~1init(noiseMap:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "textureWithNoiseMap:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKNoiseMap",
              "text": "GKNoiseMap"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "noiseMap"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap/title",
          "value": "GKNoiseMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoiseMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoiseMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1origin/title",
          "value": "origin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1origin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "origin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1init(_:size:origin:sampleCount:seamless:)/title",
          "value": "initWithNoise:size:origin:sampleCount:seamless:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1init(_:size:origin:sampleCount:seamless:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithNoise:size:origin:sampleCount:seamless:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCheckerboardNoiseSource/title",
          "value": "GKCheckerboardNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCheckerboardNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCheckerboardNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCheckerboardNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCheckerboardNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCylindersNoiseSource/title",
          "value": "GKCylindersNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCylindersNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCylindersNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCylindersNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCylindersNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1value(at:)/title",
          "value": "valueAtPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoiseMap~1value(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueAtPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SpriteKit~1SKTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKTexture"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gknoisemap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gknoisemap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
