{
  "abstract": [
    {
      "text": "A generator for random numbers that fall within a specific range and that exhibit a specific distribution over multiple samplings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKRandomDistribution",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKRandomDistribution"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKRandomDistribution"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKRandomDistribution"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The randomization services provided in GameplayKit are suitable for reliably creating deterministic, pseudorandom gameplay mechanics, but are not cryptographically robust. For cryptography, obfuscation, or cipher uses, use the Security framework, described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "You choose the algorithm that randomizes source values for a distribution by initializing it with an instance of any class that implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol, such as a basic random source (a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") or another random distribution. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class itself implements a uniform distribution—for more specialized distributions use one of the subclasses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "uniform",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " distribution, the probability of generating any number in a specified range (between the values of the distribution’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties) is approximately equal. In other words, there is no bias toward any possible outcome. To generate random numbers in this range, use the methods from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol listed in Generating Random Numbers below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on choosing and using randomizers in GameplayKit, read ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the ARC4 algorithm, which is suitable for most gameplay mechanics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKARC4RandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKARC4RandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKARC4RandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkarc4randomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution": {
      "abstract": [
        {
          "text": "A generator for random numbers that follow a ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Gaussian distribution",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " (also known as a ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "normal distribution",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") across multiple samplings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGaussianDistribution"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGaussianDistribution"
        }
      ],
      "role": "symbol",
      "title": "GKGaussianDistribution",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkgaussiandistribution"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the linear congruential generator algorithm, which is faster but less random than the default random source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLinearCongruentialRandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLinearCongruentialRandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKLinearCongruentialRandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gklinearcongruentialrandomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource": {
      "abstract": [
        {
          "text": "A basic random number generator implementing the Mersenne Twister algorithm, which is more random, but slower than the default random source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMersenneTwisterRandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMersenneTwisterRandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKMersenneTwisterRandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkmersennetwisterrandomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom": {
      "abstract": [
        {
          "text": "The common interface for all randomization classes in (or usable with) GameplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRandom"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRandom"
        }
      ],
      "role": "symbol",
      "title": "GKRandom",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandom"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution": {
      "abstract": [
        {
          "text": "A generator for random numbers that fall within a specific range and that exhibit a specific distribution over multiple samplings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRandomDistribution"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRandomDistribution"
        }
      ],
      "role": "symbol",
      "title": "GKRandomDistribution",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d20()": {
      "abstract": [
        {
          "text": "Creates a random distribution equivalent to a twenty-sided die.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "d20"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d20()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "d20"
        }
      ],
      "role": "symbol",
      "title": "d20()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/d20()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d6()": {
      "abstract": [
        {
          "text": "Creates a random distribution equivalent to a six-sided die.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "d6"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d6()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "d6"
        }
      ],
      "role": "symbol",
      "title": "d6()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/d6()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue": {
      "abstract": [
        {
          "text": "The highest value to be produced by the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highestValue"
        }
      ],
      "role": "symbol",
      "title": "highestValue",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/highestvalue"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(forDieWithSideCount:)": {
      "abstract": [
        {
          "text": "Creates a random distribution equivalent to a die with the specified number of sides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDieWithSideCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(forDieWithSideCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distributionForDieWithSideCount:"
        }
      ],
      "role": "symbol",
      "title": "init(forDieWithSideCount:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/init(fordiewithsidecount:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(lowestValue:highestValue:)": {
      "abstract": [
        {
          "text": "Creates a random distribution with the specified lower and upper bounds, using the Arc4 randomizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lowestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "highestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(lowestValue:highestValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distributionWithLowestValue:highestValue:"
        }
      ],
      "role": "symbol",
      "title": "init(lowestValue:highestValue:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/init(lowestvalue:highestvalue:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(randomSource:lowestValue:highestValue:)": {
      "abstract": [
        {
          "text": "Initializes a uniform random distribution with the specified lower and upper bounds, using the specified source randomizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "randomSource"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKRandom",
          "text": "GKRandom"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lowestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "highestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(randomSource:lowestValue:highestValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRandomSource:lowestValue:highestValue:"
        }
      ],
      "role": "symbol",
      "title": "init(randomSource:lowestValue:highestValue:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/init(randomsource:lowestvalue:highestvalue:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue": {
      "abstract": [
        {
          "text": "The lowest value to be produced by the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowestValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowestValue"
        }
      ],
      "role": "symbol",
      "title": "lowestValue",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/lowestvalue"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextBool()": {
      "abstract": [
        {
          "text": "Generates and returns a new random Boolean value within the characteristics of the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextBool"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextBool()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextBool"
        }
      ],
      "role": "symbol",
      "title": "nextBool()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/nextbool()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt()": {
      "abstract": [
        {
          "text": "Generates and returns a new random integer within the bounds of the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextInt"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextInt"
        }
      ],
      "role": "symbol",
      "title": "nextInt()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/nextint()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt(upperBound:)": {
      "abstract": [
        {
          "text": "Generates and returns a new random integer within the bounds of the distribution and less than the specified limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextInt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "upperBound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt(upperBound:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextIntWithUpperBound:"
        }
      ],
      "role": "symbol",
      "title": "nextInt(upperBound:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/nextint(upperbound:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextUniform()": {
      "abstract": [
        {
          "text": "Generates and returns a new random floating-point value within the characteristics of the distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextUniform"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextUniform()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextUniform"
        }
      ],
      "role": "symbol",
      "title": "nextUniform()",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/nextuniform()"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/numberOfPossibleOutcomes": {
      "abstract": [
        {
          "text": "The number of unique values the distribution can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfPossibleOutcomes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/numberOfPossibleOutcomes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfPossibleOutcomes"
        }
      ],
      "role": "symbol",
      "title": "numberOfPossibleOutcomes",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomdistribution/numberofpossibleoutcomes"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource": {
      "abstract": [
        {
          "text": "The superclass for all basic randomization classes in GameplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKRandomSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKRandomSource"
        }
      ],
      "role": "symbol",
      "title": "GKRandomSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkrandomsource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution": {
      "abstract": [
        {
          "text": "A generator for random numbers that are uniformly distributed across many samplings, but where short sequences of similar values are unlikely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKShuffledDistribution"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKShuffledDistribution"
        }
      ],
      "role": "symbol",
      "title": "GKShuffledDistribution",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkshuffleddistribution"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9",
      "title": "Randomization",
      "titleInlineContent": [
        {
          "text": "Randomization",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/RandomSources.html#//apple_ref/doc/uid/TP40015172-CH9"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172",
      "title": "GameplayKit Programming Guide",
      "titleInlineContent": [
        {
          "text": "GameplayKit Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/GameplayKit_Guide/index.html#//apple_ref/doc/uid/TP40015172"
    },
    "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172",
      "title": "Cryptographic Services Guide",
      "titleInlineContent": [
        {
          "text": "Cryptographic Services Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011172"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Randomization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution"
      ],
      "title": "Randomization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Random-Distribution",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(randomSource:lowestValue:highestValue:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(lowestValue:highestValue:)"
      ],
      "title": "Creating a Random Distribution"
    },
    {
      "anchor": "Creating-Specific-Random-Distributions",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d6()",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d20()",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(forDieWithSideCount:)"
      ],
      "title": "Creating Specific Random Distributions"
    },
    {
      "anchor": "Generating-Random-Numbers",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt()",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt(upperBound:)",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextUniform()",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextBool()"
      ],
      "title": "Generating Random Numbers"
    },
    {
      "anchor": "Working-with-Characteristics-of-a-Distribution",
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/numberOfPossibleOutcomes"
      ],
      "title": "Working with Characteristics of a Distribution"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKRandomDistribution"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Random-Distribution",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(randomSource:lowestValue:highestValue:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(lowestValue:highestValue:)"
              ],
              "title": "Creating a Random Distribution"
            },
            {
              "anchor": "Creating-Specific-Random-Distributions",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d6()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/d20()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/init(forDieWithSideCount:)"
              ],
              "title": "Creating Specific Random Distributions"
            },
            {
              "anchor": "Generating-Random-Numbers",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextInt(upperBound:)",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextUniform()",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/nextBool()"
              ],
              "title": "Generating Random Numbers"
            },
            {
              "anchor": "Working-with-Characteristics-of-a-Distribution",
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/lowestValue",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/highestValue",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomDistribution/numberOfPossibleOutcomes"
              ],
              "title": "Working with Characteristics of a Distribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Randomization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandom",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKRandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKARC4RandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKLinearCongruentialRandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKMersenneTwisterRandomSource",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKGaussianDistribution",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKShuffledDistribution"
              ],
              "title": "Randomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKRandomDistribution"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1init(randomSource:lowestValue:highestValue:)/title",
          "value": "initWithRandomSource:lowestValue:highestValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1init(randomSource:lowestValue:highestValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRandomSource:lowestValue:highestValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextInt(upperBound:)/title",
          "value": "nextIntWithUpperBound:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextInt(upperBound:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nextIntWithUpperBound:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1init(forDieWithSideCount:)/title",
          "value": "distributionForDieWithSideCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1init(forDieWithSideCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "distributionForDieWithSideCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution/title",
          "value": "GKGaussianDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKGaussianDistribution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGaussianDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKLinearCongruentialRandomSource/title",
          "value": "GKLinearCongruentialRandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKLinearCongruentialRandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLinearCongruentialRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKLinearCongruentialRandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLinearCongruentialRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1d20()/title",
          "value": "d20"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1d20()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "d20"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1numberOfPossibleOutcomes/title",
          "value": "numberOfPossibleOutcomes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1numberOfPossibleOutcomes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfPossibleOutcomes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKARC4RandomSource/title",
          "value": "GKARC4RandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKARC4RandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKARC4RandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKARC4RandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKARC4RandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextInt()/title",
          "value": "nextInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextInt()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nextInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution/title",
          "value": "GKRandomDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandom/title",
          "value": "GKRandom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandom/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomSource/title",
          "value": "GKRandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1d6()/title",
          "value": "d6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1d6()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "d6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextBool()/title",
          "value": "nextBool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextBool()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nextBool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1highestValue/title",
          "value": "highestValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1highestValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highestValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1lowestValue/title",
          "value": "lowestValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1lowestValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowestValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKShuffledDistribution/title",
          "value": "GKShuffledDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKShuffledDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKShuffledDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKShuffledDistribution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKShuffledDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextUniform()/title",
          "value": "nextUniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1nextUniform()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nextUniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1init(lowestValue:highestValue:)/title",
          "value": "distributionWithLowestValue:highestValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKRandomDistribution~1init(lowestValue:highestValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "distributionWithLowestValue:highestValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMersenneTwisterRandomSource/title",
          "value": "GKMersenneTwisterRandomSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMersenneTwisterRandomSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMersenneTwisterRandomSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKMersenneTwisterRandomSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMersenneTwisterRandomSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gkrandomdistribution"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gkrandomdistribution"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
