{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDraggingItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDraggingItem","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem"},{"text":".","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey","preciseIdentifier":"c:@T@NSDraggingImageComponentKey","kind":"typeIdentifier","text":"ImageComponentKey"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"NSDraggingImageComponentLabelKey","kind":"identifier"}],"extendedModule":"AppKit","roleHeading":"Type Property","title":"label","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDraggingItem","preciseIdentifier":"c:objc(cs)NSDraggingItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ImageComponentKey","preciseIdentifier":"c:@T@NSDraggingImageComponentKey","kind":"typeIdentifier"}],"role":"symbol","platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.7"}],"externalID":"c:@NSDraggingImageComponentLabelKey","symbolKind":"property"},"kind":"symbol","abstract":[{"text":"A key for a corresponding value that represents a textual label for a dragging item, for example, a file name.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingItem","doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey"]]},"variants":[{"paths":["/documentation/appkit/nsdraggingitem/imagecomponentkey/label"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdraggingitem/imagecomponentkey/label"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/icon"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/label"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageComponentKey","kind":"identifier"}],"kind":"symbol","title":"NSDraggingItem.ImageComponentKey","navigatorTitle":[{"text":"ImageComponentKey","kind":"identifier"}],"abstract":[{"text":"Keys that identify components of a dragging image.","type":"text"}],"url":"/documentation/appkit/nsdraggingitem/imagecomponentkey","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem":{"url":"/documentation/appkit/nsdraggingitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSDraggingItem"}],"title":"NSDraggingItem","kind":"symbol","abstract":[{"text":"A single dragged item within a dragging session.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSDraggingItem"}]},"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/label":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"text":"NSDraggingItem","preciseIdentifier":"c:objc(cs)NSDraggingItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSDraggingImageComponentKey","text":"ImageComponentKey","kind":"typeIdentifier"}],"kind":"symbol","title":"label","navigatorTitle":[{"text":"NSDraggingImageComponentLabelKey","kind":"identifier"}],"abstract":[{"text":"A key for a corresponding value that represents a textual label for a dragging item, for example, a file name.","type":"text"}],"url":"/documentation/appkit/nsdraggingitem/imagecomponentkey/label","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/label"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/icon":{"role":"symbol","title":"icon","navigatorTitle":[{"text":"NSDraggingImageComponentIconKey","kind":"identifier"}],"abstract":[{"type":"text","text":"A key for a corresponding value that is a dragging item’s image."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDraggingItem","preciseIdentifier":"c:objc(cs)NSDraggingItem","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ImageComponentKey","preciseIdentifier":"c:@T@NSDraggingImageComponentKey","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/icon","type":"topic","url":"/documentation/appkit/nsdraggingitem/imagecomponentkey/icon"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.7"}],"path":"/metadata/platforms","op":"replace"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"NSDraggingImageComponentLabelKey","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"NSDraggingImageComponentLabelKey"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey/icon"],"title":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingItem/ImageComponentKey","preciseIdentifier":"c:@T@NSDraggingImageComponentKey","text":"NSDraggingImageComponentKey","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDraggingImageComponentLabelKey","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey/title","op":"replace","value":"NSDraggingImageComponentKey"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDraggingImageComponentKey"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey/navigatorTitle","op":"replace","value":[{"text":"NSDraggingImageComponentKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/title","op":"replace","value":"NSDraggingItem"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDraggingItem"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem/navigatorTitle","op":"replace","value":[{"text":"NSDraggingItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey~1label/title","op":"replace","value":"NSDraggingImageComponentLabelKey"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey~1label/fragments","op":"replace","value":[{"text":"NSDraggingImageComponentLabelKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey~1icon/title","op":"replace","value":"NSDraggingImageComponentIconKey"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingItem~1ImageComponentKey~1icon/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDraggingImageComponentIconKey"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}