{"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusItem/canBecomeFocused"],"title":"Determining focusability","generated":true,"anchor":"Determining-focusability"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFocused","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the item is currently focused."}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusItem"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIFocusItem/isFocused","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","platforms":[{"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"11.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"11.0","deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFocused"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"UIKit"}],"role":"symbol","title":"isFocused","externalID":"s:So11UIFocusItemP5UIKitE9isFocusedSbvp","extendedModule":"UIKit","symbolKind":"property"},"variants":[{"paths":["/documentation/uikit/uifocusitem/isfocused"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIFocusItem":{"abstract":[{"text":"An object that can become focused.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusItem","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItem","type":"topic","title":"UIFocusItem","kind":"symbol","role":"symbol","url":"/documentation/uikit/uifocusitem","navigatorTitle":[{"text":"UIFocusItem","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusItem/isFocused":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItem/isFocused","role":"symbol","title":"isFocused","url":"/documentation/uikit/uifocusitem/isfocused","abstract":[{"text":"A Boolean value that indicates whether the item is currently focused.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFocused"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusItem/canBecomeFocused":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItem/canBecomeFocused","role":"symbol","title":"canBecomeFocused","required":true,"url":"/documentation/uikit/uifocusitem/canbecomefocused","abstract":[{"text":"A Boolean value that indicates whether the item can become focused.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeFocused"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"text":"canBecomeFocused","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/title","op":"replace","value":"UIFocusItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/fragments","op":"replace","value":[{"text":"UIFocusItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIFocusItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem~1canBecomeFocused/title","op":"replace","value":"canBecomeFocused"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem~1canBecomeFocused/fragments","op":"replace","value":[{"kind":"identifier","text":"canBecomeFocused"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}