{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting"]]},"metadata":{"role":"symbol","externalID":"c:objc(pl)NSPasteboardWriting(im)pasteboardPropertyListForType:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"pasteboardPropertyListForType:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pasteboardPropertyList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"title":"pasteboardPropertyList(forType:)","modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/pasteboardPropertyList(forType:)"},"variants":[{"paths":["/documentation/appkit/nspasteboardwriting/pasteboardpropertylist(fortype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nspasteboardwriting/pasteboardpropertylist(fortype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pasteboardPropertyList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"One of the types the receiver supports for writing (one of the UTIs returned by its implementation of "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/writableTypes(for:)"},{"type":"text","text":")."}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A property list object to represent the receiver on a pasteboard as an object of type "},{"type":"codeVoice","code":"type"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The returned value will commonly be the ","type":"text"},{"code":"NSData","type":"codeVoice"},{"text":" object for the specified data type. However, if this method returns either a string, or any other property-list type, the pasteboard will automatically convert these items to the correct data format required for the pasteboard.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Returns a property list object to represent the receiver on a pasteboard as an object of a specified type."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType":{"abstract":[{"text":"The supported pasteboard types.","type":"text"}],"navigatorTitle":[{"text":"PasteboardType","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","url":"/documentation/appkit/nspasteboard/pasteboardtype","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PasteboardType","kind":"identifier"}],"role":"symbol","title":"NSPasteboard.PasteboardType"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard":{"url":"/documentation/appkit/nspasteboard","title":"NSPasteboard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSPasteboard"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSPasteboard","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","abstract":[{"text":"An object that transfers data to and from the pasteboard server.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSPasteboardWriting","kind":"identifier"}],"title":"NSPasteboardWriting","url":"/documentation/appkit/nspasteboardwriting","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting","type":"topic","abstract":[{"type":"text","text":"A set of methods that defines the interface for retrieving a representation of an object that can be written to a pasteboard."}],"kind":"symbol","navigatorTitle":[{"text":"NSPasteboardWriting","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/writableTypes(for:)":{"title":"writableTypes(for:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writableTypes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard"},{"text":") -> [","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Returns an array of UTI strings of data types the receiver can write to a given pasteboard."}],"url":"/documentation/appkit/nspasteboardwriting/writabletypes(for:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"writableTypesForPasteboard:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/writableTypes(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/pasteboardPropertyList(forType:)":{"navigatorTitle":[{"text":"pasteboardPropertyListForType:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pasteboardPropertyList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"PasteboardType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"required":true,"url":"/documentation/appkit/nspasteboardwriting/pasteboardpropertylist(fortype:)","title":"pasteboardPropertyList(forType:)","abstract":[{"type":"text","text":"Returns a property list object to represent the receiver on a pasteboard as an object of a specified type."}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/pasteboardPropertyList(forType:)","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"pasteboardPropertyListForType:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pasteboardPropertyListForType:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"pasteboardPropertyListForType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSPasteboardType","text":"NSPasteboardType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"One of the types the receiver supports for writing (one of the UTIs returned by its implementation of "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboardWriting/writableTypes(for:)","isActive":true},{"type":"text","text":")."}]}]}]}},{"value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A property list object to represent the receiver on a pasteboard as an object of type "},{"type":"codeVoice","code":"type"},{"type":"text","text":"."}]}]},"path":"/primaryContentSections/2","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/title","op":"replace","value":"NSPasteboardType"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardType"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/navigatorTitle","op":"replace","value":[{"text":"NSPasteboardType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title","op":"replace","value":"NSPasteboard"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments","op":"replace","value":[{"text":"NSPasteboard","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSPasteboard"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting/title","op":"replace","value":"NSPasteboardWriting"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardWriting"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSPasteboardWriting"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting~1writableTypes(for:)/title","op":"replace","value":"writableTypesForPasteboard:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting~1writableTypes(for:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writableTypesForPasteboard:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting~1pasteboardPropertyList(forType:)/title","op":"replace","value":"pasteboardPropertyListForType:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboardWriting~1pasteboardPropertyList(forType:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pasteboardPropertyListForType:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}