{
  "abstract": [
    {
      "text": "Returns an identity authority for use with the Core Services Identity API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/CSIdentityAuthority"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBIdentityAuthority(py)CSIdentityAuthority",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CSIdentityAuthority"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CSIdentityAuthority"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "CSIdentityAuthority"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CSIdentityAuthorityRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSIdentityAuthorityRef",
              "text": "CSIdentityAuthorityRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSIdentityAuthority"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The opaque authority object for use with the Core Services Identity API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method, along with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", is used for interoperability with the Core Services Identity API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority": {
      "abstract": [
        {
          "text": "An identity authority is a database that stores information about identities. The ",
          "type": "text"
        },
        {
          "code": "CBIdentityAuthority",
          "type": "codeVoice"
        },
        {
          "text": " class defines one or more identity authorities. You can search this database for identities in conjunction with the ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class factory methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "CBIdentityAuthority",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/CSIdentityAuthority": {
      "abstract": [
        {
          "text": "Returns an identity authority for use with the Core Services Identity API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/CSIdentityAuthority",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSIdentityAuthority",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/csidentityauthority"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:": {
      "abstract": [
        {
          "text": "Returns an identity authority specified by a given Core Services Identity authority object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "identityAuthorityWithCSIdentityAuthority:"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identityAuthorityWithCSIdentityAuthority:"
        }
      ],
      "role": "symbol",
      "title": "identityAuthorityWithCSIdentityAuthority:",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority/identityauthoritywithcsidentityauthority:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CSIdentityAuthorityRef": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CSIdentityAuthority"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CSIdentityAuthorityRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSIdentityAuthority",
      "type": "topic",
      "url": "/documentation/coreservices/csidentityauthority"
    },
    "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490",
      "title": "Identity Services Programming Guide",
      "titleInlineContent": [
        {
          "text": "Identity Services Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Interacting-with-the-Core-Services-Identity-API",
      "generated": true,
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority/identityAuthorityWithCSIdentityAuthority:"
      ],
      "title": "Interacting with the Core Services Identity API"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/title",
          "value": "CBIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CSIdentityAuthorityRef/title",
          "value": "CSIdentityAuthorityRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbidentityauthority/csidentityauthority"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
