{
  "abstract": [
    {
      "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8PhotosUI21PHPickerConfigurationV6UpdateV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Update"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Update"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "PHPickerConfiguration.Update"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Update"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While a photos picker is visible, you can use an instance of this structure to change its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. To do that, create and configure an instance of this object and pass it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/updatePicker(using:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities": {
      "abstract": [
        {
          "text": "Options that customize the look and behavior of the photos picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerCapabilities"
        }
      ],
      "role": "symbol",
      "title": "PHPickerCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickercapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "An object that contains information about how to configure a picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update": {
      "abstract": [
        {
          "text": "An object that defines the aspects of a photo picker’s appearance that can change while it’s presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Update"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Update"
        }
      ],
      "role": "symbol",
      "title": "PHPickerConfiguration.Update",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/update"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s permiter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDirectionalRectEdge",
          "text": "NSDirectionalRectEdge"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/update/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/update/init()"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/selectionLimit": {
      "abstract": [
        {
          "text": "The maximum number of selections the user can make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/selectionLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionLimit",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/update/selectionlimit"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/disabledCapabilities": {
      "abstract": [
        {
          "text": "The aspects of a photo picker’s default appearance that your app can disable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabledCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPickerCapabilities",
          "text": "PHPickerCapabilities"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/disabledCapabilities",
      "kind": "symbol",
      "role": "symbol",
      "title": "disabledCapabilities",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/disabledcapabilities"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins": {
      "abstract": [
        {
          "text": "The portions of a photo picker’s perimeter that are borderless.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgesWithoutContentMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDirectionalRectEdge",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesWithoutContentMargins",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/edgeswithoutcontentmargins"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/mode": {
      "abstract": [
        {
          "text": "A layout type for the photos in the picker’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI12PHPickerModeV",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/mode",
      "kind": "symbol",
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/mode"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit": {
      "abstract": [
        {
          "text": "The maximum number of selections the user can make.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/selectionLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionLimit",
      "type": "topic",
      "url": "/documentation/photosui/phpickerconfiguration-swift.struct/selectionlimit"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-swift.struct": {
      "abstract": [
        {
          "text": "Layout options that determine how the picker orders photos visually.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerMode"
        }
      ],
      "role": "symbol",
      "title": "PHPickerMode",
      "type": "topic",
      "url": "/documentation/photosui/phpickermode-swift.struct"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides the user interface for choosing assets from the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "PHPickerViewController",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/updatePicker(using:)": {
      "abstract": [
        {
          "text": "Customizes your app’s photo picker according to the given configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatePicker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI21PHPickerConfigurationV",
          "text": "PHPickerConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8PhotosUI21PHPickerConfigurationV6UpdateV",
          "text": "Update"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHPickerViewController/updatePicker(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updatePicker(using:)",
      "type": "topic",
      "url": "/documentation/photosui/phpickerviewcontroller/updatepicker(using:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-picker-appearance-and-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/mode",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerMode-swift.struct",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/disabledCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerCapabilities",
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/edgesWithoutContentMargins"
      ],
      "title": "Customizing picker appearance and behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-update-object",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/init()"
      ],
      "title": "Creating an update object"
    },
    {
      "anchor": "Adjusting-selection-limits",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/selectionLimit"
      ],
      "title": "Adjusting selection limits"
    },
    {
      "anchor": "Adjusting-content-margins",
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHPickerConfiguration-swift.struct/Update/edgesWithoutContentMargins"
      ],
      "title": "Adjusting content margins"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/title",
          "value": "PHPickerCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/title",
          "value": "PHPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phpickerconfiguration-swift.struct/update"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
