{
  "abstract": [
    {
      "text": "The context that holds all RealityKit entities.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/ecs-scenes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Scenes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system adds an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Scene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when you add it to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/RealityView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/RealityViewCameraContent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/RealityViewContent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "These scenes contain anchors and a hierarchy of entities that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "make up your RealityKit content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Scene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance has helpful methods to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "perform ray casts to help you better understand your scene,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and methods that find entities either by name or by components they own.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct": {
      "abstract": [
        {
          "text": "An object that holds scene-understanding options for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneUnderstanding"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneUnderstanding"
        }
      ],
      "role": "symbol",
      "title": "ARView.Environment.SceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/arview/environment-swift.struct/sceneunderstanding-swift.struct"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct": {
      "abstract": [
        {
          "text": "Available scene-understanding options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "ARView.Environment.SceneUnderstanding.Options",
      "type": "topic",
      "url": "/documentation/realitykit/arview/environment-swift.struct/sceneunderstanding-swift.struct/options-swift.struct"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity": {
      "abstract": [
        {
          "text": "An element of a RealityKit scene to which you attach components that provide",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "appearance and behavior characteristics for the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Entity"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entity"
        }
      ],
      "role": "symbol",
      "title": "Entity",
      "type": "topic",
      "url": "/documentation/realitykit/entity"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding": {
      "abstract": [
        {
          "text": "A specification that detects and reacts to features of the physical",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HasSceneUnderstanding"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HasSceneUnderstanding"
        }
      ],
      "role": "symbol",
      "title": "HasSceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/hassceneunderstanding"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PixelCastHit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PixelCastHit"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PixelCastHit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PixelCastHit"
        }
      ],
      "role": "symbol",
      "title": "PixelCastHit",
      "type": "topic",
      "url": "/documentation/realitykit/pixelcasthit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/QueryPredicate": {
      "abstract": [
        {
          "text": "An object that defines the criteria for an entity query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QueryPredicate"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/QueryPredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QueryPredicate"
        }
      ],
      "role": "symbol",
      "title": "QueryPredicate",
      "type": "topic",
      "url": "/documentation/realitykit/querypredicate"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/RealityView": {
      "abstract": [
        {
          "text": "A view that contains RealityKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RealityView"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/RealityView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RealityView"
        }
      ],
      "role": "symbol",
      "title": "RealityView",
      "type": "topic",
      "url": "/documentation/realitykit/realityview"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/RealityViewCameraContent": {
      "abstract": [
        {
          "text": "The content of a reality view that is displayed through a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RealityViewCameraContent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/RealityViewCameraContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RealityViewCameraContent"
        }
      ],
      "role": "symbol",
      "title": "RealityViewCameraContent",
      "type": "topic",
      "url": "/documentation/realitykit/realityviewcameracontent"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/RealityViewContent": {
      "abstract": [
        {
          "text": "The content of a visionOS reality view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RealityViewContent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/RealityViewContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RealityViewContent"
        }
      ],
      "role": "symbol",
      "title": "RealityViewContent",
      "type": "topic",
      "url": "/documentation/realitykit/realityviewcontent"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Scene": {
      "abstract": [
        {
          "text": "A container that holds the collection of entities that an AR view renders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Scene"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Scene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Scene"
        }
      ],
      "role": "symbol",
      "title": "Scene",
      "type": "topic",
      "url": "/documentation/realitykit/scene"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Scene/AnchorCollection": {
      "abstract": [
        {
          "text": "A collection of anchor entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnchorCollection"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Scene/AnchorCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnchorCollection"
        }
      ],
      "role": "symbol",
      "title": "Scene.AnchorCollection",
      "type": "topic",
      "url": "/documentation/realitykit/scene/anchorcollection"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Scene/ID-swift.typealias": {
      "abstract": [
        {
          "text": "A type representing the stable identity of the entity associated with",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "an instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Scene/ID-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "Scene.ID",
      "type": "topic",
      "url": "/documentation/realitykit/scene/id-swift.typealias"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Scene/Publisher": {
      "abstract": [
        {
          "text": "A publisher for the given event type in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Publisher"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Scene/Publisher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Publisher"
        }
      ],
      "role": "symbol",
      "title": "Scene.Publisher",
      "type": "topic",
      "url": "/documentation/realitykit/scene/publisher"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneEvents": {
      "abstract": [
        {
          "text": "Events the scene invokes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneEvents"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneEvents"
        }
      ],
      "role": "symbol",
      "title": "SceneEvents",
      "type": "topic",
      "url": "/documentation/realitykit/sceneevents"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent": {
      "abstract": [
        {
          "text": "A component that specifies an entity is participating in the system’s scene-understanding features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "role": "symbol",
      "title": "SceneUnderstandingComponent",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ecs-entity-actions": {
      "abstract": [
        {
          "text": "Create simple, reusable actions that can change your app state, RealityKit scene, or animate an entity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ecs-entity-actions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Entity actions",
      "type": "topic",
      "url": "/documentation/realitykit/ecs-entity-actions"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ecs-events": {
      "abstract": [
        {
          "text": "Respond to things happening in your RealityKit scene by subscribing to specific event types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ecs-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Events",
      "type": "topic",
      "url": "/documentation/realitykit/ecs-events"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ecs-systems": {
      "abstract": [
        {
          "text": "Apply behaviors and physical effects to the entities in a RealityKit scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ecs-systems",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Systems",
      "type": "topic",
      "url": "/documentation/realitykit/ecs-systems"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding": {
      "abstract": [
        {
          "text": "Detect objects in an AR scene or create a detailed 3D reconstruction of the real-world environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
      "kind": "article",
      "role": "article",
      "title": "Implementing scene understanding and reconstruction in your RealityKit app",
      "type": "topic",
      "url": "/documentation/realitykit/realitykit-scene-understanding"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction": {
      "abstract": [
        {
          "text": "A flag that enables scene reconstruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneReconstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction",
      "kind": "symbol",
      "role": "symbol",
      "title": "sceneReconstruction",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)": {
      "abstract": [
        {
          "text": "Checks if the device supports scene reconstruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsSceneReconstruction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "sceneReconstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsSceneReconstruction(_:)",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)"
    },
    "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider": {
      "abstract": [
        {
          "text": "A source of live data about the shape of a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneReconstructionProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "SceneReconstructionProvider",
      "type": "topic",
      "url": "/documentation/ARKit/SceneReconstructionProvider"
    },
    "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene": {
      "abstract": [
        {
          "text": "Estimate the shape of the physical environment using a polygonal mesh.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing and interacting with a reconstructed scene",
      "type": "topic",
      "url": "/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene"
    },
    "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding": {
      "abstract": [
        {
          "text": "Create AR games and experiences that interact with real-world objects on LiDAR-equipped iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a game with scene understanding",
      "type": "topic",
      "url": "/documentation/realitykit/creating_a_game_with_scene_understanding"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scene-management-and-logic",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/ecs-systems",
        "doc://com.apple.RealityKit/documentation/RealityKit/ecs-events",
        "doc://com.apple.RealityKit/documentation/RealityKit/ecs-entity-actions"
      ],
      "title": "Scene management and logic"
    }
  ],
  "topicSections": [
    {
      "anchor": "Scene-management",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/Scene",
        "doc://com.apple.RealityKit/documentation/RealityKit/Scene/AnchorCollection",
        "doc://com.apple.RealityKit/documentation/RealityKit/Scene/ID-swift.typealias"
      ],
      "title": "Scene management"
    },
    {
      "anchor": "Entity-searches",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/QueryPredicate",
        "doc://com.apple.RealityKit/documentation/RealityKit/PixelCastHit"
      ],
      "title": "Entity searches"
    },
    {
      "anchor": "Event-publishers-and-subscription",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneEvents",
        "doc://com.apple.RealityKit/documentation/RealityKit/Scene/Publisher"
      ],
      "title": "Event publishers and subscription"
    },
    {
      "anchor": "Scene-reconstructions-and-analysis",
      "identifiers": [
        "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
        "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
        "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
        "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction",
        "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent",
        "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct",
        "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct",
        "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding",
        "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider",
        "doc://com.apple.documentation/documentation/ARKit/ARSession"
      ],
      "title": "Scene reconstructions and analysis"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1supportsSceneReconstruction(_:)/title",
          "value": "supportsSceneReconstruction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1supportsSceneReconstruction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "supportsSceneReconstruction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARSceneReconstruction",
              "text": "ARSceneReconstruction"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "sceneReconstruction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1sceneReconstruction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARSceneReconstruction",
              "text": "ARSceneReconstruction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sceneReconstruction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/ecs-scenes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
