{
  "abstract": [
    {
      "text": "A specification that detects and reacts to features of the physical",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17RealityFoundation21HasSceneUnderstandingP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HasSceneUnderstanding"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HasSceneUnderstanding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "HasSceneUnderstanding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HasSceneUnderstanding"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:17RealityFoundation6EntityC",
              "text": "Entity"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct": {
      "abstract": [
        {
          "text": "An object that holds scene-understanding options for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneUnderstanding"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneUnderstanding"
        }
      ],
      "role": "symbol",
      "title": "ARView.Environment.SceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/arview/environment-swift.struct/sceneunderstanding-swift.struct"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct": {
      "abstract": [
        {
          "text": "Available scene-understanding options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "ARView.Environment.SceneUnderstanding.Options",
      "type": "topic",
      "url": "/documentation/realitykit/arview/environment-swift.struct/sceneunderstanding-swift.struct/options-swift.struct"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Entity": {
      "abstract": [
        {
          "text": "An element of a RealityKit scene to which you attach components that provide",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "appearance and behavior characteristics for the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Entity"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Entity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entity"
        }
      ],
      "role": "symbol",
      "title": "Entity",
      "type": "topic",
      "url": "/documentation/realitykit/entity"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding": {
      "abstract": [
        {
          "text": "A specification that detects and reacts to features of the physical",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HasSceneUnderstanding"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HasSceneUnderstanding"
        }
      ],
      "role": "symbol",
      "title": "HasSceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/hassceneunderstanding"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding/sceneUnderstanding": {
      "abstract": [
        {
          "text": "An entity component that detects and reacts to features of the physical",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneUnderstanding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentV",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding/sceneUnderstanding",
      "kind": "symbol",
      "role": "symbol",
      "title": "sceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/hassceneunderstanding/sceneunderstanding"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent": {
      "abstract": [
        {
          "text": "A component that specifies an entity is participating in the system’s scene-understanding features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "role": "symbol",
      "title": "SceneUnderstandingComponent",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding": {
      "abstract": [
        {
          "text": "Detect objects in an AR scene or create a detailed 3D reconstruction of the real-world environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
      "kind": "article",
      "role": "article",
      "title": "Implementing scene understanding and reconstruction in your RealityKit app",
      "type": "topic",
      "url": "/documentation/realitykit/realitykit-scene-understanding"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction": {
      "abstract": [
        {
          "text": "A flag that enables scene reconstruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneReconstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction",
      "kind": "symbol",
      "role": "symbol",
      "title": "sceneReconstruction",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)": {
      "abstract": [
        {
          "text": "Checks if the device supports scene reconstruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsSceneReconstruction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "sceneReconstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsSceneReconstruction(_:)",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)"
    },
    "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider": {
      "abstract": [
        {
          "text": "A source of live data about the shape of a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneReconstructionProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "SceneReconstructionProvider",
      "type": "topic",
      "url": "/documentation/ARKit/SceneReconstructionProvider"
    },
    "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene": {
      "abstract": [
        {
          "text": "Estimate the shape of the physical environment using a polygonal mesh.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing and interacting with a reconstructed scene",
      "type": "topic",
      "url": "/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene"
    },
    "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding": {
      "abstract": [
        {
          "text": "Create AR games and experiences that interact with real-world objects on LiDAR-equipped iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a game with scene understanding",
      "type": "topic",
      "url": "/documentation/realitykit/creating_a_game_with_scene_understanding"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/Entity"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scene-reconstructions-and-analysis",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
        "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
        "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
        "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction",
        "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent",
        "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct",
        "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct",
        "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider",
        "doc://com.apple.documentation/documentation/ARKit/ARSession"
      ],
      "title": "Scene reconstructions and analysis"
    }
  ],
  "topicSections": [
    {
      "anchor": "Understanding-the-scene",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding/sceneUnderstanding"
      ],
      "title": "Understanding the scene"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1sceneReconstruction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARSceneReconstruction",
              "text": "ARSceneReconstruction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sceneReconstruction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1supportsSceneReconstruction(_:)/title",
          "value": "supportsSceneReconstruction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1supportsSceneReconstruction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "supportsSceneReconstruction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARSceneReconstruction",
              "text": "ARSceneReconstruction"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "sceneReconstruction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/hassceneunderstanding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
