{
  "abstract": [
    {
      "text": "An opaque token used to check the networking compatibility between two peers",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "in a multipeer connection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17RealityFoundation25NetworkCompatibilityTokenC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NetworkCompatibilityToken"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NetworkCompatibilityToken"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NetworkCompatibilityToken"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NetworkCompatibilityToken"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " apps running on incompatible versions of RealityKit can’t",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "connect and sync over the network. Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "check if two peers can synchronize ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " scenes over the network.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "With this class, host applications can prevent incompatible clients from",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "joining.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Client apps send a copy of their token to the host when attempting to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "connect to a host app. The host deserializes that token and calls",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/compatibilityWith(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/local",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/compatibilityWith(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility/compatible",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the client and host can sync and it’s safe to proceed with the connection.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/compatibilityWith(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns any other",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "value, the client that’s attempting to connect is incompatible and should be",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "ignored.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A client running a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for example, writes its own token into its",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser/discoveryInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "dictionary. When the host (running a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceBrowser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ")",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "discovers that client, it deserializes the client’s token from the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "discoverInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary and uses it to check compatibility before inviting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the client to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Even if two peers are compatible, scene synchronization can fail for",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "other reasons, such as packet corruption or a poor network connection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/MultipeerConnectivityService": {
      "abstract": [
        {
          "text": "A service that provides scene synchronization among all peers in a multipeer",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "connectivity session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MultipeerConnectivityService"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/MultipeerConnectivityService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MultipeerConnectivityService"
        }
      ],
      "role": "symbol",
      "title": "MultipeerConnectivityService",
      "type": "topic",
      "url": "/documentation/realitykit/multipeerconnectivityservice"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken": {
      "abstract": [
        {
          "text": "An opaque token used to check the networking compatibility between two peers",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in a multipeer connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NetworkCompatibilityToken"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NetworkCompatibilityToken"
        }
      ],
      "role": "symbol",
      "title": "NetworkCompatibilityToken",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility": {
      "abstract": [
        {
          "text": "Indicates whether two devices running RealityKit are compatible and able",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to connect and sync scenes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Compatibility"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Compatibility"
        }
      ],
      "role": "symbol",
      "title": "NetworkCompatibilityToken.Compatibility",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken/compatibility"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility/compatible": {
      "abstract": [
        {
          "text": "An indication that the compared devices are running compatible",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "versions of RealityKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compatible"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility/compatible",
      "kind": "symbol",
      "role": "symbol",
      "title": "NetworkCompatibilityToken.Compatibility.compatible",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken/compatibility/compatible"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/compatibilityWith(_:)": {
      "abstract": [
        {
          "text": "Compares network compatibility tokens between the local device and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "another device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compatibilityWith"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation25NetworkCompatibilityTokenC",
          "text": "NetworkCompatibilityToken"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation25NetworkCompatibilityTokenC",
          "text": "NetworkCompatibilityToken"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation25NetworkCompatibilityTokenC0D0O",
          "text": "Compatibility"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/compatibilityWith(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "compatibilityWith(_:)",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken/compatibilitywith(_:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/encode(to:)": {
      "abstract": [
        {
          "text": "Writes the token’s data into an encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7EncoderP",
          "text": "Encoder"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/encode(to:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "encode(to:)",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken/encode(to:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/init(from:)": {
      "abstract": [
        {
          "text": "Creates a new instance from a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7DecoderP",
          "text": "Decoder"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/init(from:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(from:)",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken/init(from:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/local": {
      "abstract": [
        {
          "text": "A token containing the local peer’s networking compatibility info.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "local"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation25NetworkCompatibilityTokenC",
          "text": "NetworkCompatibilityToken"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/local",
      "kind": "symbol",
      "role": "symbol",
      "title": "local",
      "type": "topic",
      "url": "/documentation/realitykit/networkcompatibilitytoken/local"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TransientComponent": {
      "abstract": [
        {
          "text": "An interface for components that aren’t saved to file or cloned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransientComponent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TransientComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TransientComponent"
        }
      ],
      "role": "symbol",
      "title": "TransientComponent",
      "type": "topic",
      "url": "/documentation/realitykit/transientcomponent"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/loading-remote-assets": {
      "abstract": [
        {
          "text": "Ensure assets load on all connected peers before using them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/loading-remote-assets",
      "kind": "article",
      "role": "article",
      "title": "Loading remote assets in multiplayer apps",
      "type": "topic",
      "url": "/documentation/realitykit/loading-remote-assets"
    },
    "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser": {
      "abstract": [
        {
          "text": "The `MCNearbyServiceAdvertiser` class publishes an advertisement for a specific service that your app provides through the Multipeer Connectivity framework and notifies its delegate about invitations from nearby peers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCNearbyServiceAdvertiser"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser",
      "kind": "symbol",
      "role": "symbol",
      "title": "MCNearbyServiceAdvertiser",
      "type": "topic",
      "url": "/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser"
    },
    "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser/discoveryInfo": {
      "abstract": [
        {
          "text": "The `info` dictionary passed when this object was initialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discoveryInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser/discoveryInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "discoveryInfo",
      "type": "topic",
      "url": "/documentation/MultipeerConnectivity/MCNearbyServiceAdvertiser/discoveryInfo"
    },
    "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceBrowser": {
      "abstract": [
        {
          "text": "Searches (by service type) for services offered by nearby devices using infrastructure Wi-Fi, peer-to-peer Wi-Fi, and Bluetooth (in iOS) or Ethernet (in macOS and tvOS), and provides the ability to easily invite those devices to a Multipeer Connectivity session (`MCSession`).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCNearbyServiceBrowser"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCNearbyServiceBrowser",
      "kind": "symbol",
      "role": "symbol",
      "title": "MCNearbyServiceBrowser",
      "type": "topic",
      "url": "/documentation/MultipeerConnectivity/MCNearbyServiceBrowser"
    },
    "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCSession": {
      "abstract": [
        {
          "text": "An `MCSession` object enables and manages communication among all peers in a Multipeer Connectivity session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity/MCSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "MCSession",
      "type": "topic",
      "url": "/documentation/MultipeerConnectivity/MCSession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SE": {
      "abstract": [
        {
          "text": "A type that can encode itself to an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Encodable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SE",
      "kind": "symbol",
      "role": "symbol",
      "title": "Encodable",
      "type": "topic",
      "url": "/documentation/Swift/Encodable"
    },
    "doc://com.externally.resolved.symbol/s:Se": {
      "abstract": [
        {
          "text": "A type that can decode itself from an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Decodable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Se",
      "kind": "symbol",
      "role": "symbol",
      "title": "Decodable",
      "type": "topic",
      "url": "/documentation/Swift/Decodable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:Se",
        "doc://com.externally.resolved.symbol/s:SE"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multipeer-synchronization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/loading-remote-assets",
        "doc://com.apple.RealityKit/documentation/RealityKit/MultipeerConnectivityService",
        "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility",
        "doc://com.apple.RealityKit/documentation/RealityKit/TransientComponent"
      ],
      "title": "Multipeer synchronization"
    }
  ],
  "topicSections": [
    {
      "anchor": "Retrieving-tokens",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/local"
      ],
      "title": "Retrieving tokens"
    },
    {
      "anchor": "Checking-compatibility",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/compatibilityWith(_:)"
      ],
      "title": "Checking compatibility"
    },
    {
      "anchor": "Serializing-tokens",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/init(from:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/encode(to:)"
      ],
      "title": "Serializing tokens"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/NetworkCompatibilityToken/Compatibility"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MultipeerConnectivity~1MCNearbyServiceBrowser/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MCNearbyServiceBrowser"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MultipeerConnectivity~1MCSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MCSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MultipeerConnectivity~1MCNearbyServiceAdvertiser~1discoveryInfo/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,NSString *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "discoveryInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MultipeerConnectivity~1MCNearbyServiceAdvertiser/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MCNearbyServiceAdvertiser"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/networkcompatibilitytoken"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
