{
  "abstract": [
    {
      "text": "A component that specifies an entity is participating in the system’s scene-understanding features.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17RealityFoundation27SceneUnderstandingComponentV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SceneUnderstandingComponent"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SceneUnderstandingComponent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SceneUnderstandingComponent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SceneUnderstandingComponent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Scene understanding refers to RealityKit features like physics collision, shadows, and occlusion with real-world geometry.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In iOS, ",
              "type": "text"
            },
            {
              "code": "SceneUnderstandingComponent",
              "type": "codeVoice"
            },
            {
              "text": " is a read-only component. Manually adding",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it doesn’t have any effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In visionOS, ",
              "type": "text"
            },
            {
              "code": "SceneUnderstandingComponent",
              "type": "codeVoice"
            },
            {
              "text": " is a write-only component.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Add ",
              "type": "text"
            },
            {
              "code": "SceneUnderstandingComponent",
              "type": "codeVoice"
            },
            {
              "text": " to your custom entities to let it behave",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as a virtual scene-understanding mesh.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about scene-understanding features, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct": {
      "abstract": [
        {
          "text": "An object that holds scene-understanding options for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneUnderstanding"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneUnderstanding"
        }
      ],
      "role": "symbol",
      "title": "ARView.Environment.SceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/arview/environment-swift.struct/sceneunderstanding-swift.struct"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct": {
      "abstract": [
        {
          "text": "Available scene-understanding options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "ARView.Environment.SceneUnderstanding.Options",
      "type": "topic",
      "url": "/documentation/realitykit/arview/environment-swift.struct/sceneunderstanding-swift.struct/options-swift.struct"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Component": {
      "abstract": [
        {
          "text": "A representation of a geometry or a behavior that you apply to an entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Component",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "role": "symbol",
      "title": "Component",
      "type": "topic",
      "url": "/documentation/realitykit/component"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding": {
      "abstract": [
        {
          "text": "A specification that detects and reacts to features of the physical",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HasSceneUnderstanding"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HasSceneUnderstanding"
        }
      ],
      "role": "symbol",
      "title": "HasSceneUnderstanding",
      "type": "topic",
      "url": "/documentation/realitykit/hassceneunderstanding"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent": {
      "abstract": [
        {
          "text": "A component that specifies an entity is participating in the system’s scene-understanding features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneUnderstandingComponent"
        }
      ],
      "role": "symbol",
      "title": "SceneUnderstandingComponent",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/Component-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/Component-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Component Implementations",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/component-implementations"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/EntityType-swift.enum": {
      "abstract": [
        {
          "text": "Types of real-world objects that a scene-understanding component models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EntityType"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/EntityType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EntityType"
        }
      ],
      "role": "symbol",
      "title": "SceneUnderstandingComponent.EntityType",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/entitytype-swift.enum"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/Origin-swift.enum": {
      "abstract": [
        {
          "text": "Types of scene-understanding origins this component lives in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Origin"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/Origin-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Origin"
        }
      ],
      "role": "symbol",
      "title": "SceneUnderstandingComponent.Origin",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/origin-swift.enum"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/entityType-swift.property": {
      "abstract": [
        {
          "text": "The type of real-world objects that the component models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentV",
          "text": "SceneUnderstandingComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentV10EntityTypeO",
          "text": "EntityType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/entityType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "entityType",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/entitytype-swift.property"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/init()": {
      "abstract": [
        {
          "text": "Creates a component that makes an entity aware of certain aspects of the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/init()"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/init(entityType:)": {
      "abstract": [
        {
          "text": "Creates a component for the given entity type that makes an entity aware",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "of certain aspects of the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentV",
          "text": "SceneUnderstandingComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentV10EntityTypeO",
          "text": "EntityType"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/init(entityType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(entityType:)",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/init(entitytype:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/origin-swift.property": {
      "abstract": [
        {
          "text": "The origin that RealityKit creates the component from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "origin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentV",
          "text": "SceneUnderstandingComponent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation27SceneUnderstandingComponentVAAE6OriginO",
          "text": "Origin"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/origin-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "origin",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/origin-swift.property"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/registerComponent()": {
      "abstract": [
        {
          "text": "Registers a new component type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerComponent"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/registerComponent()",
      "kind": "symbol",
      "role": "symbol",
      "title": "registerComponent()",
      "type": "topic",
      "url": "/documentation/realitykit/sceneunderstandingcomponent/registercomponent()"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding": {
      "abstract": [
        {
          "text": "Detect objects in an AR scene or create a detailed 3D reconstruction of the real-world environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
      "kind": "article",
      "role": "article",
      "title": "Implementing scene understanding and reconstruction in your RealityKit app",
      "type": "topic",
      "url": "/documentation/realitykit/realitykit-scene-understanding"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction": {
      "abstract": [
        {
          "text": "A flag that enables scene reconstruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneReconstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction",
      "kind": "symbol",
      "role": "symbol",
      "title": "sceneReconstruction",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)": {
      "abstract": [
        {
          "text": "Checks if the device supports scene reconstruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsSceneReconstruction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "sceneReconstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsSceneReconstruction(_:)",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)"
    },
    "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider": {
      "abstract": [
        {
          "text": "A source of live data about the shape of a person’s surroundings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneReconstructionProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "SceneReconstructionProvider",
      "type": "topic",
      "url": "/documentation/ARKit/SceneReconstructionProvider"
    },
    "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene": {
      "abstract": [
        {
          "text": "Estimate the shape of the physical environment using a polygonal mesh.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Visualizing and interacting with a reconstructed scene",
      "type": "topic",
      "url": "/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene"
    },
    "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding": {
      "abstract": [
        {
          "text": "Create AR games and experiences that interact with real-world objects on LiDAR-equipped iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a game with scene understanding",
      "type": "topic",
      "url": "/documentation/realitykit/creating_a_game_with_scene_understanding"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/Component"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scene-reconstructions-and-analysis",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
        "doc://com.apple.RealityKit/documentation/RealityKit/realitykit-scene-understanding",
        "doc://com.apple.documentation/documentation/ARKit/visualizing-and-interacting-with-a-reconstructed-scene",
        "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/sceneReconstruction",
        "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration/supportsSceneReconstruction(_:)",
        "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct",
        "doc://com.apple.RealityKit/documentation/RealityKit/ARView/Environment-swift.struct/SceneUnderstanding-swift.struct/Options-swift.struct",
        "doc://com.apple.RealityKit/documentation/RealityKit/HasSceneUnderstanding",
        "doc://com.apple.documentation/documentation/ARKit/SceneReconstructionProvider",
        "doc://com.apple.documentation/documentation/ARKit/ARSession"
      ],
      "title": "Scene reconstructions and analysis"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-scene-understanding-component",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/init()",
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/init(entityType:)"
      ],
      "title": "Initializing a scene-understanding component"
    },
    {
      "anchor": "Managing-the-component",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/entityType-swift.property",
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/EntityType-swift.enum",
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/registerComponent()"
      ],
      "title": "Managing the component"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/origin-swift.property"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/Origin-swift.enum"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/SceneUnderstandingComponent/Component-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1sceneReconstruction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARSceneReconstruction",
              "text": "ARSceneReconstruction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sceneReconstruction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1supportsSceneReconstruction(_:)/title",
          "value": "supportsSceneReconstruction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration~1supportsSceneReconstruction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "supportsSceneReconstruction:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ARSceneReconstruction",
              "text": "ARSceneReconstruction"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "sceneReconstruction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/sceneunderstandingcomponent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
