{
  "abstract": [
    {
      "text": "Leverage the Metal Performance Shaders framework to create special rendering effects",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "for your RealityKit scenes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit",
        "doc://com.apple.RealityKit/documentation/RealityKit/presentation-views-and-attachments",
        "doc://com.apple.RealityKit/documentation/RealityKit/postprocessing-effects"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/using-metal-performance-shaders-to-create-custom-postprocess-effects"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Using Metal performance shaders to create custom postprocess effects"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 15 and later, and macOS 12 and later, you can apply postprocess effects to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a RealityKit scene after RealityKit renders it, but before RealityKit displays it.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If you register a postprocess callback function, RealityKit passes that function",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the complete, rendered frame so you can modify it before the viewer sees it. You",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can use any image processing or drawing APIs on the rendered frame but, as a practical",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "matter, only APIs that execute on the GPU are fast enough to use every frame and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "maintain a good framerate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "One way to implement postprocess effects is to apply filters from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/metalperformanceshaders",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework to the rendered scene. You can use apply these filters to an image without",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "writing any custom shader code. Because these filters run on the GPU and operate",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "directly on Metal textures, they’re a good choice for postprocessing effects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the Metal Performance Shaders framework doesn’t provide an image filter that meets",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your needs, you can also use Core Image to postprocess frames. Core Image provides",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a greater selection of image filters, which also run on the GPU, but Core Image requires",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you to convert the rendered frame into a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/applying-core-image-filters-as-a-postprocess-effect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If neither the Metal Performance Shaders framework nor Core Image provide the effect",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you need, you can also write custom compute functions to implement postprocess effects.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/implementing-postprocess-effects-using-metal-compute-functions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Check-the-output-texture-pixel-format",
          "level": 3,
          "text": "Check the output texture pixel format",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some device GPUs require that the output texture be in a specific pixel format. If",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the device your code is running on doesn’t support ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLGPUFamily/apple2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "convert the output texture to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLPixelFormat/bgra8Unorm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "before using it. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/checking-the-pixel-format-of-a-postprocess-effect-s-output-texture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-callback-function",
          "level": 3,
          "text": "Create a callback function",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create postprocess effects using image filters from the Metal Performance Shaders",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework, create a Swift function that takes a single ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "parameter. In that method, create and configure an instance of the filter that you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "want to apply using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext/device",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from the context. Once you’ve created an instance of the shader, call its encode",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method, passing the command buffer, source color texture, and output texture from",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    func postEffectMPSGaussianBlur(context: ARView.PostProcessContext) {",
            "        let gaussianBlur = MPSImageGaussianBlur(device: context.device, sigma: 4)",
            "        gaussianBlur.encode(commandBuffer: context.commandBuffer,",
            "                            sourceTexture: context.sourceColorTexture,",
            "                            destinationTexture: context.compatibleTargetTexture)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "compatibleTargetTexture",
                  "type": "codeVoice"
                },
                {
                  "text": " property referenced above is a derived property",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "based on ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext/targetColorTexture",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". It ensures",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "that the output texture uses the appropriate pixel format for the current device.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/checking-the-pixel-format-of-a-postprocess-effect-s-output-texture",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Register-the-callback-function",
          "level": 3,
          "text": "Register the callback function",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To apply the effect, register the function as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/RenderCallbacks-swift.struct/postProcess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "render callback for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "arView.renderCallbacks.postProcess = postEffectMPSGaussianBlur"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "For more information on using Metal Performance Shader framework image filters",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "to create postprocess effects, see the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/realitykit/implementing_special_rendering_effects_with_realitykit_postprocessing",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "sample code project.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView": {
      "abstract": [
        {
          "text": "A view that enables you to display an AR experience with RealityKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARView"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARView"
        }
      ],
      "role": "symbol",
      "title": "ARView",
      "type": "topic",
      "url": "/documentation/realitykit/arview"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext": {
      "abstract": [
        {
          "text": "An object the framework uses to pass data to a postprocess callback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PostProcessContext"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PostProcessContext"
        }
      ],
      "role": "symbol",
      "title": "ARView.PostProcessContext",
      "type": "topic",
      "url": "/documentation/realitykit/arview/postprocesscontext"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext/device": {
      "abstract": [
        {
          "text": "The Metal device where the scene renders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext/device",
      "kind": "symbol",
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/realitykit/arview/postprocesscontext/device"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext/targetColorTexture": {
      "abstract": [
        {
          "text": "The output texture where the postprocess callback writes the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "modified frame buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetColorTexture"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/PostProcessContext/targetColorTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "targetColorTexture",
      "type": "topic",
      "url": "/documentation/realitykit/arview/postprocesscontext/targetcolortexture"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/ARView/RenderCallbacks-swift.struct/postProcess": {
      "abstract": [
        {
          "text": "A callback function for implementing postprocess effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postProcess"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@RealityKit@objc(cs)ARView",
          "text": "ARView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10RealityKit6ARViewC18PostProcessContextV",
          "text": "PostProcessContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/ARView/RenderCallbacks-swift.struct/postProcess",
      "kind": "symbol",
      "role": "symbol",
      "title": "postProcess",
      "type": "topic",
      "url": "/documentation/realitykit/arview/rendercallbacks-swift.struct/postprocess"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/applying-core-image-filters-as-a-postprocess-effect": {
      "abstract": [
        {
          "text": "Create special rendering effects for your RealityKit scenes using Core Image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/applying-core-image-filters-as-a-postprocess-effect",
      "kind": "article",
      "role": "article",
      "title": "Applying core image filters as a postprocess effect",
      "type": "topic",
      "url": "/documentation/realitykit/applying-core-image-filters-as-a-postprocess-effect"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/checking-the-pixel-format-of-a-postprocess-effect-s-output-texture": {
      "abstract": [
        {
          "text": "Make sure your postprocess effect works on all devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/checking-the-pixel-format-of-a-postprocess-effect-s-output-texture",
      "kind": "article",
      "role": "article",
      "title": "Checking the pixel format of a postprocess effect’s output texture",
      "type": "topic",
      "url": "/documentation/realitykit/checking-the-pixel-format-of-a-postprocess-effect-s-output-texture"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/implementing-postprocess-effects-using-metal-compute-functions": {
      "abstract": [
        {
          "text": "Create custom shaders to implement postprocess effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/implementing-postprocess-effects-using-metal-compute-functions",
      "kind": "article",
      "role": "article",
      "title": "Implementing postprocess effects using Metal compute functions",
      "type": "topic",
      "url": "/documentation/realitykit/implementing-postprocess-effects-using-metal-compute-functions"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/passing-structured-data-to-a-metal-compute-function": {
      "abstract": [
        {
          "text": "Send nontexture data from Swift to your Metal shaders using a shared header file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/passing-structured-data-to-a-metal-compute-function",
      "kind": "article",
      "role": "article",
      "title": "Passing Structured Data to a Metal Compute Function",
      "type": "topic",
      "url": "/documentation/realitykit/passing-structured-data-to-a-metal-compute-function"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/postprocessing-effects": {
      "abstract": [
        {
          "text": "Create special rendering effects for your RealityKit scenes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/postprocessing-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Postprocessing effects",
      "type": "topic",
      "url": "/documentation/realitykit/postprocessing-effects"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/presentation-views-and-attachments": {
      "abstract": [
        {
          "text": "Bring RealityKit content into your app with views and renderers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/presentation-views-and-attachments",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and attachments",
      "type": "topic",
      "url": "/documentation/realitykit/presentation-views-and-attachments"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLGPUFamily/apple2": {
      "abstract": [
        {
          "text": "Represents the Apple family 2 GPU features that correspond to the Apple A8 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple2"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLGPUFamily/apple2",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLGPUFamily.apple2",
      "type": "topic",
      "url": "/documentation/Metal/MTLGPUFamily/apple2"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLPixelFormat/bgra8Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized unsigned integer components in BGRA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bgra8Unorm"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLPixelFormat/bgra8Unorm",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLPixelFormat.bgra8Unorm",
      "type": "topic",
      "url": "/documentation/Metal/MTLPixelFormat/bgra8Unorm"
    },
    "doc://com.apple.documentation/documentation/coreimage/ciimage": {
      "abstract": [
        {
          "text": "A representation of an image to be processed or produced by Core Image filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/ciimage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIImage",
      "type": "topic",
      "url": "/documentation/coreimage/ciimage"
    },
    "doc://com.apple.documentation/documentation/metalperformanceshaders": {
      "abstract": [
        {
          "text": "Optimize graphics and compute performance with kernels that are fine-tuned for the unique characteristics of each Metal GPU family.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/metalperformanceshaders",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal Performance Shaders",
      "type": "topic",
      "url": "/documentation/metalperformanceshaders"
    },
    "doc://com.apple.documentation/documentation/realitykit/implementing_special_rendering_effects_with_realitykit_postprocessing": {
      "abstract": [
        {
          "text": "Implement a variety of postprocessing techniques to alter RealityKit rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/realitykit/implementing_special_rendering_effects_with_realitykit_postprocessing",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing Special Rendering Effects with RealityKit Postprocessing",
      "type": "topic",
      "url": "/documentation/realitykit/implementing_special_rendering_effects_with_realitykit_postprocessing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metal-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/realitykit/implementing_special_rendering_effects_with_realitykit_postprocessing",
        "doc://com.apple.RealityKit/documentation/RealityKit/checking-the-pixel-format-of-a-postprocess-effect-s-output-texture",
        "doc://com.apple.RealityKit/documentation/RealityKit/passing-structured-data-to-a-metal-compute-function",
        "doc://com.apple.RealityKit/documentation/RealityKit/implementing-postprocess-effects-using-metal-compute-functions"
      ],
      "title": "Metal effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLGPUFamily~1apple2/title",
          "value": "MTLGPUFamilyApple2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLGPUFamily~1apple2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLPixelFormat~1bgra8Unorm/title",
          "value": "MTLPixelFormatBGRA8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLPixelFormat~1bgra8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatBGRA8Unorm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/using-metal-performance-shaders-to-create-custom-postprocess-effects"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
