{
  "abstract": [
    {
      "text": "A material that supports animated textures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17RealityFoundation13VideoMaterialV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VideoMaterial"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VideoMaterial"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "VideoMaterial"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VideoMaterial"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In RealityKit, a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "material",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is an object that defines the surface properties",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of a rendered 3D object. A ",
              "type": "text"
            },
            {
              "code": "VideoMaterial",
              "type": "codeVoice"
            },
            {
              "text": " is a material that maps a movie",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "file on to the surface of an entity. Video materials are ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "unlit",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "means that scene lighting doesn’t affect them. Video materials support",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "transparency if the source video’s file format also supports transparency.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Video materials use an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to control movie playback. You can use any movie file format that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " supports",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to create a video material. To control playback of the material’s video, use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/avPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, which offers methods like",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer/play()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer/pause()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code demonstrates how to create and start playing a video",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "material using a movie file from your application bundle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create a URL that points to the movie file.",
            "if let url = Bundle.main.url(forResource: \"MyMovie\", withExtension: \"mp4\") {",
            "",
            "    // Create an AVPlayer instance to control playback of that movie.",
            "    let player = AVPlayer(url: url)",
            "",
            "    // Instantiate and configure the video material.",
            "    let material = VideoMaterial(avPlayer: player)",
            "",
            "    // Configure audio playback mode.",
            "    material.controller.audioInputMode = .spatial",
            "",
            "    // Create a new model entity using the video material.",
            "    let modelEntity = ModelEntity(mesh: cube, materials: [material])",
            "",
            "    // Start playing the video.",
            "    player.play()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To see an example of using a video texture in RealityKit, see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/Material": {
      "abstract": [
        {
          "text": "A type that describes the material aspects of a mesh, like color and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Material"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/Material",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Material"
        }
      ],
      "role": "symbol",
      "title": "Material",
      "type": "topic",
      "url": "/documentation/realitykit/material"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial": {
      "abstract": [
        {
          "text": "A material that supports animated textures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VideoMaterial"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VideoMaterial"
        }
      ],
      "role": "symbol",
      "title": "VideoMaterial",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/FaceCulling-swift.typealias": {
      "abstract": [
        {
          "text": "An alias for the cull mode object that’s appropriate for this material class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FaceCulling"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/FaceCulling-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FaceCulling"
        }
      ],
      "role": "symbol",
      "title": "VideoMaterial.FaceCulling",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/faceculling-swift.typealias"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/Material-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/Material-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Material Implementations",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/material-implementations"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/Parameters": {
      "abstract": [
        {
          "text": "The parameter type that custom materials uses for properties the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "framework passes to shader functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Parameters"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/Parameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Parameters"
        }
      ],
      "role": "symbol",
      "title": "VideoMaterial.Parameters",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/parameters"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/TriangleFillMode-swift.typealias": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TriangleFillMode"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/TriangleFillMode-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TriangleFillMode"
        }
      ],
      "role": "symbol",
      "title": "VideoMaterial.TriangleFillMode",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/trianglefillmode-swift.typealias"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/avPlayer": {
      "abstract": [
        {
          "text": "The material’s video playback controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "avPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/avPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "avPlayer",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/avplayer"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/controller": {
      "abstract": [
        {
          "text": "An object that configures framework-specific video options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation23VideoPlaybackControllerC",
          "text": "VideoPlaybackController"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/controller",
      "kind": "symbol",
      "role": "symbol",
      "title": "controller",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/controller"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/faceCulling-swift.property": {
      "abstract": [
        {
          "text": "A process in which the system specifies polygons to remove before",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "rendering a mesh using this material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceCulling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation13VideoMaterialV",
          "text": "VideoMaterial"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation13VideoMaterialVAAE11FaceCullinga",
          "text": "FaceCulling"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/faceCulling-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "faceCulling",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/faceculling-swift.property"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/init(avPlayer:)": {
      "abstract": [
        {
          "text": "Creates a new video material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "avPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayer",
          "text": "AVPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/init(avPlayer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(avPlayer:)",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/init(avplayer:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/init(videoRenderer:)": {
      "abstract": [
        {
          "text": "Creates and initializes a video material for a sample buffer video renderer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "videoRenderer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSampleBufferVideoRenderer",
          "text": "AVSampleBufferVideoRenderer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/init(videoRenderer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(videoRenderer:)",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/init(videorenderer:)"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/readsDepth": {
      "abstract": [
        {
          "text": "A boolean value that determines whether this material performs the depth test by reading RealityKit’s depth buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readsDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/readsDepth",
      "kind": "symbol",
      "role": "symbol",
      "title": "readsDepth",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/readsdepth"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/triangleFillMode-swift.property": {
      "abstract": [
        {
          "text": "The object that controls how RealityKit draws triangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleFillMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation13VideoMaterialV",
          "text": "VideoMaterial"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation13VideoMaterialV16TriangleFillModea",
          "text": "TriangleFillMode"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/triangleFillMode-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "triangleFillMode",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/trianglefillmode-swift.property"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/videoRenderer": {
      "abstract": [
        {
          "text": "The material’s video renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRenderer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSampleBufferVideoRenderer",
          "text": "AVSampleBufferVideoRenderer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/videoRenderer",
      "kind": "symbol",
      "role": "symbol",
      "title": "videoRenderer",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/videorenderer"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/writesDepth": {
      "abstract": [
        {
          "text": "A boolean value that determines whether this material writes its depth into RealityKit’s depth buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writesDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/writesDepth",
      "kind": "symbol",
      "role": "symbol",
      "title": "writesDepth",
      "type": "topic",
      "url": "/documentation/realitykit/videomaterial/writesdepth"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer/pause()": {
      "abstract": [
        {
          "text": "Pauses playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer/pause()",
      "kind": "symbol",
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer/pause()"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer/play()": {
      "abstract": [
        {
          "text": "Begins playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayer/play()",
      "kind": "symbol",
      "role": "symbol",
      "title": "play()",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayer/play()"
    },
    "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding": {
      "abstract": [
        {
          "text": "Create AR games and experiences that interact with real-world objects on LiDAR-equipped iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/realitykit/creating_a_game_with_scene_understanding",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a game with scene understanding",
      "type": "topic",
      "url": "/documentation/realitykit/creating_a_game_with_scene_understanding"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/Material"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Video-materials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/FaceCulling-swift.typealias",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/TriangleFillMode-swift.typealias",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/Parameters"
      ],
      "title": "Video materials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-video-material",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/init(avPlayer:)"
      ],
      "title": "Creating a video material"
    },
    {
      "anchor": "Controlling-playback",
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/avPlayer",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/controller"
      ],
      "title": "Controlling playback"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/init(videoRenderer:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/faceCulling-swift.property",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/readsDepth",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/triangleFillMode-swift.property",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/videoRenderer",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/writesDepth"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/FaceCulling-swift.typealias",
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/TriangleFillMode-swift.typealias"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/VideoMaterial/Material-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer~1play()/title",
          "value": "play"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer~1play()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "play"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "pause"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/videomaterial"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
