{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/callkit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CallKit Constants"
  },
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainNotificationServiceExtension": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainNotificationServiceExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainNotificationServiceExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainNotificationServiceExtension"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainNotificationServiceExtension",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomainnotificationserviceextension"
    },
    "doc://com.apple.callkit/documentation/CallKit/CX_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CX_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CX_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CX_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/callkit/cx_class_available"
    },
    "doc://com.apple.callkit/documentation/CallKit/CX_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CX_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CX_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CX_EXTERN",
      "type": "topic",
      "url": "/documentation/callkit/cx_extern"
    },
    "doc://com.apple.callkit/documentation/CallKit/callkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/callkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CallKit Enumerations",
      "type": "topic",
      "url": "/documentation/callkit/callkit-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/callkit-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainNotificationServiceExtension"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainNotificationServiceExtension",
                "doc://com.apple.callkit/documentation/CallKit/CX_EXTERN",
                "doc://com.apple.callkit/documentation/CallKit/CX_CLASS_AVAILABLE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/callkit-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainNotificationServiceExtension/title",
          "value": "CXErrorDomainNotificationServiceExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainNotificationServiceExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainNotificationServiceExtension"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/callkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/callkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
