{
  "abstract": [
    {
      "text": "A collection of methods a Call Directory extension context object calls when a request fails.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CXCallDirectoryExtensionContextDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXCallDirectoryExtensionContextDelegate"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXCallDirectoryExtensionContextDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CXCallDirectoryExtensionContextDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext": {
      "abstract": [
        {
          "text": "A programmatic interface for adding identification and blocking entries to a Call Directory app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryExtensionContext",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryextensioncontext"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate": {
      "abstract": [
        {
          "text": "A collection of methods a Call Directory extension context object calls when a request fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContextDelegate"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContextDelegate"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryExtensionContextDelegate",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryextensioncontextdelegate"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate/requestFailed(for:withError:)": {
      "abstract": [
        {
          "text": "Called when a Call Directory app extension request fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestFailed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallDirectoryExtensionContext",
          "text": "CXCallDirectoryExtensionContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate/requestFailed(for:withError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestFailedForExtensionContext:withError:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "requestFailed(for:withError:)",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryextensioncontextdelegate/requestfailed(for:witherror:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager": {
      "abstract": [
        {
          "text": "The programmatic interface to an object that manages a Call Directory app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryManager"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryManager"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryManager",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider": {
      "abstract": [
        {
          "text": "The principal object for a Call Directory app extension for a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryProvider"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls": {
      "abstract": [
        {
          "text": "Create a Call Directory app extension to identify and block incoming callers",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "by their phone number.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls",
      "kind": "article",
      "role": "article",
      "title": "Identifying and blocking calls",
      "type": "topic",
      "url": "/documentation/callkit/identifying-and-blocking-calls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Caller-ID",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager"
      ],
      "title": "Caller ID"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-Request-Failures",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate/requestFailed(for:withError:)"
      ],
      "title": "Handling Request Failures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXCallDirectoryExtensionContextDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Request-Failures",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate/requestFailed(for:withError:)"
              ],
              "title": "Handling Request Failures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Caller-ID",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager"
              ],
              "title": "Caller ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXCallDirectoryExtensionContextDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryProvider/title",
          "value": "CXCallDirectoryProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContext/title",
          "value": "CXCallDirectoryExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate/title",
          "value": "CXCallDirectoryExtensionContextDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate~1requestFailed(for:withError:)/title",
          "value": "requestFailedForExtensionContext:withError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate~1requestFailed(for:withError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestFailedForExtensionContext:withError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager/title",
          "value": "CXCallDirectoryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxcalldirectoryextensioncontextdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxcalldirectoryextensioncontextdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
