{
  "abstract": [
    {
      "text": "The programmatic interface to an object that manages a Call Directory app extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CXCallDirectoryManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXCallDirectoryManager"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXCallDirectoryManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CXCallDirectoryManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext": {
      "abstract": [
        {
          "text": "A programmatic interface for adding identification and blocking entries to a Call Directory app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryExtensionContext",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryextensioncontext"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate": {
      "abstract": [
        {
          "text": "A collection of methods a Call Directory extension context object calls when a request fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContextDelegate"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryExtensionContextDelegate"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryExtensionContextDelegate",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryextensioncontextdelegate"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager": {
      "abstract": [
        {
          "text": "The programmatic interface to an object that manages a Call Directory app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryManager"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryManager"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryManager",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus": {
      "abstract": [
        {
          "text": "The enabled status of a Call Directory app extension, as reported by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnabledStatus"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnabledStatus"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryManager.EnabledStatus",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/enabledstatus"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously returns the enabled status of the extension with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getEnabledStatusForExtension"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallDirectoryManager",
          "text": "CXCallDirectoryManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXCallDirectoryEnabledStatus",
          "text": "EnabledStatus"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getEnabledStatusForExtension(withIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/getenabledstatusforextension(withidentifier:completionhandler:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/openSettings(completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the iOS Settings app and shows the Call Blocking & Identification settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/openSettings(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openSettingsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openSettings(completionHandler:)",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/opensettings(completionhandler:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/reloadExtension(withIdentifier:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously reloads the extension with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadExtension"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/reloadExtension(withIdentifier:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reloadExtensionWithIdentifier:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "reloadExtension(withIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/reloadextension(withidentifier:completionhandler:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/sharedInstance": {
      "abstract": [
        {
          "text": "Returns the shared call directory manager instance for the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sharedInstance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallDirectoryManager",
          "text": "CXCallDirectoryManager"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/sharedInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedInstance"
        }
      ],
      "role": "symbol",
      "title": "sharedInstance",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/sharedinstance"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider": {
      "abstract": [
        {
          "text": "The principal object for a Call Directory app extension for a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallDirectoryProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallDirectoryProvider"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectoryprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the CallKit framework returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager": {
      "abstract": [
        {
          "text": "Domain for errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainCallDirectoryManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainCallDirectoryManager"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainCallDirectoryManager",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomaincalldirectorymanager"
    },
    "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls": {
      "abstract": [
        {
          "text": "Create a Call Directory app extension to identify and block incoming callers",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "by their phone number.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls",
      "kind": "article",
      "role": "article",
      "title": "Identifying and blocking calls",
      "type": "topic",
      "url": "/documentation/callkit/identifying-and-blocking-calls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Caller-ID",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate"
      ],
      "title": "Caller ID"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Shared-Instance",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/sharedInstance"
      ],
      "title": "Accessing the Shared Instance"
    },
    {
      "anchor": "Working-with-a-Call-Directory-App-Extension",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/reloadExtension(withIdentifier:completionHandler:)",
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus"
      ],
      "title": "Working with a Call Directory App Extension"
    },
    {
      "anchor": "Opening-the-Settings-App",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/openSettings(completionHandler:)"
      ],
      "title": "Opening the Settings App"
    },
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXCallDirectoryManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Shared-Instance",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/sharedInstance"
              ],
              "title": "Accessing the Shared Instance"
            },
            {
              "anchor": "Working-with-a-Call-Directory-App-Extension",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/reloadExtension(withIdentifier:completionHandler:)",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus"
              ],
              "title": "Working with a Call Directory App Extension"
            },
            {
              "anchor": "Opening-the-Settings-App",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/openSettings(completionHandler:)"
              ],
              "title": "Opening the Settings App"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Caller-ID",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/identifying-and-blocking-calls",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryProvider",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContext",
                "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryExtensionContextDelegate"
              ],
              "title": "Caller ID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXCallDirectoryManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryProvider/title",
          "value": "CXCallDirectoryProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/title",
          "value": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/title",
          "value": "CXCallDirectoryEnabledStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryEnabledStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryEnabledStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate/title",
          "value": "CXCallDirectoryExtensionContextDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContextDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1sharedInstance/title",
          "value": "sharedInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1sharedInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1openSettings(completionHandler:)/title",
          "value": "openSettingsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1openSettings(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openSettingsWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1getEnabledStatusForExtension(withIdentifier:completionHandler:)/title",
          "value": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1getEnabledStatusForExtension(withIdentifier:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainCallDirectoryManager/title",
          "value": "CXErrorDomainCallDirectoryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainCallDirectoryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContext/title",
          "value": "CXCallDirectoryExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1reloadExtension(withIdentifier:completionHandler:)/title",
          "value": "reloadExtensionWithIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1reloadExtension(withIdentifier:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reloadExtensionWithIdentifier:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager/title",
          "value": "CXCallDirectoryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxcalldirectorymanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxcalldirectorymanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
