{
  "abstract": [
    {
      "text": "An encapsulation of new and changed information about a call.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CXCallUpdate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXCallUpdate"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXCallUpdate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CXCallUpdate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXCallUpdate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects are used by the system to communicate changes to calls over time. Not every property on a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object must be set each time, as each object includes only new and changed information. For example, when a call is started, only some properties may be known and included in the first ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object sent to the system, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/localizedCallerName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Later in the same call, other properties may change; for example, a call may be upgraded from audio only to audio and video, which would be reflected by a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/hasVideo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When an incoming call is received, you construct a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object specifying a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/localizedCallerName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and pass that to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to notify the telephony provider.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When an active call is updated, you construct a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object specifying any updated information and pass that to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. For example, if a user changes their contact information during a call, you could notify the telephony provider of this change using a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with the new value set to its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/remoteHandle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXAnswerCallAction": {
      "abstract": [
        {
          "text": "An encapsulation of the act of answering an incoming call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXAnswerCallAction"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXAnswerCallAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXAnswerCallAction"
        }
      ],
      "role": "symbol",
      "title": "CXAnswerCallAction",
      "type": "topic",
      "url": "/documentation/callkit/cxanswercallaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate": {
      "abstract": [
        {
          "text": "An encapsulation of new and changed information about a call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallUpdate"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallUpdate"
        }
      ],
      "role": "symbol",
      "title": "CXCallUpdate",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/hasVideo": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the call includes video in addition to audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/hasVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasVideo"
        }
      ],
      "role": "symbol",
      "title": "hasVideo",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/hasvideo"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/localizedCallerName": {
      "abstract": [
        {
          "text": "The localized name of the caller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedCallerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/localizedCallerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedCallerName"
        }
      ],
      "role": "symbol",
      "title": "localizedCallerName",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/localizedcallername"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/remoteHandle": {
      "abstract": [
        {
          "text": "The handle for the remote party (for an incoming call, this is the caller; for an outgoing call, this is the callee).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXHandle",
          "text": "CXHandle"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/remoteHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remoteHandle"
        }
      ],
      "role": "symbol",
      "title": "remoteHandle",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/remotehandle"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsDTMF": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the call can send DTMF (dual tone multifrequency) tones via hard pause digits or in-call keypad entries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDTMF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsDTMF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDTMF"
        }
      ],
      "role": "symbol",
      "title": "supportsDTMF",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/supportsdtmf"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsGrouping": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the call can be grouped with other calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsGrouping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsGrouping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsGrouping"
        }
      ],
      "role": "symbol",
      "title": "supportsGrouping",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/supportsgrouping"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsHolding": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the call can be placed on hold or removed from hold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsHolding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsHolding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsHolding"
        }
      ],
      "role": "symbol",
      "title": "supportsHolding",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/supportsholding"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsUngrouping": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the call can be ungrouped from other calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsUngrouping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsUngrouping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsUngrouping"
        }
      ],
      "role": "symbol",
      "title": "supportsUngrouping",
      "type": "topic",
      "url": "/documentation/callkit/cxcallupdate/supportsungrouping"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an active call updated its information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallUpdate",
          "text": "CXCallUpdate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportCallWithUUID:updated:"
        }
      ],
      "role": "symbol",
      "title": "reportCall(with:updated:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportcall(with:updated:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)": {
      "abstract": [
        {
          "text": "Reports a new incoming call with the specified unique identifier to the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportNewIncomingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "update"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallUpdate",
          "text": "CXCallUpdate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportNewIncomingCallWithUUID:update:completion:"
        }
      ],
      "role": "symbol",
      "title": "reportNewIncomingCall(with:update:completion:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportnewincomingcall(with:update:completion:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls": {
      "abstract": [
        {
          "text": "Initiate outgoing calls with VoIP and configure your app to receive incoming calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
      "kind": "article",
      "role": "article",
      "title": "Making and receiving VoIP calls",
      "type": "topic",
      "url": "/documentation/callkit/making-and-receiving-voip-calls"
    },
    "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit": {
      "abstract": [
        {
          "text": "Receive incoming Voice-over-IP (VoIP) push notifications and use them to display the system call interface to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
      "kind": "article",
      "role": "article",
      "title": "Responding to VoIP Notifications from PushKit",
      "type": "topic",
      "url": "/documentation/PushKit/responding-to-voip-notifications-from-pushkit"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Incoming-calls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
        "doc://com.apple.callkit/documentation/CallKit/CXAnswerCallAction"
      ],
      "title": "Incoming calls"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Call-Update-Attributes",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/localizedCallerName",
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/remoteHandle",
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/hasVideo",
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsGrouping",
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsUngrouping",
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsHolding",
        "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsDTMF"
      ],
      "title": "Accessing Call Update Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXCallUpdate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Call-Update-Attributes",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/localizedCallerName",
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/remoteHandle",
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/hasVideo",
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsGrouping",
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsUngrouping",
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsHolding",
                "doc://com.apple.callkit/documentation/CallKit/CXCallUpdate/supportsDTMF"
              ],
              "title": "Accessing Call Update Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Incoming-calls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/PushKit/responding-to-voip-notifications-from-pushkit",
                "doc://com.apple.callkit/documentation/CallKit/CXAnswerCallAction"
              ],
              "title": "Incoming calls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXCallUpdate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1localizedCallerName/title",
          "value": "localizedCallerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1localizedCallerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedCallerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsUngrouping/title",
          "value": "supportsUngrouping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsUngrouping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsUngrouping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1remoteHandle/title",
          "value": "remoteHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1remoteHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate/title",
          "value": "CXCallUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:updated:)/title",
          "value": "reportCallWithUUID:updated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:updated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportCallWithUUID:updated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXAnswerCallAction/title",
          "value": "CXAnswerCallAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXAnswerCallAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXAnswerCallAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXAnswerCallAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXAnswerCallAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingCall(with:update:completion:)/title",
          "value": "reportNewIncomingCallWithUUID:update:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingCall(with:update:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportNewIncomingCallWithUUID:update:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsGrouping/title",
          "value": "supportsGrouping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsGrouping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsGrouping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1hasVideo/title",
          "value": "hasVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1hasVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsHolding/title",
          "value": "supportsHolding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsHolding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsHolding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsDTMF/title",
          "value": "supportsDTMF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallUpdate~1supportsDTMF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsDTMF"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxcallupdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxcallupdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
