{
  "abstract": [
    {
      "text": "Error codes for the CallKit errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11CXErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXError"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CXError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason": {
      "abstract": [
        {
          "text": "The reason that a call ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallEndedReason"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReason"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError": {
      "abstract": [
        {
          "text": "Error codes for the CallKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXError"
        }
      ],
      "role": "symbol",
      "title": "CXError",
      "type": "topic",
      "url": "/documentation/callkit/cxerror"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/Code": {
      "abstract": [
        {
          "text": "Error codes for the CallKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/errordomain"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/invalidArgument": {
      "abstract": [
        {
          "text": "The argument is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CXErrorCodeLeV",
          "text": "CXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/invalidArgument",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgument",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/invalidargument"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/missingVoIPBackgroundMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingVoIPBackgroundMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CXErrorCodeLeV",
          "text": "CXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/missingVoIPBackgroundMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingVoIPBackgroundMode",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/missingvoipbackgroundmode"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/unentitled": {
      "abstract": [
        {
          "text": "The caller doesn’t have the correct entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unentitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CXErrorCodeLeV",
          "text": "CXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/unentitled",
      "kind": "symbol",
      "role": "symbol",
      "title": "unentitled",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/unentitled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/unknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CXErrorCodeLeV",
          "text": "CXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/unknownerror"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct": {
      "abstract": [
        {
          "text": "Codes for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeNotificationServiceExtensionError-swift.struct": {
      "abstract": [
        {
          "text": "Errors that can occur when reporting new, incoming VoIP calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeNotificationServiceExtensionError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeNotificationServiceExtensionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeNotificationServiceExtensionError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeNotificationServiceExtensionError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodenotificationserviceextensionerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain": {
      "abstract": [
        {
          "text": "The domain for CallKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomain",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomain"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall": {
      "abstract": [
        {
          "text": "The domain for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainIncomingCall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainIncomingCall"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainIncomingCall",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomainincomingcall"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason",
        "doc://com.apple.callkit/documentation/CallKit/CXError/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeNotificationServiceExtensionError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall"
      ],
      "title": "Handling Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXError/invalidArgument",
        "doc://com.apple.callkit/documentation/CallKit/CXError/unentitled",
        "doc://com.apple.callkit/documentation/CallKit/CXError/unknownError"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXError/missingVoIPBackgroundMode",
        "doc://com.apple.callkit/documentation/CallKit/CXError/errorDomain"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXError/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomain/title",
          "value": "CXErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/title",
          "value": "CXCallEndedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXError~1Code/title",
          "value": "CXErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainIncomingCall/title",
          "value": "CXErrorDomainIncomingCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainIncomingCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainIncomingCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/title",
          "value": "CXErrorCodeIncomingCallError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
