{
  "abstract": [
    {
      "text": "Errors when interacting with a call directory manager.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXErrorCodeCallDirectoryManagerError"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXErrorCodeCallDirectoryManagerError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CXErrorCodeCallDirectoryManagerError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus": {
      "abstract": [
        {
          "text": "The enabled status of a Call Directory app extension, as reported by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnabledStatus"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnabledStatus"
        }
      ],
      "role": "symbol",
      "title": "CXCallDirectoryManager.EnabledStatus",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/enabledstatus"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously returns the enabled status of the extension with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getEnabledStatusForExtension"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallDirectoryManager",
          "text": "CXCallDirectoryManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXCallDirectoryEnabledStatus",
          "text": "EnabledStatus"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/getEnabledStatusForExtension(withIdentifier:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getEnabledStatusForExtension(withIdentifier:completionHandler:)",
      "type": "topic",
      "url": "/documentation/callkit/cxcalldirectorymanager/getenabledstatusforextension(withidentifier:completionhandler:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeCallDirectoryManagerError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes the CallKit framework returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeCallDirectoryManagerError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/currentlyLoading": {
      "abstract": [
        {
          "text": "The call directory manager is loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentlyLoading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/currentlyLoading",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentlyLoading",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/currentlyloading"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/duplicateEntries": {
      "abstract": [
        {
          "text": "There are duplicate entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateEntries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/duplicateEntries",
      "kind": "symbol",
      "role": "symbol",
      "title": "duplicateEntries",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/duplicateentries"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/entriesOutOfOrder": {
      "abstract": [
        {
          "text": "The entries in the call directory are out of order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entriesOutOfOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/entriesOutOfOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "entriesOutOfOrder",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/entriesoutoforder"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/errordomain"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/extensionDisabled": {
      "abstract": [
        {
          "text": "The call directory extension isn’t in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/extensionDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionDisabled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/extensiondisabled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/loadingInterrupted": {
      "abstract": [
        {
          "text": "The system interrupted the call directory manager while loading the app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadingInterrupted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/loadingInterrupted",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadingInterrupted",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/loadinginterrupted"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/maximumEntriesExceeded": {
      "abstract": [
        {
          "text": "There are too many entries in the call directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumEntriesExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/maximumEntriesExceeded",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumEntriesExceeded",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/maximumentriesexceeded"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/noExtensionFound": {
      "abstract": [
        {
          "text": "The call directory manager can’t find a corresponding app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noExtensionFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/noExtensionFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "noExtensionFound",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/noextensionfound"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unexpectedIncrementalRemoval": {
      "abstract": [
        {
          "text": "A request occurred before confirming incremental loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedIncrementalRemoval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unexpectedIncrementalRemoval",
      "kind": "symbol",
      "role": "symbol",
      "title": "unexpectedIncrementalRemoval",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/unexpectedincrementalremoval"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC36CXErrorCodeCallDirectoryManagerErrorLeV",
          "text": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeCallDirectoryManagerError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct/unknown"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager": {
      "abstract": [
        {
          "text": "Domain for errors when interacting with a call directory manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainCallDirectoryManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainCallDirectoryManager"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainCallDirectoryManager",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomaincalldirectorymanager"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallDirectoryManager/EnabledStatus",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainCallDirectoryManager"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/noExtensionFound",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/currentlyLoading",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/loadingInterrupted",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/entriesOutOfOrder",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/duplicateEntries",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/maximumEntriesExceeded",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/extensionDisabled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/unexpectedIncrementalRemoval"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/Code"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeCallDirectoryManagerError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/title",
          "value": "CXErrorCodeCallDirectoryManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeCallDirectoryManagerError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeCallDirectoryManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/title",
          "value": "CXCallDirectoryEnabledStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryEnabledStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1EnabledStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallDirectoryEnabledStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainCallDirectoryManager/title",
          "value": "CXErrorDomainCallDirectoryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainCallDirectoryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainCallDirectoryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1getEnabledStatusForExtension(withIdentifier:completionHandler:)/title",
          "value": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallDirectoryManager~1getEnabledStatusForExtension(withIdentifier:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getEnabledStatusForExtensionWithIdentifier:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcodecalldirectorymanagererror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
