{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXErrorCodeRequestTransactionError"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXErrorCodeRequestTransactionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CXErrorCodeRequestTransactionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the CallKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callIsProtected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callIsProtected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callIsProtected",
      "kind": "symbol",
      "role": "symbol",
      "title": "callIsProtected",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/callisprotected"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callUUIDAlreadyExists": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference a UUID that already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callUUIDAlreadyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callUUIDAlreadyExists",
      "kind": "symbol",
      "role": "symbol",
      "title": "callUUIDAlreadyExists",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/calluuidalreadyexists"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/emptyTransaction": {
      "abstract": [
        {
          "text": "The requested transaction doesn’t contain any actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emptyTransaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/emptyTransaction",
      "kind": "symbol",
      "role": "symbol",
      "title": "emptyTransaction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/emptytransaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/errordomain"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/invalidAction": {
      "abstract": [
        {
          "text": "The requested transaction contains an invalid action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/invalidAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/invalidaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/maximumCallGroupsReached": {
      "abstract": [
        {
          "text": "Performing the requested transaction exceeds the maximum number of call groups for the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCallGroupsReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/maximumCallGroupsReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumCallGroupsReached",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/maximumcallgroupsreached"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unentitled": {
      "abstract": [
        {
          "text": "The app doesn’t have the entitlement to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unentitled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unentitled",
      "kind": "symbol",
      "role": "symbol",
      "title": "unentitled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unentitled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unknown"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallProvider": {
      "abstract": [
        {
          "text": "The controller can’t find a call provider to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownCallProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unknowncallprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallUUID": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference an unknown UUID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC34CXErrorCodeRequestTransactionErrorLeV",
          "text": "CXErrorCodeRequestTransactionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXErrorCodeRequestTransactionError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallUUID",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownCallUUID",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/unknowncalluuid"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction": {
      "abstract": [
        {
          "text": "Domain for errors when requesting a transaction from a call controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainRequestTransaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainRequestTransaction"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainRequestTransaction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomainrequesttransaction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainRequestTransaction"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unentitled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/emptyTransaction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/unknownCallUUID",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callUUIDAlreadyExists",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/invalidAction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/maximumCallGroupsReached"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/callIsProtected",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/title",
          "value": "CXErrorCodeRequestTransactionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainRequestTransaction/title",
          "value": "CXErrorDomainRequestTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainRequestTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainRequestTransaction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
