{
  "abstract": [
    {
      "text": "An object that represents a telephony provider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CXProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXProvider"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CXProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is responsible for reporting out-of-band notifications that occur to the system. A VoIP app should create only one instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and store it for use globally. A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is initialized with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to specify the behavior and capabilities of calls. Each provider can specify an object conforming to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to respond to events, such as the call starting, the call being put on hold, or the provider’s audio session being activated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Subclassing-Notes",
          "level": 3,
          "text": "Subclassing Notes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is not intended for subclassing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason": {
      "abstract": [
        {
          "text": "The reason that a call ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXCallEndedReason"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXCallEndedReason"
        }
      ],
      "role": "symbol",
      "title": "CXCallEndedReason",
      "type": "topic",
      "url": "/documentation/callkit/cxcallendedreason"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError": {
      "abstract": [
        {
          "text": "Error codes for the CallKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXError"
        }
      ],
      "role": "symbol",
      "title": "CXError",
      "type": "topic",
      "url": "/documentation/callkit/cxerror"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXError/Code": {
      "abstract": [
        {
          "text": "Error codes for the CallKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerror/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct": {
      "abstract": [
        {
          "text": "Codes for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeNotificationServiceExtensionError-swift.struct": {
      "abstract": [
        {
          "text": "Errors that can occur when reporting new, incoming VoIP calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeNotificationServiceExtensionError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeNotificationServiceExtensionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeNotificationServiceExtensionError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeNotificationServiceExtensionError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodenotificationserviceextensionerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain": {
      "abstract": [
        {
          "text": "The domain for CallKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomain",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomain"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall": {
      "abstract": [
        {
          "text": "The domain for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorDomainIncomingCall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorDomainIncomingCall"
        }
      ],
      "role": "symbol",
      "title": "CXErrorDomainIncomingCall",
      "type": "topic",
      "url": "/documentation/callkit/cxerrordomainincomingcall"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider": {
      "abstract": [
        {
          "text": "An object that represents a telephony provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProvider"
        }
      ],
      "role": "symbol",
      "title": "CXProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/configuration": {
      "abstract": [
        {
          "text": "The configuration of the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProviderConfiguration",
          "text": "CXProviderConfiguration"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/configuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/configuration"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/init(configuration:)": {
      "abstract": [
        {
          "text": "Initializes a new provider with the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProviderConfiguration",
          "text": "CXProviderConfiguration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/init(configuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "init(configuration:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/init(configuration:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/invalidate()": {
      "abstract": [
        {
          "text": "Invalidates the provider and completes all active calls with an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/invalidate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "role": "symbol",
      "title": "invalidate()",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/invalidate()"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingCallActions(of:withCall:)": {
      "abstract": [
        {
          "text": "Returns all call actions in any pending transactions of the specified class for the specified call identifier that are incomplete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pendingCallActions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallAction",
          "text": "CXCallAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingCallActions(of:withCall:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pendingCallActionsOfClass:withCallUUID:"
        }
      ],
      "role": "symbol",
      "title": "pendingCallActions(of:withCall:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/pendingcallactions(of:withcall:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingTransactions": {
      "abstract": [
        {
          "text": "Incomplete transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pendingTransactions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXTransaction",
          "text": "CXTransaction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingTransactions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pendingTransactions"
        }
      ],
      "role": "symbol",
      "title": "pendingTransactions",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/pendingtransactions"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)": {
      "abstract": [
        {
          "text": "Reports to the provider that a call with the specified identifier ended at a given date for a particular reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endedAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXCallEndedReason",
          "text": "CXCallEndedReason"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportCallWithUUID:endedAtDate:reason:"
        }
      ],
      "role": "symbol",
      "title": "reportCall(with:endedAt:reason:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportcall(with:endedat:reason:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an active call updated its information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallUpdate",
          "text": "CXCallUpdate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportCallWithUUID:updated:"
        }
      ],
      "role": "symbol",
      "title": "reportCall(with:updated:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportcall(with:updated:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)": {
      "abstract": [
        {
          "text": "Reports a new incoming call with the specified unique identifier to the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportNewIncomingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "update"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallUpdate",
          "text": "CXCallUpdate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportNewIncomingCallWithUUID:update:completion:"
        }
      ],
      "role": "symbol",
      "title": "reportNewIncomingCall(with:update:completion:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportnewincomingcall(with:update:completion:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)": {
      "abstract": [
        {
          "text": "Reports a new incoming call after your notification service extension decrypts a VoIP call request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportNewIncomingVoIPPushPayload"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportNewIncomingVoIPPushPayload:completion:"
        }
      ],
      "role": "symbol",
      "title": "reportNewIncomingVoIPPushPayload(_:completion:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportnewincomingvoippushpayload(_:completion:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an outgoing call with the specified unique identifier finished connecting at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportOutgoingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "connectedAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportOutgoingCallWithUUID:connectedAtDate:"
        }
      ],
      "role": "symbol",
      "title": "reportOutgoingCall(with:connectedAt:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportoutgoingcall(with:connectedat:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)": {
      "abstract": [
        {
          "text": "Reports to the provider that an outgoing call with the specified unique identifier started connecting at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportOutgoingCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startedConnectingAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportOutgoingCallWithUUID:startedConnectingAtDate:"
        }
      ],
      "role": "symbol",
      "title": "reportOutgoingCall(with:startedConnectingAt:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/reportoutgoingcall(with:startedconnectingat:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider/setDelegate(_:queue:)": {
      "abstract": [
        {
          "text": "Sets a provider delegate, specifying an optional queue on which to execute delegate methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDelegate"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CXProviderDelegate",
          "text": "CXProviderDelegate"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider/setDelegate(_:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDelegate:queue:"
        }
      ],
      "role": "symbol",
      "title": "setDelegate(_:queue:)",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider/setdelegate(_:queue:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration": {
      "abstract": [
        {
          "text": "An encapsulation of the configuration of a provider object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProviderConfiguration"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProviderConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CXProviderConfiguration",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that a telephony provider object calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProviderDelegate"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProviderDelegate"
        }
      ],
      "role": "symbol",
      "title": "CXProviderDelegate",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate"
    },
    "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app": {
      "abstract": [
        {
          "text": "Configure your CallKit or LiveCommunicationKit app so people can set it as the default calling app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default calling app",
      "type": "topic",
      "url": "/documentation/callkit/preparing-your-app-to-be-the-default-calling-app"
    },
    "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls": {
      "abstract": [
        {
          "text": "Initiate outgoing calls with VoIP and configure your app to receive incoming calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
      "kind": "article",
      "role": "article",
      "title": "Making and receiving VoIP calls",
      "type": "topic",
      "url": "/documentation/callkit/making-and-receiving-voip-calls"
    },
    "doc://com.apple.callkit/documentation/CallKit/voip-calling-with-callkit": {
      "abstract": [
        {
          "text": "Use the CallKit framework to integrate native VoIP calling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/voip-calling-with-callkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "VoIP calling with CallKit",
      "type": "topic",
      "url": "/documentation/callkit/voip-calling-with-callkit"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering": {
      "abstract": [
        {
          "text": "Enable receiving notifications without displaying the notification to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.usernotifications.filtering",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
        "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
        "doc://com.apple.callkit/documentation/CallKit/voip-calling-with-callkit",
        "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-New-Providers",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/init(configuration:)"
      ],
      "title": "Creating New Providers"
    },
    {
      "anchor": "Setting-the-Delegate",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/setDelegate(_:queue:)"
      ],
      "title": "Setting the Delegate"
    },
    {
      "anchor": "Accessing-Provider-Attributes",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/configuration"
      ],
      "title": "Accessing Provider Attributes"
    },
    {
      "anchor": "Accessing-Pending-Transaction-and-Call-Actions",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingTransactions",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingCallActions(of:withCall:)"
      ],
      "title": "Accessing Pending Transaction and Call Actions"
    },
    {
      "anchor": "Reporting-Calls",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)"
      ],
      "title": "Reporting Calls"
    },
    {
      "anchor": "Invalidating-a-Provider",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider/invalidate()"
      ],
      "title": "Invalidating a Provider"
    },
    {
      "anchor": "Handling-Errors",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason",
        "doc://com.apple.callkit/documentation/CallKit/CXError",
        "doc://com.apple.callkit/documentation/CallKit/CXError/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeNotificationServiceExtensionError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall"
      ],
      "title": "Handling Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-New-Providers",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/init(configuration:)"
              ],
              "title": "Creating New Providers"
            },
            {
              "anchor": "Setting-the-Delegate",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/setDelegate(_:queue:)"
              ],
              "title": "Setting the Delegate"
            },
            {
              "anchor": "Accessing-Provider-Attributes",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/configuration"
              ],
              "title": "Accessing Provider Attributes"
            },
            {
              "anchor": "Accessing-Pending-Transaction-and-Call-Actions",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingTransactions",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/pendingCallActions(of:withCall:)"
              ],
              "title": "Accessing Pending Transaction and Call Actions"
            },
            {
              "anchor": "Reporting-Calls",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingCall(with:update:completion:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportNewIncomingVoIPPushPayload(_:completion:)",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.usernotifications.filtering",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:startedConnectingAt:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportOutgoingCall(with:connectedAt:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:updated:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/reportCall(with:endedAt:reason:)"
              ],
              "title": "Reporting Calls"
            },
            {
              "anchor": "Invalidating-a-Provider",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider/invalidate()"
              ],
              "title": "Invalidating a Provider"
            },
            {
              "anchor": "Handling-Errors",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXCallEndedReason",
                "doc://com.apple.callkit/documentation/CallKit/CXError/Code",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorDomain",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorDomainIncomingCall"
              ],
              "title": "Handling Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
                "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
                "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXProvider"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingCall(with:update:completion:)/title",
          "value": "reportNewIncomingCallWithUUID:update:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingCall(with:update:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportNewIncomingCallWithUUID:update:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:startedConnectingAt:)/title",
          "value": "reportOutgoingCallWithUUID:startedConnectingAtDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:startedConnectingAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportOutgoingCallWithUUID:startedConnectingAtDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:connectedAt:)/title",
          "value": "reportOutgoingCallWithUUID:connectedAtDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportOutgoingCall(with:connectedAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportOutgoingCallWithUUID:connectedAtDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomain/title",
          "value": "CXErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1setDelegate(_:queue:)/title",
          "value": "setDelegate:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1setDelegate(_:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDelegate:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1pendingCallActions(of:withCall:)/title",
          "value": "pendingCallActionsOfClass:withCallUUID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1pendingCallActions(of:withCall:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pendingCallActionsOfClass:withCallUUID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1configuration/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1configuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1pendingTransactions/title",
          "value": "pendingTransactions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1pendingTransactions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pendingTransactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:updated:)/title",
          "value": "reportCallWithUUID:updated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:updated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportCallWithUUID:updated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/title",
          "value": "CXProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXError~1Code/title",
          "value": "CXErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1invalidate()/title",
          "value": "invalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1invalidate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:endedAt:reason:)/title",
          "value": "reportCallWithUUID:endedAtDate:reason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportCall(with:endedAt:reason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reportCallWithUUID:endedAtDate:reason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/title",
          "value": "CXProviderConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingVoIPPushPayload(_:completion:)/title",
          "value": "reportNewIncomingVoIPPushPayload:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1reportNewIncomingVoIPPushPayload(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "reportNewIncomingVoIPPushPayload:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/title",
          "value": "CXCallEndedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXCallEndedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXCallEndedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate/title",
          "value": "CXProviderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1init(configuration:)/title",
          "value": "initWithConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider~1init(configuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/title",
          "value": "CXErrorCodeIncomingCallError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainIncomingCall/title",
          "value": "CXErrorDomainIncomingCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorDomainIncomingCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorDomainIncomingCall"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
