{
  "abstract": [
    {
      "text": "A collection of methods that a telephony provider object calls.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CXProviderDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CXProviderDelegate"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXProviderDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CXProviderDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol defines a set of methods that are called by an object that represents a telephony provider when the provider begins or resets, a transaction is requested, an action is performed, or an audio session changes its activation state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProvider": {
      "abstract": [
        {
          "text": "An object that represents a telephony provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProvider"
        }
      ],
      "role": "symbol",
      "title": "CXProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration": {
      "abstract": [
        {
          "text": "An encapsulation of the configuration of a provider object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProviderConfiguration"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProviderConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CXProviderConfiguration",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that a telephony provider object calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProviderDelegate"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProviderDelegate"
        }
      ],
      "role": "symbol",
      "title": "CXProviderDelegate",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didActivate:)": {
      "abstract": [
        {
          "text": "Called when the provider’s audio session is activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didActivate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didActivate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:didActivateAudioSession:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:didActivate:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:didactivate:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didDeactivate:)": {
      "abstract": [
        {
          "text": "Called when the provider’s audio session is deactivated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDeactivate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didDeactivate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:didDeactivateAudioSession:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:didDeactivate:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:diddeactivate:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:execute:)": {
      "abstract": [
        {
          "text": "Called when a transaction is executed by a call controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXTransaction",
          "text": "CXTransaction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:execute:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:executeTransaction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:execute:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:execute:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-2lem5": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified start call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXStartCallAction",
          "text": "CXStartCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-2lem5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performStartCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-2lem5"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4htxt": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified play DTMF (dual tone multifrequency) call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXPlayDTMFCallAction",
          "text": "CXPlayDTMFCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4htxt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performPlayDTMFCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-4htxt"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4u3yu": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified set muted call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXSetMutedCallAction",
          "text": "CXSetMutedCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4u3yu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performSetMutedCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-4u3yu"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-947b1": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified set held call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXSetHeldCallAction",
          "text": "CXSetHeldCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-947b1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performSetHeldCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-947b1"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9a0m": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified end call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXEndCallAction",
          "text": "CXEndCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9a0m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performEndCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-9a0m"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9masw": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified set group call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXSetGroupCallAction",
          "text": "CXSetGroupCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9masw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performSetGroupCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-9masw"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-h4in": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified answer call action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXAnswerCallAction",
          "text": "CXAnswerCallAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-h4in",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:performAnswerCallAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:perform:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:perform:)-h4in"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:timedOutPerforming:)": {
      "abstract": [
        {
          "text": "Called when the provider performs the specified action times out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timedOutPerforming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXAction",
          "text": "CXAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:timedOutPerforming:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provider:timedOutPerformingAction:"
        }
      ],
      "role": "symbol",
      "title": "provider(_:timedOutPerforming:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/provider(_:timedoutperforming:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidBegin(_:)": {
      "abstract": [
        {
          "text": "Called when the provider begins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDidBegin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidBegin(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providerDidBegin:"
        }
      ],
      "role": "symbol",
      "title": "providerDidBegin(_:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/providerdidbegin(_:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidReset(_:)": {
      "abstract": [
        {
          "text": "Called when the provider is reset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerDidReset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXProvider",
          "text": "CXProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidReset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providerDidReset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "providerDidReset(_:)",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderdelegate/providerdidreset(_:)"
    },
    "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app": {
      "abstract": [
        {
          "text": "Configure your CallKit or LiveCommunicationKit app so people can set it as the default calling app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default calling app",
      "type": "topic",
      "url": "/documentation/callkit/preparing-your-app-to-be-the-default-calling-app"
    },
    "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls": {
      "abstract": [
        {
          "text": "Initiate outgoing calls with VoIP and configure your app to receive incoming calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
      "kind": "article",
      "role": "article",
      "title": "Making and receiving VoIP calls",
      "type": "topic",
      "url": "/documentation/callkit/making-and-receiving-voip-calls"
    },
    "doc://com.apple.callkit/documentation/CallKit/voip-calling-with-callkit": {
      "abstract": [
        {
          "text": "Use the CallKit framework to integrate native VoIP calling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/voip-calling-with-callkit",
      "kind": "article",
      "role": "sampleCode",
      "title": "VoIP calling with CallKit",
      "type": "topic",
      "url": "/documentation/callkit/voip-calling-with-callkit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
        "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
        "doc://com.apple.callkit/documentation/CallKit/voip-calling-with-callkit",
        "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-Provider-Events",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidBegin(_:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidReset(_:)"
      ],
      "title": "Handling Provider Events"
    },
    {
      "anchor": "Determining-the-Execution-of-Transactions",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:execute:)"
      ],
      "title": "Determining the Execution of Transactions"
    },
    {
      "anchor": "Handling-Call-Actions",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-2lem5",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-h4in",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9a0m",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-947b1",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4u3yu",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9masw",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4htxt",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:timedOutPerforming:)"
      ],
      "title": "Handling Call Actions"
    },
    {
      "anchor": "Handling-Changes-to-Audio-Session-Activation-State",
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didActivate:)",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didDeactivate:)"
      ],
      "title": "Handling Changes to Audio Session Activation State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXProviderDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Provider-Events",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidBegin(_:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/providerDidReset(_:)"
              ],
              "title": "Handling Provider Events"
            },
            {
              "anchor": "Determining-the-Execution-of-Transactions",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:execute:)"
              ],
              "title": "Determining the Execution of Transactions"
            },
            {
              "anchor": "Handling-Call-Actions",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-2lem5",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-h4in",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9a0m",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-947b1",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4u3yu",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-9masw",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:perform:)-4htxt",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:timedOutPerforming:)"
              ],
              "title": "Handling Call Actions"
            },
            {
              "anchor": "Handling-Changes-to-Audio-Session-Activation-State",
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didActivate:)",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderDelegate/provider(_:didDeactivate:)"
              ],
              "title": "Handling Changes to Audio Session Activation State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXProvider",
                "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
                "doc://com.apple.callkit/documentation/CallKit/making-and-receiving-voip-calls",
                "doc://com.apple.callkit/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CXProviderDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-947b1/title",
          "value": "provider:performSetHeldCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-947b1/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performSetHeldCallAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/title",
          "value": "CXProviderConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-4htxt/title",
          "value": "provider:performPlayDTMFCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-4htxt/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performPlayDTMFCallAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-2lem5/title",
          "value": "provider:performStartCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-2lem5/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performStartCallAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:didActivate:)/title",
          "value": "provider:didActivateAudioSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:didActivate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:didActivateAudioSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:timedOutPerforming:)/title",
          "value": "provider:timedOutPerformingAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:timedOutPerforming:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:timedOutPerformingAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1providerDidReset(_:)/title",
          "value": "providerDidReset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1providerDidReset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "providerDidReset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:didDeactivate:)/title",
          "value": "provider:didDeactivateAudioSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:didDeactivate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:didDeactivateAudioSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-h4in/title",
          "value": "provider:performAnswerCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-h4in/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performAnswerCallAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1providerDidBegin(_:)/title",
          "value": "providerDidBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1providerDidBegin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "providerDidBegin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/title",
          "value": "CXProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate/title",
          "value": "CXProviderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-4u3yu/title",
          "value": "provider:performSetMutedCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-4u3yu/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performSetMutedCallAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-9a0m/title",
          "value": "provider:performEndCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-9a0m/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performEndCallAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:execute:)/title",
          "value": "provider:executeTransaction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:execute:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:executeTransaction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-9masw/title",
          "value": "provider:performSetGroupCallAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderDelegate~1provider(_:perform:)-9masw/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "provider:performSetGroupCallAction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxproviderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxproviderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
