{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iousbhost/iousbhostciendpointstatemachine/endpointstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iousbhost/iousbhostciendpointstatemachine/endpointstate"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointState"},"seeAlsoSections":[{"identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/controllerInterface","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/currentTransferMessage","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/deviceAddress","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointAddress"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOUSBHostCIEndpointState","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"endpointState"}],"externalID":"c:objc(cs)IOUSBHostCIEndpointStateMachine(py)endpointState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","kind":"typeIdentifier","text":"IOUSBHostCIEndpointState"}],"modules":[{"name":"IOUSBHost"}],"roleHeading":"Instance Property","symbolKind":"property","title":"endpointState","platforms":[{"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"10.15","beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"role":"symbol"},"references":{"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointState":{"type":"topic","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointState","navigatorTitle":[{"text":"endpointState","kind":"identifier"}],"kind":"symbol","title":"endpointState","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/endpointstate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointState"},{"text":": ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState":{"kind":"symbol","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstate","abstract":[],"navigatorTitle":[{"text":"IOUSBHostCIEndpointState","kind":"identifier"}],"role":"symbol","title":"IOUSBHostCIEndpointState"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/currentTransferMessage":{"type":"topic","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/currentTransferMessage","navigatorTitle":[{"text":"currentTransferMessage","kind":"identifier"}],"kind":"symbol","title":"currentTransferMessage","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/currenttransfermessage","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentTransferMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"IOUSBHostCIMessage","kind":"typeIdentifier","preciseIdentifier":"c:@S@IOUSBHostCIMessage"},{"text":">","kind":"text"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/controllerInterface":{"type":"topic","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/controllerInterface","navigatorTitle":[{"text":"controllerInterface","kind":"identifier"}],"kind":"symbol","title":"controllerInterface","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/controllerinterface","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerInterface"},{"kind":"text","text":": "},{"text":"IOUSBHostControllerInterface","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)IOUSBHostControllerInterface"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost":{"abstract":[{"text":"Create host-mode user space drivers for USB devices.","type":"text"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost","url":"/documentation/iousbhost","role":"collection","title":"IOUSBHost","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointAddress":{"type":"topic","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointAddress","navigatorTitle":[{"text":"endpointAddress","kind":"identifier"}],"kind":"symbol","title":"endpointAddress","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/endpointaddress","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"endpointAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/deviceAddress":{"type":"topic","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/deviceAddress","navigatorTitle":[{"text":"deviceAddress","kind":"identifier"}],"kind":"symbol","title":"deviceAddress","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/deviceaddress","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceAddress"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine":{"title":"IOUSBHostCIEndpointStateMachine","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateMachine"}],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointStateMachine"}],"type":"topic","abstract":[],"url":"/documentation/iousbhost/iousbhostciendpointstatemachine","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","role":"overview","title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"10.15","name":"macOS","deprecated":false,"unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"endpointState"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"endpointState"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/controllerInterface","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/currentTransferMessage","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/deviceAddress","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/endpointAddress"],"title":"Instance Properties","anchor":"Instance-Properties"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"IOUSBHostCIEndpointState","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointState","preciseIdentifier":"c:@EA@IOUSBHostCIEndpointState","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"endpointState","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"endpointState","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1endpointState/title"},{"op":"replace","value":[{"text":"endpointState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1endpointState/fragments"},{"op":"replace","value":"IOUSBHostCIEndpointState","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/title"},{"op":"replace","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"IOUSBHostCIEndpointState"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointState/navigatorTitle"},{"op":"replace","value":"currentTransferMessage","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1currentTransferMessage/title"},{"op":"replace","value":[{"text":"currentTransferMessage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1currentTransferMessage/fragments"},{"op":"replace","value":"controllerInterface","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1controllerInterface/title"},{"op":"replace","value":[{"kind":"identifier","text":"controllerInterface"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1controllerInterface/fragments"},{"op":"replace","value":"endpointAddress","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1endpointAddress/title"},{"op":"replace","value":[{"text":"endpointAddress","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1endpointAddress/fragments"},{"op":"replace","value":"deviceAddress","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1deviceAddress/title"},{"op":"replace","value":[{"text":"deviceAddress","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1deviceAddress/fragments"},{"op":"replace","value":"IOUSBHostCIEndpointStateMachine","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/title"},{"op":"replace","value":[{"text":"IOUSBHostCIEndpointStateMachine","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/fragments"},{"op":"replace","value":[{"text":"IOUSBHostCIEndpointStateMachine","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}