{"seeAlsoSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/inspectCommand(_:)","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/processDoorbell(_:)","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/respond(toCommand:status:)"],"generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine"]]},"variants":[{"paths":["/documentation/iousbhost/iousbhostciendpointstatemachine/enqueuetransfercompletion(for:status:transferlength:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iousbhost/iousbhostciendpointstatemachine/enqueuetransfercompletion(for:status:transferlength:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"enqueueTransferCompletionForMessage:status:transferLength:error:"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"IOUSBHost"}],"title":"enqueueTransferCompletion(for:status:transferLength:)","symbolKind":"method","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.15"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueTransferCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"IOUSBHostCIMessage","preciseIdentifier":"c:@S@IOUSBHostCIMessage"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOUSBHostCIMessageStatus","preciseIdentifier":"c:@EA@IOUSBHostCIMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transferLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"externalID":"c:objc(cs)IOUSBHostCIEndpointStateMachine(im)enqueueTransferCompletionForMessage:status:transferLength:error:"},"sections":[],"identifier":{"url":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/enqueueTransferCompletion(for:status:transferLength:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueueTransferCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SP","identifier":"doc://com.externally.resolved.symbol/s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@IOUSBHostCIMessage","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessage","kind":"typeIdentifier","text":"IOUSBHostCIMessage"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIMessageStatus","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus","kind":"typeIdentifier","text":"IOUSBHostCIMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transferLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/inspectCommand(_:)":{"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/inspectCommand(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inspectCommand"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"IOUSBHostCIMessage","preciseIdentifier":"c:@S@IOUSBHostCIMessage"},{"kind":"text","text":">) "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"inspectCommand:error:"}],"abstract":[],"kind":"symbol","role":"symbol","title":"inspectCommand(_:)","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/inspectcommand(_:)"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessage":{"title":"IOUSBHostCIMessage","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessage","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/iousbhost/iousbhostcimessage","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIMessage"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IOUSBHostCIMessage"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost":{"abstract":[{"text":"Create host-mode user space drivers for USB devices.","type":"text"}],"type":"topic","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost","url":"/documentation/iousbhost","role":"collection","title":"IOUSBHost","kind":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/initWithInterface:command:error:":{"navigatorTitle":[{"text":"initWithInterface:command:error:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithInterface:command:error:","kind":"identifier"}],"url":"/documentation/iousbhost/iousbhostciendpointstatemachine/initwithinterface:command:error:","kind":"symbol","abstract":[],"title":"initWithInterface:command:error:","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/initWithInterface:command:error:"},"doc://com.externally.resolved.symbol/s:SP":{"url":"/documentation/Swift/UnsafePointer","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"title":"UnsafePointer","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Pointee","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SP","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"title":"NSError","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/foundation/nserror","abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}]},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/processDoorbell(_:)":{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/processDoorbell(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"processDoorbell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IOUSBHostCIDoorbell","kind":"typeIdentifier","preciseIdentifier":"c:@T@IOUSBHostCIDoorbell"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"processDoorbell(_:)","navigatorTitle":[{"kind":"identifier","text":"processDoorbell:error:"}],"url":"/documentation/iousbhost/iousbhostciendpointstatemachine/processdoorbell(_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"title":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/objectivec/nsuinteger","abstract":[{"text":"Describes an unsigned integer.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","type":"topic","abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"kind":"symbol","title":"BOOL","role":"symbol"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/respond(toCommand:status:)":{"kind":"symbol","url":"/documentation/iousbhost/iousbhostciendpointstatemachine/respond(tocommand:status:)","navigatorTitle":[{"kind":"identifier","text":"respondToCommand:status:error:"}],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/respond(toCommand:status:)","title":"respond(toCommand:status:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toCommand"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@IOUSBHostCIMessage","kind":"typeIdentifier","text":"IOUSBHostCIMessage"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIMessageStatus","kind":"typeIdentifier","text":"IOUSBHostCIMessageStatus"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","role":"overview","title":"Technologies","kind":"technologies"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/enqueueTransferCompletion(for:status:transferLength:)":{"url":"/documentation/iousbhost/iousbhostciendpointstatemachine/enqueuetransfercompletion(for:status:transferlength:)","navigatorTitle":[{"kind":"identifier","text":"enqueueTransferCompletionForMessage:status:transferLength:error:"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"enqueueTransferCompletion(for:status:transferLength:)","identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/enqueueTransferCompletion(for:status:transferLength:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enqueueTransferCompletion","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@IOUSBHostCIMessage","kind":"typeIdentifier","text":"IOUSBHostCIMessage"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@EA@IOUSBHostCIMessageStatus","kind":"typeIdentifier","text":"IOUSBHostCIMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transferLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://com.externally.resolved.symbol/s:Si":{"role":"symbol","url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","abstract":[{"type":"text","text":"A signed integer value type."}],"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus":{"kind":"symbol","title":"IOUSBHostCIMessageStatus","abstract":[],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOUSBHostCIMessageStatus","kind":"identifier"}],"navigatorTitle":[{"text":"IOUSBHostCIMessageStatus","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/iousbhost/iousbhostcimessagestatus"},"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine":{"title":"IOUSBHostCIEndpointStateMachine","navigatorTitle":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateMachine"}],"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOUSBHostCIEndpointStateMachine"}],"type":"topic","abstract":[],"url":"/documentation/iousbhost/iousbhostciendpointstatemachine","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.15"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"enqueueTransferCompletionForMessage:status:transferLength:error:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueTransferCompletionForMessage:status:transferLength:error:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iousbhost/documentation/IOUSBHost","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/inspectCommand(_:)","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/processDoorbell(_:)","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/respond(toCommand:status:)","doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIEndpointStateMachine/initWithInterface:command:error:"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"enqueueTransferCompletionForMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessage","text":"IOUSBHostCIMessage","kind":"typeIdentifier","preciseIdentifier":"c:@S@IOUSBHostCIMessage"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"status:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostCIMessageStatus","text":"IOUSBHostCIMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@EA@IOUSBHostCIMessageStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"transferLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"transferLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1inspectCommand(_:)/title","value":"inspectCommand:error:"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1inspectCommand(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"inspectCommand:error:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessage/title","value":"IOUSBHostCIMessage"},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessage/fragments","value":[{"text":"IOUSBHostCIMessage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessage/navigatorTitle","value":[{"text":"IOUSBHostCIMessage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1processDoorbell(_:)/title","value":"processDoorbell:error:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processDoorbell:error:"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1processDoorbell(_:)/fragments"},{"value":"respondToCommand:status:error:","op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1respond(toCommand:status:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"respondToCommand:status:error:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1respond(toCommand:status:)/fragments"},{"value":"enqueueTransferCompletionForMessage:status:transferLength:error:","op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1enqueueTransferCompletion(for:status:transferLength:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueTransferCompletionForMessage:status:transferLength:error:"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine~1enqueueTransferCompletion(for:status:transferLength:)/fragments"},{"value":"IOUSBHostCIMessageStatus","op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/title"},{"value":[{"text":"IOUSBHostCIMessageStatus","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/fragments"},{"value":[{"kind":"identifier","text":"IOUSBHostCIMessageStatus"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIMessageStatus/navigatorTitle"},{"value":"IOUSBHostCIEndpointStateMachine","op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/title"},{"value":[{"kind":"identifier","text":"IOUSBHostCIEndpointStateMachine"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/fragments"},{"value":[{"text":"IOUSBHostCIEndpointStateMachine","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostCIEndpointStateMachine/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}