{
  "abstract": [
    {
      "text": "A response code that indicates a workout is already in progress, so another can’t start.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureOngoingWorkout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartWorkoutIntentResponseCode@INStartWorkoutIntentResponseCodeFailureOngoingWorkout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureOngoingWorkout"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INStartWorkoutIntentResponseCode.failureOngoingWorkout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureOngoingWorkout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this code when the user is already in the middle of a workout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants that indicate the response state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/continueInApp": {
      "abstract": [
        {
          "text": "A response code that indicates your app extension is ready to transfer control to the app to start the workout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/continueInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeContinueInApp"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.continueInApp",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/continueinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "A response code that indicates you were unable to start the specified workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureNoMatchingWorkout": {
      "abstract": [
        {
          "text": "A response code that indicates you didn’t find the specified workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNoMatchingWorkout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureNoMatchingWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeFailureNoMatchingWorkout"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.failureNoMatchingWorkout",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/failurenomatchingworkout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureOngoingWorkout": {
      "abstract": [
        {
          "text": "A response code that indicates a workout is already in progress, so another can’t start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureOngoingWorkout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureOngoingWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.failureOngoingWorkout",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/failureongoingworkout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "A response code that indicates the user must launch your app to start the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/handleInApp": {
      "abstract": [
        {
          "text": "A response code that indicates you want to handle the intent in your app instead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/handleInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeHandleInApp"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.handleInApp",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/handleinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "A response code that indicates app readiness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/success": {
      "abstract": [
        {
          "text": "A response code that indicates your app succeeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "A response code that indicates an unknown state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/continueInApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/handleInApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureNoMatchingWorkout"
      ],
      "title": "Response State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/continueInApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/handleInApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode/failureNoMatchingWorkout"
              ],
              "title": "Response State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failureOngoingWorkout/title",
          "value": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failureOngoingWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeFailureOngoingWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1ready/title",
          "value": "INStartWorkoutIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INStartWorkoutIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failure/title",
          "value": "INStartWorkoutIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1continueInApp/title",
          "value": "INStartWorkoutIntentResponseCodeContinueInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1continueInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeContinueInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1success/title",
          "value": "INStartWorkoutIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode/title",
          "value": "INStartWorkoutIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1handleInApp/title",
          "value": "INStartWorkoutIntentResponseCodeHandleInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1handleInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeHandleInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failureNoMatchingWorkout/title",
          "value": "INStartWorkoutIntentResponseCodeFailureNoMatchingWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1failureNoMatchingWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeFailureNoMatchingWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1unspecified/title",
          "value": "INStartWorkoutIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCodeUnspecified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartworkoutintentresponsecode/failureongoingworkout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartworkoutintentresponsecode/failureongoingworkout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
