{
  "abstract": [
    {
      "text": "The file is extendable by fragments, but doesn’t contain any fragments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MEFileInfoFragmentsStatus@MEFileInfoCouldContainButDoesNotContainFragments",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "couldContainButDoesNotContainFragments"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEFileInfoCouldContainButDoesNotContainFragments"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MEFileInfo.FragmentsStatus.couldContainButDoesNotContainFragments"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "couldContainButDoesNotContainFragments"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo": {
      "abstract": [
        {
          "text": "An object that contains file properties from the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFileInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfo"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that describes if a media asset contains or supports fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FragmentsStatus"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments": {
      "abstract": [
        {
          "text": "The file is extendable by fragments and contains at least one fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsFragments"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfoContainsFragments"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus.containsFragments",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/containsfragments"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments": {
      "abstract": [
        {
          "text": "The file is extendable by fragments, but doesn’t contain any fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couldContainButDoesNotContainFragments"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldContainButDoesNotContainFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfoCouldContainButDoesNotContainFragments"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus.couldContainButDoesNotContainFragments",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/couldcontainbutdoesnotcontainfragments"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments": {
      "abstract": [
        {
          "text": "The file isn’t extendable by fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couldNotContainFragments"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfoCouldNotContainFragments"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo.FragmentsStatus.couldNotContainFragments",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/couldnotcontainfragments"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-fragment-status-values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments"
      ],
      "title": "File fragment status values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEFileInfoCouldContainButDoesNotContainFragments"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoCouldContainButDoesNotContainFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-fragment-status-values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/couldNotContainFragments",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo/FragmentsStatus-swift.enum/containsFragments"
              ],
              "title": "File fragment status values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MEFileInfoCouldContainButDoesNotContainFragments"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1containsFragments/title",
          "value": "MEFileInfoContainsFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1containsFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoContainsFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum/title",
          "value": "MEFileInfoFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/title",
          "value": "MEFileInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldNotContainFragments/title",
          "value": "MEFileInfoCouldNotContainFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldNotContainFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoCouldNotContainFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldContainButDoesNotContainFragments/title",
          "value": "MEFileInfoCouldContainButDoesNotContainFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo~1FragmentsStatus-swift.enum~1couldContainButDoesNotContainFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfoCouldContainButDoesNotContainFragments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/couldcontainbutdoesnotcontainfragments"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mefileinfo/fragmentsstatus-swift.enum/couldcontainbutdoesnotcontainfragments"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
