{
  "abstract": [
    {
      "text": "Groups and sorts media item collections by podcast title.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/podcastTitle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPMediaGrouping@MPMediaGroupingPodcastTitle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "podcastTitle"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMediaGroupingPodcastTitle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MPMediaGrouping.podcastTitle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "podcastTitle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping": {
      "abstract": [
        {
          "text": "Keys used to configure a media query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaGrouping"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGrouping"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/album": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by album, and sorts songs within an album by track order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingAlbum"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.album",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/album"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/albumArtist": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by album artist (the primary performing artist for an album as a whole).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumArtist"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/albumArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingAlbumArtist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.albumArtist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/albumartist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/artist": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by performing artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingArtist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.artist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/artist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/composer": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composer"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingComposer"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.composer",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/composer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/genre": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by musical or film genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingGenre"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.genre",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/genre"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playlist"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingPlaylist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.playlist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/playlist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/podcastTitle": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by podcast title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcastTitle"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/podcastTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingPodcastTitle"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.podcastTitle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/podcasttitle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/title": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by title. For songs, for example, the title is the song name. This is the default grouping key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingTitle"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.title",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/title"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-query-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/title",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/album",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/artist",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/albumArtist",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/composer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/genre",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist"
      ],
      "title": "Media query keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMediaGroupingPodcastTitle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingPodcastTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-query-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/title",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/album",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/artist",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/albumArtist",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/composer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/genre",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist"
              ],
              "title": "Media query keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MPMediaGroupingPodcastTitle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1composer/title",
          "value": "MPMediaGroupingComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1podcastTitle/title",
          "value": "MPMediaGroupingPodcastTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1podcastTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingPodcastTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping/title",
          "value": "MPMediaGrouping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGrouping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGrouping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1playlist/title",
          "value": "MPMediaGroupingPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1playlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1albumArtist/title",
          "value": "MPMediaGroupingAlbumArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1albumArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingAlbumArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1album/title",
          "value": "MPMediaGroupingAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1title/title",
          "value": "MPMediaGroupingTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1genre/title",
          "value": "MPMediaGroupingGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1artist/title",
          "value": "MPMediaGroupingArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingArtist"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediagrouping/podcasttitle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediagrouping/podcasttitle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
