{
  "abstract": [
    {
      "text": "The postback’s identifier isn’t two, three, or four digits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKAdTestErrorCode@SKAdTestErrorCodeInvalidSourceIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidSourceIdentifier"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKAdTestError.Code.invalidSourceIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidSourceIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A valid postback includes two to four digits of the impression’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdImpression/sourceIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information about the varying length of source identifiers, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/receiving-postbacks-in-multiple-conversion-windows",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/SKAdImpression/sourceIdentifier": {
      "abstract": [
        {
          "text": "A four-digit integer that ad networks define to represent the ad campaign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdImpression/sourceIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceIdentifier",
      "type": "topic",
      "url": "/documentation/StoreKit/SKAdImpression/sourceIdentifier"
    },
    "doc://com.apple.documentation/documentation/StoreKit/receiving-postbacks-in-multiple-conversion-windows": {
      "abstract": [
        {
          "text": "Learn about the data that postbacks may contain in each conversion window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/receiving-postbacks-in-multiple-conversion-windows",
      "kind": "article",
      "role": "article",
      "title": "Receiving postbacks in multiple conversion windows",
      "type": "topic",
      "url": "/documentation/StoreKit/receiving-postbacks-in-multiple-conversion-windows"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId": {
      "abstract": [
        {
          "text": "The impression ID isn’t a valid UUID string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidImpressionId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidImpressionId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidImpressionId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidimpressionid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId": {
      "abstract": [
        {
          "text": "The app ID is less than zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceAppAdamId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidSourceAppAdamId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain": {
      "abstract": [
        {
          "text": "The source domain isn’t in the correct format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceDomain"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidSourceDomain"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier": {
      "abstract": [
        {
          "text": "The postback’s identifier isn’t two, three, or four digits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion": {
      "abstract": [
        {
          "text": "A postback contains an incorrect version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidVersion"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidVersion",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidversion"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeUnknownError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/unknownerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Other-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError"
      ],
      "title": "Other Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdTestErrorCodeInvalidSourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Other-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidVersion",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidImpressionId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unknownError"
              ],
              "title": "Other Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidImpressionId/title",
          "value": "SKAdTestErrorCodeInvalidImpressionId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidImpressionId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidImpressionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unknownError/title",
          "value": "SKAdTestErrorCodeUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceIdentifier/title",
          "value": "SKAdTestErrorCodeInvalidSourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceDomain/title",
          "value": "SKAdTestErrorCodeInvalidSourceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKAdImpression~1sourceIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "sourceIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidVersion/title",
          "value": "SKAdTestErrorCodeInvalidVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceAppAdamId/title",
          "value": "SKAdTestErrorCodeInvalidSourceAppAdamId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidSourceAppAdamId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidSourceAppAdamId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code/invalidsourceidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code/invalidsourceidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
