{
  "abstract": [
    {
      "text": "A non-winning postback is defined with a version prior to version 3, in the testing environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKAdTestErrorCode@SKAdTestErrorCodeInvalidRunnerUpPostback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidRunnerUpPostback"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKAdTestError.Code.invalidRunnerUpPostback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidRunnerUpPostback"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Check that all non-winning postback you create with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " specify version 3 (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") or later. Non-winning postbacks are available starting in version 3. For more information about versions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes": {
      "abstract": [
        {
          "text": "Learn about the features in each SKAdNetwork version.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/skadnetwork-release-notes",
      "kind": "article",
      "role": "article",
      "title": "SKAdNetwork release notes",
      "type": "topic",
      "url": "/documentation/StoreKit/skadnetwork-release-notes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks": {
      "abstract": [
        {
          "text": "Too many postbacks submitted to the test session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excessivePostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeExcessivePostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.excessivePostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/excessivepostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue": {
      "abstract": [
        {
          "text": "The conversion value isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConversionValue"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidConversionValue"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidConversionValue",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidconversionvalue"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL": {
      "abstract": [
        {
          "text": "The URL for the postback isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPostbackURL"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidPostbackURL"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidPostbackURL",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidpostbackurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback": {
      "abstract": [
        {
          "text": "A non-winning postback is defined with a version prior to version 3, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRunnerUpPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidRunnerUpPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidRunnerUpPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidrunneruppostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount": {
      "abstract": [
        {
          "text": "The number of winning postbacks isn’t valid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWinningPostbackCount"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeInvalidWinningPostbackCount"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.invalidWinningPostbackCount",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/invalidwinningpostbackcount"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks": {
      "abstract": [
        {
          "text": "The postback in the testing environment is malformed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malformedPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMalformedPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.malformedPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/malformedpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback": {
      "abstract": [
        {
          "text": "A winning postback wasn’t found in the first position, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "misplacedWinnerPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMisplacedWinnerPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.misplacedWinnerPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/misplacedwinnerpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks": {
      "abstract": [
        {
          "text": "The testing environment doesn’t have any postbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMissingPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.missingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/missingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback": {
      "abstract": [
        {
          "text": "The testing environment is missing a winning postback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingWinningPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMissingWinningPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.missingWinningPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/missingwinningpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks": {
      "abstract": [
        {
          "text": "The test session doesn’t have any pending postbacks to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPendingPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeNoPendingPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.noPendingPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/nopendingpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks": {
      "abstract": [
        {
          "text": "The postbacks aren’t correctly related to one another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlinkedWinningPostbacks"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeUnlinkedWinningPostbacks"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.unlinkedWinningPostbacks",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/unlinkedwinningpostbacks"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback": {
      "abstract": [
        {
          "text": "A test postback that contains ad conversion information in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostback"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestPostback",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)": {
      "abstract": [
        {
          "text": "Creates a test postback for an in-app ad.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adNetworkIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "adCampaignIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "appStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceAppStoreItemIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conversionValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fidelityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isRedownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didWin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "postbackURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostback/init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
        }
      ],
      "role": "symbol",
      "title": "init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostback/init(version:adnetworkidentifier:adcampaignidentifier:appstoreitemidentifier:sourceappstoreitemidentifier:conversionvalue:fidelitytype:isredownload:didwin:postbackurl:)"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0": {
      "abstract": [
        {
          "text": "A constant that represents SKAdNetwork version 3.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SKAdTestPostbackVersion",
          "text": "SKAdTestPostbackVersion"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestPostbackVersion/version3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestPostbackVersion3_0"
        }
      ],
      "role": "symbol",
      "title": "version3_0",
      "type": "topic",
      "url": "/documentation/storekittest/skadtestpostbackversion/version3_0"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Postback-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks"
      ],
      "title": "Postback Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdTestErrorCodeInvalidRunnerUpPostback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Postback-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/misplacedWinnerPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingWinningPostback",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/noPendingPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/unlinkedWinningPostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/excessivePostbacks",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidConversionValue",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidPostbackURL",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/invalidWinningPostbackCount",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/malformedPostbacks"
              ],
              "title": "Postback Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1misplacedWinnerPostback/title",
          "value": "SKAdTestErrorCodeMisplacedWinnerPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1misplacedWinnerPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMisplacedWinnerPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1excessivePostbacks/title",
          "value": "SKAdTestErrorCodeExcessivePostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1excessivePostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeExcessivePostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidWinningPostbackCount/title",
          "value": "SKAdTestErrorCodeInvalidWinningPostbackCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidWinningPostbackCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidWinningPostbackCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidPostbackURL/title",
          "value": "SKAdTestErrorCodeInvalidPostbackURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidPostbackURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidPostbackURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingPostbacks/title",
          "value": "SKAdTestErrorCodeMissingPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMissingPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidRunnerUpPostback/title",
          "value": "SKAdTestErrorCodeInvalidRunnerUpPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidRunnerUpPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidRunnerUpPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version3_0/title",
          "value": "SKAdTestPostbackVersion3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostbackVersion~1version3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostbackVersion3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)/title",
          "value": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback~1init(version:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithVersion:adNetworkIdentifier:adCampaignIdentifier:appStoreItemIdentifier:sourceAppStoreItemIdentifier:conversionValue:fidelityType:isRedownload:didWin:postbackURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/title",
          "value": "SKAdTestPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestPostback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidConversionValue/title",
          "value": "SKAdTestErrorCodeInvalidConversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1invalidConversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeInvalidConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1malformedPostbacks/title",
          "value": "SKAdTestErrorCodeMalformedPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1malformedPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMalformedPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unlinkedWinningPostbacks/title",
          "value": "SKAdTestErrorCodeUnlinkedWinningPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1unlinkedWinningPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeUnlinkedWinningPostbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingWinningPostback/title",
          "value": "SKAdTestErrorCodeMissingWinningPostback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingWinningPostback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMissingWinningPostback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1noPendingPostbacks/title",
          "value": "SKAdTestErrorCodeNoPendingPostbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1noPendingPostbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeNoPendingPostbacks"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code/invalidrunneruppostback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code/invalidrunneruppostback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
