{
  "abstract": [
    {
      "text": "An unknown error occurred with the signature in the testing environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKAdTestErrorCode@SKAdTestErrorCodeSignatureUnknownError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "signatureUnknownError"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKAdTestErrorCodeSignatureUnknownError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKAdTestError.Code.signatureUnknownError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "signatureUnknownError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError": {
      "abstract": [
        {
          "text": "An error the testing environment returns for SKAdNetwork testing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code": {
      "abstract": [
        {
          "text": "Enumerated error codes related to ad network testing in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature": {
      "abstract": [
        {
          "text": "The signature for the ad is missing, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingSignature"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeMissingSignature"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.missingSignature",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/missingsignature"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey": {
      "abstract": [
        {
          "text": "The public key isn’t a valid cryptographic key, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidKey"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureInvalidKey"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureInvalidKey",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureinvalidkey"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder": {
      "abstract": [
        {
          "text": "The order of the parameters in the signature is invalid, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureInvalidOrder"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureInvalidOrder"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureInvalidOrder",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureinvalidorder"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId": {
      "abstract": [
        {
          "text": "The signature is missing an ad network identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAdNetworkId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingAdNetworkId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingAdNetworkId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingadnetworkid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the app item identifier for the advertised app, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingAppAdamId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingAppAdamId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType": {
      "abstract": [
        {
          "text": "The signature is missing the fidelity type, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingFidelityType"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingFidelityType"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingFidelityType",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingfidelitytype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce": {
      "abstract": [
        {
          "text": "The signature is missing the nonce, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingNonce"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingNonce"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingNonce",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingnonce"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId": {
      "abstract": [
        {
          "text": "The signature is missing the source app item identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceAppAdamId"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingSourceAppAdamId"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingSourceAppAdamId",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingsourceappadamid"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain": {
      "abstract": [
        {
          "text": "The signature is missing the source domain, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceDomain"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingSourceDomain"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingSourceDomain",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingsourcedomain"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier": {
      "abstract": [
        {
          "text": "The signature is missing the source identifier, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingSourceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingSourceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingSourceIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingsourceidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp": {
      "abstract": [
        {
          "text": "The signature is missing a timestamp, in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureMissingTimestamp"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureMissingTimestamp"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureMissingTimestamp",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signaturemissingtimestamp"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError": {
      "abstract": [
        {
          "text": "An unknown error occurred with the signature in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureUnknownError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureUnknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureUnknownError"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureUnknownError",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureunknownerror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed": {
      "abstract": [
        {
          "text": "The signature verification failed in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signatureVerificationFailed"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKAdTestErrorCodeSignatureVerificationFailed"
        }
      ],
      "role": "symbol",
      "title": "SKAdTestError.Code.signatureVerificationFailed",
      "type": "topic",
      "url": "/documentation/storekittest/skadtesterror/code/signatureverificationfailed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Signature-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder"
      ],
      "title": "Signature Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKAdTestErrorCodeSignatureUnknownError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Signature-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAdNetworkId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingFidelityType",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingNonce",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceAppAdamId",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceDomain",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingSourceIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureMissingTimestamp",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureVerificationFailed",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/missingSignature",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidKey",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKAdTestError/Code/signatureInvalidOrder"
              ],
              "title": "Signature Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKAdTestErrorCodeSignatureUnknownError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceIdentifier/title",
          "value": "SKAdTestErrorCodeSignatureMissingSourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingFidelityType/title",
          "value": "SKAdTestErrorCodeSignatureMissingFidelityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingFidelityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingFidelityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingTimestamp/title",
          "value": "SKAdTestErrorCodeSignatureMissingTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAdNetworkId/title",
          "value": "SKAdTestErrorCodeSignatureMissingAdNetworkId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAdNetworkId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingAdNetworkId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/title",
          "value": "SKAdTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceDomain/title",
          "value": "SKAdTestErrorCodeSignatureMissingSourceDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingSourceDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceAppAdamId/title",
          "value": "SKAdTestErrorCodeSignatureMissingSourceAppAdamId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingSourceAppAdamId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingSourceAppAdamId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureUnknownError/title",
          "value": "SKAdTestErrorCodeSignatureUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureUnknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureVerificationFailed/title",
          "value": "SKAdTestErrorCodeSignatureVerificationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureVerificationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureVerificationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidKey/title",
          "value": "SKAdTestErrorCodeSignatureInvalidKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureInvalidKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAppAdamId/title",
          "value": "SKAdTestErrorCodeSignatureMissingAppAdamId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingAppAdamId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingAppAdamId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidOrder/title",
          "value": "SKAdTestErrorCodeSignatureInvalidOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureInvalidOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureInvalidOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingSignature/title",
          "value": "SKAdTestErrorCodeMissingSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1missingSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeMissingSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingNonce/title",
          "value": "SKAdTestErrorCodeSignatureMissingNonce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKAdTestError~1Code~1signatureMissingNonce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKAdTestErrorCodeSignatureMissingNonce"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code/signatureunknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/skadtesterror/code/signatureunknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
