{
  "abstract": [
    {
      "text": "A structure to update the attributed title when the button state changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButton",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleTextAttributesTransformer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So8UIButtonC5UIKitE13ConfigurationV30titleTextAttributesTransformerAC015UIConfigurationefG0VSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "titleTextAttributesTransformer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit40UIConfigurationTextAttributesTransformerV",
        "text": "UIConfigurationTextAttributesTransformer"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "titleTextAttributesTransformer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "titleTextAttributesTransformer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit40UIConfigurationTextAttributesTransformerV",
              "text": "UIConfigurationTextAttributesTransformer"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/TitleAlignment-swift.enum": {
      "abstract": [
        {
          "text": "Specifies how to align a button’s title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TitleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/TitleAlignment-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TitleAlignment"
        }
      ],
      "role": "symbol",
      "title": "UIButton.Configuration.TitleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlealignment-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedSubtitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s subtitle label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedSubtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation16AttributedStringV",
          "text": "AttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedSubtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedSubtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/attributedsubtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedTitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s title label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation16AttributedStringV",
          "text": "AttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedTitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedTitle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/attributedtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitle": {
      "abstract": [
        {
          "text": "The text the subtitle label of the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/subtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleLineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/subtitlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A structure to update the attributed subtitle when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit40UIConfigurationTextAttributesTransformerV",
          "text": "UIConfigurationTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/subtitletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/title": {
      "abstract": [
        {
          "text": "The text of the title label the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/title",
      "kind": "symbol",
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleAlignment-swift.property": {
      "abstract": [
        {
          "text": "The text alignment the button uses to lay out the title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV14TitleAlignmentO",
          "text": "TitleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleAlignment-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlealignment-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleLineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titlePadding": {
      "abstract": [
        {
          "text": "The distance between the title and subtitle labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titlePadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titlePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "titlePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titlepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A structure to update the attributed title when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit40UIConfigurationTextAttributesTransformerV",
          "text": "UIConfigurationTextAttributesTransformer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configuration-swift.struct/titletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct": {
      "abstract": [
        {
          "text": "Defines a text transformation that can affect the visual appearance of a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationTextAttributesTransformer"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationtextattributestransformer-swift.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-titles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/title",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedTitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/attributedSubtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titlePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleAlignment-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/TitleAlignment-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/titleLineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/Configuration-swift.struct/subtitleLineBreakMode"
      ],
      "title": "Configuring titles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton/configuration-swift.struct/titletextattributestransformer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
