{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedMatrix4x4"]]},"metadata":{"externalID":"c:objc(cs)MDLAnimatedMatrix4x4(im)resetWithFloat4x4Array:atTimes:count:","navigatorTitle":[{"text":"resetWithFloat4x4Array:atTimes:count:","kind":"identifier"}],"platforms":[{"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"10.13","deprecated":false,"unavailable":false,"name":"macOS","beta":false},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS","beta":false}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"resetWithFloat4x4Array:atTimes:count:","kind":"identifier"}],"modules":[{"name":"Model I/O"}],"title":"resetWithFloat4x4Array:atTimes:count:"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlanimatedmatrix4x4/resetwithfloat4x4array:attimes:count:"]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedMatrix4x4/resetWithFloat4x4Array:atTimes:count:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resetWithFloat4x4Array:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@matrix_float4x4","kind":"typeIdentifier","text":"matrix_float4x4","preciseIdentifier":"c:@T@matrix_float4x4"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"valuesArray"},{"kind":"text","text":" "},{"kind":"identifier","text":"atTimes:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSTimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timesArray"},{"kind":"text","text":" "},{"kind":"identifier","text":"count:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"count"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedMatrix4x4/resetWithFloat4x4Array:atTimes:count:":{"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetWithFloat4x4Array:atTimes:count:"}],"navigatorTitle":[{"kind":"identifier","text":"resetWithFloat4x4Array:atTimes:count:"}],"type":"topic","url":"/documentation/modelio/mdlanimatedmatrix4x4/resetwithfloat4x4array:attimes:count:","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedMatrix4x4/resetWithFloat4x4Array:atTimes:count:","title":"resetWithFloat4x4Array:atTimes:count:","abstract":[]},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","url":"/documentation/objectivec/nsuinteger","abstract":[{"type":"text","text":"Describes an unsigned integer."}],"type":"topic","role":"symbol","kind":"symbol","title":"NSUInteger"},"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval":{"role":"symbol","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"TimeInterval"}],"type":"topic","title":"TimeInterval","abstract":[{"type":"text","text":"A number of seconds."}],"url":"/documentation/foundation/timeinterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedMatrix4x4":{"url":"/documentation/modelio/mdlanimatedmatrix4x4","title":"MDLAnimatedMatrix4x4","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAnimatedMatrix4x4","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MDLAnimatedMatrix4x4","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAnimatedMatrix4x4","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@matrix_float4x4":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@matrix_float4x4","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matrix_float4x4","kind":"identifier"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"simd_float4x4","preciseIdentifier":"c:@SA@simd_float4x4"}],"abstract":[{"type":"text","text":"A type alias for a single-precision 4 x 4 matrix."}],"title":"matrix_float4x4","url":"/documentation/simd/matrix_float4x4"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"}},"variantOverrides":[{"patch":[{"value":"NSTimeInterval","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title","op":"replace"},{"value":"MDLAnimatedMatrix4x4","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedMatrix4x4/title","op":"replace"},{"op":"replace","value":[{"text":"MDLAnimatedMatrix4x4","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedMatrix4x4/fragments"},{"op":"replace","value":[{"text":"MDLAnimatedMatrix4x4","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAnimatedMatrix4x4/navigatorTitle"},{"op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simd_float4x4","kind":"typeIdentifier","preciseIdentifier":"c:@SA@simd_float4x4"},{"text":" ","kind":"text"},{"text":"matrix_float4x4","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@matrix_float4x4/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}