{
  "abstract": [
    {
      "text": "The possible errors returned by a GATT server (a remote peripheral) during Bluetooth low energy ATT transactions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CBATTError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CBATTError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These error constants derive from the Bluetooth ATT error codes, defined in the Bluetooth 4.0 specification. For more information, see the Bluetooth 4.0 specification, Volume 3, Part F, Section 3.4.1.1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns while using Attribute Protocol (ATT).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBATTError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTError"
        }
      ],
      "role": "symbol",
      "title": "CBATTError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The possible errors returned by a GATT server (a remote peripheral) during Bluetooth low energy ATT transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotFound": {
      "abstract": [
        {
          "text": "The attribute wasn’t found within the specified attribute handle range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeNotFound"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorAttributeNotFound"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.attributeNotFound",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/attributenotfound"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotLong": {
      "abstract": [
        {
          "text": "The ATT read blob request can’t read or write the attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeNotLong"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotLong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorAttributeNotLong"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.attributeNotLong",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/attributenotlong"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthentication": {
      "abstract": [
        {
          "text": "Reading or writing the attribute’s value failed for lack of authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientAuthentication"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInsufficientAuthentication"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.insufficientAuthentication",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/insufficientauthentication"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthorization": {
      "abstract": [
        {
          "text": "Reading or writing the attribute’s value failed for lack of authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientAuthorization"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInsufficientAuthorization"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.insufficientAuthorization",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/insufficientauthorization"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryption": {
      "abstract": [
        {
          "text": "Reading or writing the attribute’s value failed for lack of encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientEncryption"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInsufficientEncryption"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.insufficientEncryption",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/insufficientencryption"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryptionKeySize": {
      "abstract": [
        {
          "text": "The encryption key size used for encrypting this link is insufficient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientEncryptionKeySize"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryptionKeySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInsufficientEncryptionKeySize"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.insufficientEncryptionKeySize",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/insufficientencryptionkeysize"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientResources": {
      "abstract": [
        {
          "text": "Resources are insufficient to complete the ATT request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientResources"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInsufficientResources"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.insufficientResources",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/insufficientresources"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidAttributeValueLength": {
      "abstract": [
        {
          "text": "The length of the attribute’s value is invalid for the intended operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAttributeValueLength"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidAttributeValueLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInvalidAttributeValueLength"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.invalidAttributeValueLength",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/invalidattributevaluelength"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidHandle": {
      "abstract": [
        {
          "text": "The attribute handle is invalid on this peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInvalidHandle"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.invalidHandle",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/invalidhandle"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidOffset": {
      "abstract": [
        {
          "text": "The specified offset value was past the end of the attribute’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOffset"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInvalidOffset"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.invalidOffset",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/invalidoffset"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidPdu": {
      "abstract": [
        {
          "text": "The attribute Protocol Data Unit (PDU) is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPdu"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidPdu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorInvalidPdu"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.invalidPdu",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/invalidpdu"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/prepareQueueFull": {
      "abstract": [
        {
          "text": "The prepare queue is full, as a result of there being too many write requests in the queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareQueueFull"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/prepareQueueFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorPrepareQueueFull"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.prepareQueueFull",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/preparequeuefull"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/readNotPermitted": {
      "abstract": [
        {
          "text": "The permissions prohibit reading the attribute’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readNotPermitted"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/readNotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorReadNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.readNotPermitted",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/readnotpermitted"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/requestNotSupported": {
      "abstract": [
        {
          "text": "The attribute server doesn’t support the request received from the client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestNotSupported"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/requestNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorRequestNotSupported"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.requestNotSupported",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/requestnotsupported"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/success": {
      "abstract": [
        {
          "text": "The ATT command or request successfully completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorSuccess"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.success",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/success"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unlikelyError": {
      "abstract": [
        {
          "text": "The ATT request encountered an unlikely error and wasn’t completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlikelyError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unlikelyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorUnlikelyError"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.unlikelyError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/unlikelyerror"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unsupportedGroupType": {
      "abstract": [
        {
          "text": "The attribute type isn’t a supported grouping attribute as defined by a higher-layer specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedGroupType"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unsupportedGroupType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorUnsupportedGroupType"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.unsupportedGroupType",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/unsupportedgrouptype"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/writeNotPermitted": {
      "abstract": [
        {
          "text": "The permissions prohibit writing the attribute’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeNotPermitted"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/writeNotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorWriteNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code.writeNotPermitted",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code/writenotpermitted"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Bluetooth ATT errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBATTErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CBATTErrorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterrordomain"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "role": "symbol",
      "title": "CBError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The codes for errors that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Bluetooth errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CBErrorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/success",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidHandle",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/readNotPermitted",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/writeNotPermitted",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidPdu",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthentication",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/requestNotSupported",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidOffset",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthorization",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/prepareQueueFull",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotFound",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotLong",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryptionKeySize",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidAttributeValueLength",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unlikelyError",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryption",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unsupportedGroupType",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientResources"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBATTError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/success",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidHandle",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/readNotPermitted",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/writeNotPermitted",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidPdu",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthentication",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/requestNotSupported",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidOffset",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientAuthorization",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/prepareQueueFull",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotFound",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/attributeNotLong",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryptionKeySize",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/invalidAttributeValueLength",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unlikelyError",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientEncryption",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/unsupportedGroupType",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code/insufficientResources"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBATTError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1attributeNotFound/title",
          "value": "CBATTErrorAttributeNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1attributeNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorAttributeNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidOffset/title",
          "value": "CBATTErrorInvalidOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInvalidOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1unsupportedGroupType/title",
          "value": "CBATTErrorUnsupportedGroupType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1unsupportedGroupType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorUnsupportedGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1unlikelyError/title",
          "value": "CBATTErrorUnlikelyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1unlikelyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorUnlikelyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1attributeNotLong/title",
          "value": "CBATTErrorAttributeNotLong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1attributeNotLong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorAttributeNotLong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1prepareQueueFull/title",
          "value": "CBATTErrorPrepareQueueFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1prepareQueueFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorPrepareQueueFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title",
          "value": "CBError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/title",
          "value": "CBATTError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidHandle/title",
          "value": "CBATTErrorInvalidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInvalidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidAttributeValueLength/title",
          "value": "CBATTErrorInvalidAttributeValueLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidAttributeValueLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInvalidAttributeValueLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1writeNotPermitted/title",
          "value": "CBATTErrorWriteNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1writeNotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorWriteNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1requestNotSupported/title",
          "value": "CBATTErrorRequestNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1requestNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorRequestNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1readNotPermitted/title",
          "value": "CBATTErrorReadNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1readNotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorReadNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1success/title",
          "value": "CBATTErrorSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientResources/title",
          "value": "CBATTErrorInsufficientResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInsufficientResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientEncryptionKeySize/title",
          "value": "CBATTErrorInsufficientEncryptionKeySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientEncryptionKeySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInsufficientEncryptionKeySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBErrorDomain/title",
          "value": "CBErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTErrorDomain/title",
          "value": "CBATTErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientEncryption/title",
          "value": "CBATTErrorInsufficientEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInsufficientEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidPdu/title",
          "value": "CBATTErrorInvalidPdu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1invalidPdu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInvalidPdu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientAuthentication/title",
          "value": "CBATTErrorInsufficientAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInsufficientAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientAuthorization/title",
          "value": "CBATTErrorInsufficientAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code~1insufficientAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorInsufficientAuthorization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbatterror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbatterror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
