{
  "abstract": [
    {
      "text": "The rules the system satisfies when generating a strong password for your extension during an automatic upgrade.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.ASAccountAuthenticationModificationPasswordGenerationRequirements",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "ASAccountAuthenticationModificationPasswordGenerationRequirements",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the format and content of this value, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/customizing-password-autofill-rules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements": {
      "abstract": [
        {
          "text": "The rules the system satisfies when generating a strong password for your extension during an automatic upgrade.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationPasswordGenerationRequirements",
      "kind": "symbol",
      "name": "ASAccountAuthenticationModificationPasswordGenerationRequirements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
        }
      ],
      "role": "symbol",
      "title": "ASAccountAuthenticationModificationPasswordGenerationRequirements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationpasswordgenerationrequirements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the extension supports upgrading a user’s password to a strong password.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange",
      "kind": "symbol",
      "name": "ASAccountAuthenticationModificationSupportsStrongPasswordChange",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccountAuthenticationModificationSupportsStrongPasswordChange"
        }
      ],
      "role": "symbol",
      "title": "ASAccountAuthenticationModificationSupportsStrongPasswordChange",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationsupportsstrongpasswordchange"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the extension supports upgrading from using password authentication to using Sign in with Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple",
      "kind": "symbol",
      "name": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
        }
      ],
      "role": "symbol",
      "title": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationsupportsupgradetosigninwithapple"
    },
    "doc://com.apple.documentation/documentation/Security/customizing-password-autofill-rules": {
      "abstract": [
        {
          "text": "Modify the strong password rules for your app by adding your own restrictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/customizing-password-autofill-rules",
      "kind": "article",
      "role": "article",
      "title": "Customizing Password AutoFill rules",
      "type": "topic",
      "url": "/documentation/Security/customizing-password-autofill-rules"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authentication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
      ],
      "title": "Authentication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Authentication",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsStrongPasswordChange",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
              ],
              "title": "Authentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationPasswordGenerationRequirements/title",
          "value": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationPasswordGenerationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationPasswordGenerationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple/title",
          "value": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationSupportsUpgradeToSignInWithApple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsStrongPasswordChange/title",
          "value": "ASAccountAuthenticationModificationSupportsStrongPasswordChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ASAccountAuthenticationModificationSupportsStrongPasswordChange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccountAuthenticationModificationSupportsStrongPasswordChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationpasswordgenerationrequirements"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/asaccountauthenticationmodificationpasswordgenerationrequirements"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
