{
  "abstract": [
    {
      "text": "The custom actions for a File Provider extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionFileProviderActions",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtensionFileProviderActions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSExtensionFileProviderActions"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtensionFileProviderActions",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions": {
      "abstract": [
        {
          "text": "The custom actions for a File Provider extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions",
      "kind": "symbol",
      "name": "NSExtensionFileProviderActions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderActions"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderActions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionActivationRule": {
      "abstract": [
        {
          "text": "A predicate that determines whether a File Provider extension action appears in the context menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionActivationRule",
      "kind": "symbol",
      "name": "NSExtensionFileProviderActionActivationRule",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderActionActivationRule"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderActionActivationRule",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions/nsextensionfileprovideractionactivationrule"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a File Provider extension action.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionIdentifier",
      "kind": "symbol",
      "name": "NSExtensionFileProviderActionIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderActionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderActionIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions/nsextensionfileprovideractionidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionName": {
      "abstract": [
        {
          "text": "The localized name for a File Provider extension action that appears in the context menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionName",
      "kind": "symbol",
      "name": "NSExtensionFileProviderActionName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderActionName"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderActionName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions/nsextensionfileprovideractionname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup": {
      "abstract": [
        {
          "text": "The identifier of a shared container that can be accessed by a Document Picker extension and its associated File Provider extension.",
          "type": "text"
        }
      ],
      "ideTitle": "App group used for document storage",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup",
      "kind": "symbol",
      "name": "NSExtensionFileProviderDocumentGroup",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderDocumentGroup"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderDocumentGroup",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileproviderdocumentgroup"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth": {
      "abstract": [
        {
          "text": "The per-domain limit of concurrent calls that a file provider extension can make to fetch data from remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth",
      "kind": "symbol",
      "name": "NSExtensionFileProviderDownloadPipelineDepth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderDownloadPipelineDepth"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderDownloadPipelineDepth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileproviderdownloadpipelinedepth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a File Provider extension enumerates its content.",
          "type": "text"
        }
      ],
      "ideTitle": "File Provider supports Enumeration",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration",
      "kind": "symbol",
      "name": "NSExtensionFileProviderSupportsEnumeration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderSupportsEnumeration"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderSupportsEnumeration",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovidersupportsenumeration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth": {
      "abstract": [
        {
          "text": "The per-domain limit of concurrent calls that a file provider extension can make to upload data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth",
      "kind": "symbol",
      "name": "NSExtensionFileProviderUploadPipelineDepth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionFileProviderUploadPipelineDepth"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionFileProviderUploadPipelineDepth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideruploadpipelinedepth"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-Provider",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth"
      ],
      "title": "File Provider"
    }
  ],
  "topicSections": [
    {
      "anchor": "Action-Configuration",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionActivationRule",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionName"
      ],
      "title": "Action Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtensionFileProviderActions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Action-Configuration",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionActivationRule",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderActions/NSExtensionFileProviderActionName"
              ],
              "title": "Action Configuration"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-Provider",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDocumentGroup",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderSupportsEnumeration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderDownloadPipelineDepth",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionFileProviderUploadPipelineDepth"
              ],
              "title": "File Provider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions~1NSExtensionFileProviderActionActivationRule/title",
          "value": "NSExtensionFileProviderActionActivationRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions~1NSExtensionFileProviderActionActivationRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderActionActivationRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDownloadPipelineDepth/title",
          "value": "NSExtensionFileProviderDownloadPipelineDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDownloadPipelineDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderDownloadPipelineDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions/title",
          "value": "NSExtensionFileProviderActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderUploadPipelineDepth/title",
          "value": "NSExtensionFileProviderUploadPipelineDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderUploadPipelineDepth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderUploadPipelineDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDocumentGroup/title",
          "value": "NSExtensionFileProviderDocumentGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderDocumentGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderDocumentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions~1NSExtensionFileProviderActionName/title",
          "value": "NSExtensionFileProviderActionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions~1NSExtensionFileProviderActionName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderActionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions~1NSExtensionFileProviderActionIdentifier/title",
          "value": "NSExtensionFileProviderActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderActions~1NSExtensionFileProviderActionIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderSupportsEnumeration/title",
          "value": "NSExtensionFileProviderSupportsEnumeration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionFileProviderSupportsEnumeration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionFileProviderSupportsEnumeration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionfileprovideractions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
