{
  "abstract": [
    {
      "text": "The extension point that supports an app extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionPointIdentifier",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtensionPointIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "NSExtensionPointIdentifier"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtensionPointIdentifier",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "com.apple.authentication-services-account-authentication-modification-ui"
        },
        {
          "content": [],
          "name": "com.apple.ui-services"
        },
        {
          "content": [],
          "name": "com.apple.services"
        },
        {
          "content": [],
          "name": "com.apple.AudioUnit-UI"
        },
        {
          "content": [],
          "name": "com.apple.AppSSO.idp-extension"
        },
        {
          "content": [],
          "name": "com.apple.authentication-services-credential-provider-ui"
        },
        {
          "content": [],
          "name": "com.apple.broadcast-services-setupui"
        },
        {
          "content": [],
          "name": "com.apple.broadcast-services-upload"
        },
        {
          "content": [],
          "name": "com.apple.callkit.call-directory"
        },
        {
          "content": [],
          "name": "com.apple.classkit.context-provider"
        },
        {
          "content": [],
          "name": "com.apple.Safari.content-blocker"
        },
        {
          "content": [],
          "name": "com.apple.keyboard-service"
        },
        {
          "content": [],
          "name": "com.apple.fileprovider-nonui"
        },
        {
          "content": [],
          "name": "com.apple.fileprovider-actionsui"
        },
        {
          "content": [],
          "name": "com.apple.FinderSync"
        },
        {
          "content": [],
          "name": "com.apple.intents-service"
        },
        {
          "content": [],
          "name": "com.apple.intents-ui-service"
        },
        {
          "content": [],
          "name": "com.apple.identitylookup.message-filter"
        },
        {
          "content": [],
          "name": "com.apple.networkextension.app-proxy"
        },
        {
          "content": [],
          "name": "com.apple.usernotifications.content-extension"
        },
        {
          "content": [],
          "name": "com.apple.usernotifications.service"
        },
        {
          "content": [],
          "name": "com.apple.ctk-tokens"
        },
        {
          "content": [],
          "name": "com.apple.photo-editing"
        },
        {
          "content": [],
          "name": "com.apple.photo-project"
        },
        {
          "content": [],
          "name": "com.apple.quicklook.preview"
        },
        {
          "content": [],
          "name": "com.apple.Safari.extension"
        },
        {
          "content": [],
          "name": "com.apple.share-services"
        },
        {
          "content": [],
          "name": "com.apple.ctk-tokens"
        },
        {
          "content": [],
          "name": "com.apple.spotlight.index"
        },
        {
          "content": [],
          "name": "com.apple.message-payload-provider"
        },
        {
          "content": [],
          "name": "com.apple.quicklook.thumbnail"
        },
        {
          "content": [],
          "name": "com.apple.tv-top-shelf"
        },
        {
          "content": [],
          "name": "com.apple.identitylookup.classification-ui"
        },
        {
          "content": [],
          "name": "com.apple.widgetkit-extension"
        },
        {
          "content": [],
          "name": "com.apple.dt.Xcode.extension.source-editor"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Action extension is presented in full screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
      "kind": "symbol",
      "name": "NSExtensionActionWantsFullScreenPresentation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActionWantsFullScreenPresentation"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActionWantsFullScreenPresentation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionactionwantsfullscreenpresentation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard": {
      "abstract": [
        {
          "text": "The name of the app extension’s main storyboard file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
      "kind": "symbol",
      "name": "NSExtensionMainStoryboard",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionMainStoryboard"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionMainStoryboard",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionmainstoryboard"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app extension ignores appearance changes made by the host app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
      "kind": "symbol",
      "name": "NSExtensionOverridesHostUIAppearance",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionOverridesHostUIAppearance"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionOverridesHostUIAppearance",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionoverrideshostuiappearance"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier": {
      "abstract": [
        {
          "text": "The extension point that supports an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
      "kind": "symbol",
      "name": "NSExtensionPointIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPointIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPointIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionpointidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The custom class that implements an app extension’s primary view or functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
      "kind": "symbol",
      "name": "NSExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionprincipalclass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Appearance-and-Presentation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass"
      ],
      "title": "Appearance and Presentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtensionPointIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPointIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Appearance-and-Presentation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass"
              ],
              "title": "Appearance and Presentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/title",
          "value": "NSExtensionPointIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPointIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/title",
          "value": "NSExtensionMainStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionMainStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/title",
          "value": "NSExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/title",
          "value": "NSExtensionActionWantsFullScreenPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActionWantsFullScreenPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/title",
          "value": "NSExtensionOverridesHostUIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionOverridesHostUIAppearance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionpointidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionpointidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
