{
  "abstract": [
    {
      "text": "Properties of an app extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.NSExtensionAttributes",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExtensionAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "NSExtensionAttributes"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "NSExtensionAttributes",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported": {
      "abstract": [
        {
          "text": "The names of the intents that an extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported",
      "kind": "symbol",
      "name": "IntentsSupported",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntentsSupported"
        }
      ],
      "role": "symbol",
      "title": "IntentsSupported",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/intentssupported"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Action extension is presented in full screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
      "kind": "symbol",
      "name": "NSExtensionActionWantsFullScreenPresentation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActionWantsFullScreenPresentation"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActionWantsFullScreenPresentation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionactionwantsfullscreenpresentation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes": {
      "abstract": [
        {
          "text": "Properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes",
      "kind": "symbol",
      "name": "NSExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities": {
      "abstract": [
        {
          "text": "The credential types supported by a credential provider extension, and whether it presents a user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities",
      "kind": "symbol",
      "name": "ASCredentialProviderExtensionCapabilities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASCredentialProviderExtensionCapabilities"
        }
      ],
      "role": "symbol",
      "title": "ASCredentialProviderExtensionCapabilities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/ascredentialproviderextensioncapabilities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/CSSupportedContentTypes": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/CSSupportedContentTypes",
      "kind": "symbol",
      "name": "CSSupportedContentTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSupportedContentTypes"
        }
      ],
      "role": "symbol",
      "title": "CSSupportedContentTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/cssupportedcontenttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL": {
      "abstract": [
        {
          "text": "The server that a Message Filter app extension may defer a query to.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL",
      "kind": "symbol",
      "name": "IDMessageFilterExtensionNetworkURL",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IDMessageFilterExtensionNetworkURL"
        }
      ],
      "role": "symbol",
      "title": "IDMessageFilterExtensionNetworkURL",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/idmessagefilterextensionnetworkurl"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination": {
      "abstract": [
        {
          "text": "The phone number that receives SMS messages when the user reports an SMS message or a call.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination",
      "kind": "symbol",
      "name": "ILClassificationExtensionSMSReportDestination",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILClassificationExtensionSMSReportDestination"
        }
      ],
      "role": "symbol",
      "title": "ILClassificationExtensionSMSReportDestination",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/ilclassificationextensionsmsreportdestination"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a custom keyboard displays standard ASCII characters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable",
      "kind": "symbol",
      "name": "IsASCIICapable",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IsASCIICapable"
        }
      ],
      "role": "symbol",
      "title": "IsASCIICapable",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/isasciicapable"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEComposeSession": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEComposeSession",
      "kind": "symbol",
      "name": "MEComposeSession",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEComposeSession"
        }
      ],
      "role": "symbol",
      "title": "MEComposeSession",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/mecomposesession"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities",
      "kind": "symbol",
      "name": "MEExtensionCapabilities",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEExtensionCapabilities"
        }
      ],
      "role": "symbol",
      "title": "MEExtensionCapabilities",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/meextensioncapabilities"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages": {
      "abstract": [
        {
          "text": "The contexts that an iMessage app or sticker pack supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages",
      "kind": "symbol",
      "name": "MSMessagesAppPresentationContextMessages",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContextMessages"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationContextMessages",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/msmessagesapppresentationcontextmessages"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule": {
      "abstract": [
        {
          "text": "The semantic data types that a Share or Action extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule",
      "kind": "symbol",
      "name": "NSExtensionActivationRule",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionActivationRule"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionActivationRule",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionactivationrule"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile": {
      "abstract": [
        {
          "text": "The name of a JavaScript file supplied by a Share or Action extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile",
      "kind": "symbol",
      "name": "NSExtensionJavaScriptPreprocessingFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionJavaScriptPreprocessingFile"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionJavaScriptPreprocessingFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionjavascriptpreprocessingfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the extension appears in the Finder Preview pane and Quick Actions menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem",
      "kind": "symbol",
      "name": "NSExtensionServiceAllowsFinderPreviewItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceAllowsFinderPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceAllowsFinderPreviewItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionserviceallowsfinderpreviewitem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether an Action extension displays an item in a window’s toolbar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem",
      "kind": "symbol",
      "name": "NSExtensionServiceAllowsToolbarItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceAllowsToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceAllowsToolbarItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionserviceallowstoolbaritem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the extension appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
      "kind": "symbol",
      "name": "NSExtensionServiceAllowsTouchBarItem",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceAllowsTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceAllowsTouchBarItem",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionserviceallowstouchbaritem"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName": {
      "abstract": [
        {
          "text": "The name of an icon for display when the extension appears in the Finder Preview pane and Quick Actions menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName",
      "kind": "symbol",
      "name": "NSExtensionServiceFinderPreviewIconName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceFinderPreviewIconName"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceFinderPreviewIconName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicefinderpreviewiconname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel": {
      "abstract": [
        {
          "text": "A name for display when the extension appears in the Finder Preview pane and Quick Actions menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel",
      "kind": "symbol",
      "name": "NSExtensionServiceFinderPreviewLabel",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceFinderPreviewLabel"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceFinderPreviewLabel",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicefinderpreviewlabel"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceRoleType": {
      "abstract": [
        {
          "text": "The type of task an Action extension performs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceRoleType",
      "kind": "symbol",
      "name": "NSExtensionServiceRoleType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceRoleType"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceRoleType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionserviceroletype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile": {
      "abstract": [
        {
          "text": "The image for an Action extension’s toolbar item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile",
      "kind": "symbol",
      "name": "NSExtensionServiceToolbarIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceToolbarIconFile"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceToolbarIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetoolbariconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel": {
      "abstract": [
        {
          "text": "The label for an Action extension’s toolbar item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel",
      "kind": "symbol",
      "name": "NSExtensionServiceToolbarPaletteLabel",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceToolbarPaletteLabel"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceToolbarPaletteLabel",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetoolbarpalettelabel"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName": {
      "abstract": [
        {
          "text": "The color to use for the bezel around the extension when it appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
      "kind": "symbol",
      "name": "NSExtensionServiceTouchBarBezelColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceTouchBarBezelColorName"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarBezelColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbarbezelcolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName": {
      "abstract": [
        {
          "text": "The name of an icon for display when the extension appears as a Quick Action in the Touch Bar",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
      "kind": "symbol",
      "name": "NSExtensionServiceTouchBarIconName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceTouchBarIconName"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarIconName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbariconname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel": {
      "abstract": [
        {
          "text": "A name for display when the extension appears as a Quick Action in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel",
      "kind": "symbol",
      "name": "NSExtensionServiceTouchBarLabel",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionServiceTouchBarLabel"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionServiceTouchBarLabel",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/nsextensionservicetouchbarlabel"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the Photos app gets a list of supported project types from an extension.",
          "type": "text"
        }
      ],
      "ideTitle": "Extension defines custom project types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes",
      "kind": "symbol",
      "name": "PHProjectExtensionDefinesProjectTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectExtensionDefinesProjectTypes"
        }
      ],
      "role": "symbol",
      "title": "PHProjectExtensionDefinesProjectTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/phprojectextensiondefinesprojecttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes": {
      "abstract": [
        {
          "text": "The types of assets a Photo Editing extension can edit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes",
      "kind": "symbol",
      "name": "PHSupportedMediaTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHSupportedMediaTypes"
        }
      ],
      "role": "symbol",
      "title": "PHSupportedMediaTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/phsupportedmediatypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a keyboard extension supports right-to-left languages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft",
      "kind": "symbol",
      "name": "PrefersRightToLeft",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrefersRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "PrefersRightToLeft",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/prefersrighttoleft"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage": {
      "abstract": [
        {
          "text": "The primary language for a keyboard extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage",
      "kind": "symbol",
      "name": "PrimaryLanguage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PrimaryLanguage"
        }
      ],
      "role": "symbol",
      "title": "PrimaryLanguage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/primarylanguage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a custom keyboard uses a shared container and accesses the network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess",
      "kind": "symbol",
      "name": "RequestsOpenAccess",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RequestsOpenAccess"
        }
      ],
      "role": "symbol",
      "title": "RequestsOpenAccess",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/requestsopenaccess"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/SupportedMediaCategories": {
      "abstract": [
        {
          "text": "Types of media supported by an app extension’s media-playing intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/SupportedMediaCategories",
      "kind": "symbol",
      "name": "SupportedMediaCategories",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SupportedMediaCategories"
        }
      ],
      "role": "symbol",
      "title": "SupportedMediaCategories",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/supportedmediacategories"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes": {
      "abstract": [
        {
          "text": "The modes that a Document Picker extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes",
      "kind": "symbol",
      "name": "UIDocumentPickerModes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerModes"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerModes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/uidocumentpickermodes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes": {
      "abstract": [
        {
          "text": "The Uniform Type Identifiers that a document picker extension supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes",
      "kind": "symbol",
      "name": "UIDocumentPickerSupportedFileTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerSupportedFileTypes"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerSupportedFileTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/uidocumentpickersupportedfiletypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory": {
      "abstract": [
        {
          "text": "The identifier of a category declared by the app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory",
      "kind": "symbol",
      "name": "UNNotificationExtensionCategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionCategory"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionCategory",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensioncategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether only the app extension’s custom view controller is displayed in the notification interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden",
      "kind": "symbol",
      "name": "UNNotificationExtensionDefaultContentHidden",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionDefaultContentHidden"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionDefaultContentHidden",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensiondefaultcontenthidden"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio": {
      "abstract": [
        {
          "text": "The initial size of the view controller’s view for an app extension, expressed as a ratio of its height to its width.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio",
      "kind": "symbol",
      "name": "UNNotificationExtensionInitialContentSizeRatio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionInitialContentSizeRatio"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionInitialContentSizeRatio",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensioninitialcontentsizeratio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the title of the app extension’s view controller is used as the title of the notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle",
      "kind": "symbol",
      "name": "UNNotificationExtensionOverridesDefaultTitle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionOverridesDefaultTitle"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionOverridesDefaultTitle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensionoverridesdefaulttitle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether user interactions in a custom notification are enabled.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled",
      "kind": "symbol",
      "name": "UNNotificationExtensionUserInteractionEnabled",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationExtensionUserInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationExtensionUserInteractionEnabled",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes/unnotificationextensionuserinteractionenabled"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard": {
      "abstract": [
        {
          "text": "The name of the app extension’s main storyboard file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
      "kind": "symbol",
      "name": "NSExtensionMainStoryboard",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionMainStoryboard"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionMainStoryboard",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionmainstoryboard"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app extension ignores appearance changes made by the host app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
      "kind": "symbol",
      "name": "NSExtensionOverridesHostUIAppearance",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionOverridesHostUIAppearance"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionOverridesHostUIAppearance",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionoverrideshostuiappearance"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier": {
      "abstract": [
        {
          "text": "The extension point that supports an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
      "kind": "symbol",
      "name": "NSExtensionPointIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPointIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPointIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionpointidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The custom class that implements an app extension’s primary view or functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
      "kind": "symbol",
      "name": "NSExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "NSExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/nsextensionprincipalclass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Appearance-and-Presentation",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile"
      ],
      "title": "Appearance and Presentation"
    },
    {
      "anchor": "Core-Spotlight",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/CSSupportedContentTypes"
      ],
      "title": "Core Spotlight"
    },
    {
      "anchor": "Credential-providers",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities"
      ],
      "title": "Credential providers"
    },
    {
      "anchor": "Intents",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/SupportedMediaCategories"
      ],
      "title": "Intents"
    },
    {
      "anchor": "Mail",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEComposeSession",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities"
      ],
      "title": "Mail"
    },
    {
      "anchor": "Photos",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes"
      ],
      "title": "Photos"
    },
    {
      "anchor": "Quick-Actions",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceRoleType"
      ],
      "title": "Quick Actions"
    },
    {
      "anchor": "Toolbar",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel"
      ],
      "title": "Toolbar"
    },
    {
      "anchor": "Touch-Bar",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel"
      ],
      "title": "Touch Bar"
    },
    {
      "anchor": "UIKit",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled"
      ],
      "title": "UIKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Appearance-and-Presentation",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionActionWantsFullScreenPresentation",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionMainStoryboard",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionOverridesHostUIAppearance",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPointIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionActivationRule",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionJavaScriptPreprocessingFile"
              ],
              "title": "Appearance and Presentation"
            },
            {
              "anchor": "Core-Spotlight",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/CSSupportedContentTypes"
              ],
              "title": "Core Spotlight"
            },
            {
              "anchor": "Credential-providers",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ASCredentialProviderExtensionCapabilities"
              ],
              "title": "Credential providers"
            },
            {
              "anchor": "Intents",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/IntentsSupported",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/SupportedMediaCategories"
              ],
              "title": "Intents"
            },
            {
              "anchor": "Mail",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEComposeSession",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MEExtensionCapabilities"
              ],
              "title": "Mail"
            },
            {
              "anchor": "Photos",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHProjectExtensionDefinesProjectTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PHSupportedMediaTypes"
              ],
              "title": "Photos"
            },
            {
              "anchor": "Quick-Actions",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsFinderPreviewItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewIconName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceFinderPreviewLabel",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceRoleType"
              ],
              "title": "Quick Actions"
            },
            {
              "anchor": "Toolbar",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsToolbarItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceToolbarPaletteLabel"
              ],
              "title": "Toolbar"
            },
            {
              "anchor": "Touch-Bar",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceAllowsTouchBarItem",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarBezelColorName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarIconName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/NSExtensionServiceTouchBarLabel"
              ],
              "title": "Touch Bar"
            },
            {
              "anchor": "UIKit",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IDMessageFilterExtensionNetworkURL",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/ILClassificationExtensionSMSReportDestination",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/IsASCIICapable",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/MSMessagesAppPresentationContextMessages",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrefersRightToLeft",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/PrimaryLanguage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/RequestsOpenAccess",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerModes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UIDocumentPickerSupportedFileTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionCategory",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionDefaultContentHidden",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionInitialContentSizeRatio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionOverridesDefaultTitle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/NSExtensionAttributes/UNNotificationExtensionUserInteractionEnabled"
              ],
              "title": "UIKit"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarBezelColorName/title",
          "value": "NSExtensionServiceTouchBarBezelColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarBezelColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarBezelColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IsASCIICapable/title",
          "value": "IsASCIICapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IsASCIICapable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IsASCIICapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1RequestsOpenAccess/title",
          "value": "RequestsOpenAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1RequestsOpenAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RequestsOpenAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsFinderPreviewItem/title",
          "value": "NSExtensionServiceAllowsFinderPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsFinderPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceAllowsFinderPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/title",
          "value": "NSExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionJavaScriptPreprocessingFile/title",
          "value": "NSExtensionJavaScriptPreprocessingFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionJavaScriptPreprocessingFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionJavaScriptPreprocessingFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarLabel/title",
          "value": "NSExtensionServiceTouchBarLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionUserInteractionEnabled/title",
          "value": "UNNotificationExtensionUserInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionUserInteractionEnabled/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionUserInteractionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceFinderPreviewLabel/title",
          "value": "NSExtensionServiceFinderPreviewLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceFinderPreviewLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceFinderPreviewLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/title",
          "value": "NSExtensionOverridesHostUIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionOverridesHostUIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionOverridesHostUIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1IntentsSupported/title",
          "value": "IntentsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1IntentsSupported/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IntentsSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionInitialContentSizeRatio/title",
          "value": "UNNotificationExtensionInitialContentSizeRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionInitialContentSizeRatio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionInitialContentSizeRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IDMessageFilterExtensionNetworkURL/title",
          "value": "IDMessageFilterExtensionNetworkURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1IDMessageFilterExtensionNetworkURL/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IDMessageFilterExtensionNetworkURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/title",
          "value": "NSExtensionPointIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPointIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPointIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/title",
          "value": "NSExtensionMainStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionMainStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionMainStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarIconName/title",
          "value": "NSExtensionServiceTouchBarIconName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceTouchBarIconName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceTouchBarIconName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1SupportedMediaCategories/title",
          "value": "SupportedMediaCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1SupportedMediaCategories/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SupportedMediaCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1ILClassificationExtensionSMSReportDestination/title",
          "value": "ILClassificationExtensionSMSReportDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1ILClassificationExtensionSMSReportDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILClassificationExtensionSMSReportDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1CSSupportedContentTypes/title",
          "value": "CSSupportedContentTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1CSSupportedContentTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSupportedContentTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule/title",
          "value": "NSExtensionActivationRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionActivationRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActivationRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerSupportedFileTypes/title",
          "value": "UIDocumentPickerSupportedFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerSupportedFileTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerSupportedFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MEComposeSession/title",
          "value": "MEComposeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MEComposeSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEComposeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarPaletteLabel/title",
          "value": "NSExtensionServiceToolbarPaletteLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarPaletteLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceToolbarPaletteLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHProjectExtensionDefinesProjectTypes/title",
          "value": "PHProjectExtensionDefinesProjectTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHProjectExtensionDefinesProjectTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectExtensionDefinesProjectTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrefersRightToLeft/title",
          "value": "PrefersRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrefersRightToLeft/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PrefersRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHSupportedMediaTypes/title",
          "value": "PHSupportedMediaTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PHSupportedMediaTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHSupportedMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionCategory/title",
          "value": "UNNotificationExtensionCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MEExtensionCapabilities/title",
          "value": "MEExtensionCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MEExtensionCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEExtensionCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/title",
          "value": "NSExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionDefaultContentHidden/title",
          "value": "UNNotificationExtensionDefaultContentHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionDefaultContentHidden/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionDefaultContentHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsTouchBarItem/title",
          "value": "NSExtensionServiceAllowsTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceAllowsTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/title",
          "value": "NSExtensionActionWantsFullScreenPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionActionWantsFullScreenPresentation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionActionWantsFullScreenPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsToolbarItem/title",
          "value": "NSExtensionServiceAllowsToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceAllowsToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceAllowsToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionOverridesDefaultTitle/title",
          "value": "UNNotificationExtensionOverridesDefaultTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UNNotificationExtensionOverridesDefaultTitle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationExtensionOverridesDefaultTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarIconFile/title",
          "value": "NSExtensionServiceToolbarIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceToolbarIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceToolbarIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceFinderPreviewIconName/title",
          "value": "NSExtensionServiceFinderPreviewIconName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceFinderPreviewIconName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceFinderPreviewIconName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerModes/title",
          "value": "UIDocumentPickerModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1UIDocumentPickerModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MSMessagesAppPresentationContextMessages/title",
          "value": "MSMessagesAppPresentationContextMessages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1MSMessagesAppPresentationContextMessages/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContextMessages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceRoleType/title",
          "value": "NSExtensionServiceRoleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1NSExtensionServiceRoleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtensionServiceRoleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrimaryLanguage/title",
          "value": "PrimaryLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1PrimaryLanguage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PrimaryLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1ASCredentialProviderExtensionCapabilities/title",
          "value": "ASCredentialProviderExtensionCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1NSExtensionAttributes~1ASCredentialProviderExtensionCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASCredentialProviderExtensionCapabilities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/nsextensionattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
