{
  "abstract": [
    {
      "text": "The name of the class with the principal implementation of your extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.ProExtensionPrincipalClass",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ProExtensionPrincipalClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "ProVideo Encoder Extensions",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "ProVideo Workflow Extensions",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "ProExtensionPrincipalClass"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "ProExtensionPrincipalClass",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Compressor app instantiates the class specified in the ",
              "type": "text"
            },
            {
              "code": "ProExtensionPrincipalClass",
              "type": "codeVoice"
            },
            {
              "text": " key to convert source files to the output format your extension supports. Customize your extension code by adopting the following protocols in the implementation of this class:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionSettings",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionColorSpaces",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionSettingsOptional",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionEncoder",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes": {
      "abstract": [
        {
          "text": "A dictionary that specifies the minimum size of the floating window in which Final Cut Pro hosts the extension view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
      "kind": "symbol",
      "name": "ProExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the class with the principal implementation of your extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
      "kind": "symbol",
      "name": "ProExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass": {
      "abstract": [
        {
          "text": "The name of the principal view controller class of your extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
      "kind": "symbol",
      "name": "ProExtensionPrincipalViewControllerClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionPrincipalViewControllerClass"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionPrincipalViewControllerClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalviewcontrollerclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID": {
      "abstract": [
        {
          "text": "A UUID string that uniquely identifies your extension to the Compressor app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID",
      "kind": "symbol",
      "name": "ProExtensionUUID",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionUUID"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionUUID",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionuuid"
    },
    "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionColorSpaces": {
      "abstract": [
        {
          "text": "An interface you use to specify the supported color spaces in an extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompressorExtensionColorSpaces"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionColorSpaces",
      "kind": "symbol",
      "role": "symbol",
      "title": "CompressorExtensionColorSpaces",
      "type": "topic",
      "url": "/documentation/professional_video_applications/CompressorExtensionColorSpaces"
    },
    "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionEncoder": {
      "abstract": [
        {
          "text": "An interface an extension implements to convert source media to the output format supported in your extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompressorExtensionEncoder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionEncoder",
      "kind": "symbol",
      "role": "symbol",
      "title": "CompressorExtensionEncoder",
      "type": "topic",
      "url": "/documentation/professional_video_applications/CompressorExtensionEncoder"
    },
    "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionSettings": {
      "abstract": [
        {
          "text": "A set of methods you use to manage the extension UI that displays the current encoder settings for users to view and customize.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompressorExtensionSettings"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionSettings",
      "kind": "symbol",
      "role": "symbol",
      "title": "CompressorExtensionSettings",
      "type": "topic",
      "url": "/documentation/professional_video_applications/CompressorExtensionSettings"
    },
    "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionSettingsOptional": {
      "abstract": [
        {
          "text": "An interface you use to receive updated values of source media attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CompressorExtensionSettingsOptional"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/professional_video_applications/CompressorExtensionSettingsOptional",
      "kind": "symbol",
      "role": "symbol",
      "title": "CompressorExtensionSettingsOptional",
      "type": "topic",
      "url": "/documentation/professional_video_applications/CompressorExtensionSettingsOptional"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Professional-Video-Applications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID"
      ],
      "title": "Professional Video Applications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "ProVideo Encoder Extensions",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "ProVideo Workflow Extensions",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ProExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Professional-Video-Applications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID"
              ],
              "title": "Professional Video Applications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1professional_video_applications~1CompressorExtensionSettingsOptional/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CompressorExtensionSettingsOptional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1professional_video_applications~1CompressorExtensionColorSpaces/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CompressorExtensionColorSpaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionUUID/title",
          "value": "ProExtensionUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes/title",
          "value": "ProExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalViewControllerClass/title",
          "value": "ProExtensionPrincipalViewControllerClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalViewControllerClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalViewControllerClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1professional_video_applications~1CompressorExtensionSettings/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CompressorExtensionSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalClass/title",
          "value": "ProExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1professional_video_applications~1CompressorExtensionEncoder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CompressorExtensionEncoder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
