{
  "abstract": [
    {
      "text": "A dictionary that specifies the minimum size of the floating window in which Final Cut Pro hosts the extension view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.NSExtension.ProExtensionAttributes",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ProExtensionAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "ProVideo Workflow Extensions",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "ProExtensionAttributes"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "ProExtensionAttributes",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Professional-Video-Applications/designing-workflow-extensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension": {
      "abstract": [
        {
          "text": "The properties of an app extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension",
      "kind": "symbol",
      "name": "NSExtension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExtension"
        }
      ],
      "role": "symbol",
      "title": "NSExtension",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes": {
      "abstract": [
        {
          "text": "A dictionary that specifies the minimum size of the floating window in which Final Cut Pro hosts the extension view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes",
      "kind": "symbol",
      "name": "ProExtensionAttributes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionAttributes"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionAttributes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumHeight": {
      "abstract": [
        {
          "text": "An integer that specifies the minimum height of the floating window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumHeight",
      "kind": "symbol",
      "name": "ContentViewMinimumHeight",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentViewMinimumHeight"
        }
      ],
      "role": "symbol",
      "title": "ContentViewMinimumHeight",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes/contentviewminimumheight"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumWidth": {
      "abstract": [
        {
          "text": "An integer that specifies the minimum width of the floating window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumWidth",
      "kind": "symbol",
      "name": "ContentViewMinimumWidth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentViewMinimumWidth"
        }
      ],
      "role": "symbol",
      "title": "ContentViewMinimumWidth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes/contentviewminimumwidth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass": {
      "abstract": [
        {
          "text": "The name of the class with the principal implementation of your extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
      "kind": "symbol",
      "name": "ProExtensionPrincipalClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionPrincipalClass"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionPrincipalClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass": {
      "abstract": [
        {
          "text": "The name of the principal view controller class of your extension.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
      "kind": "symbol",
      "name": "ProExtensionPrincipalViewControllerClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionPrincipalViewControllerClass"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionPrincipalViewControllerClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionprincipalviewcontrollerclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID": {
      "abstract": [
        {
          "text": "A UUID string that uniquely identifies your extension to the Compressor app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID",
      "kind": "symbol",
      "name": "ProExtensionUUID",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProExtensionUUID"
        }
      ],
      "role": "symbol",
      "title": "ProExtensionUUID",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/nsextension/proextensionuuid"
    },
    "doc://com.apple.documentation/documentation/Professional-Video-Applications/designing-workflow-extensions": {
      "abstract": [
        {
          "text": "Follow these design guidelines to provide a unique experience to workflow extension users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Professional-Video-Applications/designing-workflow-extensions",
      "kind": "article",
      "role": "article",
      "title": "Designing Workflow Extensions",
      "type": "topic",
      "url": "/documentation/Professional-Video-Applications/designing-workflow-extensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Professional-Video-Applications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID"
      ],
      "title": "Professional Video Applications"
    }
  ],
  "topicSections": [
    {
      "anchor": "Attributes",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumHeight",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumWidth"
      ],
      "title": "Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "ProVideo Workflow Extensions",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ProExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Attributes",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumHeight",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionAttributes/ContentViewMinimumWidth"
              ],
              "title": "Attributes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Professional-Video-Applications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionPrincipalViewControllerClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSExtension/ProExtensionUUID"
              ],
              "title": "Professional Video Applications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionUUID/title",
          "value": "ProExtensionUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/title",
          "value": "NSExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalViewControllerClass/title",
          "value": "ProExtensionPrincipalViewControllerClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalViewControllerClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalViewControllerClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes~1ContentViewMinimumHeight/title",
          "value": "ContentViewMinimumHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes~1ContentViewMinimumHeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ContentViewMinimumHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes/title",
          "value": "ProExtensionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes~1ContentViewMinimumWidth/title",
          "value": "ContentViewMinimumWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionAttributes~1ContentViewMinimumWidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ContentViewMinimumWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalClass/title",
          "value": "ProExtensionPrincipalClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSExtension~1ProExtensionPrincipalClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProExtensionPrincipalClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/nsextension/proextensionattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
