{
  "abstract": [
    {
      "text": "The color of the simulated ground.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLSkyCubeTexture(py)groundColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "groundColor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CGColorRef",
        "text": "CGColor"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "groundColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "groundColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "groundColor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGColorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGColorRef",
              "text": "CGColor"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, this property’s value is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", causing Model I/O to render an infinite sky above and below. If you set this property to a color, Model I/O renders a solid color for all areas of the cube texture below the level specified in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/horizonElevation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates cube textures using a physically realistic simulation of the sunlit sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "role": "symbol",
      "title": "MDLSkyCubeTexture",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundAlbedo": {
      "abstract": [
        {
          "text": "A factor that influences the clarity of the simulated sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groundAlbedo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundAlbedo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groundAlbedo"
        }
      ],
      "role": "symbol",
      "title": "groundAlbedo",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture/groundalbedo"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundColor": {
      "abstract": [
        {
          "text": "The color of the simulated ground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groundColor"
        }
      ],
      "role": "symbol",
      "title": "groundColor",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture/groundcolor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/horizonElevation": {
      "abstract": [
        {
          "text": "The angle, in radians relative to center, below which to render the ground color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizonElevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/horizonElevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizonElevation"
        }
      ],
      "role": "symbol",
      "title": "horizonElevation",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture/horizonelevation"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/sunElevation": {
      "abstract": [
        {
          "text": "The sun’s position in the simulated sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sunElevation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/sunElevation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sunElevation"
        }
      ],
      "role": "symbol",
      "title": "sunElevation",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture/sunelevation"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/turbidity": {
      "abstract": [
        {
          "text": "The cloudiness or haziness of the simulated sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turbidity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/turbidity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "turbidity"
        }
      ],
      "role": "symbol",
      "title": "turbidity",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture/turbidity"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/upperAtmosphereScattering": {
      "abstract": [
        {
          "text": "A factor that influences the color of the simulated sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upperAtmosphereScattering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/upperAtmosphereScattering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "upperAtmosphereScattering"
        }
      ],
      "role": "symbol",
      "title": "upperAtmosphereScattering",
      "type": "topic",
      "url": "/documentation/modelio/mdlskycubetexture/upperatmospherescattering"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGColorRef": {
      "abstract": [
        {
          "text": "A set of components that define a color, with a color space specifying how to interpret them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGColor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGColorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColor",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcolor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Sky-Simulation-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/turbidity",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/sunElevation",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/upperAtmosphereScattering",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundAlbedo",
        "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/horizonElevation"
      ],
      "title": "Working with Sky Simulation Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "groundColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Sky-Simulation-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/turbidity",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/sunElevation",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/upperAtmosphereScattering",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/groundAlbedo",
                "doc://com.apple.modelio/documentation/ModelIO/MDLSkyCubeTexture/horizonElevation"
              ],
              "title": "Working with Sky Simulation Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGColorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGColorRef",
                    "text": "CGColorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "groundColor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1horizonElevation/title",
          "value": "horizonElevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1horizonElevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizonElevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGColorRef/title",
          "value": "CGColorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1groundAlbedo/title",
          "value": "groundAlbedo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1groundAlbedo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groundAlbedo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/title",
          "value": "MDLSkyCubeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1turbidity/title",
          "value": "turbidity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1turbidity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "turbidity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1upperAtmosphereScattering/title",
          "value": "upperAtmosphereScattering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1upperAtmosphereScattering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "upperAtmosphereScattering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1sunElevation/title",
          "value": "sunElevation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1sunElevation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sunElevation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1groundColor/title",
          "value": "groundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSkyCubeTexture~1groundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groundColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlskycubetexture/groundcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlskycubetexture/groundcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
