{
  "abstract": [
    {
      "text": "The user explicitly denied access to address book data for this app.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "use CNAuthorizationStatus",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/denied"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ABAuthorizationStatus@kABAuthorizationStatusDenied",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "denied"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kABAuthorizationStatusDenied"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "use CNAuthorizationStatus",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "use CNAuthorizationStatus",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "use CNAuthorizationStatus",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ABAuthorizationStatus.denied"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "denied"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus": {
      "abstract": [
        {
          "text": "Different possible values for the authorization status of an app with respect to address book data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ABAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/addressbook/abauthorizationstatus"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The app is authorized to access address book data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "ABAuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/addressbook/abauthorizationstatus/authorized"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "The user explicitly denied access to address book data for this app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "ABAuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/addressbook/abauthorizationstatus/denied"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "No authorization status could be determined.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "ABAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/addressbook/abauthorizationstatus/notdetermined"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "The app is not authorized to access address book data. The user cannot change this access, possibly due to restrictions such as parental controls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kABAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "ABAuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/addressbook/abauthorizationstatus/restricted"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/notDetermined",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/restricted",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/authorized"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kABAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/notDetermined",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/restricted",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAuthorizationStatus/authorized"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kABAuthorizationStatusDenied"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "use CNAuthorizationStatus",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus/title",
          "value": "ABAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1authorized/title",
          "value": "kABAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1restricted/title",
          "value": "kABAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1denied/title",
          "value": "kABAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1notDetermined/title",
          "value": "kABAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kABAuthorizationStatusNotDetermined"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abauthorizationstatus/denied"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abauthorizationstatus/denied"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
