{"seeAlsoSections":[{"title":"Responding to editing notifications","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)"],"anchor":"Responding-to-editing-notifications"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextviewdelegate/textviewdidendediting(_:)"]},{"paths":["/documentation/uikit/uitextviewdelegate/textviewdidendediting(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Tells the delegate when editing of the specified text view ends.","type":"text"}],"metadata":{"platforms":[{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"UIKit"}],"title":"textViewDidEndEditing(_:)","externalID":"c:objc(pl)UITextViewDelegate(im)textViewDidEndEditing:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"textViewDidEndEditing:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITextView","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView","kind":"typeIdentifier","text":"UITextView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"parameters","parameters":[{"name":"textView","content":[{"inlineContent":[{"type":"text","text":"The text view in which editing ended."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Implementation of this method is optional. A text view sends this message to its delegate after it closes out any pending edits and resigns its first responder status. You can use this method to tear down any data structures or change any state information that you set when editing began.","type":"text"}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)","type":"topic","url":"/documentation/uikit/uitextviewdelegate/textviewshouldbeginediting(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewShouldBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Asks the delegate whether to begin editing in the specified text view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textViewShouldBeginEditing:"}],"title":"textViewShouldBeginEditing(_:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)","type":"topic","url":"/documentation/uikit/uitextviewdelegate/textviewshouldendediting(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewShouldEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Asks the delegate whether to stop editing in the specified text view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textViewShouldEndEditing:"}],"title":"textViewShouldEndEditing(_:)"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)":{"type":"topic","role":"symbol","kind":"symbol","title":"textViewDidBeginEditing(_:)","navigatorTitle":[{"text":"textViewDidBeginEditing:","kind":"identifier"}],"url":"/documentation/uikit/uitextviewdelegate/textviewdidbeginediting(_:)","abstract":[{"text":"Tells the delegate when editing of the specified text view begins.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewDidBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate":{"navigatorTitle":[{"text":"UITextViewDelegate","kind":"identifier"}],"url":"/documentation/uikit/uitextviewdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The methods for receiving editing-related messages for text view objects.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate","title":"UITextViewDelegate","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"textViewDidEndEditing:","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uitextviewdelegate/textviewdidendediting(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)","title":"textViewDidEndEditing(_:)","role":"symbol","abstract":[{"text":"Tells the delegate when editing of the specified text view ends.","type":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextView":{"navigatorTitle":[{"text":"UITextView","kind":"identifier"}],"title":"UITextView","url":"/documentation/uikit/uitextview","abstract":[{"text":"A scrollable, multiline text region.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"textViewDidEndEditing:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidEndEditing:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Responding-to-editing-notifications","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)"],"title":"Responding to editing notifications"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"textViewDidEndEditing:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView","kind":"typeIdentifier","text":"UITextView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textView"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"textView","content":[{"type":"paragraph","inlineContent":[{"text":"The text view in which editing ended.","type":"text"}]}]}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldBeginEditing(_:)/title","value":"textViewShouldBeginEditing:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldBeginEditing(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewShouldBeginEditing:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldEndEditing(_:)/title","value":"textViewShouldEndEditing:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldEndEditing(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"textViewShouldEndEditing:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidBeginEditing(_:)/title","value":"textViewDidBeginEditing:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidBeginEditing(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"textViewDidBeginEditing:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/title","value":"UITextViewDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/fragments","value":[{"text":"UITextViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/navigatorTitle","value":[{"text":"UITextViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidEndEditing(_:)/title","value":"textViewDidEndEditing:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidEndEditing(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidEndEditing:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title","value":"UITextView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments","value":[{"kind":"identifier","text":"UITextView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle","value":[{"kind":"identifier","text":"UITextView"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}