{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"textView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text view whose selection changed."}]}]}],"kind":"parameters"},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Implementation of this method is optional. You can use the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView/selectedRange","isActive":true,"type":"reference"},{"text":" property of the text view to get the new selection.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Tells the delegate when the text selection changes in the specified text view.","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"text":"textViewDidChangeSelection:","kind":"identifier"}],"externalID":"c:objc(pl)UITextViewDelegate(im)textViewDidChangeSelection:","roleHeading":"Instance Method","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0","name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textViewDidChangeSelection","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"UIKit"}],"title":"textViewDidChangeSelection(_:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextviewdelegate/textviewdidchangeselection(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextviewdelegate/textviewdidchangeselection(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"textViewDidChangeSelection:","kind":"identifier"}],"title":"textViewDidChangeSelection(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)","url":"/documentation/uikit/uitextviewdelegate/textviewdidchangeselection(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChangeSelection"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate when the text selection changes in the specified text view."}]},"doc://com.apple.uikit/documentation/UIKit/UITextView/selectedRange":{"url":"/documentation/uikit/uitextview/selectedrange","navigatorTitle":[{"kind":"identifier","text":"selectedRange"}],"type":"topic","abstract":[{"text":"The current selection range of the text view.","type":"text"}],"role":"symbol","kind":"symbol","title":"selectedRange","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView/selectedRange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRange"},{"kind":"text","text":": "},{"text":"NSRange","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITextView":{"navigatorTitle":[{"text":"UITextView","kind":"identifier"}],"title":"UITextView","url":"/documentation/uikit/uitextview","abstract":[{"text":"A scrollable, multiline text region.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate":{"navigatorTitle":[{"text":"UITextViewDelegate","kind":"identifier"}],"url":"/documentation/uikit/uitextviewdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The methods for receiving editing-related messages for text view objects.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate","title":"UITextViewDelegate","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"textViewDidChangeSelection:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidChangeSelection:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"textViewDidChangeSelection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textView"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text view whose selection changed."}]}],"name":"textView"}]},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidChangeSelection(_:)/title","value":"textViewDidChangeSelection:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidChangeSelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"textViewDidChangeSelection:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView~1selectedRange/title","value":"selectedRange"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView~1selectedRange/fragments","value":[{"text":"selectedRange","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title","value":"UITextView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments","value":[{"kind":"identifier","text":"UITextView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle","value":[{"text":"UITextView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/title","value":"UITextViewDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/fragments","value":[{"text":"UITextViewDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/navigatorTitle","value":[{"text":"UITextViewDelegate","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}