{
  "abstract": [
    {
      "text": "Aligns the ruby text with the ending edge of the base text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTRubyAlignment@kCTRubyAlignmentEnd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "end"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTRubyAlignmentEnd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTRubyAlignment.end"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "end"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment": {
      "abstract": [
        {
          "text": "Constants that specify how to align the ruby text and the base text relative to each other when they have different lengths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto": {
      "abstract": [
        {
          "text": "Core Text automatically determines the alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentAuto"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.auto",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/auto"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center": {
      "abstract": [
        {
          "text": "Centers the ruby text within the width of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.center",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/center"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter": {
      "abstract": [
        {
          "text": "Distributes the ruby text evenly over the width of the base text, aligning the first and last characters of the ruby text with the first and last characters of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distributeLetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentDistributeLetter"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.distributeLetter",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/distributeletter"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace": {
      "abstract": [
        {
          "text": "Distributes the ruby text evenly over the width of the base text, adding space before the first and after the last character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distributeSpace"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentDistributeSpace"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.distributeSpace",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/distributespace"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end": {
      "abstract": [
        {
          "text": "Aligns the ruby text with the ending edge of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentEnd"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.end",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/end"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid": {
      "abstract": [
        {
          "text": "The alignment is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentInvalid"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.invalid",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/invalid"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge": {
      "abstract": [
        {
          "text": "Aligns the ruby text to an adjacent line edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineEdge"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentLineEdge"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.lineEdge",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/lineedge"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start": {
      "abstract": [
        {
          "text": "Aligns the ruby text with the starting edge of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentStart"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.start",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/start"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTRubyAlignmentEnd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTRubyAlignmentEnd"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1invalid/title",
          "value": "kCTRubyAlignmentInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1end/title",
          "value": "kCTRubyAlignmentEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1end/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1center/title",
          "value": "kCTRubyAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1start/title",
          "value": "kCTRubyAlignmentStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1start/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1lineEdge/title",
          "value": "kCTRubyAlignmentLineEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1lineEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentLineEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeLetter/title",
          "value": "kCTRubyAlignmentDistributeLetter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeLetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentDistributeLetter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeSpace/title",
          "value": "kCTRubyAlignmentDistributeSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentDistributeSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/title",
          "value": "CTRubyAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1auto/title",
          "value": "kCTRubyAlignmentAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentAuto"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrubyalignment/end"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctrubyalignment/end"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
