{
  "abstract": [
    {
      "text": "Calculate and store tremor and dyskinetic symptom results for the duration of the specified time interval.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMMovementDisorderManager(im)monitorKinesiasForDuration:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "monitorKinesias"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "forDuration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "monitorKinesiasForDuration:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "monitorKinesias(forDuration:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "monitorKinesias"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "forDuration"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "duration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The monitoring duration in seconds. The maximum duration is seven days.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "duration"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coremotion/documentation/CoreMotion/getting-movement-disorder-symptom-data"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to begin monitoring, calculating, and storing tremor and dyskinetic symptom results. The manager stores results for a period of seven days after the time of recording. You can access the results at any time within that seven-day interval, after which they expire. To retrieve these results, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryTremor(from:to:withHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryDyskineticSymptom(from:to:withHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To determine whether the results are currently being monitored and calculated, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesiasExpirationDate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The maximum monitoring duration is seven days. In order to continue monitoring beyond the expiration date, you need to renew your subscription by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " again before the monitoring period expires. Note that repeated calls allow you to extend monitoring, but not shorten it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager": {
      "abstract": [
        {
          "text": "A manager for recording and querying movement disorder data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMovementDisorderManager"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMovementDisorderManager"
        }
      ],
      "role": "symbol",
      "title": "CMMovementDisorderManager",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)": {
      "abstract": [
        {
          "text": "Calculate and store tremor and dyskinetic symptom results for the duration of the specified time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monitorKinesias"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesias(forDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "monitorKinesiasForDuration:"
        }
      ],
      "role": "symbol",
      "title": "monitorKinesias(forDuration:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager/monitorkinesias(forduration:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesiasExpirationDate()": {
      "abstract": [
        {
          "text": "Returns the expiration date for the most recent monitoring period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monitorKinesiasExpirationDate"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesiasExpirationDate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "monitorKinesiasExpirationDate"
        }
      ],
      "role": "symbol",
      "title": "monitorKinesiasExpirationDate()",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager/monitorkinesiasexpirationdate()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryDyskineticSymptom(from:to:withHandler:)": {
      "abstract": [
        {
          "text": "Query for dyskinetic symptoms from the provided time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryDyskineticSymptom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMDyskineticSymptomResultHandler",
          "text": "CMDyskineticSymptomResultHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryDyskineticSymptom(from:to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryDyskineticSymptomFromDate:toDate:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "queryDyskineticSymptom(from:to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager/querydyskineticsymptom(from:to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryTremor(from:to:withHandler:)": {
      "abstract": [
        {
          "text": "Query for tremor results from the provided time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryTremor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTremorResultHandler",
          "text": "CMTremorResultHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryTremor(from:to:withHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryTremorFromDate:toDate:withHandler:"
        }
      ],
      "role": "symbol",
      "title": "queryTremor(from:to:withHandler:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmmovementdisordermanager/querytremor(from:to:withhandler:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/getting-movement-disorder-symptom-data": {
      "abstract": [
        {
          "text": "Retrieve data from the Apple Watch’s movement disorder manager.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/getting-movement-disorder-symptom-data",
      "kind": "article",
      "role": "article",
      "title": "Getting movement disorder symptom data",
      "type": "topic",
      "url": "/documentation/coremotion/getting-movement-disorder-symptom-data"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryTremor(from:to:withHandler:)",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryDyskineticSymptom(from:to:withHandler:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Recording-Movement-Disorders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesiasExpirationDate()"
      ],
      "title": "Recording Movement Disorders"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "monitorKinesiasForDuration:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "monitorKinesiasForDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryTremor(from:to:withHandler:)",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/queryDyskineticSymptom(from:to:withHandler:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Recording-Movement-Disorders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMMovementDisorderManager/monitorKinesiasExpirationDate()"
              ],
              "title": "Recording Movement Disorders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "monitorKinesiasForDuration:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTimeInterval",
                    "text": "NSTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "duration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The monitoring duration in seconds. The maximum duration is seven days.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "duration"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1monitorKinesias(forDuration:)/title",
          "value": "monitorKinesiasForDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1monitorKinesias(forDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "monitorKinesiasForDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager/title",
          "value": "CMMovementDisorderManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMovementDisorderManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMovementDisorderManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1queryTremor(from:to:withHandler:)/title",
          "value": "queryTremorFromDate:toDate:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1queryTremor(from:to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "queryTremorFromDate:toDate:withHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1monitorKinesiasExpirationDate()/title",
          "value": "monitorKinesiasExpirationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1monitorKinesiasExpirationDate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "monitorKinesiasExpirationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1queryDyskineticSymptom(from:to:withHandler:)/title",
          "value": "queryDyskineticSymptomFromDate:toDate:withHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMMovementDisorderManager~1queryDyskineticSymptom(from:to:withHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "queryDyskineticSymptomFromDate:toDate:withHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmmovementdisordermanager/monitorkinesias(forduration:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmmovementdisordermanager/monitorkinesias(forduration:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
