{
  "abstract": [
    {
      "text": "Initializes the receiver with a URL for the store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription/init(url:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPersistentStoreDescription(im)initWithURL:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "url"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithURL:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(url:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Location for the store.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "url"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Initialized ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " configured with the given URL.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription": {
      "abstract": [
        {
          "text": "A description object used to create and load a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreDescription"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreDescription",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoredescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription/init(url:)": {
      "abstract": [
        {
          "text": "Initializes the receiver with a URL for the store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription/init(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:"
        }
      ],
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoredescription/init(url:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription/persistentStoreDescriptionWithURL:": {
      "abstract": [
        {
          "text": "Initializes and returns a persistent store description with the given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "persistentStoreDescriptionWithURL:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription/persistentStoreDescriptionWithURL:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentStoreDescriptionWithURL:"
        }
      ],
      "role": "symbol",
      "title": "persistentStoreDescriptionWithURL:",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoredescription/persistentstoredescriptionwithurl:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithURL:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Persistent-Store-Description",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription/persistentStoreDescriptionWithURL:"
              ],
              "title": "Creating a Persistent Store Description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithURL:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "url"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Location for the store.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "url"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Initialized ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " configured with the given URL.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription/title",
          "value": "NSPersistentStoreDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription~1init(url:)/title",
          "value": "initWithURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription~1init(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentstoredescription/init(url:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistentstoredescription/init(url:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
