{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/unwindAction","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The action method associated with the unwind segue."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unwindAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Each unwind segue has an associated action method. The view controller that’s the destination of the unwind segue must implement this action method."}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"anchor":"Getting-the-unwind-segue-attributes","title":"Getting the unwind segue attributes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/source","doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/sender"],"generated":true}],"metadata":{"title":"unwindAction","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unwindAction","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"unwindAction"}],"externalID":"c:objc(cs)UIStoryboardUnwindSegueSource(py)unwindAction","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"modules":[{"name":"UIKit"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource"]]},"variants":[{"paths":["/documentation/uikit/uistoryboardunwindseguesource/unwindaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uistoryboardunwindseguesource/unwindaction"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@SEL":{"role":"symbol","url":"/documentation/objectivec/sel","abstract":[{"text":"Defines an opaque type that represents a method selector.","type":"text"}],"type":"topic","title":"SEL","identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/source":{"title":"source","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceViewController"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/source","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"abstract":[{"type":"text","text":"The view controller being dismissed by the unwind segue."}],"url":"/documentation/uikit/uistoryboardunwindseguesource/source"},"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource","navigatorTitle":[{"kind":"identifier","text":"UIStoryboardUnwindSegueSource"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIStoryboardUnwindSegueSource"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An encapsulation of information about an unwind segue."}],"title":"UIStoryboardUnwindSegueSource","url":"/documentation/uikit/uistoryboardunwindseguesource","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/unwindAction":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/unwindAction","abstract":[{"text":"The action method associated with the unwind segue.","type":"text"}],"title":"unwindAction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unwindAction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"}],"navigatorTitle":[{"text":"unwindAction","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uistoryboardunwindseguesource/unwindaction","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/sender":{"type":"topic","abstract":[{"text":"The object that performed the unwind action.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sender","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uistoryboardunwindseguesource/sender","role":"symbol","navigatorTitle":[{"text":"sender","kind":"identifier"}],"title":"sender","identifier":"doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/sender","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"abstract":[{"text":"","type":"text"}],"title":"Selector","url":"/documentation/objectivec/selector","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","fragments":[{"text":"struct ","kind":"text"},{"text":"Selector","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"9.0","beta":false},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false}]},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"unwindAction","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"unwindAction"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Getting-the-unwind-segue-attributes","generated":true,"title":"Getting the unwind segue attributes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/source","doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource/sender"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@SEL","identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","kind":"typeIdentifier","text":"SEL"},{"text":" ","kind":"text"},{"text":"unwindAction","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":"sourceViewController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource~1source/title"},{"op":"replace","value":[{"kind":"identifier","text":"sourceViewController"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource~1source/fragments"},{"op":"replace","value":"UIStoryboardUnwindSegueSource","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIStoryboardUnwindSegueSource"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIStoryboardUnwindSegueSource"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource/navigatorTitle"},{"op":"replace","value":"unwindAction","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource~1unwindAction/title"},{"op":"replace","value":[{"text":"unwindAction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource~1unwindAction/fragments"},{"op":"replace","value":"sender","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource~1sender/title"},{"op":"replace","value":[{"text":"sender","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource~1sender/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}