{
  "abstract": [
    {
      "text": "A type of event indicating the report is about a pass/block decision made after analyzing some amount of a flow’s data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/dataDecision"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEFilterReportEvent@NEFilterReportEventDataDecision",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dataDecision"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEFilterReportEventDataDecision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEFilterReport.Event.dataDecision"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dataDecision"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport": {
      "abstract": [
        {
          "text": "The report of the data provider’s action on a flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEFilterReport"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReport"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum": {
      "abstract": [
        {
          "text": "A type that represents the kind of event indicated by a report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport.Event",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport/event-swift.enum"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/dataDecision": {
      "abstract": [
        {
          "text": "A type of event indicating the report is about a pass/block decision made after analyzing some amount of a flow’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataDecision"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/dataDecision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReportEventDataDecision"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport.Event.dataDecision",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport/event-swift.enum/datadecision"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/flowClosed": {
      "abstract": [
        {
          "text": "A type of event indicating the report is for a flow’s closing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flowClosed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/flowClosed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReportEventFlowClosed"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport.Event.flowClosed",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport/event-swift.enum/flowclosed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/newFlow": {
      "abstract": [
        {
          "text": "A type of event indicating the report is for a new flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/newFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReportEventNewFlow"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport.Event.newFlow",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport/event-swift.enum/newflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/statistics": {
      "abstract": [
        {
          "text": "A type of event indicating the report is for the latest statistics of the flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statistics"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/statistics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEFilterReportEventStatistics"
        }
      ],
      "role": "symbol",
      "title": "NEFilterReport.Event.statistics",
      "type": "topic",
      "url": "/documentation/networkextension/nefilterreport/event-swift.enum/statistics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/newFlow",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/flowClosed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/statistics"
      ],
      "title": "Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEFilterReportEventDataDecision"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEventDataDecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/newFlow",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/flowClosed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEFilterReport/Event-swift.enum/statistics"
              ],
              "title": "Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEFilterReportEventDataDecision"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1statistics/title",
          "value": "NEFilterReportEventStatistics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1statistics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEventStatistics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1dataDecision/title",
          "value": "NEFilterReportEventDataDecision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1dataDecision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEventDataDecision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1flowClosed/title",
          "value": "NEFilterReportEventFlowClosed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1flowClosed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEventFlowClosed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum/title",
          "value": "NEFilterReportEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/title",
          "value": "NEFilterReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1newFlow/title",
          "value": "NEFilterReportEventNewFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEFilterReport~1Event-swift.enum~1newFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEFilterReportEventNewFlow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nefilterreport/event-swift.enum/datadecision"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nefilterreport/event-swift.enum/datadecision"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
