{
  "abstract": [
    {
      "text": "Creates a new camera position the coordinate region you provide.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/region(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:15_MapKit_SwiftUI0A14CameraPositionV6regionyACSo18MKCoordinateRegionaFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "region"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@MKCoordinateRegion",
        "text": "MKCoordinateRegion"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
        "text": "MapCameraPosition"
      }
    ],
    "modules": [
      {
        "name": "MapKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "region(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "region"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "region"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MKCoordinateRegion",
              "text": "MKCoordinateRegion"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
              "text": "MapCameraPosition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that describes the camera boundaries.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "region"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion": {
      "abstract": [
        {
          "text": "A rectangular geographic region that centers around a specific latitude and longitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCoordinateRegion"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCoordinateRegion"
        }
      ],
      "role": "symbol",
      "title": "MKCoordinateRegion",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinateregion"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition": {
      "abstract": [
        {
          "text": "A structure that describes how to position the map’s camera within the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCameraPosition"
        }
      ],
      "role": "symbol",
      "title": "MapCameraPosition",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/camera(_:)": {
      "abstract": [
        {
          "text": "Creates a new camera position from an existing map camera you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A6CameraV",
          "text": "MapCamera"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/camera(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "camera(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition/camera(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/item(_:allowsAutomaticPitch:)": {
      "abstract": [
        {
          "text": "Creates a new camera position centered on a map item and automatic pitch selection you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "item"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allowsAutomaticPitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/item(_:allowsAutomaticPitch:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "item(_:allowsAutomaticPitch:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition/item(_:allowsautomaticpitch:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/rect(_:)": {
      "abstract": [
        {
          "text": "Creates a new camera position with the map boundaries you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapRect",
          "text": "MKMapRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/rect(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "rect(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition/rect(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/region(_:)": {
      "abstract": [
        {
          "text": "Creates a new camera position the coordinate region you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "region"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKCoordinateRegion",
          "text": "MKCoordinateRegion"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/region(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "region(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition/region(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/userLocation(followsHeading:fallback:)": {
      "abstract": [
        {
          "text": "Creates a camera position with the specific fallback position and optionally follows the user’s heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userLocation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "followsHeading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
          "text": "MapCameraPosition"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A14CameraPositionV",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/userLocation(followsHeading:fallback:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "userLocation(followsHeading:fallback:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition/userlocation(followsheading:fallback:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-camera-position",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/camera(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/item(_:allowsAutomaticPitch:)",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/rect(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition/userLocation(followsHeading:fallback:)"
      ],
      "title": "Creating a camera position"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/title",
          "value": "MKCoordinateRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateRegion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mapcameraposition/region(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
