{
  "abstract": [
    {
      "text": "Returns a count of the objects the specified request fetches when it executes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/count(for:)-3r91z"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreData",
    "externalID": "s:So22NSManagedObjectContextC8CoreDataE5count3forSiSo14NSFetchRequestCyxG_tKSo0hI6ResultRzlF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "count"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "T"
      },
      {
        "kind": "text",
        "text": ">("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFetchRequest",
        "text": "NSFetchRequest"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "T"
      },
      {
        "kind": "text",
        "text": ">) "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "count(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "count"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "T"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFetchRequest",
              "text": "NSFetchRequest"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "T"
            },
            {
              "kind": "text",
              "text": ">) "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "T"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSFetchRequestResult",
              "text": "NSFetchRequestResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest": {
      "abstract": [
        {
          "text": "A description of search criteria used to retrieve data from a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFetchRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestResult": {
      "abstract": [
        {
          "text": "An abstract protocol used with parameterized fetch requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchRequestResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchRequestResult"
        }
      ],
      "role": "symbol",
      "title": "NSFetchRequestResult",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequestresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext": {
      "abstract": [
        {
          "text": "An object space to manipulate and track changes to managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/count(for:)-3r91z": {
      "abstract": [
        {
          "text": "Returns a count of the objects the specified request fetches when it executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/count(for:)-3r91z",
      "kind": "symbol",
      "role": "symbol",
      "title": "count(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/count(for:)-3r91z"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/count(for:)-93zbm": {
      "abstract": [
        {
          "text": "Returns the number of objects the specified request fetches when it executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFetchRequestResult",
          "text": "NSFetchRequestResult"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/count(for:)-93zbm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "countForFetchRequest:error:"
        }
      ],
      "role": "symbol",
      "title": "count(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/count(for:)-93zbm"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/execute(_:)": {
      "abstract": [
        {
          "text": "Passes a request to the persistent store without affecting the contents of the managed object context, and returns a persistent store result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreRequest",
          "text": "NSPersistentStoreRequest"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreResult",
          "text": "NSPersistentStoreResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/execute(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeRequest:error:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/execute(_:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/existingObject(with:)": {
      "abstract": [
        {
          "text": "Returns an existing object from either the context or the persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "existingObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/existingObject(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "existingObjectWithID:error:"
        }
      ],
      "role": "symbol",
      "title": "existingObject(with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/existingobject(with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/fetch(_:)-38ys1": {
      "abstract": [
        {
          "text": "Returns an array of objects that meet the criteria of the specified fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFetchRequestResult",
          "text": "NSFetchRequestResult"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/fetch(_:)-38ys1",
      "kind": "symbol",
      "role": "symbol",
      "title": "fetch(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/fetch(_:)-38ys1"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/fetch(_:)-4xeoz": {
      "abstract": [
        {
          "text": "Returns an array of items of the specified type that meet the fetch request’s critieria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetch"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/fetch(_:)-4xeoz",
      "kind": "symbol",
      "role": "symbol",
      "title": "fetch(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/fetch(_:)-4xeoz"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/object(with:)": {
      "abstract": [
        {
          "text": "Returns either an existing object from the context or a fault that represents that object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/object(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectWithID:"
        }
      ],
      "role": "symbol",
      "title": "object(with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/object(with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/refreshAllObjects()": {
      "abstract": [
        {
          "text": "Refreshes all of the registered managed objects in the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshAllObjects"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/refreshAllObjects()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refreshAllObjects"
        }
      ],
      "role": "symbol",
      "title": "refreshAllObjects()",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/refreshallobjects()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/registeredObject(for:)": {
      "abstract": [
        {
          "text": "Returns an object that exists in the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registeredObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/registeredObject(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectRegisteredForID:"
        }
      ],
      "role": "symbol",
      "title": "registeredObject(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/registeredobject(for:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/registeredObjects": {
      "abstract": [
        {
          "text": "The set of registered managed objects in the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registeredObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/registeredObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registeredObjects"
        }
      ],
      "role": "symbol",
      "title": "registeredObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/registeredobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/retainsRegisteredObjects": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the context keeps strong references to all registered managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retainsRegisteredObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/retainsRegisteredObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retainsRegisteredObjects"
        }
      ],
      "role": "symbol",
      "title": "retainsRegisteredObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/retainsregisteredobjects"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Registering-and-fetching-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/fetch(_:)-38ys1",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/fetch(_:)-4xeoz",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/count(for:)-93zbm",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/registeredObject(for:)",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/object(with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/existingObject(with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/registeredObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/execute(_:)",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/refreshAllObjects()",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/retainsRegisteredObjects"
      ],
      "title": "Registering and fetching objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/title",
          "value": "NSManagedObjectContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1refreshAllObjects()/title",
          "value": "refreshAllObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1refreshAllObjects()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "refreshAllObjects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1retainsRegisteredObjects/title",
          "value": "retainsRegisteredObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1retainsRegisteredObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "retainsRegisteredObjects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1execute(_:)/title",
          "value": "executeRequest:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1execute(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeRequest:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestResult/title",
          "value": "NSFetchRequestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1registeredObject(for:)/title",
          "value": "objectRegisteredForID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1registeredObject(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectRegisteredForID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1existingObject(with:)/title",
          "value": "existingObjectWithID:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1existingObject(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "existingObjectWithID:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/title",
          "value": "NSFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1object(with:)/title",
          "value": "objectWithID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1object(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectWithID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1registeredObjects/title",
          "value": "registeredObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1registeredObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "registeredObjects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1count(for:)-93zbm/title",
          "value": "countForFetchRequest:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1count(for:)-93zbm/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "countForFetchRequest:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsmanagedobjectcontext/count(for:)-3r91z"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
