{
  "abstract": [
    {
      "text": "Keys to access details in user info dictionaries of managed object context notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreData",
    "externalID": "s:So22NSManagedObjectContextC8CoreDataE15NotificationKeyO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NotificationKey"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NotificationKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSManagedObjectContext.NotificationKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NotificationKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeletedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were marked for deletion during the previous event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeletedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeletedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeletedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeletedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsdeletedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were inserted into the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInsertedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInsertedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinsertedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedAllObjectsKey": {
      "abstract": [
        {
          "text": "A key that specifies that all objects in the context have been invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInvalidatedAllObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedAllObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInvalidatedAllObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInvalidatedAllObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinvalidatedallobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInvalidatedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInvalidatedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInvalidatedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinvalidatedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext": {
      "abstract": [
        {
          "text": "An object space to manipulate and track changes to managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey": {
      "abstract": [
        {
          "text": "Keys to access details in user info dictionaries of managed object context notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of deleted object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.deletedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/deletedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of deleted objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.deletedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/deletedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of inserted object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.insertedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/insertedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of inserted objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.insertedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/insertedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedAllObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of all invalidated objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatedAllObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedAllObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.invalidatedAllObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedallobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of invalidated object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.invalidatedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of invalidated objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.invalidatedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/invalidatedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/queryGeneration": {
      "abstract": [
        {
          "text": "A key for the token that indicates which generation of the persistent store Core Data is accessing",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryGeneration"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/queryGeneration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.queryGeneration",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/querygeneration"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of refreshed object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.refreshedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/refreshedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of refreshed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refreshedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.refreshedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/refreshedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjectIDs": {
      "abstract": [
        {
          "text": "A key for the set of updated object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatedObjectIDs"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjectIDs",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.updatedObjectIDs",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/updatedobjectids"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjects": {
      "abstract": [
        {
          "text": "A key for the context’s set of updated objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatedObjects"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjects",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey.updatedObjects",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey/updatedobjects"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didChangeObjectsNotification": {
      "abstract": [
        {
          "text": "A notification that posts when a context makes changes to its registered objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeObjectsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didChangeObjectsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didChangeObjectsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didchangeobjectsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didMergeChangesObjectIDsNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a context finishes merging changes from another notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMergeChangesObjectIDsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didMergeChangesObjectIDsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didMergeChangesObjectIDsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didmergechangesobjectidsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectIDsNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a context finishes saving changes to its managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSaveObjectIDsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectIDsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didSaveObjectIDsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didsaveobjectidsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectsNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a context completes a save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSaveObjectsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didSaveObjectsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didsaveobjectsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/willSaveObjectsNotification": {
      "abstract": [
        {
          "text": "A notification that posts before a context writes pending changes to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willSaveObjectsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/willSaveObjectsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "willSaveObjectsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/willsaveobjectsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRefreshedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were refreshed but were not dirtied in the scope of this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRefreshedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRefreshedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRefreshedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSRefreshedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsrefreshedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpdatedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpdatedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSUpdatedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsupdatedobjectskey"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave": {
      "abstract": [
        {
          "text": "A notification that posts after a context finishes writing unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextDidSave"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContextDidSave",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave": {
      "abstract": [
        {
          "text": "A notification that posts before a context writes unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextWillSave"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContextWillSave",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid": {
      "abstract": [
        {
          "text": "A notification that posts when there are changes to context’s registered managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextObjectsDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContextObjectsDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didChangeObjectsNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectsNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/willSaveObjectsNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave",
        "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSDeletedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSRefreshedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedAllObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didMergeChangesObjectIDsNotification",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectIDsNotification"
      ],
      "title": "Managing notifications"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/deletedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/insertedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedAllObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/invalidatedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/queryGeneration",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/refreshedObjects",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjectIDs",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey/updatedObjects"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRefreshedObjectsKey/title",
          "value": "NSRefreshedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRefreshedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRefreshedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedAllObjectsKey/title",
          "value": "NSInvalidatedAllObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedAllObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInvalidatedAllObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/title",
          "value": "NSManagedObjectContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUpdatedObjectsKey/title",
          "value": "NSUpdatedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUpdatedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpdatedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedObjectsKey/title",
          "value": "NSInvalidatedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInvalidatedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeletedObjectsKey/title",
          "value": "NSDeletedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeletedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeletedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInsertedObjectsKey/title",
          "value": "NSInsertedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInsertedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertedObjectsKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsmanagedobjectcontext/notificationkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
