{
  "abstract": [
    {
      "text": "Dependency information about the sample the cursor points to.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/dependencyInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MESampleCursor(py)dependencyInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dependencyInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@AVSampleCursorDependencyInfo",
        "text": "AVSampleCursorDependencyInfo"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dependencyInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dependencyInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dependencyInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@AVSampleCursorDependencyInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AVSampleCursorDependencyInfo",
              "text": "AVSampleCursorDependencyInfo"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value includes any valid flags set. Don’t implement this property if this kind of dependency information doesn’t make sense for the sequence of samples.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor": {
      "abstract": [
        {
          "text": "A protocol that defines the information to provide about samples within a track of a media asset, and enables stepping through samples in the track in decode or presentation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MESampleCursor"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MESampleCursor"
        }
      ],
      "role": "symbol",
      "title": "MESampleCursor",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleDuration": {
      "abstract": [
        {
          "text": "The decode duration of the sample at the current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDuration"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentSampleDuration",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/currentsampleduration"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleFormatDescription": {
      "abstract": [
        {
          "text": "The format description for the sample at the current position of the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleFormatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleFormatDescription"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentSampleFormatDescription",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/currentsampleformatdescription"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource": {
      "abstract": [
        {
          "text": "The duration of the playable content starting from the cursor position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource"
        }
      ],
      "role": "symbol",
      "title": "decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/decodetimeoflastsamplereachablebyforwardsteppingthatisalreadyloadedbybytesource"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeStamp": {
      "abstract": [
        {
          "text": "The decode timestamp (DTS) of the sample at the current position of the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decodeTimeStamp"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "decodeTimeStamp",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/decodetimestamp"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/dependencyInfo": {
      "abstract": [
        {
          "text": "Dependency information about the sample the cursor points to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorDependencyInfo",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/dependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "dependencyInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/dependencyinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/hevcDependencyInfo": {
      "abstract": [
        {
          "text": "Additional information that’s necessary to recover complete sample dependency information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevcDependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEHEVCDependencyInfo",
          "text": "MEHEVCDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/hevcDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hevcDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "hevcDependencyInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/hevcdependencyinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/presentationTimeStamp": {
      "abstract": [
        {
          "text": "The presentation timestamp (PTS) of the sample at the current position of the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/presentationTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationTimeStamp"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "presentationTimeStamp",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/presentationtimestamp"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/syncInfo": {
      "abstract": [
        {
          "text": "Decoder synchronization information about the sample the cursor points to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorSyncInfo",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/syncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "syncInfo"
        }
      ],
      "role": "symbol",
      "title": "syncInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor/syncinfo"
    },
    "doc://com.externally.resolved.symbol/c:@SA@AVSampleCursorDependencyInfo": {
      "abstract": [
        {
          "text": "A value for describing dependencies between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@AVSampleCursorDependencyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSampleCursorDependencyInfo",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVSampleCursorDependencyInfo"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-sample-cursor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/presentationTimeStamp",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeStamp",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleDuration",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleFormatDescription",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/syncInfo",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/hevcDependencyInfo",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource"
      ],
      "title": "Inspecting a sample cursor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dependencyInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-sample-cursor",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/presentationTimeStamp",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeStamp",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleDuration",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/currentSampleFormatDescription",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/syncInfo",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/hevcDependencyInfo",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor/decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource"
              ],
              "title": "Inspecting a sample cursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@AVSampleCursorDependencyInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@AVSampleCursorDependencyInfo",
                    "text": "AVSampleCursorDependencyInfo"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "dependencyInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource/title",
          "value": "decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decodeTimeOfLastSampleReachableByForwardSteppingThatIsAlreadyLoadedByByteSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1dependencyInfo/title",
          "value": "dependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1dependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1currentSampleFormatDescription/title",
          "value": "currentSampleFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1currentSampleFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@AVSampleCursorDependencyInfo/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor/title",
          "value": "MESampleCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1syncInfo/title",
          "value": "syncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1syncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "syncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1hevcDependencyInfo/title",
          "value": "hevcDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1hevcDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hevcDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1decodeTimeStamp/title",
          "value": "decodeTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1decodeTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decodeTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1presentationTimeStamp/title",
          "value": "presentationTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1presentationTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1currentSampleDuration/title",
          "value": "currentSampleDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor~1currentSampleDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mesamplecursor/dependencyinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mesamplecursor/dependencyinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
