{
  "abstract": [
    {
      "text": "Highlight content from your Apple TV application by building a full screen Top Shelf extension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/building-a-full-screen-top-shelf-extension"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Building a Full Screen Top Shelf Extension"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC 2019 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc19/211/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "0d8c2394f814/BuildingAFullScreenTopShelfExtension.zip": {
      "checksum": "0d8c2394f814756c00b7545aa4cb2ad698f64e7e28889924bdc6f40405d578d532ee27ae8c3184c59f848d2903c52a39482b3df316b8d8c23bf7d77e395bfa3f",
      "identifier": "0d8c2394f814/BuildingAFullScreenTopShelfExtension.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/0d8c2394f814/BuildingAFullScreenTopShelfExtension.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfContentProvider": {
      "abstract": [
        {
          "text": "The main interface for your Top Shelf app extension, which you use to provide content for the top shelf area of the tvOS Home Screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVTopShelfContentProvider"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfContentProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVTopShelfContentProvider"
        }
      ],
      "role": "symbol",
      "title": "TVTopShelfContentProvider",
      "type": "topic",
      "url": "/documentation/tvservices/tvtopshelfcontentprovider"
    },
    "doc://com.apple.tvservices/documentation/TVServices/legacy-extension": {
      "abstract": [
        {
          "text": "Help users discover your app by providing top shelf content and a description of your tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/legacy-extension",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Extension",
      "type": "topic",
      "url": "/documentation/tvservices/legacy-extension"
    },
    "https://developer.apple.com/videos/play/wwdc19/211/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc19/211/",
      "title": "211: Mastering the Living Room With tvOS",
      "titleInlineContent": [
        {
          "text": "211: Mastering the Living Room With tvOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc19/211/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "0d8c2394f814/BuildingAFullScreenTopShelfExtension.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Top-shelf-app-extensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfContentProvider",
        "doc://com.apple.tvservices/documentation/TVServices/legacy-extension"
      ],
      "title": "Top shelf app extensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Top-shelf-app-extensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVTopShelfContentProvider",
                "doc://com.apple.tvservices/documentation/TVServices/legacy-extension"
              ],
              "title": "Top shelf app extensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfContentProvider/title",
          "value": "TVTopShelfContentProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfContentProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfContentProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVTopShelfContentProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVTopShelfContentProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/building-a-full-screen-top-shelf-extension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/building-a-full-screen-top-shelf-extension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
