{
  "abstract": [
    {
      "text": "Store separate data for each user with the new Runs as Current User capability.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/supporting-multiple-users-in-your-tvos-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Supporting Multiple Users in Your tvOS App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC20 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2020/10645",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "You must run this sample code project on a physical device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "355a1ffe663d/SupportingMultipleUsersInYourTvOSApp.zip": {
      "checksum": "355a1ffe663dc9c36e4a105adaa97b3cff0791a9e8f65d8d2c47b27099a3debb946fb804752ddbf08ebb0c4a4a92f7ca38aae856324906e8dc8a3cad0af3e922",
      "identifier": "355a1ffe663d/SupportingMultipleUsersInYourTvOSApp.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/355a1ffe663d/SupportingMultipleUsersInYourTvOSApp.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager": {
      "abstract": [
        {
          "text": "An object that indicates how to store preferences for multiple people on a shared device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVUserManager"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVUserManager"
        }
      ],
      "role": "symbol",
      "title": "TVUserManager",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager"
    },
    "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles": {
      "abstract": [
        {
          "text": "Adapt the content of your app for the current viewer by using an entitlement and simplifying sign-in flows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles",
      "kind": "article",
      "role": "sampleCode",
      "title": "Mapping Apple TV users to app profiles",
      "type": "topic",
      "url": "/documentation/tvservices/mapping-apple-tv-users-to-app-profiles"
    },
    "doc://com.apple.tvservices/documentation/TVServices/personalizing-your-app-for-each-user-on-apple-tv": {
      "abstract": [
        {
          "text": "Use account-specific storage to segregate data on a multiuser system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/personalizing-your-app-for-each-user-on-apple-tv",
      "kind": "article",
      "role": "article",
      "title": "Personalizing Your App for Each User on Apple TV",
      "type": "topic",
      "url": "/documentation/tvservices/personalizing-your-app-for-each-user-on-apple-tv"
    },
    "https://developer.apple.com/videos/play/wwdc2020/10645": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2020/10645",
      "title": "10645: Support Multiple Users in Your tvOS App",
      "titleInlineContent": [
        {
          "text": "10645: Support Multiple Users in Your tvOS App",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2020/10645"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "355a1ffe663d/SupportingMultipleUsersInYourTvOSApp.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiple-users",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/personalizing-your-app-for-each-user-on-apple-tv",
        "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager"
      ],
      "title": "Multiple users"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Multiple-users",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/personalizing-your-app-for-each-user-on-apple-tv",
                "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles",
                "doc://com.apple.tvservices/documentation/TVServices/TVUserManager"
              ],
              "title": "Multiple users"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/title",
          "value": "TVUserManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/supporting-multiple-users-in-your-tvos-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/supporting-multiple-users-in-your-tvos-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
