{
  "abstract": [
    {
      "text": "An enumerated type that identifies the shape in which the content item should be displayed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVContentItemImageShape",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVContentItemImageShape"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVContentItemImageShape"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "TVContentItemImageShape"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/creationDate": {
      "abstract": [
        {
          "text": "The date when the content item was created, or the date when it was first broadcast, or some other kind of origination date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/creationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationDate"
        }
      ],
      "role": "symbol",
      "title": "creationDate",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitem/creationdate"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/duration": {
      "abstract": [
        {
          "text": "The amount of time required to play the media to completion.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitem/duration"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/expirationDate": {
      "abstract": [
        {
          "text": "The date when the user will no longer be able to access the item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expirationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/expirationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expirationDate"
        }
      ],
      "role": "symbol",
      "title": "expirationDate",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitem/expirationdate"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/imageShape": {
      "abstract": [
        {
          "text": "The intended aspect ratio or shape of the content image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageShape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVContentItemImageShape",
          "text": "TVContentItemImageShape"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/imageShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageShape"
        }
      ],
      "role": "symbol",
      "title": "imageShape",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitem/imageshape"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape": {
      "abstract": [
        {
          "text": "An enumerated type that identifies the shape in which the content item should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVContentItemImageShape"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShape"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV": {
      "abstract": [
        {
          "text": "The content is high-definition television content with a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "16:9",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HDTV"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeHDTV"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.HDTV",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/hdtv"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV": {
      "abstract": [
        {
          "text": "The content is standard-definition television content with a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "4:3",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SDTV"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeSDTV"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.SDTV",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/sdtv"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "80:27",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraWide"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeExtraWide"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.extraWide",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/extrawide"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/init(rawvalue:)"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none": {
      "abstract": [
        {
          "text": "The content has no particular shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeNone"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.none",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/none"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "2:3",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "poster"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapePoster"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.poster",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/poster"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "1:1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeSquare"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.square",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/square"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "8:3",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wide"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeWide"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.wide",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/wide"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Content-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/creationDate",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/duration",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/expirationDate",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/imageShape"
      ],
      "title": "Inspecting the Content Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVContentItemImageShape"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Content-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/creationDate",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/duration",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/expirationDate",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItem/imageShape"
              ],
              "title": "Inspecting the Content Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVContentItemImageShape"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1extraWide/title",
          "value": "TVContentItemImageShapeExtraWide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1extraWide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeExtraWide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1imageShape/title",
          "value": "imageShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1imageShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1wide/title",
          "value": "TVContentItemImageShapeWide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1wide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeWide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1poster/title",
          "value": "TVContentItemImageShapePoster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1poster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapePoster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1SDTV/title",
          "value": "TVContentItemImageShapeSDTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1SDTV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeSDTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1square/title",
          "value": "TVContentItemImageShapeSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape/title",
          "value": "TVContentItemImageShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1HDTV/title",
          "value": "TVContentItemImageShapeHDTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1HDTV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeHDTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1expirationDate/title",
          "value": "expirationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1expirationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expirationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1none/title",
          "value": "TVContentItemImageShapeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1creationDate/title",
          "value": "creationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItem~1creationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creationDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimageshape"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimageshape"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
