{
  "abstract": [
    {
      "text": "Methods for detecting cameras, getting metadata and thumbnails, handling access and capability changes, and performing other actions on connected cameras.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ICCameraDeviceDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ICCameraDeviceDelegate"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICCameraDeviceDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "ICCameraDeviceDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ICCameraDeviceDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)ICDeviceDelegate",
              "text": "ICDeviceDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice": {
      "abstract": [
        {
          "text": "An object that represents a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICCameraDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDevice"
        }
      ],
      "role": "symbol",
      "title": "ICCameraDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate": {
      "abstract": [
        {
          "text": "Methods for detecting cameras, getting metadata and thumbnails, handling access and capability changes, and performing other actions on connected cameras.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICCameraDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICCameraDeviceDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-8oukd": {
      "abstract": [
        {
          "text": "Tells the client when objects are added to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-8oukd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didAddItems:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDevice(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didadd:)-8oukd"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-9pnzo": {
      "abstract": [
        {
          "text": "Tells the client when an object is added to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-9pnzo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didAddItem:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didadd:)-9pnzo"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didCompleteDeleteFilesWithError:)": {
      "abstract": [
        {
          "text": "Tells the client when the camera completes a delete operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteDeleteFilesWithError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didCompleteDeleteFilesWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didCompleteDeleteFilesWithError:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:didCompleteDeleteFilesWithError:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didcompletedeletefileswitherror:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadata:for:error:)": {
      "abstract": [
        {
          "text": "Tells the client when the metadata requested for an item on a camera is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveMetadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadata:for:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didReceiveMetadata:forItem:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDevice(_:didReceiveMetadata:for:error:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didreceivemetadata:for:error:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadataFor:)": {
      "abstract": [
        {
          "text": "Tells the client when the metadata requested for an item on a camera is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveMetadataFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadataFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didReceiveMetadataForItem:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:didReceiveMetadataFor:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didreceivemetadatafor:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceivePTPEvent:)": {
      "abstract": [
        {
          "text": "Tells the client about a PTP event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceivePTPEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceivePTPEvent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didReceivePTPEvent:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDevice(_:didReceivePTPEvent:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didreceiveptpevent:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnail:for:error:)": {
      "abstract": [
        {
          "text": "Tells the client when the requested thumbnail is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveThumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnail:for:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didReceiveThumbnail:forItem:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDevice(_:didReceiveThumbnail:for:error:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didreceivethumbnail:for:error:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnailFor:)": {
      "abstract": [
        {
          "text": "Tells the client when the requested thumbnail is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveThumbnailFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnailFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didReceiveThumbnailForItem:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:didReceiveThumbnailFor:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didreceivethumbnailfor:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-4m5al": {
      "abstract": [
        {
          "text": "Tells the client when objects are removed from the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-4m5al",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didRemoveItems:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDevice(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didremove:)-4m5al"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-9rz34": {
      "abstract": [
        {
          "text": "Tells the client when an object is removed from the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-9rz34",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didRemoveItem:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didremove:)-9rz34"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRenameItems:)": {
      "abstract": [
        {
          "text": "Tells the client when one or more objects are renamed on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRenameItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRenameItems:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:didRenameItems:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDevice(_:didRenameItems:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:didrenameitems:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetMetadataOf:)": {
      "abstract": [
        {
          "text": "Tells the client when the camera is about to execute queued requests for the metadata of a specific item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldGetMetadataOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetMetadataOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:shouldGetMetadataOfItem:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:shouldGetMetadataOf:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:shouldgetmetadataof:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetThumbnailOf:)": {
      "abstract": [
        {
          "text": "Tells the client when the camera is about to execute queued requests for the thumbnail of a specific item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldGetThumbnailOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraItem",
          "text": "ICCameraItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetThumbnailOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDevice:shouldGetThumbnailOfItem:"
        }
      ],
      "role": "symbol",
      "title": "cameraDevice(_:shouldGetThumbnailOf:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevice(_:shouldgetthumbnailof:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidChangeCapability(_:)": {
      "abstract": [
        {
          "text": "Tells the client when a capability of a camera changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceDidChangeCapability"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidChangeCapability(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDeviceDidChangeCapability:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDeviceDidChangeCapability(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevicedidchangecapability(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidEnableAccessRestriction(_:)": {
      "abstract": [
        {
          "text": "Tells the client when an Apple device has been locked, and media is unavailable until the restriction has been removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceDidEnableAccessRestriction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidEnableAccessRestriction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDeviceDidEnableAccessRestriction:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDeviceDidEnableAccessRestriction(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevicedidenableaccessrestriction(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidRemoveAccessRestriction(_:)": {
      "abstract": [
        {
          "text": "Tells the client when an Apple device has been unlocked, paired to the host, and media is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceDidRemoveAccessRestriction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICDevice",
          "text": "ICDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidRemoveAccessRestriction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraDeviceDidRemoveAccessRestriction:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cameraDeviceDidRemoveAccessRestriction(_:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/cameradevicedidremoveaccessrestriction(_:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/deviceDidBecomeReady(withCompleteContentCatalog:)": {
      "abstract": [
        {
          "text": "Tells the client that the camera device is done enumerating its content and is ready to receive requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceDidBecomeReady"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCompleteContentCatalog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ICCameraDevice",
          "text": "ICCameraDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/deviceDidBecomeReady(withCompleteContentCatalog:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceDidBecomeReadyWithCompleteContentCatalog:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deviceDidBecomeReady(withCompleteContentCatalog:)",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevicedelegate/devicedidbecomeready(withcompletecontentcatalog:)"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile": {
      "abstract": [
        {
          "text": "An object that represents a file on a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICCameraFile"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraFile"
        }
      ],
      "role": "symbol",
      "title": "ICCameraFile",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccamerafile"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFolder": {
      "abstract": [
        {
          "text": "An object that represents a folder on a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICCameraFolder"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFolder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraFolder"
        }
      ],
      "role": "symbol",
      "title": "ICCameraFolder",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccamerafolder"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItem": {
      "abstract": [
        {
          "text": "An abstract class that represents a camera item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICCameraItem"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraItem"
        }
      ],
      "role": "symbol",
      "title": "ICCameraItem",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameraitem"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to device events and changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "ICDeviceDelegate",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicedelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Cameras",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItem",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFolder"
      ],
      "title": "Cameras"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Device-Readiness",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/deviceDidBecomeReady(withCompleteContentCatalog:)"
      ],
      "title": "Determining Device Readiness"
    },
    {
      "anchor": "Adding-Objects",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-8oukd",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-9pnzo"
      ],
      "title": "Adding Objects"
    },
    {
      "anchor": "Removing-Objects",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-4m5al",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didCompleteDeleteFilesWithError:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-9rz34"
      ],
      "title": "Removing Objects"
    },
    {
      "anchor": "Renaming-Objects",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRenameItems:)"
      ],
      "title": "Renaming Objects"
    },
    {
      "anchor": "Receiving-Metadata",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadata:for:error:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetMetadataOf:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadataFor:)"
      ],
      "title": "Receiving Metadata"
    },
    {
      "anchor": "Receiving-Thumbnails",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnail:for:error:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnailFor:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetThumbnailOf:)"
      ],
      "title": "Receiving Thumbnails"
    },
    {
      "anchor": "Responding-to-Capability-Changes",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidChangeCapability(_:)"
      ],
      "title": "Responding to Capability Changes"
    },
    {
      "anchor": "Responding-to-Access-Restrictions",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidEnableAccessRestriction(_:)",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidRemoveAccessRestriction(_:)"
      ],
      "title": "Responding to Access Restrictions"
    },
    {
      "anchor": "Responding-to-PTP-Events",
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceivePTPEvent:)"
      ],
      "title": "Responding to PTP Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICCameraDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-Device-Readiness",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/deviceDidBecomeReady(withCompleteContentCatalog:)"
              ],
              "title": "Determining Device Readiness"
            },
            {
              "anchor": "Adding-Objects",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-8oukd",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didAdd:)-9pnzo"
              ],
              "title": "Adding Objects"
            },
            {
              "anchor": "Removing-Objects",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-4m5al",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didCompleteDeleteFilesWithError:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRemove:)-9rz34"
              ],
              "title": "Removing Objects"
            },
            {
              "anchor": "Renaming-Objects",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didRenameItems:)"
              ],
              "title": "Renaming Objects"
            },
            {
              "anchor": "Receiving-Metadata",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadata:for:error:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetMetadataOf:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveMetadataFor:)"
              ],
              "title": "Receiving Metadata"
            },
            {
              "anchor": "Receiving-Thumbnails",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnail:for:error:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceiveThumbnailFor:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:shouldGetThumbnailOf:)"
              ],
              "title": "Receiving Thumbnails"
            },
            {
              "anchor": "Responding-to-Capability-Changes",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidChangeCapability(_:)"
              ],
              "title": "Responding to Capability Changes"
            },
            {
              "anchor": "Responding-to-Access-Restrictions",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidEnableAccessRestriction(_:)",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDeviceDidRemoveAccessRestriction(_:)"
              ],
              "title": "Responding to Access Restrictions"
            },
            {
              "anchor": "Responding-to-PTP-Events",
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDeviceDelegate/cameraDevice(_:didReceivePTPEvent:)"
              ],
              "title": "Responding to PTP Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Cameras",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItem",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFile",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraFolder"
              ],
              "title": "Cameras"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICCameraDeviceDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)ICDeviceDelegate",
                    "text": "ICDeviceDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDeviceDidRemoveAccessRestriction(_:)/title",
          "value": "cameraDeviceDidRemoveAccessRestriction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDeviceDidRemoveAccessRestriction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDeviceDidRemoveAccessRestriction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didRenameItems:)/title",
          "value": "cameraDevice:didRenameItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didRenameItems:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didRenameItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice/title",
          "value": "ICCameraDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFolder/title",
          "value": "ICCameraFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFolder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFolder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveThumbnail:for:error:)/title",
          "value": "cameraDevice:didReceiveThumbnail:forItem:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveThumbnail:for:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didReceiveThumbnail:forItem:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDeviceDidChangeCapability(_:)/title",
          "value": "cameraDeviceDidChangeCapability:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDeviceDidChangeCapability(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDeviceDidChangeCapability:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate/title",
          "value": "ICCameraDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItem/title",
          "value": "ICCameraItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:shouldGetThumbnailOf:)/title",
          "value": "cameraDevice:shouldGetThumbnailOfItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:shouldGetThumbnailOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:shouldGetThumbnailOfItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveMetadata:for:error:)/title",
          "value": "cameraDevice:didReceiveMetadata:forItem:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveMetadata:for:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didReceiveMetadata:forItem:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveMetadataFor:)/title",
          "value": "cameraDevice:didReceiveMetadataForItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveMetadataFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didReceiveMetadataForItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didAdd:)-8oukd/title",
          "value": "cameraDevice:didAddItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didAdd:)-8oukd/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didAddItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didRemove:)-9rz34/title",
          "value": "cameraDevice:didRemoveItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didRemove:)-9rz34/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didRemoveItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didAdd:)-9pnzo/title",
          "value": "cameraDevice:didAddItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didAdd:)-9pnzo/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didAddItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDeviceDidEnableAccessRestriction(_:)/title",
          "value": "cameraDeviceDidEnableAccessRestriction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDeviceDidEnableAccessRestriction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDeviceDidEnableAccessRestriction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1deviceDidBecomeReady(withCompleteContentCatalog:)/title",
          "value": "deviceDidBecomeReadyWithCompleteContentCatalog:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1deviceDidBecomeReady(withCompleteContentCatalog:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceDidBecomeReadyWithCompleteContentCatalog:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:shouldGetMetadataOf:)/title",
          "value": "cameraDevice:shouldGetMetadataOfItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:shouldGetMetadataOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:shouldGetMetadataOfItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didRemove:)-4m5al/title",
          "value": "cameraDevice:didRemoveItems:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didRemove:)-4m5al/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didRemoveItems:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceDelegate/title",
          "value": "ICDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didCompleteDeleteFilesWithError:)/title",
          "value": "cameraDevice:didCompleteDeleteFilesWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didCompleteDeleteFilesWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didCompleteDeleteFilesWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/title",
          "value": "ICCameraFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveThumbnailFor:)/title",
          "value": "cameraDevice:didReceiveThumbnailForItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceiveThumbnailFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didReceiveThumbnailForItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceivePTPEvent:)/title",
          "value": "cameraDevice:didReceivePTPEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDeviceDelegate~1cameraDevice(_:didReceivePTPEvent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraDevice:didReceivePTPEvent:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/iccameradevicedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/iccameradevicedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
